### PR TITLE
Fix jdbc ResultSet getBoolean throw ClassCastException

### LINKED ISSUE #16296: Trino jdbc getBoolean method throw ClassCastException
When I used jdbc type to connect trino, the `ResultSet.getBoolean` method throw ClassCastException. I expect it is SQLException.

### PR DESCRIPTION
**Pull request by Heltman**
## Description
As JDBC specification, if a data conversion fails, then a SQLException will be raised. But getBoolean will cause a ClassCastException.

Fixes #16296

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

File: client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java [hunk 1]
```diff
@@ -260,7 +260,13 @@ public boolean getBoolean(int columnIndex)
             throws SQLException
     {
         Object value = column(columnIndex);
-        return (value != null) ? (Boolean) value : false;
+        if (value == null) {
+            return false;
+        }
+        if (value instanceof Boolean) {
```
Comment (wendigo) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java:266]: nit:
```
if (value instanceof Boolean booleanValue) {
	return booleanValue;
}
```

**Review by wendigo — APPROVED** [review]

File: client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java [hunk 2]
```diff
@@ -260,7 +260,13 @@ public boolean getBoolean(int columnIndex)
...
+            return (Boolean) value;
+        }
+        throw new SQLException("Value is not a boolean: " + value);
```
Comment (ebyhr) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java:269]: Can we add a test? Probably in `BaseTestJdbcResultSet`.

Comment (Heltman) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java:269]: @ebyhr I had add asimple test. I think it's enough.

**Review by ebyhr — APPROVED** [review]
