### PR TITLE
Skip dropping testing Glue database when create time is within threshold

### LINKED ISSUE #19100: Flaky TestIcebergGlueCatalogAccessOperations
```
Error:  Failures: 
Error:    TestIcebergGlueCatalogAccessOperations.cleanUpSchema:125 » QueryFailed line 1:1: Schema 'iceberg.test_schema_pw0y3fdm00' does not exist
Error:    TestIcebergGlueCatalogAccessOperations.testJoin:319->AbstractTestQueryFramework.assertUpdate:412->AbstractTestQueryFramework.assertUpdate:417 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testRefreshMaterializedView:300->AbstractTestQueryFramework.assertUpdate:402->AbstractTestQueryFramework.assertUpdate:407 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testSelect:196->AbstractTestQueryFramework.assertUpdate:402->AbstractTestQueryFramework.assertUpdate:407 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testSelectFromMaterializedView:264->AbstractTestQueryFramework.assertUpdate:402->AbstractTestQueryFramework.assertUpdate:407 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testSelectFromMaterializedViewWithFilter:282->AbstractTestQueryFramework.assertUpdate:412->AbstractTestQueryFramework.assertUpdate:417 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testSelectFromView:228->AbstractTestQueryFramework.assertUpdate:402->AbstractTestQueryFramework.assertUpdate:407 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testSelectFromViewWithFilter:246->AbstractTestQueryFramework.assertUpdate:412->AbstractTestQueryFramework.assertUpdate:417 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testSelectSystemTable:401->AbstractTestQueryFramework.assertUpdate:412->AbstractTestQueryFramework.assertUpdate:417 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testSelectWithFilter:212->AbstractTestQueryFramework.assertUpdate:412->AbstractTestQueryFramework.assertUpdate:417 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testSelfJoin:337->AbstractTestQueryFramework.assertUpdate:412->AbstractTestQueryFramework.assertUpdate:417 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testShowStatsForTable:369->AbstractTestQueryFramework.assertUpdate:412->AbstractTestQueryFramework.assertUpdate:417 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testShowStatsForTableWithFilter:385->AbstractTestQueryFramework.assertUpdate:412->AbstractTestQueryFramework.assertUpdate:417 » QueryFailed Schema test_schema_pw0y3fdm00 not found
Error:    TestIcebergGlueCatalogAccessOperations.testUse:137->assertGlueMetastoreApiInvocations:591->assertInvocations:619 » QueryFailed Schema does not exist: iceberg.test_schema_pw0y3fdm00
```

https://github.com/trinodb/trino/actions/runs/6242294586/job/16946074046

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

I suppose TestDatabricksWithGlueMetastoreCleanUp affected TestIcebergGlueCatalogAccessOperations. 
There were many Glue `DeleteDatabase` calls in CloudTrail when TestIcebergGlueCatalogAccessOperations was running. 

Fixes #19100

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java [hunk 1]
```diff
@@ -99,9 +101,13 @@ private void cleanSchema(String schema, long startTime, AWSGlueAsync glueClient)
         }
         log.info("Dropped %d tables in schema %s", droppedTablesCount, schema);
         if (!schema.equals("default") && findAllTablesInSchema(schema).isEmpty()) {
+            Database database = glueClient.getDatabase(new GetDatabaseRequest().withName(schema)).getDatabase();
+            Instant createTime = database.getCreateTime().toInstant();
             try {
-                onTrino().executeQuery("DROP SCHEMA IF EXISTS " + schema);
-                log.info("Dropped schema %s", schema);
+                if (createTime.isBefore(SCHEMA_CLEANUP_THRESHOLD)) {
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java:107]: If we are not going to delete the schema, we should also abstain from deleting tables in that schema

**Review by findinpath — APPROVED** [review]

**Review by findinpath — APPROVED** [review]

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java [hunk 2]
```diff
@@ -69,6 +71,12 @@ public void testCleanUpOldTablesUsingDelta()
 
     private void cleanSchema(String schema, long startTime, AWSGlueAsync glueClient)
     {
+        Database database = glueClient.getDatabase(new GetDatabaseRequest().withName(schema)).getDatabase();
+        if (database.getCreateTime().toInstant().isAfter(SCHEMA_CLEANUP_THRESHOLD)) {
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java:75]: nit, pre-existing, SCHEMA_CLEANUP_THRESHOLD shouldn't be a static constant
it doesn't matter when class was loaded in current JVM. it matters when cleanup code was invoked.

**Review by findepi — APPROVED** [review]
