### PR TITLE
Fix DELETE and UPDATE for connectors that subsume filters

### LINKED ISSUE #7290: ORC ACID DELETE ignores partition filter, deleting too much
```
trino:default> CREATE TABLE nation WITH (transactional=true, partitioned_by=ARRAY['regionkey']) AS SELECT nationkey, regionkey FROM tpch.tiny.nation;
CREATE TABLE: 25 rows
```

```
trino:default> SELECT * FROM nation ORDER BY regionkey, nationkey;
 nationkey | regionkey
-----------+-----------
         0 |         0
         5 |         0
        14 |         0
        15 |         0
        16 |         0
         1 |         1
         2 |         1
         3 |         1
        17 |         1
        24 |         1
         8 |         2
         9 |         2
        12 |         2
        18 |         2
        21 |         2
         6 |         3
         7 |         3
        19 |         3
        22 |         3
        23 |         3
         4 |         4
        10 |         4
        11 |         4
        13 |         4
        20 |         4
(25 rows)
```

```
trino:default> DELETE FROM nation WHERE regionkey = 4 AND nationkey % 10 = 3;
DELETE: 3 rows
```
-- this should have deleted 1 row, not 3

```
trino:default> SELECT * FROM nation ORDER BY regionkey, nationkey;
 nationkey | regionkey
-----------+-----------
         0 |         0
         5 |         0
        14 |         0
        15 |         0
        16 |         0
         1 |         1
         2 |         1
        17 |         1
        24 |         1
         8 |         2
         9 |         2
        12 |         2
        18 |         2
        21 |         2
         6 |         3
         7 |         3
        19 |         3
        22 |         3
         4 |         4
        10 |         4
        11 |         4
        20 |         4
(22 rows)
```

```
trino:default> DELETE FROM nation WHERE regionkey = 4 AND nationkey < 100;
DELETE: 22 rows
```

```
trino:default> SELECT * FROM nation ORDER BY regionkey, nationkey;
 nationkey | regionkey
-----------+-----------
(0 rows)
```

Relates to https://github.com/trinodb/trino/issues/7291 and https://github.com/trinodb/trino/issues/7300

### LINKED ISSUE #7300: ORC ACID UPDATE ignores partition filter, updating too much
```
trino:default> CREATE TABLE tpch_nation AS TABLE tpch.tiny.nation;
CREATE TABLE: 25 rows
```

```
0: jdbc:hive2://localhost:10000/default> CREATE TABLE nation (nationkey bigint, name string) PARTITIONED BY (regionkey bigint) STORED AS ORC TBLPROPERTIES ('transactional' = 'true');

0: jdbc:hive2://localhost:10000/default> INSERT INTO nation (nationkey, name, regionkey) SELECT nationkey, name, regionkey FROM tpch_nation;
```

```
trino:default> UPDATE nation SET nationkey = nationkey + 100 WHERE regionkey = 4 AND nationkey % 10 = 3;
UPDATE: 3 rows
```

```
trino:default> SELECT * FROM nation;
 nationkey |      name      | regionkey
-----------+----------------+-----------
         8 | INDIA          |         2
         9 | INDONESIA      |         2
        12 | JAPAN          |         2
        18 | CHINA          |         2
        21 | VIETNAM        |         2
         0 | ALGERIA        |         0
         5 | ETHIOPIA       |         0
        14 | KENYA          |         0
        15 | MOROCCO        |         0
        16 | MOZAMBIQUE     |         0
       123 | UNITED KINGDOM |         3                                *************
       103 | CANADA         |         1                                *************
       113 | JORDAN         |         4                                *************
         6 | FRANCE         |         3
         1 | ARGENTINA      |         1
         7 | GERMANY        |         3
        19 | ROMANIA        |         3
         2 | BRAZIL         |         1
        17 | PERU           |         1
        24 | UNITED STATES  |         1
        22 | RUSSIA         |         3
         4 | EGYPT          |         4
        10 | IRAN           |         4
        11 | IRAQ           |         4
        20 | SAUDI ARABIA   |         4
(25 rows)
```

relates to https://github.com/trinodb/trino/issues/7290

### PR DESCRIPTION
**Pull request by electrum**
Fix #7290, fix #7300

### CODE REVIEW

**Comment by electrum** [comment]
I tried to add a test for update
```java
@Test(groups = HIVE_TRANSACTIONAL, timeOut = TEST_TIMEOUT)
public void testUpdatePartitionedTable()
{
    withTemporaryTable("update_partitioned", true, true, NONE, tableName -> {
        onPresto().executeQuery(format("CREATE TABLE %s WITH (transactional = true, partitioned_by = ARRAY['regionkey'])" +
                " AS SELECT nationkey, name, regionkey FROM tpch.tiny.nation", tableName));

        verifySelectForPrestoAndHive("SELECT COUNT(*) FROM " + tableName, "nationkey < 100", row(25));

        onPresto().executeQuery(format("UPDATE %s SET nationkey = nationkey + 333 WHERE regionkey = 4 AND nationkey %% 10 = 3", tableName));
        verifySelectForPrestoAndHive("SELECT COUNT(*) FROM " + tableName, "nationkey < 100", row(24));

        onPresto().executeQuery(format("UPDATE %s SET nationkey = nationkey + 333 WHERE regionkey = 4 AND nationkey < 100", tableName));
        verifySelectForPrestoAndHive("SELECT COUNT(*) FROM " + tableName, "nationkey < 100", row(20));
    });
}
```
But it fails with
```
Caused by: io.trino.spi.TrinoException: page doesn't have enough columns
	at io.trino.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:331)
	at io.trino.plugin.hive.HiveUpdatablePageSource.getNextPage(HiveUpdatablePageSource.java:237)
	at io.trino.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:376)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	...
Caused by: java.lang.IllegalArgumentException: page doesn't have enough columns
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at io.trino.plugin.hive.HiveUpdateProcessor.createUpdateRowBlock(HiveUpdateProcessor.java:123)
	at io.trino.plugin.hive.orc.OrcPageSource$UpdatedRowAdaptation.block(OrcPageSource.java:358)
	at io.trino.plugin.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:145)
	at io.trino.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:274)
	... 38 more
```

**Comment by hashhar** [comment]
@electrum see https://github.com/trinodb/trino/issues/7298 (and https://github.com/trinodb/trino/issues/6281).

**Comment by findepi** [comment]
> Caused by: io.trino.spi.TrinoException: page doesn't have enough columns

you need to create a table via Hive for that

File: core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java [hunk 1]
```diff
@@ -225,6 +235,29 @@ private WriterTarget createWriterTarget(WriterTarget target)
             throw new IllegalArgumentException("Unhandled target type: " + target.getClass().getSimpleName());
         }
 
+        private TableHandle findTableScanHandle(PlanNode node)
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:238]: The logic here seems duplicated over `rewriteModifyTableScan`.
Can we somehow avoid the duplication?

it looks tongue-in-cheek to traverse the plan to find the TH from the TableScan so that we can call beginDelete and traverse the plan back and put a new TH into the TableScan. 

Perhaps instead of adding new method, remove the TH param from `rewriteModifyTableScan` and instead pass some information or function, what to do when TableScan is eventually found.

File: core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java [hunk 2]
```diff
@@ -176,10 +176,20 @@ public WriterTarget getTarget(PlanNode node)
                 return ((TableWriterNode) node).getTarget();
             }
             if (node instanceof DeleteNode) {
-                return ((DeleteNode) node).getTarget();
+                DeleteNode deleteNode = (DeleteNode) node;
+                DeleteTarget delete = deleteNode.getTarget();
+                return new DeleteTarget(
+                        findTableScanHandle(deleteNode.getSource()),
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:182]: We should also fix here
https://github.com/trinodb/trino/blob/075276b7b63dff9d68ce0afa681cf833b9cbf205/core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java#L480

-- the TH stored there is unused until here, and having it error-prone, it is IMO the sole reason we have the bugs being fixed here

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java [hunk 3]
```diff
@@ -1263,6 +1263,23 @@ public void testInsertDeletUpdateWithPrestoAndHive()
         });
     }
 
+    @Test(groups = HIVE_TRANSACTIONAL, timeOut = TEST_TIMEOUT)
+    public void testDeletePartitionedTable()
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1267]: There already is `testBucketedPartitionedDelete` which you can use, or add `testUnbucketedPartitionedDelete` (per existing convention in the class)

see also https://github.com/trinodb/trino/pull/7299

**Comment by findepi** [comment]
Failure seems related

```
2021-03-16T08:04:51.3926646Z tests               | 2021-03-16 13:49:51 INFO: FAILURE     /    io.trino.tests.hive.TestHiveTransactionalTable.testAcidUpdatePartitioned (Groups: hive_transactional) took 2.5 seconds
2021-03-16T08:04:51.3929374Z tests               | 2021-03-16 13:49:51 SEVERE: Failure cause:
2021-03-16T08:04:51.3930367Z tests               | java.lang.AssertionError: [onPresto] Could not find rows:
2021-03-16T08:04:51.3931142Z tests               | [18, S1, 7]
2021-03-16T08:04:51.3931561Z tests               | 
2021-03-16T08:04:51.3932066Z tests               | actual rows:
2021-03-16T08:04:51.3932481Z tests               | [17, S1, 7]
2021-03-16T08:04:51.3932971Z tests               | [24, T2, 3]
2021-03-16T08:04:51.3933477Z tests               | [13, T1, 3]
2021-03-16T08:04:51.3935278Z tests               | 	at io.trino.tests.hive.TestHiveTransactionalTable.verifySelect(TestHiveTransactionalTable.java:1612)
2021-03-16T08:04:51.3939657Z tests               | 	at io.trino.tests.hive.TestHiveTransactionalTable.verifySelectForPrestoAndHive(TestHiveTransactionalTable.java:1602)
2021-03-16T08:04:51.3943818Z tests               | 	at io.trino.tests.hive.TestHiveTransactionalTable.lambda$testAcidUpdatePartitioned$48(TestHiveTransactionalTable.java:1188)
2021-03-16T08:04:51.3974350Z tests               | 	at io.trino.tests.hive.TestHiveTransactionalTable.withTemporaryTable(TestHiveTransactionalTable.java:1334)
2021-03-16T08:04:51.3979325Z tests               | 	at io.trino.tests.hive.TestHiveTransactionalTable.testAcidUpdatePartitioned(TestHiveTransactionalTable.java:1179)
```

-- looks like the test for UPDATE is already there

File: core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java (hunk 1 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:238]: I agree with your observation, but these methods are called from different places. `getTarget` is called from `visitTableFinish` and `rewriteModifyTableScan` is called from `visitDelete`. With the current plan structure, the target is stored in the `TableFinishNode`, but we modify the table scan in the `DeleteNode`, using the target saved in the visitor context.

There's probably a way to clean this up, but that's outside the scope of fixing this bug.

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java (hunk 3 above)
Comment (electrum) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1267]: I wanted to have the exact test case from the issue.

File: core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java (hunk 2 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:182]: @martint and I had the same thought. I'll see how feasible it is to change this.

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java [hunk 4]
```diff
@@ -1280,6 +1280,24 @@ public void testDeletePartitionedTable()
...
+    public void testUpdatePartitionedTable()
+    {
+        withTemporaryTable("update_partitioned", true, true, NONE, tableName -> {
+            onHive().executeQuery(format("CREATE TABLE %s (nationkey bigint, name string) PARTITIONED BY (regionkey bigint) " +
+                    "STORED AS ORC TBLPROPERTIES ('transactional' = 'true')", tableName));
+            onPresto().executeQuery(format("INSERT INTO %s SELECT nationkey, name, regionkey FROM tpch.tiny.nation", tableName));
+
+            verifySelectForPrestoAndHive("SELECT COUNT(*) FROM " + tableName, "nationkey < 100", row(25));
+
+            onPresto().executeQuery(format("UPDATE %s SET nationkey = nationkey + 333 WHERE regionkey = 4 AND nationkey %% 10 = 3", tableName));
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1293]: You can use `nationkey < 100` to avoid `%%`.
it'd expose the bug the same way.

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java [hunk 5]
```diff
@@ -1280,6 +1280,24 @@ public void testDeletePartitionedTable()
...
 
+    @Test(groups = HIVE_TRANSACTIONAL, timeOut = TEST_TIMEOUT)
+    public void testUpdatePartitionedTable()
+    {
+        withTemporaryTable("update_partitioned", true, true, NONE, tableName -> {
+            onHive().executeQuery(format("CREATE TABLE %s (nationkey bigint, name string) PARTITIONED BY (regionkey bigint) " +
+                    "STORED AS ORC TBLPROPERTIES ('transactional' = 'true')", tableName));
+            onPresto().executeQuery(format("INSERT INTO %s SELECT nationkey, name, regionkey FROM tpch.tiny.nation", tableName));
+
+            verifySelectForPrestoAndHive("SELECT COUNT(*) FROM " + tableName, "nationkey < 100", row(25));
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1291]: nit: lowercase `count`

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java [hunk 6]
```diff
@@ -1280,6 +1280,24 @@ public void testDeletePartitionedTable()
         });
     }
 
+    @Test(groups = HIVE_TRANSACTIONAL, timeOut = TEST_TIMEOUT)
+    public void testUpdatePartitionedTable()
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1284]: I don't feel like this test is needed over `testAcidUpdatePartitioned`

if you keep it, please give it a name that can distinguish it.
currently the two have names saying the same ("updated partitioned table"), just with different words

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java [hunk 7]
```diff
@@ -1263,6 +1263,41 @@ public void testInsertDeletUpdateWithPrestoAndHive()
...
     }
 
+    @Test(groups = HIVE_TRANSACTIONAL, timeOut = TEST_TIMEOUT)
+    public void testDeletePartitionedTable()
+    {
+        withTemporaryTable("delete_partitioned", true, true, NONE, tableName -> {
+            onPresto().executeQuery(format("CREATE TABLE %s WITH (transactional = true, partitioned_by = ARRAY['regionkey'])" +
+                    " AS SELECT nationkey, name, regionkey FROM tpch.tiny.nation", tableName));
+
+            verifySelectForPrestoAndHive("SELECT COUNT(*) FROM " + tableName, "TRUE", row(25));
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1273]: nit: lowercase `count` and `true`

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java [hunk 8]
```diff
@@ -1263,6 +1263,41 @@ public void testInsertDeletUpdateWithPrestoAndHive()
...
+
+            onPresto().executeQuery(format("DELETE FROM %s WHERE regionkey = 4 AND nationkey %% 10 = 3", tableName));
+            verifySelectForPrestoAndHive("SELECT COUNT(*) FROM " + tableName, "TRUE", row(24));
+
+            onPresto().executeQuery(format("DELETE FROM %s WHERE regionkey = 4", tableName));
+            verifySelectForPrestoAndHive("SELECT COUNT(*) FROM " + tableName, "TRUE", row(20));
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1279]: You can add a comment here
```
// TODO (https://github.com/trinodb/trino/issues/7291) this currently removes partition directories, should create delete_delta files
```

(optional)

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java (hunk 3 above)
Comment (findepi) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1267]: it's good for development,  but these tests are slow... whatever

File: core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java (hunk 2 above)
Comment (findepi) [reply core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:182]: Maybe `DeleteTarget.tableHandle` can be made Optional (sounds like taking a shortcut, i know ...)

**Review by findepi — APPROVED** [review]

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java (hunk 4 above)
Comment (electrum) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1293]: That would match all rows, rather than specific ones. You're right that it would expose the bug, I feel like updating all rows is somewhat of a special case and thus a different test.

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java (hunk 6 above)
Comment (electrum) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1284]: You're right, we can remove it

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java (hunk 4 above)
Comment (electrum) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1293]: Removed the test

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java (hunk 8 above)
Comment (electrum) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java:1279]: I'll leave this alone, since that bug is not specific to this test

File: core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java (hunk 2 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java]: I changed it to optional.

File: core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java [hunk 9]
```diff
@@ -263,20 +298,17 @@ private PlanNode rewriteModifyTableScan(PlanNode node, TableHandle handle)
 
     public static class Context
```
Comment (martint) [inline core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:299]: Since the `Context` now just holds an `Optional<WriterTarget>`, the visitor could just use `Optional<WriterTarget>` as the context type and get rid of this class.

**Review by martint — APPROVED** [review]

File: core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java (hunk 9 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:299]: `Optional` is not mutable. We could use `AtomicReference<WriterTarget>`, but would still need a place to put the sanity checks that are currently in the `Context` class, so I don't think that's an improvement.

Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:299]: It doesn't need to be mutable. You just need to pass the proper instance when visiting the child.

Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:299]: Where it does 

```java
child = child.accept(this, context);
```

you'd do this instead:

```java
child = child.accept(this, Optional.of(newTarget);
```

In the `optimize()` method:

```java
return SimplePlanRewriter.rewriteWith(new Rewriter(session), plan, Optional.empty());
```

Comment (electrum) [reply core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java:299]: Makes sense. I'll update it

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java [hunk 10]
```diff
@@ -203,7 +203,7 @@ public String getPartitionName()
 
         int statementId = 0;
 
-        if (transaction.isDelete()) {
+        if (transaction.isDelete() || transaction.isUpdate()) {
```
Comment (findepi) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java:206]: Thanks for adding explanation https://github.com/trinodb/trino/issues/7186#issuecomment-802439753

> * Fix allocation of statement IDs for ACID tables, which could result in query failure or
  data loss due to creating multiple delta files with the same name. ({issue}`7302`)

Sounds like this should be tested.
