### PR TITLE
Fix TEXTFILE and RCTEXT string escape of an escape character

### LINKED ISSUE #18215: Native TEXTFILE reader produces incorrect results when varchars contain the field separator escape character
Here's a test case:

```
    @Test
    public void testTextfileFieldSeparator()
    {
        List<String> specialCharacterValues = ImmutableList.of(
                "1, 'a,comma'",
                "2, 'a|pipe'",
                "3, 'an''escaped quote'",
                "4, 'a~null encoding'");

        Session withHadoopReaders = Session.builder(getSession())
                .setCatalogSessionProperty("hive", "json_native_reader_enabled", "false")
                .setCatalogSessionProperty("hive", "text_file_native_reader_enabled", "false")
                .build();
        Session withNativeReaders = Session.builder(getSession())
                .setCatalogSessionProperty("hive", "json_native_reader_enabled", "true")
                .setCatalogSessionProperty("hive", "text_file_native_reader_enabled", "true")
                .build();

        try (TestTable table = new TestTable(
                getQueryRunner()::execute,
                "test_textfile_field_separator",
                "(id INT, varchar_t VARCHAR) WITH (format = 'TEXTFILE', textfile_field_separator=',', textfile_field_separator_escape='|', null_format='~')",
                specialCharacterValues)) {
            assertQuery(withHadoopReaders, "SELECT id FROM " + table.getName() + " WHERE varchar_t = 'a,comma'", "VALUES 1");
            assertQuery(withHadoopReaders, "SELECT id FROM " + table.getName() + " WHERE varchar_t = 'a|pipe'", "VALUES 2");
            assertQuery(withHadoopReaders, "SELECT id FROM " + table.getName() + " WHERE varchar_t = 'an''escaped quote'", "VALUES 3");
            assertQuery(withHadoopReaders, "SELECT id FROM " + table.getName() + " WHERE varchar_t = 'a~null encoding'", "VALUES 4");

            assertQuery(withNativeReaders, "SELECT id FROM " + table.getName() + " WHERE varchar_t = 'a,comma'", "VALUES 1");
            // This assertion fails
            assertQuery(withNativeReaders, "SELECT id FROM " + table.getName() + " WHERE varchar_t = 'a|pipe'", "VALUES 2");
            assertQuery(withNativeReaders, "SELECT id FROM " + table.getName() + " WHERE varchar_t = 'an''escaped quote'", "VALUES 3");
            assertQuery(withNativeReaders, "SELECT id FROM " + table.getName() + " WHERE varchar_t = 'a~null encoding'", "VALUES 4");
        }
    }
```

### PR DESCRIPTION
**Pull request by dain**
Fixes #18215

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix TEXTFILE and RCTEXT handling of an escaped escape character. ({issue}`18215`)
```

### CODE REVIEW

File: lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/simple/TestSimpleFormat.java [hunk 1]
```diff
@@ -1401,7 +1404,12 @@ private static Slice writeHiveLine(List<Column> columns, Slice line, TextEncodin
             throws SerDeException
     {
         List<Object> values = readHive(columns, line, options);
+        return writeHiveLine(columns, values, options);
+    }
 
+    private static Slice writeHiveLine(List<Column> columns, List<Object> values, TextEncodingOptions options)
```
Comment (electrum) [inline lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/simple/TestSimpleFormat.java:1410]: Looks like introducing this method is not necessary?

**Review by electrum — APPROVED** [review]
