### PR TITLE
Fix overly restrictive correctness checks in native line readers

### LINKED ISSUE #16492: CSV headers broken in Hive tables
Hi, Since the upgrade to version 409 i started to have this errors when creating an Hive table based on CSV files.
```
CREATE TABLE hive.{schema}.{table} (
    field1 VARCHAR,
    field2 VARCHAR
)
WITH (
  format = 'CSV',
  skip_header_line_count = 1,  -- THIS LINE IS THE PROBLEM but is required to skip column headers
  external_location = '<storage_location>'
)
```

```
Error: TrinoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="Header not supported for a split file", query_id=20230309_180613_62604_ud47x)
```

I suspect it has to do with the [implementation of a native CSV writer/reader](https://github.com/trinodb/trino/pull/15918), but I’m not sure what the breaking change is, or how to resolve it. Could you please have a look?

### LINKED ISSUE #16510: Queries fail while using native hive formats
Since version `409`  (with https://github.com/trinodb/trino/pull/15918) queries fail on `java.lang.IllegalArgumentException: Compressed files are not splittable` while using  configuration `{$format}.native-reader.enabled=true`

Issue happens when reading external hive tables and only during the time that the underline files are updated.

Issue doesn't happen when the underlined files are not updated.
It also doesn’t happen when
`native-reader.enabled=false`.

External table for example:
```
CREATE TABLE hive.temp.events (
   event_name varchar,
   event_at varchar,
   env varchar,
   payload varchar
)
WITH (
   csv_escape = U&'\0000',
   csv_separator = ',',
   external_location = 's3a://bucket-name/events/last_hour',
   format = 'CSV'
)
```

Files in `s3://bucket-name/events/last_hour`
```
-- Each one minute, a relevant file is replaced. 

s3://bucket-name/events/last_hour/00.gz
s3://bucket-name/events/last_hour/01.gz
s3://bucket-name/events/last_hour/02.gz
.
.
.
s3://bucket-name/events/last_hour/59.gz
```

Query using `events` table:
```
SELECT count(*) 
FROM events
WHERE event_name = 'some_event'
AND json_extract_scalar(payload, '$.status') = 'failed'
```

When `csv.native-reader.enabled=false` no issue happen 

When `csv.native-reader.enabled=true` (the default) queries fail from time to time:

```
io.trino.spi.TrinoException: Error opening Hive split s3a://bucket-name/events/last_hour/59.gz (offset=0, length=18736): Compressed files are not splittable
	at io.trino.plugin.hive.line.LinePageSourceFactory.createPageSource(LinePageSourceFactory.java:191)
	at io.trino.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:216)
	at io.trino.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:154)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:266)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:194)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:360)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:347)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:241)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:262)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:256)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:413)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:146)
	at io.trino.operator.Driver.processInternal(Driver.java:394)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:297)
	at io.trino.operator.Driver.tryWithLock(Driver.java:689)
	at io.trino.operator.Driver.process(Driver.java:289)
	at io.trino.operator.Driver.processForDuration(Driver.java:260)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_409____20230312_083525_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Compressed files are not splittable
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at io.trino.hive.formats.line.text.TextLineReaderFactory.createLineReader(TextLineReaderFactory.java:71)
	at io.trino.plugin.hive.line.LinePageSourceFactory.createPageSource(LinePageSourceFactory.java:179)
	... 31 more
```

cc: @dain @electrum

### PR DESCRIPTION
**Pull request by dain**
## Description
Do not verify length when determining if a file is split and instead only check that start offset is zero.  This is because Hive supports replacing files during a query, and users take advantage of this.  This check is still correct, because a split file necessarily has second split that will have a non-zero start offset.

For all native file formats, hardcode the handling of the isSplittable check as it is a behavior of the code and not the file format.

Fixes #16492 
Fixes #16510 

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Hive
* Fix support for text formats with single header row when the file is split. ({issue}`16492`)
* Fix support for reading text formats when the file is replaced during the query. ({issue}`16510`)
```

### CODE REVIEW

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/LinePageSourceFactory.java [hunk 1]
```diff
@@ -117,12 +117,12 @@ public Optional<ReaderPageSource> createPageSource(
 
         // get header and footer count
         int headerCount = getHeaderCount(schema);
-        if (headerCount > 0) {
-            checkArgument(estimatedFileSize == start + length, "Header not supported for a split file");
+        if (headerCount > 1) {
+            checkArgument(start == 0, "Multiple header rows is not supported for a split file");
```
Comment (electrum) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/LinePageSourceFactory.java:121]: Grammar: is -> are

Or remove the word

**Review by electrum — APPROVED** [review]
