### PR TITLE
Prevent table creation on non-empty location for Iceberg tables

### LINKED ISSUE #12573: Iceberg `CREATE TABLE` statement allows to create a table on a location already used by another Iceberg table
On Iceberg with default settings following statements result in a location being shared by two tables.

```
CREATE TABLE T1 AS SELECT 1 as a;
ALTER TABLE T1 RENAME TO T2;
CREATE TABLE T1 AS SELECT 1 as a;
```

If later on one of these tables is dropped, it will result in data and metadata loss on the other table as the location is shared.

```
DROP TABLE t1;
SELECT * FROM t2;
```

Results in following exception:

```
13:33:35  FAILED  [SELECT - 0 rows, 91.531 secs]  [Code: 65536, SQL State: ]  Query failed (#20220527_113335_00012_44zsa): Failed to read file: HdfsInputFile{delegate=s3a://datalake/t1/metadata/00000-ac141ee9-369f-4b5b-996d-b88ef979445a.metadata.json, identity=ConnectorIdentity{user='admin', groups=[], principal=admin, enabledSystemroles=[], extraCredentials=[]}}  
select * from t2;
```

We should prevent the user from getting into this situation by throwing an exception on table creation on a non-empty path and suggesting setting `iceberg.unique-table-location=true`.

We should also document this config `iceberg.unique-table-location=true`.

### PR DESCRIPTION
**Pull request by mdesmet**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Change to Iceberg connector

> How would you describe this change to a non-technical end user or system administrator?

## Related issues, pull requests, and links

* Fixes #12573

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by findepi — APPROVED** [review]

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java [hunk 1]
```diff
@@ -565,16 +565,28 @@ public ConnectorOutputTableHandle beginCreateTable(ConnectorSession session, Con
...
-                getColumns(transaction.table().schema(), typeManager),
-                transaction.table().location(),
-                getFileFormat(transaction.table()),
-                transaction.table().properties(),
-                retryMode);
+        String location = transaction.table().location();
+        HdfsContext hdfsContext = new HdfsContext(session);
+        try {
+            FileSystem fileSystem = hdfsEnvironment.getFileSystem(hdfsContext, new Path(location));
+            if (fileSystem.exists(new Path(location))) {
```
[the remark this answers is not in the document]
Comment (findepi) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:572]: That can be useful and indeed is safe to do.

(except for concurrency, which we need to ignore anyway)

**Review by ebyhr — APPROVED** [review]

**Review by alexjo2144 — APPROVED** [review]

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java [hunk 2]
```diff
@@ -565,16 +565,29 @@ public ConnectorOutputTableHandle beginCreateTable(ConnectorSession session, Con
...
+                    SchemaParser.toJson(transaction.table().schema()),
+                    PartitionSpecParser.toJson(transaction.table().spec()),
+                    getColumns(transaction.table().schema(), typeManager),
+                    location,
+                    getFileFormat(transaction.table()),
+                    transaction.table().properties(),
+                    retryMode);
+        }
+        catch (IOException e) {
+            throw new TrinoException(ICEBERG_FILESYSTEM_ERROR, "Failed getting FileSystem: " + location, e);
```
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:589]: it's not only `hdfsEnvironment.getFileSystem(` what can throw IOE.
change message to

```
"Failed checking new table's location: " + location
```

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java [hunk 3]
```diff
@@ -565,16 +565,29 @@ public ConnectorOutputTableHandle beginCreateTable(ConnectorSession session, Con
...
-                transaction.table().properties(),
-                retryMode);
+        String location = transaction.table().location();
+        HdfsContext hdfsContext = new HdfsContext(session);
+        try {
+            Path path = new Path(location);
+            FileSystem fileSystem = hdfsEnvironment.getFileSystem(hdfsContext, path);
+            if (fileSystem.exists(path) && fileSystem.listFiles(path, true).hasNext()) {
+                throw new TrinoException(ICEBERG_FILESYSTEM_ERROR, "Cannot create a table on a non-empty location: " + location + ", " +
+                        "set 'iceberg.unique-table-location=true' in your Iceberg catalog properties to use unique table locations for every table.");
```
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:575]: use `format`

```suggestion
                throw new TrinoException(ICEBERG_FILESYSTEM_ERROR, format(
                        "Cannot create a table on a non-empty location: %s, set 'iceberg.unique-table-location=true' in your Iceberg catalog properties " +
                                "to use unique table locations for every table.",
                        location));
```

**Review by findepi — APPROVED** [review]
