### PR TITLE
Report written rows and size by MERGE statement

### LINKED ISSUE #25922: Missing written rows/data metrics for Iceberg's MERGE INTO query summary
Environment:

- Ubuntu v22.04.4 LTS (host)
- Docker version 28.2.2, build e6534b4
- Containerized Trino v475 (test performed on v471 also) + HMS v3.x + MySQL v8.x + MinIO v2025-03

My containerized test deployment consists of 1 trino coordinator / 1 worker with iceberg connector, 1 minio service, 1 mysql and 1 hive metastore service (hms) .

It looks like `MERGE INTO` query result summary in the Web UI does not show information about written data/rows (inserts, updates or deletes) ie `Written Rows` and `Logical/Physical Written Data` being 0 for successful merges :

Image

The UI shows the summary for eg `INSERT` queries (writing 5 rows):

Image

To reproduce:

```sql
DROP SCHEMA IF EXISTS iceberg.testschema CASCADE; 
CREATE SCHEMA iceberg.testschema;

CREATE TABLE iceberg.testschema.testtbl (
    c1,
    c2
)
WITH (
    format = 'PARQUET',
    partitioning = ARRAY['c1']
)
AS VALUES
    (1, 1000);

INSERT INTO iceberg.testschema.testtbl values (2, 2000), (3, 3000);

CREATE TABLE iceberg.testschema.testtmptbl (
    c1,
    c2
)
WITH (
    format = 'PARQUET'
)
AS VALUES
    (1, 1000),
    (4, 2000);

MERGE INTO iceberg.testschema.testtbl "t"
      USING (
        SELECT c1, c2 FROM iceberg.testschema.testtmptbl
      ) "s"
      ON "t"."c1" = "s"."c1" 
      WHEN MATCHED and "t"."c2" IS DISTINCT FROM "s"."c2" THEN 
              UPDATE set
	        "c1" = "s"."c1",
	        "c2" = "s"."c2"
      WHEN NOT MATCHED THEN 
	      INSERT (
	        "c1",
	        "c2"
	      ) 
	      VALUES (
	        "s"."c1",
	        "s"."c2"
        	);

```

While the `MERGE INTO` operation itself is working correctly and modifying the Iceberg table as expected, the lack of accurate Written Rows and Logical/Physical Written Data metrics is a concern for monitoring and understanding query performance and impact.

Is it possible to provide metrics for `Written Rows` and `Logical/Physical Written Data`? These could be calculated as a total number (a sum) of inserted, updated, and deleted rows plus bytes written in total as another metric.

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #25922

Screenshot 2025-11-17 at 10 07 08

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java [hunk 1]
```diff
@@ -118,6 +118,7 @@ public class DeltaLakeMergeSink
     private final DeltaLakeWriterStats writerStats;
     private final Location rootTableLocation;
     private final ConnectorPageSink insertPageSink;
+    private long writtenBytes;
```
Comment (raunaqmorarka) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java]: non-final variable after final variables

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java [hunk 2]
```diff
@@ -205,8 +206,14 @@ public void storeMergedRows(Page page)
...
-        mergePage.insertionsPage().ifPresent(insertPageSink::appendPage);
-        mergePage.updateInsertionsPage().ifPresent(insertPageSink::appendPage);
+        mergePage.insertionsPage().ifPresent(insertions -> {
+            insertPageSink.appendPage(insertions);
+            writtenBytes += insertions.getSizeInBytes();
+        });
+        mergePage.updateInsertionsPage().ifPresent(updateInsertions -> {
+            insertPageSink.appendPage(updateInsertions);
+            writtenBytes += updateInsertions.getSizeInBytes();
+        });
```
Comment (raunaqmorarka) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java]: We should be tracking only physical written bytes that is available in `insertPageSink.getCompletedBytes()`.
So this should be addition of one line at the end of this method:
`writtenBytes = insertPageSink.getCompletedBytes()`

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java [hunk 3]
```diff
@@ -205,8 +206,14 @@ public void storeMergedRows(Page page)
...
 
         processInsertions(mergePage.insertionsPage(), INSERT_CDF_LABEL);
         processInsertions(mergePage.updateInsertionsPage(), UPDATE_POSTIMAGE_CDF_LABEL);
```
Comment (raunaqmorarka) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java:213]: after insert completed bytes, we should have
`writtenBytes += cdfPageSink == null ? 0 : cdfPageSink.getCompletedBytes()`

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java [hunk 4]
```diff
@@ -342,6 +355,7 @@ public CompletableFuture<Collection<Slice>> finish()
                 .map(mergeResultJsonCodec::toJsonBytes)
                 .map(Slices::wrappedBuffer)
                 .forEach(fragments::add);
+        writtenBytes += insertPageSink.getCompletedBytes();
```
Comment (raunaqmorarka) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java]: Shouldn't be needed after above changes

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java [hunk 5]
```diff
@@ -342,6 +355,7 @@ public CompletableFuture<Collection<Slice>> finish()
...
 
         fileDeletions.forEach((path, deletion) -> {
```
Comment (raunaqmorarka) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java:357]: I think we're missing tracking of bytes written for delete files

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMergeSink.java [hunk 6]
```diff
@@ -62,6 +62,7 @@ public class IcebergMergeSink
     private final Schema schema;
     private final Map<Integer, PartitionSpec> partitionsSpecs;
     private final ConnectorPageSink insertPageSink;
+    private long writtenBytes;
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMergeSink.java]: Similar comments as above

File: core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMergeSink.java [hunk 7]
```diff
@@ -71,6 +71,15 @@ public interface ConnectorMergeSink
      */
     void storeMergedRows(Page page);
 
+    /**
+     * Gets the number of output bytes written by this page source so far.
```
Comment (raunaqmorarka) [inline core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMergeSink.java]: `page source` -> `page sink`

Comment (raunaqmorarka) [inline core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMergeSink.java]: `output bytes written` -> `physical bytes written`

File: core/trino-main/src/main/java/io/trino/execution/QueryStats.java [hunk 8]
```diff
@@ -753,7 +756,7 @@ public DataSize getLogicalWrittenDataSize()
     {
         return succinctBytes(
                 operatorSummaries.stream()
-                        .filter(stats -> stats.getOperatorType().equals(TableWriterOperator.class.getSimpleName()))
+                        .filter(stats -> WRITER_OPERATORS.contains(stats.getOperatorType()))
```
Comment (raunaqmorarka) [inline core/trino-main/src/main/java/io/trino/execution/QueryStats.java:759]: Let's separate the commit for fixing reporting of "Logical written bytes"

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java (hunk 4 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java]: `AbstractDeltaLakePageSink` updates its `writtenBytes` in `finish()` method. The value becomes inaccurate if I remove this line.

Comment (raunaqmorarka) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java]: We can keep it, but I think it'll have to be updated to something like:
```
writtenBytes = insertPageSink.getCompletedBytes();
writtenBytes += cdfPageSink == null ? 0 : cdfPageSink.getCompletedBytes();
writtenBytes += deletedFilesWrittenBytes;
```

File: core/trino-main/src/test/java/io/trino/connector/MockConnector.java [hunk 9]
```diff
@@ -1063,6 +1063,12 @@ public CompletableFuture<?> appendPage(Page page)
         @Override
         public void storeMergedRows(Page page) {}
 
+        @Override
+        public long getCompletedBytes()
+        {
+            return 0;
+        }
```
Comment (raunaqmorarka) [inline core/trino-main/src/test/java/io/trino/connector/MockConnector.java:1070]: Is this needed given that you have a default method for returning 0 ?

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
Comment (raunaqmorarka) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java:362]: Are we missing tracking in the `io.trino.plugin.deltalake.DeltaLakeMergeSink#rewriteFile` code path ?

File: core/trino-main/src/test/java/io/trino/connector/MockConnector.java (hunk 9 above)
Comment (ebyhr) [reply core/trino-main/src/test/java/io/trino/connector/MockConnector.java:1070]: We can't build the project without overriding this method: 
```java
java: types io.trino.spi.connector.ConnectorPageSink and io.trino.spi.connector.ConnectorMergeSink are incompatible;
  class io.trino.connector.MockConnector.MockPageSink inherits unrelated defaults for getCompletedBytes() from types io.trino.spi.connector.ConnectorPageSink and io.trino.spi.connector.ConnectorMergeSink
```

Comment (raunaqmorarka) [reply core/trino-main/src/test/java/io/trino/connector/MockConnector.java:1070]: i see, its a side effect of implementing both interfaces in same mock class

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java [hunk 10]
```diff
@@ -213,6 +214,9 @@ public void storeMergedRows(Page page)
 
         mergePage.deletionsPage().ifPresent(deletions -> processDeletion(deletions, DELETE_CDF_LABEL));
         mergePage.updateDeletionsPage().ifPresent(deletions -> processDeletion(deletions, UPDATE_PREIMAGE_CDF_LABEL));
+
+        writtenBytes = insertPageSink.getCompletedBytes();
+        writtenBytes += cdfPageSink == null ? 0 : cdfPageSink.getCompletedBytes();
```
Comment (wendigo) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java:219]: if statement would be more readable then ternary one

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java [hunk 11]
```diff
@@ -5886,6 +5886,33 @@ public void testWrittenDataSize()
...
+        try {
+            assertQueryStats(
+                    getSession(),
+                    "MERGE INTO " + tableName + " USING (VALUES 42) t(dummy) ON false WHEN NOT MATCHED THEN INSERT VALUES (1, 'alice')",
+                    queryStats -> {
+                        assertThat(queryStats.getWrittenPositions()).isEqualTo(1L);
+                        assertThat(queryStats.getLogicalWrittenDataSize().toBytes()).isPositive();
+
+                        if (hasBehavior(SUPPORTS_REPORTING_WRITTEN_BYTES)) {
+                            assertThat(queryStats.getPhysicalWrittenDataSize().toBytes()).isPositive();
```
Comment (wendigo) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:5906]: can we assert on the actual written size?

**Comment by ebyhr** [comment]
(Just squashed fixup commits)

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java (hunk 10 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java:219]: This is simple enough to me.

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java (hunk 11 above)
Comment (ebyhr) [reply testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:5906]: I don't think we want to make this assertion complex in the base test class. Such tests can be implemented in each connector, with more detailed scenarios.
