### PR TITLE
Use CassandraQueryWaitStrategy in CassandraServer

### LINKED ISSUE #19926: Flaky TestCassandraTokenSplitManager.setUp
```
Error:  io.trino.plugin.cassandra.TestCassandraTokenSplitManager -- Time elapsed: 17.60 s <<< ERROR!
com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=localhost/127.0.0.1:32770, hostId=null, hashCode=6ebf142c): [com.datastax.oss.driver.api.core.connection.ConnectionInitException: [s2|control|id: 0xd0529295, L:/127.0.0.1:58048 - R:localhost/127.0.0.1:32770] Protocol initialization request, step 1 (OPTIONS): unexpected failure (com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Lost connection to remote peer)]
	at com.datastax.oss.driver.api.core.AllNodesFailedException.copy(AllNodesFailedException.java:141)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:835)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at io.trino.plugin.cassandra.CassandraSession.close(CassandraSession.java:615)
	at io.trino.plugin.cassandra.CassandraServer.<init>(CassandraServer.java:117)
	at io.trino.plugin.cassandra.CassandraServer.<init>(CassandraServer.java:79)
	at io.trino.plugin.cassandra.CassandraServer.<init>(CassandraServer.java:73)
	at io.trino.plugin.cassandra.TestCassandraTokenSplitManager.setUp(TestCassandraTokenSplitManager.java:48)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:[184](https://github.com/trinodb/trino/actions/runs/7008402419/job/19067263055#step:5:185)3)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:[188](https://github.com/trinodb/trino/actions/runs/7008402419/job/19067263055#step:5:189))
	Suppressed: com.datastax.oss.driver.api.core.connection.ConnectionInitException: [s2|control|id: 0xd0529295, L:/127.0.0.1:58048 - R:localhost/127.0.0.1:32770] Protocol initialization request, step 1 (OPTIONS): unexpected failure (com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Lost connection to remote peer)
		at com.datastax.oss.driver.internal.core.channel.ProtocolInitHandler$InitRequest.fail(ProtocolInitHandler.java:356)
		at com.datastax.oss.driver.internal.core.channel.ChannelHandlerRequest.onFailure(ChannelHandlerRequest.java:104)
		at com.datastax.oss.driver.internal.core.channel.InFlightHandler.fail(InFlightHandler.java:381)
		at com.datastax.oss.driver.internal.core.channel.InFlightHandler.abortAllInFlight(InFlightHandler.java:371)
		at com.datastax.oss.driver.internal.core.channel.InFlightHandler.abortAllInFlight(InFlightHandler.java:353)
		at com.datastax.oss.driver.internal.core.channel.InFlightHandler.channelInactive(InFlightHandler.java:331)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
		at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411)
		at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
		at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
		at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:1583)
	Caused by: com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Lost connection to remote peer
	Suppressed: java.lang.NullPointerException: Cannot invoke "io.trino.plugin.cassandra.CassandraServer.close()" because "this.server" is null
		at io.trino.plugin.cassandra.TestCassandraTokenSplitManager.tearDown(TestCassandraTokenSplitManager.java:57)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
		at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
		... 6 more
```

https://github.com/trinodb/trino/actions/runs/7009448726/job/19069391217
https://github.com/trinodb/trino/actions/runs/7008402419/job/19067263055

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #19926

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

File: plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraServer.java [hunk 1]
```diff
@@ -152,16 +136,7 @@ public String getHost()
 
     public int getPort()
     {
-        return dockerContainer.getMappedPort(PORT);
-    }
-
-    private static void checkConnectivity(CassandraSession session)
```
Comment (ebyhr) [inline plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraServer.java:158]: Replaced with [CassandraQueryWaitStrategy](https://github.com/testcontainers/testcontainers-java/blob/main/modules/cassandra/src/main/java/org/testcontainers/containers/wait/CassandraQueryWaitStrategy.java)

File: plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraServer.java [hunk 2]
```diff
@@ -52,19 +50,17 @@
...
-import static org.assertj.core.api.Assertions.assertThat;
+import static org.testcontainers.containers.CassandraContainer.CQL_PORT;
 import static org.testcontainers.utility.MountableFile.forHostPath;
 
 public class CassandraServer
         implements Closeable
 {
     private static final Logger log = Logger.get(CassandraServer.class);
 
-    private static final int PORT = 9142;
```
Comment (ebyhr) [inline plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraServer.java:63]: `CassandraContainer` expects 9042 as the default port.

**Review by wendigo — APPROVED** [review]
