### PR TITLE
Fix oauth2 and jwt authentificaor interference

### LINKED ISSUE #13575: OAuth Token Refresh will cause JWT authentication to fail
## Overview

We can enable token refresh with something like the following config:

```
http-server.authentication.type=PASSWORD,oauth2
http-server.authentication.oauth2.client-id=${ENV:OAUTH_CLIENT_ID}
http-server.authentication.oauth2.client-secret=${ENV:OAUTH_CLIENT_SECRET}
http-server.authentication.oauth2.issuer={server}
http-server.authentication.oauth2.additional-audiences=api://default
http-server.authentication.oauth2.oidc.use-userinfo-endpoint=false
http-server.authentication.oauth2.auth-url={url}
http-server.authentication.oauth2.token-url={url-2}
http-server.authentication.oauth2.jwks-url={url-3}
http-server.authentication.oauth2.scopes=insights_read_write,openid,offline_access
http-server.authentication.oauth2.refresh-tokens=true
http-server.authentication.oauth2.refresh-tokens.issued-token.timeout=1h
```

This will make Trino use a different implementation of `TokenPairSerializer` that will encrypt tokens trino fetches through the OAuth Challenge:
https://github.com/trinodb/trino/blob/b3d03cde33583e312f077d53b9133e13487ce92b/core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java#L145 and it will also attempt to decrypt all JWT tokens:
(https://github.com/trinodb/trino/blob/b3d03cde33583e312f077d53b9133e13487ce92b/core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java#L103).

## Issue 
Token refresh when only OAuth is enabled works fine, but when we enable both JWT and OAuth, which someone could want to do if they want to support both SSO and JWT for M2M auth, Trino will attempt to decrypt any JWT tokens it receives. This results in the following error:
```
Error running command: Error starting query at {url} returned an invalid response: JsonResponse{statusCode=500, statusMessage=, headers={content-length=[5842], content-type=[text/plain], date=[Thu, 28 Jul 2022 15:36:48 GMT], strict-transport-security=[max-age=15724800; includeSubDomains]}, hasValue=false} [Error: java.lang.RuntimeException: Authentication error
	at io.trino.server.security.AbstractBearerAuthenticator.authenticate(AbstractBearerAuthenticator.java:47)
	at io.trino.server.security.AbstractBearerAuthenticator.authenticate(AbstractBearerAuthenticator.java:34)
	at io.trino.server.security.AuthenticationFilter.filter(AuthenticationFilter.java:88)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
	
	...

	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Malformed jwt token
	at io.trino.server.security.oauth2.JweTokenSerializer.deserialize(JweTokenSerializer.java:111)
	at io.trino.server.security.oauth2.OAuth2Authenticator.createIdentity(OAuth2Authenticator.java:67)
	at io.trino.server.security.AbstractBearerAuthenticator.authenticate(AbstractBearerAuthenticator.java:41)
	... 62 more
Caused by: java.text.ParseException: Unexpected number of Base64URL parts, must be five
	at com.nimbusds.jose.JWEObject.parse(JWEObject.java:506)
	at io.trino.server.security.oauth2.JweTokenSerializer.deserialize(JweTokenSerializer.java:102)
	... 64 more
]
```

Thrown here because in this case, JWT tokens passed in through `--access-token` are not encrypted, meaning parsing will fail: 
https://github.com/trinodb/trino/blob/b3d03cde33583e312f077d53b9133e13487ce92b/core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java#L102

trino config to reproduce:
```
http-server.authentication.type=PASSWORD,oauth2,JWT
http-server.authentication.oauth2.client-id=${ENV:OAUTH_CLIENT_ID}
http-server.authentication.oauth2.client-secret=${ENV:OAUTH_CLIENT_SECRET}
http-server.authentication.oauth2.issuer={server}
http-server.authentication.oauth2.additional-audiences=api://default
http-server.authentication.oauth2.oidc.use-userinfo-endpoint=false
http-server.authentication.oauth2.auth-url={url}
http-server.authentication.oauth2.token-url={url-2}
http-server.authentication.oauth2.jwks-url={url-3}
http-server.authentication.oauth2.scopes=insights_read_write,openid,offline_access
http-server.authentication.oauth2.refresh-tokens=true
http-server.authentication.oauth2.refresh-tokens.issued-token.timeout=1h
http-server.authentication.oauth2.oidc.use-userinfo-endpoint=false
# http-server.authentication.oauth2.oidc.discovery=false
http-server.authentication.jwt.key-file={url-4}
```

Note that the trino docs suggest that if one form of Auth fails the next authentication type in the list should be attempted, but in this case, Oauth fails and JWT is not attempted, likely due to the un-handled parsing exception.

### Workaround
If I change the ordering of the auth types likesso:
``` http-server.authentication.type=PASSWORD,JWT,oauth2```
JWT will be attempted first, resulting in no parsing exceptions. 

## Suggested Change
If parsing fails, don't throw an error but mark the authentication as failed so we move to the next authentication type in the chain, if any.

### PR DESCRIPTION
**Pull request by s2lomon**
## Description

Beore this fix, when oauth2 with refresh token is enabled
along with jwt authenticator, user couldn't log in
by using standard jwt token. After the fix, every attempt of sending
token that can't be consumed by oauth2 authenticator will result in 
standard AuthenticationError, that plays along the contract of Authentificators

> Is this change a fix, improvement, new feature, refactoring, or other?

Fixes #13575

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

OAuth2 Authentification - core

> How would you describe this change to a non-technical end user or system administrator?

Brings back possibility of using both OAuth2 and jwt at the same time. 

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# Section
* OAuth Token Refresh will no longer cause JWT authentication failure  ({issue}`13575`)
```

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java [hunk 1]
```diff
@@ -80,11 +87,22 @@ protected Optional<Identity> createIdentity(String token)
         return Optional.of(builder.build());
     }
 
+    private Optional<TokenPair> deserializeToken(String token)
+    {
+        try {
+            return Optional.of(tokenPairSerializer.deserialize(token));
+        }
+        catch (RuntimeException ex) {
```
Comment (andrewdibiasio6) [inline core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java:95]: Do we want to just catch parse exceptions for now?

**Review by andrewdibiasio6 — APPROVED** [review]
LGTM! Thanks for the fix.

File: core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java (hunk 1 above)
Comment (Praveen2112) [inline core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java:95]: nit: Can we use `exception` ?

Comment (Praveen2112) [reply core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java:95]: Can we narrow down the catching ? What if the token fails because it is damaged or expired ?

Comment (s2lomon) [reply core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java:95]: Ok so this catch is so wide on purpose. Right now there are plenty of reasons why token deserialization might fail. We might be having invalid token (on purpose - like in this bug scenario), token might have expired - meaning that both access token and refresh token are either expired or soon to be expired, encryption keys might have been rolled out (after restart) etc. All of the above suggests that we need to discard the token, but we should not request any specific handling of these errors. Rather I think we should just discard this token and issue another challenge to the client - so business as usual. I could narrow catching to IllegalArgumentException (with allowing the possibility that some other valid case might not be handled atm), but then I would like to add this to official contract of the TokenPairSerializer interface as a throws. Catching implementation specific exceptions is not a best design decision.

File: core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java [hunk 2]
```diff
@@ -14,6 +14,7 @@
 package io.trino.server.security.oauth2;
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java:14]: There is a typo in the commit message.

> user couldn't log in by using standard jwt token.

Can you please explain why in the commit message too?

File: core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java [hunk 3]
```diff
@@ -42,6 +43,7 @@
 public class OAuth2Authenticator
         extends AbstractBearerAuthenticator
 {
+    private static final Logger LOG = Logger.get(OAuth2Authenticator.class);
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java:46]: nit: s/LOG/log

File: core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java (hunk 1 above)
Comment (kokosing) [reply core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java:95]: It would be too broad. Also there are no checked exceptions, as compiler would complain.

**Review by kokosing — COMMENTED** [review]
Please add a test.

**Comment by lukasz-walkiewicz** [comment]
Looks good but test is definitely needed. Please take a look at: `io.trino.server.security.TestResourceSecurity#testJwtAndOAuth2AuthenticatorsSeparation`

File: core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java [hunk 4]
```diff
@@ -50,7 +50,7 @@
 public class JweTokenSerializer
         implements TokenPairSerializer
 {
-    private static final Logger LOG = Logger.get(JweTokenSerializer.class);
+    private static final Logger log = Logger.get(JweTokenSerializer.class);
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java:53]: separate commit

File: core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java (hunk 3 above)
Comment (kokosing) [reply core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java:46]: ping :)

**Review by lukasz-walkiewicz — APPROVED** [review]

**Comment by kokosing** [comment]
@s2lomon the build is red

File: core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java (hunk 1 above)
Comment (Praveen2112) [reply core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java:95]: I meant the variable name. nvm

File: core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java [hunk 5]
```diff
@@ -816,6 +816,48 @@ public void testJwtAndOAuth2AuthenticatorsSeparation()
...
+            throws Exception
+    {
+        TestingHttpServer jwkServer = createTestingJwkServer();
+        jwkServer.start();
+        try (TokenServer tokenServer = new TokenServer(Optional.empty());
+                TestingTrinoServer server = TestingTrinoServer.builder()
+                        .setProperties(
+                                ImmutableMap.<String, String>builder()
+                                        .putAll(SECURE_PROPERTIES)
+                                        .put("http-server.authentication.type", "jwt,oauth2")
```
Comment (Praveen2112) [inline core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java:830]: Can test with the config that causes the issue i.e `http-server.authentication.type=oauth2,JWT` ?

**Review by Praveen2112 — APPROVED** [review]
