### PR TITLE
Throw relevent error when query didn't match any selection rule

### LINKED ISSUE #21895: [Trino-420] Relevant Error message should be shown when clientTags is not passed while query is run
Steps to reproduce the issue:

1. Configure resource-groups.json on a co-ordinator node
2. Add clientTags in one of the groups
3. Try accessing the co-ordinator or running any query by passing the clientTags

Expected:
Connection should be successful and query should work

Actual:
Connectivity / Query is failing with "Query did not match any selection rule"

PFA screenshot for the same.
Trino_ClientTags_Issue

### PR DESCRIPTION
**Pull request by uditvarshney**
## Description
The error message can be more significant which will help user to understand the query failure reason.

Fixes #21895

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`21895`)
```

### CODE REVIEW

**Comment by hashhar** [comment]
Resource group can be applied to things other than users (e.g. query type or source) - the new error message would be wrong then.

**Comment by hashhar** [comment]
@mosabua Can you suggest something better which is accurate yet more clear?

File: core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroupManager.java [hunk 1]
```diff
@@ -118,7 +118,7 @@ public void submit(ManagedQueryExecution queryExecution, SelectionContext<C> sel
     public SelectionContext<C> selectGroup(SelectionCriteria criteria)
     {
         return configurationManager.get().match(criteria)
-                .orElseThrow(() -> new TrinoException(QUERY_REJECTED, "Query did not match any selection rule"));
+                .orElseThrow(() -> new TrinoException(QUERY_REJECTED, "User does not belong to any enabled resource group"));
```
Comment (mosabua) [inline core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroupManager.java:121]: Maybe

No matching resource group found with configured selection rules. No resources for query processing available.

Or only part of that even.

Comment (mosabua) [reply core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroupManager.java:121]: sounds good to me

Comment (uditvarshney) [reply core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroupManager.java]: @mosabua please review it.

**Review by mosabua — APPROVED** [review]
Looks good now. Tested local build as well. Will wait for CI

**Comment by mosabua** [comment]
Failing teste in CI is unrelated in Pinot connector
