### PR TITLE
Delta Lake: skip statistics on error

### LINKED ISSUE #24487: Delta Lake: unhandled column statistics for one column break all column statistics
Delta Lake entries contain column statistics that can be used by the Trino optimiser to speed up queries.

Only a subset of data types are supported in stats:
https://github.com/trinodb/trino/blob/e369f66563863cd775ffe081dca3728949e8a00e/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java#L193-L236

When stats do not match one of these columns, we throw an exception:
https://github.com/trinodb/trino/blob/e369f66563863cd775ffe081dca3728949e8a00e/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java#L243-L246

Which gives this stack trace in practice:
```
	at java.base/java.lang.Thread.run(Thread.java:1570)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at io.trino.$gen.Trino_435_3370_ga3323af____20241216_070309_2.run(Unknown Source)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:134)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:150)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:416)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:478)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:498)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:233)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:238)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:266)
	at io.trino.sql.planner.LogicalPlanner.runOptimizer(LogicalPlanner.java:303)
	at io.trino.sql.planner.optimizations.StatsRecordingPlanOptimizer.optimize(StatsRecordingPlanOptimizer.java:41)
	at io.trino.sql.planner.optimizations.DeterminePartitionCount.optimize(DeterminePartitionCount.java:120)
	at io.trino.sql.planner.optimizations.DeterminePartitionCount.determinePartitionCount(DeterminePartitionCount.java:174)
	at io.trino.sql.planner.optimizations.DeterminePartitionCount.getPartitionCountBasedOnRows(DeterminePartitionCount.java:227)
	at io.trino.sql.planner.optimizations.DeterminePartitionCount.getSourceNodesOutputStats(DeterminePartitionCount.java:299)
	at java.base/java.util.stream.DoublePipeline.sum(DoublePipeline.java:450)
	at java.base/java.util.stream.DoublePipeline.collect(DoublePipeline.java:541)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:5082)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:5074)
	at java.base/java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:263)
	at io.trino.sql.planner.optimizations.DeterminePartitionCount.lambda$getPartitionCountBasedOnRows$3(DeterminePartitionCount.java:227)
	at io.trino.cost.CachingStatsProvider.getStats(CachingStatsProvider.java:87)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:71)
	at io.trino.cost.ComposableStatsCalculator.calculateStats(ComposableStatsCalculator.java:83)
	at io.trino.cost.SimpleStatsRule.calculate(SimpleStatsRule.java:37)
	at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:36)
	at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:60)
	at io.trino.cost.CachingTableStatsProvider.getTableStatistics(CachingTableStatsProvider.java:46)
	at io.trino.tracing.TracingMetadata.getTableStatistics(TracingMetadata.java:311)
	at io.trino.metadata.MetadataManager.getTableStatistics(MetadataManager.java:477)
	at io.trino.tracing.TracingConnectorMetadata.getTableStatistics(TracingConnectorMetadata.java:331)
	at com.dune.trino.metastore.AbstractDelegatingConnectorMetadata.getTableStatistics(AbstractDelegatingConnectorMetadata.kt:262)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableStatistics(ClassLoaderSafeConnectorMetadata.java:354)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.getTableStatistics(DeltaLakeMetadata.java:899)
	at io.trino.plugin.deltalake.statistics.FileBasedTableStatisticsProvider.getTableStatistics(FileBasedTableStatisticsProvider.java:174)
	at io.trino.plugin.deltalake.transactionlog.statistics.DeltaLakeJsonFileStatistics.getMinColumnValue(DeltaLakeJsonFileStatistics.java:136)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at io.trino.plugin.deltalake.transactionlog.statistics.DeltaLakeJsonFileStatistics.lambda$getMinColumnValue$4(DeltaLakeJsonFileStatistics.java:136)
	at io.trino.plugin.deltalake.transactionlog.statistics.DeltaLakeJsonFileStatistics.deserializeStatisticsValue(DeltaLakeJsonFileStatistics.java:144)
	at io.trino.plugin.deltalake.transactionlog.TransactionLogParser.deserializeColumnValue(TransactionLogParser.java:246)
io.trino.spi.TrinoException: Unable to parse value [\x00\x03\x01\x0f\x932\xd3\xf5\xe8\x11\x9cY\xd0\xd6\x92v\xa7c,\xd8] from column hash with type varbinary
2024-12-16T14:54:24.199Z	ERROR	Query-20241216_145422_23066_5cgep-43942	io.trino.cost.CachingStatsProvider	Error occurred when computing stats for query 20241216_145422_23066_5cgep
```

When this happens, _all_ stats for the query are ignored:
https://github.com/trinodb/trino/blob/e369f66563863cd775ffe081dca3728949e8a00e/core/trino-main/src/main/java/io/trino/cost/CachingStatsProvider.java#L91-L97

Which makes it impossible for Trino to optimise based on stats at all, even if stats for some other columns are available.

We've noticed that some implementations (namely delta_rs) write stats for more types than Trino supports, for example in the stacktrace above a stat for a VARBINARY column.

Until Trino adds official support for using these stats, let's consider stats to be unavailable for these specific columns rather than blow up and not consider stats at all?

### PR DESCRIPTION
**Pull request by Pluies**
## Description

When faced with un-deserializable stats, log a warning and return empty stats, rather than failing to return any statistics

## Additional context and related issues

Fixes #24487 

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
## Delta Lake
* Improve support for Delta Lake statistics. ({issue}`24487`)
```

### CODE REVIEW

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java [hunk 1]
```diff
@@ -141,7 +142,15 @@ private Optional<Object> deserializeStatisticsValue(DeltaLakeColumnHandle column
...
             return Optional.empty();
         }
-        Object columnValue = deserializeColumnValue(columnHandle, statValue, DeltaLakeJsonFileStatistics::readStatisticsTimestamp, DeltaLakeJsonFileStatistics::readStatisticsTimestampWithZone);
+
+        Object columnValue;
+        try {
+            columnValue = deserializeColumnValue(columnHandle, statValue, DeltaLakeJsonFileStatistics::readStatisticsTimestamp, DeltaLakeJsonFileStatistics::readStatisticsTimestampWithZone);
+        }
+        catch (TrinoException e) {
+            log.warn("Cannot deserialize column value, skipping statistics: %s", e.getMessage());
```
Comment (pajaks) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java:151]: Could you add test case with unsupported statistics types?

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java [hunk 2]
```diff
@@ -141,7 +142,15 @@ private Optional<Object> deserializeStatisticsValue(DeltaLakeColumnHandle column
         if (!columnHandle.isBaseColumn()) {
             return Optional.empty();
         }
-        Object columnValue = deserializeColumnValue(columnHandle, statValue, DeltaLakeJsonFileStatistics::readStatisticsTimestamp, DeltaLakeJsonFileStatistics::readStatisticsTimestampWithZone);
+
+        Object columnValue;
+        try {
+            columnValue = deserializeColumnValue(columnHandle, statValue, DeltaLakeJsonFileStatistics::readStatisticsTimestamp, DeltaLakeJsonFileStatistics::readStatisticsTimestampWithZone);
```
Comment (raunaqmorarka) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java:148]: Is it hard to add support for the varbinary case ? I would rather we do that than add a try/catch which will hide the underlying problem

Comment (Pluies) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java:148]: @raunaqmorarka I'm not entirely sure, and adding the stats here has serious correctness implications (skip a partition that shouldn't be skipped -> incomplete data 😬 ), so I don't feel confident I can come up with a good solution and would rather explicitly skip unsupported statistics in this PR, and let someone else come up with the enhancement in a separate PR.

Additionally, besides VARBINARY, any implementation could come up with statistics for new types, so this PR future-proofs Trino to ensure we'll keep using the stats we know how to handle and avoid the yet-unimplemented ones.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java (hunk 1 above)
Comment (Pluies) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java:151]: Test case added! 👍

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java (hunk 2 above)
Comment (raunaqmorarka) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java:148]: @ebyhr @findinpath do you know how to tackle adding support for varbinary stats ? I'd rather have that than swallowing exceptions

Comment (Pluies) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java:148]: @raunaqmorarka adding support for varbinary would fix this specific issue, but I still think we should handle unknown types more gracefully, as currently a failure means that _all stats are ignored_, rather than just the unknown stat being ignored. Wdyt?

Comment (Pluies) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java:148]: Hey folks, happy new year! :) Hope you had a happy holiday season. Trying to get this moved forward, I still strongly feel it's better to have two PRs here, this one to handle unknown statistics gracefully, and a follow-up for varbinary stats; wdyt @raunaqmorarka / @ebyhr / @findinpath ?

**Comment by mosabua** [comment]
@raunaqmorarka @pajaks @Pluies @findinpath .. do you want to sync up and figure out a path forward for this

**Review by raunaqmorarka — APPROVED** [review]

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java (hunk 2 above)
Comment (chenjian2664) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java:148]: If we skip the stats, then do we have chance to parse some know formats of the stats, like we know the default format of timestamp in Spark in the future?
So, next question is how to add those `enhancement` in the future, or at least we should file an issue, or add some comments?

Comment (raunaqmorarka) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java:148]: I've added a code comment and a TODO

**Comment by Pluies** [comment]
Thank you @raunaqmorarka ! 🙌
