### PR TITLE
Handle row ambiguous dereference as semantic error

### LINKED ISSUE #7398: Handle ambiguous dereference as semantic error
This query should fail during analysis:
```sql
SELECT CAST(ROW(1, 2) AS ROW(a BIGINT, A DOUBLE)).a
```
But it fails during planning:
```
java.lang.IllegalArgumentException: Ambiguous field io.trino.spi.type.RowType$Field@226de93c in type row(a bigint, a double)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:441)
	at io.trino.sql.planner.ExpressionInterpreter$Visitor.visitDereferenceExpression(ExpressionInterpreter.java:318)
```

### PR DESCRIPTION
**Pull request by brandboat**
Fixes #7398

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java [hunk 1]
```diff
@@ -619,11 +620,16 @@ protected Type visitDereferenceExpression(DereferenceExpression node, StackableA
             RowType rowType = (RowType) baseType;
             String fieldName = node.getField().getValue();
 
+            int index = -1;
             Type rowFieldType = null;
             for (RowType.Field rowField : rowType.getFields()) {
-                if (fieldName.equalsIgnoreCase(rowField.getName().orElse(null))) {
+                String rowFieldName = rowField.getName().orElse(null);
+                if (fieldName.equalsIgnoreCase(rowFieldName)) {
```
Comment (Praveen2112) [inline core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java:627]: What if we have an expression like this `CAST(ROW(1, 2, 3) AS ROW(a BIGINT, A DOUBLE, c BIGINT)).c`. In this case we won't fail right ? Is it okay to evaluate them based on the field being accessed ?

cc @martint , @kasiafi

File: core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java [hunk 2]
```diff
@@ -619,11 +620,16 @@ protected Type visitDereferenceExpression(DereferenceExpression node, StackableA
...
+                    if (index >= 0) {
+                        throw ambiguousAttributeException(node, QualifiedName.of(rowFieldName));
```
Comment (kasiafi) [inline core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java:629]: I would do:
```
throw semanticException(AMBIGUOUS_NAME, node.getField(), "Ambiguous row field reference: " + fieldName);
```
to adjust the error message, and also to locate the error at the ambiguous identifier.

**Comment by brandboat** [comment]
Thanks for your comments, @kasiafi . I've addressed your comments.

File: core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java [hunk 3]
```diff
@@ -619,11 +620,16 @@ protected Type visitDereferenceExpression(DereferenceExpression node, StackableA
             RowType rowType = (RowType) baseType;
             String fieldName = node.getField().getValue();
 
+            int index = -1;
```
Comment (kasiafi) [inline core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java:623]: Use `boolean found` instead of the integer.

File: core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java [hunk 4]
```diff
@@ -619,11 +620,16 @@ protected Type visitDereferenceExpression(DereferenceExpression node, StackableA
...
             Type rowFieldType = null;
             for (RowType.Field rowField : rowType.getFields()) {
-                if (fieldName.equalsIgnoreCase(rowField.getName().orElse(null))) {
+                String rowFieldName = rowField.getName().orElse(null);
```
Comment (kasiafi) [inline core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java:626]: Inline `rowFieldName`.

**Review by kasiafi — COMMENTED** [review]
Just two more comments.

File: core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java (hunk 4 above)
Comment (brandboat) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java]: Copy that. I've addressed your latest comments. Thanks !

File: core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java (hunk 3 above)
Comment (brandboat) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java]: Copy that.

**Review by kasiafi — APPROVED** [review]

**Review by Praveen2112 — APPROVED** [review]
