### PR TITLE
Fix incorrect derivation of effective predicate

### LINKED ISSUE #21457: Different query results when using aggregate function over a null value
Starting at version `444` Trino returns different query results when using an aggregation function over a hardcoded null value.

Example:
```sql
WITH t0 AS (
    SELECT
        s_manager,
        s_market_manager,
        s_market_desc,
        COUNT(*) AS total
    FROM tpcds.sf10.store
    GROUP BY 1, 2, 3
),
t1 AS (
    SELECT
        s_manager as s_manager1,
        s_market_manager,
        /*
            When using max(null) the query return a result set, but when using just
            `null` the query returns an empty result set.
        */
        -- max(null) AS null_column,
        null AS null_column,
        SUM(total) AS total_sum
    FROM t0
    GROUP BY 1, 2
),
t2 AS (
    SELECT
        s_manager1 as s_manager2,
        null_column,
        SUM(total_sum) AS total_sum2
    FROM t1
    where  s_market_manager != 'Michael Aguilar'
    GROUP BY 1, 2
),
t3 AS (
    SELECT
        *
    FROM t2
        inner JOIN t1
        ON t1.s_manager1 = t2.s_manager2
)
SELECT *
    FROM t3
order by 1, 2, 3, 4, 5, 6, 7
```

When using the same query (with `null AS null_column`)  but replacing the `FROM t2 INNER JOIN t1` with  `FROM t2 LEFT JOIN t1` the query returns data but all values from t1 CTE is null:
image

The query works properly for both `max(null) as ...` and `null as ...` if I remove the `where s_market_manager != 'Michael Aguilar'` statement from t2 CTE.

I've tested with version `443` and both queries (with `max(null) as ...` and `null as ...`) works properly.

### PR DESCRIPTION
**Pull request by martint**
Fixes #21457 

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# General
* TBD. ({issue}`21457`)
```

### CODE REVIEW

File: core/trino-main/src/test/java/io/trino/sql/query/TestIssue21457.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.TestInstance;
+import org.junit.jupiter.api.parallel.Execution;
+
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.junit.jupiter.api.TestInstance.Lifecycle.PER_CLASS;
+import static org.junit.jupiter.api.parallel.ExecutionMode.CONCURRENT;
+
+@TestInstance(PER_CLASS)
+@Execution(CONCURRENT)
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/sql/query/TestIssue21457.java:25]: nit: remove

**Review by findepi — APPROVED** [review]
(skimmed)

**Review by dain — APPROVED** [review]
