### PR TITLE
remove old Kerberos ticket after relogin to make Kudu authentication work correctly

### LINKED ISSUE #14372: Cannot access Kudu tables due to expire of Kerberos TGTs
Hi, community. We recently encounter a problem that Trino (386) cannot list and query tables in a Kerberized Kudu cluster. The error message is:

```
org.apache.kudu.client.NonRecoverableException: server requires authentication, but client Kerberos credentials (TGT) have expired. Authentication tokens were not used because no token is available, org.apache.kudu.client.NonRecoverableException: server requires authentication, but client Kerberos credentials (TGT) have expired. Authentication tokens were not used because no token is available
```

Our Trino cluster works well when it is newly started, and a few days later, some of the workers and/or the coordinator start to raise such exceptions. A server restart can temporarily fix the problem and fails still occur days after. We configure the lifetime of Kerberos ticket to be 1 day. That is to say, after a few times of ticket refreshment, the authentication mechanism will fail.

I use the production test environment `multinode-kerberos-kudu` to re-produce the error, using the following steps:
1. start a kerberized kudu cluster and trino cluster by `testing/bin/ptl env up --environment multinode-kerberos-kudu --debug`
2. wait for more than 1 minute (the lifetime of ticket is set to 1 minute)
3. make a query to the kudu catalog, like `show tables from kudu.default;`

If you are *lucky* enough (it cannot be re-produced every time, I will explain later), you will see similar error messages.

The exception stack is as follows: 

```
"type": "org.apache.kudu.client.KuduException.OriginalException",
"message": "Original asynchronous stack trace",
"suppressed": [],
"stack": [
    "org.apache.kudu.client.ConnectToCluster.incrementCountAndCheckExhausted(ConnectToCluster.java:268)",
    "org.apache.kudu.client.ConnectToCluster.access$100(ConnectToCluster.java:51)",
    "org.apache.kudu.client.ConnectToCluster$ConnectToMasterErrCB.call(ConnectToCluster.java:387)",
    "org.apache.kudu.client.ConnectToCluster$ConnectToMasterErrCB.call(ConnectToCluster.java:376)",
    "com.stumbleupon.async.Deferred.doCall(Deferred.java:1280)",
    "com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1259)",
    "com.stumbleupon.async.Deferred.handleContinuation(Deferred.java:1315)",
    "com.stumbleupon.async.Deferred.doCall(Deferred.java:1286)",
    "com.stumbleupon.async.Deferred.runCallbacks(Deferred.java:1259)",
    "com.stumbleupon.async.Deferred.callback(Deferred.java:1002)",
    "org.apache.kudu.client.KuduRpc.handleCallback(KuduRpc.java:276)",
    "org.apache.kudu.client.KuduRpc.errback(KuduRpc.java:330)",
    "org.apache.kudu.client.RpcProxy.responseReceived(RpcProxy.java:255)",
    "org.apache.kudu.client.RpcProxy.access$000(RpcProxy.java:63)",
    "org.apache.kudu.client.RpcProxy$1.call(RpcProxy.java:157)",
    "org.apache.kudu.client.RpcProxy$1.call(RpcProxy.java:153)",
    "org.apache.kudu.client.Connection.cleanup(Connection.java:727)",
    "org.apache.kudu.client.Connection.exceptionCaught(Connection.java:445)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)",
    "org.apache.kudu.shaded.io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)",
    "org.apache.kudu.shaded.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)",
    "org.apache.kudu.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)",
    "org.apache.kudu.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)",
    "org.apache.kudu.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)",
    "org.apache.kudu.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)",
    "org.apache.kudu.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)",
    "org.apache.kudu.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)",
    "org.apache.kudu.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)",
    "org.apache.kudu.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)",
    "org.apache.kudu.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)",
    "org.apache.kudu.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)",
    "org.apache.kudu.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)",
    "org.apache.kudu.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)",
    "org.apache.kudu.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)",
    "org.apache.kudu.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)",
    "java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)",
    "java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)",
    "java.base/java.lang.Thread.run(Thread.java:829)"
],
```

The error occurs when `KuduClient` starts connecting to Kudu tserver. Kudu connection negotiator will check ticket expiration via the following [code](https://github.com/apache/kudu/blob/df40fff0dea06fde06c3cc4967047177524f0b09/java/kudu-client/src/main/java/org/apache/kudu/client/Negotiator.java#L464-L467):

```java
Subject s = securityContext.getSubject();
// ...
if (SecurityUtil.isTgtExpired(s)) {
  errorsByMech.put(clientMech.name(), "client Kerberos credentials (TGT) have expired");
  continue;
}
```
and an error will be raised later from the negotiation. It is inferred that TGT is expired when connection being made. But, we have a delegated `KuduClient` in `io.trino.plugin.kudu.KerberizedKuduClient` and before we get the client instance, Trino will check and refresh the ticket via: 

```
// io.trino.plugin.kudu.KerberizedKuduClient
protected KuduClient delegate()
{
    cachingKerberosAuthentication.reauthenticateIfSoonWillBeExpired();
    return kuduClient;
}
```

After step into the code, I find that the `Subject`'s credentials are not well managed by Trino. The reauthentication code is:

```java
// io.trino.plugin.base.authentication.CachingKerberosAuthentication:L48-L56
public synchronized void reauthenticateIfSoonWillBeExpired()
{
    if (ticketNeedsRefresh()) {
        kerberosAuthentication.attemptLogin(subject);        // create a new LoginContext and invoke its login method
        KerberosTicket tgtTicket = getTicketGrantingTicket(subject);      // get the first TGT from subject.privateCredentials
        nextRefreshTime = KerberosTicketUtils.getRefreshTime(tgtTicket);   // calculated by tickets startTime and endTime
    }
}
```

The problem is the first TGT from `subject.privateCredentials` is not always the newest one! Look at the implementation of `getTicketGrantingTicket()`:

```java
public static KerberosTicket getTicketGrantingTicket(Subject subject)
{
    Set<KerberosTicket> tickets = subject.getPrivateCredentials(KerberosTicket.class);  // the underlying collection is a HashSet!
    for (KerberosTicket ticket : tickets) {
        if (isOriginalTicketGrantingTicket(ticket)) {
            return ticket;
        }
    }
    throw new IllegalArgumentException("kerberos ticket not found in " + subject);
}
```

The `HashSet`'s iteration is unpredictable, so the re-production above is unstable. The mechanism will lead to the following problems:

1. Ticket expiration detection in Kudu client follow the similar way, it may get an old ticket and reject to connect (as the problem described above);
2. The `nextRefreshTime` calculated with ticket `startTime` and `endTime` will be an time point in the past, thus, Trino will reauthenticate again for the next query;
3. There will be a lot of tickets stored in the subject (tickets are not removed from `subject.privateCredentials`), and situation may become worse and worse - it is harder and harder for a new ticket to locate in the first place of a `HashSet`'s iterator, and more and more reauthentication will be send to KDC.

### PR DESCRIPTION
**Pull request by xiacongling**
## Description

A bugfix to make authentication work correctly on a Kerberized Kudu cluster. Old Kerberos tickets may be used to make Kudu connections, it may lead to Kudu `UnrecoverableException` being raised when query Kudu's data even though relogin recently. Besides, next ticket refresh time is calculated based on the ticket's `startTime` and `endTime`, a wrong result will lead to frequent access to the KDC. Remove old tickets after relogin can fix the issue.

This PR fixes #14372
fixes https://github.com/trinodb/trino/issues/14441

## Non-technical explanation

Remove old Kerberos ticket to avoid authentication check failures when access Kerberized Kudu clusters.

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix a bug in Kudu Kerberos ticket management. ({issue}`14372`)
```

### CODE REVIEW

**Comment by ebyhr** [comment]
Does this PR fix #14441?

**Comment by xiacongling** [comment]
> Does this PR fix #14441?

Yes, the error message in #14441 and #14372 are the same.

**Comment by ebyhr** [comment]
Could you add a temporary commit for a stress test like https://github.com/trinodb/trino/pull/14393?

**Comment by grantatspothero** [comment]
@ebyhr for the release notes, do any other connectors utilize `CachingKerberosAuthentication`? 

The bug is not kudu specific.

**Comment by ebyhr** [comment]
@grantatspothero `KerberosAuthentication.attemptLogin` method is used only from Kudu as far as I confirmed.

File: lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/authentication/KerberosAuthentication.java [hunk 1]
```diff
@@ -58,8 +58,11 @@ public Subject getSubject()
     public void attemptLogin(Subject subject)
     {
         try {
-            LoginContext loginContext = new LoginContext("", subject, null, configuration);
-            loginContext.login();
+            synchronized (subject.getPrivateCredentials()) {
```
Comment (findepi) [inline lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/authentication/KerberosAuthentication.java:61]: Why on `subject.getPrivateCredentials()` and not on `subject`?
Why do we need synchronize at all?

please capture reasoning as a code comment

**Comment by grantatspothero** [comment]
+1 on @findepi 's comment, but otherwise LGTM. 

Thanks for adding a [detailed description of the bug here](https://github.com/trinodb/trino/issues/14372)

**Comment by findepi** [comment]
I am not convinced this is the right fix, but it seems to help with test flakiness (https://github.com/trinodb/trino/pull/15990). Therefore I am merging this.

@grantatspothero is following up with a better fix here https://github.com/trinodb/trino/pull/15997

cc @anusudarsan
