### PR TITLE
Set DB_CLOSE_DELAY for Raptor H2

### LINKED ISSUE #12726: trino-raptor-legacy tests are flaky, e.g. sometimes fail with OutOfMemoryError

### PR DESCRIPTION
**Pull request by electrum**
Test fix. Restores previous `dbpool` behavior.

## Related issues, pull requests, and links

Fixes #12726

## Documentation

(x) No documentation is needed.

## Release notes

(x) No release notes entries required.

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]
Approving as stress test result in #12770 looks fine.

File: plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseMetadataModule.java [hunk 1]
```diff
@@ -85,7 +86,7 @@ public void configure(Binder binder)
         @ForMetadata
         public static ConnectionFactory createConnectionFactory(H2DatabaseConfig config)
         {
-            String url = "jdbc:h2:" + config.getFilename();
+            String url = format("jdbc:h2:%s;DB_CLOSE_DELAY=-1", config.getFilename());
```
Comment (findepi) [inline plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseMetadataModule.java:89]: Worth documenting why DB_CLOSE_DELAY matters?

Comment (findepi) [reply plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseMetadataModule.java:89]: per h2 docs, `DB_CLOSE_DELAY=-1` will keep database around for longer (which is probably desireable in the tests)
i expect this will address some H2 related failures that i observed in my stress test https://github.com/trinodb/trino/pull/12730
will this also prevent OOM? why?
intuitively `DB_CLOSE_DELAY=-1`  increases memory usage, not decreases.

Comment (electrum) [reply plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseMetadataModule.java:89]: I have no idea. It's been there forever.
