### PR TITLE
Fix incorrect case optimization

### LINKED ISSUE #22530: [Bug][Trino 450] CASE Statements unexpectedly propagate NULL values
This issue started occurring after upgrading from Trino 439 -> Trino 450. 

In Trino 450, CASE statements that previously worked as expected now start unexpectedly propogating NULL values, even when the CASE should never allow for that to happen. This seems to only happen if the source column in a conditional is NULL and not explicitly null-checked

Steps to reproduce:

Create test table with values

```SQL
create table scratch.foo (id integer, val varchar);
insert into scratch.foo VALUES (1, 'True'), (2, 'False'), (3, null)
```

Try to query it

```SQL
SELECT
CASE WHEN val = 'True' THEN TRUE
ELSE FALSE END AS boolean_value from scratch.foo;
```

Results:

```
 boolean_value
---------------
 true
 false
 NULL
```

This can be fixed by explicitly checking for nullness:

```sql
SELECT
CASE WHEN val = 'True' and val is not null THEN TRUE
ELSE FALSE END AS boolean_value from scratch.foo;
```

But pre 450 this wasn't the case. Has something changed with the logic to force explicit null checks?

### PR DESCRIPTION
**Pull request by martint**
Expressions of the form:

```
CASE
    WHEN <cond> THEN true
    ELSE false
END
```

were being simplified to `<cond>`, which is
incorrect due to null handling. The original
form would return false, while the simplified
form returns null.

The correct transformation is: `<cond> ≡ true`.

Conversely, for an expression such as:

```
CASE
    WHEN <cond> THEN false
    ELSE true
END
```

The correct transformation is: `not(<cond> ≡ true)`.

Fixes #22530 

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# General
* Fix incorrect results for CASE expressions of the form `CASE WHEN ... THEN true ELSE false END`. ({issue}`22530`)
```

### CODE REVIEW

**Review by dain — APPROVED** [review]

File: core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/SimplifyRedundantCase.java [hunk 1]
```diff
@@ -53,11 +54,11 @@ public Optional<Expression> apply(Expression expression, Session session, Map<Sy
 
         WhenClause thenClause = caseTerm.whenClauses().getFirst();
         if (thenClause.getResult().equals(TRUE) && caseTerm.defaultValue().equals(FALSE)) {
-            return Optional.of(thenClause.getOperand());
+            return Optional.of(new Comparison(Comparison.Operator.IDENTICAL, thenClause.getOperand(), TRUE));
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/SimplifyRedundantCase.java:57]: Why not `coalesce(thenClause.getOperand(), false)`?

This would let coalesce pruning to kick in and simplify this further.

Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/SimplifyRedundantCase.java:57]: Good question!

That's a larger topic of discussion, but the short answer is that coalesce is a conditional expression and it makes it harder, in general, for the engine to reason about. It turns out that using `x ≡ true` and `x  ≡ false` is a much better way to turn ternary logic into binary logic, do transformations that preserve properties, etc.

Comment (findepi) [reply core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/SimplifyRedundantCase.java:57]: do we have a rule optimizing `x ≡ true` to `x` when `x` is not nullable?

Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/SimplifyRedundantCase.java:57]: Not yet, because we don't have a way to know if x is nullable or not. But that's coming, too.
