### PR TITLE
to_iso8601 with timezone incorrect during dst hour

### LINKED ISSUE #11619: to_iso8601 with timezone incorrect during dst hour
Trino 371. Daylight savings time ended on November 1st 2020 but the following select statement does not yield expected.

```sql
SELECT to_iso8601(timestamp '2020-11-01 06:00 UTC' AT TIME ZONE 'America/Chicago')
    ,  to_iso8601(timestamp '2020-11-01 07:00 UTC' AT TIME ZONE 'America/Chicago')
    ,  to_iso8601(timestamp '2020-11-01 08:00 UTC' AT TIME ZONE 'America/Chicago')
```

Expected
```
2020-11-01T01:00:00-05:00     2020-11-01T01:00:00-06:00    2020-11-01T02:00:00-06:00
```   

Actual
```
2020-11-01T01:00:00-05:00     2020-11-01T01:00:00-05:00    2020-11-01T02:00:00-06:00
```

Analogous issue is not observed for format_datetime function. E.g.

```sql
SELECT format_datetime(timestamp '2020-11-01 06:00 UTC' AT TIME ZONE 'America/Chicago','YYYY-MM-dd HH:mm:ss ZZ')
     ,  format_datetime(timestamp '2020-11-01 07:00 UTC' AT TIME ZONE 'America/Chicago','YYYY-MM-dd HH:mm:ss ZZ')
     ,  format_datetime(timestamp '2020-11-01 08:00 UTC' AT TIME ZONE 'America/Chicago','YYYY-MM-dd HH:mm:ss ZZ')
```

Actual == Expected
```
2020-11-01 01:00:00 -05:00        2020-11-01 01:00:00 -06:00        2020-11-01 02:00:00 -06:00
```

### PR DESCRIPTION
**Pull request by zhaoyim**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?
a fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

this change is for the scalar function to_iso8601.

> How would you describe this change to a non-technical end user or system administrator?
pick a valid time even if there's ambiguity

## Related issues, pull requests, and links
Fixes https://github.com/trinodb/trino/issues/11619

## Documentation

(x) No documentation is needed.

## Release notes

(x) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix incorrect result for {func}`to_iso8601` when the timestamp is in the 
  daylight savings transition region. ({issue}`11619`)
```

### CODE REVIEW

**Comment by zhaoyim** [comment]
image
I already send the CLA to the board, so far not got the response. Could anyone help? Thanks!

**Comment by ebyhr** [comment]
@cla-bot check

**Review by martint — CHANGES_REQUESTED** [review]
The offset is not incorrect. The problem is that there are actually two valid offsets for times in that gap (the offset before the DST change and the one after the clock moved back)

The proper fix for this is to make the function fail for those ambiguous timestamps. Here's a related issue: https://github.com/trinodb/trino/issues/5781

**Comment by zhaoyim** [comment]
@martint  Thanks for response！If make the function fail for the ambiguous timestamps, how about the correct SQL for the ambiguous timestamps? Yes, there are 2 valid offset, but no matter choose which one, the offset + the convert time should be equal the input time. 
For example(as the issue mentioned):
```
SELECT to_iso8601(timestamp '2020-11-01 06:00 UTC' AT TIME ZONE 'America/Chicago')
    ,  to_iso8601(timestamp '2020-11-01 07:00 UTC' AT TIME ZONE 'America/Chicago')
    ,  to_iso8601(timestamp '2020-11-01 08:00 UTC' AT TIME ZONE 'America/Chicago')
```

Expacted
```
2020-11-01T01:00:00-05:00(1+5=6)     2020-11-01T01:00:00-06:00(1+6=7)    2020-11-01T02:00:00-06:00(2+6=8)
```
Actual
```
2020-11-01T01:00:00-05:00(1+5=6)      2020-11-01T01:00:00-05:00(1+5!=7, this is not correct)    2020-11-01T02:00:00-06:00(2+6=8)
```

**Comment by martint** [comment]
Yes, agreed that it's incorrect. We can have the code pick a valid time (even if there's ambiguity), by updating ToIso8601 to do this instead:

```java
long picoFraction = ((long) getMillisOfSecond(epochMillis)) * PICOSECONDS_PER_MILLISECOND + picosOfMilli;

ZonedDateTime dateTime = ZonedDateTime.ofInstant(Instant.ofEpochMilli(epochMillis), zoneId);
ZoneOffset offset = dateTime.getOffset();
if (offset.getTotalSeconds() % 60 != 0) {
    throw new TrinoException(INVALID_ARGUMENTS, "Timezone with non-zero seconds offset cannot be rendered as ISO8601: " + offset.getId());
}

return DateTimes.formatTimestamp(precision, dateTime.toLocalDateTime(), picoFraction, ISO8601_FORMATTER, builder -> builder.append(offset));
```

This ensures that the selected offset is consistent with the localtime derived for the underlying instant.

**Comment by zhaoyim** [comment]
@martint Thanks for your suggestion! Your code worked well. I followed your changes. Thanks!

File: core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestTimestampWithTimeZone.java [hunk 1]
```diff
@@ -1987,6 +1987,14 @@ public void testToIso8601()
...
                 .isEqualTo("2020-05-01T12:34:56.123456789012+05:45");
 
+        assertThat(assertions.expression("to_iso8601(TIMESTAMP '2020-11-01 07:00:00.123456789012 UTC' AT TIME ZONE 'America/Chicago')"))
+                .hasType(createVarcharType(41))
+                .isEqualTo("2020-11-01T01:00:00.123456789012-06:00");
+
+        assertThat(assertions.expression("to_iso8601(TIMESTAMP '2020-11-01 07:00 UTC' AT TIME ZONE 'America/Chicago')"))
+                .hasType(createVarcharType(28))
+                .isEqualTo("2020-11-01T01:00:00-06:00");
+
```
Comment (martint) [inline core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestTimestampWithTimeZone.java:1997]: Can you add tests for all precisions? See examples above. Also, please add a comment before all those tests explaining that this tests timestamps that fall in the DST gap.

**Review by martint — COMMENTED** [review]
Thanks for updating it. I just had some comments about the tests and this will be good to go.

File: core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestTimestampWithTimeZone.java (hunk 1 above)
Comment (zhaoyim) [reply core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestTimestampWithTimeZone.java]: Thanks for your comments! Updated the test cases.
