### PR TITLE
Fix race condition in BinPackingNodeAllocator

### LINKED ISSUE #11876: TestDistributedFaultTolerantEngineOnlyQueries: tried to release more than allocated
```
2022-04-04T09:37:22.484-0500	ERROR	pool-5-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST FAILURE] io.trino.tests.TestDistributedFaultTolerantEngineOnlyQueries.testUnionRequiringCoercion; (took: 1.1 seconds)
java.lang.AssertionError: Execution of 'actual' query failed: SELECT * FROM (VALUES (2, 2)) UNION SELECT * FROM (VALUES (1, 1.0))
	at org.testng.Assert.fail(Assert.java:83)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:248)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:243)
	at io.trino.testing.AbstractTestEngineOnlyQueries.testUnionRequiringCoercion(AbstractTestEngineOnlyQueries.java:5721)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: tried to release more than allocated (1073741824 vs null) for node 638624cd-df26-421a-b87c-d818c0b2d9a0
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:527)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 17 more
	Suppressed: java.lang.Exception: SQL: SELECT * FROM (VALUES (2, 2)) UNION SELECT * FROM (VALUES (1, 1.0))
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:530)
		... 18 more
Caused by: com.google.common.base.VerifyException: tried to release more than allocated (1073741824 vs null) for node 638624cd-df26-421a-b87c-d818c0b2d9a0
	at com.google.common.base.Verify.verify(Verify.java:436)
	at io.trino.execution.scheduler.BinPackingNodeAllocatorService.lambda$updateAllocatedMemory$1(BinPackingNodeAllocatorService.java:238)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at io.trino.execution.scheduler.BinPackingNodeAllocatorService.updateAllocatedMemory(BinPackingNodeAllocatorService.java:235)
	at io.trino.execution.scheduler.BinPackingNodeAllocatorService$BinPackingNodeLease.release(BinPackingNodeAllocatorService.java:299)
	at io.trino.execution.scheduler.FaultTolerantStageScheduler.updateTaskStatus(FaultTolerantStageScheduler.java:545)
	at io.trino.execution.scheduler.FaultTolerantStageScheduler.lambda$startTask$7(FaultTolerantStageScheduler.java:372)
	at io.trino.execution.StateMachine.fireStateChangedListener(StateMachine.java:241)
	at io.trino.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:233)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by losipiuk**
Fix race condition in BinPackingNodeAllocator where
BinPackingNodeLease.release() could subtract from entry in
allocatedMemory map before processPendingAcquires added to this entry.

With changed allocation/deallocation protocol it is no longer possible.

> Is this change a fix, improvement, new feature, refactoring, or other?

fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

core engine

## Related issues, pull requests, and links

fixes #11876

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

### CODE REVIEW

File: core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java [hunk 1]
```diff
@@ -580,6 +580,20 @@ public void testAllocateWithRuntimeMemoryEstimateOverhead()
...
 
+    @Test
+    public void testStressAcquireRelease()
+    {
+        InMemoryNodeManager nodeManager = testingNodeManager(basicNodesMap(NODE_1));
+        setupNodeAllocatorService(nodeManager, DataSize.of(4, GIGABYTE));
+
+        try (NodeAllocator nodeAllocator = nodeAllocatorService.getNodeAllocator(SESSION)) {
+            for (int i = 0; i < 10_000_000; ++i) {
+                NodeAllocator.NodeLease acquire1 = nodeAllocator.acquire(REQ_32);
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java:591]: rename variable

File: core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java [hunk 2]
```diff
@@ -378,6 +379,16 @@ public void release()
                 throw new IllegalStateException("Node " + node + " already released");
             }
         }
+
+        public void deallocateMemory(InternalNode node)
+        {
+            // guarding deallocation on atomic boolean.
+            // Otherwise, memory could be deallocated twice in case of race between
+            // call to BinPackingNodeLease.release() and deallocation in processPendingAcquires().
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java:387]: I'd go without comment

- "guarding deallocation on atomic boolean" -- this is exactly what the code is doing, obvious 
- "Otherwise, memory could be deallocated twice" -- well, this is part is also obvious
- "BinPackingNodeLease.release() and deallocation in processPendingAcquires()." -- redundant, the callers are easily findable via "Call Hierarchy".

**Review by findepi — APPROVED** [review]

**Review by arhimondr — APPROVED** [review]
