### PR TITLE
Fix OrcWriterOptions mapping from Hive TableProperties

### LINKED ISSUE #9792: ORC bloom filter in Trino working?
I created a transactional table in ORC Format with a bloom filter for some columns in Hive, and inserted some rows in Trino.

But the bloom filter is not created in the ORC file.

Inspecting some code, I found some problems in the following.

https://github.com/trinodb/trino/blob/8f5aa1cbca7393eadfbbf3d81b57587b9a933793/plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java#L1017-L1037

1) The schema parameter does not contains keys ORC_BLOOM_FILTER_COLUMNS("orc_bloom_filter_columns") and ORC_BLOOM_FILTER_FPP("orc_bloom_filter_fpp"), but contains ORC_BLOOM_FILTER_COLUMNS_KEY("orc.bloom.filter.columns") and ORC_BLOOM_FILTER_FPP_KEY("orc.bloom.filter.fpp")

2) Keys of Properties is checked using contains() not containsKey()

3) Throw exception when fpp value is in valid range(>0.0 and <1.0)

               if (fpp > 0.0 && fpp < 1.0) {
                    throw new TrinoException(HIVE_UNSUPPORTED_FORMAT, format("Invalid value for bloom filter: %f", fpp));
                }

According to code, bloom filter options in ORCWriteOptions are never set when creating an OrcFileWriter object.

### PR DESCRIPTION
**Pull request by Praveen2112**
Fixes #9792

### CODE REVIEW

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java [hunk 1]
```diff
@@ -1022,9 +1022,6 @@ public static OrcWriterOptions getOrcWriterOptions(Properties schema, OrcWriterO
             }
             try {
                 double fpp = parseDouble(schema.getProperty(ORC_BLOOM_FILTER_FPP));
-                if (fpp > 0.0 && fpp < 1.0) {
```
Comment (dain) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java:1025]: Is this check invalid or redundant?  If redundant, then state that instead of saying invalid.  If invalid, state why instead of saying there is a similar check somewhere.... either way update the commit message.

File: pom.xml [hunk 2]
```diff
@@ -1718,7 +1718,6 @@
                                     <!-- -Xep:ReferenceEquality:OFF fails in IDEA --> \
                                     <!-- -Xep:BoxedPrimitiveEquality:OFF fails in IDEA --> \
                                     -Xep:GuardedBy:OFF <!-- needs some careful inspection --> \
-                                    -Xep:HashtableContains:OFF <!-- https://github.com/trinodb/trino/pull/7001 --> \
```
Comment (dain) [inline pom.xml:1721]: Is this related to this PR?  Just checking

**Review by dain — APPROVED** [review]

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java (hunk 1 above)
Comment (Praveen2112) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java:1025]: applied comments.

File: pom.xml (hunk 2 above)
Comment (Praveen2112) [reply pom.xml:1721]: It is too small to be extracted as a different PR.

Comment (ksobolew) [reply pom.xml:1721]: Yes, this PR fixes the issue flagged by this Error Prone check.

**Review by dain — APPROVED** [review]
