### PR TITLE
Fix wrong handling for NaN on partitioned columns in Iceberg

### LINKED ISSUE #15723: Iceberg connector stores `0.0` when inserting `NaN` on partitioned real or double columns
Read logic also needs fixes. Both `floatValue` & `doubleValue` methods in Jackson `JsonNode` class methods return `0.0` for non-number nodes.
```sql
trino> CREATE TABLE default.test_double (engine varchar, part double) WITH (partitioning =
array['part']);
trino> INSERT INTO default.test_double VALUES ('trino', double 'NaN');
spark> INSERT INTO default.test_double VALUES ('spark', cast('NaN' as double));

trino> SELECT * FROM default.test_double;
 engine | part
--------+------
 trino  |  0.0
 spark  |  0.0

trino> SELECT * FROM default."test_double$partitions";
 partition  | record_count | file_count | total_size |                             data
------------+--------------+------------+------------+---------------------------------------------------------------
 {part=0.0} |            1 |          1 |        425 | {engine={min=trino, max=trino, null_count=0, nan_count=NULL}}
 {part=NaN} |            1 |          1 |        389 | {engine={min=spark, max=spark, null_count=0, nan_count=NULL}}

spark> SELECT * FROM default.test_double;
spark	NaN
trino	0.0
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #15723

Both `floatValue` & `doubleValue` methods in Jackson JsonNode class methods return 0.0 for non-number nodes.
`SqlJsonLiteralConverter` also calls those methods, but `NaN` value was handled as `JsonNodeType.STRING` and it returns the expected value (`TestSqlJsonLiteralConverter` already ensures the value).  

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Iceberg
* Fix incorrect results when reading or writing `NaN` with `real` or `double` types on partitioned columns. ({issue}`15723`)
```

### CODE REVIEW

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java [hunk 1]
```diff
@@ -139,8 +139,14 @@ public static Object getValue(JsonNode partitionValue, Type type)
             case TIME:
                 return partitionValue.asLong();
             case FLOAT:
+                if (partitionValue.asText().equals("NaN")) {
```
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java:142]: can the nan be written as "nan" or "naN" ?

**Review by findepi — APPROVED** [review]

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java:142]: It won't be as far as I read Iceberg and Avro codes.
