### PR TITLE
Fix errors caused by predicates pushdown on MongoDB JSON columns

### LINKED ISSUE #13536: Predicates on JSON column fails in MongoDB connector
We can just disable the pushdown on json column in MongoDB connector. `TestMongoTypeMapping` needs a new test method for json type when fixing this issue. 

```sql
CREATE TABLE test (c1 json);
INSERT INTO test VALUES (json '{"id":0,"name":"user_0"}');

SELECT * FROM test WHERE c1 = json '{"id":0,"name":"user_0"}';
java.lang.UnsupportedOperationException
	at io.trino.spi.predicate.ValueSet.getRanges(ValueSet.java:122)
	at io.trino.plugin.mongodb.MongoSession.buildPredicate(MongoSession.java:438)
	at io.trino.plugin.mongodb.MongoSession.buildQuery(MongoSession.java:417)
	at io.trino.plugin.mongodb.MongoSession.execute(MongoSession.java:398)
	at io.trino.plugin.mongodb.MongoPageSource.<init>(MongoPageSource.java:108)
	at io.trino.plugin.mongodb.MongoPageSourceProvider.createPageSource(MongoPageSourceProvider.java:59)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:268)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:196)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:338)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:325)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$3(WorkProcessorUtils.java:219)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:240)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$4(WorkProcessorUtils.java:234)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:150)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_testversion____20220808_001654_36.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by silly-carbon**
## Description

Fix errors caused by predicates pushdown on MongoDB JSON columns

> Is this change a fix, improvement, new feature, refactoring, or other?
fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
This is a change to the MongoDB connector only

> How would you describe this change to a non-technical end user or system administrator?
The MongoDB connector no longer causes errors on predicates on JSON columns

## Related issues, pull requests, and links

* Fixes #13536
* Related documentation: None needed

## Documentation

( ) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# MongoDB
* Fix failure for queries filtering on columns with `json` type. ({issue}`13536`)
```

### CODE REVIEW

File: plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java [hunk 1]
```diff
@@ -433,6 +433,11 @@ private static Optional<Document> buildPredicate(MongoColumnHandle column, Domai
             return Optional.of(documentOf(name, isNotNullPredicate()));
         }
 
+        // Disable pushdown on json columns, see https://github.com/trinodb/trino/issues/13536
```
Comment (ebyhr) [inline plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java:436]: It would be better to fix `io.trino.plugin.mongodb.MongoMetadata#applyFilter` instead.

File: plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java [hunk 2]
```diff
@@ -433,6 +433,11 @@ private static Optional<Document> buildPredicate(MongoColumnHandle column, Domai
...
+        if (TypeUtils.isJsonType(type)) {
```
Comment (ebyhr) [inline plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java:437]: Static import `isJsonType`. The method name is descriptive without the class name.

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java [hunk 3]
```diff
@@ -311,6 +311,15 @@ public void testArrayNulls()
         }
     }
 
+    @Test
+    public void testJSON()
```
Comment (ebyhr) [inline plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java:315]: Rename to `testJson`.

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java [hunk 4]
```diff
@@ -311,6 +311,15 @@ public void testArrayNulls()
...
+    {
+        // Verify only SELECT instead of using SqlDataTypeTest to avoid MongoDB json cast failures
```
Comment (ebyhr) [inline plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java:317]: `SqlDataTypeTest` with `trinoCreateAsSelect` and `trinoCreateAndInsert` works well as far as I confirmed. What error did you face?

**Review by ebyhr — COMMENTED** [review]
Could you change the commit title and body to 
```
Disable predicate pushdown on MongoDB json columns

The query failed when building MongoDB query.
```

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java (hunk 4 above)
Comment (silly-carbon) [reply plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java:317]: I wrote the test case like this in the first place:
```
        SqlDataTypeTest.create()
                .addRoundTrip("json", "'{\"id\":0,\"name\":\"user_0\"}'", JSON, "'{\"id\":0,\"name\":\"user_0\"}'")
                .execute(getQueryRunner(), trinoCreateAsSelect("test_json"))
                .execute(getQueryRunner(), trinoCreateAndInsert("test_json"));
```
This is the generated SQL:
```
CREATE TABLE test_jsonjxn0mmcfdl AS SELECT CAST('{"id":0,"name":"user_0"}' AS json) col_0
```
And it failed with reason:
```
io.trino.spi.TrinoException: Can't convert json to MongoDB Document: "{\"id\":0,\"name\":\"user_0\"}"
	at io.trino.plugin.mongodb.MongoPageSink.getObjectValue(MongoPageSink.java:188)
	at io.trino.plugin.mongodb.MongoPageSink.appendPage(MongoPageSink.java:112)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:257)
	at io.trino.operator.Driver.processInternal(Driver.java:415)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:703)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:737)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_testversion____20220821_012151_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.bson.BsonInvalidOperationException: readStartDocument can only be called when CurrentBSONType is DOCUMENT, not when CurrentBSONType is STRING.
	at org.bson.AbstractBsonReader.verifyBSONType(AbstractBsonReader.java:689)
	at org.bson.AbstractBsonReader.checkPreconditions(AbstractBsonReader.java:721)
	at org.bson.AbstractBsonReader.readStartDocument(AbstractBsonReader.java:449)
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:174)
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:44)
	at org.bson.Document.parse(Document.java:126)
	at org.bson.Document.parse(Document.java:111)
	at io.trino.plugin.mongodb.MongoPageSink.getObjectValue(MongoPageSink.java:185)
	... 14 more
```

File: plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java (hunk 1 above)
Comment (silly-carbon) [reply plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java:436]: OK, that would be better

File: plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java (hunk 2 above)
Comment (silly-carbon) [reply plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java:437]: Yeah, this could be simplified

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java (hunk 3 above)
Comment (silly-carbon) [reply plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java:315]: Yeah, but what are the considerations behind this? I thought JSON is like just any other acronyms (NASA? ASCII?)

**Comment by silly-carbon** [comment]
@ebyhr Hello there, I've made some updates(according to your previous comments) to the code and wish to get your feedback😁

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java (hunk 4 above)
Comment (ebyhr) [reply plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java:317]: Thanks for sharing the example. Prepending `json ` in literals makes the test work. 
```java
.addRoundTrip("json", "json '{\"id\":0,\"name\":\"user_0\"}'", JSON, "json '{\"id\":0,\"name\":\"user_0\"}'")
```

Comment (silly-carbon) [reply plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java:317]: > Thanks for sharing the example. Prepending `json ` in literals makes the test work.
> 
> ```java
> .addRoundTrip("json", "json '{\"id\":0,\"name\":\"user_0\"}'", JSON, "json '{\"id\":0,\"name\":\"user_0\"}'")
> ```

Yes, this totally works as expected, thanks.

Comment (silly-carbon) [reply plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java:317]: Case 1: the original issue, https://github.com/trinodb/trino/issues/13536

Case 2: when case 1 is solved, it only means that a json filter would not cause errors when building the query, but the filter may be eliminated entirely(which is not correct, so a new test should be fired to ensure this filter is still working)

the previous test which used only "SELECT": solves both case 1 and 2 (2 rows are inserted and only 1 row is back)
SqlDataTypeTest: solves only case 1 (at lease for now)

Comment (ebyhr) [reply plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java:317]: `SqlDataTypeTest` has `verifyPredicate`. Note that the current `SELECT` base doesn't cover whether the predicate is pushed down or not either.

Comment (silly-carbon) [reply plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java]: OK, code changed.

I've seen the intrinsic logics of `SqlDataTypeTest`, they are very marvelous ~~

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java [hunk 5]
```diff
@@ -311,6 +312,15 @@ public void testArrayNulls()
         }
     }
 
+    @Test
+    public void testJson()
+    {
+        SqlDataTypeTest.create()
+                .addRoundTrip("json", "json '{\"id\":0,\"name\":\"user_0\"}'", JSON, "json '{\"id\":0,\"name\":\"user_0\"}'")
```
Comment (ebyhr) [inline plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java:319]: Let's add some special cases:
```java
                .addRoundTrip("json", "json '{}'", JSON, "json '{}'")
                .addRoundTrip("json", "CAST(NULL AS json)", JSON, "CAST(NULL AS json)")
```

File: plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java [hunk 6]
```diff
@@ -339,6 +343,31 @@ public Optional<ConstraintApplicationResult<ConnectorTableHandle>> applyFilter(C
...
+        else {
+            Map<ColumnHandle, Domain> domains = newDomain.getDomains().orElseThrow();
+
+            Map<ColumnHandle, Domain> supported = new HashMap<>();
+            Map<ColumnHandle, Domain> unsupported = new HashMap<>();
+
+            for (Map.Entry<ColumnHandle, Domain> entry : domains.entrySet()) {
+                Type columnType = ((MongoColumnHandle) entry.getKey()).getType();
+                if (isJsonType(columnType)) {
+                    // Disable pushdown on json columns, see https://github.com/trinodb/trino/issues/13536
```
Comment (ebyhr) [inline plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java:360]: "Disable pushdown on json columns" is obvious without this comment. Let's leave TODO comment instead.
```
// TODO: Support predicate pushdown on JSON type column
```

**Review by ebyhr — APPROVED** [review]

File: plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java (hunk 6 above)
Comment (silly-carbon) [reply plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java]: OK, that's better

**Comment by silly-carbon** [comment]
@ebyhr Thanks for the comments, I've updated the code.

By the way, please take a look at the CLA mailbox, I believe I've sent a signed PDF 😁

**Comment by ebyhr** [comment]
@cla-bot check

**Comment by ebyhr** [comment]
Could you confirm CI failures?

**Comment by silly-carbon** [comment]
> Could you confirm CI failures?
@ebyhr 
Failures solved.

Made changes to `io.trino.plugin.mongodb.MongoMetadata#applyFilter` to explicitly distinguish between supported and unsupported types

**Comment by ebyhr** [comment]
Merged, thanks!
