### PR TITLE
Fix calculateOffsetRanges in parquet page filtering

### LINKED ISSUE #9097: io.trino.spi.TrinoException: Failed reading parquet data: Socket is closed by peer
After upgrading to 361, I'm facing an issue when running a fairly straight forward query:
```
SELECT * FROM some_table WHERE some_column = 'some_value' LIMIT 10
```
However, if I remove `WHERE` clause, it works as expected.

I have verified that parquet file is not corrupted in any way, and is indeed readable. Same query, using the same data source works as expected in v360.

Here's the full error:

```
io.trino.spi.TrinoException: Failed reading parquet data; source= s3://<REDACTED>; can not read class org.apache.parquet.format.PageHeader: Socket is closed by peer.
	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:230)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:396)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:375)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:282)
	at io.trino.operator.project.DictionaryAwarePageFilter.filter(DictionaryAwarePageFilter.java:59)
	at io.trino.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:121)
	at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:293)
	at io.trino.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:245)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:151)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_361____20210901_181740_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: can not read class org.apache.parquet.format.PageHeader: Socket is closed by peer.
	at org.apache.parquet.format.Util.read(Util.java:365)
	at org.apache.parquet.format.Util.readPageHeader(Util.java:132)
	at org.apache.parquet.format.Util.readPageHeader(Util.java:127)
	at io.trino.parquet.reader.ParquetColumnChunk.readPageHeader(ParquetColumnChunk.java:76)
	at io.trino.parquet.reader.ParquetColumnChunk.readAllPages(ParquetColumnChunk.java:89)
	at io.trino.parquet.reader.ParquetReader.createPageReader(ParquetReader.java:388)
	at io.trino.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:368)
	at io.trino.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:444)
	at io.trino.parquet.reader.ParquetReader.readBlock(ParquetReader.java:427)
	at io.trino.plugin.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
	... 39 more
Caused by: io.trino.hive.$internal.parquet.org.apache.thrift.transport.TTransportException: Socket is closed by peer.
	at io.trino.hive.$internal.parquet.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:130)
	at io.trino.hive.$internal.parquet.org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at io.trino.hive.$internal.parquet.org.apache.thrift.protocol.TCompactProtocol.readByte(TCompactProtocol.java:635)
	at io.trino.hive.$internal.parquet.org.apache.thrift.protocol.TCompactProtocol.readFieldBegin(TCompactProtocol.java:541)
	at org.apache.parquet.format.InterningProtocol.readFieldBegin(InterningProtocol.java:155)
	at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:1026)
	at org.apache.parquet.format.PageHeader$PageHeaderStandardScheme.read(PageHeader.java:1019)
	at org.apache.parquet.format.PageHeader.read(PageHeader.java:896)
	at org.apache.parquet.format.Util.read(Util.java:362)
	... 48 more
```

`SET SESSION hive.parquet_ignore_statistics = true` seems to bypass the issue. And the query works as expected on v361.

### PR DESCRIPTION
**Pull request by raunaqmorarka**
Fixes the failure scenario identified in https://github.com/trinodb/trino/issues/9382
Fixes #9097

### CODE REVIEW

**Comment by findepi** [comment]
@raunaqmorarka can you add "Fixes https://github.com/trinodb/trino/issues/9097" in the description?

File: lib/trino-parquet/src/main/java/io/trino/parquet/reader/FilteredOffsetIndex.java [hunk 1]
```diff
@@ -112,29 +112,22 @@ public String toString()
...
-                else if (currentOffset + currentLength == offset) {
+                if (currentOffset + currentLength == offset) {
                     currentLength += length;
                 }
                 else {
                     ranges.add(new OffsetRange(currentOffset, currentLength));
-                    currentOffset = -1;
-                    currentLength = 0;
+                    currentOffset = offset;
+                    currentLength = length;
```
Comment (findepi) [inline lib/trino-parquet/src/main/java/io/trino/parquet/reader/FilteredOffsetIndex.java:127]: Looks like this would be the minimal fix, right?

I like other changes, but would be nice to separate actual bugfix from readability improvement.

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java [hunk 2]
```diff
@@ -118,7 +139,7 @@ private int assertSameResults(String query)
                         .setCatalogSessionProperty(getSession().getCatalog().get(), "parquet_use_column_index", "false")
                         .build(),
                 query);
-        assertEquals(withColumnIndexing, withoutColumnIndexing);
+        assertEqualsIgnoreOrder(withColumnIndexing, withoutColumnIndexing);
```
Comment (findepi) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java:142]: Extract as prep commit, since it fixes pre-exsiting bug in the test.

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java [hunk 3]
```diff
@@ -88,6 +88,27 @@ public void testAndPredicates()
         assertUpdate("DROP TABLE " + tableName);
     }
 
+    @Test
+    public void testRandomData()
```
Comment (findepi) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java:92]: Give it a meaningful name. What makes this test worthy keeping?

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java [hunk 4]
```diff
@@ -88,6 +88,27 @@ public void testAndPredicates()
...
+                        "SELECT * FROM unnest(transform(repeat(1, 8192), x -> rand()))",
+                updateCount);
+        for (int i = 0; i < 8; i++) {
+            assertUpdate(
+                    "INSERT INTO " + tableName + " SELECT rand() FROM " + tableName,
+                    updateCount);
+            updateCount += updateCount;
+        }
+        for (double i = 0; i < 1; i += 0.1) {
+            assertSameResults(format("SELECT * FROM %s WHERE col BETWEEN %f AND %f", tableName, i - 0.0001, i + 0.0001));
```
Comment (findepi) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java:107]: `assertSameResults` is not meaningful name, since it doesn't tell "same as .." ?

let's call it `assertColumnIndexResults`

**Review by findepi — APPROVED** [review]

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java (hunk 2 above)
Comment (raunaqmorarka) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java:144]: done

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java (hunk 3 above)
Comment (raunaqmorarka) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java]: updated name and added a comment

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java (hunk 4 above)
Comment (raunaqmorarka) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java]: added a prep commit which renames this

File: lib/trino-parquet/src/main/java/io/trino/parquet/reader/FilteredOffsetIndex.java (hunk 1 above)
Comment (raunaqmorarka) [reply lib/trino-parquet/src/main/java/io/trino/parquet/reader/FilteredOffsetIndex.java:127]: Yes, I confirmed by running tests that this would fix it too.
If you don't mind, I'd prefer to keep the change in current commit though as I found it easier to follow the logic after simplification of the loop.

Comment (findepi) [reply lib/trino-parquet/src/main/java/io/trino/parquet/reader/FilteredOffsetIndex.java:127]: Yes, i find your code more readable. However, i think it would be better to

- have minimal change fixing the problem (those two lines), along with test you added
- have next commit do the readability refactor

this way, someone else looking at the fix commit, will have it easy to understand what was the problem about (we were losing offset,length pairs)

Comment (raunaqmorarka) [reply lib/trino-parquet/src/main/java/io/trino/parquet/reader/FilteredOffsetIndex.java:127]: I've separated the simplification into another commit now

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
@raunaqmorarka can you please rebase to resolve conflict with https://github.com/trinodb/trino/pull/9357 ?

**Comment by raunaqmorarka** [comment]
> @raunaqmorarka can you please rebase to resolve conflict with #9357 ?

done

**Comment by lhofhansl** [comment]
+1 I can confirm that my test case is fixed.

**Comment by raunaqmorarka** [comment]
Test failure is due to https://github.com/trinodb/trino/issues/7919

**Review by JamesRTaylor — APPROVED** [review]
Good find, @raunaqmorarka. The fix looks good to me.
