### PR TITLE
Get Data compression only for non-indexed SQL Server tables

### LINKED ISSUE #6464: SQL Server "Expected zero to one elements, but found multiple"
SQL Query fails with a simple select * from to any table on the database.
Also tried multiple instances of SQL Server.

imagen

There is no error when the table it's empty:

imagen

Trino:
```
java.lang.IllegalStateException: Expected zero to one elements, but found multiple
	at org.jdbi.v3.core.result.ResultIterable.findOne(ResultIterable.java:163)
	at io.prestosql.plugin.sqlserver.SqlServerClient.getTableDataCompression(SqlServerClient.java:437)
	at io.prestosql.plugin.sqlserver.SqlServerClient.getTableProperties(SqlServerClient.java:378)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getTableProperties(ForwardingJdbcClient.java:288)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableProperties(StatisticsAwareJdbcClient.java:305)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.getTableProperties(CachingJdbcClient.java:365)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.getTableProperties(CachingJdbcClient.java:365)
	at io.prestosql.plugin.jdbc.JdbcMetadata.getTableMetadata(JdbcMetadata.java:344)
	at io.prestosql.metadata.MetadataManager.getTableMetadata(MetadataManager.java:508)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1231)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.Table.accept(Table.java:53)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2529)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1553)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:356)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1061)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:329)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:346)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:315)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:263)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:186)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:768)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:129)
	at io.prestosql.$gen.Presto_350____20211229_170343_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by Praveen2112**
Fixes #6464

### CODE REVIEW

File: presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java [hunk 1]
```diff
@@ -417,6 +417,30 @@ public void testShowCreateForPartitionedTablesWithDataCompression()
...
+                "   key3 BIGINT NOT NULL,\n" +
+                "   key4 BIGINT NOT NULL,\n" +
+                "   key5 BIGINT NOT NULL,\n" +
+                "   CONSTRAINT PK_IndexedTable PRIMARY KEY CLUSTERED (key1),\n" +
+                "   CONSTRAINT IX_IndexedTable UNIQUE (key2, key3),\n" +
+                "   INDEX IX_MyTable4 NONCLUSTERED (key4, key5))\n" +
+                "   WITH (DATA_COMPRESSION = PAGE)");
+
+        assertThat((String) computeActual("SHOW CREATE TABLE IndexedTable").getOnlyValue())
+                .matches("CREATE TABLE \\w+\\.\\w+\\.indexedtable \\Q(\n" +
```
Comment (ssheikin) [inline presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java:435]: It's harder to compare text with regexp. 
It's easier to compare text with text.

Please consider 
`.matches` -> `isEqualTo`, 
`\\w+\\.\\w+\\.` -> `getSession().getCatalog().orElseThrow() + "." + getSession().getSchema().orElseThrow() + "." + `
May be extract common sql part.

My version is here https://github.com/starburstdata/starburst-presto/pull/1870/files#diff-43bde5e16ff97c2e1a6bc5ff0861404572ef8c0db16580d69d4d544610b4a23dR253

File: presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java [hunk 2]
```diff
@@ -428,9 +428,10 @@ public void setNull(PreparedStatement statement, int index)
         return handle.createQuery("" +
                 "SELECT data_compression_desc FROM sys.partitions p " +
                 "INNER JOIN sys.tables t ON p.object_id = t.object_id " +
+                "INNER JOIN sys.schemas s ON t.schema_id = s.schema_id " +
                 "INNER JOIN sys.indexes i ON t.object_id = i.object_id " +
-                "WHERE SCHEMA_NAME(t.schema_id) = :schema AND t.name = :table_name AND i.type IN (0,1) " +
-                "AND i.data_space_id NOT IN (SELECT data_space_id FROM sys.partition_schemes)")
+                "WHERE s.name = :schema AND t.name = :table_name AND p.index_id = 0 AND i.type = 0 " +
```
Comment (ssheikin) [inline presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java:433]: > `p.index_id = 0 AND i.type = 0`

why do you need this check? 

just for the info:

> sys.partitions.index_id
> Indicates the ID of the index within the object to which this partition belongs.
> 0 = heap
> 1 = clustered index
> 2 or greater = nonclustered index
> https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-partitions-transact-sql?view=sql-server-ver15

> sys.indexes.type 
> Type of index:
> 0 = Heap
> 1 = Clustered
> 2 = Nonclustered
> 3 = XML
> 4 = Spatial
> 5 = Clustered columnstore index. Applies to: SQL Server 2014 (12.x) and later.
> 6 = Nonclustered columnstore index. Applies to: SQL Server 2012 (11.x) and later.
> 7 = Nonclustered hash index. Applies to: SQL Server 2014 (12.x) and later.
> https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-indexes-transact-sql?view=sql-server-ver15

Comment (Praveen2112) [reply presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java:433]: Currently we have planned to support only for Heap tables. So we have restricted for other types of object

File: presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java [hunk 3]
```diff
@@ -417,6 +417,30 @@ public void testShowCreateForPartitionedTablesWithDataCompression()
...
+    @Test
+    public void testShowCreateForIndexedNonPartitionedTablesWithDataCompression()
+    {
+        sqlServer.execute("CREATE TABLE IndexedTable (\n" +
+                "   key1 BIGINT NOT NULL,\n" +
+                "   key2 BIGINT NOT NULL,\n" +
+                "   key3 BIGINT NOT NULL,\n" +
+                "   key4 BIGINT NOT NULL,\n" +
+                "   key5 BIGINT NOT NULL,\n" +
+                "   CONSTRAINT PK_IndexedTable PRIMARY KEY CLUSTERED (key1),\n" +
```
Comment (ssheikin) [inline presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java:429]: Maybe it worth to create separate test `testShowCreateForIndexedTablesAreNotSupportedYet` just to underline that current test fails not because of data compression once such support is implemented?

File: presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java (hunk 2 above)
Comment (ssheikin) [reply presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java:433]: could you please add two `/* Heap */` comments near `= 0`

File: presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java [hunk 4]
```diff
@@ -428,8 +428,9 @@ public void setNull(PreparedStatement statement, int index)
         return handle.createQuery("" +
                 "SELECT data_compression_desc FROM sys.partitions p " +
                 "INNER JOIN sys.tables t ON p.object_id = t.object_id " +
+                "INNER JOIN sys.schemas s ON t.schema_id = s.schema_id " +
                 "INNER JOIN sys.indexes i ON t.object_id = i.object_id " +
-                "WHERE SCHEMA_NAME(t.schema_id) = :schema AND t.name = :table_name AND i.type IN (0,1) " +
```
Comment (findepi) [inline presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java:432]: replacing SCHEMA_NAME with INNER JOIN sys.schemas looks like independent change.
please split this into 2 commits?

File: presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java (hunk 2 above)
Comment (findepi) [reply presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java:433]: Good idea to add a comment:
```
"WHERE s.name = :schema AND t.name = :table_name " +
"AND p.index_id = 0 " + // ....
"AND i.type = 0 " // 0 means Heap index type
```

File: presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java [hunk 5]
```diff
@@ -417,6 +417,30 @@ public void testShowCreateForPartitionedTablesWithDataCompression()
...
+                "   CONSTRAINT IX_IndexedTable UNIQUE (key2, key3),\n" +
+                "   INDEX IX_MyTable4 NONCLUSTERED (key4, key5))\n" +
+                "   WITH (DATA_COMPRESSION = PAGE)");
+
+        assertThat((String) computeActual("SHOW CREATE TABLE IndexedTable").getOnlyValue())
+                .matches("CREATE TABLE sqlserver\\.dbo\\.indexedtable \\Q(\n" +
```
Comment (findepi) [inline presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java:435]: matches -> isEqualTo

File: presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java [hunk 6]
```diff
@@ -417,6 +417,30 @@ public void testShowCreateForPartitionedTablesWithDataCompression()
                         ")");
     }
 
+    @Test
+    public void testShowCreateForNonIndexedNonPartitionedTablesWithDataCompression()
+    {
+        sqlServer.execute("CREATE TABLE IndexedTable (\n" +
```
Comment (findepi) [inline presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java:423]: IndexedTable -> test_show_indexed_table

File: presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java [hunk 7]
```diff
@@ -417,6 +417,30 @@ public void testShowCreateForPartitionedTablesWithDataCompression()
                         ")");
     }
 
+    @Test
+    public void testShowCreateForNonIndexedNonPartitionedTablesWithDataCompression()
```
Comment (findepi) [inline presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java:421]: > NonIndexed

the test table is called indexed. is it indexed or non-indexed?

> NonPartitioned

remove

> TablesWithDataCompression

CompressedTable

File: presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java (hunk 2 above)
Comment (ssheikin) [reply presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java:433]: I think comments within sql fit better here.

**Comment by Praveen2112** [comment]
@findepi && @ssheikin AC

File: presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java [hunk 8]
```diff
@@ -417,6 +417,30 @@ public void testShowCreateForPartitionedTablesWithDataCompression()
                         ")");
     }
 
+    @Test
+    public void testShowCreateForIndexedAndCompressedTable()
```
Comment (ssheikin) [inline presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java:421]: Please add comment that `SHOW CREATE TABLE` does not support indices and table compression yet.

**Review by ssheikin — APPROVED** [review]
% comment

File: presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java [hunk 9]
```diff
@@ -428,8 +428,11 @@ public void setNull(PreparedStatement statement, int index)
...
+                "WHERE s.name = :schema AND t.name = :table_name " +
+                "AND p.index_id = 0 " + // Heap
```
Comment (ssheikin) [inline presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java:434]: nit: this comment belongs to java now. Once sql code is copied to sql editor comment is lost. I still think that it has to be within sql.

File: presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java (hunk 2 above)
Comment (findepi) [reply presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java]: @ssheikin no need to send our comments to SQL Server, is there?

**Review by findepi — APPROVED** [review]

File: presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java (hunk 2 above)
Comment (ssheikin) [reply presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java]: You are right. Is it expensive?

Comment (findepi) [reply presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java]: Not at all. Just redundant.

**Review by kokosing — APPROVED** [review]
Let's go with this one instead of https://github.com/trinodb/trino/pull/6473

File: plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java [hunk 10]
```diff
@@ -415,6 +415,8 @@ public void testShowCreateForPartitionedTablesWithDataCompression()
                         "   salesdate date,\n" +
                         "   quantity integer\n" +
                         ")");
+
+        assertUpdate("DROP TABLE partitionedSales");
```
Comment (kokosing) [inline plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java:418]: don't you need to drop `pfSales` and `psSales`? The best would be to use `io.trino.testing.sql.TestTable` (modified somehow) for things like that.

**Review by kokosing — APPROVED** [review]
% comments

**Review by ssheikin — APPROVED** [review]

**Review by kokosing — APPROVED** [review]

**Review by findepi — APPROVED** [review]
