### PR TITLE
Fix test flakiness

### LINKED ISSUE #19198: TestDeltaLakeFileOperations.testSelfJoin flaky
```
 Error:  io.trino.plugin.deltalake.TestDeltaLakeFileOperations.testSelfJoin -- Time elapsed: 0.556 s <<< FAILURE!
java.lang.AssertionError: 
Expected: 
		1 more occurrences of FileOperation[fileType=DATA, fileId=no partition, operationType=INPUT_FILE_NEW_STREAM]
	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.MultisetAssertions.assertMultisetsEqual(MultisetAssertions.java:52)
	at io.trino.plugin.deltalake.TestDeltaLakeFileOperations.assertFileSystemAccesses(TestDeltaLakeFileOperations.java:639)
	at io.trino.plugin.deltalake.TestDeltaLakeFileOperations.assertFileSystemAccesses(TestDeltaLakeFileOperations.java:630)
	at io.trino.plugin.deltalake.TestDeltaLakeFileOperations.testSelfJoin(TestDeltaLakeFileOperations.java:281)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

https://github.com/trinodb/trino/actions/runs/6344560785/job/17235464113?pr=19196#step:6:24700

### PR DESCRIPTION
**Pull request by findinpath**
## Description

In case that the dynamic filtering was finishing fast enough, the second scan on `test_self_join_table` was not being performed anymore because there was no purpose in doing so, given that the result was empty anyway. Adapt the content of the `test_self_join_table` to actually return a result so that the scanning of the data files is actually performed twice for each occurrence of the table in the JOIN operation.

## Additional context and related issues

Fixes #19198

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java [hunk 1]
```diff
@@ -276,10 +276,10 @@ public void testReadWholePartition()
     @Test
     public void testSelfJoin()
     {
-        assertUpdate("CREATE TABLE test_self_join_table AS SELECT 2 as age, 0 parent, 3 AS id", 1);
+        assertUpdate("CREATE TABLE test_self_join_table(name, manager_id, id) AS VALUES ('Mary', NULL, 1), ('John', 1, 2)", 2);
 
         assertFileSystemAccesses(
-                "SELECT child.age, parent.age FROM test_self_join_table child JOIN test_self_join_table parent ON child.parent = parent.id",
+                "SELECT employee.name, manager.name FROM test_self_join_table employee JOIN test_self_join_table manager ON employee.manager_id = manager.id",
```
Comment (findepi) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java:282]: Why would it prevent DF from short-circuiting?

also, can we simply disable DF for the test query?

**Comment by findepi** [comment]
@findinpath thank you

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java (hunk 1 above)
Comment (findinpath) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java:282]: @raunaqmorarka pointed out that this might be related to the extended stats causing the pruning.

Comment (findepi) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java:282]: > might be related to the extended stats causing the pruning.

extended stats cannot cause pruning, since they are just estimates, rigt?

Comment (findepi) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java:282]: > Do you rather prefer it this way?

yes

Comment (findinpath) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java]: > extended stats cannot cause pruning, since they are just estimates, right?

Correct. My bad. The split predicate is built from the `add` statistics from the transaction log.

https://github.com/trinodb/trino/blob/29ee2a541623071265b7c740caa3e796d946bf99/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitSource.java#L117-L128

https://github.com/trinodb/trino/blob/29ee2a541623071265b7c740caa3e796d946bf99/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java#L219-L222

**Review by findepi — APPROVED** [review]
