### PR TITLE
Fix failure to read nullable time(6) columns

### LINKED ISSUE #15603: Iceberg Connector does not properly support nullable TIME columns using ORC
Querying an ORC file with a TIME column containing both null and non-null values results in an exception similar to the following:

```
java.lang.VerifyError: Unsupported type time(6)
	at io.trino.orc.reader.LongColumnReader.readNullBlock(LongColumnReader.java:199)
	at io.trino.orc.reader.LongColumnReader.readBlock(LongColumnReader.java:144)
	at io.trino.orc.OrcBlockFactory$OrcBlockLoader.load(OrcBlockFactory.java:76)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:407)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:386)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:293)
	at io.trino.plugin.hive.orc.OrcPageSource$SourceColumn$MaskingBlockLoader.load(OrcPageSource.java:390)
	at io.trino.spi.block.LazyBlock$LazyData.load(LazyBlock.java:407)
	at io.trino.spi.block.LazyBlock$LazyData.getFullyLoadedBlock(LazyBlock.java:386)
	at io.trino.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:293)
	at io.trino.spi.Page.getLoadedPage(Page.java:230)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:314)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:752)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:519)
	at io.trino.$gen.Trino_405____20230104_215851_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

io.trino.orc.reader.LongColumnReader appears to have a method for reading all-non-null data(readNonNullBlock) and a method for reading partially-null data (readNullBlock). It does not appear that support for TimeType was ever added to the method which handles partially null data.

### PR DESCRIPTION
**Pull request by joejensen**
## Description
Fixes #15603 

## Additional context and related issues

Fixes issue where ORC files containing nullable Iceberg TIME columns could throw an exception when being read.  Also fixed an error in the ORC file validator where time columns did not validate correctly in order to add appropriate tests for the Time type.

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Iceberg
* Fix Iceberg query failure when reading ORC files with nullable `time` columns. ({issue}`15606`)
```

### CODE REVIEW

**Review by ebyhr — COMMENTED** [review]
Could you add a test in Iceberg connector as well?

**Comment by joejensen** [comment]
Added relevant test in the Iceberg connector.

**Comment by joejensen** [comment]
Rebased onto current master.

**Comment by bitsondatadev** [comment]
@raunaqmorarka are you able to review this?

**Comment by joejensen** [comment]
Rebasing to resolve merge conflict in TestIcebergOrcConnectorTest.

Anything I can do to help get this merged?

**Comment by bitsondatadev** [comment]
@joejensen looking into it now.

File: lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/TimeStatisticsBuilder.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ */
+package io.trino.orc.metadata.statistics;
+
+import io.trino.spi.block.Block;
+import io.trino.spi.type.Type;
+
+import static io.trino.spi.type.Timestamps.PICOSECONDS_PER_MICROSECOND;
+
+public class TimeStatisticsBuilder
+        extends IntegerStatisticsBuilder
```
Comment (raunaqmorarka) [inline lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/TimeStatisticsBuilder.java:22]: We usually avoid using inheritance to share code. This should implement LongValueStatisticsBuilder along similar lines as TimestampStatisticsBuilder

File: lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/TimeStatisticsBuilder.java [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+        implements LongValueStatisticsBuilder
+{
+    private long nonNullValueCount;
+    private long minimum = Long.MAX_VALUE;
+    private long maximum = Long.MIN_VALUE;
+    private long sum;
+    private boolean overflow;
+    private final BloomFilterBuilder bloomFilterBuilder;
+
+    public TimeStatisticsBuilder(BloomFilterBuilder bloomFilterBuilder)
```
Comment (raunaqmorarka) [inline lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/TimeStatisticsBuilder.java:36]: TimeMicrosStatisticsBuilder

File: lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/TimeStatisticsBuilder.java [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+            null,
+            integerStatistics.orElse(null),
+            null,
+            null,
+            null,
+            null,
+            null,
+            null,
+            null,
+            bloomFilterBuilder.buildBloomFilter());
```
Comment (raunaqmorarka) [inline lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/TimeStatisticsBuilder.java:90]: we can populate `null` here and drop the `bloomFilterBuilder`

File: lib/trino-orc/src/main/java/io/trino/orc/OrcWriteValidation.java [hunk 4]
```diff
@@ -628,6 +630,11 @@ else if (VARBINARY.equals(type) || UUID.equals(type)) {
                 fieldExtractor = ignored -> ImmutableList.of();
                 fieldBuilders = ImmutableList.of();
             }
+            else if (TIME_MICROS.equals(type)) {
+                statisticsBuilder = new TimeStatisticsBuilder(new NoOpBloomFilterBuilder());
```
Comment (raunaqmorarka) [inline lib/trino-orc/src/main/java/io/trino/orc/OrcWriteValidation.java:634]: I think we're supposed to use the same class for building statistics in the writer and in the validation. Since we're not changing the writer, I think this should use IntegerStatisticsBuilder. Would dropping the `/ PICOSECONDS_PER_MICROSECOND` in other places in the tests allow using `IntegerStatisticsBuilder` here ?

**Comment by ebyhr** [comment]
@joejensen Could you rebase on master to resolve conflicts?

**Comment by ebyhr** [comment]
Rebased on master to resolve conflicts and addressed comments except for https://github.com/trinodb/trino/pull/15606#discussion_r1148468176

File: lib/trino-orc/src/main/java/io/trino/orc/OrcWriteValidation.java (hunk 4 above)
Comment (ebyhr) [reply lib/trino-orc/src/main/java/io/trino/orc/OrcWriteValidation.java]: @raunaqmorarka Using `IntegerStatisticsBuilder` leads to overflow when calculating sum as far as I confirmed. Could you look into the details?

Comment (raunaqmorarka) [reply lib/trino-orc/src/main/java/io/trino/orc/OrcWriteValidation.java]: I added a change to use TimeMicrosStatisticsBuilder in ColumnWriters instead. This makes the writer consistent with the validation logic

**Review by raunaqmorarka — COMMENTED** [review]
This lgtm, but would be great to get another pair of eyes on it

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java [hunk 5]
```diff
@@ -135,6 +135,25 @@ private void testReadSingleIntegerColumnOrcFile(String orcFileResourceName, int
...
 
+    @Test
+    public void testTimeType()
+            throws Exception
+    {
+        try (TestTable table = new TestTable(getQueryRunner()::execute, "test_time", "(\"_col0\") AS VALUES " +
+                "(TIME '10:03:34.123000'), (NULL), (NULL), (NULL), (TIME '10:03:34.123000'), (TIME '10:03:34.123000')")) {
+            String orcFilePath = (String) computeScalar(format("SELECT DISTINCT file_path FROM \"%s$files\"", table.getName()));
+            try (OutputStream outputStream = fileSystem.newOutputFile(Location.of(orcFilePath)).createOrOverwrite()) {
+                Files.copy(new File(getResource("single-time-column.orc").toURI()).toPath(), outputStream);
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java:146]: Does the file we're replacing and the `single-time-column.orc` have same length?

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java [hunk 6]
```diff
@@ -135,6 +135,25 @@ private void testReadSingleIntegerColumnOrcFile(String orcFileResourceName, int
         }
     }
 
+    @Test
+    public void testTimeType()
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java:139]: Anyway, what is this test testing? what's the role of `single-time-column.orc` file?
How was `single-time-column.orc` produced?

File: lib/trino-orc/src/test/java/io/trino/orc/OrcTester.java [hunk 7]
```diff
@@ -1351,6 +1377,25 @@ private static Type rowType(Type... fieldTypes)
         return TESTING_TYPE_MANAGER.getParameterizedType(StandardTypes.ROW, typeSignatureParameters.build());
     }
 
+    private static boolean isTime(Type type)
+    {
+        if (type.equals(TIME_MICROS)) {
+            return true;
+        }
+        if (type instanceof ArrayType arrayType) {
+            return isTime(arrayType.getElementType());
```
Comment (findepi) [inline lib/trino-orc/src/test/java/io/trino/orc/OrcTester.java:1386]: `isTime( "array(time)" )` feels wrong

rename `isTime` method to `containsTimeMicros`

File: lib/trino-orc/src/main/java/io/trino/orc/writer/ColumnWriters.java [hunk 8]
```diff
@@ -57,7 +58,7 @@ public static ColumnWriter createColumnWriter(
             checkArgument(timeType.getPrecision() == 6, "%s not supported for ORC writer", type);
             checkArgument(orcType.getOrcTypeKind() == LONG, "wrong ORC type %s for type %s", orcType, type);
             checkArgument("TIME".equals(orcType.getAttributes().get(ICEBERG_LONG_TYPE)), "wrong attributes %s for type %s", orcType.getAttributes(), type);
-            return new TimeColumnWriter(columnId, type, compression, bufferSize, () -> new IntegerStatisticsBuilder(bloomFilterBuilder.get()));
+            return new TimeColumnWriter(columnId, type, compression, bufferSize, () -> new TimeMicrosStatisticsBuilder(bloomFilterBuilder.get()));
```
Comment (findepi) [inline lib/trino-orc/src/main/java/io/trino/orc/writer/ColumnWriters.java:61]: This should involve testing SHOW STATS, since the manifest stats are populated from file stats

**Comment by findepi** [comment]
> Fixes #15603

@raunaqmorarka we should have connector-level test coverage for this.
Why `TestIcebergMinioOrcConnectorTest.testDataMappingSmokeTest` did not catch this for "time(6)" case?

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java (hunk 6 above)
Comment (ebyhr) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java:139]: We can reproduce the issue without `single-time-column.orc`
```sql
CREATE TABLE test (c1 time(6));
INSERT INTO test VALUES (TIME '13:30:00'), (TIME '14:30:00'), (NULL);
SELECT * FROM test;
-- Unsupported type time(6)
```

**Comment by raunaqmorarka** [comment]
> > Fixes #15603
> 
> @raunaqmorarka we should have connector-level test coverage for this. Why `TestIcebergMinioOrcConnectorTest.testDataMappingSmokeTest` did not catch this for "time(6)" case?

That is because of a quirk in that test's data setup and the way orc reader works. There is only 1 null in the setup and that is in the first row. The orc reader reads in batches of 1, 2, 4 ... rows. So the first batch is all nulls, while the 2nd batch is all non-nulls. This bug requires a batch containing null as well as non-null values to cause failure.
I think improving that should be tackled separately from this PR, there is sufficient testing here to land this.
