### PR TITLE
Fix failure when column names contain uppercase letters in table procedures

### LINKED ISSUE #28970: 480 regression: Table procedures throw "No handle found for column" when a table contains uppercase characters
### Trino version

480

### Please describe the bug

1536db9e700c288b2b8e78da420d613078e4cb04 introduced the bug. `getColumnHandles` method may contain uppercase keys, but `getTableMetadata` internally lowercases column names. 

Steps to reproduce: 
```sql
# Spark
CREATE TABLE test (X int) USING delta LOCATION 's3://test-bucket/test';
INSERT INTO test VALUES 1;
INSERT INTO test VALUES 2;

# Trino
ALTER TABLE delta.default.test EXECUTE optimize;
```

```
io.trino.spi.TrinoException: No handle found for column 'x' in table execute
	at io.trino.spi.connector.ConnectorMetadata.lambda$getColumnHandlesForTableExecute$0(ConnectorMetadata.java:159)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:723)
	at io.trino.spi.connector.ConnectorMetadata.getColumnHandlesForTableExecute(ConnectorMetadata.java:163)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getColumnHandlesForTableExecute(ClassLoaderSafeConnectorMetadata.java:227)
	at io.trino.tracing.TracingConnectorMetadata.getColumnHandlesForTableExecute(TracingConnectorMetadata.java:163)
	at io.trino.metadata.MetadataManager.getColumnHandlesForTableExecute(MetadataManager.java:370)
	at io.trino.tracing.TracingMetadata.getColumnHandlesForTableExecute(TracingMetadata.java:222)
	at io.trino.sql.planner.LogicalPlanner.createTableExecutePlan(LogicalPlanner.java:1005)
	at io.trino.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:386)
	at io.trino.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:349)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:248)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:241)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:236)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:502)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:482)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:420)
	at io.trino.execution.QueryManager.createQuery(QueryManager.java:317)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:151)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$1(LocalDispatchQuery.java:135)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$0(MoreFutures.java:570)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at io.trino.$gen.Trino_testversion____20260402_005703_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

1536db9 introduced this bug. The getColumnHandles method may return uppercase keys, while getTableMetadata internally lowercases column names.

* Fixes #28970

## Release notes

```markdown
## General, Iceberg, Delta Lake
* Fix failure when executing table procedures on tables with uppercase column names. ({issue}`28970`)
```

### CODE REVIEW

File: core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java [hunk 1]
```diff
@@ -149,17 +147,8 @@ default Optional<ConnectorTableExecuteHandle> getTableHandleForExecute(
...
-                .filter(not(ColumnMetadata::isHidden))
-                .map(ColumnMetadata::getName)
-                .map(columnName -> {
-                    ColumnHandle columnHandle = columnHandles.get(columnName);
-                    if (columnHandle == null) {
-                        throw new TrinoException(GENERIC_INTERNAL_ERROR, format("No handle found for column '%s' in table execute", columnName));
-                    }
-                    return columnHandle;
-                })
+        return getColumnHandles(connectorSession, tableHandle).values().stream()
```
Comment (findepi) [inline core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java:150]: Why do we have a default implementation of `getColumnHandlesForTableExecute` at all?
Can we just throw here?

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java [hunk 2]
```diff
@@ -878,6 +878,25 @@ public void testRequiresQueryPartitionFilterWithUppercaseColumnName()
...
+        copyDirectoryContents(new File(Resources.getResource("deltalake/case_sensitive").toURI()).toPath(), tableLocation);
+
+        assertUpdate("CALL system.register_table(CURRENT_SCHEMA, '%s', '%s')".formatted(tableName, tableLocation.toUri()));
+        assertQueryReturnsEmptyResult("SELECT * FROM " + tableName);
+
+        assertUpdate("INSERT INTO " + tableName + " VALUES (1, 11)", 1);
+        assertUpdate("INSERT INTO " + tableName + " VALUES (2, 22)", 1);
+
+        assertUpdate("ALTER TABLE " + tableName + " EXECUTE optimize");
+
```
Comment (chenjian2664) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java]: nit: add a query verify the table data is as expected

File: core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java (hunk 1 above)
Comment (ebyhr) [reply core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java:150]: This method was newly added in v480 and LogicalPlanner always calls it for table procedures. 

I believe @dain added a default implementation so that third-party developers don't need to implement it for existing procedures. 

Another approach was to return Optional type by default, but it requires further changes in SPI and LogicalPlanner.

**Comment by dain** [comment]
@ebyhr Thanks!
