### PR TITLE
Fix failure when non-lowercase column exists in BigQuery query function

### LINKED ISSUE #16075: Big query PTF queries fails when projection contains now lowercase column names
Description:

Big query polymorphic table function (PTF) query fails when the output projection of native query involves any non-lower case column names. 
Query `SELECT * FROM TABLE(bigquery.system.query(query => 'select 1 as lower, 2 as UPPER, 3 as miXED'))`

The above query throws an `Internal server exception` due to a mismatch in the following line since the Trino internal column name doesn't match the projected column name.
https://github.com/trinodb/trino/blob/406/plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java#L710

Another workaround without the fix is always to alias the column names to be lowercase.

### PR DESCRIPTION
**Pull request by RameshByndoor**
This patch fixes #16075 

I have taken the reference from the DefaultJdbcMetadata and it works with that approach.
Another workaround without the fix is always to alias the column names to be lowercase.

### CODE REVIEW

File: plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java [hunk 1]
```diff
@@ -709,6 +711,14 @@ public void testNativeQuerySimple()
                 "VALUES 1");
     }
 
+    @Test
+    public void testNativeQuerySelectForCaseSensitiveColumnNames()
+    {
+        MaterializedResult result = computeActual
+                ("SELECT * FROM TABLE(bigquery.system.query(query => 'select 1 as lower, 2 as UPPER, 3 as miXED'))");
```
Comment (ebyhr) [inline plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java:718]: Uppercase `select` and `as`. Also, please create a table instead of string literal and assert the rows in addition to the column names.

File: plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java [hunk 2]
```diff
@@ -709,6 +711,14 @@ public void testNativeQuerySimple()
...
+        assertTrue(result.getColumnNames().containsAll(ImmutableList.of("lower", "UPPER", "miXED")));
```
Comment (ebyhr) [inline plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java:719]: Please use `assertThat` method.

**Review by ebyhr — COMMENTED** [review]
The commit message is too long. Please follow this guideline. 
https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages

**Comment by ebyhr** [comment]
/test-with-secrets sha=8f5fbd8a832ddab7bc1a638b45dbd9d0a47a39f3

**Review by ebyhr — APPROVED** [review]
