### PR TITLE
Check duplicated field names in Iceberg

### LINKED ISSUE #16273: Iceberg connector can create tables having difference case fields in row types, but can't read it
It would be better to deny when creating tables. 
```sql
trino:tpch> CREATE TABLE test AS SELECT cast(row(1,2) AS row("X" int, x int)) col;
CREATE TABLE: 1 row

-- ORC
trino:tpch> TABLE test;
io.trino.spi.TrinoException: Error opening Iceberg split /var/folders/8s/dkvf18z55lj_9yxhy1n54sph0000gn/T/TrinoTest14995291286640599612/iceberg_data/tpch/test-71cbb7a701ab43fa9ef9bffe5fc77129/data/20230227_062327_00025_dg69i-beb13022-c1e7-4db3-b9e1-60190e22ceba.orc (offset=0, length=421): Multiple entries with same key: x=3 and x=2
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createOrcPageSource(IcebergPageSourceProvider.java:699)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createDataPageSource(IcebergPageSourceProvider.java:480)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:296)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:298)
	at io.trino.operator.Driver.processInternal(Driver.java:394)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:297)
	at io.trino.operator.Driver.tryWithLock(Driver.java:689)
	at io.trino.operator.Driver.process(Driver.java:289)
	at io.trino.operator.Driver.processForDuration(Driver.java:260)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_testversion____20230227_062239_36.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: x=3 and x=2
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:377)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:371)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:241)
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:132)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:94)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:573)
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:601)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:588)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:686)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider$IdBasedFieldMapperFactory.populateMapping(IcebergPageSourceProvider.java:849)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider$IdBasedFieldMapperFactory.<init>(IcebergPageSourceProvider.java:823)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createOrcPageSource(IcebergPageSourceProvider.java:657)

-- Parquet
io.trino.spi.TrinoException: Error opening Iceberg split /var/folders/8s/dkvf18z55lj_9yxhy1n54sph0000gn/T/TrinoTest14995291286640599612/iceberg_data/tpch/test-f1021397fddd4b5798961effbe0681fe/data/20230227_062436_00032_dg69i-d12244b7-cd3a-4fef-9136-da9f49d614f0.parquet (offset=0, length=337): Multiple entries with same key: [col, x] optional int32 x = 3=min: 2, max: 2, num_nulls: 0 and [col, x] optional int32 x = 3=min: 1, max: 1, num_nulls: 0
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createParquetPageSource(IcebergPageSourceProvider.java:1050)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createDataPageSource(IcebergPageSourceProvider.java:503)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:296)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:298)
	at io.trino.operator.Driver.processInternal(Driver.java:394)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:297)
	at io.trino.operator.Driver.tryWithLock(Driver.java:689)
	at io.trino.operator.Driver.process(Driver.java:289)
	at io.trino.operator.Driver.processForDuration(Driver.java:260)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:773)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:523)
	at io.trino.$gen.Trino_testversion____20230227_062239_36.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: [col, x] optional int32 x = 3=min: 2, max: 2, num_nulls: 0 and [col, x] optional int32 x = 3=min: 1, max: 1, num_nulls: 0
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:377)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:371)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:241)
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:132)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:94)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:573)
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:601)
	at io.trino.parquet.predicate.PredicateUtils.getStatistics(PredicateUtils.java:186)
	at io.trino.parquet.predicate.PredicateUtils.predicateMatches(PredicateUtils.java:142)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.createParquetPageSource(IcebergPageSourceProvider.java:933)
	... 17 more

-- Avro
    col
------------
 {X=1, x=2}
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

We should fix Delta Lake connector as a follow-up. 
Fixes #16273

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java [hunk 1]
```diff
@@ -2115,6 +2120,28 @@ private static boolean fieldExists(StructType structType, String fieldName)
...
+            checkDuplicatedFieldNames(arrayType.getElementType());
+        }
+        else if (type instanceof MapType mapType) {
+            checkDuplicatedFieldNames(mapType.getKeyType());
+            checkDuplicatedFieldNames(mapType.getValueType());
+        }
+        if (type instanceof RowType rowType) {
+            Set<String> fieldNames = new HashSet<>();
+            for (RowType.Field field : rowType.getFields()) {
+                field.getName().ifPresent(name -> {
```
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:2135]: `field.getName()` must be present. anonymous rows are not supported

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java [hunk 2]
```diff
@@ -6595,6 +6595,41 @@ public void testDeleteRetainsMetadataFile()
         assertUpdate("DROP TABLE " + tableName);
     }
 
+    @Test
+    @Override // Override because ambiguous field name is disallowed in the connector
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:6599]: ❤️  thank you for this comment

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java [hunk 3]
```diff
@@ -2115,6 +2120,28 @@ private static boolean fieldExists(StructType structType, String fieldName)
...
+    private static void checkDuplicatedFieldNames(io.trino.spi.type.Type type)
+    {
+        if (type instanceof ArrayType arrayType) {
+            checkDuplicatedFieldNames(arrayType.getElementType());
+        }
+        else if (type instanceof MapType mapType) {
+            checkDuplicatedFieldNames(mapType.getKeyType());
+            checkDuplicatedFieldNames(mapType.getValueType());
+        }
+        if (type instanceof RowType rowType) {
```
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:2132]: be consistent whether `else if` or separate `if`s
imo here `else if` would be more appropriate

**Review by findepi — APPROVED** [review]

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:2135]: I avoided throwing an exception because an empty field name is checked in a different place:
https://github.com/trinodb/trino/blob/abc57cc2921577ece33624abc5920a9bf99e5ab7/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TypeConverter.java#L182-L199

Comment (findepi) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:2135]: can we do both checks in one place?

**Review by anusudarsan — APPROVED** [review]
