### PR TITLE
Fix table props for Iceberg with orc_bloom_filter

### LINKED ISSUE #20432: Incorrect table properties set for Iceberg with orc_bloom_filter
We set `orc.bloom.filter.columns` instead of `write.orc.bloom.filter.columns`,
and `orc.bloom.filter.fpp` instead of `write.orc.bloom.filter.fpp`.

Spec: https://iceberg.apache.org/docs/latest/configuration/#write-properties
```bash
trino> CREATE TABLE test_metadata_write_properties (a bigint) WITH (
         format = 'orc',
         orc_bloom_filter_columns = array['a']);

$ jq '.properties' metadata/00000-01a10e5b-c4d9-4144-ba6d-5af151ae031c.metadata.json
{
  "orc.bloom.filter.columns": "a",
  "write.format.default": "ORC",
  "write.parquet.compression-codec": "zstd",
  "orc.bloom.filter.fpp": "0.05"
}
```

### PR DESCRIPTION
**Pull request by oneonestar**
## Description
This PR fix table properties for Iceberg table with orc_bloom_filter:

Fix #20432

## Additional context and related issues
The correct table properties should be:
`orc.bloom.filter.columns` -> `write.orc.bloom.filter.columns`
`orc.bloom.filter.fpp` -> `write.orc.bloom.filter.fpp`.

Spec: https://iceberg.apache.org/docs/latest/configuration/#write-properties

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
(x) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 1]
```diff
@@ -242,18 +244,41 @@ public static Map<String, Object> getIcebergTableProperties(Table icebergTable)
...
+            properties.put(ORC_BLOOM_FILTER_FPP, Double.parseDouble(orcBloomFilterFpp.get()));
         }
 
         return properties.buildOrThrow();
     }
 
+    // Version 382-436 set incorrect table properties: https://github.com/trinodb/trino/commit/b89aac68c43e5392f23b8d6ba053bbeb6df85028#diff-2af3e19a6b656640a7d0bb73114ef224953a2efa04e569b1fe4da953b2cc6d15R418-R419
+    // `orc.bloom.filter.columns` was set instead of `write.orc.bloom.filter.columns`, and `orc.bloom.filter.fpp` instead of `write.orc.bloom.filter.fpp`
+    // These methods maintain backward compatibility for existing table.
+    public static Optional<String> getOrcBloomFilterColumnsFixed(Map<String, String> properties)
```
Comment (findinpath) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:263]: `getOrcBloomFilterColumnsFixed` -> `getOrcBloomFilterColumns`

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 2]
```diff
@@ -242,18 +244,41 @@ public static Map<String, Object> getIcebergTableProperties(Table icebergTable)
...
+    {
+        Optional<String> orcBloomFilterColumns = Stream.of(
+                    properties.get(TableProperties.ORC_BLOOM_FILTER_COLUMNS),
+                    properties.get(BROKEN_ORC_BLOOM_FILTER_COLUMNS_KEY))
+                .filter(Objects::nonNull)
+                .findFirst();
+        return orcBloomFilterColumns;
+    }
+
+    public static Optional<String> getOrcBloomFilterFppFixed(Map<String, String> properties)
```
Comment (findinpath) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:273]: `getOrcBloomFilterFppFixed` -> `getOrcBloomFilterFpp`

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 3]
```diff
@@ -662,8 +687,8 @@ public static Map<String, String> createTableProperties(ConnectorTableMetadata t
         if (!columns.isEmpty()) {
             checkFormatForProperty(fileFormat.toIceberg(), FileFormat.ORC, ORC_BLOOM_FILTER_COLUMNS);
             validateOrcBloomFilterColumns(tableMetadata, columns);
-            propertiesBuilder.put(ORC_BLOOM_FILTER_COLUMNS_KEY, Joiner.on(",").join(columns));
-            propertiesBuilder.put(ORC_BLOOM_FILTER_FPP_KEY, String.valueOf(getOrcBloomFilterFpp(tableMetadata.getProperties())));
+            propertiesBuilder.put(TableProperties.ORC_BLOOM_FILTER_COLUMNS, Joiner.on(",").join(columns));
```
Comment (findinpath) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:690]: static import

**Comment by findinpath** [comment]
LGTM % comments

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java [hunk 4]
```diff
@@ -315,8 +315,10 @@ public class IcebergMetadata
     private static final String UNKNOWN_SNAPSHOT_TOKEN = "UNKNOWN";
     public static final Set<String> UPDATABLE_TABLE_PROPERTIES = ImmutableSet.of(FILE_FORMAT_PROPERTY, FORMAT_VERSION_PROPERTY, PARTITIONING_PROPERTY, SORTED_BY_PROPERTY);
 
-    public static final String ORC_BLOOM_FILTER_COLUMNS_KEY = "orc.bloom.filter.columns";
-    public static final String ORC_BLOOM_FILTER_FPP_KEY = "orc.bloom.filter.fpp";
+    // For backward compatibility only. DO NOT USE.
```
Comment (findinpath) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:318]: Let's move those constants to `IcebergUtil` and make them private

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java (hunk 3 above)
Comment (oneonestar) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:690]:
```
io.trino.plugin.iceberg.IcebergTableProperties.ORC_BLOOM_FILTER_COLUMNS
org.apache.iceberg.TableProperties.ORC_BLOOM_FILTER_COLUMNS
```
We have a name conflict here so we can't static import both.

I thought about refactor the mapping logic between Trino session properties and Iceberg table properties.
The current mapping logic is a bit messy and across multiple classes.
However, the changes will be big so it's better to do it in another PR.

Comment (ndrluis) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:690]: @oneonestar What do you think about suffixing the ORC Trino session properties with _PROPERTY (as is already done with the other properties) and importing ORC_BLOOM_FILTER_COLUMNS and ORC_BLOOM_FILTER_FPP from org.apache.iceberg.TableProperties into IcebergTableProperties, and then importing them here?

This approach would maintain the pattern that already exists, and it would make things easier for me in the #20393 PR to add the constant that holds the iceberg table properties.

Subsequently, we could revisit how we deal with both kinds of properties.

What are your thoughts on this?

Comment (oneonestar) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java]: @ndrluis Thanks for the suggestion.
Rename Trino session properties with `_PROPERTY` make a lot of sense.

> importing ORC_BLOOM_FILTER_COLUMNS and ORC_BLOOM_FILTER_FPP from org.apache.iceberg.TableProperties into IcebergTableProperties, and then importing them here?

I don't understand why these properties are needed in IcebergTableProperties.

I did the change in https://github.com/trinodb/trino/pull/20433/commits/eddb7e8ab7e4052ea378f099553ca01f7548e3ff . Please take a look.

**Review by ndrluis — APPROVED** [review]

**Review by findinpath — APPROVED** [review]

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcWithBloomFilters.java [hunk 5]
```diff
@@ -39,4 +46,26 @@ protected String getTableProperties(String bloomFilterColumnName, String bucketi
                 bloomFilterColumnName,
                 bucketingColumnName);
     }
+
+    @Test
+    public void testMetadataWriteProperties()
```
Comment (findinpath) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcWithBloomFilters.java:51]: `testMetadataWriteProperties` -> `testBloomFilterPropertiesArePersistedDuringCreate`

**Review by wendigo — APPROVED** [review]

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java [hunk 6]
```diff
@@ -4714,6 +4716,36 @@ protected void verifyIcebergTableProperties(MaterializedResult actual)
         assertEqualsIgnoreOrder(actual.getMaterializedRows(), expected.getMaterializedRows());
     }
 
+    @Test
+    public void testGetIcebergTableWithLegacyOrcBloomFilterProperties()
+            throws Exception
```
Comment (ebyhr) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:4721]: Redundant.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java [hunk 7]
```diff
@@ -4714,6 +4716,36 @@ protected void verifyIcebergTableProperties(MaterializedResult actual)
...
+                tableMetadata.spec(),
+                tableMetadata.sortOrder(),
+                tableMetadata.location(),
+                newProperties);
+        TableMetadataParser.overwrite(newTableMetadata, new ForwardingOutputFile(fileSystem, Location.of(metadataLocation)));
+
+        MaterializedResult actualCreateTable = computeActual("SHOW CREATE TABLE " + tableName);
+        assertThat(actualCreateTable).isNotNull();
+        assertThat(actualCreateTable.getMaterializedRows().getFirst().toString())
+                .contains(ImmutableList.of("orc_bloom_filter_columns", "orc_bloom_filter_fpp"));
```
Comment (ebyhr) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:4746]: We could simplify like below:
```java
        assertThat((String) computeScalar("SHOW CREATE TABLE " + tableName))
                .contains("orc_bloom_filter_columns", "orc_bloom_filter_fpp");
```

Same for TestIcebergOrcWithBloomFilters.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java (hunk 6 above)
Comment (oneonestar) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:4721]: https://github.com/trinodb/trino/pull/20908

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java (hunk 7 above)
Comment (oneonestar) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:4746]: https://github.com/trinodb/trino/pull/20908
