### PR TITLE
Fix column comments in Accumulo connector

### LINKED ISSUE #14095: Accumulo connector ignores column comments when creating a new table
```sql
> CREATE TABLE test (c1 int COMMENT 'foo', c2 int COMMENT 'bar');
CREATE TABLE

> SHOW CREATE TABLE test;
                         Create Table
---------------------------------------------------------------
 CREATE TABLE accumulo.tpch.test (
    c1 integer COMMENT 'Accumulo row ID',
    c2 integer COMMENT 'Accumulo column c2:c2. Indexed: false'
 )
```

See `io.trino.plugin.accumulo.AccumuloClient#getColumnHandles`

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fix column comments in Accumulo connector
Fixes #14095 

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Accumulo
* Show column mapping and index information in extra field instead of comment. ({issue}`14095`)
* Support column comments when creating a new table. ({issue}`14114`)
```

### CODE REVIEW

File: plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloClient.java [hunk 1]
```diff
@@ -351,6 +352,7 @@ private static List<AccumuloColumnHandle> getColumnHandles(ConnectorTableMetadat
                                 cm.getType(),
                                 ordinal,
                                 comment,
```
Comment (ebyhr) [inline plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloClient.java:354]: I will rename this variable to `extraInfo`

**Review by hashhar — APPROVED** [review]
