### PR TITLE
Set hbase.client.retries.number as 15 in testing Phoenix server

### LINKED ISSUE #7216: Flaky test TestPhoenixTypeMapping with phoenix5

### LINKED ISSUE #9199: Flaky phoenix5's TestPhoenixConnectorTest.testStddevAggregationPushdown test
https://github.com/trinodb/trino/runs/3564747062

```
Error:  Tests run: 230, Failures: 1, Errors: 0, Skipped: 52, Time elapsed: 408.893 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.phoenix5.TestPhoenixConnectorTest.testStddevAggregationPushdown  Time elapsed: 1.112 s  <<< FAILURE!
java.lang.RuntimeException: 
org.apache.phoenix.exception.PhoenixIOException: Failed after attempts=4, exceptions:
2021-09-10T07:41:03.515Z, RpcRetryingCaller{globalStartTime=1631259663509, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1.1588230740 is closing
	at org.apache.hadoop.hbase.regionserver.HRegion.startRegionOperation(HRegion.java:8455)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2972)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2967)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2961)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2569)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

```

### LINKED ISSUE #11303: Flaky phoenix5's test TestPhoenixConnectorTest. testDataMappingSmokeTest
https://github.com/trinodb/trino/runs/5406847639?check_suite_focus=true 

```
2022-03-03T07:07:14.381-0600 SEVERE [TEST FAILURE] io.trino.plugin.phoenix5.TestPhoenixConnectorTest.testDataMappingSmokeTest [char(3)]; (took: 4.8 seconds)
java.lang.RuntimeException: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=4, exceptions:
2022-03-03T13:07:13.643Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1.1588230740 is closing
	at org.apache.hadoop.hbase.regionserver.HRegion.startRegionOperation(HRegion.java:8455)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2972)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2967)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2961)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2569)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

2022-03-03T13:07:13.746Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.exceptions.RegionMovedException: Region moved to: hostname=fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net port=43483 startCode=1646312524573. As of locationSeqNum=1042.
2022-03-03T13:07:13.950Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1 is not online on fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net,43483,1646312524573
	at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegionByEncodedName(HRegionServer.java:3382)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegion(HRegionServer.java:3359)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.getRegion(RSRpcServices.java:1467)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2545)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

2022-03-03T13:07:14.252Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.exceptions.RegionMovedException: Region moved to: hostname=fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net port=43483 startCode=1646312524573. As of locationSeqNum=1042.

	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:506)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:271)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:266)
	at io.trino.testing.BaseConnectorTest.testDataMapping(BaseConnectorTest.java:2700)
	at io.trino.testing.BaseConnectorTest.testDataMappingSmokeTest(BaseConnectorTest.java:2645)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: SQL: DROP TABLE test_data_mapping_smoke_char_3__jb66q5kams
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:509)
		... 18 more
Caused by: io.trino.spi.TrinoException: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=4, exceptions:
2022-03-03T13:07:13.643Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1.1588230740 is closing
	at org.apache.hadoop.hbase.regionserver.HRegion.startRegionOperation(HRegion.java:8455)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2972)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2967)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2961)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2569)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

2022-03-03T13:07:13.746Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.exceptions.RegionMovedException: Region moved to: hostname=fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net port=43483 startCode=1646312524573. As of locationSeqNum=1042.
2022-03-03T13:07:13.950Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1 is not online on fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net,43483,1646312524573
	at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegionByEncodedName(HRegionServer.java:3382)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegion(HRegionServer.java:3359)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.getRegion(RSRpcServices.java:1467)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2545)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

2022-03-03T13:07:14.252Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.exceptions.RegionMovedException: Region moved to: hostname=fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net port=43483 startCode=1646312524573. As of locationSeqNum=1042.

	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:879)
	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:865)
	at io.trino.plugin.phoenix5.PhoenixClient.execute(PhoenixClient.java:237)
	at io.trino.plugin.jdbc.BaseJdbcClient.dropTable(BaseJdbcClient.java:736)
	at io.trino.plugin.jdbc.BaseJdbcClient.dropTable(BaseJdbcClient.java:730)
	at io.trino.plugin.phoenix5.PhoenixMetadata.dropTable(PhoenixMetadata.java:252)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.dropTable(ClassLoaderSafeConnectorMetadata.java:374)
	at io.trino.metadata.MetadataManager.dropTable(MetadataManager.java:794)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:94)
	at io.trino.execution.DropTableTask.execute(DropTableTask.java:36)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_testversion____20220303_130214_3.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.RuntimeException: Query: DROP TABLE "TPCH"."TEST_DATA_MAPPING_SMOKE_CHAR_3__JB66Q5KAMS"
		at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:880)
		... 16 more
Caused by: org.apache.phoenix.exception.PhoenixIOException: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=4, exceptions:
2022-03-03T13:07:13.643Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1.1588230740 is closing
	at org.apache.hadoop.hbase.regionserver.HRegion.startRegionOperation(HRegion.java:8455)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2972)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2967)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2961)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2569)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

2022-03-03T13:07:13.746Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.exceptions.RegionMovedException: Region moved to: hostname=fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net port=43483 startCode=1646312524573. As of locationSeqNum=1042.
2022-03-03T13:07:13.950Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1 is not online on fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net,43483,1646312524573
	at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegionByEncodedName(HRegionServer.java:3382)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegion(HRegionServer.java:3359)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.getRegion(RSRpcServices.java:1467)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2545)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

2022-03-03T13:07:14.252Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.exceptions.RegionMovedException: Region moved to: hostname=fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net port=43483 startCode=1646312524573. As of locationSeqNum=1042.

	at org.apache.phoenix.util.ServerUtil.parseServerException(ServerUtil.java:138)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.dropTables(ConnectionQueryServicesImpl.java:2182)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.dropTable(ConnectionQueryServicesImpl.java:2070)
	at org.apache.phoenix.schema.MetaDataClient.dropTable(MetaDataClient.java:3450)
	at org.apache.phoenix.schema.MetaDataClient.dropTable(MetaDataClient.java:3358)
	at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableDropTableStatement$1.execute(PhoenixStatement.java:1243)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:441)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:423)
	at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
	at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:422)
	at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:410)
	at org.apache.phoenix.jdbc.PhoenixStatement.execute(PhoenixStatement.java:1986)
	at io.trino.plugin.jdbc.BaseJdbcClient.execute(BaseJdbcClient.java:876)
	... 16 more
Caused by: org.apache.hadoop.hbase.HBaseIOException: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=4, exceptions:
2022-03-03T13:07:13.643Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1.1588230740 is closing
	at org.apache.hadoop.hbase.regionserver.HRegion.startRegionOperation(HRegion.java:8455)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2972)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2967)
	at org.apache.hadoop.hbase.regionserver.HRegion.getScanner(HRegion.java:2961)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2642)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2569)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

2022-03-03T13:07:13.746Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.exceptions.RegionMovedException: Region moved to: hostname=fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net port=43483 startCode=1646312524573. As of locationSeqNum=1042.
2022-03-03T13:07:13.950Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.NotServingRegionException: org.apache.hadoop.hbase.NotServingRegionException: hbase:meta,,1 is not online on fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net,43483,1646312524573
	at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegionByEncodedName(HRegionServer.java:3382)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.getRegion(HRegionServer.java:3359)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.getRegion(RSRpcServices.java:1467)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2545)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:42274)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

2022-03-03T13:07:14.252Z, RpcRetryingCaller{globalStartTime=1646312833640, pause=100, maxAttempts=4}, org.apache.hadoop.hbase.exceptions.RegionMovedException: Region moved to: hostname=fv-az127-974.5aj0erdmsgperguxzqs1t2u5da.phxx.internal.cloudapp.net port=43483 startCode=1646312524573. As of locationSeqNum=1042.

	at org.apache.hadoop.hbase.master.procedure.AbstractStateMachineTableProcedure.preflightChecks(AbstractStateMachineTableProcedure.java:177)
	at org.apache.hadoop.hbase.master.procedure.DisableTableProcedure.<init>(DisableTableProcedure.java:80)
	at org.apache.hadoop.hbase.master.HMaster$11.run(HMaster.java:2366)
	at org.apache.hadoop.hbase.master.procedure.MasterProcedureUtil.submitProcedure(MasterProcedureUtil.java:134)
	at org.apache.hadoop.hbase.master.HMaster.disableTable(HMaster.java:2349)
	at org.apache.hadoop.hbase.master.MasterRpcServices.disableTable(MasterRpcServices.java:755)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:418)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:133)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:338)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:318)

```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Set `hbase.client.retries.number` as 15 in testing Phoenix server to fix flaky tests.

## Related issues, pull requests, and links

* Fixes #11303
* Fixes #7216
* Fixes #9199

## Documentation

(x) No documentation is needed.

## Release notes

(x) No release notes entries required.

### CODE REVIEW

**Comment by ebyhr** [comment]
3/100 failed due to #10904
https://github.com/trinodb/trino/actions/runs/1932443666

**Comment by ebyhr** [comment]
100/100 succeeded https://github.com/trinodb/trino/actions/runs/1932848182

**Comment by ebyhr** [comment]
100/100 succeeded https://github.com/trinodb/trino/actions/runs/1933431236

**Comment by ebyhr** [comment]
1/100 failed due to #11344
https://github.com/trinodb/trino/runs/5430335432

**Comment by ebyhr** [comment]
Some flaky issues still exist, but #11303, #7216 and #9199 looks disappeared.

File: plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestingPhoenixServer.java [hunk 1]
```diff
@@ -89,7 +89,7 @@ private TestingPhoenixServer()
         this.conf.set("hbase.security.logger", "ERROR");
         this.conf.setInt(MASTER_INFO_PORT, -1);
         this.conf.setInt(REGIONSERVER_INFO_PORT, -1);
-        this.conf.setInt(HBASE_CLIENT_RETRIES_NUMBER, 1);
+        this.conf.setInt(HBASE_CLIENT_RETRIES_NUMBER, 15);
```
Comment (hashhar) [inline plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestingPhoenixServer.java:92]: The default value is 15 according to https://hbase.apache.org/book.html (`hbase.client.retries.number`). Can we instead remove this config?

**Review by hashhar — APPROVED** [review]
LGTM % comment.

File: plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestingPhoenixServer.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestingPhoenixServer.java:92]: I would specify explicitly to use the same number between 4 and 5. The default number differs in two versions.
