### PR TITLE
Fix Hudi query runners

### LINKED ISSUE #14340: Fix broken main method in Hudi query runners
Both `HudiQueryRunner` and `S3HudiQueryRunner` fail:
```
java.nio.file.NoSuchFileException: src/test/resources/hudi-testing-data
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base/java.nio.file.Files.walk(Files.java:3918)
	at java.base/java.nio.file.Files.walk(Files.java:3973)
	at io.trino.plugin.hudi.testing.ResourceHudiTablesInitializer.copyDir(ResourceHudiTablesInitializer.java:137)
	at io.trino.plugin.hudi.testing.ResourceHudiTablesInitializer.initializeTables(ResourceHudiTablesInitializer.java:72)
	at io.trino.plugin.hudi.HudiQueryRunner.createHudiQueryRunner(HudiQueryRunner.java:83)
	at io.trino.plugin.hudi.HudiQueryRunner.main(HudiQueryRunner.java:94)
```

### PR DESCRIPTION
**Pull request by codope**
## Description

Fixes #14340 

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java [hunk 1]
```diff
@@ -13,6 +13,7 @@
  */
 package io.trino.plugin.hudi;
 
+import com.google.common.collect.ImmutableList;
```
Comment (ebyhr) [inline plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java:16]: Still failing with below error in my laptop. Does the main method work in your environment? 
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @378542de
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.apache.hudi.common.util.ObjectSizeCalculator$ClassSizeInfo.<init>(ObjectSizeCalculator.java:246)
	at org.apache.hudi.common.util.ObjectSizeCalculator.getClassSizeInfo(ObjectSizeCalculator.java:140)
	at org.apache.hudi.common.util.ObjectSizeCalculator.visit(ObjectSizeCalculator.java:158)
	at org.apache.hudi.common.util.ObjectSizeCalculator.calculateObjectSize(ObjectSizeCalculator.java:124)
	at org.apache.hudi.common.util.ObjectSizeCalculator.getObjectSize(ObjectSizeCalculator.java:74)
	at org.apache.hudi.common.util.DefaultSizeEstimator.sizeEstimate(DefaultSizeEstimator.java:30)
	at org.apache.hudi.common.util.queue.BoundedInMemoryQueue.adjustBufferSizeIfNeeded(BoundedInMemoryQueue.java:154)
	at org.apache.hudi.common.util.queue.BoundedInMemoryQueue.insertRecord(BoundedInMemoryQueue.java:191)
	at org.apache.hudi.common.util.queue.IteratorBasedQueueProducer.produce(IteratorBasedQueueProducer.java:46)
	at org.apache.hudi.common.util.queue.BoundedInMemoryExecutor.lambda$null$0(BoundedInMemoryExecutor.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java [hunk 2]
```diff
@@ -152,7 +159,7 @@ public static void main(String[] args)
         Logging.initialize();
         Logger log = Logger.get(S3HudiQueryRunner.class);
 
-        String bucketName = "test-bucket";
+        String bucketName = "test-bucket-" + randomTableSuffix();
```
Comment (ebyhr) [inline plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java:162]: Why `randomTableSuffix` is needed?

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java [hunk 3]
```diff
@@ -162,7 +169,7 @@ public static void main(String[] args)
                 HUDI_MINIO_TESTS.getSchemaName(),
                 ImmutableMap.of("http-server.http.port", "8080"),
                 ImmutableMap.of(),
-                new ResourceHudiTablesInitializer(),
+                new TpchHudiTablesInitializer(COPY_ON_WRITE, ImmutableList.of(CUSTOMER, NATION, ORDERS, REGION)),
```
Comment (ebyhr) [inline plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java:172]: Why not `TpchTable.getTables()`?

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java [hunk 4]
```diff
@@ -46,11 +46,13 @@
 import java.util.stream.Collectors;
 import java.util.stream.Stream;
 
+import static com.google.common.base.Verify.verify;
```
Comment (ebyhr) [inline plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java:49]: The main method exists soon due to try-with-resource. Please remove it. You can refer to other query runners. e.g. PostgreSqlQueryRunner

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java [hunk 5]
```diff
@@ -69,7 +71,7 @@ public void initializeTables(
             throws Exception
     {
         Path basePath = Path.of(dataDir);
-        copyDir(Paths.get("src/test/resources/hudi-testing-data"), basePath);
+        copyDir(Paths.get(getResourcePath().toString(), "src/test/resources/hudi-testing-data"), basePath);
```
Comment (ebyhr) [inline plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java:74]: How about
```java
        copyDir(new File(getResource("hudi-testing-data").toURI()).toPath(), basePath);
```

**Comment by ebyhr** [comment]
> Fixes issue https://github.com/trinodb/trino/issues/14340

Could you change the description to `Fixes #14340` for closing the issue automatically? 
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java (hunk 1 above)
Comment (codope) [reply plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java:16]: Yes, it does. You may have to add the following VM arguments
```
-ea --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
```
This will be fixed in the upcoming Hudi release.

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java (hunk 2 above)
Comment (codope) [reply plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java:162]: Just in case older bucket is not cleaned up. So, with `randomTableSuffix` it always starts with a different bucket name.

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java:16]: Please leave a code comment.

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java (hunk 2 above)
Comment (ebyhr) [reply plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java:162]: I don't think it happens because we don't reuse the container. Please remove it.

File: plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java (hunk 3 above)
Comment (ebyhr) [reply plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java:172]: Also, we generally use `tpch` as the schema name for TPCH tables.

**Comment by codope** [comment]
@ebyhr I have addressed your feedback. Please take a look again.

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
Merged, thanks!
