### PR TITLE
Delta Lake Azure Smoke Tests:Rewrite test to avoid flakiness

### LINKED ISSUE #21554: Flaky TestDeltaLakeAdlsConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable
```
Error:  Tests run: 203, Failures: 0, Errors: 2, Skipped: 2, Time elapsed: 642.3 s <<< FAILURE! -- in io.trino.plugin.deltalake.metastore.glue.TestDeltaS3AndGlueMetastoreTest
Error:  io.trino.plugin.deltalake.TestDeltaLakeAdlsConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable -- Time elapsed: 24.76 s <<< ERROR!
java.lang.RuntimeException: Wait timed out
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$16(BaseDeltaLakeConnectorSmokeTest.java:2396)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$17(BaseDeltaLakeConnectorSmokeTest.java:2396)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:729)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable(BaseDeltaLakeConnectorSmokeTest.java:2398)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable(BaseDeltaLakeConnectorSmokeTest.java:2350)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1003)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

Error:  io.trino.plugin.deltalake.TestDeltaLakeAdlsConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable -- Time elapsed: 27.91 s <<< ERROR!
java.lang.RuntimeException: Wait timed out
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$16(BaseDeltaLakeConnectorSmokeTest.java:2396)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$17(BaseDeltaLakeConnectorSmokeTest.java:2396)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:258)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(ReduceOps.java:248)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.count(ReferencePipeline.java:729)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable(BaseDeltaLakeConnectorSmokeTest.java:2398)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable(BaseDeltaLakeConnectorSmokeTest.java:2351)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1534)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2269)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:495)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1003)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

https://github.com/trinodb/trino/actions/runs/8673807420/job/23786003063

cc: @findinpath

### PR DESCRIPTION
**Pull request by findinpath**
Avoid test flakiness on Azure generated a too small timeout
duration for slow rename concurrent operations.

On Azure, at the time of this writing, renaming concurrently
more than 2 files to the same target file at the same time
can cause on Azure some of the `rename` operations to take
even about 2 minutes.

Fixes #21554

Created Azure Storage follow-up https://github.com/Azure/azure-sdk-for-java/issues/39774

### CODE REVIEW

**Comment by findinpath** [comment]
Maintainer, pls run the PR with secrets.

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java [hunk 1]
```diff
@@ -2532,7 +2532,7 @@ private void testConcurrentInsertsSelectingFromTheSameTable(boolean partitioned)
                     .collect(toImmutableList());
 
             long successfulInsertsCount = futures.stream()
-                    .map(future -> tryGetFutureValue(future, 20, SECONDS).orElseThrow(() -> new RuntimeException("Wait timed out")))
+                    .map(future -> tryGetFutureValue(future, 60, SECONDS).orElseThrow(() -> new RuntimeException("Wait timed out")))
```
Comment (wendigo) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java:2535]: it's too generous. Can we go 30 s first?

Comment (findinpath) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java:2535]: Decreased to 40s

**Comment by findinpath** [comment]
> unfortunately I can't run with secrets.

@nineinchnick any ideas on this one?

**Comment by wendigo** [comment]
@findinpath I've raised this issue multiple times but couldn't get help so there is no point in asking once again

**Comment by nineinchnick** [comment]
@findinpath I don't have any ideas. I'd ask someone with admin permissions here to looks through the settings. I don't know what to look for, but I'd compare them with others that can trigger these jobs.

**Comment by ebyhr** [comment]
/test-with-secrets sha=3de9f49f1e4af1e83c82a9831de6daf69aa01b3a

**Review by wendigo — APPROVED** [review]

**Comment by ebyhr** [comment]
The test is still failing:
```
Error:  io.trino.plugin.deltalake.TestDeltaLakeAdlsConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable
Error:    Run 1: TestDeltaLakeAdlsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable:2490->BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable:2537->BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$22:2535->BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$21:2535 » Runtime Wait timed out
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
```

**Comment by findinpath** [comment]
Increased the timeout to `60` seconds.

@ebyhr  could you please run the PR again with secrets?

I'm also inclined to remove `@RepeatedTest(3)` which is likely contributing to potential throttling.

**Comment by ebyhr** [comment]
/test-with-secrets sha=4dac277568599444ba59459d76d43ed2e492c464

**Comment by ebyhr** [comment]
Still failing with 60 seconds:
```
Error:  io.trino.plugin.deltalake.TestDeltaLakeAdlsConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable
Error:    Run 1: TestDeltaLakeAdlsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable:2489->BaseDeltaLakeConnectorSmokeTest.testConcurrentInsertsSelectingFromTheSameTable:2537->BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$22:2535->BaseDeltaLakeConnectorSmokeTest.lambda$testConcurrentInsertsSelectingFromTheSameTable$21:2535 » Runtime Wait timed out
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
```

**Comment by findinpath** [comment]
Relevant log while reproducing the issue locally

```
2024-04-17T03:04:44.019-0600	INFO	pool-112-thread-3	io.trino.plugin.deltalake.DeltaLakeMetadata	AFTER AWAIT
2024-04-17T03:04:44.019-0600	INFO	pool-112-thread-1	io.trino.plugin.deltalake.DeltaLakeMetadata	AFTER AWAIT
2024-04-17T03:04:44.019-0600	INFO	pool-112-thread-2	io.trino.plugin.deltalake.DeltaLakeMetadata	AFTER AWAIT


2024-04-17T03:04:47.384-0600	WARN	SplitRunner-20240417_090444_00003_e9chp.0.0.0-5-372	io.trino.plugin.deltalake.DeltaLakeMetadata	Commit failed on attempt 1, will retry.
Caused by: java.io.IOException: File rename from abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-54jhjjljte/smoke_test/test_concurrent_inserts_select_from_same_table_3bvmz0x56n-84546eb4b7fb459390fc22a72692f0ea/_delta_log/00000000000000000001.json.a78adda2-41cb-4040-a839-d39cd5394190.tmp to abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-54jhjjljte/smoke_test/test_concurrent_inserts_select_from_same_table_3bvmz0x56n-84546eb4b7fb459390fc22a72692f0ea/_delta_log/00000000000000000001.json failed: rename failed
	at io.trino.filesystem.hdfs.HdfsFileSystem.lambda$renameFile$4(HdfsFileSystem.java:222)


2024-04-17T03:04:47.550-0600	INFO	pool-112-thread-1	io.trino.plugin.deltalake.DeltaLakeMetadata	INSERT SUCCESS



2024-04-17T03:04:48.011-0600	ERROR	pool-112-thread-3	io.trino.plugin.deltalake.DeltaLakeMetadata	ERROR ON INSERT
Caused by: io.trino.plugin.deltalake.transactionlog.writer.TransactionFailedException: Conflicting concurrent writes found. Data files added in the modified table by concurrent write operation.
...
Caused by: java.io.IOException: File rename from abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-54jhjjljte/smoke_test/test_concurrent_inserts_select_from_same_table_3bvmz0x56n-84546eb4b7fb459390fc22a72692f0ea/_delta_log/00000000000000000001.json.05ee8c5f-7f4c-4a9b-bd51-f22a1064f3b8.tmp to abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-54jhjjljte/smoke_test/test_concurrent_inserts_select_from_same_table_3bvmz0x56n-84546eb4b7fb459390fc22a72692f0ea/_delta_log/00000000000000000001.json failed: rename failed


2024-04-17T03:06:47.461-0600	WARN	SplitRunner-20240417_090444_00002_e9chp.0.0.0-5-376	io.trino.plugin.deltalake.DeltaLakeMetadata	Commit failed on attempt 1, will retry.
io.trino.plugin.deltalake.transactionlog.writer.TransactionConflictException: Conflict detected while writing Transaction Log entry to ADLS
	at io.trino.plugin.deltalake.transactionlog.writer.AzureTransactionLogSynchronizer.write(AzureTransactionLogSynchronizer.java:71)
    Caused by: java.io.IOException: File rename from abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-54jhjjljte/smoke_test/test_concurrent_inserts_select_from_same_table_3bvmz0x56n-84546eb4b7fb459390fc22a72692f0ea/_delta_log/00000000000000000001.json.05ee8c5f-7f4c-4a9b-bd51-f22a1064f3b8.tmp to abfs://trino-ci@devcicdhierarchical.dfs.core.windows.net/test-delta-lake-integration-smoke-test-54jhjjljte/smoke_test/test_concurrent_inserts_select_from_same_table_3bvmz0x56n-84546eb4b7fb459390fc22a72692f0ea/_delta_log/00000000000000000001.json failed: rename failed
2024-04-17T03:06:48.109-0600	ERROR	pool-112-thread-2	io.trino.plugin.deltalake.DeltaLakeMetadata	ERROR ON INSERT
Caused by: io.trino.plugin.deltalake.transactionlog.writer.TransactionFailedException: Conflicting concurrent writes found. Data files added in the modified table by concurrent write operation.
```

It can be noticed that both losing INSERT operations fail to rename the file, but one of them enters in a "wait" loop which takes over 2 minutes.

**Comment by findinpath** [comment]
I'm guessing that the situation reported on https://github.com/trinodb/trino/pull/21560#issuecomment-2060800909 is rather linked to the usage of hdfs azure client.
Migrating to native azure Trino client which runs consistently without flakiness.

**Comment by findinpath** [comment]
@ebyhr / @wendigo could you please run the PR with secrets 🙏

**Comment by ebyhr** [comment]
/test-with-secrets sha=f5fc1dfc184dbcd59cef256202291c694f144c73

**Comment by findinpath** [comment]
We seem to be dealing with an Azure storage issue related to renaming concurrently multiple temporary files to the same target file.
I've added extra logging to `AzureTransactionLogSynchronizer` and discovered the following:

```
2024-04-17T15:17:18.766-0600 BEGIN WRITE 00000000000000000001.json.3d3b414b-ef91-483c-a25f-e970c894badb.tmp
2024-04-17T15:17:18.775-0600 BEGIN WRITE 00000000000000000001.json.b0879e34-1919-4f9d-aeb1-1ec6ecd9dded.tmp
2024-04-17T15:17:18.775-0600 BEGIN WRITE 00000000000000000001.json.4a55e73a-8bf9-43ab-8d48-980b5142f825.tmp
2024-04-17T15:17:19.225-0600 BEFORE RENAME 00000000000000000001.json.b0879e34-1919-4f9d-aeb1-1ec6ecd9dded.tmp
2024-04-17T15:17:19.225-0600 BEFORE RENAME 00000000000000000001.json.4a55e73a-8bf9-43ab-8d48-980b5142f825.tmp
2024-04-17T15:17:19.236-0600 BEFORE RENAME 00000000000000000001.json.3d3b414b-ef91-483c-a25f-e970c894badb.tmp
2024-04-17T15:17:19.681-0600 AFTER RENAME 00000000000000000001.json.b0879e34-1919-4f9d-aeb1-1ec6ecd9dded.tmp
2024-04-17T15:17:19.681-0600 END WRITE 00000000000000000001.json.b0879e34-1919-4f9d-aeb1-1ec6ecd9dded.tmp
2024-04-17T15:17:19.847-0600 AFTER RENAME 00000000000000000001.json.4a55e73a-8bf9-43ab-8d48-980b5142f825.tmp
2024-04-17T15:17:19.847-0600 BEFORE DELETE 00000000000000000001.json.4a55e73a-8bf9-43ab-8d48-980b5142f825.tmp
2024-04-17T15:17:20.277-0600 AFTER DELETE 00000000000000000001.json.4a55e73a-8bf9-43ab-8d48-980b5142f825.tmp
2024-04-17T15:17:20.278-0600 END WRITE 00000000000000000001.json.4a55e73a-8bf9-43ab-8d48-980b5142f825.tmp

2024-04-17T15:19:19.706-0600 AFTER RENAME 00000000000000000001.json.3d3b414b-ef91-483c-a25f-e970c894badb.tmp
2024-04-17T15:19:19.706-0600 BEFORE DELETE 00000000000000000001.json.3d3b414b-ef91-483c-a25f-e970c894badb.tmp
2024-04-17T15:19:20.081-0600 AFTER DELETE 00000000000000000001.json.3d3b414b-ef91-483c-a25f-e970c894badb.tmp
2024-04-17T15:19:20.081-0600 END WRITE 00000000000000000001.json.3d3b414b-ef91-483c-a25f-e970c894badb.tmp
```

The `rename` operation for the file `00000000000000000001.json.3d3b414b-ef91-483c-a25f-e970c894badb.tmp` takes over 2 minutes.

Changing slightly the problematic test to contain less threads to avoid getting into the above mentioned situation.

**Comment by ebyhr** [comment]
/test-with-secrets sha=cb062e305d73e626c7ae6138cec45fa2e228399b

**Review by Praveen2112 — APPROVED** [review]
