### PR TITLE
Fix incorrect cast from timestamp to time

### LINKED ISSUE #3848: Incorrect cast from timestamp to time
```
presto> select localtimestamp, CAST(localtimestamp AS time);
          _col0          |    _col1
-------------------------+--------------
 2020-05-26 09:26:10.661 | 08:26:10.661
```

Relates to https://github.com/prestosql/presto/issues/3926

### PR DESCRIPTION
**Pull request by martint**
When the offset of the session timezone on the current day
differs from the offset during the epoch due to, say, daylight
savings, the result of the cast would be wrong.

Fixes #3848

### CODE REVIEW

File: presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java [hunk 1]
```diff
@@ -13,11 +13,41 @@
...
         super(true);
     }
+
+    @Test
+    public void testCastToTimeWithDaylightSavings()
+    {
+        // The number of seconds since the beginning of the day for the America/Los_Angeles in 2020 doesn't match
+        // that of 1970, the year of the epoch. Make sure the proper corrections are being performed.
+        Session session = assertions.sessionBuilder()
+                .setTimeZoneKey(getTimeZoneKey("America/Los_Angeles"))
```
Comment (findepi) [inline presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java:36]: nit: We usually use Kathmandu for this.

File: presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java [hunk 2]
```diff
@@ -13,11 +13,41 @@
...
 public class TestTimestampLegacy
         extends BaseTestTimestamp
 {
     protected TestTimestampLegacy()
     {
         super(true);
     }
+
+    @Test
+    public void testCastToTimeWithDaylightSavings()
```
Comment (findepi) [inline presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java:31]: This could go into BaseTestTimestamp, to cover the new semantics (even though it was not broken)

**Review by findepi — APPROVED** [review]

File: presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java (hunk 1 above)
Comment (martint) [reply presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java:36]: Does it matter? This timezone reproduces the issue and is easy to reason about.

File: presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java (hunk 2 above)
Comment (martint) [reply presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java:31]: I thought about that, but this is just testing an implementation detail. (New) timestamps are not sensitive to timezones, so it didn't feel right to be testing that.

File: presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java (hunk 1 above)
Comment (findepi) [reply presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java:36]: Kathmandu zone is very easy to reason about.  It doesn't

File: presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java (hunk 2 above)
Comment (findepi) [reply presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java:31]: I would prefer to have a common test. The new semantics are immune to session zone & its DST, but it is OK to verify that with a test ("black box").

File: presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java (hunk 1 above)
Comment (martint) [reply presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java:36]: I guess what I'm referring to is to the fact that while I know what the daylight saving rules for America/Los_Angeles, I have no idea about Kathmandu's. I'd need to look them up (what day it switches over, etc).

Comment (findepi) [reply presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java:36]: We use Kathmandu in the code base for two reasons:
- it has an offset that is not whole hours (x:45)
- it has a different offset on 1970-01-01 than "today" 
(and it has no DST btw, which probably doesn't matter for this test)

https://github.com/prestosql/presto/blob/4e1393d4933f73876999944ef9c7d0b5ddd3e534/presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StandardColumnMappings.java#L357
https://github.com/prestosql/presto/blob/21e3ddf55a641e1c17b7e4a17689223ff1120b42/presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java#L196
https://github.com/prestosql/presto/blob/21e3ddf55a641e1c17b7e4a17689223ff1120b42/presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java#L1125-L1126

That doesn't not surprise me you know the rules for Los Angeles. I would need to look them up though.

To be clear: I am fine with this test using Los Angeles zone. 
I just do not agree that Los Angeles is "better" in general.
(See also https://github.com/prestodb/presto/issues/10078)

Comment (findepi) [reply presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestampLegacy.java:36]: Of course, we do not need (and we should not) use 2-4 selected zones everywhere.
