### PR TITLE
Fix incorrect min/max with limit in window functions

### LINKED ISSUE #14886: Incorrect result for min/max with limit in window functions
```
trino> SELECT max(x,1) OVER () FROM (VALUES 1,2,3) t(x);

 _col0
-------
 [3]
 NULL
 NULL
(3 rows)
```

### PR DESCRIPTION
**Pull request by martint**
Window functions have an optimization whereby if the frame is the same, it avoids resetting the function and just calls output().

The implementation of output in min and max with N is destructive, which causes subsequent calls to return empty results.

In this change, we update the output method to walk over the sorted contents of the heap instead of clearing it.

Fixes #14886

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# General
* Fix incorrect results when `min(x, n)` or `max(x, n)` is used as a window function. ({issue}`14886`)
```

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/TypedHeap.java [hunk 1]
```diff
@@ -111,41 +112,26 @@ public static TypedHeap deserialize(boolean min, MethodHandle compare, Type elem
...
-        while (positionCount > 0) {
-            indexes[positionCount - 1] = heapIndex[0];
-            positionCount--;
-            heapIndex[0] = heapIndex[positionCount];
-            siftDown();
-        }
+        System.arraycopy(heapIndex, 0, indexes, 0, positionCount);
+        IntArrays.quickSort(indexes, (a, b) -> {
+            try {
+                int comparison = compare(heapBlockBuilder, a, heapBlockBuilder, b);
```
Comment (dain) [inline core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/TypedHeap.java:121]: If I'm reading this correctly, `compare` doesn't throw, so you should be able to simplify this.  Also, you might want to apply the `min ? comparison : -comparison` in the function so all of this folds to a method reference

File: core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/TypedHeap.java [hunk 2]
```diff
@@ -237,6 +223,18 @@ private void compactIfNecessary()
         heapBlockBuilder = newHeapBlockBuilder;
     }
 
+    private int compare(Block leftBlock, int leftPosition, Block rightBlock, int rightPosition)
```
Comment (dain) [inline core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/TypedHeap.java:226]: I think you can share this with keyGreaterThanOrEqual

File: core/trino-main/src/test/java/io/trino/sql/query/TestMinMaxN.java [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+import org.junit.jupiter.api.AfterAll;
+import org.junit.jupiter.api.BeforeAll;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.TestInstance;
+
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.junit.jupiter.api.TestInstance.Lifecycle.PER_CLASS;
+
+@TestInstance(PER_CLASS)
+public class TestMinMaxN
```
Comment (dain) [inline core/trino-main/src/test/java/io/trino/sql/query/TestMinMaxN.java:25]: Add `Window` to the test class name

**Review by dain — APPROVED** [review]

File: core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/TypedHeap.java (hunk 1 above)
Comment (martint) [reply core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/TypedHeap.java]: Ah, yeah, that try-catch was a leftover from an earlier experiment.

> so all of this folds to a method reference

It still needs to reference heapBlockBuilder, so the lambda expression will be there regardless.
