### PR TITLE
Classify errors as external when creating Iceberg tables

### LINKED ISSUE #20695: Failed to create Iceberg table due to insufficient fs permission produce INTERNAL_ERROR
Trino 438.
This should be an `User Error` or `External Error`.

<details>
  <summary>Error Log</summary>

```
java.io.UncheckedIOException: Failed to create file: /projects/trino/oneonestar_test_permission/metadata/snap-7710203132458213822-1-a7b6bb98-ea64-4613-9c8a-51562cd0e5b4.avro
at io.trino.plugin.iceberg.fileio.ForwardingOutputFile.createOrOverwrite(ForwardingOutputFile.java:62)
at org.apache.iceberg.avro.AvroFileAppender.<init>(AvroFileAppender.java:56)
at org.apache.iceberg.avro.Avro$WriteBuilder.build(Avro.java:191)
at org.apache.iceberg.ManifestListWriter$V2Writer.newAppender(ManifestListWriter.java:100)
at org.apache.iceberg.ManifestListWriter.<init>(ManifestListWriter.java:35)
at org.apache.iceberg.ManifestListWriter.<init>(ManifestListWriter.java:31)
at org.apache.iceberg.ManifestListWriter$V2Writer.<init>(ManifestListWriter.java:77)
at org.apache.iceberg.ManifestLists.write(ManifestLists.java:67)
at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:231)
at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:376)
at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413)
at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219)
at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203)
at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196)
at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:374)
at io.trino.plugin.iceberg.IcebergUtil.commit(IcebergUtil.java:809)
at io.trino.plugin.iceberg.IcebergMetadata.finishCreateTable(IcebergMetadata.java:984)
at io.trino.plugin.iceberg.IcebergMetadata.createTable(IcebergMetadata.java:883)
at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:457)
at io.trino.tracing.TracingConnectorMetadata.createTable(TracingConnectorMetadata.java:394)
at io.trino.metadata.MetadataManager.createTable(MetadataManager.java:821)
at io.trino.tracing.TracingMetadata.createTable(TracingMetadata.java:406)
at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:297)
at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:126)
at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:92)
at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:145)
at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:264)
at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1135)
at io.trino.$gen.Trino_438____20240213_123948_2.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Creation of file /projects/trino/oneonestar_test_permission/metadata/snap-7710203132458213822-1-a7b6bb98-ea64-4613-9c8a-51562cd0e5b4.avro failed: Permission denied: user=oneonestar, access=WRITE, inode="/projects/trino":trino:users:drwxr-xr-x
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:496)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:336)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:241)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1909)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1893)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1852)
at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:323)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2635)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2577)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:808)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:494)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:547)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1126)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1050)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:978)
at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2986)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): Permission denied: user=oneonestar, access=WRITE, inode="/projects/trino":trino:users:drwxr-xr-x
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:496)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:336)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:241)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1909)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1893)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1852)
at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:323)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2635)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2577)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:808)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:494)
at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:547)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1126)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1050)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:978)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2986)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1509)
	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
	at org.apache.hadoop.ipc.Client.call(Client.java:1346)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:244)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
	at com.sun.proxy.$Proxy23.create(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.create(ClientNamenodeProtocolTranslatorPB.java:382)
	at jdk.internal.reflect.GeneratedMethodAccessor395.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invoke(RouterRpcClient.java:686)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeMethod(RouterRpcClient.java:533)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSequential(RouterRpcClient.java:1017)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSequential(RouterRpcClient.java:968)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSingle(RouterRpcClient.java:950)
	at org.apache.hadoop.hdfs.server.federation.router.RouterClientProtocol.create(RouterClientProtocol.java:294)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcServer.create(RouterRpcServer.java:689)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:494)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:547)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1126)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1050)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:978)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2986)

	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:106)
	at io.trino.filesystem.hdfs.HdfsOutputFile.createOrOverwrite(HdfsOutputFile.java:69)
	at io.trino.filesystem.TrinoOutputFile.createOrOverwrite(TrinoOutputFile.java:36)
	at io.trino.filesystem.tracing.TracingOutputFile.lambda$createOrOverwrite$1(TracingOutputFile.java:58)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingOutputFile.createOrOverwrite(TracingOutputFile.java:58)
	at io.trino.plugin.iceberg.fileio.ForwardingOutputFile.createOrOverwrite(ForwardingOutputFile.java:59)
	... 35 more
Caused by: org.apache.hadoop.security.AccessControlException: Permission denied: user=oneonestar, access=WRITE, inode="/projects/trino":trino:users:drwxr-xr-x
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:496)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:336)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:241)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1909)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1893)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1852)
at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:323)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2635)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2577)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:808)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:494)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:547)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1126)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1050)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:978)
at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2986)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): Permission denied: user=oneonestar, access=WRITE, inode="/projects/trino":trino:users:drwxr-xr-x
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:496)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:336)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:241)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1909)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1893)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1852)
at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:323)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2635)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2577)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:808)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:494)
at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:547)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1126)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1050)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:978)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2986)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1509)
	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
	at org.apache.hadoop.ipc.Client.call(Client.java:1346)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:244)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
	at com.sun.proxy.$Proxy23.create(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.create(ClientNamenodeProtocolTranslatorPB.java:382)
	at jdk.internal.reflect.GeneratedMethodAccessor395.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invoke(RouterRpcClient.java:686)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeMethod(RouterRpcClient.java:533)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSequential(RouterRpcClient.java:1017)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSequential(RouterRpcClient.java:968)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSingle(RouterRpcClient.java:950)
	at org.apache.hadoop.hdfs.server.federation.router.RouterClientProtocol.create(RouterClientProtocol.java:294)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcServer.create(RouterRpcServer.java:689)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:494)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:547)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1126)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1050)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:978)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2986)

	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
	at org.apache.hadoop.hdfs.DFSOutputStream.newStreamForCreate(DFSOutputStream.java:286)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1271)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1250)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1232)
	at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1170)
	at org.apache.hadoop.hdfs.DistributedFileSystem$8.doCall(DistributedFileSystem.java:556)
	at org.apache.hadoop.hdfs.DistributedFileSystem$8.doCall(DistributedFileSystem.java:553)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:567)
	at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:494)
	at io.trino.hdfs.TrinoFileSystemCache$FileSystemWrapper.create(TrinoFileSystemCache.java:366)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1240)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1217)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098)
	at io.trino.filesystem.hdfs.HdfsOutputFile.lambda$create$1(HdfsOutputFile.java:98)
	at io.trino.hdfs.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:453)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1876)
	at io.trino.hdfs.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
	at io.trino.hdfs.authentication.DirectHdfsAuthentication.doAs(DirectHdfsAuthentication.java:37)
	at io.trino.hdfs.HdfsEnvironment.doAs(HdfsEnvironment.java:134)
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:113)
	at io.trino.filesystem.hdfs.HdfsOutputFile.create(HdfsOutputFile.java:98)
	... 41 more
Caused by: org.apache.hadoop.ipc.RemoteException: Permission denied: user=oneonestar, access=WRITE, inode="/projects/trino":trino:users:drwxr-xr-x
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:496)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:336)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:241)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1909)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1893)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1852)
at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:323)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2635)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2577)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:808)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:494)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:547)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1126)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1050)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:978)
at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2986)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): Permission denied: user=oneonestar, access=WRITE, inode="/projects/trino":trino:users:drwxr-xr-x
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:496)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:336)
at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:241)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1909)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1893)
at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1852)
at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:323)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2635)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2577)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:808)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:494)
at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:547)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1126)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1050)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:978)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2986)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1509)
	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
	at org.apache.hadoop.ipc.Client.call(Client.java:1346)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:244)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
	at com.sun.proxy.$Proxy23.create(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.create(ClientNamenodeProtocolTranslatorPB.java:382)
	at jdk.internal.reflect.GeneratedMethodAccessor395.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invoke(RouterRpcClient.java:686)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeMethod(RouterRpcClient.java:533)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSequential(RouterRpcClient.java:1017)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSequential(RouterRpcClient.java:968)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSingle(RouterRpcClient.java:950)
	at org.apache.hadoop.hdfs.server.federation.router.RouterClientProtocol.create(RouterClientProtocol.java:294)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcServer.create(RouterRpcServer.java:689)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:494)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:547)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1126)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1050)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:978)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1845)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2986)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1584)
	at org.apache.hadoop.ipc.Client.call(Client.java:1530)
	at org.apache.hadoop.ipc.Client.call(Client.java:1427)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:258)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:139)
	at jdk.proxy9/jdk.proxy9.$Proxy431.create(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.create(ClientNamenodeProtocolTranslatorPB.java:383)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:433)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:166)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:158)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:96)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:362)
	at jdk.proxy9/jdk.proxy9.$Proxy432.create(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream.newStreamForCreate(DFSOutputStream.java:280)
	... 64 more
```

</details>

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

When creating an Iceberg table fails, for example with a permission error, it should be classified as an external error, not internal generic error.

Fixes #20695. Tested manually using the Iceberg query runner.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Comment by nineinchnick** [comment]
The exception after this change starts with:
```
io.trino.spi.TrinoException: Failed to finish creating table: Failed to create file: /var/folders/h6/n2g1k82s6rgcw5ghnf1lmgd00000gn/T/0e630379-7c4d-4b8c-9a86-adfa616e57b7/iceberg_data/tpch/aa3-2c6be4f75c3547ea85e029532adce979/metadata/snap-2755585535599766673-1-e9ec17c8-673a-4e61-a065-8df7503c6a20.avro
	at io.trino.plugin.iceberg.IcebergMetadata.finishCreateTable(IcebergMetadata.java:1054)
	at io.trino.plugin.iceberg.IcebergMetadata.createTable(IcebergMetadata.java:912)
```

before:
```
java.io.UncheckedIOException: Failed to create file: /var/folders/h6/n2g1k82s6rgcw5ghnf1lmgd00000gn/T/bf851f5f-7a4c-4df7-bcd9-e4f5062a09cb/iceberg_data/tpch/aa2-ca347f7732ef40bbb660c1fb6fe96007/metadata/snap-6360407032692364376-1-ce8e960b-f0f0-4db7-a63a-c071a0b5e62d.avro
	at io.trino.plugin.iceberg.fileio.ForwardingOutputFile.create(ForwardingOutputFile.java:50)
	at io.trino.plugin.iceberg.fileio.ForwardingOutputFile.createOrOverwrite(ForwardingOutputFile.java:58)
```

This now shows as an external error:
image

**Review by wendigo — APPROVED** [review]

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java [hunk 1]
```diff
@@ -1049,6 +1050,9 @@ public Optional<ConnectorOutputMetadata> finishCreateTable(ConnectorSession sess
             // May happen when table has been already created concurrently.
             throw new TrinoException(TABLE_ALREADY_EXISTS, format("Table %s already exists", icebergTableHandle.name()), e);
         }
+        catch (RuntimeException e) {
```
Comment (ebyhr) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:1053]: > Classify Iceberg IO errors as external

The commit title is misleading. The exception isn't limited to IO errors. 

> for example with a permission error

Please share the stacktrace to PR description.

Comment (nineinchnick) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:1053]: I updated the commit message, PTAL

Comment (pajaks) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:1053]: If the exception is during commit then you should change:
https://github.com/trinodb/trino/blob/232916b75d415a5eb643cf922492eb8513d99aae/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L1620-L1624

Comment (nineinchnick) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:1053]: Did you mean here? https://github.com/trinodb/trino/blob/232916b75d415a5eb643cf922492eb8513d99aae/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java#L967

Comment (pajaks) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:1053]: No `commit` method only prepares commit
It's always used like:
https://github.com/trinodb/trino/blob/232916b75d415a5eb643cf922492eb8513d99aae/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L1040-L1041
 most failures are from:
`commitTransaction(...) ->transaction.commitTransaction()`

Comment (nineinchnick) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:1053]: Not in this case, see the stack trace in the commit message. This is the relevant part:
```
        at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:384)
        at io.trino.plugin.iceberg.IcebergUtil.commit(IcebergUtil.java:970)
        at io.trino.plugin.iceberg.IcebergMetadata.finishCreateTable(IcebergMetadata.java:1041)
```

Comment (nineinchnick) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java]: I refactored the error handling to keep it more consistent, @pajaks @wendigo @ebyhr PTAL

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java [hunk 2]
```diff
@@ -1615,13 +1614,24 @@ private void finishOptimize(ConnectorSession session, IcebergTableExecuteHandle
...
 
+    private static void commitUpdateAndTransaction(SnapshotUpdate<?> update, ConnectorSession session, Transaction transaction, String operation)
+    {
+        try {
+            commit(update, session);
+        }
+        catch (UncheckedIOException e) {
+            throw new TrinoException(ICEBERG_COMMIT_ERROR, format("Failed to commit the update during %s: %s", operation, firstNonNull(e.getMessage(), e)), e);
+        }
+        commitTransaction(transaction, operation);
```
Comment (pajaks) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:1625]: Can you put it inside try for better visibility?

**Review by pajaks — APPROVED** [review]

**Comment by ebyhr** [comment]
/test-with-secrets sha=c7c9a60a380b0c40e4654df2815acbeb09f60196

**Comment by nineinchnick** [comment]
There was one failure in tests with secrets:
```
 Error:  io.trino.plugin.iceberg.TestIcebergConnectorSmokeTest.testDeleteRowsConcurrently -- Time elapsed: 0.980 s <<< FAILURE!
java.lang.AssertionError: 

Expecting actual:
  "Found new conflicting delete files that can apply to records matching true: [local:///tpch/test_concurrent_deletewjlnq60nxb-74ac5438e4a5480698e9f71810766d62/data/20240829_234344_00075_avxmg-dc765b49-e008-417e-bfad-9daecade3ede.orc]"
to contain at least one of the following elements:
  ["Failed to commit the transaction during write:",
    "Failed to replace table due to concurrent updates:"]
but none were found 
	at io.trino.plugin.iceberg.BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$0(BaseIcebergConnectorSmokeTest.java:152)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

I cannot reproduce this locally. Also, this test passed here. Can it be an intermittent failure? @pajaks @raunaqmorarka WDYT? There's [one issue open](https://github.com/trinodb/trino/issues/21862) about this test being flaky, but it's not timing out in this case.

**Comment by pajaks** [comment]
> @pajaks @raunaqmorarka WDYT?

This is known flaky, seems not related to changes to me.

**Comment by wendigo** [comment]
@nineinchnick that's a flaky test

**Comment by nineinchnick** [comment]
@wendigo @ebyhr can you merge this?

**Review by raunaqmorarka — APPROVED** [review]
