### PR TITLE
Fix error with multiple nested partition columns on Iceberg

### LINKED ISSUE #24628: Iceberg query fails with multiple nested partition columns
can be reproduced with example query in error message below. 
Issue seems introduced in 468 with new bucket execution. (passed in 467)

```
Suppressed: java.lang.Exception: SQL: CREATE TABLE test_partition_columns_f1wsd6bhrn WITH (partitioning = ARRAY[
    '"r1.f1"',
    'bucket(b1, 4)'
]) AS
SELECT
    CAST('c1' AS VARCHAR) as c1
    , CAST(ROW(1, 2) AS ROW(f1 integer, f2 integer)) as r1
    , CAST('2022-01-01 01:01:01' AS TIMESTAMP) as d1
    , CAST('2022-01-01 01:01:01' AS TIMESTAMP) as d2
    , CAST('2022-01-01 01:01:01' AS TIMESTAMP) as d3
    , CAST('2022-01-01 01:01:01' AS TIMESTAMP) as d4
    , CAST('b' AS VARCHAR) as b1
    , CAST('12345678' AS VARCHAR) as t1
		at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:572)
		... 11 more
Caused by: java.lang.ClassCastException: class io.trino.spi.block.VariableWidthBlock cannot be cast to class io.trino.spi.block.RowBlock (io.trino.spi.block.VariableWidthBlock and io.trino.spi.block.RowBlock are in unnamed module of loader 'app')
	at io.trino.plugin.iceberg.IcebergBucketFunction$HashFunction.getValue(IcebergBucketFunction.java:124)
	at io.trino.plugin.iceberg.IcebergBucketFunction$HashFunction.computeHash(IcebergBucketFunction.java:131)
	at io.trino.plugin.iceberg.IcebergBucketFunction.getBucket(IcebergBucketFunction.java:74)
	at io.trino.operator.BucketPartitionFunction.getPartition(BucketPartitionFunction.java:46)
	at io.trino.operator.output.SkewedPartitionFunction.getPartition(SkewedPartitionFunction.java:47)
	at io.trino.operator.output.PagePartitioner.partitionPageByRow(PagePartitioner.java:258)
	at io.trino.operator.output.PagePartitioner.partitionPage(PagePartitioner.java:146)
	at io.trino.operator.output.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:337)
```

```
        public Object getValue(Page page, int position)
        {
            Block block = page.getBlock(dataPath.getFirst());
            for (int i = 1; i < dataPath.size(); i++) {
                position = block.getUnderlyingValuePosition(position);
                block = ((RowBlock) block.getUnderlyingValueBlock()).getFieldBlock(dataPath.get(i));
            }
            return valueTransform.apply(block, position);
        }
```

### PR DESCRIPTION
**Pull request by jinyangli34**
## Description

Assign channel number based on the order of field ID.

Fixes #24628

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
## Section
* Fix some things. ({issue}`24628`)
```

### CODE REVIEW

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java [hunk 1]
```diff
@@ -683,4 +684,24 @@ private BaseTable loadTable(String tableName)
     {
         return IcebergTestUtils.loadTable(tableName, metastore, fileSystemFactory, "hive", "tpch");
     }
+
+    @Test
```
Comment (ebyhr) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:688]: BaseIcebergSystemTables is for testing metadata tables. Please move to `BaseIcebergConnectorTest`.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java [hunk 2]
```diff
@@ -683,4 +684,24 @@ private BaseTable loadTable(String tableName)
...
+                ]) AS
+                SELECT
+                    CAST('c1' AS VARCHAR) as c1
+                    , CAST(ROW(1, 2) AS ROW(f1 integer, f2 integer)) as r1
+                    , CAST('2022-01-01 01:01:01' AS TIMESTAMP) as d1
+                    , CAST('2022-01-01 01:01:01' AS TIMESTAMP) as d2
+                    , CAST('2022-01-01 01:01:01' AS TIMESTAMP) as d3
+                    , CAST('2022-01-01 01:01:01' AS TIMESTAMP) as d4
+                    , CAST('b' AS VARCHAR) as b1
+                    , CAST('12345678' AS VARCHAR) as t1""", tableName), 1);
```
Comment (ebyhr) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:705]: Please verify the result with `SELECT` statement.

Comment (jinyangli34) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:708]: Added `select from $partitions`

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java (hunk 1 above)
Comment (jinyangli34) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:691]: shall we leave the test here after added $partitions select?

Comment (ebyhr) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:691]: The test purpose is verifying CTAS success, right? BaseIcebergConnectorTest is more suitable if so.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java [hunk 3]
```diff
@@ -683,4 +687,31 @@ private BaseTable loadTable(String tableName)
...
+    @Test
+    public void testPartitionColumns()
+    {
+        String tableName = "test_partition_columns_" + randomNameSuffix();
+        assertUpdate(String.format("""
+                CREATE TABLE %s WITH (partitioning = ARRAY[
+                    '"r1.f1"',
+                    'bucket(b1, 4)'
+                ]) AS
+                SELECT
```
Comment (ebyhr) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:700]: Could you remove unrelated columns from this SELECT statement?

Comment (jinyangli34) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:700]: removed

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java [hunk 4]
```diff
@@ -683,4 +687,25 @@ private BaseTable loadTable(String tableName)
...
+                    CAST(ROW(1, 2) AS ROW(f1 integer, f2 integer)) as r1
+                    , CAST('b' AS VARCHAR) as b1""", tableName), 1);
+
+        assertThat(query("SELECT partition FROM \"" + tableName + "$partitions\""))
+                .result()
+                .hasTypes(ImmutableList.of(rowType(
+                        field("r1.f1", INTEGER),
+                        field("b1_bucket", INTEGER) )))
+                .matches("SELECT CAST(ROW(1, 3) AS ROW(\"r1.f1\" integer, b1_bucket integer))");
+    }
```
Comment (chenjian2664) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:710]: Drop the test table 
`assertUpdate("DROP TABLE " + tableName)`

**Comment by wendigo** [comment]
I've applied some fixes, ptal @ebyhr @raunaqmorarka @chenjian2664

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java [hunk 5]
```diff
@@ -92,16 +113,14 @@ private static boolean buildDataPaths(Set<Integer> partitionFieldIds, Types.Stru
             currentPaths.addLast(fieldOrdinal);
             org.apache.iceberg.types.Type type = field.type();
             if (type instanceof Types.StructType nestedStruct) {
-                hasPartitionFields = buildDataPaths(partitionFieldIds, nestedStruct, currentPaths, dataPaths) || hasPartitionFields;
+                buildDataPaths(partitionFieldIds, nestedStruct, currentPaths, dataPaths);
             }
             // Map and List types are not supported in partitioning
             if (type.isPrimitiveType() && partitionFieldIds.contains(fieldId)) {
```
Comment (dain) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java:119]: should this be `else if`?  I assume structure is mutually exclusive of these cases. If so, I think it makes more sense to be explicit.  If not, we should explain what the consequences of that is.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java [hunk 6]
```diff
@@ -64,26 +66,45 @@ private static Map<Integer, List<Integer>> buildDataPaths(PartitionSpec spec)
...
-                    channel++;
-                }
+                buildDataPaths(partitionFieldIds, nestedStruct, new ArrayDeque<>(ImmutableList.of(field.fieldId())), fieldInfo);
             }
             else if (field.type().isPrimitiveType() && partitionFieldIds.contains(field.fieldId())) {
-                fieldInfo.put(field.fieldId(), ImmutableList.of(channel));
-                channel++;
+                fieldInfo.put(field.fieldId(), ImmutableList.of(field.fieldId()));
             }
         }
```
Comment (dain) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java:78]: This feels like it is just one step unrolled of the inner build data paths call, but I'm pretty sure it is not.  I believe the difference is this out call is using field id, but he inner code is using ordinal position.  This is preexisting, but maybe add a comment mentioning this, since the code now looks so similar.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java [hunk 7]
```diff
@@ -64,26 +66,45 @@ private static Map<Integer, List<Integer>> buildDataPaths(PartitionSpec spec)
...
-        return fieldInfo;
+
+        // assign channel for top level fields based on the order of the field id
```
Comment (dain) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java:80]: I think this step is doing more than the comment lets on.  The paths are being rewritten from `fieldId.structOrdinalX.structOrdinalY` to `channel.structOrdinalX.structOrdinalY`, where channels are assigned based on the numeric ordering of the field ID.  So I would mention this rewrites the path, changing the root path from field ID to sequential channel number (maybe phrase this better with help from copilot).

**Review by dain — APPROVED** [review]
So the root problem here is my original code assumed the fields from the iceberg spec would be returned in field ID order and that not necessarily true.  The fix is to build the data paths, sort by field ID, and then build the final paths?  Maybe we should mention the faulty assumption and the fix in the commit message.

I had some comments about adding more comments but the rest looks good to me.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java [hunk 8]
```diff
@@ -64,26 +66,45 @@ private static Map<Integer, List<Integer>> buildDataPaths(PartitionSpec spec)
     {
         Set<Integer> partitionFieldIds = spec.fields().stream().map(PartitionField::sourceId).collect(toImmutableSet());
 
-        int channel = 0;
         Map<Integer, List<Integer>> fieldInfo = new HashMap<>();
         for (Types.NestedField field : spec.schema().asStruct().fields()) {
```
Comment (dain) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java:70]: After reading the change again, it seems that the sole purpose of the change is to ensure that channels are allocated in field ID order.  If so, can we fix this by sorting the fields before this loop.  I'm thinking something like this:

```suggestion
        List<Types.NestedField> fields = spec.schema().asStruct().fields().stream()
                .sorted(Comparator.comparingInt(Types.NestedField::fieldId))
                .collect(toImmutableList());
        for (Types.NestedField field : fields) {
```

Comment (jinyangli34) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java:70]: it needs to be sorted by the field that used for partitioning, not only using the root field. 
for nested schema with [f1: [f3, f4], f2], and partition by f3 and f2; then order should be [f2, f1.f3]

I think it's sorted [here](https://github.com/trinodb/trino/blob/cb7a9cc1cf4e9ea26ccaa966e8a421a76c273954/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L1241)

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java (hunk 6 above)
Comment (jinyangli34) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java:90]: Updated the comments. PTAL and feel free to modify.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java (hunk 8 above)
Comment (dain) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java:82]: Can you add a test that partitions on `[f4, f2, f3]`? I'm concerned about what happens when there are multiple nested partitioned fields, intermixed with non-nested or nested from another structured field.

Comment (jinyangli34) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java:82]: Added test with
```
WITH (partitioning = ARRAY[
                    '"r1.f2"',
                    'bucket(b1, 4)',
                    '"r1.f1"'
                ]) AS
                SELECT
                    CAST(ROW('f1', 'f2') AS ROW(f1 VARCHAR, f2 VARCHAR)) as r1
                    , CAST('b' AS VARCHAR) as b1
```

**Review by dain — APPROVED** [review]
