### PR TITLE
Fix inconsistent behavior for to_unixtime with timestamp

### LINKED ISSUE #7450: Inconsistent behavior for to_unixtime(timestamp(p))
Trino currently has two variants of to_unixtime:
* to_unixtime(timestamp(p))
* to_unixtime(timestamp(p) with time zone)

After the timestamp semantics fix (#37), the behavior of the first variant became inconsistent with the second variant. Unix times represent a point in time (vs a wall clock time), so, conceptually, a `timestamp(p)` first needs to be converted to a `timestamp(p) with time zone` before the transformation is applied.

Currently, such timestamps are interpreted as being UTC, which is confusing and counter-intuitive, especially in comparison with an invocation that uses an explicit cast:

```sql
SELECT 
    to_unixtime(localtimestamp), 
    to_unixtime(cast(localtimestamp as timestamp with time zone))
```

=>

```
      _col0       |      _col1
------------------+------------------
 1.617009524129E9 | 1.617034724129E9
```

In a way, the function should only be defined for `timestamp(p) with time zone` and regular coercion rules for `timestamp(p)` -> `timestamp(p) with time zone` should apply

This can be fixed simply by removing io.trino.operator.scalar.timestamp.ToUnixTime

### PR DESCRIPTION
**Pull request by martint**
Fixes https://github.com/trinodb/trino/issues/7450

### CODE REVIEW

File: core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/TestTimestamp.java [hunk 1]
```diff
@@ -63,19 +63,19 @@ public void teardown()
...
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.1234567890')")).matches("1589114096.1234567e0");
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.12345678901')")).matches("1589114096.1234567e0");
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.123456789012')")).matches("1589114096.1234567e0");
+        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56')")).matches("1589067296e0");
+        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.1')")).matches("1589067296.1e0");
+        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.12')")).matches("1589067296.12e0");
+        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.123')")).matches("1589067296.123e0");
+        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.1234')")).matches("1589067296.1234e0");
+        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.12345')")).matches("1589067296.1234498e0");
```
[the remark this answers is not in the document]
Comment (findepi) [reply core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/TestTimestamp.java:71]: i wish `to_unixtime` returned exact numeric ...

File: core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/TestTimestamp.java [hunk 2]
```diff
@@ -63,19 +63,19 @@ public void teardown()
...
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.12345')")).matches("1589114096.12345e0");
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.123456')")).matches("1589114096.123456e0");
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.1234567')")).matches("1589114096.1234567e0");
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.12345678')")).matches("1589114096.1234567e0");
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.123456789')")).matches("1589114096.1234567e0");
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.1234567890')")).matches("1589114096.1234567e0");
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.12345678901')")).matches("1589114096.1234567e0");
-        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56.123456789012')")).matches("1589114096.1234567e0");
+        assertThat(assertions.expression("to_unixtime(TIMESTAMP '2020-05-10 12:34:56')")).matches("1589067296e0");
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/TestTimestamp.java:66]: Maybe add a comment we're testing to_unixtime + coercion here, as it's unusual.

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
It's important that we follow up with `from_unixtime` changes, otherwise things will be inconsistent and confusing. 
People will expect the functions to roundtrip....

**Comment by martint** [comment]
I added a commit for `from_unixtime`. Now the conversions roundtrip properly:

```before
trino> select 
    localtimestamp, 
    from_unixtime(to_unixtime(localtimestamp)), 
    current_timestamp, 
    from_unixtime(to_unixtime(current_timestamp)) \G

-[ RECORD 1 ]--------------------------------------
_col0 | 2021-03-30 15:50:52.543
_col1 | 2021-03-30 15:50:52.543
_col2 | 2021-03-30 15:50:52.543 America/Los_Angeles
_col3 | 2021-03-30 22:50:52.543
```

after:
```
trino> select 
    localtimestamp, 
    from_unixtime(to_unixtime(localtimestamp)), 
    current_timestamp, 
    from_unixtime(to_unixtime(current_timestamp)) \G

-[ RECORD 1 ]--------------------------------------
_col0 | 2021-03-30 15:49:26.375
_col1 | 2021-03-30 15:49:26.375 America/Los_Angeles
_col2 | 2021-03-30 15:49:26.375 America/Los_Angeles
_col3 | 2021-03-30 15:49:26.375 America/Los_Angeles
```

**Comment by GuoPhilipse** [comment]
@martint @findepi Great to meet this new fix, do we have the plan for next release?

File: core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/ToUnixTime.java [hunk 3]
```diff
@@ -1,43 +0,0 @@
...
-import io.trino.spi.type.LongTimestamp;
-import io.trino.spi.type.StandardTypes;
-
-import static io.trino.type.DateTimes.MICROSECONDS_PER_SECOND;
-import static io.trino.type.DateTimes.PICOSECONDS_PER_SECOND;
-
-@ScalarFunction("to_unixtime")
-public final class ToUnixTime
-{
-    private ToUnixTime() {}
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/ToUnixTime.java:28]: Update datetime.rst as well

```
.. function:: to_unixtime(timestamp) -> double

    Returns ``timestamp`` as a UNIX timestamp.
```

File: core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java [hunk 4]
```diff
@@ -121,10 +119,10 @@ public static Slice currentTimeZone(ConnectorSession session)
     }
 
     @ScalarFunction("from_unixtime")
-    @SqlType("timestamp(3)")
-    public static long fromUnixTime(@SqlType(StandardTypes.DOUBLE) double unixTime)
+    @SqlType("timestamp(3) with time zone")
+    public static long fromUnixTime(ConnectorSession session, @SqlType(StandardTypes.DOUBLE) double unixTime)
     {
-        return Math.round(unixTime * MICROSECONDS_PER_SECOND);
+        return packDateTimeWithZone(Math.round(unixTime * 1000), session.getTimeZoneKey());
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java:125]: Some points in time are non-representable in the session zone.
maybe add
```
// TODO (https://github.com/trinodb/trino/issues/5781) ....
```


here

(it doesn't make sense to fix this problem for this method, but not fix it elsewhere, hence TODO only)

(https://github.com/trinodb/trino/issues/5781)

File: core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java [hunk 5]
```diff
@@ -155,9 +153,10 @@ public static long fromUnixTime(@SqlType(StandardTypes.DOUBLE) double unixTime,
         private FromUnixtimeNanosDecimal() {}
 
         @LiteralParameters({"p", "s"})
-        @SqlType("timestamp(9)")
-        public static LongTimestamp fromLong(@LiteralParameter("s") long scale, @SqlType("decimal(p, s)") Slice unixTimeNanos)
+        @SqlType("timestamp(9) with time zone")
+        public static LongTimestampWithTimeZone fromLong(@LiteralParameter("s") long scale, ConnectorSession session, @SqlType("decimal(p, s)") Slice unixTimeNanos)
         {
+            // TODO
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java:159]: ?

File: core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java [hunk 6]
```diff
@@ -167,27 +166,27 @@ public static LongTimestamp fromLong(@LiteralParameter("s") long scale, @SqlType
                 epochSeconds -= 1;
                 picosOfSecond += PICOSECONDS_PER_SECOND;
             }
-            return DateTimes.longTimestamp(epochSeconds, picosOfSecond);
+            return DateTimes.longTimestampWithTimeZone(epochSeconds, picosOfSecond, session.getTimeZoneKey().getZoneId());
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java:169]: as above -- Some points in time are non-representable in the session zone.

File: testing/trino-product-tests/src/main/resources/sql-tests/testcases/horology_functions/checkHorologyFunctionsRegistered.result [hunk 7]
```diff
@@ -66,7 +66,6 @@
  quarter | bigint | timestamp(p) with time zone | scalar | true | Quarter of the year of the given timestamp |
  timezone_hour | bigint | timestamp(p) with time zone | scalar | true | Time zone hour of the given timestamp |
  timezone_minute | bigint | timestamp(p) with time zone | scalar | true | Time zone minute of the given timestamp |
- to_unixtime | double | timestamp(p) | scalar | true | |
```
Comment (findepi) [inline testing/trino-product-tests/src/main/resources/sql-tests/testcases/horology_functions/checkHorologyFunctionsRegistered.result:70]: Shows up in `Return timestamp with time zone from from_unixtime` but belongs to prev commit

File: core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/ToUnixTime.java (hunk 3 above)
Comment (martint) [reply core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/ToUnixTime.java:28]: `timestamp` in that context is the name of the argument, not a type

Comment (findepi) [reply core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/ToUnixTime.java:28]: isn't that a bit less informative than it could be?
(not to say 'misleading')

Comment (martint) [reply core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/ToUnixTime.java:28]: There's no way to indicate the type in the rst syntax we use, unfortunately. Also, the names of the arguments are not very consistent. We have stuff like this, for instance: `.. function:: date(x) -> date`
