### PR TITLE
fix materialized views to allow duplicated source tables without breaking the metadata schema

### LINKED ISSUE #10229: [MATERIALIZED VIEW]: java.lang.IllegalArgumentException: Duplicate key [tpcds1t.b] found
I use trino-365 release version with iceberg connector to select materialized view ,and met a “duplicate key " error ,
      below is the detail info.
      Simply check, the root cause is :
       Map<String, String> tableToSnapshotIdMap = Splitter.on(',').withKeyValueSeparator('=').split(dependsOnTables); 
       in IcebergMetadata.java file at 1069 line.
       There is the table used twice here,and the map key can not be same .
 
       create table a (a1 int ,b1 int ,c1 int) ;
       create table b (a1 int ,b1 int ,c1 int) ;
       create table c (a1 int ,b1 int ,c1 int) ;

       insert into a values (1,1,1),(2,2,2),(3,3,3);
       insert into b values (1,1,1),(2,2,2),(3,3,3);
       insert into c values (1,1,1),(2,2,2),(3,3,3);

       create materialized view tv with  (partitioning = ARRAY['bucket(a1,64)']) as (
       select a.a1,b.b1,c.c1 from a,b,c where a.a1=b.b1 and a.c1=c.c1 
       union all 
       select c.a1,b.b1,c.c1 from b,c where c.c1=b.b1) ;
	
       refresh materiaized view tv;
       select * from tv limit 10;
        
        **Here is error stack:**
        **java.lang.IllegalArgumentException: Duplicate key [tpcds1t.b] found.**
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:524)
	at io.trino.plugin.iceberg.IcebergMetadata.getMaterializedViewToken(IcebergMetadata.java:1069)
	at io.trino.plugin.iceberg.IcebergMetadata.getMaterializedViewFreshness(IcebergMetadata.java:1026)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getMaterializedViewFreshness(ClassLoaderSafeConnectorMetadata.java:972)
	at io.trino.metadata.MetadataManager.getMaterializedViewFreshness(MetadataManager.java:1596)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1499)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:377)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:394)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2147)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:377)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:185)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:394)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:402)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1365)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:377)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:394)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:357)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:259)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:187)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:796)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_365_4_gec2e959_dirty____20211208_020140_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### PR DESCRIPTION
**Pull request by berndlunghamer**
fix #10229, remove duplicates from materialized view source tables when saving metdata

Fixes https://github.com/trinodb/trino/issues/10229

### CODE REVIEW

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java [hunk 1]
```diff
@@ -140,6 +140,15 @@ public void testCreateWithInvalidPropertyFails()
                 .hasMessage("Catalog 'iceberg' does not support materialized view property 'invalid_property'");
     }
 
+    @Test
+    public void testCreateWithDuplicateSourceTableSucceeds()
+    {
+        assertUpdate("CREATE MATERIALIZED VIEW materialized_view_with_duplicate_source AS " +
```
Comment (sopel39) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java:146]: nit: better formatting would be
```
assertUpdate("" +
   ".."
```

**Review by sopel39 — APPROVED** [review]

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java (hunk 1 above)
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java:146]: The changed code isn't going to get called unless we also do a `assertUpdate("REFRESH MATERIALIZED VIEW materialized_view_with_duplicate_source", 12);` after the create.
But the test doesn't fail even after adding that without your fix.
We need a test which would fail without your fix.

Comment (berndlunghamer) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java:146]: ok I see, I need to refresh and then select from the table. This then should fail as the metadata is only evaluated at query time not when refreshing.

Comment (berndlunghamer) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java]: applied

Comment (berndlunghamer) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java]: select path added which should trigger both the write metadata and read metadata path.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java [hunk 2]
```diff
@@ -140,6 +140,20 @@ public void testCreateWithInvalidPropertyFails()
...
+    @Test
+    public void testCreateWithDuplicateSourceTableSucceeds()
+    {
+        assertUpdate("" +
+                "CREATE MATERIALIZED VIEW materialized_view_with_duplicate_source AS " +
+                "SELECT _bigint, _date FROM base_table1 " +
+                "UNION ALL " +
+                "SELECT _bigint, _date FROM base_table1 ");
+
+        assertUpdate("REFRESH MATERIALIZED VIEW materialized_view_with_duplicate_source");
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java:152]: Does this assertion pass without the `count = 12` parameter ?

Comment (berndlunghamer) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java:152]: I ran the test locally, assertion passed without count = 12, yes. 

Same behaviour in the test as in in testShowTables or testSessionCatalogSchema. I am not sure if iceberg plugin is specified to return the true count of rows updated / written

**Review by sopel39 — APPROVED** [review]

**Comment by sopel39** [comment]
please rebase and squash commits

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java (hunk 2 above)
Comment (raunaqmorarka) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java:152]: That's strange, when I try to run it locally I get
```
java.lang.AssertionError: expected no update count, but got 12

	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:88)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:235)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:230)
	at io.trino.plugin.iceberg.TestIcebergMaterializedViews.testCreateWithDuplicateSourceTableSucceeds(TestIcebergMaterializedViews.java:474)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
```
All the other assertions in this file with `REFRESH MATERIALIZED VIEW` include the count parameter as well

Comment (berndlunghamer) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java]: again you are right, apologies. Do not know where I was looking and the test now failed without the parameter locally. So this has been added. sorry for the mess up.

**Review by raunaqmorarka — APPROVED** [review]

**Comment by berndlunghamer** [comment]
> @berndlunghamer could you sign CLA?

yes, i have sent it to cla@trino.io from two different email addresses but have not heard back and github handles have not been updated to the cla repo.

**Comment by sopel39** [comment]
@cla-bot check

**Comment by sopel39** [comment]
merged, thanks!
