### PR TITLE
Increase timeouts in Cassandra product test environment 

### LINKED ISSUE #12818: Flaky `Query timed out after PT2S` in Cassandra product tests
We may want to increase the timeout or add retry logic to `onCassandra` method. 
```
tests               | 2022-06-13 14:03:00 INFO: FAILURE     /    io.trino.tests.product.cassandra.TestSelect.testSelectAllTypePartitioningMaterializedView (Groups: profile_specific_tests, cassandra) took 12.8 seconds
tests               | 2022-06-13 14:03:00 SEVERE: Failure cause:
tests               | com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S
tests               | 	at com.datastax.oss.driver.api.core.DriverTimeoutException.copy(DriverTimeoutException.java:34)
tests               | 	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
tests               | 	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
tests               | 	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
tests               | 	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
tests               | 	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
tests               | 	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:78)
tests               | 	at io.trino.tempto.internal.query.CassandraQueryExecutor.executeQuery(CassandraQueryExecutor.java:87)
tests               | 	at io.trino.tests.product.cassandra.TestSelect.onCassandra(TestSelect.java:569)
tests               | 	at io.trino.tests.product.cassandra.TestSelect.testSelectAllTypePartitioningMaterializedView(TestSelect.java:329)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
```
https://github.com/trinodb/trino/runs/6857005393

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

1/9 failed without this fix. https://github.com/trinodb/trino/actions/runs/4726186779/jobs/8386368706?pr=17060
More than 30 attempts succeeded with this change. 

Requires https://github.com/trinodb/tempto/pull/111
Fixes #12818

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

File: testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeCassandra.java [hunk 1]
```diff
@@ -62,7 +62,10 @@ private DockerContainer createCassandra()
                 .withCommand(
                         "bash",
                         "-cxeu",
-                        "ln -snf /usr/share/zoneinfo/Asia/Kathmandu /etc/localtime && echo Asia/Kathmandu > /etc/timezone && /docker-entrypoint.sh cassandra -f")
+                        "ln -snf /usr/share/zoneinfo/Asia/Kathmandu /etc/localtime && " +
```
Comment (ebyhr) [inline testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeCassandra.java:65]: Going to revert and change `basic.request.timeout` instead.

File: testing/trino-product-tests/src/main/resources/tempto-configuration.yaml [hunk 2]
```diff
@@ -132,6 +132,9 @@ databases:
     default_schema: test
     skip_create_schema: false
     table_manager_type: cassandra
+    basic:
+        request:
+            timeout_seconds: 30
```
Comment (hashhar) [inline testing/trino-product-tests/src/main/resources/tempto-configuration.yaml:137]: indentation seems off

**Review by hashhar — APPROVED** [review]
LGTM

**Comment by findepi** [comment]
@ebyhr should this be "milestone 414"?

**Comment by ebyhr** [comment]
Yes, added the milestone.

**Comment by findepi** [comment]
thanks @ebyhr !
do you maybe know why it wasn't added automatically for this PR?

**Comment by ebyhr** [comment]
It seems maven upgrade #16777 affected it. I already set a milestone to other affected 3 PRs.
Not sure why it happened temporarily. 
```
Error: Unable to process file command 'env' successfully.
Error:  format '[ERROR] Extension io.takari.aether:takari'
```

https://github.com/trinodb/trino/actions/runs/4748403112/jobs/8434562002

**Comment by findepi** [comment]
thanks @ebyhr for looking into that and for the manual fix!

without knowing what problem was fixed by https://github.com/trinodb/trino/pull/16777 it's hard to tell whether we should roll back

@wendigo @kokosing please chime in

cc  @nineinchnick 
cc @trinodb/maintainers milestoning doesn't currently work
