### PR TITLE
Disallow creating Delta tables partitioned by all columns

### LINKED ISSUE #14001: Disallow creating Delta tables partitioned by all columns
Delta doesn't support creating such tables. 
```
Cannot use all columns for partition columns
```

Steps to reproduce:
```sql
CREATE TABLE test1 (c1 int) WITH (partitioned_by = array['c1']);
INSERT INTO test1 VALUES (1);

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetMetadata(ParquetMetadataConverter.java:1538)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:1485)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:583)
	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:777)
	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:646)
	at io.trino.plugin.deltalake.DeltaLakeWriter.readStatistics(DeltaLakeWriter.java:187)
	at io.trino.plugin.deltalake.DeltaLakeWriter.getDataFileInfo(DeltaLakeWriter.java:169)
	at io.trino.plugin.deltalake.DeltaLakePageSink.closeWriter(DeltaLakePageSink.java:425)
	at io.trino.plugin.deltalake.DeltaLakePageSink.doFinish(DeltaLakePageSink.java:233)
	at io.trino.hdfs.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.hdfs.HdfsEnvironment.doAs(HdfsEnvironment.java:94)
	at io.trino.plugin.deltalake.DeltaLakePageSink.finish(DeltaLakePageSink.java:226)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:77)
	at io.trino.operator.TableWriterOperator.finish(TableWriterOperator.java:212)
	at io.trino.operator.Driver.processInternal(Driver.java:429)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:737)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:514)
	at io.trino.$gen.Trino_testversion____20220906_065104_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Below INSERT also fails:
```sql
CREATE TABLE test2 (c1 int, c2 int) WITH (partitioned_by = array['c1', 'c2']);
INSERT INTO test2 VALUES (1, 2);
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #14001
I will send another PR for `DROP COLUMN` statement. Currently, OSS Delta Lake allows dropping the last data column https://github.com/delta-io/delta/issues/1929

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java [hunk 1]
```diff
@@ -248,4 +249,43 @@ public void testReplaceTableWithSchemaChangeOnCheckpoint()
...
+            assertThatThrownBy(() -> onDelta().executeQuery("" +
+                    "CREATE TABLE default." + tableName + " " +
+                    "USING DELTA " +
+                    "PARTITIONED BY (part, another_part)" +
+                    "LOCATION 's3://" + bucketName + "/" + tableDirectory + "'" +
+                    "SELECT 1 part, 2 another_part"))
+                    .hasMessageContaining("Cannot use all columns for partition columns");
+        }
+        finally {
+            dropDeltaTableWithRetry("default." + tableName);
```
Comment (pajaks) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java:288]: Do we need cleanup if expected behaviour is that table will not be created?

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java [hunk 2]
```diff
@@ -248,4 +249,43 @@ public void testReplaceTableWithSchemaChangeOnCheckpoint()
             dropDeltaTableWithRetry(tableName);
         }
     }
+
+    @Test(groups = {DELTA_LAKE_DATABRICKS, PROFILE_SPECIFIC_TESTS})
+    @Flaky(issue = DATABRICKS_COMMUNICATION_FAILURE_ISSUE, match = DATABRICKS_COMMUNICATION_FAILURE_MATCH)
+    public void testCreateTableAsSelectWithAllPartitionColumns()
```
Comment (pajaks) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java:255]: Can we use other tests in this case? This test will be run only when run with secrets, maybe it would be good to have it run for all PRs?

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java (hunk 1 above)
Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java:288]: The expected behavior can be changed in the future. We may introduce regressions or Delta Lake may change their behavior.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 3]
```diff
@@ -1073,6 +1073,9 @@ private static void checkPartitionColumns(List<ColumnMetadata> columns, List<Str
         if (!invalidPartitionNames.isEmpty()) {
             throw new TrinoException(DELTA_LAKE_INVALID_SCHEMA, "Table property 'partition_by' contained column names which do not exist: " + invalidPartitionNames);
         }
+        if (columns.size() == partitionColumnNames.size()) {
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1076]: Add a test in `TestDeltaLakeConnectorTest`

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java [hunk 4]
```diff
@@ -248,4 +249,43 @@ public void testReplaceTableWithSchemaChangeOnCheckpoint()
             dropDeltaTableWithRetry(tableName);
         }
     }
+
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java:252]: test the behavior outside of product test too (delta connector test?)

**Review by findepi — APPROVED** [review]

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java (hunk 2 above)
Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java:287]: Added tests to `TestDeltaLakeConnectorTest`. Please note that this class is dedicated to Databricks, not OSS Delta Lake for now.
