### PR TITLE
[Pinot connector] Add support for basic authentication

### LINKED ISSUE #9531: [Pinot connector] Add authentication
At the moment Pinot supports Basic Authentication - see https://docs.pinot.apache.org/operators/tutorials/authentication-authorization-and-acls

Trying to access a secured Pinot cluster results in the following exception:

```
Query <query_id> failed: io.trino.plugin.pinot.PinotException: Unexpected response status: 403 for request  to url http://pinotcontroller:9000/tables/sometable/instances, with headers {Accept=[application/json]}, full response null
com.google.common.util.concurrent.UncheckedExecutionException: io.trino.plugin.pinot.PinotException: Unexpected response status: 403 for request  to url http://pinotcontroller:9000/tables/sometable/instances, with headers {Accept=[application/json]}, full response null
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946)
	at io.trino.plugin.pinot.client.PinotClient.getBrokerHost(PinotClient.java:289)
	at io.trino.plugin.pinot.client.PinotClient.sendHttpGetToBrokerJson(PinotClient.java:191)
	at io.trino.plugin.pinot.client.PinotClient.getRoutingTableForTable(PinotClient.java:308)
	at io.trino.plugin.pinot.PinotSplitManager.generateSplitsForSegmentBasedScan(PinotSplitManager.java:72)
	at io.trino.plugin.pinot.PinotSplitManager.getSplits(PinotSplitManager.java:167)
	at io.trino.split.SplitManager.getSplits(SplitManager.java:86)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitScanAndFilter(DistributedExecutionPlanner.java:206)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:275)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:159)
	at io.trino.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:346)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:159)
	at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:82)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitAggregation(DistributedExecutionPlanner.java:304)
	at io.trino.sql.planner.DistributedExecutionPlanner$Visitor.visitAggregation(DistributedExecutionPlanner.java:159)
	at io.trino.sql.planner.plan.AggregationNode.accept(AggregationNode.java:203)
	at io.trino.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:127)
	at io.trino.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:134)
	at io.trino.sql.planner.DistributedExecutionPlanner.doPlan(DistributedExecutionPlanner.java:134)
	at io.trino.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:104)
	at io.trino.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:508)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:415)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_362____20211005_125016_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.trino.plugin.pinot.PinotException: Unexpected response status: 403 for request  to url http://pinotcontroller:9000/tables/sometable/instances, with headers {Accept=[application/json]}, full response null
	at io.trino.plugin.pinot.client.PinotClient.doHttpActionWithHeadersJson(PinotClient.java:169)
	at io.trino.plugin.pinot.client.PinotClient.sendHttpGetToControllerJson(PinotClient.java:182)
	at io.trino.plugin.pinot.client.PinotClient.getAllBrokersForTable(PinotClient.java:265)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:168)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 31 more
```

This ticket is to add configuration properties for username and password or basic token to support basic authentication

### PR DESCRIPTION
**Pull request by ddcprg**
Fixes #9531

### CODE REVIEW

**Comment by ddcprg** [comment]
Thanks, I will do

**Comment by ebyhr** [comment]
@ddcprg Could you rebase on upstream since #9098 was already merged?

**Comment by ddcprg** [comment]
@ebyhr I'll submit the CLA in the next few days, I still need confirmation from my employer - this shouldn't be a problem. In the meantime I'll add ITs for this functionality

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java [hunk 1]
```diff
@@ -93,7 +94,7 @@ protected QueryRunner createQueryRunner()
     {
         TestingKafka kafka = closeAfterClass(TestingKafka.createWithSchemaRegistry());
         kafka.start();
-        TestingPinotCluster pinot = closeAfterClass(new TestingPinotCluster(kafka.getNetwork()));
+        TestingPinotCluster pinot = closeAfterClass(new TestingPinotCluster(kafka.getNetwork(), true));
```
Comment (ddcprg) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java:97]: Let me know whether is worth keeping both secured and unsecured ITs

File: docs/src/main/sphinx/connector/pinot.rst [hunk 2]
```diff
@@ -33,18 +33,22 @@ Configuration properties
...
+                                                   Pinot returns hostnames and not IP addresses.
+``pinot.segments-per-split``            No         The number of segments processed in a split. Setting this higher reduces the
+                                                   number of requests made to Pinot. This is useful for smaller Pinot clusters.
+``pinot.request-timeout``               No         The timeout for Pinot requests. Increasing this can reduce timeouts if DNS
+                                                   resolution is slow.
+``pinot.authentication.method``         No         Pinot authentication method for requests. Allowed values are ``none`` and
+                                                   ``basic`` - defaults to ``none`` which is no authentication.
+``pinot.authentication.basic.user``     No         Username for basic authentication method.
+``pinot.authentication.basic.password`` No         Password for basic authentication method.
+======================================= ========== ==============================================================================
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply docs/src/main/sphinx/connector/pinot.rst]: This is example PR: https://github.com/trinodb/trino/pull/9052/commits

[the remark this answers is not in the document]
Comment (ddcprg) [reply docs/src/main/sphinx/connector/pinot.rst]: thanks, done

[the remark this answers is not in the document]
Comment (ddcprg) [reply docs/src/main/sphinx/connector/pinot.rst]: thanks, done

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java (hunk 1 above)
Comment (ddcprg) [reply plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java]: I've done this refactoring in the latest commit

**Comment by ddcprg** [comment]
@ebyhr I've submitted my CLA now

**Comment by ebyhr** [comment]
@cla-bot check

File: docs/src/main/sphinx/connector/pinot.rst [hunk 3]
```diff
@@ -33,18 +33,29 @@ Configuration properties
...
+``pinot.controller-urls``                          Yes        A comma separated list of controller hosts. If Pinot is deployed via
+                                                              `Kubernetes <https://kubernetes.io/>`_ this needs to point to the controller
+                                                              service endpoint. The Pinot broker and server must be accessible via DNS as
+                                                              Pinot returns hostnames and not IP addresses.
+``pinot.segments-per-split``                       No         The number of segments processed in a split. Setting this higher reduces the
+                                                              number of requests made to Pinot. This is useful for smaller Pinot clusters.
+``pinot.request-timeout``                          No         The timeout for Pinot requests. Increasing this can reduce timeouts if DNS
+                                                              resolution is slow.
+``pinot.authentication.method``                    No         Pinot authentication method for requests. Allowed values are ``NONE`` and
```
Comment (ebyhr) [inline docs/src/main/sphinx/connector/pinot.rst:47]: `pinot.authentication.type` is the right property name.

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java [hunk 4]
```diff
@@ -101,6 +106,13 @@ public TestingPinotCluster(Network network)
                 .withNetworkAliases("pinot-server", "localhost")
                 .withExposedPorts(SERVER_PORT, SERVER_ADMIN_PORT);
         closer.register(server::stop);
+
+        this.secured = secured;
+    }
+
+    public TestingPinotCluster(Network network)
```
Comment (ebyhr) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java:113]: Let's avoid creating another constructor because the usage is only one place.

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestUnsecuredPinotIntegrationSmokeTest.java [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.trino.plugin.pinot;
+
+public class TestUnsecuredPinotIntegrationSmokeTest
```
Comment (ebyhr) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestUnsecuredPinotIntegrationSmokeTest.java:16]: Rename to `TestPinotWithoutAuthenticationIntegrationSmokeTest`.

**Review by ebyhr — COMMENTED** [review]
Does Pinot allow using different authentication type between controller and broker? If yes, the current implementation can't handle such environment (e.g. secured controller + insecure broker).

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java]: The overhead is only 2min. Let's keep both tests.

**Comment by ebyhr** [comment]
> Would we need tests for all the config permutations?

I suppose it's resolved in configuration level. Two test classes look sufficient if so.

**Comment by ddcprg** [comment]
@ebyhr I can't find an easy way to do the authentication permutations in a single class because of the way tests are structured and I think changing that could be a big refactoring. I can easily add 2 more test classes to test the missing combinations

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConfig.java [hunk 6]
```diff
@@ -313,11 +322,61 @@ public PinotConfig setCountDistinctPushdownEnabled(boolean countDistinctPushdown
...
+        return this;
+    }
+
     @PostConstruct
     public void validate()
     {
         checkState(
                 !countDistinctPushdownEnabled || aggregationPushdownEnabled,
                 "Invalid configuration: pinot.aggregation-pushdown.enabled must be enabled if pinot.count-distinct-pushdown.enabled");
+        if (authenticationMethod == AuthenticationMethod.BASIC) {
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConfig.java]: @ddcprg Reminder.

[the remark this answers is not in the document]
Comment (ddcprg) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConfig.java]: thanks, I'll take a look at this one later today

[the remark this answers is not in the document]
Comment (ddcprg) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConfig.java]: I've now refactored the code to follow a similar pattern to JDBC authentication

File: docs/src/main/sphinx/connector/pinot.rst [hunk 7]
```diff
@@ -33,18 +33,36 @@ Configuration properties
...
+                                                                     Pinot returns hostnames and not IP addresses.
+``pinot.segments-per-split``                              No         The number of segments processed in a split. Setting this higher reduces the
+                                                                     number of requests made to Pinot. This is useful for smaller Pinot clusters.
+``pinot.request-timeout``                                 No         The timeout for Pinot requests. Increasing this can reduce timeouts if DNS
+                                                                     resolution is slow.
+``pinot.authentication.controller.type``                  No         Pinot authentication method for controller requests. Allowed values are
+                                                                     ``NONE`` and ``BASIC_INLINE`` - defaults to ``NONE`` which is no
+                                                                     authentication.
+``pinot.authentication.controller.basic-inline.user``     No         Controller username for basic authentication method.
```
Comment (ddcprg) [inline docs/src/main/sphinx/connector/pinot.rst:50]: I've now called this `basic-inline` because there could be more than one way to provide basic auth credentials, e.g. via password file

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/TestPinotAuthenticationTypeConfig.java [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+import static io.trino.plugin.pinot.auth.PinotAuthenticationType.BASIC_INLINE;
+import static io.trino.plugin.pinot.auth.PinotAuthenticationType.NONE;
+
+public class TestPinotAuthenticationTypeConfig
+{
+    @Test
+    public void testDefaults()
+    {
+        ConfigAssertions.assertRecordedDefaults(
+                ConfigAssertions.recordDefaults(PinotAuthenticationTypeConfig.class)
```
Comment (ebyhr) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/TestPinotAuthenticationTypeConfig.java:31]: Static import `assertRecordedDefaults` and `recordDefaults`.

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/TestPinotAuthenticationTypeConfig.java [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+        Map<String, String> properties = new ImmutableMap.Builder<String, String>()
+                .put("pinot.authentication.controller.type", "basic_inline")
+                .put("pinot.authentication.broker.type", "basic_inline")
+                .build();
+
+        PinotAuthenticationTypeConfig expected = new PinotAuthenticationTypeConfig()
+                .setControllerAuthenticationType(BASIC_INLINE)
+                .setBrokerAuthenticationType(BASIC_INLINE);
+
+        ConfigAssertions.assertFullMapping(properties, expected);
```
Comment (ebyhr) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/TestPinotAuthenticationTypeConfig.java:48]: Static import `assertFullMapping`.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/PinotBasicAuthenticationProvider.java [hunk 10]
```diff
@@ -0,0 +1,48 @@
...
+        return authToken;
+    }
+
+    private String encode(String username, String password)
+    {
+        String auth = username + ":" + password;
+        byte[] encodedAuth = Base64.getEncoder().encode(auth.getBytes(StandardCharsets.ISO_8859_1));
+        return "Basic " + new String(encodedAuth, StandardCharsets.UTF_8);
+    }
+}
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/PinotBasicAuthenticationProvider.java:48]: Please use library to build credential. For instance, Okhttp has `Credentials.basic`.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/none/PinotEmptyAuthenticationProvider.java [hunk 11]
```diff
@@ -0,0 +1,39 @@
...
+
+    public static PinotEmptyAuthenticationProvider instance()
+    {
+        return INSTANCE;
+    }
+
+    private PinotEmptyAuthenticationProvider()
+    {
+    }
+
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/none/PinotEmptyAuthenticationProvider.java:33]: We generally use `private PinotEmptyAuthenticationProvider() {}` as the format for private empty constructor.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationType.java [hunk 12]
```diff
@@ -0,0 +1,19 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.trino.plugin.pinot.auth;
+
+public enum PinotAuthenticationType {
+    NONE,
+    BASIC_INLINE,
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationType.java:18]: Rename to `PASSWORD` for consistency with other connectors.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationTypeConfig.java [hunk 13]
```diff
@@ -0,0 +1,50 @@
...
+    private PinotAuthenticationType controllerAuthenticationType = PinotAuthenticationType.NONE;
+    private PinotAuthenticationType brokerAuthenticationType = PinotAuthenticationType.NONE;
+
+    @NotNull
+    public PinotAuthenticationType getControllerAuthenticationType()
+    {
+        return controllerAuthenticationType;
+    }
+
+    @Config("pinot.authentication.controller.type")
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationTypeConfig.java:31]: Change to `pinot.controller.authentication.type`.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationTypeConfig.java [hunk 14]
```diff
@@ -0,0 +1,50 @@
...
+        return this;
+    }
+
+    @NotNull
+    public PinotAuthenticationType getBrokerAuthenticationType()
+    {
+        return brokerAuthenticationType;
+    }
+
+    @Config("pinot.authentication.broker.type")
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationTypeConfig.java:44]: Change to `pinot.broker.authentication.type`.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotBrokerBasicAuthenticationConfig.java [hunk 15]
```diff
@@ -0,0 +1,52 @@
...
+    private String user;
+    private String password;
+
+    @NotNull
+    public String getUser()
+    {
+        return user;
+    }
+
+    @Config("pinot.authentication.broker.basic-inline.user")
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotBrokerBasicAuthenticationConfig.java:32]: Change to `pinot.broker.authentication.user`.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotBrokerBasicAuthenticationConfig.java [hunk 16]
```diff
@@ -0,0 +1,52 @@
...
+        return this;
+    }
+
+    @NotNull
+    public String getPassword()
+    {
+        return password;
+    }
+
+    @Config("pinot.authentication.broker.basic-inline.password")
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotBrokerBasicAuthenticationConfig.java:45]: Change to `pinot.broker.authentication.password`.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotControllerBasicAuthenticationConfig.java [hunk 17]
```diff
@@ -0,0 +1,52 @@
...
+    private String user;
+    private String password;
+
+    @NotNull
+    public String getUser()
+    {
+        return user;
+    }
+
+    @Config("pinot.authentication.controller.basic-inline.user")
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotControllerBasicAuthenticationConfig.java:32]: Change to `pinot.controller.authentication.user`.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotControllerBasicAuthenticationConfig.java [hunk 18]
```diff
@@ -0,0 +1,52 @@
...
+        return this;
+    }
+
+    @NotNull
+    public String getPassword()
+    {
+        return password;
+    }
+
+    @Config("pinot.authentication.controller.basic-inline.password")
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotControllerBasicAuthenticationConfig.java:45]: Change to `pinot.authentication.controller.password`.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/PinotBasicAuthenticationProvider.java [hunk 19]
```diff
@@ -0,0 +1,48 @@
...
+
+import io.trino.plugin.pinot.auth.PinotAuthenticationProvider;
+
+import java.nio.charset.StandardCharsets;
+import java.util.Base64;
+import java.util.Optional;
+
+import static java.util.Objects.requireNonNull;
+
+public class PinotBasicAuthenticationProvider
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/PinotBasicAuthenticationProvider.java:24]: Rename to `PinotPasswordAuthenticationProvider`.

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java [hunk 20]
```diff
@@ -64,8 +66,9 @@
     private final GenericContainer<?> zookeeper;
     private final HttpClient httpClient;
     private final Closer closer = Closer.create();
+    private final boolean securedController;
 
-    public TestingPinotCluster(Network network)
+    public TestingPinotCluster(Network network, boolean securedController, boolean securedBroker)
```
Comment (ebyhr) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java:71]: No need to split into two boolean variables since they are always same.

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java [hunk 21]
```diff
@@ -204,6 +214,13 @@ public void addRealTimeTable(InputStream realTimeSpec, String tableName)
         throw exception;
     }
 
+    private static String controllerAuthToken()
```
Comment (ebyhr) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java:217]: Please reuse the method in `PinotBasicAuthenticationProvider`.

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/AbstractPinotIntegrationSmokeTest.java [hunk 22]
```diff
@@ -294,19 +299,34 @@ protected QueryRunner createQueryRunner()
...
+                    .put("pinot.authentication.controller.basic-inline.user", "admin")
+                    .put("pinot.authentication.controller.basic-inline.password", "verysecret");
+        }
+        if (isBrokerSecured()) {
+            pinotPropertiesBuilder
+                    .put("pinot.authentication.broker.type", BASIC_INLINE.name())
+                    .put("pinot.authentication.broker.basic-inline.user", "query")
+                    .put("pinot.authentication.broker.basic-inline.password", "secret");
+        }
+        return pinotPropertiesBuilder.build();
```
Comment (ebyhr) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/AbstractPinotIntegrationSmokeTest.java:327]: Please provide secured properties from `TestSecuredPinotIntegrationSmokeTest` (not this class).

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationType.java (hunk 12 above)
Comment (ddcprg) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationType.java:18]: is it `PASSWORD` not a bit ambiguous? Password authentication could be used OAuth2 as well for example. The refactoring could also allow users to provide credentials in a password file (not implemented) rather than inline the values in config properties or use a

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java (hunk 21 above)
Comment (ddcprg) [reply plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java:217]: I would have to relax the access in the method definition and make it static just because of this test, I wouldn't do that, Now that I use OKHTTP I can delegate to that instead. Let me know if you agree

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java (hunk 20 above)
Comment (ddcprg) [reply plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java:71]: I won't have to write test for combinations of secured and non-secured then?

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotControllerBasicAuthenticationConfig.java (hunk 18 above)
Comment (ddcprg) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/basic/inline/PinotControllerBasicAuthenticationConfig.java]: `pinot.controller.authentication.password` for consistency

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java (hunk 20 above)
Comment (ebyhr) [reply plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java:71]: Such test isn't required.

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java (hunk 21 above)
Comment (ebyhr) [reply plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java:217]: You can use `@VisibleForTesting` annotation for such case.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationType.java (hunk 12 above)
Comment (ebyhr) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationType.java:18]: We will use `OAUTH2` or `OAUTH2_PASSTHROUGH` for such use case.

**Comment by ebyhr** [comment]
@ddcprg By the way, there is `#dev` channel in Trino community Slack. Please feel free to join the workspace.
https://trino.io/slack.html

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/AbstractPinotIntegrationSmokeTest.java (hunk 22 above)
Comment (ddcprg) [reply plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/AbstractPinotIntegrationSmokeTest.java]: sure. it's probably easier to discuss over slack... I'll send you a message later today in case there are more changes you'd like me to make

**Comment by ddcprg** [comment]
@ebyhr  sure. it's probably easier to discuss over slack... I'll send you a message later today in case there are more changes you'd like me to make

**Review by ebyhr — APPROVED** [review]
We can use airlift's `BasicAuthRequestFilter`, but follow-up PR is fine. 

Please squash commits into two commits. https://github.com/trinodb/trino/pull/9541#discussion_r723963535 meant: 
1. Change table width in docs (= don't add new properties)
2. Implement basic auth + add new config properties to docs

**Comment by ddcprg** [comment]
> We can use airlift's `BasicAuthRequestFilter`, but follow-up PR is fine.
> 
> Please squash commits into two commits. [#9541 (comment)](https://github.com/trinodb/trino/pull/9541#discussion_r723963535) meant:
> 
> 1. Change table width in docs (= don't add new properties)
> 2. Implement basic auth + add new config properties to docs

done

**Comment by ebyhr** [comment]
Thanks. Please fix commit titles as below (no prefix, no commit body)
1. `Make Pinot configuration table wider`
2. `Add basic authentication to Pinot connector`

This is our commit message guideline. 
https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages

**Comment by ddcprg** [comment]
> Thanks. Please fix commit titles as below (no prefix, no commit body)
> 
> 1. `Make Pinot configuration table wider`
> 2. `Add basic authentication to Pinot connector`
> 
> This is our commit message guideline. https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages

Thank you, done

**Comment by ebyhr** [comment]
Could you rebase on upstream to resolve conflicts?

**Comment by ebyhr** [comment]
Merged, thanks!
