### PR TITLE
Fix failure when converting json stats to parquet in Delta Lake

### LINKED ISSUE #15496: Converting Delta Lake JSON statistics to Parquet format fails
Reported on [Slack](https://trinodb.slack.com/archives/C03E2DYAS0J/p1671504031363849)

Relates to: https://github.com/trinodb/trino/pull/13331
cc @ebyhr 

Delta Lake checkpoint writing fails to convert some stats from their JSON entry representation to the Parquet Struct statistics format.

Repro:
Create a table with a `BIGINT` column
Insert new values until 10 JSON entries have been added
On the tenth entry a `checkpoint.parquet` file should be generated, but it is not

```sql
create table test(c1 bigint);
insert into test values (1);
insert into test values (2);
insert into test values (3);
insert into test values (4);
insert into test values (5);
insert into test values (6);
insert into test values (7);
insert into test values (8);
insert into test values (9);
insert into test values (9223372036854775807);
```

```java
2022-12-22T09:24:39.615+0900	ERROR	20221222_002439_00037_wy7z9.0.0.0-4-190	io.trino.plugin.deltalake.DeltaLakeMetadata	Failed to write checkpoint for table tpch.test for version 10
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at io.trino.plugin.deltalake.transactionlog.DeltaLakeParquetStatisticsUtils.jsonValueToTrinoValue(DeltaLakeParquetStatisticsUtils.java:113)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointWriter.lambda$preprocessMinMaxValues$6(CheckpointWriter.java:367)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointWriter.lambda$preprocessMinMaxValues$7(CheckpointWriter.java:361)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointWriter.preprocessMinMaxValues(CheckpointWriter.java:353)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointWriter.writeMinMaxMapAsFields(CheckpointWriter.java:308)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointWriter.writeParsedStats(CheckpointWriter.java:294)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointWriter.writeAddFileEntry(CheckpointWriter.java:228)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointWriter.write(CheckpointWriter.java:150)
	at io.trino.plugin.deltalake.transactionlog.checkpoint.CheckpointWriterManager.writeCheckpoint(CheckpointWriterManager.java:135)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.writeCheckpointIfNeeded(DeltaLakeMetadata.java:2018)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.finishInsert(DeltaLakeMetadata.java:1388)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:510)
	at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:902)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4054)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:752)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:519)
	at io.trino.$gen.Trino_testversion____20221222_002418_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #15496

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Delta Lake
* Fix failure when converting JSON statistics to Parquet format. ({issue}`15496`)
```

### CODE REVIEW

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeParquetStatisticsUtils.java [hunk 1]
```diff
@@ -110,7 +110,13 @@ public static Object jsonValueToTrinoValue(Type type, @Nullable Object jsonValue
             return (long) (int) jsonValue;
         }
         if (type == BIGINT) {
-            return (long) (int) jsonValue;
+            if (jsonValue instanceof Long) {
+                return (long) jsonValue;
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeParquetStatisticsUtils.java:114]: nit (IntelliJ eye candy) : can we add here `//noinspection RedundantCast`

same as here 

https://github.com/trinodb/trino/blob/01270cafb4a4bb0b82f859380171f47e460f51f5/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTypes.java#L146-L149

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeParquetStatisticsUtils.java [hunk 2]
```diff
@@ -110,7 +110,13 @@ public static Object jsonValueToTrinoValue(Type type, @Nullable Object jsonValue
...
+            }
+            if (jsonValue instanceof Integer) {
+                return (long) (int) jsonValue;
+            }
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeParquetStatisticsUtils.java:118]: I tried out locally (snippet is used in `io.trino.plugin.deltalake.transactionlog.statistics.DeltaLakeJsonFileStatistics`)

```
parseJson(OBJECT_MAPPER, "{\"numRecords\":1,\"minValues\":{\"col\":0},\"maxValues\":{\"col\":9223372036854775807324},\"nullCount\":{\"col\":0}}", DeltaLakeJsonFileStatistics.class)
```

and the parsed value has `BigInteger` . 

However, in this case, I agree  that an exception should be thrown because the value provided is greater than `bigint` max value in Trino https://trino.io/docs/current/language/types.html#bigint

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java [hunk 3]
```diff
@@ -1174,37 +1174,42 @@ public void testCheckpointWriteStatsAsStruct(String type, String inputValue, Str
...
-                {"date", "date '2021-02-03'", "0.0", "'2021-02-03'"},
-                {"timestamp(3) with time zone", "timestamp '2001-08-22 03:04:05.321 -08:00'", "0.0", "'2001-08-22 11:04:05.321 UTC'"},
-                {"array(int)", "array[1]", "null", "null"},
-                {"map(varchar,int)", "map(array['foo', 'bar'], array[1, 2])", "null", "null"},
-                {"row(x bigint)", "cast(row(1) as row(x bigint))", "null", "null"},
+                {"boolean", "true", "false", "0.0", "null", "null"},
+                {"integer", "1", "2147483647", "0.0", "1", "2147483647"},
+                {"tinyint", "2", "127", "0.0", "2", "127"},
+                {"smallint", "3", "32767", "0.0", "3", "32767"},
+                {"bigint", "1000", "9223372036854775807", "0.0", "1000", "9223372036854775807"},
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java:1201]: Please add 

```
{"bigint", "1001", "2147483647", "0.0", "1001", "2147483647"},
```

in order to test also the branch used to test also the branch `if (jsonValue instanceof Integer) {` in `io.trino.plugin.deltalake.transactionlog.DeltaLakeParquetStatisticsUtils#jsonValueToTrinoValue`

**Review by findinpath — APPROVED** [review]

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java (hunk 3 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java:1201]: Both branches are already covered in the existing case.

**Review by findinpath — APPROVED** [review]

**Comment by ebyhr** [comment]
Just rebased on upstream without changes.
