### PR TITLE
Check table existence in Pinot connector

### LINKED ISSUE #8307: Trino-Pinot Connector does not work in Superset when creating datasets or viewing table schemas
Hello,

When use trino via superset to connect to a Pinot table I am unable to create datasets:
Screenshot from 2021-06-18 11-01-02

Or view a given pinot-table schema definition (notice the black popup in the lower right corner):
Screenshot from 2021-06-16 16-39-16

Superset logs show this:
```
ERROR:root:TrinoUserError(type=USER_ERROR, name=NOT_FOUND, message="Table 'default.hitexecutionview$partitions' not found", query_id=20210616_104957_00099_unjsj)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 84, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/log.py", line 70, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/views/base_api.py", line 79, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/utils/core.py", line 1311, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/superset/databases/api.py", line 454, in table_metadata
    table_info = get_table_metadata(database, table_name, schema_name)
  File "/usr/local/lib/python3.8/site-packages/superset/databases/utils.py", line 73, in get_table_metadata
    indexes = get_indexes_metadata(database, table_name, schema_name)
  File "/usr/local/lib/python3.8/site-packages/superset/databases/utils.py", line 38, in get_indexes_metadata
    indexes = database.get_indexes(table_name, schema_name)
  File "/usr/local/lib/python3.8/site-packages/superset/models/core.py", line 623, in get_indexes
    return self.inspector.get_indexes(table_name, schema)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 513, in get_indexes
    return self.dialect.get_indexes(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_trino/dialect.py", line 195, in get_indexes
    partitioned_columns = self._get_columns(connection, f'{table_name}$partitions', schema, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_trino/dialect.py", line 118, in _get_columns
    for record in res:
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1010, in __iter__
    row = self.fetchone()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1343, in fetchone
    self.connection._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1336, in fetchone
    row = self._fetchone_impl()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/result.py", line 1215, in _fetchone_impl
    return self.cursor.fetchone()
  File "/usr/local/lib/python3.8/site-packages/trino/dbapi.py", line 427, in fetchone
    return next(self._iterator)
  File "/usr/local/lib/python3.8/site-packages/trino/client.py", line 456, in __iter__
    rows = self._query.fetch()
  File "/usr/local/lib/python3.8/site-packages/trino/client.py", line 532, in fetch
    status = self._request.process(response)
  File "/usr/local/lib/python3.8/site-packages/trino/client.py", line 402, in process
    raise self._process_error(response["error"], response.get("id"))
trino.exceptions.TrinoUserError: TrinoUserError(type=USER_ERROR, name=NOT_FOUND, message="Table 'default.hitexecutionview$partitions' not found", query_id=20210616_104957_00099_unjsj)
```

This is because the trino-pinot connector does not match API return assumptions on some API.
This is reproducible in Trino with 2 databases (druid & pinot) with the following queries:

```
trino:information_schema> SELECT "column_name","column_default","is_nullable", "data_type" FROM "pinot"."information_schema"."columns" WHERE "table_name" = 'hitexecuti';
Query 20210616_150620_00265_eamyy failed: Table 'default.hitexecuti' not found

trino:information_schema> SELECT "column_name","column_default","is_nullable", "data_type" FROM "druid"."information_schema"."columns" WHERE "table_name" = 'hitexecuti';
 column_name | column_default | is_nullable | data_type 
-------------+----------------+-------------+-----------
(0 rows)

Query 20210616_150637_00266_eamyy, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.24 [0 rows, 0B] [0 rows/s, 0B/s]
```

Druid connector returns 0 results while the Pinot connector returns an error message which is consistent with what is shown in sqlalchemy-trino.

Software versions:
Trino: 358
Pinot: 0.7.1
Superset: [amancevice/superset:0.38.0 ](https://github.com/amancevice/docker-superset)

cc @elonazoulay

### LINKED ISSUE #8834: CREATE TABLE in Pinot connector fail with table already exists error
This should fail with "This connector does not support creating tables" error. 

```bash
trino> show tables in pinot.default;
 Table
-------
(0 rows)

trino> create table pinot.default.test (c1 int);
Query 20210808_141052_00005_bdyan failed: line 1:1: Table 'pinot.default.test' already exists
```

https://github.com/trinodb/trino/blob/f0d49a70e008320096fcec9adaba228f4c3213e0/plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java#L111-L119

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #8834 Fixes #8307

Confirmed added two tests failed before this change.

### CODE REVIEW

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java [hunk 1]
```diff
@@ -115,7 +118,15 @@ public PinotTableHandle getTableHandle(ConnectorSession session, SchemaTableName
             DynamicTable dynamicTable = DynamicTableBuilder.buildFromPql(this, tableName);
             return new PinotTableHandle(tableName.getSchemaName(), dynamicTable.getTableName(), TupleDomain.all(), OptionalLong.empty(), Optional.of(dynamicTable));
         }
-        return new PinotTableHandle(tableName.getSchemaName(), tableName.getTableName());
+
+        try {
+            String pinotTableName = getPinotTableNameFromTrinoTableName(tableName.getTableName());
```
Comment (hashhar) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java:123]: This seems to also fix a possible bug where if Pinot already has a table with a different case Trino might've created a new one and then would fail to query them.

Comment (hashhar) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java:123]: Can we add a test where `test_table` already exists and we try to create `TeSt_TaBlE`. It should fail.

Comment (ebyhr) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java:123]: Even if we try "create TeSt_TaBlE" in Trino, `PinotMetadata.getTableHandle()` recognizes as a lower case table name because of `SchemaTableName` argument. 

I would add another case to TestPinotMetadata as https://github.com/trinodb/trino/pull/8859/files#diff-23d04803adfe20ed595663294bb3803f43828b85c667b119fa2492e49fb78664R51-R52 instead. This test will fail if `PinotMetadata.getTableHandle()` couldn't look up a table name having uppercase. 

Another possible test is preparing an upper case table in Pinot side and verify CT failure with lower case in Trino. But, I assume added test in TestPinotMetadata is sufficient at this time.

Comment (hashhar) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java:123]: > preparing an upper case table in Pinot side and verify CT failure with lower case in Trino

This was my intention. But the new test you added looks sufficient. As long metadata returns lowercase name always engine will take care of the rest.

**Review by hashhar — APPROVED** [review]
