### PR TITLE
Move handling of internal retry error when schema already exist for Hive

### LINKED ISSUE #15174: Hive connector throws confusing SchemaAlreadyExistsException when client received timed out, but database creation succeeded remotely
https://github.com/trinodb/trino/actions/runs/3536197820/jobs/5935006179

```
Error:  io.trino.plugin.hive.TestHiveThriftMetastoreWithS3.setUp  Time elapsed: 109.244 s  <<< FAILURE!
io.trino.testing.QueryFailedException: Schema already exists: 'test_thrift_s3_x0378m5aty'
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:122)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:488)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:71)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:363)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:358)
	at io.trino.plugin.hive.TestHiveThriftMetastoreWithS3.setUp(TestHiveThriftMetastoreWithS3.java:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: CREATE SCHEMA test_thrift_s3_x0378m5aty WITH (location = 's3a://trino-ci-test/test_thrift_s3_x0378m5aty')
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
		... 17 more
Caused by: io.trino.plugin.hive.SchemaAlreadyExistsException: Schema already exists: 'test_thrift_s3_x0378m5aty'
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.createDatabase(ThriftHiveMetastore.java:855)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.createDatabase(BridgingHiveMetastore.java:160)
	at io.trino.plugin.hive.metastore.ForwardingHiveMetastore.createDatabase(ForwardingHiveMetastore.java:132)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.createDatabase(CachingHiveMetastore.java:450)
	at io.trino.plugin.hive.HiveMetastoreClosure.createDatabase(HiveMetastoreClosure.java:140)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.lambda$createDatabase$2(SemiTransactionalHiveMetastore.java:426)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1340)
	at io.trino.plugin.hive.HiveMetadata.commit(HiveMetadata.java:3666)
	at io.trino.plugin.hive.HiveTransactionManager.lambda$commit$0(HiveTransactionManager.java:59)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.trino.plugin.hive.HiveTransactionManager.commit(HiveTransactionManager.java:57)
	at io.trino.plugin.hive.HiveConnector.commit(HiveConnector.java:216)
	at io.trino.metadata.CatalogTransaction.commit(CatalogTransaction.java:78)
	at io.trino.metadata.CatalogMetadata.commit(CatalogMetadata.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at io.trino.$gen.Trino_testversion____20221123_230203_71.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by pajaks**
## Description
HiveMetadata used SemiTransactionalHiveMetastore which delays method executions until commit is invoked.
Due to that catching SchemaAlreadyExistsException in HiveMetadata::createSchema was not enough as exception was not thrown there.

Proposed solution moves schema already exists error handling to SemiTransactionalHiveMetastore class.

Fixes #15174

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( x) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix incorrect `schema already exists` error caused by a client timeout when
  creating a new schema. ({issue}`15174`)
```

### CODE REVIEW

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 1]
```diff
@@ -423,9 +424,28 @@ public synchronized List<String> getAllViews(String databaseName)
         return delegate.getAllViews(databaseName);
     }
 
-    public synchronized void createDatabase(Database database)
+    public synchronized void createDatabase(Database database, String queryId)
```
Comment (ebyhr) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java:427]: Remove `queryId` argument and call `getQueryId()` instead.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java [hunk 2]
```diff
@@ -2901,6 +2921,11 @@ private static Optional<String> getQueryId(Partition partition)
         return Optional.ofNullable(partition.getParameters().get(PRESTO_QUERY_ID_NAME));
     }
 
+    private static Optional<String> getQueryId(Database database)
```
Comment (ebyhr) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java:2924]: Move to before `getQueryId(Table table)`

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCreateSchemaInternalRetry.java [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+
+public class TestHiveCreateSchemaInternalRetry
+        extends AbstractTestQueryFramework
+{
+    private static final String TEST_SCHEMA_TIMEOUT = "test_hive_schema_" + randomNameSuffix();
+    private static final String TEST_SCHEMA_DIFFERENT_SESSION = "test_hive_schema_" + randomNameSuffix();
+
+    private HiveMetastore metastore;
+
+    private FileHiveMetastore createMetastore(String dataDirectory)
```
Comment (ebyhr) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCreateSchemaInternalRetry.java:41]: Move to after `createQueryRunner()`
