### PR TITLE
Configure retries for trino-filesystem-gcs

### LINKED ISSUE #19943: Flaky TestDeltaLakeGcsConnectorSmokeTest.testOptimizeUsingForcedPartitioning
```
Error:  Tests run: 105, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 826.4 s <<< FAILURE! -- in io.trino.plugin.deltalake.TestDeltaLakeGcsConnectorSmokeTest
Error:  io.trino.plugin.deltalake.TestDeltaLakeGcsConnectorSmokeTest.testOptimizeUsingForcedPartitioning -- Time elapsed: 11.18 s <<< ERROR!
io.trino.testing.QueryFailedException: Failed to write Delta Lake transaction log entry
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:505)
	at io.trino.testing.QueryAssertions.assertDistributedUpdate(QueryAssertions.java:107)
	at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:61)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:424)
	at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:419)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testOptimizeUsingForcedPartitioning(BaseDeltaLakeConnectorSmokeTest.java:1961)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.lang.Exception: SQL: INSERT INTO test_optimize_partitioned_table_13kkuabawe VALUES ('one', 6, 'test2', 9)
		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:509)
		... 12 more
Caused by: io.trino.spi.TrinoException: Failed to write Delta Lake transaction log entry
	at io.trino.plugin.deltalake.DeltaLakeMetadata.finishInsert(DeltaLakeMetadata.java:1912)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:617)
	at io.trino.tracing.TracingConnectorMetadata.finishInsert(TracingConnectorMetadata.java:697)
	at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:1140)
	at io.trino.tracing.TracingMetadata.finishInsert(TracingMetadata.java:694)
	at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$4(LocalExecutionPlanner.java:4164)
	at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20231128_181115_1233.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.trino.spi.TrinoException: Failed to store statistics with table location: gs://trino-ci-test/test-delta-lake-integration-smoke-test-gu5i5s6vxd/test_optimize_partitioned_table_13kkuabawe
	at io.trino.plugin.deltalake.statistics.MetaDirStatisticsAccess.updateExtendedStatistics(MetaDirStatisticsAccess.java:109)
	at io.trino.plugin.deltalake.statistics.CachingExtendedStatisticsAccess.updateExtendedStatistics(CachingExtendedStatisticsAccess.java:74)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.updateTableStatistics(DeltaLakeMetadata.java:3350)
	at io.trino.plugin.deltalake.DeltaLakeMetadata.finishInsert(DeltaLakeMetadata.java:1895)
	... 18 more
Caused by: java.io.IOException: Error writing file: gs://trino-ci-test/test-delta-lake-integration-smoke-test-gu5i5s6vxd/test_optimize_partitioned_table_13kkuabawe/_delta_log/_trino_meta/extended_stats.json
	at io.trino.filesystem.gcs.GcsUtils.handleGcsException(GcsUtils.java:39)
	at io.trino.filesystem.gcs.GcsOutputFile.createOutputStream(GcsOutputFile.java:94)
	at io.trino.filesystem.gcs.GcsOutputFile.createOrOverwrite(GcsOutputFile.java:63)
	at io.trino.filesystem.TrinoOutputFile.createOrOverwrite(TrinoOutputFile.java:35)
	at io.trino.filesystem.tracing.TracingOutputFile.lambda$createOrOverwrite$1(TracingOutputFile.java:57)
	at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
	at io.trino.filesystem.tracing.TracingOutputFile.createOrOverwrite(TracingOutputFile.java:57)
	at io.trino.plugin.deltalake.statistics.MetaDirStatisticsAccess.updateExtendedStatistics(MetaDirStatisticsAccess.java:98)
	... 21 more
Caused by: com.google.cloud.storage.StorageException: The object trino-ci-test/test-delta-lake-integration-smoke-test-gu5i5s6vxd/test_optimize_partitioned_table_13kkuabawe/_delta_log/_trino_meta/extended_stats.json exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.
	at com.google.cloud.storage.StorageException.translate(StorageException.java:170)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:313)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:392)
	at com.google.cloud.storage.StorageImpl.lambda$internalCreate$2(StorageImpl.java:213)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.storage.Retrying.run(Retrying.java:65)
	at com.google.cloud.storage.StorageImpl.run(StorageImpl.java:1514)
	at com.google.cloud.storage.StorageImpl.internalCreate(StorageImpl.java:210)
	at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:142)
	at io.trino.filesystem.gcs.GcsOutputFile.createOutputStream(GcsOutputFile.java:84)
	... 27 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 429 Too Many Requests
POST https://storage.googleapis.com/upload/storage/v1/b/trino-ci-test/o?projection=full&uploadType=multipart
{
  "code" : 429,
  "errors" : [ {
    "domain" : "usageLimits",
    "message" : "The object trino-ci-test/test-delta-lake-integration-smoke-test-gu5i5s6vxd/test_optimize_partitioned_table_13kkuabawe/_delta_log/_trino_meta/extended_stats.json exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429.",
    "reason" : "rateLimitExceeded"
  } ],
  "message" : "The object trino-ci-test/test-delta-lake-integration-smoke-test-gu5i5s6vxd/test_optimize_partitioned_table_13kkuabawe/_delta_log/_trino_meta/extended_stats.json exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:570)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:389)
	... 36 more
```

https://github.com/trinodb/trino/actions/runs/7022450870/job/19107239986

### PR DESCRIPTION
**Pull request by elonazoulay**
## Description

Resolves #19943 

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by elonazoulay** [comment]
Notes:
Tried different settings for the retries and optimized for the lowest amount of requests, i.e. maxAttempts.
Other settings that worked:
* Only set gcs.retry.max-attempts: 200 - This works has no back off and issues more calls than the default settings

Max attempts < 20 and delay multiplier < 2.0 also resulted in 429's.

Also: the retry strategy needs to be uniform and the trino-filesystem api ensures that the idempotency requirements are not violated - see [retries](https://cloud.google.com/storage/docs/retry-strategy?utm_source=devrel&utm_medium=api_error&utm_campaign=gcs429)

**Comment by ebyhr** [comment]
/test-with-secrets sha=b932b90bcfadfeaf7cea8fc940a5b39f00af0b7f

**Comment by elonazoulay** [comment]
Looks like the failure above was unrelated, trying again.

**Comment by elonazoulay** [comment]
/test-with-secrets sha=b932b90bcfadfeaf7cea8fc940a5b39f00af0b7f

**Comment by elonazoulay** [comment]
/test-with-secrets sha=52edc07ebeaef3375db3a88049033e30287b938a

File: lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java [hunk 1]
```diff
@@ -38,6 +43,16 @@ public class GcsFileSystemConfig
     private String jsonKey;
     private String jsonKeyFilePath;
 
+    // Note: without uniform strategy we cannot retry idempotent operations.
+    // The trino-filesystem api does not violate the conditions for idempotency, see https://cloud.google.com/storage/docs/retry-strategy#java for details.
+    private Optional<RetryStrategy> retryStrategy = Optional.of(RetryStrategy.UNIFORM);
+
+    private Optional<Duration> initialRetryDelay = Optional.of(new Duration(10, TimeUnit.MILLISECONDS));
+    // Note: there is no benefit to setting this much higher as the rpc quota is 1x per second: https://cloud.google.com/storage/docs/retry-strategy#java
+    private Optional<Duration> maxRetryDelay = Optional.of(new Duration(1100, TimeUnit.MILLISECONDS));
```
Comment (losipiuk) [inline lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java:52]: Why those are optionals?

File: lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java [hunk 2]
```diff
@@ -28,4 +34,16 @@ void setup()
     {
         initialize(getRequiredEnvironmentVariable("GCP_CREDENTIALS_KEY"));
     }
+
+    @Test
+    void testCreateFileRetry()
```
Comment (losipiuk) [inline lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java:39]: how much time does it take?

File: pom.xml [hunk 3]
```diff
@@ -2058,6 +2058,12 @@
                 <version>1.13.1</version>
             </dependency>
 
+            <dependency>
```
Comment (losipiuk) [inline pom.xml:2061]: nit: moving this to root pom could be separate commit

File: lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java (hunk 1 above)
Comment (elonazoulay) [reply lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java:52]: In case we wanted to use the defaults. Initially was thinking that would be better but to match the behavior of the gcs hadoop connector switched to using retries. Do you think it would be better to make them nullable or set explicitly? lmk, whatever works.

Comment (electrum) [reply lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java:52]: I think making these optional and using the library defaults is confusing for users, as that's inconsistent with how other config defaults work. Also, it seems like unnecessary complexity.

File: lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java [hunk 4]
```diff
@@ -38,6 +43,16 @@ public class GcsFileSystemConfig
     private String jsonKey;
     private String jsonKeyFilePath;
 
+    // Note: without uniform strategy we cannot retry idempotent operations.
+    // The trino-filesystem api does not violate the conditions for idempotency, see https://cloud.google.com/storage/docs/retry-strategy#java for details.
+    private Optional<RetryStrategy> retryStrategy = Optional.of(RetryStrategy.UNIFORM);
```
Comment (electrum) [inline lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java:48]: Let's remove this config. Users just care that it works, so we should make it work automatically. After reading that page, I'm still not sure why you would change it from UNIFORM to DEFAULT, so I doubt any users would either.

File: lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java [hunk 5]
```diff
@@ -148,14 +163,92 @@ public GcsFileSystemConfig setJsonKeyFilePath(String jsonKeyFilePath)
...
+        return this;
+    }
+
+    public Optional<@MinDuration("0ms") Duration> getInitialRetryDelay()
+    {
+        return initialRetryDelay;
+    }
+
+    @Config("gcs.retry.initial-delay")
+    @ConfigDescription("Initial delay between rpc retries. See https://cloud.google.com/storage/docs/retry-strategy.")
```
Comment (electrum) [inline lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java:185]: Let's remove these links. The page doesn't directly explain what the setting does. (though what it does seems fairly obvious and similar to other retry configuration)

Also, capitalize RPC

File: lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java [hunk 6]
```diff
@@ -148,14 +163,92 @@ public GcsFileSystemConfig setJsonKeyFilePath(String jsonKeyFilePath)
...
+
+    @Config("gcs.retry.max-delay")
+    @ConfigDescription("Maximum delay between rpc retries. See https://cloud.google.com/storage/docs/retry-strategy.")
+    public GcsFileSystemConfig setMaxRetryDelay(Duration maxRetryDelay)
+    {
+        this.maxRetryDelay = Optional.ofNullable(maxRetryDelay);
+        return this;
+    }
+
+    @Min(value = 1, message = "Retry delay multiplier must be greater than 1.0.")
```
Comment (electrum) [inline lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java:205]: I don't think we need a message, since the default one should be sufficient

File: lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java [hunk 7]
```diff
@@ -148,14 +163,92 @@ public GcsFileSystemConfig setJsonKeyFilePath(String jsonKeyFilePath)
...
         if (useGcsAccessToken) {
-            checkState(jsonKey == null, "Cannot specify 'hive.gcs.json-key' when 'hive.gcs.use-access-token' is set");
-            checkState(jsonKeyFilePath == null, "Cannot specify 'hive.gcs.json-key-file-path' when 'hive.gcs.use-access-token' is set");
+            checkState(jsonKey == null, "Cannot specify 'gcs.json-key' when 'gcs.use-access-token' is set");
+            checkState(jsonKeyFilePath == null, "Cannot specify 'gcs.json-key-file-path' when 'gcs.use-access-token' is set");
+        }
+        checkState(jsonKey == null || jsonKeyFilePath == null, "'gcs.json-key' and 'gcs.json-key-file-path' cannot be both set");
+        checkState(initialRetryDelay.isPresent() == maxRetryDelay.isPresent(), "gcs.retry.initial-delay and gcs.retry.max-delay must both be set or both empty");
+        if (initialRetryDelay.isPresent()) {
+            checkState(initialRetryDelay.get().compareTo(maxRetryDelay.get()) <= 0, "gcs.retry.initial-delay must be less than or equal to gcs.retry.max-delay");
```
Comment (electrum) [inline lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java:245]: I think this can be done on the config class using `@AssertTrue`

File: lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java [hunk 8]
```diff
@@ -148,14 +163,92 @@ public GcsFileSystemConfig setJsonKeyFilePath(String jsonKeyFilePath)
...
+        this.retryStrategy = Optional.ofNullable(retryStrategy);
+        return this;
+    }
+
+    public Optional<@MinDuration("0ms") Duration> getInitialRetryDelay()
+    {
+        return initialRetryDelay;
+    }
+
+    @Config("gcs.retry.initial-delay")
```
Comment (electrum) [inline lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java:184]: We might want to name these to be consistent with the Thrift configs in `ThriftMetastoreConfig`

* `gcs.client.max-retries` -- note that we should do `setMaxAttempts(maxRetries + 1)` and have a minimum of zero for this
* `gcs.client.max-retry-time` -- this seems to be `setTotalTimeout()`
* `gcs.client.backoff-scale-factor`
* `gcs.client.min-backoff-delay`
* `gcs.client.max-backoff-delay`

File: lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java [hunk 9]
```diff
@@ -57,7 +57,8 @@ protected void initialize(String gcpCredentialKey)
         // create/get/list/delete blob
         // For gcp testing this corresponds to the Cluster Storage Admin and Cluster Storage Object Admin roles
         byte[] jsonKeyBytes = Base64.getDecoder().decode(gcpCredentialKey);
-        GcsFileSystemConfig config = new GcsFileSystemConfig().setJsonKey(new String(jsonKeyBytes, UTF_8));
```
Comment (electrum) [inline lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java:60]: Unrelated change

File: lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java [hunk 10]
```diff
@@ -68,6 +69,13 @@ protected void initialize(String gcpCredentialKey)
         cleanupFiles();
     }
 
+    // Note: adjust settings here if tests are flaky, ex. increase maxAttempts, initial delay
```
Comment (electrum) [inline lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java:72]: I don't think we should have this. If tests are flaky, that seems to indicate the defaults are not reliable and will result in failures for real queries. The defaults should be sufficient to make the tests reliable.

The tests should be a minimum bar for reliability, unless we think there is something special about the tests that makes them pathological compared to normal usage.

**Comment by electrum** [comment]
Looks good overall. We definitely need this as the tests are flaky now (and might mean that queries will also fail).

File: lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java (hunk 2 above)
Comment (elonazoulay) [reply lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java:39]: About 130 to 132 seconds.

File: lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java [hunk 11]
```diff
@@ -148,14 +163,92 @@ public GcsFileSystemConfig setJsonKeyFilePath(String jsonKeyFilePath)
...
+    public Optional<RetryStrategy> getRetryStrategy()
+    {
+        return this.retryStrategy;
+    }
+
+    @Config("gcs.retry.strategy")
+    @ConfigDescription("Determines the retry strategy: DEFAULT|UNIFORM. See https://cloud.google.com/storage/docs/retry-strategy.")
+    public GcsFileSystemConfig setRetryStrategy(RetryStrategy retryStrategy)
+    {
+        this.retryStrategy = Optional.ofNullable(retryStrategy);
```
[the remark this answers is not in the document]
Comment (elonazoulay) [reply lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java:175]: update - removed, per suggestion below - added a note about why we must use uniform strategy in GcsStorageFactory.

File: lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java (hunk 2 above)
Comment (losipiuk) [reply lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java:39]: This is quite a lot - adjust configs to make it shorter if possible

Comment (findepi) [inline lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java:39]: How does this test verifies retries take place?
If it is not obvious how the test works,  is it worth documenting?

Comment (elonazoulay) [reply lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java:39]: Sure will do. Just for context: this fails consistently without the retries. Can repro locally as well.

File: lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsStorageFactory.java [hunk 12]
```diff
@@ -81,7 +95,20 @@ public Storage create(ConnectorIdentity identity)
             if (projectId != null) {
                 storageOptionsBuilder.setProjectId(projectId);
             }
-            return storageOptionsBuilder.setCredentials(credentials).build().getService();
+            // Note: without uniform strategy we cannot retry idempotent operations.
```
[the remark this answers is not in the document]
Comment (elonazoulay) [reply lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsStorageFactory.java:98]: Without uniform strategy, the retries do not affect create operations so the tests would still fail, this strategy allows retrying all operations, since trino-filesystem api takes care of idempotency for create.

File: lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java (hunk 2 above)
Comment (elonazoulay) [reply lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java:39]: I did, actually the 2.0 multiplier was the minimum. Maybe I can reduce the repetitions?
When it fails it's generally before 30 tries, usually well before (7-8 repetitions). 

I will do some tests to see the min number of repetitions that guarantees we won't see flakiness.

**Review by electrum — APPROVED** [review]

**Comment by electrum** [comment]
I'll merge this for now since it's in good shape and fixes the frequent test failures. We can follow up on the comments.

File: lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java [hunk 13]
```diff
@@ -28,4 +34,16 @@ void setup()
...
+    {
+        assertThatNoException().isThrownBy(() -> {
```
Comment (electrum) [inline lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java:41]: I'm confused by the purpose of `assertThatNoException()`. Any exception should fail the test. Isn't that the normal behavior of unit tests?

Comment (losipiuk) [reply lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java:41]: I think it captures intent nicely - for the case when you just want to check code runs fine and do not do any assertions. 
Otherwise, if there is code without assertions in test method, it kinda looks that test writer forgot about sth.

**Comment by elonazoulay** [comment]
Thanks! I will push a follow up pr with the remaining suggestions to reduce the time and add some comments to explain the test.
