### PR TITLE
Fix incorrect effective predicate derivation for non-equatable type

### LINKED ISSUE #21508: Failure when queries involve filters with non-equatable types
We came across to an error upgrading trino to `444`.
One of our query that work on trino `443` now return an exception 
> java.lang.AssertionError: Type cannot be used in a comparison expression (should have been caught in analysis): Geometry

We managed to reproduce the bug 

 ```
create table iceberg.test.values1 as SELECT *
             FROM (VALUES (1, 1, 2),
                          (2, 2, 4),
                          (3, 22, 22),
                          (4, 45, 65),
                          (5, 6, 6)) AS a (id, lat, lon);

create table iceberg.test.values2 as SELECT *
             FROM (VALUES (1, 'value1'),
                          (2, 'value2'),
                          (3, 'value3'),
                          (4, 'value4'),
                          (5, 'value5')) AS a (id, name);

WITH geom
         AS (select st_geometryfromtext('POLYGON((0 0,0 10,10 10,10 0 ))') as geo),
     cte1 as (select id
           from iceberg.test.values1
           where ST_WITHIN(ST_POINT(lon, lat), (select geo from geom))),
     cte2 as (select *
           from iceberg.test.values2
           where id in (select id from cte1))
select *
from cte2;

```

the block above works fine on trino `443` but if run on trino `444` return the exception cited above

### PR DESCRIPTION
**Pull request by martint**
EffectivePredicateExtractor was incorrectly deriving an equality predicate for a type that's no comparable or orderable.

Fixes #21508 

## Release notes

( x) Release notes are required, with the following suggested text:

```markdown
# General
* TBD. ({issue}`21508`)
```

### CODE REVIEW

**Review by wendigo — APPROVED** [review]

File: core/trino-main/src/test/java/io/trino/sql/query/TestIssue21508.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+package io.trino.sql.query;
+
+import org.junit.jupiter.api.Test;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class TestIssue21508
+{
+    @Test
+    public void test()
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/sql/query/TestIssue21508.java:23]: Would it also make sense to have a unit test for EPE?
