### PR TITLE
Correctly cache S3 client in S3 native FS with security mapping

### LINKED ISSUE #23545: Unable to load credentials from any of the providers in the chain file with native s3 support
I have an hive external table that points to an s3 location with some CSV gzipped files.
Each 1 minute, one file in the s3 location is updated (replaced) by some external flow.

In `458` lots of queries on this hive external table starts to fail with HIVE_CANNOT_OPEN_SPLIT
Setting back `fs.hadoop.enabled=true` (as of https://github.com/trinodb/trino/pull/23343) fixed the issue.
I tried to workaround the issue by setting `s3.retry-mode` parameter to STANDARD / ADAPTIVE but with no luck.

I wonder if there is something else that can be done here as it seems that [Legacy S3 support](https://trino.io/docs/current/object-storage/legacy-s3.html#fs-legacy-s3-migration) will be removed in the future  ?

Hive security mapping is enabled with the following `hive_security_mapping.json` file:

```
{
  "mappings": [
    {
      "useClusterDefault": true
    }
  ]
}
```

hive properties for s3 legacy support (no issue)
```
fs.hadoop.enabled=true
hive.s3.security-mapping.config-file=/usr/lib/trino/etc/hive_security_mapping.json
hive.s3.security-mapping.refresh-period=5s
```

hive properties for s3 native support
```
fs.hadoop.enabled=false
fs.native-s3.enabled=true
s3.retry-mode=ADAPTIVE
s3.security-mapping.enabled=true
s3.security-mapping.config-file=/usr/lib/trino/etc/hive_security_mapping.json
s3.security-mapping.refresh-period=5s
```

Slack discussion [here](https://trinodb.slack.com/archives/CGB0QHWSW/p1727177619331739)

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

S3 native FS with security mapping enabled is supposed to cache S3 clients for mappings resolved using both an identity and location. This change avoids creating new caches when resolving locations.

Fixes #23545

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

File: lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java [hunk 1]
```diff
@@ -95,7 +98,18 @@ private S3FileSystemLoader(Optional<S3SecurityMappingProvider> mappingProvider,
     @Override
     public TrinoFileSystemFactory apply(Location location)
     {
-        return new S3SecurityMappingFileSystemFactory(mappingProvider.orElseThrow(), clientFactory, preSigner, context, location, uploadExecutor);
+        return identity -> {
+            Optional<S3SecurityMappingResult> mapping = mappingProvider.orElseThrow().getMapping(identity, location);
+
+            S3Client client = clients.computeIfAbsent(mapping, _ -> clientFactory.create(mapping));
+            S3Context context = this.context.withCredentials(identity);
```
Comment (wendigo) [inline lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java:105]: drop this.

**Review by wendigo — APPROVED** [review]

**Review by anusudarsan — APPROVED** [review]

**Review by electrum — APPROVED** [review]
