### PR TITLE
Fix incorrect partitionValues_parsed with id & name column mapping in Delta Lake

### LINKED ISSUE #24121: `partitionValues_parsed` field holds incorrect value with logical column name in case of id and name column mapping mode in Delta Lake
The checkpoint file should use physical column names and correct values. 

```json
{
   "path":"log_date=2024-03-03/20241113_112637_00079_v9t2h_d61a63e0-0b10-47fd-bc53-ad7bab80d362",
   "partitionValues":[
      "(""col-d3204827-65fd-4199-b59c-f789f3b72d4e",
      "2024-03-03"")"
   ],
   "size":277.0,
   "modificationTime":1731497197916.0,
   "dataChange":true,
   "stats":"{\"\"numRecords\"\":1,\"\"minValues\"\":{\"\"col-787739d5-5a80-426e-97a6-51baceb6853f\"\":3},\"\"maxValues\"\":{\"\"col-787739d5-5a80-426e-97a6-51baceb6853f\"\":3},\"\"nullCount\"\":{\"\"col-787739d5-5a80-426e-97a6-51baceb6853f\"\":0}}",
   "partitionValues_parsed":{
      "log_date":"None" ← 
   },
   "stats_parsed":{
      "numRecords":1.0,
      "minValues":{
         "col-787739d5-5a80-426e-97a6-51baceb6853f":3.0
      },
      "maxValues":{
         "col-787739d5-5a80-426e-97a6-51baceb6853f":3.0
      },
      "nullCount":{
         "col-787739d5-5a80-426e-97a6-51baceb6853f":0.0,
         "col-d3204827-65fd-4199-b59c-f789f3b72d4e":"None"
      }
   },
   "tags":[
      
   ]
}
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

We should write physical column names in `partitionValues_parsed` field on checkpoint files. 

Fixes #24121

## Release notes

```markdown
## Delta Lake
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java [hunk 1]
```diff
@@ -161,7 +161,7 @@ public void write(CheckpointEntries entries, TrinoOutputFile outputFile)
         }
         List<DeltaLakeColumnHandle> partitionColumns = extractPartitionColumns(entries.metadataEntry(), entries.protocolEntry(), typeManager);
         List<RowType.Field> partitionValuesParsedFieldTypes = partitionColumns.stream()
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java:163]: Let's add a corresponding test in `io.trino.plugin.deltalake.transactionlog.checkpoint.TestCheckpointWriter`

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java [hunk 2]
```diff
@@ -183,7 +183,7 @@ public RowType getAddEntryType(
             List<DeltaLakeColumnHandle> partitionColumns = extractPartitionColumns(metadataEntry, protocolEntry, typeManager);
             if (!partitionColumns.isEmpty()) {
                 List<RowType.Field> partitionValuesParsed = partitionColumns.stream()
-                        .map(column -> RowType.field(column.columnName(), typeManager.getType(getTypeSignature(DeltaHiveTypeTranslator.toHiveType(column.type())))))
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java:186]: Add test in `io.trino.plugin.deltalake.transactionlog.checkpoint.TestCheckpointEntryIterator`

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java:163]: I intentionally avoided that. Both TestCheckpointWriter & TestCheckpointEntryIterator are not suitable to verify `partitionValues_parsed` field because `AddFileEntry` doesn't hold the value.

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java [hunk 3]
```diff
@@ -270,6 +282,72 @@ private void testAddNestedColumnWithColumnMappingMode(String columnMappingMode)
...
+
+            RowType.Field partitionValuesParsedField = addEntryType.getFields().get(partitionValuesParsedFieldPosition);
+            assertThat(partitionValuesParsedField.getName().orElseThrow()).matches("partitionValues_parsed");
+            RowType partitionValuesParsedType = (RowType) partitionValuesParsedField.getType();
+            assertThat(partitionValuesParsedType.getFields().stream().collect(onlyElement()).getName().orElseThrow()).isEqualTo(physicalColumnName);
+
+            ParquetMetadata parquetMetadata = MetadataReader.readFooter(
+                    new TrinoParquetDataSource(new LocalInputFile(checkpoint.toFile()), new ParquetReaderOptions(), new FileFormatDataSourceStats()),
+                    Optional.empty());
+            ParquetDataSource dataSource = new FileParquetDataSource(checkpoint.toFile(), new ParquetReaderOptions());
```
Comment (raunaqmorarka) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java:331]: I think you can use the same dataSource in MetadataReader.readFooter as well as createParquetReader

**Review by raunaqmorarka — APPROVED** [review]

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java (hunk 1 above)
Comment (findinpath) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java:163]: I was thinking about a test similar to  `io.trino.plugin.deltalake.transactionlog.checkpoint.TestCheckpointEntryIterator#testReadAddEntriesPartitionPruning` with corresponding resource files

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java [hunk 4]
```diff
@@ -161,7 +161,7 @@ public void write(CheckpointEntries entries, TrinoOutputFile outputFile)
...
-                .map(column -> RowType.field(column.columnName(), column.type()))
+                .map(column -> RowType.field(column.basePhysicalColumnName(), column.type()))
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java:164]: Looks good now

```
"PartitionValues": {
        "col-6d32b73c-d46b-47f3-aeee-b4ce2231c81f": "30"
      },
      "PartitionValues_parsed": {
        "Col456d32b73c45d46b4547f345aeee45b4ce2231c81f": 30
      }
```

**Review by findinpath — APPROVED** [review]
LGTM 

The integration test is low-level enough to not require anymore additional unit tests.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java (hunk 4 above)
Comment (findinpath) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java:164]: Note the missing dashes.

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java [hunk 5]
```diff
@@ -270,6 +280,70 @@ private void testAddNestedColumnWithColumnMappingMode(String columnMappingMode)
...
+        testPartitionValuesParsedCheckpoint(ColumnMappingMode.NONE);
+    }
+
+    private void testPartitionValuesParsedCheckpoint(ColumnMappingMode columnMappingMode)
+            throws Exception
+    {
+        try (TestTable table = new TestTable(
+                getQueryRunner()::execute,
+                "test_checkpoint",
+                "(x int, part int) WITH (checkpoint_interval = 3, column_mapping_mode = '" + columnMappingMode + "', partitioned_by = ARRAY['part'])")) {
```
Comment (pajaks) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java:298]: Can you add also test for other types (like Date) which has different representation in `PartitionValues` and `PartitionValues_parsed`

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java [hunk 6]
```diff
@@ -270,6 +280,70 @@ private void testAddNestedColumnWithColumnMappingMode(String columnMappingMode)
...
+    @Test // regression test for https://github.com/trinodb/trino/issues/24121
+    void testPartitionValuesParsedCheckpoint()
+            throws Exception
+    {
+        testPartitionValuesParsedCheckpoint(ColumnMappingMode.ID);
+        testPartitionValuesParsedCheckpoint(ColumnMappingMode.NAME);
+        testPartitionValuesParsedCheckpoint(ColumnMappingMode.NONE);
+    }
+
+    private void testPartitionValuesParsedCheckpoint(ColumnMappingMode columnMappingMode)
```
Comment (pajaks) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java:292]: Should we have also product test in `TestDeltaLakeColumnMappingMode` to check reading/writing checkpoints by trino/delta

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java (hunk 4 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java:164]: dashed should be kept as far as I confirmed Delta Lake protocol and checkpoints Spark generated locally.

https://github.com/delta-io/delta/blob/master/PROTOCOL.md#checkpoint-schema
> 
```
|    |-- partitionValues_parsed: struct
|    |    |-- col-798f4abc-c63f-444c-9a04-e2cf1ecba115: date
|    |    |-- col-19034dc3-8e3d-4156-82fc-8e05533c088e: string
```

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java [hunk 7]
```diff
@@ -270,6 +290,105 @@ private void testAddNestedColumnWithColumnMappingMode(String columnMappingMode)
...
+            testPartitionValuesParsedCheckpoint(mode, "bigint", ImmutableList.of("10000", "20000"), ImmutableList.of(10000L, 20000L));
+            testPartitionValuesParsedCheckpoint(mode, "real", ImmutableList.of("REAL '1.23'", "REAL '4.56'"), ImmutableList.of(1.23f, 4.56f));
+            testPartitionValuesParsedCheckpoint(mode, "double", ImmutableList.of("DOUBLE '12.34'", "DOUBLE '56.78'"), ImmutableList.of(12.34d, 56.78d));
+            testPartitionValuesParsedCheckpoint(
+                    mode,
+                    "decimal(3,2)",
+                    ImmutableList.of("0.12", "3.45"),
+                    ImmutableList.of(decimal("0.12", createDecimalType(3, 2)), decimal("3.45", createDecimalType(3, 2))));
+            testPartitionValuesParsedCheckpoint(mode, "varchar", ImmutableList.of("'alice'", "'bob'"), ImmutableList.of("alice", "bob"));
+            // TODO https://github.com/trinodb/trino/issues/24155 Cannot insert varbinary values into partitioned columns
```
Comment (pajaks) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java:311]: Do we have test with varbinary?

Comment (ebyhr) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java:311]: Added `TestDeltaLakeConnectorTest#testInsertIntoUnsupportedVarbinaryPartitionType`.

**Review by pajaks — APPROVED** [review]
