### PR TITLE
Fix flaky TestCassandraConnectorTest

### LINKED ISSUE #21247: Flaky test TestCassandraConnectorTest.testSelectInformationSchemaColumns, testSelectInformationSchemaTables
```
Error:  io.trino.plugin.cassandra.TestCassandraConnectorTest.testSelectInformationSchemaColumns -- Time elapsed: 3.041 s <<< FAILURE!
java.lang.AssertionError: Expected query 20240325_213705_00350_hc5v2 to succeed: SELECT * FROM information_schema.columns
	at io.trino.testing.QueryAssertions.assertQuerySucceeds(QueryAssertions.java:450)
	at io.trino.testing.AbstractTestQueryFramework.assertQuerySucceeds(AbstractTestQueryFramework.java:435)
	at io.trino.testing.AbstractTestQueryFramework.assertQuerySucceeds(AbstractTestQueryFramework.java:430)
	at io.trino.testing.BaseConnectorTest.testSelectInformationSchemaColumns(BaseConnectorTest.java:2116)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2076)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:423)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: io.trino.testing.QueryFailedException: Error listing table columns for catalog cassandra: More than one keyspace has been found for the case insensitive schema name: keyspace_3 -> (KeYsPaCe_3, kEySpAcE_3)
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:508)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:491)
	at io.trino.testing.QueryAssertions.assertQuerySucceeds(QueryAssertions.java:447)
	... 20 more
	Suppressed: java.lang.Exception: SQL: SELECT * FROM information_schema.columns
		at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:515)
		... 22 more
Caused by: io.trino.spi.TrinoException: Error listing table columns for catalog cassandra: More than one keyspace has been found for the case insensitive schema name: keyspace_3 -> (KeYsPaCe_3, kEySpAcE_3)
	at io.trino.metadata.MetadataListing.handleListingException(MetadataListing.java:358)
	at io.trino.metadata.MetadataListing.listTableColumns(MetadataListing.java:254)
	at io.trino.connector.informationschema.InformationSchemaPageSource.addColumnsRecords(InformationSchemaPageSource.java:250)
	at io.trino.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:218)
	at io.trino.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:185)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:291)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20240325_213223_186.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.trino.spi.TrinoException: More than one keyspace has been found for the case insensitive schema name: keyspace_3 -> (KeYsPaCe_3, kEySpAcE_3)
	at io.trino.plugin.cassandra.CassandraSession.getKeyspaceByCaseInsensitiveName(CassandraSession.java:292)
	at io.trino.plugin.cassandra.CassandraSession.getCaseSensitiveTableNames(CassandraSession.java:193)
	at io.trino.plugin.cassandra.CassandraMetadata.listTables(CassandraMetadata.java:169)
	at io.trino.plugin.cassandra.CassandraMetadata.listTables(CassandraMetadata.java:218)
	at io.trino.plugin.cassandra.CassandraMetadata.listTableColumns(CassandraMetadata.java:204)
	at io.trino.spi.connector.ConnectorMetadata.streamTableColumns(ConnectorMetadata.java:349)
	at io.trino.spi.connector.ConnectorMetadata.streamRelationColumns(ConnectorMetadata.java:370)
	at io.trino.tracing.TracingConnectorMetadata.streamRelationColumns(TracingConnectorMetadata.java:321)
	at io.trino.metadata.MetadataManager.listTableColumns(MetadataManager.java:669)
	at io.trino.tracing.TracingMetadata.listTableColumns(TracingMetadata.java:355)
	at io.trino.metadata.MetadataListing.doListTableColumns(MetadataListing.java:261)
	at io.trino.metadata.MetadataListing.listTableColumns(MetadataListing.java:251)
	... 16 more
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #21247

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

File: plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java [hunk 1]
```diff
@@ -222,6 +222,13 @@ public void testCharVarcharComparison()
                 .hasMessage("Unsupported type: char(3)");
     }
 
+    @Test
+    @Override
+    public void testSelectInformationSchemaColumns()
+    {
+        executeExclusively(super::testSelectInformationSchemaColumns);
```
Comment (findepi) [inline plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:229]: would be good to have a code comment explaining why

Comment (ebyhr) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:229]: https://github.com/trinodb/trino/pull/21670
