### PR TITLE
Fix failure when path contains special character on ADLS in Delta Lake

### LINKED ISSUE #15376: Delta Lake connector fails to read path containing special characters on ADLS
`org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem#open` encodes the path as URL internally. If we pass a path which was already encoded to the method argument, the Azure client makes the path double-encoded and fails to open the file. 

We should confirm other connectors as well.

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #15376

## Release notes

(x) This is not user-visible or docs only and no release notes are required (if this PR is merged in 404).

Follows https://github.com/trinodb/trino/pull/15201

### CODE REVIEW

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAzureBlobFileSystem.java [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+    @Test(groups = AZURE)
+    @Flaky(issue = ERROR_COMMITTING_WRITE_TO_HIVE_ISSUE, match = ERROR_COMMITTING_WRITE_TO_HIVE_MATCH)
+    public void testPathContainsSpecialCharacter()
+    {
+        String tableName = "test_path_special_character" + randomNameSuffix();
+        String tableLocation = schemaLocation + "/" + tableName;
+
+        onHive().executeQuery("CREATE TABLE " + tableName + " (id bigint) PARTITIONED BY (part string) LOCATION '" + tableLocation + "'");
+        onHive().executeQuery("INSERT INTO " + tableName + " VALUES (1, 'hive=equal'), (2, 'hive:colon'), (3, 'hive+plus')");
+        onTrino().executeQuery("INSERT INTO " + tableName + " VALUES (11, 'trino=equal'), (12, 'trino:colon'), (13, 'trino+plus')");
```
Comment (alexjo2144) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAzureBlobFileSystem.java:68]: Test case with a space would be good too
```suggestion
        onHive().executeQuery("INSERT INTO " + tableName + " VALUES (1, 'hive=equal'), (2, 'hive:colon'), (3, 'hive+plus'), (4, 'hive space')");
        onTrino().executeQuery("INSERT INTO " + tableName + " VALUES (11, 'trino=equal'), (12, 'trino:colon'), (13, 'trino+plus'), (14, 'trino space')");
```

Comment (findepi) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAzureBlobFileSystem.java:68]: and `%` since it's what is used in url encoding

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java [hunk 2]
```diff
@@ -291,7 +295,13 @@ private static String buildSplitPath(String tableLocation, AddFileEntry addActio
     {
         // paths are relative to the table location and are RFC 2396 URIs
         // https://github.com/delta-io/delta/blob/master/PROTOCOL.md#add-file-and-remove-file
-        String path = URI.create(addAction.getPath()).getPath();
+        URI uri = URI.create(addAction.getPath());
+        String path = uri.getPath();
+
+        // org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem encodes the path as URL
+        if (tableLocation.startsWith("abfs://") || tableLocation.startsWith("abfss://")) {
+            path = URLDecoder.decode(path, UTF_8).replace(SINGLE_WHITE_SPACE, PLUS);
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java:303]: I couldn't find existing issues. I will file a jira and add a comment.

**Comment by ebyhr** [comment]
CI hit #13199

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java [hunk 3]
```diff
@@ -291,7 +293,14 @@ private static String buildSplitPath(String tableLocation, AddFileEntry addActio
...
         // paths are relative to the table location and are RFC 2396 URIs
         // https://github.com/delta-io/delta/blob/master/PROTOCOL.md#add-file-and-remove-file
-        String path = URI.create(addAction.getPath()).getPath();
+        URI uri = URI.create(addAction.getPath());
+        String path = uri.getPath();
+
+        // org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem encodes the path as URL
+        // https://issues.apache.org/jira/browse/HADOOP-18580
+        if (tableLocation.startsWith("abfs://") || tableLocation.startsWith("abfss://")) {
+            path = URLDecoder.decode(path.replace("+", "%2B"), UTF_8);
```
Comment (alexjo2144) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java:302]: Why is the `+` symbol special?

Comment (findepi) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java:302]: https://stackoverflow.com/a/5450212 ?

**Comment by ebyhr** [comment]
Rebased on upstream to resolve conflicts.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java (hunk 3 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java:302]: Right. For instance, both `/a space` & `/a+space` would be decoded as `/a space` and Azure library throws a file not found exception for `/a+space`. I will leave a comment if needed.

**Comment by findepi** [comment]
> ## Additional context and related issues
> ## Release notes
> ( ) This is not user-visible or docs only and no release notes are required (if this PR is merged in 404). ( ) Release notes are required, with the following suggested text:
> 
> ```gfm
> # Section
> * Fix some things. ({issue}`issuenumber`)
> ```

If you're not filling the PR template, please remove it from the PR description so that it's obvious to the reader there there isn't any information to look for.

File: plugin/trino-delta-lake/src/test/resources/databricks/uri/_delta_log/00000000000000000005.json [hunk 4]
```diff
@@ -0,0 +1,2 @@
+{"add":{"path":"part=a%2525percent/part-00000-f6243f45-fea9-4d0e-8744-ef23cfe2b99c.c000.snappy.parquet","partitionValues":{"part":"a%percent"},"size":475,"modificationTime":1671166390000,"dataChange":true,"stats":"{\"numRecords\":1,\"minValues\":{\"y\":5},\"maxValues\":{\"y\":5},\"nullCount\":{\"y\":0}}"}}
```
Comment (findepi) [inline plugin/trino-delta-lake/src/test/resources/databricks/uri/_delta_log/00000000000000000005.json:1]: why `a%2525percent` and not `a%25percent`?

note also that the resource file path is `part=a%25percent/part-00000-f6243f45-fea9-4d0e-8744-ef23cfe2b99c.c000.snappy.parquet` while it probably should be `part=a%percent/part-00000-f6243f45-fea9-4d0e-8744-ef23cfe2b99c.c000.snappy.parquet`

**Review by findepi — APPROVED** [review]

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAzureBlobFileSystem.java [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+    }
+
+    @Test(groups = AZURE)
+    @Flaky(issue = ERROR_COMMITTING_WRITE_TO_HIVE_ISSUE, match = ERROR_COMMITTING_WRITE_TO_HIVE_MATCH)
+    public void testPathContainsSpecialCharacter()
+    {
+        String tableName = "test_path_special_character" + randomNameSuffix();
+        String tableLocation = schemaLocation + "/" + tableName;
+
+        onHive().executeQuery("CREATE TABLE " + tableName + " (id bigint) PARTITIONED BY (part string) LOCATION '" + tableLocation + "'");
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAzureBlobFileSystem.java:66]: `BaseDeltaLakeConnectorSmokeTest` already has a `testPathUriDecoding`.  Added a few partition cases to existing `TestDeltaLakeSelectCompatibility#testPartitionedSelectSpecialCharacters`.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAzureBlobFileSystem.java [hunk 6]
```diff
@@ -0,0 +1,97 @@
...
+    public void tearDown()
+    {
+        onHive().executeQuery("dfs -mkdir -p " + schemaLocation);
+    }
+
+    @Test(groups = AZURE)
+    @Flaky(issue = ERROR_COMMITTING_WRITE_TO_HIVE_ISSUE, match = ERROR_COMMITTING_WRITE_TO_HIVE_MATCH)
+    public void testPathContainsSpecialCharacter()
+    {
+        String tableName = "test_path_special_character" + randomNameSuffix();
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAzureBlobFileSystem.java:63]: Let me check internally.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java [hunk 7]
```diff
@@ -291,7 +293,14 @@ private static String buildSplitPath(String tableLocation, AddFileEntry addActio
     {
         // paths are relative to the table location and are RFC 2396 URIs
         // https://github.com/delta-io/delta/blob/master/PROTOCOL.md#add-file-and-remove-file
-        String path = URI.create(addAction.getPath()).getPath();
+        URI uri = URI.create(addAction.getPath());
+        String path = uri.getPath();
+
+        // org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem encodes the path as URL
+        // https://issues.apache.org/jira/browse/HADOOP-18580
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java]: > You mean that addAction.path content is URL-encoded in case of ABFS and not url encoded otherwise (HDFS, S3, ADLS, GS)?

Not exactly. addAction.path is **_URI_**-encoded. This is defined in Delta protocol https://github.com/delta-io/delta/blob/master/PROTOCOL.md#add-file-and-remove-file. _**URL**_-encoding happens in the subsequent logic when  trying to read the file on ABFS.

File: plugin/trino-delta-lake/src/test/resources/databricks/uri/_delta_log/00000000000000000005.json (hunk 4 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/test/resources/databricks/uri/_delta_log/00000000000000000005.json:1]: The path is escaped at `DeltaLakePageSink#makePartName` and encoded at `DeltaLakeMetadata#toUriFormat`. 

> note also that the resource file path is part=a%25percent/part-00000-f6243f45-fea9-4d0e-8744-ef23cfe2b99c.c000.snappy.parquet while it probably should be part=a%percent/part-00000-f6243f45-fea9-4d0e-8744-ef23cfe2b99c.c000.snappy.parquet

It's exactly weird, but the resource path is the same as what Spark generated. 

Filed #15499 to investigate the details.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java (hunk 3 above)
Comment (findepi) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java:303]: Looking at the https://github.com/trinodb/trino/pull/17038 I now think the code shouldn't be here at all.
We should defer ABFS filesstem hacks until we talk to the filesystem, i.e. do this on the worker when opening the split.
This would also make it impossible/hard to apply the logic inconsistently for relative/absolute paths, as per https://github.com/trinodb/trino/pull/17038#discussion_r1188386453



cc @vinay-kl @findinpath @alexjo2144 @ebyhr
