### PR TITLE
Fix SHOW ROLES where there are no roles to display

### LINKED ISSUE #9189: `SHOW [CURRENT] ROLES` fails with `IllegalStateException` when there are no roles to display
```
trino:tpch> show roles;
Query 20210909_201730_00058_csqwf failed: Internal error
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:494)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitValues(StatementAnalyzer.java:2425)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitValues(StatementAnalyzer.java:360)
	at io.trino.sql.tree.Values.accept(Values.java:55)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:1861)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:360)
	at io.trino.sql.tree.AliasedRelation.accept(AliasedRelation.java:71)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3185)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1955)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:360)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:387)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1169)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:360)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:340)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_testversion____20210909_201458_3.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by kokosing**
Fix SHOW ROLES where there are no roles to display

Fixes #9189

### CODE REVIEW

**Comment by kokosing** [comment]
Fixes https://github.com/trinodb/trino/issues/9189

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java [hunk 1]
```diff
@@ -292,26 +293,28 @@ protected Node visitShowRoles(ShowRoles node, Void context)
         {
             Optional<String> catalog = node.getCatalog().map(c -> c.getValue().toLowerCase(ENGLISH));
 
+            List<Expression> rows;
```
Comment (ssheikin) [inline core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:296]: please extract method to obtain rows

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java [hunk 2]
```diff
@@ -548,7 +557,8 @@ protected Node visitShowCreate(ShowCreate node, Void context)
                 accessControl.checkCanShowCreateTable(session.toSecurityContext(), new QualifiedObjectName(catalogName.getValue(), schemaName.getValue(), tableName.getValue()));
 
                 CreateView.Security security = viewDefinition.get().isRunAsInvoker() ? INVOKER : DEFINER;
-                String sql = formatSql(new CreateView(QualifiedName.of(ImmutableList.of(catalogName, schemaName, tableName)), query, false, viewDefinition.get().getComment(), Optional.of(security))).trim();
+                String sql = formatSql(new CreateView(QualifiedName.of(ImmutableList.of(catalogName, schemaName, tableName)), query, false, viewDefinition.get()
+                        .getComment(), Optional.of(security))).trim();
```
Comment (ssheikin) [inline core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:561]: consider better formatting here and below. Please move it to the separate commit

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java [hunk 3]
```diff
@@ -292,26 +293,28 @@ protected Node visitShowRoles(ShowRoles node, Void context)
...
+                rows = metadata.listRoles(session, catalog).stream()
                         .map(role -> row(new StringLiteral(role)))
                         .collect(toList());
-                return simpleQuery(
-                        selectList(new AllColumns()),
-                        aliased(new Values(rows), "role_name", ImmutableList.of("Role")));
             }
+            List<String> columns = ImmutableList.of("Role");
+            if (rows.isEmpty()) {
+                return emptyQuery(columns);
```
Comment (ssheikin) [inline core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:313]: Do I understand correctly that this was impossible situation for the Connector Roles (when System Access roles were not implemented) to return the empty result?

Comment (kokosing) [reply core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:313]: No, it was implemented differently. It was reading previously from a `information_schema.roles`, now we are using `VALUES`

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java [hunk 4]
```diff
@@ -317,10 +317,6 @@ protected Node visitShowRoles(ShowRoles node, Void context)
         @Override
         protected Node visitShowRoleGrants(ShowRoleGrants node, Void context)
         {
-            if (node.getCatalog().isEmpty() && session.getCatalog().isEmpty()) {
-                throw semanticException(MISSING_CATALOG_NAME, node, "Catalog must be specified when session catalog is not set");
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:321]: This should come with a test addition/change. Seems we're missing testing coverage.

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java [hunk 5]
```diff
@@ -292,26 +293,28 @@ protected Node visitShowRoles(ShowRoles node, Void context)
...
-                        selectList(new AllColumns()),
-                        aliased(new Values(rows), "role_name", ImmutableList.of("Role")));
             }
+            List<String> columns = ImmutableList.of("Role");
+            if (rows.isEmpty()) {
+                return emptyQuery(columns);
+            }
+            return simpleQuery(
+                    selectList(new AllColumns()),
+                    aliased(new Values(rows), "role_name", columns));
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:317]: pre-exsiting, is the role_name alias meaningless?

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java [hunk 6]
```diff
@@ -515,7 +522,9 @@ protected Node visitShowCreate(ShowCreate node, Void context)
                 accessControl.checkCanShowCreateTable(session.toSecurityContext(), new QualifiedObjectName(catalogName.getValue(), schemaName.getValue(), tableName.getValue()));
 
                 Map<String, Object> properties = viewDefinition.get().getProperties();
-                Map<String, PropertyMetadata<?>> allMaterializedViewProperties = metadata.getMaterializedViewPropertyManager().getAllProperties().get(new CatalogName(catalogName.getValue()));
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:522]: unrelated change?

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java [hunk 7]
```diff
@@ -548,7 +557,8 @@ protected Node visitShowCreate(ShowCreate node, Void context)
                 accessControl.checkCanShowCreateTable(session.toSecurityContext(), new QualifiedObjectName(catalogName.getValue(), schemaName.getValue(), tableName.getValue()));
 
                 CreateView.Security security = viewDefinition.get().isRunAsInvoker() ? INVOKER : DEFINER;
-                String sql = formatSql(new CreateView(QualifiedName.of(ImmutableList.of(catalogName, schemaName, tableName)), query, false, viewDefinition.get().getComment(), Optional.of(security))).trim();
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:555]: unrelated change?

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java [hunk 8]
```diff
@@ -579,7 +589,8 @@ protected Node visitShowCreate(ShowCreate node, Void context)
                         .filter(column -> !column.isHidden())
                         .map(column -> {
                             List<Property> propertyNodes = buildProperties(targetTableName, Optional.of(column.getName()), INVALID_COLUMN_PROPERTY, column.getProperties(), allColumnProperties);
-                            return new ColumnDefinition(new Identifier(column.getName()), toSqlType(column.getType()), column.isNullable(), propertyNodes, Optional.ofNullable(column.getComment()));
+                            return new ColumnDefinition(new Identifier(column.getName()), toSqlType(column.getType()), column.isNullable(), propertyNodes, Optional.ofNullable(column
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:592]: unrelated change?

File: core/trino-parser/src/main/java/io/trino/sql/QueryUtil.java [hunk 9]
```diff
@@ -267,6 +268,24 @@ public static Query singleValueQuery(String columnName, boolean value)
                 aliased(values, "t", ImmutableList.of(columnName)));
     }
 
+    public static Query emptyQuery(List<String> columns)
+    {
+        Select select = selectList(columns.stream()
+                .map(column -> new SingleColumn(new NullLiteral(), QueryUtil.identifier(column)))
```
Comment (findepi) [inline core/trino-parser/src/main/java/io/trino/sql/QueryUtil.java:274]: as a follow up we might want to have the columns be of proper type, eg varchar for role names

**Review by findepi — APPROVED** [review]

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java (hunk 5 above)
Comment (kokosing) [reply core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java]: It depends. I think the value used here is wrong here. It is an alias for a relation. So possibly you could reference the relation via column names. So in this test is meaningless, but in general it is needed.

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java (hunk 1 above)
Comment (kokosing) [reply core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java]: No. I will extract a method to handle rows. It will be better.

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java (hunk 6 above)
Comment (kokosing) [reply core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java:522]: extracted to separate commit

File: core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java (hunk 8 above)
Comment (kokosing) [reply core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java]: extracted to separate commit

**Review by kokosing — COMMENTED** [review]
AC

File: core/trino-parser/src/main/java/io/trino/sql/QueryUtil.java (hunk 9 above)
Comment (findepi) [reply core/trino-parser/src/main/java/io/trino/sql/QueryUtil.java:274]: consider adding todo here

**Review by findepi — APPROVED** [review]
