### PR TITLE
Fix failure when query table function contains column alias in JDBC connectors

### LINKED ISSUE #16225: ptf fails when alias exists for result column
企业微信截图_16771221992510

alias exist, query failed
alias not exist, query success

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #16225

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# MySQL, Druid, MariaDB, SingleStore
* Fix failure when `query` table function contains column alias. ({issue}`16225`)
```

### CODE REVIEW

File: plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java [hunk 1]
```diff
@@ -256,6 +256,16 @@ public void testTableWithOnlyUnsupportedColumns()
         }
     }
 
+    @Override
+    public void testNativeQueryColumnAlias()
+    {
+        // override because H2 uppercase column names by default
+        assertThat(query(format("SELECT * FROM TABLE(system.query(query => 'SELECT name AS region_name FROM %s.region WHERE regionkey = 0'))", getSession().getSchema().orElseThrow())))
+                .skippingTypesCheck()
```
Comment (martint) [inline plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java:264]: Why skip types check?

File: plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java [hunk 2]
```diff
@@ -1405,6 +1405,15 @@ public void testNativeQuerySelectFromNation()
                 .isNotFullyPushedDown(FilterNode.class);
     }
 
+    @Test
+    public void testNativeQueryColumnAlias()
+    {
+        assertThat(query("SELECT * FROM TABLE(system.query(query => 'SELECT name AS region_name FROM tpch.region WHERE regionkey = 0 ALLOW FILTERING'))"))
+                .skippingTypesCheck()
+                .hasOutputNames(ImmutableList.of("region_name"))
```
Comment (martint) [inline plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:1413]: There's no guarantee that the outputs of the query will match the column names in the table function. If you want to be absolutely sure, you should do something like:

```
SELECT region_name FROM TABLE(...)
```

which should fail if the column is not exposed by the table function.

**Review by martint — CHANGES_REQUESTED** [review]

File: plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java (hunk 2 above)
Comment (ebyhr) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:1413]: Changing to the suggested query hides the actual output column names. For instance, the below test pass in H2. 
```java
```

File: plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java:264]: Type check is unrelated to this test. Otherwise, the test will fail due to length difference: `varchar(25)` vs `varchar(6)`

**Comment by ebyhr** [comment]
@martint Please take a look at the above comments.

File: plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java (hunk 2 above)
Comment (martint) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:1413]: Not sure what you mean. If the table function doesn’t expose the name, the outer query should fail with a column not found error.

Also, what do you mean by “passes on H2”? That query should not even run against H2, since it H2 doesn’t support table functions, or any of the table functions in Trino.

File: plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java (hunk 1 above)
Comment (martint) [reply plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java:264]: You need to use CAST(… as varchar(25)) in the .matches() clause. The assertion framework performs strict type checking.

Comment (ebyhr) [reply plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java:264]: I knew and didn't add the cast intentionally. I will fix it though.

File: plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java (hunk 2 above)
Comment (martint) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:1413]: For example, given:

```
SELECT region_name FROM TABLE(system.query(query => 'SELECT name FROM tpch.region WHERE regionkey = 0'));
```

=>

```
Query 20230225_223332_00030_tgtxv failed: line 1:8: Column 'region_name' cannot be resolved
```

Comment (ebyhr) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:1413]: We have `TestJdbcConnectorTest` running on H2. 

The given example ensures column names **_without case sensitivity_**. The below query (added a column alias to the table function) should pass in my understanding because `SELECT name FROM (SELECT name as "NAME" FROM region)` is a valid query in Trino. This is what happening on the above H2 example, the table function exposes the column names with uppercase, but adding the projection lowercase the final output column names. That's why I didn't add the projection. 
```
SELECT name FROM TABLE(system.query(query => 'SELECT name AS "NAME" FROM tpch.region WHERE regionkey = 0'));
  name
--------
 AFRICA
```

Comment (martint) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:1413]: > We have TestJdbcConnectorTest running on H2.

Some tests do, but QueryAssert does not use H2. It runs the given query and compares the results to the output of the .matches() clause (which is another query that runs in Trino).

Comment (martint) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:1413]: > The given example ensures column names without case sensitivity.

Well, it tests that the name is resolvable using Trino's identifier resolution rules (which, unfortunately, currently don't follow proper SQL semantics).

Comment (ebyhr) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:1413]: > Some tests do, but QueryAssert does not use H2. It runs the given query and compares the results to the output of the .matches() clause (which is another query that runs in Trino).

`TestJdbcConnectorTest` uses `createH2QueryRunner`. The behind database is H2 regardless of assertion methods.

Comment (ebyhr) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java:1412]: Added some test cases and comments to clarify the above behaviors.

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java [hunk 3]
```diff
@@ -253,7 +253,8 @@ public JdbcTableHandle getTableHandle(ConnectorSession session, PreparedQuery pr
                 throw new UnsupportedOperationException("Query not supported: ResultSetMetaData not available for query: " + preparedQuery.getQuery());
             }
             for (int column = 1; column <= metadata.getColumnCount(); column++) {
-                String name = metadata.getColumnName(column);
+                // Use getColumnLabel method because query pass-through table function may contain column aliases
+                String name = metadata.getColumnLabel(column);
```
Comment (allendang001) [inline plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java:257]: so，is this the key to problem？

Comment (ebyhr) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java:257]: Yes.

**Comment by ebyhr** [comment]
@martint Please take another look.

File: core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java [hunk 4]
```diff
@@ -438,6 +438,16 @@ public QueryAssert containsAll(MaterializedResult expected)
             });
         }
 
+        @CanIgnoreReturnValue
+        public QueryAssert hasOutputNames(List<String> expectedNames)
```
Comment (wendigo) [inline core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java:442]: nit: hasColumnNames (consistent with the `actual.getColumnNames()` that we are checking here)

File: core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java [hunk 5]
```diff
@@ -438,6 +438,16 @@ public QueryAssert containsAll(MaterializedResult expected)
...
+        {
+            return satisfies(actual -> {
+                assertThat(actual.getColumnNames())
+                        .as("Output names for query [%s]", query)
```
Comment (wendigo) [inline core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java:446]: Column names for query [%s]

File: core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java (hunk 4 above)
Comment (wendigo) [inline core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java:442]: maybe vararg instead: `public QueryAssert hasOutputNames(String... columnNames)`

then the assertion will be more readable:

```
assertThat(query("SELECT * FROM TABLE(system.query(query => 'SELECT name AS region_name FROM tpch.region WHERE regionkey = 0'))"))
                .hasColumnNames("region_name")
                .matches("VALUES CAST('AFRICA' AS VARCHAR)");

```

**Review by wendigo — APPROVED** [review]
LGTM! Thanks @ebyhr

**Comment by ebyhr** [comment]
@hashhar @Praveen2112 Gentle reminder.

File: plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java (hunk 2 above)
Comment (ebyhr) [reply plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java]: @martint Gentle reminder.

**Review by hashhar — APPROVED** [review]
Looks good to me. @Praveen2112 do you want to take a look?

I don't understand Martin's concerns since none of this happens within the engine, it's how the connector reports information back to the engine and this is actually a bugfix showcased by the tests.

**Review by wendigo — APPROVED** [review]

**Comment by martint** [comment]
What I said above is that we shouldn’t be verifying that the table function exposes the expected names by checking how they are propagated outside of the outer query. We can validate that by having the outer query try to resolve the names directly.

**Comment by ebyhr** [comment]
> We can validate that by having the outer query try to resolve the names directly.

It's already addressed.
