### PR TITLE
Fix SET TIME ZONE LOCAL works appropriate

### LINKED ISSUE #15314: SET TIME ZONE LOCAL does not work as documented
From 403's docs https://trino.io/docs/403/sql/set-time-zone.html

> If the LOCAL option is specified, the time zone for the current session is set to the initial time zone of the session.

Iinitial time zone is the client's default zone.

From the code:

https://github.com/trinodb/trino/blob/c05c73967185be545d01a8e1e7abb2d4dca9767b/core/trino-main/src/main/java/io/trino/execution/SetTimeZoneTask.java#L81

i.e. Trino server's default zone

### Expected

* clearly docs and code should be aligned
* intuitively, server's zone should be invisible to the client, so I think docs are right, not the code.

### PR DESCRIPTION
**Pull request by leeyh0216**
## Description

This is a PR to solve the #15314 issue.

`SET TIME ZONE LOCAL` statement means to reflect the TimeZone initially set on the client. Currently, if TimeZone information is not checked in the syntax (LOCAL), the default TimeZone of the server is reflected.

In the case of LOCAL, rather than setting the client TimeZone in `SessionProperties`, the code was modified to invalidate the TIME_ZONE_ID set in `SessionProperties` and use the client's TimeZoneKey.

Based on the changed code, it works as follows.

* Server's timezone: `America/Los_Angeles`
* Client's timezone: `Europe/Warsaw`

```

trino> select current_timestamp;
                 _col0                 
---------------------------------------
 2022-12-08 07:47:48.873 Europe/Warsaw 
(1 row)

Query 20221208_064748_00005_yxge6, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.14 [0 rows, 0B] [0 rows/s, 0B/s]

trino> SET TIME ZONE 'Asia/Seoul';
SET TIME ZONE
trino> select current_timestamp;
               _col0                
------------------------------------
 2022-12-08 15:48:04.399 Asia/Seoul 
(1 row)

Query 20221208_064804_00007_yxge6, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.08 [0 rows, 0B] [0 rows/s, 0B/s]

trino> SET TIME ZONE LOCAL;
SET TIME ZONE
trino> select current_timestamp;
                 _col0                 
---------------------------------------
 2022-12-08 07:48:12.829 Europe/Warsaw 
(1 row)

Query 20221208_064812_00009_yxge6, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.16 [0 rows, 0B] [0 rows/s, 0B/s]
```

## Additional context and related issues

Fixes #15314

## Release notes

(x) Release notes are required, please propose a release note for me.

### CODE REVIEW

**Comment by leeyh0216** [comment]
Hi, @findepi 
Can you review this PR Please? 

In the case of a CLA, it is in a submitted state and is still waiting to be processed.

**Review by hashhar — APPROVED** [review]
LGTM. But @findepi please take a look.

**Comment by hashhar** [comment]
@leeyh0216 Please squash the commits together - we want each commit to compile and pass tests so that in future bisecting is easier.

File: core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java [hunk 1]
```diff
@@ -79,9 +79,23 @@ public void testSetTimeZoneLocal()
                 Optional.empty());
         executeSetTimeZone(setTimeZone, stateMachine);
 
+        assertThat(stateMachine.getSetSessionProperties()).hasSize(0);
+    }
+
+    @Test
+    public void testSetTimeZoneLocalAfterSetTimeZoneExecuted()
+    {
+        QueryStateMachine stateMachine = createQueryStateMachine("SET TIME ZONE 'America/Bahia_Banderas'");
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java:88]: Not sure i follow. This `stateMachine` is worked on, but not asserted on.

Comment (leeyh0216) [reply core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java:88]: @findepi 

After checking, the test itself was meaningless because there was no connection between the first `QueryStateMachine` and the second `QueryStateMachine` object. 

When creating the second `QueryStateMachine`, do you think setting `setSessionProperties` of the first `QueryStateMachine` to the second `setSessionProperties` would be appropriate?

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
Assigning to @martint because of pending CLA.

**Comment by ebyhr** [comment]
@cla-bot check

**Comment by ebyhr** [comment]
`ci / pt (default, suite-cassandra` hit #12818

**Comment by ebyhr** [comment]
@findepi CLA was registered yesterday. Can we merge this PR now?

**Comment by findepi** [comment]
> `ci / pt (default, suite-cassandra` hit #12818

i don't see any new comment under that issue. did you mean to post a message there too?

**Comment by findepi** [comment]
> @findepi CLA was registered yesterday. Can we merge this PR now?

sure, go for it!
