### PR TITLE
Run testReplaceTableWithSchemaChangeOnCheckpoint only with OSS Delta

### LINKED ISSUE #19580: Flaky or broken TestDeltaLakeCreateTableAsSelectCompatibility.testReplaceTableWithSchemaChangeOnCheckpoint on 9.1 LTS
https://github.com/trinodb/trino/actions/runs/6700193910/job/18206194746?pr=19564

```
tests               | 2023-10-31 06:37:50 INFO: FAILURE     /    io.trino.tests.product.deltalake.TestDeltaLakeCreateTableAsSelectCompatibility.testReplaceTableWithSchemaChangeOnCheckpoint (Groups: profile_specific_tests, delta-lake-databricks, delta-lake-exclude-133, delta-lake-oss) took 36.9 seconds
tests               | 2023-10-31 06:37:50 SEVERE: Failure cause:
tests               | java.lang.AssertionError: expected [00000000000000000011.json] but found [00000000000000000012.json]
tests               | 	at org.testng.Assert.fail(Assert.java:94)
tests               | 	at org.testng.Assert.failNotEquals(Assert.java:513)
tests               | 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
tests               | 	at org.testng.Assert.assertEquals(Assert.java:116)
tests               | 	at org.testng.Assert.assertEquals(Assert.java:190)
tests               | 	at org.testng.Assert.assertEquals(Assert.java:200)
tests               | 	at io.trino.tests.product.deltalake.TransactionLogAssertions.assertTransactionLogVersion(TransactionLogAssertions.java:50)
tests               | 	at io.trino.tests.product.deltalake.TestDeltaLakeCreateTableAsSelectCompatibility.testReplaceTableWithSchemaChangeOnCheckpoint(TestDeltaLakeCreateTableAsSelectCompatibility.java:195)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Probably, OPTIMIZE procedure ran in the background on Databricks side. 
Fixes #19580

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java [hunk 1]
```diff
@@ -172,9 +171,7 @@ public void testReplaceTableWithSchemaChange()
         }
     }
 
-    // Databricks 11.3, 12.2 and 13.3 don't create a checkpoint file at 'CREATE OR REPLACE TABLE' statement
-    @Test(groups = {DELTA_LAKE_DATABRICKS, DELTA_LAKE_OSS, DELTA_LAKE_EXCLUDE_133, PROFILE_SPECIFIC_TESTS})
-    @Flaky(issue = DATABRICKS_COMMUNICATION_FAILURE_ISSUE, match = DATABRICKS_COMMUNICATION_FAILURE_MATCH)
+    @Test(groups = {DELTA_LAKE_OSS, PROFILE_SPECIFIC_TESTS})
```
Comment (Praveen2112) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java:174]: So does this means - `Replace table` doesn't create a new checkpoint on Databricks side ?

Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java:174]: Yes. Or it might be a bug in assertLastEntryIsCheckpointed method.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TransactionLogAssertions.java [hunk 2]
```diff
@@ -50,43 +46,6 @@ public static void assertTransactionLogVersion(AmazonS3 s3Client, String bucketN
         assertEquals(lastJsonEntry.get(), format("%020d.json", versionNumber));
     }
 
-    public static void assertNewVersion(AmazonS3 s3Client, String bucketName, String tableName, ThrowingRunnable runnable)
```
Comment (Praveen2112) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TransactionLogAssertions.java:53]: nit: This one is not related to excluding the test right ?

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java (hunk 1 above)
Comment (Praveen2112) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java:174]: Bug as in ?

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TransactionLogAssertions.java (hunk 2 above)
Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TransactionLogAssertions.java:53]: Right.

**Review by Praveen2112 — APPROVED** [review]
