### PR TITLE
Ignore failures translating hive views while listing views

### LINKED ISSUE #6370: Queries to information_schema.views fails with Hive view translation enabled
When Hive view translation is enabled, the following type of query is failing:

    SELECT table_name FROM information_schema.views WHERE table_schema='default'

See below for full exception, but apparently Presto actually tries to translate the view names returned by the query.

```
    io.prestosql.spi.PrestoException: Failed to translate Hive view 'default.fact_eta_segments_with_flags_hive': At line 0, column 0: No match found for function signature greatest(<NUMERIC>, <NUMERIC>)
        at io.prestosql.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:180)
        at io.prestosql.plugin.hive.HiveMetadata.lambda$getView$57(HiveMetadata.java:1935)
        at java.base/java.util.Optional.map(Optional.java:265)
        at io.prestosql.plugin.hive.HiveMetadata.getView(HiveMetadata.java:1929)
        at io.prestosql.spi.connector.ConnectorMetadata.getViews(ConnectorMetadata.java:551)
        at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getViews(ClassLoaderSafeConnectorMetadata.java:506)
        at io.prestosql.metadata.MetadataManager.getViews(MetadataManager.java:1037)
        at io.prestosql.metadata.MetadataListing.getViews(MetadataListing.java:109)
        at io.prestosql.connector.informationschema.InformationSchemaPageSource.addViewsRecords(InformationSchemaPageSource.java:301)
        at io.prestosql.connector.informationschema.InformationSchemaPageSource.buildPages(InformationSchemaPageSource.java:222)
        at io.prestosql.connector.informationschema.InformationSchemaPageSource.getNextPage(InformationSchemaPageSource.java:183)
        at io.prestosql.operator.ScanFilterAndProjectOperator$ConnectorPageSourceToPages.process(ScanFilterAndProjectOperator.java:376)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils$YieldingProcess.process(WorkProcessorUtils.java:181)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
        at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
        at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
        at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_____20201216_171228_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.calcite.runtime.CalciteContextException: At line 0, column 0: No match found for function signature greatest(<NUMERIC>, <NUMERIC>)
        at jdk.internal.reflect.GeneratedConstructorAccessor450.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
        at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:834)
        at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:819)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4867)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.handleUnresolvedFunction(SqlValidatorImpl.java:1770)
        at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:288)
        at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:216)
        at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5626)
        at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5613)
        at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1688)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1673)
        at org.apache.calcite.sql.SqlOperator.deriveType(SqlOperator.java:501)
        at org.apache.calcite.sql.SqlBinaryOperator.deriveType(SqlBinaryOperator.java:144)
        at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5626)
        at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5613)
        at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1688)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1673)
        at org.apache.calcite.sql.type.InferTypes.lambda$static$0(InferTypes.java:46)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1868)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1876)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1839)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.inferUnknownTypes(SqlValidatorImpl.java:1856)
        at com.linkedin.coral.hive.hive2rel.HiveSqlValidator.inferUnknownTypes(HiveSqlValidator.java:50)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.expandSelectItem(SqlValidatorImpl.java:474)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelectList(SqlValidatorImpl.java:4104)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3392)
        at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
        at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1005)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:965)
        at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:216)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:940)
        at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:647)
        at com.linkedin.coral.hive.hive2rel.HiveSqlToRelConverter.convertQuery(HiveSqlToRelConverter.java:58)
        at com.linkedin.coral.hive.hive2rel.HiveToRelConverter.toRel(HiveToRelConverter.java:126)
        at com.linkedin.coral.hive.hive2rel.HiveToRelConverter.convertView(HiveToRelConverter.java:108)
        at io.prestosql.plugin.hive.ViewReaderUtil$HiveViewReader.decodeViewData(ViewReaderUtil.java:161)
        ... 47 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: No match found for function signature greatest(<NUMERIC>, <NUMERIC>)
        at jdk.internal.reflect.GeneratedConstructorAccessor449.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
        at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572)
        ... 124 more
```

### PR DESCRIPTION
**Pull request by phd3**
Fix #6370

### CODE REVIEW

File: presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java [hunk 1]
```diff
@@ -1917,6 +1918,26 @@ public boolean supportsMetadataDelete(ConnectorSession session, ConnectorTableHa
...
+    @Override
+    public Map<SchemaTableName, ConnectorViewDefinition> getViews(ConnectorSession session, Optional<String> schemaName)
+    {
+        ImmutableMap.Builder<SchemaTableName, ConnectorViewDefinition> views = ImmutableMap.builder();
+        for (SchemaTableName name : listViews(session, schemaName)) {
+            try {
+                getView(session, name).ifPresent(view -> views.put(name, view));
+            }
+            catch (PrestoException e) {
+                if (e.getErrorCode().equals(HIVE_VIEW_TRANSLATION_ERROR.toErrorCode())) {
```
Comment (JamesRTaylor) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java:1930]: What's the implication of not adding failing views to the view map? What would happen if one of these views was referenced in a query?

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java [hunk 2]
```diff
@@ -231,6 +233,32 @@ public void testHiveViewInInformationSchema()
                 .contains(row("n_nationkey", "bigint", "", ""));
     }
 
+    @Test(groups = HIVE_VIEWS)
+    public void testFailingHiveViewsForInformationSchema()
```
Comment (JamesRTaylor) [inline presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:237]: Based on your comment, are you leaning toward not committing this test because you're worried about future versions of Coral supporting these functions? Perhaps you can instead use a construct that you think may never be supported by Coral? I like the idea of keeping the test if it's possible. FWIW, there are often times that tests need to be removed as functionality evolves.

**Comment by JamesRTaylor** [comment]
👍

File: presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java [hunk 3]
```diff
@@ -1917,6 +1918,26 @@ public boolean supportsMetadataDelete(ConnectorSession session, ConnectorTableHa
         return handle.getTableParameters().isEmpty() || !isFullAcidTable(handle.getTableParameters().get());
     }
 
+    @Override
+    public Map<SchemaTableName, ConnectorViewDefinition> getViews(ConnectorSession session, Optional<String> schemaName)
```
Comment (findepi) [inline presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java:1922]: Can we have a test for reading information_schema.views when one of the views cannot be translated?
(in fact, we could perhaps define a totally bogus view for that -- would that be possible?)

Also, can we have a test for reading information_schema.columns without and with filter?
This is where the `ConnectorMetadata.getViews` seems to be also used.

Comment (phd3) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java:1922]: Added the suggested tests.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java (hunk 2 above)
Comment (phd3) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:237]: Added a more reliable test.

File: presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java (hunk 1 above)
Comment (phd3) [reply presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java:1930]: view resolution shouldn't be impacted, as getViews method is only used for listing views and columns.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java [hunk 4]
```diff
@@ -231,6 +233,45 @@ public void testHiveViewInInformationSchema()
...
+    {
+        if (getHiveVersionMajor() < 3) {
+            // Skip older versions since they don't support "getTableNamesByType" in ThriftHiveMetastore#getAllViews
+            throw new SkipException("Only test the behavior for hive 3");
```
Comment (findepi) [inline presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:241]: Maybe add a bit more explanation:
```
// Skip older versions since they don't support "getTableNamesByType" in ThriftHiveMetastore#getAllViews
// and so information_schema.views does not include translated Hive views properly
```

BTW, it still worthwhile to run the test with older Hive versions, just the assertions would be different -- to document current behavior & prevent regressions. 
How would it look like if you used `getHiveVersionMajor()` on per-assertion basis?
kind of like https://github.com/prestosql/presto/blob/3c5b5b053affa6cf093e7f4cbca0bb26d9bfb380/presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTableStatistics.java#L129-L131

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java [hunk 5]
```diff
@@ -231,6 +233,45 @@ public void testHiveViewInInformationSchema()
...
+                .containsOnly(row("correct_view"));
+
+        // Listing fails when metadata for the problematic view is queried specifically
+        assertThatThrownBy(() -> query("SELECT table_name FROM information_schema.views WHERE table_schema = 'test_list_failing_views' and table_name = 'failing_view'"))
+                .hasMessageContaining("Failed to translate Hive view 'test_list_failing_views.failing_view'");
+
+        // Queries on information_schema.columns also trigger ConnectorMetadata#getViews. Columns from failing_view are
+        // listed too since HiveMetadata#listTableColumns does not ignore views.
+        assertThat(query("SELECT DISTINCT table_name FROM information_schema.columns WHERE table_schema = 'test_list_failing_views'"))
+                .containsOnly(row("correct_view"), row("failing_view"));
```
Comment (findepi) [inline presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:269]: `DISTINCT table_name` -> table_name, column_name

so that we test also _what_ is returned for these views

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java [hunk 6]
```diff
@@ -231,6 +233,45 @@ public void testHiveViewInInformationSchema()
...
+
+        assertThatThrownBy(() -> query("SELECT * FROM information_schema.columns WHERE table_schema = 'test_list_failing_views' AND table_name = 'failing_view'"))
+                .hasMessageContaining("Failed to translate Hive view 'test_list_failing_views.failing_view'");
```
Comment (findepi) [inline presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:272]: Why does it fail? In the unfiltered `information_schema.columns` query we were OK to use information available in metastore, without translating the view. Why are we not doing this here?

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java (hunk 4 above)
Comment (losipiuk) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:241]: Can you also add a test to `TestHiveViewsLegacy.java` to document behavior difference.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java (hunk 6 above)
Comment (phd3) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:272]: This is because the unfiltered version uses `HiveMetadata#getViews`, which ignores failures. Filtered version uses `HiveMetadata#getView` which doesn't.

Comment (findepi) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:280]: That's technically understood and what i anticipated, but is there a sound reason for the difference?

Comment (phd3) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:280]: Note that `information_schema.views` also has a similar discrepancy of ignoring v/s failing for unfiltered v/s filtered case. Do you think the discrepancy is okay there but not for `information_schema.columns`?

An argument in favor of the discrepancy is that - we want to show most other metadata (from valid views) when only some of the tables/views have invalid metadata. In the "filtered" case, the specific view being looked for is problematic, so failing doesn't result in losing any metadata.

To make filtered v/s unfiltered cases more consistent, I think it'd help to make `ConnectorMetadata#getViews` (and other listing calls) return an iterator, but may be do such an SPI change in a separate PR.

Comment (phd3) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java:280]: From SQL perspective, I see how this is problematic. While listing with a coerce filter, we ignore the failing view. But for point-lookup, we fail the query. So to be consistent, we might want to always ignore so that we can atleast return partial correct metadata where we can. How about we swallow PrestoExceptions from https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java#L1036 to do this? This will resolve discrepancy for both the tables.

Comment (findepi) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java]: I think you made a valid point and i see how inconsistent it is. It is not limited to views either and we have this "ignore or throw? sacrifice SQL consistency?" challenge in other places as well.

I think it does not help to solve those cases on one-by-one basis, as this may lead to different decisions in different cases (eg due to different priorities or whatever else). 
Let's maybe have a dedicated discussion, document the outcome somewhere and go ahead. 
My prediction is that chances are high we come to the conclusion aligned with your thinking, but i would really want to preserve the consistency by being a bit more structured about the decision making process.
What do you think?

**Comment by JamesRTaylor** [comment]
@phd3 @findepi - would it be possible to get this committed soon? We've had to completely disable this feature which is a shame.

File: presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java (hunk 6 above)
Comment (phd3) [reply presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java]: @findepi Does it seem reasonable to you to go ahead with this PR in the current form? We can update this test for filtered case in future according to the final verdict in #6551. (The current approach seems aligned with @kokosing 's opinion too.)

**Comment by findepi** [comment]
> would it be possible to get this committed soon?

@JamesRTaylor i proposed that we reach a conclusion on a general approach and this is why @phd3 started https://github.com/trinodb/trino/issues/6551
I do not see a consensus there yet.

**Comment by findepi** [comment]
> perhaps in the meantime it'd be useful to disable Coral integration or document that it's broken so that others don't turn it on and run into the same problems we did.

@JamesRTaylor i agree with you that coral-based view handling is not ready to be enabled by default.
There is a bunch of issues that need to be done tracked in https://github.com/trinodb/trino/issues/5606, 
some of them are even regressions from the previous naive hive view handling logic.

**Comment by JamesRTaylor** [comment]
> i agree with you that coral-based view handling is not ready to be enabled by default.

@findepi - until this is fixed, it should not even be possible to enable coral integration. It causes production issues which aren't immediately clear are relate to coral.

What's the downside of committing this PR while letting the other PRs continue on their own course? It fixes the issue and puts the coral integration back into a working state.

**Comment by wmoustafa** [comment]
@findepi, @phd3 can we commit this PR until the discussion in #6551 is resolved?

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java [hunk 7]
```diff
@@ -2006,6 +2007,26 @@ public boolean supportsMetadataDelete(ConnectorSession session, ConnectorTableHa
...
+    public Map<SchemaTableName, ConnectorViewDefinition> getViews(ConnectorSession session, Optional<String> schemaName)
+    {
+        ImmutableMap.Builder<SchemaTableName, ConnectorViewDefinition> views = ImmutableMap.builder();
+        for (SchemaTableName name : listViews(session, schemaName)) {
+            try {
+                getView(session, name).ifPresent(view -> views.put(name, view));
+            }
+            catch (TrinoException e) {
+                if (e.getErrorCode().equals(HIVE_VIEW_TRANSLATION_ERROR.toErrorCode())) {
+                    // Ignore hive views for which translation fails
```
Comment (findepi) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java:2020]: We should also ignore `TableNotFoundException` (race condition)

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java [hunk 8]
```diff
@@ -13,5 +13,71 @@
...
 public class TestHiveViews
-        extends AbstractTestHiveViews {}
+        extends AbstractTestHiveViews
+{
+    @Test(groups = HIVE_VIEWS)
+    public void testFailingHiveViewsForInformationSchema()
+    {
+        // The expected behavior is different across hive versions. For hive 3, the call "getTableNamesByType" is
+        // used in ThriftHiveMetastore#getAllViews. For older versions, the fallback to doGetTablesWithParameter
+        // is used, so information_schema.views does not include translated Hive views.
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java:41]: Make sure it's clear we're talking about Trino's `information_schema`, not the one in HMS

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java [hunk 9]
```diff
@@ -13,5 +13,71 @@
...
+import static io.trino.tempto.query.QueryExecutor.query;
+import static io.trino.tests.TestGroups.HIVE_VIEWS;
+import static io.trino.tests.utils.QueryExecutors.onHive;
+import static io.trino.tests.utils.QueryExecutors.onPresto;
+import static org.assertj.core.api.Assertions.assertThatThrownBy;
+
+@Requires({
+        ImmutableTpchTablesRequirements.ImmutableNationTable.class,
+        ImmutableTpchTablesRequirements.ImmutableOrdersTable.class,
+})
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java:32]: I very much dislike annotation-based requirements, because they make working with tests harder.
Anyway `TestHiveViewsLegacy` already uses this, so please keep it.

import the inner classes

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java [hunk 10]
```diff
@@ -13,5 +13,71 @@
...
+        runQueryWithAssertion(
+                "SELECT table_name FROM information_schema.views WHERE table_schema = 'test_list_failing_views'",
+                getHiveVersionMajor() == 3
+                        ? queryAssert -> queryAssert.containsOnly(row("correct_view"))
+                        : QueryAssert::hasNoRows);
+
+        runQueryWithAssertion("SELECT table_name FROM information_schema.views",
+                getHiveVersionMajor() == 3
+                        ? queryAssert -> queryAssert.contains(row("correct_view"))
+                        : queryAssert -> assertThatThrownBy(() -> queryAssert.contains(row("correct_view"))));
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java:61]: `assertThatThrownBy` should be followed with the actual assertion.

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java [hunk 11]
```diff
@@ -13,5 +13,71 @@
...
+
+        assertThat(query("SELECT table_name FROM information_schema.views WHERE table_schema = 'test_list_failing_views' and table_name = 'correct_view'"))
+                .containsOnly(row("correct_view"));
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java:64]: Why this does not depend on the hive version? please add a comment

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/AbstractTestHiveViews.java [hunk 12]
```diff
@@ -359,14 +359,14 @@ public void testCurrentUser()
         assertThat(connectToPresto("alice@presto").executeQuery(testQuery)).containsOnly(row("alice"));
     }
 
-    protected static void assertViewQuery(String query, Consumer<QueryAssert> assertion)
+    protected static void assertOnHiveAndPresto(String query, Consumer<QueryAssert> assertion)
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/hive/AbstractTestHiveViews.java:362]: Let's use "Trino" here even though the body has onPresto.
Less work later.

**Review by findepi — APPROVED** [review]

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java (hunk 8 above)
Comment (losipiuk) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java:41]: Please move the comment just above assertion queries.

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java (hunk 10 above)
Comment (losipiuk) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java:61]: nit; can we make it 
```
if ( getHiveVersionMajor() == 3) {
// assertThat(...)
}
else {
// different assertThat...
}

**Review by losipiuk — COMMENTED** [review]
Looks good to me.

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java (hunk 10 above)
Comment (phd3) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java]: @losipiuk @findepi 

Removed ternary conditional operator to simplify (and hence also removed the related refactoring commit)

So, previously the PR had: 

```
        runQueryWithAssertion(
                "SELECT table_name FROM information_schema.views WHERE table_schema = 'test_list_failing_views'",
                getHiveVersionMajor() == 3
                        ? queryAssert -> queryAssert.containsOnly(row("correct_view"))
                        : QueryAssert::hasNoRows);

        runQueryWithAssertion(
                "SELECT table_name FROM information_schema.views",
                getHiveVersionMajor() == 3
                        ? queryAssert -> queryAssert.contains(row("correct_view"))
                        : queryAssert -> assertThatThrownBy(() -> queryAssert.contains(row("correct_view"))));
```
 
and now changed it to

```
        String withSchemaFilter = "SELECT table_name FROM information_schema.views WHERE table_schema = 'test_list_failing_views'";
        String withNoFilter = "SELECT table_name FROM information_schema.views";
        if (getHiveVersionMajor() == 3) {
            assertThat(query(withSchemaFilter)).containsOnly(row("correct_view"));
            assertTrue(query(withNoFilter).rows().contains(ImmutableList.of("correct_view")));
        }
        else {
            assertThat(query(withSchemaFilter)).hasNoRows();
            assertFalse(query(withNoFilter).rows().contains(ImmutableList.of("correct_view")));
        }
```

One problem is that `QueryAssert` doesn't have `doesNotContain` method currently, so ended up using `assertTrue` and `assertFalse` for the `withNoFilter` query. LMK if you'd prefer `assertThatThrownBy` (which seems bit hard to read) or any other cleaner way to handle this.

**Review by losipiuk — APPROVED** [review]

File: testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java (hunk 10 above)
Comment (losipiuk) [reply testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java]: Can't you assert on `rows()` using standard collection assertion:

```java
Assertions.assertThat(query(withNoFilter).rows()).doesNotContain(.....)
```
