### PR TITLE
Replace predicate pushdown in the Faker connector with column properties 

### LINKED ISSUE #24147: Faker connector produces incorrect results
The connector seems to be using the WHERE clause to make decisions on which values to produce. This is an abuse of SQL semantics, and it leads to inconsistent and nonsensical results.

For example, given:

```sql
CREATE TABLE t (x bigint)
```

The following query produces 1000 values of random data, as expected:

```sql
SELECT * FROM t
```

However,

```sql
SELECT * FROM t WHERE x = 1
```

on *the same table*, produces 1000 rows with a value of `1`. By SQL semantics, that should not be the case unless the table contains 1000 rows with `x = 1`, which contradicts the first query.

Additionally, 

```sql
SELECT * FROM t WHERE x = 1 OR rand() >= 0
```

produces the same data as if the first query. By SQL semantics, `x = 1` is equivalent to `x =1 OR rand() >= 0`, so both queries should produce the same results.

See related discussion in https://github.com/trinodb/trino/pull/24078

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

Predicate pushdown in the Faker connector violates the SQL semantics,
because when applied to separate columns, correlation between columns is
not preserved, and returned results are not deterministic. The `min`,
`max`, and `allowed_values` column properties should be used instead.

Fixes #24147

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
## Faker
* Replace predicate pushdown with `min`, `max`, and `options` column properties. ({issue}`24147`)
```

### CODE REVIEW

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java [hunk 1]
```diff
@@ -15,21 +15,49 @@
...
+        if (max == null) {
+            return Range.greaterThanOrEqual(type, Literal.parse(min, type));
+        }
+        if (min == null) {
+            return Range.lessThanOrEqual(type, Literal.parse(max, type));
+        }
+        return Range.range(type, Literal.parse(min, type), true, Literal.parse(max, type), true);
+    }
+
+    public List<Object> nativeOptions()
```
Comment (raunaqmorarka) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java:57]: parsedValues

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java [hunk 2]
```diff
@@ -15,21 +15,49 @@
...
 public record FakerColumnHandle(
         int columnIndex,
         String name,
         Type type,
         double nullProbability,
-        String generator)
+        String generator,
+        String min,
+        String max,
+        List<String> options)
```
Comment (raunaqmorarka) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java:34]: Unless you want to directly use these somewhere, it would be better for range and parsedValues to be the member variables

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java [hunk 3]
```diff
@@ -161,7 +167,28 @@ public List<PropertyMetadata<?>> getColumnProperties()
                                 throw new TrinoException(INVALID_COLUMN_PROPERTY, "generator must be a valid Faker expression", e);
                             }
                         },
-                        false));
+                        false),
+                stringProperty(
+                        MIN_PROPERTY,
+                        "Minimum constraint for generated values, inclusive",
```
Comment (raunaqmorarka) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java:173]: Minimum generated value (inclusive)

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java [hunk 4]
```diff
@@ -161,7 +167,28 @@ public List<PropertyMetadata<?>> getColumnProperties()
...
+                        null,
+                        false),
+                stringProperty(
+                        MAX_PROPERTY,
+                        "Maximum constraint for generated values, inclusive",
```
Comment (raunaqmorarka) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java:178]: Maximum generated value (inclusive)

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java [hunk 5]
```diff
@@ -161,7 +167,28 @@ public List<PropertyMetadata<?>> getColumnProperties()
...
+                        null,
+                        false),
+                new PropertyMetadata<>(
+                        OPTIONS_PROPERTY,
+                        "Values to choose from",
```
Comment (raunaqmorarka) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java:183]: List of generated values

File: docs/src/main/sphinx/connector/faker.md [hunk 6]
```diff
@@ -102,6 +102,15 @@ The following table details all supported column properties.
     sentence from the
     [Lorem](https://javadoc.io/doc/net.datafaker/datafaker/latest/net/datafaker/providers/base/Lorem.html)
     provider.
+* - `min`
+  - Minimum constraint for generated values, inclusive. Cannot be set for
+    character-based type columns.
+* - `max`
+  - Maximum constraint for generated values, inclusive. Cannot be set for
+    character-based type columns.
+* - `options`
```
Comment (raunaqmorarka) [inline docs/src/main/sphinx/connector/faker.md:111]: options -> values
"Options" can be misunderstood for some kind of config

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerPageSource.java [hunk 7]
```diff
@@ -257,8 +261,10 @@ private Generator constraintedValueGenerator(FakerColumnHandle handle, Domain do
         };
     }
 
-    private Generator randomValueGenerator(FakerColumnHandle handle, Range range)
+    private Generator randomValueGenerator(FakerColumnHandle handle, Range predicateRange)
     {
+        Range range = predicateRange.intersect(handle.range())
+                .orElseThrow(() -> new TrinoException(INVALID_ROW_FILTER, "Predicates do not overlap with column min and max properties"));
```
Comment (raunaqmorarka) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerPageSource.java]: Why is this an error ? Can't we generate empty page for this case ?

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java [hunk 8]
```diff
@@ -15,21 +15,49 @@
...
 import static java.util.Objects.requireNonNull;
 
 public record FakerColumnHandle(
         int columnIndex,
         String name,
         Type type,
         double nullProbability,
-        String generator)
+        String generator,
+        String min,
```
Comment (losipiuk) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java:32]: Can you use Optionals please

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java [hunk 9]
```diff
@@ -309,13 +309,48 @@ public synchronized FakerOutputTableHandle beginCreateTable(ConnectorSession ses
...
+            catch (IllegalArgumentException e) {
+                throw new TrinoException(INVALID_COLUMN_PROPERTY, "The `min` property must be a valid " + column.getType().getDisplayName() + " literal", e);
+            }
+            String max = (String) column.getProperties().get(ColumnInfo.MAX_PROPERTY);
+            try {
+                Literal.parse(max, column.getType());
+            }
+            catch (IllegalArgumentException e) {
+                throw new TrinoException(INVALID_COLUMN_PROPERTY, "The `max` property must be a valid " + column.getType().getDisplayName() + " literal", e);
+            }
```
Comment (losipiuk) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java:323]: nit: extract helper methods here. Specifically min/max handling is kinda identical. 
Also moving this catch driven logic outside will make caller method more readable

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java [hunk 10]
```diff
@@ -309,13 +309,48 @@ public synchronized FakerOutputTableHandle beginCreateTable(ConnectorSession ses
...
+            if ((min != null || max != null) && isCharacterColumn(column)) {
+                throw new TrinoException(INVALID_COLUMN_PROPERTY, "The `min` and `max` properties cannot be set for CHAR, VARCHAR or VARBINARY columns");
+            }
+            List<String> options = null;
+            if (column.getProperties().containsKey(ColumnInfo.OPTIONS_PROPERTY)) {
+                options = getOptions((List<?>) column.getProperties().get(ColumnInfo.OPTIONS_PROPERTY));
```
Comment (losipiuk) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java:329]: nit: static import OPTIONS_PROPERTY

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java [hunk 11]
```diff
@@ -309,13 +309,48 @@ public synchronized FakerOutputTableHandle beginCreateTable(ConnectorSession ses
...
+            // only parse min, max, and options to validate literals - FakerColumnHandle needs to be serializable,
+            // and some internal Trino types are not (Int128, LongTimestamp, LongTimestampWithTimeZone), so they cannot be stored in the handle as native types
+            String min = (String) column.getProperties().get(ColumnInfo.MIN_PROPERTY);
+            try {
+                Literal.parse(min, column.getType());
+            }
+            catch (IllegalArgumentException e) {
+                throw new TrinoException(INVALID_COLUMN_PROPERTY, "The `min` property must be a valid " + column.getType().getDisplayName() + " literal", e);
+            }
+            String max = (String) column.getProperties().get(ColumnInfo.MAX_PROPERTY);
```
Comment (losipiuk) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java:317]: nit static import MAX_PROPERTY

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java [hunk 12]
```diff
@@ -309,13 +309,48 @@ public synchronized FakerOutputTableHandle beginCreateTable(ConnectorSession ses
             if (generator != null && !isCharacterColumn(column)) {
                 throw new TrinoException(INVALID_COLUMN_PROPERTY, "The `generator` property can only be set for CHAR, VARCHAR or VARBINARY columns");
             }
+            // only parse min, max, and options to validate literals - FakerColumnHandle needs to be serializable,
+            // and some internal Trino types are not (Int128, LongTimestamp, LongTimestampWithTimeZone), so they cannot be stored in the handle as native types
+            String min = (String) column.getProperties().get(ColumnInfo.MIN_PROPERTY);
```
Comment (losipiuk) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java:310]: nit: static import MIN_PROPERTY.

Maybe worth naming `MIN_COLUMN_PROPERTY` (together with others)

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/Literal.java [hunk 13]
```diff
@@ -0,0 +1,247 @@
...
+import static java.lang.System.arraycopy;
+import static java.util.Locale.ENGLISH;
+
+public class Literal
+{
+    private static final CharMatcher WHITESPACE_MATCHER = CharMatcher.whitespace();
+    private static final CharMatcher HEX_DIGIT_MATCHER = CharMatcher.inRange('A', 'F')
+            .or(CharMatcher.inRange('0', '9'))
+            .precomputed();
+    private static final Pattern DECIMAL_PATTERN = Pattern.compile("([+-]?)(\\d(?:_?\\d)*)?(?:\\.(\\d(?:_?\\d)*)?)?");
```
Comment (losipiuk) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/Literal.java:73]: is this chatGPT generated?

Comment (losipiuk) [reply plugin/trino-faker/src/main/java/io/trino/plugin/faker/Literal.java:73]: OH - I see it is stolen from `Decimals`

File: plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java [hunk 14]
```diff
@@ -850,4 +850,491 @@ AND rnd_uuid IN (UUID '1fc74d96-0216-449b-a145-455578a9eaa5', UUID '3ee49ede-002
...
+        @Language("SQL")
+        String tableQuery;
+        @Language("SQL")
+        String testQuery;
+
+        // inclusive ranges that produce only 2 values
+        // high boundary float value obtained using `Math.nextUp((float) 0.0)`
+        tableQuery =
+                """
+                CREATE TABLE faker.default.all_types_range_prop (
```
Comment (losipiuk) [inline plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java:325]: can you change code structure so column definition and expected value are side by side (a list of records?).
And generate SQL from that. 
With this shape it is hard to match what is going on.
Also it may make sense to generate separate table with single column for each column definition you want to test.

**Review by losipiuk — COMMENTED** [review]
some comments. looks nice

**Comment by nineinchnick** [comment]
I'm still working on this.

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java (hunk 2 above)
Comment (nineinchnick) [reply plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java:34]: `FakerColumnHandle` needs to be serializable, if I use `Range` as a member, I get:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.trino.spi.predicate.Range
```

The same applies to options (values), not all types are serializable, like `io.trino.spi.type.LongTimestampWithTimeZone`.

Comment (raunaqmorarka) [reply plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java:34]: Can you try with `io.trino.spi.predicate.Domain#create`, I'm sure we serialize domains for transfer between coordinator and worker

File: docs/src/main/sphinx/connector/faker.md (hunk 6 above)
Comment (nineinchnick) [reply docs/src/main/sphinx/connector/faker.md]: I applied this change, but since `values` is a reserved SQL keyword, it'll always require double quotes.

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerPageSource.java (hunk 7 above)
Comment (nineinchnick) [reply plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerPageSource.java]: This is removed in the following commit, so it doesn't matter how we handle it here.

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java (hunk 8 above)
Comment (nineinchnick) [reply plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java:45]: Why? We handle all cases when the value is null.

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java (hunk 9 above)
Comment (nineinchnick) [reply plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java]: I moved all of this to the `FakerColumnHandle` class, it looks much better, thanks!

File: plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java (hunk 14 above)
Comment (nineinchnick) [reply plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java]: Done! But as a separate commit.

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/Literal.java [hunk 15]
```diff
@@ -0,0 +1,247 @@
...
+    }
+
+    private static Boolean parseBoolean(String value)
+    {
+        value = value.toLowerCase(ENGLISH);
+        checkArgument(value.equals("true") || value.equals("false"));
+        return value.equals("true");
+    }
+
+    private static Object parseDecimal(String value, DecimalType decimalType)
```
[the remark this answers is not in the document]
Comment (nineinchnick) [reply plugin/trino-faker/src/main/java/io/trino/plugin/faker/Literal.java:164]: No, because it infers the data type from the value, and can sometimes return a short decimal when a long decimal is expected. I added a code comment to mention this.

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java (hunk 2 above)
Comment (nineinchnick) [reply plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java]: It worked! I'm not very comfortable working with domains, and I wouldn't have figured this out myself, thanks!

File: docs/src/main/sphinx/connector/faker.md [hunk 16]
```diff
@@ -260,37 +266,47 @@ CREATE TABLE generator.default.customer (LIKE production.public.customer EXCLUDI
...
+
+```sql
+CREATE TABLE generator.default.customer (
+  id UUID NOT NULL,
+  name VARCHAR NOT NULL,
+  address VARCHAR NOT NULL,
+  born_at DATE WITH (min = '1900-01-01', max = '2025-01-01'),
+  age_years INTEGER WITH (min = '0', max = '150')
+);
+```
```
Comment (raunaqmorarka) [inline docs/src/main/sphinx/connector/faker.md:291]: Lets have an example of `values` in the docs as well

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java [hunk 17]
```diff
@@ -14,22 +14,128 @@
...
+        if (max == null) {
+            return Range.greaterThanOrEqual(type, Literal.parse(min, type));
+        }
+        if (min == null) {
+            return Range.lessThanOrEqual(type, Literal.parse(max, type));
+        }
+        return Range.range(type, Literal.parse(min, type), true, Literal.parse(max, type), true);
+    }
+
+    private static List<String> strings(Collection<?> values)
```
Comment (raunaqmorarka) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java:133]:
```
values.stream()
      .map(String.class::cast)
      .collect(toImmutableList())
```

File: plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java [hunk 18]
```diff
@@ -311,543 +221,184 @@ void testSelectFunctions()
...
-                2,
-                -- character types
-                2,
-                2,
-                2,
-                -- ip, uuid
-                2,
-                2)
-                """);
+    private record testDataType(String name, String type, Map<String, String> properties, String queryExpression, String expectedValue)
```
Comment (raunaqmorarka) [inline plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java:387]: testDataType -> TestDataType or DataType

File: docs/src/main/sphinx/connector/faker.md [hunk 19]
```diff
@@ -102,6 +102,13 @@ The following table details all supported column properties.
     sentence from the
```
Comment (raunaqmorarka) [inline docs/src/main/sphinx/connector/faker.md:102]: Update the commit message

File: docs/src/main/sphinx/connector/faker.md (hunk 6 above)
Comment (raunaqmorarka) [reply docs/src/main/sphinx/connector/faker.md]: Let's use `allowedValues` to avoid the extra quotes then

File: docs/src/main/sphinx/connector/faker.md (hunk 16 above)
Comment (nineinchnick) [reply docs/src/main/sphinx/connector/faker.md:292]: Done! I've also noticed there's an outdated limitation at the end, I removed it in a separate commit.

File: docs/src/main/sphinx/connector/faker.md (hunk 6 above)
Comment (raunaqmorarka) [reply docs/src/main/sphinx/connector/faker.md]: ping

Comment (nineinchnick) [reply docs/src/main/sphinx/connector/faker.md]: Or `allowed_values`? Properties are probably case insensitive.

Comment (raunaqmorarka) [reply docs/src/main/sphinx/connector/faker.md]: yes

Comment (nineinchnick) [reply docs/src/main/sphinx/connector/faker.md]: Done!

File: docs/src/main/sphinx/connector/faker.md [hunk 20]
```diff
@@ -102,6 +102,15 @@ The following table details all supported column properties.
...
     [Lorem](https://javadoc.io/doc/net.datafaker/datafaker/latest/net/datafaker/providers/base/Lorem.html)
     provider.
+* - `min`
+  - Minimum generated value (inclusive). Cannot be set for character-based type
+    columns.
+* - `max`
+  - Maximum generated value (inclusive). Cannot be set for character-based type
+    columns.
+* - `allowed_values`
+  - List of allowed generated values. Cannot be set together with the `min`, or
```
Comment (raunaqmorarka) [inline docs/src/main/sphinx/connector/faker.md:112]: `allowed generated` -> `allowed`

File: plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java [hunk 21]
```diff
@@ -161,7 +167,28 @@ public List<PropertyMetadata<?>> getColumnProperties()
...
+                        null,
+                        false),
+                stringProperty(
+                        MAX_PROPERTY,
+                        "Maximum generated value (inclusive)",
+                        null,
+                        false),
+                new PropertyMetadata<>(
+                        ALLOWED_VALUES_PROPERTY,
+                        "List of allowed generated values",
```
Comment (raunaqmorarka) [inline plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java:183]: `allowed generated` -> `allowed`

**Review by raunaqmorarka — APPROVED** [review]

File: docs/src/main/sphinx/connector/faker.md [hunk 22]
```diff
@@ -102,6 +102,15 @@ The following table details all supported column properties.
     sentence from the
     [Lorem](https://javadoc.io/doc/net.datafaker/datafaker/latest/net/datafaker/providers/base/Lorem.html)
     provider.
+* - `min`
+  - Minimum generated value (inclusive). Cannot be set for character-based type
```
Comment (mosabua) [inline docs/src/main/sphinx/connector/faker.md:106]: So does it work for numeric and also date types?

File: docs/src/main/sphinx/connector/faker.md [hunk 23]
```diff
@@ -166,7 +175,7 @@ Faker supports the following non-character types:
 - `UUID`
 
 You can not use generator expressions for non-character-based columns. To limit
-their data range, specify constraints in the `WHERE` clause - see
+their data range, set the `min` and/or `max` column properties - see
```
[the remark this answers is not in the document]
Comment (nineinchnick) [reply docs/src/main/sphinx/connector/faker.md:178]: I'll fix this in #24585, I haven't updated the docs there yet.
