### PR TITLE
Fix deadlock failure when listing objects in SQL Server connector

### LINKED ISSUE #10846: SQL Server metadata listing may fail with "Transaction was deadlocked on lock resources with another process" in case of concurrent table creation/deletion

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #10846

## Release notes

```markdown
## SQL Server
* Fix potential failure when listing tables and columns. ({issue}`10846`)
```

### CODE REVIEW

File: plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java [hunk 1]
```diff
@@ -1238,6 +1239,15 @@ public Connection getConnection(ConnectorSession session, JdbcOutputTableHandle
         return connection;
     }
 
+    @Override
+    public Connection openConnectionForListOperations(ConnectorSession session)
+            throws SQLException
+    {
+        Connection connection = connectionFactory.openConnection(session);
+        connection.setTransactionIsolation(TRANSACTION_READ_UNCOMMITTED);
```
Comment (findinpath) [inline plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java]: What is the downside of using `TRANSACTION_READ_UNCOMMITTED` for table listing?

File: plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java [hunk 2]
```diff
@@ -277,27 +278,55 @@ private List<String> testTableNameTestData()
...
+
+    @RepeatedTest(100)
     @Override
     public void testSelectInformationSchemaTables()
     {
-        // Isolate this test to avoid problem described in https://github.com/trinodb/trino/issues/10846
-        executeExclusively(super::testSelectInformationSchemaTables);
+        super.testSelectInformationSchemaTables();
+        try {
+            super.testUpdateRowConcurrently();
```
Comment (findinpath) [inline plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java]: copy-paste issue or intentional?

**Comment by findinpath** [comment]
> Use TRANSACTION_READ_UNCOMMITTED for listing objects in SQL Server
> This resolve "Transaction was deadlocked on lock resources with another process" when listing objects in SQL Server connector.

It would be worthwhile to explain what is the rationale for going with the TRANSACTION_READ_UNCOMMITTED isolation level.

File: plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java [hunk 3]
```diff
@@ -277,27 +278,55 @@ private List<String> testTableNameTestData()
...
     }
 
-    @Test
+    @RepeatedTest(100)
+    @Override
+    public void testShowTablesLike()
+    {
+        super.testShowTablesLike();
+        try {
+            super.testUpdateRowConcurrently();
```
Comment (findinpath) [inline plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java]: This test creates `test_update_row...` tables which will likely left unaffected the `SHOW TABLES LIKE 'or%'` query from `testShowTablesLike`.

File: plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java (hunk 2 above)
Comment (ebyhr) [reply plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java]: Intentional. The purpose is to test concurrent modification.

File: plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java]: The downside is potential risk of dirty reads. For instance, the connector might see a table that will be rolled back (doesn't really exist).

File: plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java (hunk 3 above)
Comment (ebyhr) [reply plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java]: That is fine because the condition isn't pushed-down to SQL Server. I confirmed the current test can reproduce a deadlock issue.

**Comment by ebyhr** [comment]
CI hit #26567

File: plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java (hunk 1 above)
Comment (findepi) [reply plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java]: I don't think "read uncommitted" is desired.
the sql server's snapshot  isolation was supposed to avoid deadlocks.
Besides, listing operations should be retried on retryable exceptions (as should be all other forms of network communication with external services), and those retries would likely solve the problem at hand

Comment (ebyhr) [reply plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java]: I was missing the existing `retryOnDeadlock` method. Updated.

File: plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java [hunk 4]
```diff
@@ -277,27 +278,55 @@ private List<String> testTableNameTestData()
                 .build();
     }
 
-    @Test
+    @RepeatedTest(100)
```
Comment (findepi) [inline plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java]: I understand this is only for development, and not meant for final merge?

Comment (ebyhr) [reply plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java]: Right, I just dropped the tmp commit.

File: plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java [hunk 5]
```diff
@@ -276,28 +276,4 @@ private List<String> testTableNameTestData()
...
-        executeExclusively(super::testSelectInformationSchemaColumns);
-    }
-
-    @Test
-    @Override
-    public void testBulkColumnListingOptions()
-    {
-        // Isolate this test to avoid problem described in https://github.com/trinodb/trino/issues/10846
-        executeExclusively(super::testBulkColumnListingOptions);
-    }
```
Comment (findepi) [inline plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java:302]: ❤️
