### PR TITLE
Fix event collector

### LINKED ISSUE #5922: Flaky test TestEventListener.testPlanningFailure
https://github.com/prestosql/presto/runs/1386057381

```
2020-11-11T16:45:57.6822217Z [ERROR] Tests run: 2082, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2,162.941 s <<< FAILURE! - in TestSuite
2020-11-11T16:45:57.6823688Z [ERROR] testPlanningFailure(io.prestosql.execution.TestEventListener)  Time elapsed: 0.019 s  <<< FAILURE!
2020-11-11T16:45:57.6825688Z java.lang.IllegalArgumentException: expected one element but was: <io.prestosql.spi.eventlistener.QueryCompletedEvent@7142368e, io.prestosql.spi.eventlistener.QueryCompletedEvent@4b216d17>
2020-11-11T16:45:57.6827721Z 	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:315)
2020-11-11T16:45:57.6829025Z 	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
2020-11-11T16:45:57.6830576Z 	at io.prestosql.execution.TestEventListener.assertFailedQuery(TestEventListener.java:243)
2020-11-11T16:45:57.6832346Z 	at io.prestosql.execution.TestEventListener.assertFailedQuery(TestEventListener.java:235)
2020-11-11T16:45:57.6834519Z 	at io.prestosql.execution.TestEventListener.testPlanningFailure(TestEventListener.java:164)
2020-11-11T16:45:57.6839232Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-11T16:45:57.6846082Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-11T16:45:57.6854238Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-11T16:45:57.6860892Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-11T16:45:57.6869367Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-11-11T16:45:57.6876055Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-11-11T16:45:57.6881417Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-11-11T16:45:57.6886531Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-11-11T16:45:57.6892121Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-11-11T16:45:57.6897339Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-11-11T16:45:57.6904472Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-11T16:45:57.6912367Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-11T16:45:57.6917184Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by dain**
## Description

Fix basic thread safety issues in EventsCollector.

## Related issues, pull requests, and links

* Fixes #5922

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

### CODE REVIEW

File: testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java [hunk 1]
```diff
@@ -80,41 +91,59 @@ public synchronized void addQueryCompleted(QueryCompletedEvent event)
...
-        if (!eventFilters.splitCompletedFilter.test(event)) {
+        if (!eventFilters.getSplitCompletedFilter().test(event)) {
             return;
         }
         splitCompletedEvents.add(event);
         eventsLatch.countDown();
     }
 
-    public List<QueryCreatedEvent> getQueryCreatedEvents()
+    public synchronized List<QueryCreatedEvent> getQueryCreatedEvents()
```
Comment (dain) [inline testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java:101]: This is the actual fix. The writer thread may be different from the reader thread, and without the synchronization, you can get an old view of the list.

File: testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java [hunk 2]
```diff
@@ -57,12 +64,16 @@ public synchronized void reset(int numEvents)
     public void waitForEvents(int timeoutSeconds)
             throws InterruptedException
     {
+        CountDownLatch eventsLatch;
+        synchronized (this) {
+            eventsLatch = this.eventsLatch;
```
Comment (dain) [inline testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java:69]: This could major problem, since the reset could happen on a separate thread, and then you could wait on the old event latch

File: testing/trino-tests/src/test/java/io/trino/execution/TestConnectorEventListener.java [hunk 3]
```diff
@@ -31,7 +32,9 @@
 @Test(singleThreaded = true)
 public class TestConnectorEventListener
 {
-    private final EventsCollector generatedEvents = new EventsCollector();
+    private final EventsCollector generatedEvents = new EventsCollector(EventFilters.builder()
+            .setSplitCompletedFilter(event -> false)
```
Comment (dain) [inline testing/trino-tests/src/test/java/io/trino/execution/TestConnectorEventListener.java:36]: Also this is not testing for split completed, so explicitly ignore them incase we somehow ended up with an extra split, which is very unlikely given this is a VALUES query

File: testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java (hunk 2 above)
Comment (losipiuk) [reply testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java:69]: How would that help? You can still reset `eventsLatch` to new instance just after we get out of this synchronized section, and then you are still waiting on an old one.
It looks to me that what we need to do is to ensure that the old latch is fully released in the `reset` method before we switch it to new one.

Comment (losipiuk) [reply testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java:69]: Or is this just a memory barier to ensure variable visibility?

**Review by losipiuk — APPROVED** [review]

File: testing/trino-tests/src/test/java/io/trino/execution/TestConnectorEventListener.java [hunk 4]
```diff
@@ -31,7 +32,9 @@
 @Test(singleThreaded = true)
 public class TestConnectorEventListener
 {
-    private final EventsCollector generatedEvents = new EventsCollector();
+    private final EventsCollector generatedEvents = new EventsCollector(EventFilters.builder()
```
Comment (phd3) [inline testing/trino-tests/src/test/java/io/trino/execution/TestConnectorEventListener.java:39]: nit: should we do the same in `TestCompletedEventWarnings` for event types not tested?

File: testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java (hunk 2 above)
Comment (phd3) [reply testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java:69]: nit: imo worth adding the explanation as a comment in the code for future readers

**Review by phd3 — COMMENTED** [review]
lgtm.

nit: may be change the last commit msg to `Add more debug information`
