### PR TITLE
Fix incorrect min and max stats when writing NULL in Delta Lake

### LINKED ISSUE #13389: Delta Lake connector writes incorrect column stats when the column contains null
```
trino> SELECT * FROM test_stats;
  a
------
    1
 NULL

trino> SHOW STATS FOR test_stats;
 column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
 a           |      NULL |                  NULL |            0.5 |      NULL | 0         | 1
 NULL        |      NULL |                  NULL |           NULL |       2.0 | NULL      | NULL

(low_value should be 1)
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fix incorrect min and max stats when writing NULL in Delta Lake
Fixes #13389

## Documentation

(x) No documentation is needed.

## Release notes

( ) No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# Delta Lake
* Fix storing incorrect min and max stats when writing `NULL`. ({issue}`13389`)
```

### CODE REVIEW

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableStatistics.java [hunk 1]
```diff
@@ -140,4 +140,16 @@ public void testShowStatsForQueryWithWhereClause()
                         "('val_col', null, null, 0.0, null, 23, 26)," +
                         "(null, null, null, null, 3.0, null, null)");
     }
+
+    @Test
+    public void testShowStatsForQueryWithNll()
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableStatistics.java:145]: `Nll` -> `Null`

**Review by findinpath — APPROVED** [review]

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableStatistics.java [hunk 2]
```diff
@@ -140,4 +140,16 @@ public void testShowStatsForQueryWithWhereClause()
                         "('val_col', null, null, 0.0, null, 23, 26)," +
                         "(null, null, null, null, 3.0, null, null)");
     }
+
+    @Test
+    public void testShowStatsForQueryWithNull()
```
Comment (findepi) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableStatistics.java:145]: testShowStatsForAllNullColumn

**Review by findepi — APPROVED** [review]
