### PR TITLE
Avoid writing NaN and Infinity with json format table

### LINKED ISSUE #20395: Hive connector can write numeric NaN and ±infinity with JSON format, but can't read the value
```
create table test_nan with (format = 'json') as select nan() a;
table test_nan;

Failed to read file at /var/folders/9s/_zwn4r_n2_9bp0krllp1pl3c0000gp/T/TrinoTest16541592175967501555/hive_data/tpch/test_nan/20240117_001008_00024_7aya8_e9ee5153-2b74-4446-a143-49470ee8dd3b.gz
io.trino.spi.TrinoException: Failed to read file at /var/folders/9s/_zwn4r_n2_9bp0krllp1pl3c0000gp/T/TrinoTest16541592175967501555/hive_data/tpch/test_nan/20240117_001008_00024_7aya8_e9ee5153-2b74-4446-a143-49470ee8dd3b.gz
	at io.trino.plugin.hive.line.LinePageSource.getNextPage(LinePageSource.java:75)
	at io.trino.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:166)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:266)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20240117_000919_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_STRING) not numeric, can not use numeric value accessors
 at [Source: (byte[])"{"a":"NaN"}"; line: 1, column: 7]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2477)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:755)
	at com.fasterxml.jackson.core.base.ParserBase._parseNumericValue(ParserBase.java:936)
	at com.fasterxml.jackson.core.base.ParserBase.getDoubleValue(ParserBase.java:830)
	at io.trino.hive.formats.line.json.JsonDeserializer$DoubleDecoder.decodeValue(JsonDeserializer.java:403)
	at io.trino.hive.formats.line.json.JsonDeserializer$Decoder.decode(JsonDeserializer.java:243)
	at io.trino.hive.formats.line.json.JsonDeserializer$RowDecoder.decodeValue(JsonDeserializer.java:718)
	at io.trino.hive.formats.line.json.JsonDeserializer$RowDecoder.decode(JsonDeserializer.java:688)
	at io.trino.hive.formats.line.json.JsonDeserializer.deserialize(JsonDeserializer.java:157)
	at io.trino.plugin.hive.line.LinePageSource.getNextPage(LinePageSource.java:62)
```

```
create table test_inf with (format = 'json') as select infinity() a;
table test_inf;

Failed to read file at /var/folders/9s/_zwn4r_n2_9bp0krllp1pl3c0000gp/T/TrinoTest16541592175967501555/hive_data/tpch/test_inf/20240117_001337_00026_7aya8_7924f951-0c9a-4914-8512-ef47571a42f0.gz
io.trino.spi.TrinoException: Failed to read file at /var/folders/9s/_zwn4r_n2_9bp0krllp1pl3c0000gp/T/TrinoTest16541592175967501555/hive_data/tpch/test_inf/20240117_001337_00026_7aya8_7924f951-0c9a-4914-8512-ef47571a42f0.gz
	at io.trino.plugin.hive.line.LinePageSource.getNextPage(LinePageSource.java:75)
	at io.trino.plugin.hive.HivePageSource.getNextPage(HivePageSource.java:166)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:266)
	at io.trino.operator.Driver.processInternal(Driver.java:398)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:301)
	at io.trino.operator.Driver.tryWithLock(Driver.java:704)
	at io.trino.operator.Driver.process(Driver.java:293)
	at io.trino.operator.Driver.processForDuration(Driver.java:264)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_testversion____20240117_000919_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_STRING) not numeric, can not use numeric value accessors
 at [Source: (byte[])"{"a":"Infinity"}"; line: 1, column: 7]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2477)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:755)
	at com.fasterxml.jackson.core.base.ParserBase._parseNumericValue(ParserBase.java:936)
	at com.fasterxml.jackson.core.base.ParserBase.getDoubleValue(ParserBase.java:830)
	at io.trino.hive.formats.line.json.JsonDeserializer$DoubleDecoder.decodeValue(JsonDeserializer.java:403)
	at io.trino.hive.formats.line.json.JsonDeserializer$Decoder.decode(JsonDeserializer.java:243)
	at io.trino.hive.formats.line.json.JsonDeserializer$RowDecoder.decodeValue(JsonDeserializer.java:718)
	at io.trino.hive.formats.line.json.JsonDeserializer$RowDecoder.decode(JsonDeserializer.java:688)
	at io.trino.hive.formats.line.json.JsonDeserializer.deserialize(JsonDeserializer.java:157)
	at io.trino.plugin.hive.line.LinePageSource.getNextPage(LinePageSource.java:62)
```

### PR DESCRIPTION
**Pull request by sug-ghosh**
fixes #20395 https://github.com/trinodb/trino/issues/20395

This pr will fix inserting NaN and Infinity into table as Json Format.

Screenshot 2024-12-22 at 7 22 08 PM
Screenshot 2024-12-22 at 7 22 24 PM

In hive, if we insert NaN or Infinity in json format table, it would store that as NULL, which readable from Trino. We can go that path also if we want to create table to be successful.

@ebyhr @hashhar 

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
## Hive
* Fail loudly when writing NaN, Infinity, -Infinity values with the JSON writer. Previously, the write would succeed but the result of the write would fail to be read back in. ({issue}`24558`)
```

### CODE REVIEW

**Review by ebyhr — COMMENTED** [review]
Could you add a test?

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java [hunk 1]
```diff
@@ -123,7 +123,16 @@ else if (REAL.equals(type)) {
             return (generator, block, position) -> generator.writeNumber(REAL.getFloat(block, position));
         }
         else if (DOUBLE.equals(type)) {
-            return (generator, block, position) -> generator.writeNumber(DOUBLE.getDouble(block, position));
+            return (generator, block, position) -> {
```
Comment (ebyhr) [inline lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:126]: What about REAL type?

Comment (sug-ghosh) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:126]: 'NaN' and 'Infinity' getting casted as Double it seems. It goes through double datatype.

Comment (ebyhr) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:126]: I don't think so. Please try `create table test_nan with (format = 'json') as select real 'NaN' a;`.

Comment (sug-ghosh) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:128]: okay

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java [hunk 2]
```diff
@@ -120,10 +122,26 @@ else if (type instanceof DecimalType decimalType) {
             };
         }
         else if (REAL.equals(type)) {
-            return (generator, block, position) -> generator.writeNumber(REAL.getFloat(block, position));
+            return (generator, block, position) -> {
+                float value = REAL.getFloat(block, position);
+                if (!Float.isNaN(value) && !Float.isInfinite(value)) {
+                    generator.writeNumber(value);
+                }
```
Comment (zhaner08) [inline lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:129]: ```Float.isFinite()``` will cover both infinite and NaN, as the comparison of NaN with any Float (MAX_VALUE in this case) will return false

Same apply to ```Double``` type handling below

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java [hunk 3]
```diff
@@ -120,10 +122,26 @@ else if (type instanceof DecimalType decimalType) {
             };
         }
         else if (REAL.equals(type)) {
```
Comment (zhaner08) [inline lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:124]: Similar logic is also in ```createMapKeyFunction(Type type)```

Comment (zhaner08) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:124]: even though they will not break as these, but still worth discussing on how those values supposed to be read back especially considering cases like duplicate map keys of NaN etc., or just leave them as is and that the downstream consumer decide

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java [hunk 4]
```diff
@@ -120,10 +122,26 @@ else if (type instanceof DecimalType decimalType) {
...
-            return (generator, block, position) -> generator.writeNumber(REAL.getFloat(block, position));
+            return (generator, block, position) -> {
+                float value = REAL.getFloat(block, position);
+                if (!Float.isNaN(value) && !Float.isInfinite(value)) {
+                    generator.writeNumber(value);
+                }
+                else {
+                    throw new TrinoException(StandardErrorCode.INVALID_JSON_LITERAL, "Invalid value to Insert Real " + value);
```
Comment (zhaner08) [inline lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:131]: would prefer to add ```:``` to separate the value out more obviously

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java (hunk 3 above)
Comment (pettyjamesm) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:124]: In other cases, we've preferred to emulate the Hive SerDe behavior. What happens in Hive if you serialize maps with `NaN` / `Infinite` / `-Infinite` keys there, @sug-ghosh ?

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java (hunk 4 above)
Comment (sug-ghosh) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:131]: okay

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java (hunk 3 above)
Comment (sug-ghosh) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:124]: @pettyjamesm will check this

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java (hunk 2 above)
Comment (sug-ghosh) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:129]: okay,

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java (hunk 3 above)
Comment (sug-ghosh) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:124]: @pettyjamesm In hive, it basically store it as NULL, 'NaN / Infinite / -Infinite' for all values.

Comment (pettyjamesm) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java:124]: Thanks for looking into that, sounds like we can leave the logic in `createMapKeyFunction` as-is then.

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java [hunk 5]
```diff
@@ -120,10 +122,26 @@ else if (type instanceof DecimalType decimalType) {
...
         }
         else if (REAL.equals(type)) {
-            return (generator, block, position) -> generator.writeNumber(REAL.getFloat(block, position));
+            return (generator, block, position) -> {
+                float value = REAL.getFloat(block, position);
+                if (Float.isFinite(value)) {
+                    generator.writeNumber(value);
+                }
+                else {
+                    throw new TrinoException(StandardErrorCode.INVALID_JSON_LITERAL, "Invalid value to Insert Real: " + value);
```
[the remark this answers is not in the document]
Comment (sug-ghosh) [reply lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java]: done that, can you review once

**Review by pettyjamesm — APPROVED** [review]
Thanks for the PR, @sug-ghosh! Also thanks @zhaner08 for helping with the review.

**Comment by ebyhr** [comment]
@pettyjamesm I'm not sure why this PR was merged without tests. Please send a follow-up PR.

**Comment by pettyjamesm** [comment]
@ebyhr - my bad, opened https://github.com/trinodb/trino/pull/24700 to address that

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveErrorCode.java [hunk 6]
```diff
@@ -68,6 +68,7 @@ public enum HiveErrorCode
     HIVE_VIEW_TRANSLATION_ERROR(41, EXTERNAL),
     HIVE_PARTITION_NOT_FOUND(42, USER_ERROR),
     HIVE_INVALID_TIMESTAMP_COERCION(43, EXTERNAL),
+    HIVE_UNSERIALIZABLE_JSON_VALUE(44, USER_ERROR),
```
Comment (ebyhr) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveErrorCode.java:71]: This is unused. Revert.

Comment (pettyjamesm) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveErrorCode.java:71]: `HiveFormatsErrorCode` has to match existing values in `HiveErrorCode` and must not conflict- so we need this value here even though it isn't statically used directly.
