### PR TITLE
Fix writing bloom filter for string columns in orc

### LINKED ISSUE #11757: Does trino support bloom filter for varchar columns for ORC
I have tried to create and insert the data to Hive ORC table with bloom filter enabled for double and Varchar columns, however column with double data type had Bloom filter not for Varchar.

**Steps to reproduce**:
```
CREATE TABLE hive.orctest.orc_bloom_test (
   transactionidreference double,
   eventtypestream varchar(5),
   dattype date
 )
WITH (
   orc_bloom_filter_columns = ARRAY['transactionidreference','eventtypestream']
);

insert into hive.orctest.orc_bloom_test values(10.2,'ab',DATE '2022-01-02'),(10.2,'ab',DATE '2022-01-02'),(10.2,'abc1',DATE '2022-01-02'),(10.2,'1344',DATE '2022-01-02'),(10.2,'abcde',DATE '2022-01-02');
```

**ORCDump**: We only see column 1 with bloom filter under stripes. 

File Version: 0.12 with FUTURE
Rows: 5
Compression: ZLIB
Compression size: 262144
Type: struct<transactionidreference:double,eventtypestream:varchar(5),dattype:date>

```
Stripe Statistics:
  Stripe 1:
    Column 0: count: 5 hasNull: true
    Column 1: count: 5 hasNull: true min: 10.2 max: 10.2 sum: 0.0
    Column 2: count: 5 hasNull: true min: 1344 max: abcde sum: 17
    Column 3: count: 5 hasNull: true min: 2022-01-02 max: 2022-01-02

File Statistics:
  Column 0: count: 5 hasNull: true
  Column 1: count: 5 hasNull: true min: 10.2 max: 10.2 sum: 0.0
  Column 2: count: 5 hasNull: true min: 1344 max: abcde sum: 17
  Column 3: count: 5 hasNull: true min: 2022-01-02 max: 2022-01-02

Stripes:
  Stripe: offset: 3 data: 47 rows: 5 tail: 65 index: 174
    Stream: column 1 section ROW_INDEX start: 3 length 25
    Stream: column 1 section BLOOM_FILTER_UTF8 start: 28 length 93
    Stream: column 2 section ROW_INDEX start: 121 length 32
    Stream: column 3 section ROW_INDEX start: 153 length 24
    Stream: column 3 section DATA start: 177 length 6
    Stream: column 2 section LENGTH start: 183 length 8
    Stream: column 1 section DATA start: 191 length 14
    Stream: column 2 section DATA start: 205 length 19
    Encoding column 0: DIRECT
    Encoding column 1: DIRECT
    Encoding column 2: DIRECT_V2
    Encoding column 3: DIRECT_V2

File length: 615 bytes
Padding length: 0 bytes
Padding ratio: 0%

User Metadata:
  presto_query_id=20220401_145637_00009_nt75j
  trino.writer.version=370-68-g3904620-dirty
  presto_version=371-e
```

### PR DESCRIPTION
**Pull request by ans76**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?
fix #11757 

## Documentation

( ) No documentation is needed.

## Release notes

( ) No release notes entries required.

### CODE REVIEW

File: lib/trino-orc/src/main/java/io/trino/orc/writer/SliceDictionaryColumnWriter.java [hunk 1]
```diff
@@ -479,6 +479,10 @@ private static List<Integer> createSliceColumnPositionList(
     public List<StreamDataOutput> getBloomFilters(CompressedMetadataWriter metadataWriter)
             throws IOException
     {
+        if (directEncoded) {
```
Comment (sopel39) [inline lib/trino-orc/src/main/java/io/trino/orc/writer/SliceDictionaryColumnWriter.java:482]: Is there a way to test it?

How it was broken? (improve commie message)

Comment (ans76) [reply lib/trino-orc/src/main/java/io/trino/orc/writer/SliceDictionaryColumnWriter.java:482]: https://github.com/trinodb/trino/blob/2df56a057aedf3a59088212214ac84e7ce759f59/lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java#L386-L406

`SliceDictionaryColumnWriter#tryConvertToDirect` will clear rowGroups finally in dictionary compression optimization, index streams use the rowGroups after optimization that result in losing bloom filter streams

**Comment by sopel39** [comment]
@dain could you review this change. I don't have enough context here

**Review by Praveen2112 — APPROVED** [review]
Can we add test to ensure that bloom filter is written for supported datatypes ?

**Comment by Praveen2112** [comment]
@ans76 Can you please apply the comments.

File: lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+
+            for (StripeInformation stripe : footer.getStripes()) {
+                // read the footer
+                Slice tailBuffer = orcDataSource.readFully(stripe.getOffset() + stripe.getIndexLength() + stripe.getDataLength(), toIntExact(stripe.getFooterLength()));
+                try (InputStream inputStream = new OrcInputStream(OrcChunkLoader.create(orcDataSource.getId(), tailBuffer, Optional.empty(), newSimpleAggregatedMemoryContext()))) {
+                    StripeFooter stripeFooter = new OrcMetadataReader().readStripeFooter(footer.getTypes(), inputStream, ZoneId.of("UTC"));
+
+                    int bloomFilters = 0;
+                    for (io.trino.orc.metadata.Stream stream : stripeFooter.getStreams()) {
+                        if (stream.getStreamKind() == io.trino.orc.metadata.Stream.StreamKind.BLOOM_FILTER || stream.getStreamKind() == io.trino.orc.metadata.Stream.StreamKind.BLOOM_FILTER_UTF8) {
```
Comment (Praveen2112) [inline lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java:145]: I think we can check only for `BLOOM_FILTER_UTF8` instead of `BLOOM_FILTER`

File: lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+            orcDataSource = new FileOrcDataSource(tempFile.getFile(), READER_OPTIONS);
+
+            for (StripeInformation stripe : footer.getStripes()) {
+                // read the footer
+                Slice tailBuffer = orcDataSource.readFully(stripe.getOffset() + stripe.getIndexLength() + stripe.getDataLength(), toIntExact(stripe.getFooterLength()));
+                try (InputStream inputStream = new OrcInputStream(OrcChunkLoader.create(orcDataSource.getId(), tailBuffer, Optional.empty(), newSimpleAggregatedMemoryContext()))) {
+                    StripeFooter stripeFooter = new OrcMetadataReader().readStripeFooter(footer.getTypes(), inputStream, ZoneId.of("UTC"));
+
+                    int bloomFilters = 0;
+                    for (io.trino.orc.metadata.Stream stream : stripeFooter.getStreams()) {
```
Comment (Praveen2112) [inline lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java:144]: Can we have something like this 
```
stripeFooter.getStreams().stream()
    .map(Stream::getStreamKind)
    .filter(BLOOM_FILTER_UTF8::equals)
    .count();

```

File: lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java [hunk 4]
```diff
@@ -0,0 +1,157 @@
...
+import static io.trino.spi.type.RealType.REAL;
+import static io.trino.spi.type.SmallintType.SMALLINT;
+import static io.trino.spi.type.VarcharType.VARCHAR;
+import static java.lang.Math.toIntExact;
+import static org.testng.Assert.assertEquals;
+
+public class TestWriteBloomFilter
+{
+    @DataProvider
+    public Object[][] dataTypes()
```
Comment (Praveen2112) [inline lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java:58]: DataProvider can be below the test method

File: lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java [hunk 5]
```diff
@@ -0,0 +1,157 @@
...
+                {DOUBLE},
+                {VARCHAR}
+        };
+    }
+
+    @Test(dataProvider = "dataTypes")
+    public void testCheckBloomFilterWrite(Type type)
+            throws Exception
+    {
+        write(type);
```
Comment (Praveen2112) [inline lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java:75]: Can we inline this method ?

File: lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+    }
+
+    private static void write(Type type)
+            throws Exception
+    {
+        for (OrcWriteValidation.OrcWriteValidationMode validationMode : OrcWriteValidation.OrcWriteValidationMode.values()) {
```
Comment (Praveen2112) [inline lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java:81]: static import for `OrcWriteValidationMode`

Comment (Praveen2112) [reply lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java:81]: Do we need to check it for all validation modes ?

File: lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java [hunk 7]
```diff
@@ -0,0 +1,157 @@
...
+            TempFile tempFile = new TempFile();
+
+            List<String> column = ImmutableList.of("test");
```
Comment (Praveen2112) [inline lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java:84]: Can we specific name for column instead of `test`

**Comment by Praveen2112** [comment]
@alexjo2144 and @raunaqmorarka Can you PTAL ?

File: lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java [hunk 8]
```diff
@@ -0,0 +1,157 @@
...
+import static io.trino.spi.type.DateType.DATE;
+import static io.trino.spi.type.DoubleType.DOUBLE;
+import static io.trino.spi.type.IntegerType.INTEGER;
+import static io.trino.spi.type.RealType.REAL;
+import static io.trino.spi.type.SmallintType.SMALLINT;
+import static io.trino.spi.type.VarcharType.VARCHAR;
+import static java.lang.Math.toIntExact;
+import static org.testng.Assert.assertEquals;
+
+public class TestWriteBloomFilter
```
Comment (raunaqmorarka) [inline lib/trino-orc/src/test/java/io/trino/orc/TestWriteBloomFilter.java:55]: The triggering conditions for the bug seems to be dictionary becoming too large and the writer falling back to non-dictionary encoding. But I don't see any tweaks to orc writer config (like reducing hive.orc.writer.dictionary-max-memory) which would guarantee that the conditions of the bug are reproduced.
It seems to me that it would be simpler to just test this in TestSliceDictionaryColumnWriter for CHAR, VARCHAR and STRING types and just call `tryConvertToDirect` and `getBloomFilters` directly in the unit test.

**Review by raunaqmorarka — COMMENTED** [review]
Please update commit title to
`Fix writing bloom filter for string columns in orc`
Commit message
```
Ensures that bloom filters are written when the writer falls back to 
direct encoding due to dictionary becoming too large.
```

Also, please squash your commits.

**Comment by Praveen2112** [comment]
Merged !! Thanks for fixing this
