### PR TITLE
Fix predicate failure for negative offset value on _timestamp column

### LINKED ISSUE #13167: Fix predicate failure for negative offset value on _timestamp column
When I use trino(389 version) kafka connector, I find some problems.
For example:
```sql
SELECT _timestamp FROM  kafka_table WHERE _timestamp < timestamp '2022-07-07 07:14:43.437'
```

```
Stack Trace: 
       'io.trino.spi.TrinoException: Cannot list splits for table '    '  reading topic  '    '
	at io.trino.plugin.kafka.KafkaSplitManager.getSplits(KafkaSplitManager.java:110)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:51)
	at io.trino.split.SplitManager.getSplits(SplitManager.java:58)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitScanAndFilter(SplitSourceFactory.java:177)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitFilter(SplitSourceFactory.java:246)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitFilter(SplitSourceFactory.java:125)
	at io.trino.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitLimit(SplitSourceFactory.java:353)
	at io.trino.sql.planner.SplitSourceFactory$Visitor.visitLimit(SplitSourceFactory.java:125)
	at io.trino.sql.planner.plan.LimitNode.accept(LimitNode.java:124)
	at io.trino.sql.planner.SplitSourceFactory.createSplitSources(SplitSourceFactory.java:105)
	at io.trino.execution.scheduler.SqlQueryScheduler$PipelinedDistributedStagesScheduler.createStageScheduler(SqlQueryScheduler.java:1364)
	at io.trino.execution.scheduler.SqlQueryScheduler$PipelinedDistributedStagesScheduler.create(SqlQueryScheduler.java:1244)
	at io.trino.execution.scheduler.SqlQueryScheduler.createDistributedStagesScheduler(SqlQueryScheduler.java:371)
	at io.trino.execution.scheduler.SqlQueryScheduler.start(SqlQueryScheduler.java:332)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:425)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:243)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_388_21_g844f91b_dirty____20220713_142511_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
``` 
      
I guess the problem is that when we use timestamp push down, the range may be (-1, timestamp).
And kafkaConsumer.offsetsForTimes cannot be negative.
So I think when we meet '-1' , we do not push down timestamp.

### PR DESCRIPTION
**Pull request by harris233**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?
A fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
Kafka connector

> How would you describe this change to a non-technical end user or system administrator?
Fix predicate failure for negative offset value on _timestamp column

## Related issues, pull requests, and links

Fixes #13167

## Documentation

(x) No documentation is needed.

## Release notes

(x) Release notes entries required with the following suggested text:

Issue:[#13167](https://github.com/trinodb/trino/issues/13167)

### CODE REVIEW

**Review by ebyhr — COMMENTED** [review]
Thanks for you contribution! Please submit CLA if you haven't sent it https://github.com/trinodb/cla.

Could you add a test to `TestKafkaIntegrationPushDown`?

File: plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java [hunk 1]
```diff
@@ -129,11 +129,15 @@ public KafkaFilteringResult getKafkaFilterResult(
             if (offsetTimestampRanged.isPresent()) {
                 try (KafkaConsumer<byte[], byte[]> kafkaConsumer = consumerFactory.create(session)) {
                     Optional<Range> finalOffsetTimestampRanged = offsetTimestampRanged;
-                    partitionBeginOffsets = overridePartitionBeginOffsets(partitionBeginOffsets,
-                            partition -> findOffsetsForTimestampGreaterOrEqual(kafkaConsumer, partition, finalOffsetTimestampRanged.get().getBegin()));
+                    if (offsetTimestampRanged.get().getBegin() >= 0) {
```
Comment (Praveen2112) [inline plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java:132]: Can we add some tests to check if it works as expected ?

Comment (harris233) [reply plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java:132]: OK, I added some test cases in TestKafkaIntegrationPushDown.

**Comment by harris233** [comment]
> Thanks for you contribution! Please submit CLA if you haven't sent it https://github.com/trinodb/cla.
> 
> Could you please add a test to `TestKafkaIntegrationPushDown`? Also, I would recommend improving the commit title - we can't understand what's the issue from "small bug".
OK, I sent cla to [cla@trino.io](mailto:cla@trino.io) just now. I have added some test cases and updated the commit title.

**Comment by harris233** [comment]
Hello, I have signed CLA and got it.Please review again@[ebyhr](https://github.com/ebyhr)

File: plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java (hunk 1 above)
Comment (ebyhr) [inline plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java:132]: It would better to extract a constant for 0. e.g. `MIN_ALLOWED_OFFSET`

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java [hunk 2]
```diff
@@ -169,6 +169,57 @@ public void testTimestampLogAppendModePushDown()
         });
     }
 
+    @Test
+    public void testTimestampCreateTimeModeOpenRangePushDown()
```
Comment (ebyhr) [inline plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java:173]: Please add missing operators `=`, `>`, `<=` and `BETWEEN`. The above change affects them.

**Review by ebyhr — COMMENTED** [review]
Could you fix the commit title likes below sentence?  
```
Fix predicate failure for negative offset value on _timestamp column
```

**Comment by harris233** [comment]
> Could you fix the commit title likes below sentence?
> 
> ```
> Fix predicate failure for negative offset value on _timestamp column
> ```

OK, I changed to `Fix predicate failure for negative offset value on _timestamp column`

File: plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java (hunk 1 above)
Comment (harris233) [reply plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java]: OK, I used `INVALID_KAFKA_RANGE_INDEX`

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java (hunk 2 above)
Comment (harris233) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java]: OK, I added these cases in test.

File: plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java [hunk 3]
```diff
@@ -129,11 +129,15 @@ public KafkaFilteringResult getKafkaFilterResult(
             if (offsetTimestampRanged.isPresent()) {
                 try (KafkaConsumer<byte[], byte[]> kafkaConsumer = consumerFactory.create(session)) {
                     Optional<Range> finalOffsetTimestampRanged = offsetTimestampRanged;
-                    partitionBeginOffsets = overridePartitionBeginOffsets(partitionBeginOffsets,
-                            partition -> findOffsetsForTimestampGreaterOrEqual(kafkaConsumer, partition, finalOffsetTimestampRanged.get().getBegin()));
+                    if (offsetTimestampRanged.get().getBegin() > INVALID_KAFKA_RANGE_INDEX) {
```
Comment (ebyhr) [inline plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java:132]: It would be better to leave comment why we ignore instead of an exception.

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java [hunk 4]
```diff
@@ -115,26 +114,9 @@ private void assertProcessedInputPossitions(String sql, long expectedProcessedIn
         });
     }
 
-    @Test
-    public void testTimestampCreateTimeModePushDown()
-            throws Exception
+    private void assertProcessedInputPossitionsByUsingTimestampUpperPushDown(String sql, long expectedProcessedInputPositions)
```
[the remark this answers is not in the document]
Comment (harris233) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java]: OK. I added a session argument in assertProcessedInputPositions.

File: plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java (hunk 3 above)
Comment (harris233) [reply plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java:133]: OK, I added the reason why we need.

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java [hunk 5]
```diff
@@ -101,70 +100,60 @@ public void testPartitionPushDown()
...
-    }
-
-    private void assertProcessedInputPossitions(String sql, long expectedProcessedInputPositions)
-    {
-        DistributedQueryRunner queryRunner = getDistributedQueryRunner();
-        assertEventually(() -> {
-            MaterializedResultWithQueryId queryResult = queryRunner.executeWithQueryId(getSession(), sql);
-            assertEquals(getQueryInfo(queryRunner, queryResult).getQueryStats().getProcessedInputPositions(), expectedProcessedInputPositions);
-        });
+        Session session = getSession();
```
Comment (ebyhr) [inline plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java:103]: We don't need to pass the default session by adding another `assertProcessedInputPositions`. See other comment.

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java [hunk 6]
```diff
@@ -101,70 +100,60 @@ public void testPartitionPushDown()
...
+        assertProcessedInputPossitions(format("SELECT count(*) FROM default.%s WHERE _partition_offset between 2 and 10", topicNameOffset), 18, session);
+        assertProcessedInputPossitions(format("SELECT count(*) FROM default.%s WHERE _partition_offset > 2 and _partition_offset < 10", topicNameOffset), 14, session);
+        assertProcessedInputPossitions(format("SELECT count(*) FROM default.%s WHERE _partition_offset = 3", topicNameOffset), 2, session);
     }
 
     @Test
     public void testTimestampCreateTimeModePushDown()
             throws Exception
     {
+        Session session = getSession();
```
Comment (ebyhr) [inline plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java:113]: ditto.

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java [hunk 7]
```diff
@@ -101,70 +100,60 @@ public void testPartitionPushDown()
...
-            // timestamp_upper_bound_force_push_down_enabled set as true.
-            Session sessionWithUpperBoundPushDownEnabled = Session.builder(getSession())
-                    .setSystemProperty("kafka.timestamp_upper_bound_force_push_down_enabled", "true")
-                    .build();
-
-            MaterializedResultWithQueryId queryResult = queryRunner.executeWithQueryId(sessionWithUpperBoundPushDownEnabled, sql);
-            assertThat(getQueryInfo(queryRunner, queryResult).getQueryStats().getProcessedInputPositions())
-                    .isEqualTo(2);
-        });
+        session = Session.builder(getSession())
```
Comment (ebyhr) [inline plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java:124]: Let's rename to `sessionWithUpperBoundPushDownEnabled`

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java [hunk 8]
```diff
@@ -101,70 +100,60 @@ public void testPartitionPushDown()
...
+        assertProcessedInputPossitions(format("SELECT count(*) FROM default.%s WHERE _timestamp > timestamp '%s'", topicNameLogAppend, recordMessage.getStartTime()), 997, session);
+        assertProcessedInputPossitions(format("SELECT count(*) FROM default.%s WHERE _timestamp >= timestamp '%s'", topicNameLogAppend, recordMessage.getStartTime()), 998, session);
+        assertProcessedInputPossitions(format("SELECT count(*) FROM default.%s WHERE _timestamp between timestamp '%s' and timestamp '%s'", topicNameLogAppend, recordMessage.getStartTime(), recordMessage.getEndTime()), 2, session);
+        assertProcessedInputPossitions(format("SELECT count(*) FROM default.%s WHERE _timestamp >= timestamp '%s' and _timestamp < timestamp '%s'", topicNameLogAppend, recordMessage.getStartTime(), recordMessage.getEndTime()), 2, session);
+        assertProcessedInputPossitions(format("SELECT count(*) FROM default.%s WHERE _timestamp = timestamp '%s'", topicNameLogAppend, recordMessage.getStartTime()), 0, session);
+    }
 
+    private void assertProcessedInputPossitions(String sql, long expectedProcessedInputPositions, Session session)
```
Comment (ebyhr) [inline plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java:151]: Let's add a preparatory commit to fix typo. `assertProcessedInputPositions`

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java [hunk 9]
```diff
@@ -101,70 +100,60 @@ public void testPartitionPushDown()
...
+    {
+        DistributedQueryRunner queryRunner = getDistributedQueryRunner();
         assertEventually(() -> {
-            MaterializedResultWithQueryId queryResult = queryRunner.executeWithQueryId(getSession(), sql);
-            assertThat(getQueryInfo(queryRunner, queryResult).getQueryStats().getProcessedInputPositions())
-                    .isEqualTo(2);
+            MaterializedResultWithQueryId queryResult = queryRunner.executeWithQueryId(session, sql);
+            assertEquals(getQueryInfo(queryRunner, queryResult).getQueryStats().getProcessedInputPositions(), expectedProcessedInputPositions);
```
Comment (ebyhr) [inline plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java:156]: Let's add another `assertProcessedInputPositions` so that we can avoid passing the default session. 

```java
    private void assertProcessedInputPositions(String sql, long expectedProcessedInputPositions)
    {
        assertProcessedInputPositions(sql, expectedProcessedInputPositions, getSession());
    }

    private void assertProcessedInputPositions(String sql, long expectedProcessedInputPositions, Session session)
    {
        DistributedQueryRunner queryRunner = getDistributedQueryRunner();
        assertEventually(() -> {
            MaterializedResultWithQueryId queryResult = queryRunner.executeWithQueryId(session, sql);
            assertEquals(getQueryInfo(queryRunner, queryResult).getQueryStats().getProcessedInputPositions(), expectedProcessedInputPositions);
        });
    }
```

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
@harris233 Please rebase instead of merge to follow upstream.

**Comment by harris233** [comment]
> @harris233 Please rebase instead of merge to follow upstream.

OK, I rebased it.

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java (hunk 9 above)
Comment (harris233) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java:158]: OK, I added it.

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java (hunk 8 above)
Comment (harris233) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java]: I changed to assertProcessedInputPositions

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java (hunk 7 above)
Comment (harris233) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java]: I used sessionWithUpperBoundPushDownEnabled instead of session

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java (hunk 8 above)
Comment (ebyhr) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java]: > Let's add a preparatory commit to fix typo.

This commend isn't addressed.

Comment (harris233) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java]: I added another commit to fix it.

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java (hunk 5 above)
Comment (harris233) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java]: OK

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java (hunk 6 above)
Comment (harris233) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java]: OK

**Comment by ebyhr** [comment]
Merged, thanks!
