### PR TITLE
Fix BigQuery tests for column names with special characters

### LINKED ISSUE #16603: TestBigQueryAvroConnectorTest, TestBigQueryArrowConnectorTest  `testColumnName` & `testCommentColumnName` are failing
Probably, BigQuery changed their Avro behavior today. 

https://github.com/trinodb/trino/actions/runs/4444615412/jobs/7803295648
```
Error:  Failures: 
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4709->AbstractTestQueryFramework.assertQuery:340 Execution of 'actual' query failed: SELECT * FROM tcn_aleadingspacejx716wcghv
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4709->AbstractTestQueryFramework.assertQuery:340 Execution of 'actual' query failed: SELECT * FROM tcn_0startwithdigiteiyeoizydr
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4709->AbstractTestQueryFramework.assertQuery:340 Execution of 'actual' query failed: SELECT * FROM tcn_aspacevh5gb1gjqi
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4696->AbstractTestQueryFramework.assertUpdate:396->AbstractTestQueryFramework.assertUpdate:401 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4696->AbstractTestQueryFramework.assertUpdate:396->AbstractTestQueryFramework.assertUpdate:401 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4709->AbstractTestQueryFramework.assertQuery:340 Execution of 'actual' query failed: SELECT * FROM tcn_ahyphenminusn6hvtqcis8
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4696->AbstractTestQueryFramework.assertUpdate:396->AbstractTestQueryFramework.assertUpdate:401 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4696->AbstractTestQueryFramework.assertUpdate:396->AbstractTestQueryFramework.assertUpdate:401 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4709->AbstractTestQueryFramework.assertQuery:340 Execution of 'actual' query failed: SELECT * FROM tcn_acolonzryo5ahw7h
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4696->AbstractTestQueryFramework.assertUpdate:396->AbstractTestQueryFramework.assertUpdate:401 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4696->AbstractTestQueryFramework.assertUpdate:396->AbstractTestQueryFramework.assertUpdate:401 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4696->AbstractTestQueryFramework.assertUpdate:396->AbstractTestQueryFramework.assertUpdate:401 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4709->AbstractTestQueryFramework.assertQuery:340 Execution of 'actual' query failed: SELECT * FROM tcn_anapostrophez12qyivvxs
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4696->AbstractTestQueryFramework.assertUpdate:396->AbstractTestQueryFramework.assertUpdate:401 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testColumnName:4686->BaseConnectorTest.testColumnName:4709->AbstractTestQueryFramework.assertQuery:340 Execution of 'actual' query failed: SELECT * FROM tcn_atrailingspacec8evpfgvyb
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testCommentColumnName:3604->BaseConnectorTest.testCommentColumnName:3611 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testCommentColumnName:3604->BaseConnectorTest.testCommentColumnName:3611 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testCommentColumnName:3604->BaseConnectorTest.testCommentColumnName:3611 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testCommentColumnName:3604->BaseConnectorTest.testCommentColumnName:3611 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testCommentColumnName:3604->BaseConnectorTest.testCommentColumnName:3611 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testCommentColumnName:3604->BaseConnectorTest.testCommentColumnName:3611 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testCommentColumnName:3604->BaseConnectorTest.testCommentColumnName:3611 » QueryFailed
Error:    TestBigQueryAvroConnectorTest>BaseConnectorTest.testCommentColumnName:3604->BaseConnectorTest.testCommentColumnName:3611 » QueryFailed
```

### PR DESCRIPTION
**Pull request by ssheikin**
Some column names started to fail because of BigQuery internal change
~ between
18:00 16 of March 2023 GMT and
00:00 17 of March 2023 GMT,
first noticed when 90d6f0737a1f8dd4fbb8b85c2d95b20093d1b4ba merged to
master.

## Description

Fixes #16603

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

File: plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java [hunk 1]
```diff
@@ -659,6 +689,42 @@ public void testMissingWildcardTable()
...
+    {
+        Throwable throwable = null;
+        try {
+            super.testColumnName(columnName);
+            fail("Test above should throw");
+        }
+        catch (Exception e) {
+            throwable = e;
+        }
+        catch (Error e) {
```
Comment (kokosing) [inline plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java:703]: error?

File: plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java [hunk 2]
```diff
@@ -659,6 +689,42 @@ public void testMissingWildcardTable()
                 .hasMessageEndingWith("does not match any table.");
     }
 
+    @Test(dataProvider = "testColumnNameFailsDataProvider")
+    public void testColumnNameFails(String columnName)
+    {
+        Throwable throwable = null;
+        try {
+            super.testColumnName(columnName);
```
Comment (kokosing) [inline plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java:697]: assertThatThrownBy?

File: plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java [hunk 3]
```diff
@@ -13,6 +13,7 @@
  */
```
Comment (kokosing) [inline plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java:13]: I am a bit lost. Are we testing bigquery here? @ebyhr can you please let me know what is the point of test based on incorrect column names?

As I understand we should only update `filterColumnNameTestData`

File: plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java [hunk 4]
```diff
@@ -659,6 +689,42 @@ public void testMissingWildcardTable()
...
+    @DataProvider
+    public Object[][] testColumnNameFailsDataProvider()
+    {
+        return NOT_ALLOWED_ANYMORE_COLUMN_NAMES.stream().collect(toDataProvider());
+    }
+
+    @Override
+    protected Optional<String> filterColumnNameTestData(String columnName)
+    {
+        if (NOT_ALLOWED_ANYMORE_COLUMN_NAMES.contains(columnName)) {
```
Comment (ebyhr) [inline plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java:722]: Creating and inserting into tables with these columns works and selecting the table isn't problem, right? This change hides the fact and we can't understand what happened after the operations. It would be better to deny such columns in all operations, or verify the result with different way, e.g. use query based API instead of storage API.

File: plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java (hunk 3 above)
Comment (ebyhr) [reply plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java:13]: Testing unsupported column names helps us find SQL injection vector.

**Comment by ssheikin** [comment]
@ebyhr hope I've addressed your comments. 
I think this PR is good enough to fix failing tests. However the additional work required to be able to SELECT from such columns again.
Please review.

File: plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java [hunk 5]
```diff
@@ -14,11 +14,32 @@
...
+
+import static io.trino.testing.DataProviders.toDataProvider;
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.assertj.core.api.Assertions.assertThatThrownBy;
 
 public class TestBigQueryAvroConnectorTest
         extends BaseBigQueryConnectorTest
 {
+    // these column names started to fail because of BigQuery internal change ~ between 18:00 16 of March 2023 GMT and 00:00 17 of March 2023 GMT
+    // it's still possible to CREATE TABLE with such column names, and even INSERT some data, but it is not possible to SELECT from it.
```
Comment (ebyhr) [inline plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java:33]: > but it is not possible to SELECT from it.

This sentence is misleading. We can select the table using query based API. https://github.com/trinodb/trino/pull/16613#discussion_r1141524457

**Review by ebyhr — APPROVED** [review]

File: plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java [hunk 6]
```diff
@@ -28,4 +49,39 @@ protected QueryRunner createQueryRunner()
...
+    {
+        if (UNSUPPORTED_COLUMN_NAMES.contains(columnName)) {
+            return Optional.empty();
+        }
+        return Optional.of(columnName);
+    }
+
+    // these column names started to fail because of BigQuery internal change ~ between 18:00 16 of March 2023 GMT and 00:00 17 of March 2023 GMT
+    // it's still possible to CREATE TABLE with such column names, and even INSERT some data, but it is not possible to SELECT from it.
+    // TODO is it possible to improve trino to be able to SELECT from such columns again?
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java]: Let's handle in follow-up https://github.com/trinodb/trino/issues/16664. We would like to fix CI failure first.

**Comment by ssheikin** [comment]
@ebyhr Thank you for improving and merging
