### PR TITLE
Don't drop destination table when non-transactional insert fails

### LINKED ISSUE #12225: PostgreSQL connector drops destination table upon error during non-transactional insert
```
psql> create table x(y int primary key);

trino-cli> show tables;
Table   
----------
x        
(1 row)

trino-cli> set session postgres.non_transactional_insert=true
SET SESSION

trino-cli> insert into x values(1);
INSERT: 1 row

Query 20220503_183326_00017_kyvma, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.37 [0 rows, 0B] [0 rows/s, 0B/s]

trino-cli> insert into x values(1);

Query 20220503_183328_00018_kyvma, FAILED, 1 node
Splits: 19 total, 9 done (47.37%)
0.22 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220503_183328_00018_kyvma failed: Failed to insert data: Batch entry 0 INSERTINTO "x" ("y") VALUES (1) was aborted: ERROR: duplicate key value violates unique constraint "x_pkey"
Detail: Key (y)=(1) already exists.  Call getNextException to see other errors in the batch.

trino-cli> show tables;
Table
-------
(0 rows)

Query 20220503_183354_00020_kyvma, FINISHED, 1 node
Splits: 11 total, 11 done (100.00%)
0.26 [0 rows, 0B] [0 rows/s, 0B/s]
```

This is certainly... Unexpected.

Since the PostgreSQL connector does not override the XXXinsert methods from BaseJdbcClient this is probably a problem with all BaseJdbcDerived connectors.

### PR DESCRIPTION
**Pull request by lhofhansl**
## Description
See #12225

> Is this change a fix, improvement, new feature, refactoring, or other?

Fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Most JDBC connectors will have this issue. Verified with Postgres.

> How would you describe this change to a non-technical end user or system administrator?

Trino will happily drop your entire table if it encounters an error during a non-transactional insert.
This is a pretty SERIOUS issue.

## Related issues, pull requests, and links

Fixes #12225

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by lhofhansl** [comment]
Simple fix. I'll think on a quick test too (very limited time, though.)

**Comment by lhofhansl** [comment]
Haven't run tests in a while. Always fails with `docker-machine executable was not found on PATH ...`

**Comment by lhofhansl** [comment]
Something like this. But I cannot run the tests locally ATM.

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java [hunk 1]
```diff
@@ -699,7 +700,9 @@ public ConnectorInsertTableHandle beginInsert(ConnectorSession session, Connecto
                 .map(JdbcColumnHandle.class::cast)
                 .collect(toImmutableList());
         JdbcOutputTableHandle handle = jdbcClient.beginInsertTable(session, (JdbcTableHandle) tableHandle, columnHandles);
-        setRollback(() -> jdbcClient.rollbackCreateTable(session, handle));
+        if (!isNonTransactionalInsert(session)) {
+            setRollback(() -> jdbcClient.rollbackCreateTable(session, handle));
+        }
```
Comment (findepi) [inline plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java:705]: This should be a logic of `jdbcClient.rollbackCreateTable`
since `isNonTransactionalInsert` is handled by `jdbcClient.beginInsertTable`

(eg imagine a connector which overrides `jdbcClient.beginInsertTable` and ignores `isNonTransactionalInsert` session property; it would have no way to behave correctly)

Comment (lhofhansl) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java:705]: What if someone calls jdbcClient.rollbackCreateTable in some other context? In that case we'd want to remove that table regardless of whether inserts are transactional or not.

Comment (lhofhansl) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java:705]: Seem it's wrong either way:
DefaultJdbcMetadata.beginCreateTable also sets up jdbcClient.rollbackCreateTable as rollback action. In that case we always want the rollback to happen.
For DefaultJdbcMetadata.beginInsert we want the rollback handled conditionally.

Comment (findepi) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java:705]: i think `JdbcOutputTableHandle` needs to track information whether this is a temp table or not.

Comment (lhofhansl) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java:705]: Actually... Even that would not work (nicely). It would need to be a specific flag for isNonTransactionalInsert.
All other table creation (that we want to have removed) have to be marked as temporary. Now you have remember explicitly not do that, seems more frail to me. IMHO this has to be connected to an action, not the OutputTable.

I think my initial fix is still the safest. BaseJdbcClient.beginInsertTable is not overriden (except for disabling via throwing an Exception). And when one overrides that, one would have to aware of the implications. One could put a comment on that method.

As is, this will happily drop your TB size table if you fail to insert into it on non-transactional mode. :(

IMHO, the damage is done in the original implementation that separated table creation from the responsibility to clean the table up into two different classes. It's not immediately clear how to undo that.

Comment (findepi) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java:705]: > I think my initial fix is still the safest.

it spreads responsibility between the two classes: DefaultJdbcMetadata (which generally should not be overridden)  and `JdbcClient` which is the extension point for all the jdbc-based connectors

> All other table creation (that we want to have removed) have to be marked as temporary. Now you have remember explicitly not do that, seems more frail to me

I thought about adding new parameter to `JdbcOutputTableHandle`. You cannot forget about it, because it's a required parameter.

However, we don't need a new parameter, we should just compare `JdbcOutputTableHandle#tableName` and `JdbcOutputTableHandle#temporaryTableName`. Or, better, make `temporaryTableName` Optional.

Comment (lhofhansl) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java:705]: > it spreads responsibility between the two classes

That already happened because BaseJdbcClient creates the tables, but DefaultJdbcMetadata is responsible for the cleanup.

> I thought about adding new parameter to JdbcOutputTableHandle. You cannot forget about it, because it's a required parameter.

I started with that, easy enough to do. But I ran into the issue I mentioned above.

> compare JdbcOutputTableHandle#tableName and JdbcOutputTableHandle#temporaryTableName

So from looking `BaseJdbcClient.beginInsertTable` you are suggesting that `DefaultJdbcMetadata.beginInsert` to set up the rollback only handler when tableName and temporaryTableName are identical? (real tables seem to have these two set differently)
Or that the rollback handler not do anything when the tableName and temporaryTableName are identical? (that would seem weird)
Won't any derived `beginInsertTable` now equally have to be aware of that or have the table removed?

Happy to do that as long as we can fix the problem.

Comment (lhofhansl) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java:704]: How about this?

**Comment by lhofhansl** [comment]
We should get this into 380. This is a serious bug that will delete data unexpectedly.

@findepi @martint

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java [hunk 2]
```diff
@@ -700,7 +699,7 @@ public ConnectorInsertTableHandle beginInsert(ConnectorSession session, Connecto
                 .map(JdbcColumnHandle.class::cast)
                 .collect(toImmutableList());
         JdbcOutputTableHandle handle = jdbcClient.beginInsertTable(session, (JdbcTableHandle) tableHandle, columnHandles);
-        if (!isNonTransactionalInsert(session)) {
+        if (!handle.getTableName().equals(handle.getTemporaryTableName())) {
```
Comment (findepi) [inline plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java:702]: Thanks for improving the logic, but this doesn't change the fact the logic belongs to jdbcClient.rollbackCreateTable, as it is coupled with jdbcClient.beginInsertTable.

As suggested in https://github.com/trinodb/trino/pull/12229/commits/a1f6ada23ada49944c665f1307af1ff7aa0a48f6#r866674664, let's make temporaryTableName `Optional`.

Comment (lhofhansl) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java]: I pushed a new update. (Will rename squash/rename the commits later).

Not sure I like.
Perhaps I could abstract the repeated handle.getTemporaryTableName().orElse(handle.getTableName()) into JdbcOutputTableHanlde itself, and add a separate method to check whether a temporary table has been provided.

**Comment by findepi** [comment]
(changed commit title and applied small style changes)

**Review by findepi — APPROVED** [review]

**Review by hashhar — APPROVED** [review]

**Comment by lhofhansl** [comment]
As usually, thank for the thorough review.
