### PR TITLE
Remove Pinot Column Name Property

### LINKED ISSUE #14071: Pinot connector throws `No PropertyMetadata for property: pinotColumnName` in `SHOW CREATE TABLE`
```
SHOW CREATE TABLE region;

io.trino.spi.TrinoException: No PropertyMetadata for property: pinotColumnName
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.buildProperties(ShowQueriesRewrite.java:745)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.lambda$visitShowCreate$10(ShowQueriesRewrite.java:671)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:679)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowCreate(ShowQueriesRewrite.java:216)
	at io.trino.sql.tree.ShowCreate.accept(ShowCreate.java:70)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:213)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:53)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:76)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:254)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:192)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:792)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:135)
	at io.trino.$gen.Trino_testversion____20220908_234608_71.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

cc: @elonazoulay @xiangfu0

### PR DESCRIPTION
**Pull request by elonazoulay**
## Description

Add the column name property to Pinot column properties.
Fixes #14071 

## Non-technical explanation

The pinot column name property was missing so `SHOW CREATE TABLE` queries would fail.

## Release notes

( ) This is not user-visible and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Pinot
* Fix failure when executing `SHOW CREATE TABLE` statement. ({issue}`14071`)
```

### CODE REVIEW

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnector.java [hunk 1]
```diff
@@ -48,14 +49,17 @@ public PinotConnector(
...
+            PinotTableProperties tableProperties)
     {
         this.lifeCycleManager = requireNonNull(lifeCycleManager, "lifeCycleManager is null");
         this.metadata = requireNonNull(metadata, "metadata is null");
         this.splitManager = requireNonNull(splitManager, "splitManager is null");
         this.pageSourceProvider = requireNonNull(pageSourceProvider, "pageSourceProvider is null");
         this.partitioningProvider = requireNonNull(partitioningProvider, "partitioningProvider is null");
         this.sessionProperties = requireNonNull(pinotSessionProperties, "pinotSessionProperties is null");
+        requireNonNull(tableProperties, "tableProperties is null");
+        columnProperties = tableProperties.getColumnProperties();
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnector.java:62]: nit: Add `requireNonNull` and `ImmutableList.copyOf`.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java [hunk 2]
```diff
@@ -529,7 +528,7 @@ private List<ColumnMetadata> getPinotColumnMetadataForPinotSchema(Schema pinotTa
                         .setName(columnName)
                         .setType(typeConverter.toTrinoType(pinotTableSchema.getFieldSpecFor(columnName)))
                         .setProperties(ImmutableMap.<String, Object>builder()
-                                .put(PINOT_COLUMN_NAME_PROPERTY, columnName)
+                                .put(PinotTableProperties.PINOT_COLUMN_NAME_PROPERTY, columnName)
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java:531]: nit: Static import `PINOT_COLUMN_NAME_PROPERTY`

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+import com.google.common.collect.ImmutableList;
+import io.trino.spi.session.PropertyMetadata;
+
+import java.util.List;
+
+import static io.trino.spi.session.PropertyMetadata.stringProperty;
+
+public class PinotTableProperties
+{
+    public static final String PINOT_COLUMN_NAME_PROPERTY = "pinot_column_name";
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java:25]: Could you leave code comment why this property is required? It's much different from other connectors.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+    private final List<PropertyMetadata<?>> columnProperties;
+
+    public PinotTableProperties()
+    {
+        columnProperties = ImmutableList.<PropertyMetadata<?>>builder()
+                .add(stringProperty(PINOT_COLUMN_NAME_PROPERTY, "Pinot columnName", null, false))
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java:31]: I'm not sure if we want to expose this property to users. Can we make it hidden?

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java [hunk 5]
```diff
@@ -979,7 +979,7 @@ public static Object of(
     @Override
     public void testShowCreateTable()
     {
-        assertQueryFails("SHOW CREATE TABLE region", "No PropertyMetadata for property: pinotColumnName");
+        assertQuerySucceeds("SHOW CREATE TABLE region");
```
Comment (ebyhr) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java:982]: Please check returned value likes: 
```java
        assertThat((String) computeScalar("SHOW CREATE TABLE region"))
                .isEqualTo(...);
```

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java (hunk 4 above)
Comment (elonazoulay) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java:31]: Sure, but there might be some value, as it will show the actual pinot column name if it contains non lower case characters. I have a pr (need to update) for create table which uses this and many more properties. Should I leave it hidden for now and update in the future when it becomes more relevant? Or do you think it's worth exposing now bcz of non-lower case characters in tables?

Comment (ebyhr) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java:31]: I think it would be better to hide for now because exposing hidden table property later wouldn't break compatibilities.

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java [hunk 6]
```diff
@@ -979,7 +979,7 @@ public static Object of(
     @Override
     public void testShowCreateTable()
     {
-        assertQueryFails("SHOW CREATE TABLE region", "No PropertyMetadata for property: pinotColumnName");
```
Comment (findepi) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java:982]: So we have generic tests to prevent bugs like https://github.com/trinodb/trino/issues/14071, but then we disable tests because we have bugs. 
What can we improve in our process to avoid having bugs lingering in the code?

Comment (ebyhr) [reply plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java:982]: This test class was migrated to BaseConnectorSmokeTest from AbstractTestQueryFramework 6 days ago in #13619. The bug was found and the test was disabled during the migration, so it's not "lingering" in my opinion. 

(It's not answer to "What can we improve in our process to avoid having bugs lingering in the code?" though)

Comment (findepi) [reply plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java:982]: It'd be better if the code here had a TODO comment and a github issue link.

Anyway, thanks for explaining. It's good it was not lingering.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnector.java (hunk 1 above)
Comment (elonazoulay) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnector.java:62]: requireNonNull is on the line above, should I merge it?

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java (hunk 3 above)
Comment (elonazoulay) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java:25]: Added a note. Do you recommend I do it differently? lmk if you have an example I can look at. Thanks!

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnector.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnector.java:62]: Let's add only `ImmutableList.copyOf`.

**Comment by findepi** [comment]
What's the "column name property" and how is it different from the column name?

cc @martint

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java (hunk 3 above)
Comment (ebyhr) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java:25]: Could you push the change? I can't see the note.

**Comment by elonazoulay** [comment]
@findepi - The column name property is the pinot column name which may contain non lowercase characters.

**Comment by elonazoulay** [comment]
Does it make sense to entirely remove the PINOT_COLUMN_NAME property until create table pr (#7164 )?
I will add a commit and remove it. I can always revert.

**Comment by elonazoulay** [comment]
Looks like the hidden property is ignored for show create table.
Should hidden column properties be filtered out in ShowQueriesRewrite (below)?
```
Collection<PropertyMetadata<?>> allColumnProperties = columnPropertyManager.getAllProperties(tableHandle.getCatalogHandle());
```
@ebyhr @findepi

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java (hunk 3 above)
Comment (elonazoulay) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableProperties.java:27]: Pushed.

**Comment by findepi** [comment]
> @findepi - The column name property is the pinot column name which may contain non lowercase characters.

We don't use "column property" in any other connector. Why did we consider Pinot to be special and require different approach?

**Comment by elonazoulay** [comment]
I don't want it to be special in that way:) iirc this was from the first version. Instead should I just keep a mapping? 
Instead of being able to create a PinotColumnHandle directly from column metadata, should it look up the pinot "raw" column name? Assuming that's what you mean, lmk.

**Comment by findepi** [comment]
If agree that "column property" is the way to go, that's what we should be doing in other connectors, like PostgreSQL, MySQL, SQL Server, etc.
if we agree that "column property" way is not superior, Pinot connector shouldn't be doing that (unless there is some Pinot-specific reason to)

**Comment by elonazoulay** [comment]
I think it's better to remove it: since no other connectors use it and there is a way to do this without the column property then it makes more sense to remove it. Refactoring this pr. wdyt? (I'll save this branch just in case).

**Comment by elonazoulay** [comment]
Whenever you have a chance, I updated to pr to remove the property cc @findepi @ebyhr

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotColumnHandle.java [hunk 7]
```diff
@@ -44,7 +41,7 @@
 
     public PinotColumnHandle(String columnName, Type dataType)
     {
-        this(columnName, dataType, columnName, false, false, true, Optional.empty(), Optional.empty());
+        this(columnName, dataType, quoteIdentifier(columnName), false, false, true, Optional.empty(), Optional.empty());
```
Comment (ebyhr) [inline plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotColumnHandle.java:44]: It would be better to store an original column name (not quoted) in `PinotColumnHandle` and quote it when needed. Could you leave TODO comment since it's pre-existing issue?

File: plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java [hunk 8]
```diff
@@ -1000,7 +1001,16 @@ public static Object of(
...
+        assertThat((String) computeScalar("SHOW CREATE TABLE region"))
+                .matches(format(
```
Comment (ebyhr) [inline plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java:1005]: Can we use `isEqualTo` instead? I suppose we don't need to use a regular expression here.

File: plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotColumnHandle.java (hunk 7 above)
Comment (elonazoulay) [reply plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotColumnHandle.java]: I updated to quote when needed. Do you still recommend a TODO comment?
(also saved previous version just in case)

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
Merged, thanks!
