### PR TITLE
Fix incorrect results for aggregation functions on case-sensitive types

### LINKED ISSUE #7320: Incorrect aggregation pushdown for case insensitive columns in JDBC some connectors
In MySql:
```
trino:tpch> select c from x;
 c
---
 a
 A
 b
 B
(4 rows)

trino:tpch> select distinct c from x;
 c
---
 a
 b
(2 rows)
```

Possibly affects SQL Server and MemSql too.

### PR DESCRIPTION
**Pull request by hashhar**
Pushdown of aggregation functions to case-insensitive databases (e.g. MySQL) on case-sensitive inputs (e.g. VARCHAR/CHAR) can lead to incorrect results.

This change disables aggregation pushdown when:

- Any of the grouping sets is a case-sensitive type
- If the aggregation function is case-sensitive (e.g. max/min but not count) and any of the inputs to the aggregation function is a case-sensitive type

~It also introduces a toggle to restore previous incorrect behaviour.~

Fixes #7320

### CODE REVIEW

File: plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java [hunk 1]
```diff
@@ -682,6 +682,13 @@ public WriteMapping toWriteMapping(ConnectorSession session, Type type)
         return aggregateFunctionRewriter.rewrite(session, aggregate, assignments);
     }
 
+    @Override
+    public boolean supportsAggregationPushdown(ConnectorSession session, JdbcTableHandle table, List<AggregateFunction> aggregates, Map<String, ColumnHandle> assignments, List<List<ColumnHandle>> groupingSets)
+    {
+        // Postgres sorts textual types differently compared to Trino so we cannot safely pushdown any aggregations which take a text type as an input or as part of grouping set
```
Comment (findepi) [inline plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java:688]: if it's about sorting (as we believe it is), limitation doesn't apply to GROUPING SETs. 
Also it applies to some aggregation functions (`min`, `max`), but not others `count`, or `count(DISTINCT)`

File: plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java [hunk 2]
```diff
@@ -423,6 +423,13 @@ private static LongReadFunction sqlServerDateReadFunction()
         return aggregateFunctionRewriter.rewrite(session, aggregate, assignments);
     }
 
+    @Override
+    public boolean supportsAggregationPushdown(ConnectorSession session, JdbcTableHandle table, List<AggregateFunction> aggregates, Map<String, ColumnHandle> assignments, List<List<ColumnHandle>> groupingSets)
+    {
+        // Remote database can be case insensitive.
+        return preventTextualTypeAggregationPushdown(aggregates, groupingSets);
```
Comment (findepi) [inline plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java:430]: `count(a_varchar)` should still be pushed down, as case sensitivity (or more broadly: collations), doesn't impact results.

File: plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java [hunk 3]
```diff
@@ -159,6 +159,13 @@ public ClickHouseClient(
         return aggregateFunctionRewriter.rewrite(session, aggregate, assignments);
     }
 
+    @Override
+    public boolean supportsAggregationPushdown(ConnectorSession session, JdbcTableHandle table, List<AggregateFunction> aggregates, Map<String, ColumnHandle> assignments, List<List<ColumnHandle>> groupingSets)
+    {
+        // TODO: Remove override once https://github.com/trinodb/trino/issues/7100 is resolved. Currently pushdown for textual types is not tested and may lead to incorrect results.
```
Comment (findepi) [inline plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java:165]: https://github.com/trinodb/trino/issues/7100

File: plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java (hunk 1 above)
Comment (hashhar) [reply plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java:688]: Yes. The part about difference between aggregation functions came up before but I couldn't find a nice way to model it (other than introduce a field to AggregateFunction and having each of them declare if they depend on case-sensitivity for correctness).

For the grouping set - thanks for catching. Postgres indeed doesn't need the grouping set check - only the aggregate function check.

Comment (findepi) [reply plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java:688]: Re how to model - since this is function specific, it could be handled by `io.trino.plugin.jdbc.expression.AggregateFunctionRule#rewrite` returning `empty` or not.

Comment (hashhar) [reply plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java:688]: That's what I tried initially but it's a bit errorprone since each module has their own rewrites. I can try to move as many to base-jdbc as possible in a preparatory commit.

Comment (hashhar) [reply plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java:688]: Also, to confirm, you mean that the grouping sets condition can be handled in `supportsAggregation` like now.
And instead of handling the functions in `supportsAggregation` I should handle them in the rewrite rules?

Comment (findepi) [reply plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java:688]: > That's what I tried initially but it's a bit errorprone since each module has their own rewrites. I can try to move as many to base-jdbc as possible in a preparatory commit.

That's unlikely to work. We have separate rewrites because there were some differences.

> Also, to confirm, you mean that the grouping sets condition can be handled in supportsAggregation like now.

i didn't read that part, so "maybe"

> And instead of handling the functions in supportsAggregation I should handle them in the rewrite rules?

that's my intuition

Comment (hashhar) [reply plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java:688]: I implemented the approach you suggested - it works and thankfully the only case-sensitive rewrites live in base-jdbc already.

**Comment by hashhar** [comment]
PTAL @findepi @wendigo

I can add a session property to restore performance at the user's own discretion - what should we call it? (if we do this then I'll also address https://github.com/trinodb/trino/pull/7022 as part of it).

**Comment by hashhar** [comment]
@wendigo @findepi Gentle ping. 🙂

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java [hunk 4]
```diff
@@ -55,6 +64,11 @@
         JdbcColumnHandle columnHandle = (JdbcColumnHandle) context.getAssignment(input.getName());
         verify(columnHandle.getColumnType().equals(aggregateFunction.getOutputType()));
 
+        // Remote database is case insensitive or sorts values differently from Trino
+        if (!isRemoteCaseSensitive && (columnHandle.getColumnType() instanceof CharType || columnHandle.getColumnType() instanceof VarcharType)) {
+            return Optional.empty();
```
Comment (findepi) [inline plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java:69]: That's based on a wrong type.

For example, PostgreSQL's money and enum types are mapped to Trino varchar, while both will have different sorting properties.

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java [hunk 5]
```diff
@@ -40,6 +42,13 @@
 {
     private static final Capture<Variable> INPUT = newCapture();
 
+    private final boolean isRemoteCaseSensitive;
+
+    public ImplementMinMax(boolean isRemoteCaseSensitive)
+    {
+        this.isRemoteCaseSensitive = isRemoteCaseSensitive;
```
Comment (findepi) [inline plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java:49]: it's not exactly about case sensitivity. For example, by default PostgreSQL is case-sensitive, but still sorts differently than Trino, so we shouldn't push min/max on varchar.

BTW do PostgresQL min/max accept COLLATE?

File: plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java [hunk 6]
```diff
@@ -195,7 +195,7 @@ public void testAggregationPushdown()
         // GROUP BY above TopN
         assertConditionallyPushedDown(
                 getSession(),
-                "SELECT clerk, sum(totalprice) FROM (SELECT clerk, totalprice FROM orders ORDER BY orderdate ASC, totalprice ASC LIMIT 10) GROUP BY clerk",
+                "SELECT custkey, sum(totalprice) FROM (SELECT custkey, totalprice FROM orders ORDER BY orderdate ASC, totalprice ASC LIMIT 10) GROUP BY custkey",
```
Comment (findepi) [inline plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java:198]: why change here?

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java [hunk 7]
```diff
@@ -949,6 +950,24 @@ protected WriteMapping legacyToWriteMapping(@SuppressWarnings("unused") Connecto
         throw new TrinoException(NOT_SUPPORTED, "Unsupported column type: " + type.getDisplayName());
     }
 
+    protected boolean preventTextualTypeAggregationPushdown(List<AggregateFunction> aggregates, List<List<ColumnHandle>> groupingSets)
```
Comment (findepi) [inline plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java:953]: can this be static?

(that would help understand the state flow)

File: plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java [hunk 8]
```diff
@@ -211,17 +211,80 @@ public void testAggregationPushdown()
...
+            assertConditionallyPushedDown(getSession(),
+                    "SELECT a_char, count(*) FROM " + table.getName() + " GROUP BY a_char",
+                    expectAggregationPushdown,
+                    groupingAggregationOverTableScan)
+                    .skippingTypesCheck()
+                    .matches("VALUES ('A', BIGINT '1'), ('B', BIGINT '1'), ('a', BIGINT '1'), ('b', BIGINT '1')");
+
+            // case-insensitive functions can still be pushed down as long as grouping sets are not case-sensitive
+            assertThat(query("SELECT count(a_string), count(a_char) FROM " + table.getName())).isFullyPushedDown();
+            assertThat(query("SELECT count(a_string), count(a_char) FROM " + table.getName() + " GROUP BY a_bigint")).isFullyPushedDown();
```
Comment (findepi) [inline plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java:284]: let's add a correctness cases 

- `count(DISTINCT a_string)`
- `count(DISTINCT a_string), `count(DISTINCT a_bigint)` (together)

this could help avoid any regressions in #8562 cc @alexjo2144

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java [hunk 9]
```diff
@@ -949,6 +950,24 @@ protected WriteMapping legacyToWriteMapping(@SuppressWarnings("unused") Connecto
...
+    {
+        // The remote database may be case-insensitive or sort textual types differently than Trino.
```
Comment (findepi) [inline plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java:955]: > remote database may be case-insensitive

nit: Use "Remote database can be case insensitive" words, so that similar places in the code are searchable.

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java (hunk 5 above)
Comment (hashhar) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java:49]: I think the complaint here is that the variable is named in a misleading way? Maybe `isCollationSensitive` would be better?

Functions don't accept explicit collations - I couldn't find any examples and the variations I tried led to syntax errors.

File: plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java (hunk 6 above)
Comment (hashhar) [reply plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java:198]: clerk is varchar and part of grouping set so it prevents pushdown after the change. Changed to use a numeric column since we just want to test GROUP BY + TOPN.

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java (hunk 7 above)
Comment (hashhar) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java:953]: Yes, should've been static from the start. thanks.

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java (hunk 4 above)
Comment (hashhar) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java:69]: Since the rewrite rule is generic I think the only solution is to allow connectors to pass a list of `jdbcTypeName` through the constructor for types which should not be pushed down?

Or maybe add a static function to JdbcClient called `isCollationSensitive(JdbcColumnHandle)` and let connectors define their own impls? This method already exists in the PostgreSQL client btw and may be useful for others where we can pass explicit collations (MySQL once we drop 5.x).

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java (hunk 5 above)
Comment (findepi) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java:49]: > I think the complaint here is that the variable is named in a misleading way

yes

File: plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java (hunk 4 above)
Comment (findepi) [reply plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java:69]: Yeah, i think we already use "is mapped to char or varchar" as a way to determine if it's potentially case insensitive (or collation-sensitive).
it may catch too much, but shouldn't catch too little, so it's fine.

live as is

**Review by findepi — APPROVED** [review]
% earlier feedback

**Comment by hashhar** [comment]
@wendigo PTAL. Applied @findepi 's comments.

**Comment by wendigo** [comment]
LGTM @hashhar - thanks for working on that

**Review by wendigo — APPROVED** [review]

**Comment by hashhar** [comment]
Rebasing to make sure nothing broke since the upgrade. Will merge once CI finishes.

**Comment by hashhar** [comment]
CI hit https://github.com/trinodb/trino/issues/8719 and https://github.com/trinodb/trino/issues/8432
