### PR TITLE
Fix exponential behavior during error reporting

### LINKED ISSUE #1407: Excessive runtime for parser error reporting
The following query takes over ten minutes to fail with a syntax error:
```sql
SELECT CASE
WHEN orderkey = 1 THEN rand() * rand() * rand() * rand() * rand() * rand() * orderkey
WHEN orderkey = 2 THEN rand() * rand() * rand() * rand() * rand() * rand() * orderkey
WHEN orderkey = 3 THEN rand() * rand() * rand() * rand() * rand() * rand() * orderkey
FROM tpch.tiny.orders
```
Example stack trace while it is executing:
```
dispatcher-query-1
    at io.prestosql.sql.parser.ErrorHandler$Analyzer.process(ErrorHandler.java:227)
    at io.prestosql.sql.parser.ErrorHandler$Analyzer.process(ErrorHandler.java:168)
    at io.prestosql.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:94)
    at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
    at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
    at io.prestosql.sql.parser.SqlBaseParser.selectItem(SqlBaseParser.java:5399)
    at io.prestosql.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:4639)
    at io.prestosql.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:4407)
    at io.prestosql.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:4212)
    at io.prestosql.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3967)
    at io.prestosql.sql.parser.SqlBaseParser.query(SqlBaseParser.java:3335)
    at io.prestosql.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1702)
    at io.prestosql.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:241)
    at io.prestosql.sql.parser.SqlParser$$Lambda$1043/1469548577.apply(Unknown Source)
    at io.prestosql.sql.parser.SqlParser.invokeParser(SqlParser.java:160)
    at io.prestosql.sql.parser.SqlParser.createStatement(SqlParser.java:96)
    at io.prestosql.execution.QueryPreparer.prepareQuery(QueryPreparer.java:55)
    at io.prestosql.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:173)
    at io.prestosql.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:145)
    at io.prestosql.dispatcher.DispatchManager$$Lambda$1036/1172325934.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by martint**
Fixes #1407

### CODE REVIEW

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 1]
```diff
@@ -148,24 +185,23 @@ public CallerContext(CallerContext parent, ATNState followState)
...
                 Map<Integer, String> specialTokens,
-                Set<Integer> ignoredRules,
-                TokenStream stream)
+                Set<Integer> ignoredRules)
         {
-            this.stream = stream;
-            this.atn = atn;
-            this.vocabulary = vocabulary;
+            this.parser = parser;
+            this.stream = parser.getTokenStream();
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: could you also move this assignment last? (stream is a last field)

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 2]
```diff
@@ -115,14 +115,50 @@ public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int
...
+            this.parser = parser;
+            this.depth = depth;
+        }
+
+        @Override
+        public String toString()
+        {
+            Token token = parser.getTokenStream().get(tokenIndex);
+
+            String text = token.getText();
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: nit `firstNonNull(token.getText(), "?")`

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 3]
```diff
@@ -115,14 +115,50 @@ public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int
...
+            if (text != null) {
+                text = text.replace("\n", "\\n");
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: you may also want (first)
`.replace("\\", "\\\\")`

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 4]
```diff
@@ -115,14 +115,50 @@ public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int
...
+                text = text.replace("\r", "\\r");
+                text = text.replace("\t", "\\t");
+            }
+            else {
+                text = "?";
+            }
+
+            StringBuilder builder = new StringBuilder();
+            builder.append(String.format("[%s] %s%s:%s @ %s:<%s>:%s",
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: static import,
per code style, add \n before fmt str

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 5]
```diff
@@ -115,14 +115,50 @@ public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int
...
+            if (text != null) {
+                text = text.replace("\n", "\\n");
+                text = text.replace("\r", "\\r");
+                text = text.replace("\t", "\\t");
+            }
+            else {
+                text = "?";
+            }
+
+            StringBuilder builder = new StringBuilder();
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: no need for StringBuilder here.

Just
```
String string = format( ... );

if (caller != null) {
    string += format(...);
}

return string;
```

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 6]
```diff
@@ -144,33 +136,13 @@ public String toString()
                 text = "?";
             }
 
-            StringBuilder builder = new StringBuilder();
-            builder.append(String.format("[%s] %s%s:%s @ %s:<%s>:%s",
-                    depth,
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: correct me if i'm wrong, this belongs to the previous commit

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 7]
```diff
@@ -144,33 +136,13 @@ public String toString()
...
+            return String.format("%s%s:%s @ %s:<%s>:%s",
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: static import,
per code style, add \n before fmt str

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 8]
```diff
@@ -199,14 +174,59 @@ public Analyzer(
...
+            activeStates.add(from);
+
+            while (!activeStates.isEmpty()) {
+                ATNState current = activeStates.pop();
+
+                if (current.stateNumber == target.stateNumber) {
+                    return true;
+                }
+
+                for (int i = 0; i < current.getNumberOfTransitions(); i++) {
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: `for (Transition transition : current.getTransitions()) {`

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 9]
```diff
@@ -199,14 +174,59 @@ public Analyzer(
...
+        }
+
+        private boolean isReachable(ATNState target, RuleStartState from)
         {
-            return process(new ParsingState(currentState, tokenIndex, false, makeCallStack(context), parser, 0));
+            Deque<ATNState> activeStates = new ArrayDeque<>();
+            activeStates.add(from);
+
+            while (!activeStates.isEmpty()) {
+                ATNState current = activeStates.pop();
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: is it obvious there cannot be a cycle?

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 10]
```diff
@@ -199,14 +174,59 @@ public Analyzer(
...
+
+                if (current.stateNumber == target.stateNumber) {
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: The search could be shorter if you checked the condition before _adding_ to the queue, not after _pop_. (just thinking)

File: presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java [hunk 11]
```diff
@@ -112,7 +112,7 @@
                 {"SELECT a AS z FROM t WHERE x = 1 + ",
                         "line 1:36: mismatched input '<EOF>'. Expecting: <expression>"},
                 {"SELECT a AS z FROM t WHERE a. ",
-                        "line 1:29: mismatched input '.'. Expecting: '%', '*', '+', '-', '/', 'AT', '||', <expression>"},
+                        "line 1:29: mismatched input '.'. Expecting: '%', '*', '+', '-', '/', 'AND', 'AT', 'EXCEPT', 'FETCH', 'GROUP', 'HAVING', 'INTERSECT', 'LIMIT', 'OFFSET', 'OR', 'ORDER', 'UNION', '||', <EOF>, <predicate>"},
```
Comment (findepi) [inline presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java]: I wonder why the `.` is the problem. It could be saying:
```
unexpected EOF, expecting: <identifier> (field)
```

File: presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java [hunk 12]
```diff
@@ -139,6 +139,23 @@
         };
     }
 
+    @Test
```
Comment (findepi) [inline presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java]: add timeout

File: presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java [hunk 13]
```diff
@@ -139,6 +139,23 @@
...
+                        "1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9 * " +
+                        "1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9 * " +
+                        "1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9 * " +
+                        "1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9 * " +
+                        "1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9 * " +
+                        "1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9 * " +
+                        "1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9 * " +
+                        "1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9 * " +
+                        "1 * 2 * 3 * 4 * 5 * 6 * 7 * 8 * 9",
+                "line 1:375: mismatched input '<EOF>'. Expecting: '%', '*', '+', '-', '/', 'AT', 'THEN', '||'");
```
Comment (findepi) [inline presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java]: i'd expect `IS` too, for example in `CASE WHEN {multiplication} IS NULL THEN 'zonk' ELSE ..`

(just noting, no change requested)

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 14]
```diff
@@ -345,4 +376,26 @@ public ErrorHandler build()
             return new ErrorHandler(specialRules, specialTokens, ignoredRules);
         }
     }
+
+    private static class Result
+    {
+        private final int errorToken;
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: `Token`? or name it `errorTokenIndex`

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 15]
```diff
@@ -91,17 +90,14 @@ public void syntaxError(Recognizer<?, ?> recognizer, Object offendingSymbol, int
...
-            String expected = candidates.asMap().entrySet().stream()
-                    .max(Comparator.comparing(Map.Entry::getKey))
-                    .get()
-                    .getValue().stream()
+            String expected = result.getExpected().stream()
                     .sorted()
                     .collect(Collectors.joining(", "));
 
-            message = format("mismatched input '%s'. Expecting: %s", ((Token) offendingSymbol).getText(), expected);
+            message = format("mismatched input '%s'. Expecting: %s", parser.getTokenStream().get(result.getErrorToken()).getText(), expected);
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: Using `result.getErrorToken()` (`furthestToken`) there is a theoretical possibility we will say "mismatched" at quoting something else than ANTLR choked at. 

I replaced `parser.getTokenStream().get(result.getErrorToken())` with `((Token) offendingSymbol)` and it didnt have any noticable impact.
Maybe at least something like
```
if (((Token) offendingSymbol).getTokenIndex() != result.getErrorToken()) {
   log.warn ..
}
```
?

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 16]
```diff
@@ -273,41 +293,52 @@ else if (transition instanceof WildcardTransition) {
                             labels = labels.complement(IntervalSet.of(Token.MIN_USER_TOKEN_TYPE, atn.maxTokenType));
                         }
 
-                        if (labels.contains(currentToken)) {
-                            activeStates.push(new ParsingState(transition.target, tokenIndex + 1, false, caller, parser, current.depth + 1));
+                        if (labels.contains(currentToken) && tokenIndex < stream.size() - 1) {
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: is `&& tokenIndex < stream.size() - 1` necessary?
i think EOF token serves as a sentinel.

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java [hunk 17]
```diff
@@ -273,41 +293,52 @@ else if (transition instanceof WildcardTransition) {
...
         {
-            if (context == null || context.invokingState == -1) {
-                return null;
+            if (tokenIndex >= furthestToken) {
+                if (tokenIndex > furthestToken) {
+                    candidates.clear();
+                }
+
+                candidates.addAll(labels);
+                furthestToken = tokenIndex;
```
Comment (findepi) [inline presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: move this assignment inside `if (tokenIndex > furthestToken) {`

**Review by findepi — APPROVED** [review]
Couple of minor comments

File: presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java (hunk 11 above)
Comment (martint) [reply presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java]: That's a good question. Let me investigate.

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java (hunk 15 above)
Comment (martint) [reply presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: It doesn't really matter. All we care about is that there is *some* syntax error and we want to produce a reasonable error. There's no false positive issue here where we might report an error where there is none.

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java (hunk 16 above)
Comment (martint) [reply presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: I had to add this in one of my earlier experiments, but you're right. Let me see if I can change it back.

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java (hunk 9 above)
Comment (martint) [reply presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: Yes, it's guaranteed there are no cycles via epsilon transitions. Obviously, there could be a cycle via transitions that consume tokens, but those would eventually consume the entire input and finish.

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java (hunk 8 above)
Comment (martint) [reply presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: I chose the current version because `getTransitions()` does an eager copy of the underlying array.

File: presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java (hunk 10 above)
Comment (martint) [reply presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java]: I'd need to duplicate the check in the `add` above the loop (in case target == from) and before the `push()` below. I thought it unnecessarily complicated the code for very little practical gain.

File: presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java (hunk 11 above)
Comment (martint) [reply presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java]: It's because Antlr bails out and leaves the the parser at a state past `>primaryExpression>`, which is the one that recognizes `<identifier> . <identifier>`. I guess it's matching `<identifier>` greedily as a `<primaryExpression>' because that's all that it can match given the available tokens in the stream and then it says "oops, what do I do with this `.`" now?

File: presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java (hunk 13 above)
Comment (martint) [reply presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java]: That's partly because our grammar does: `CASE <valueExpression> WHEN ...`. Looking at the spec, it seems to allow more complex expressions, including our `<booleanExpression>` (I'll fix that as a separate change). Even them, it suffers from the same problem I explained regarding `SELECT ... FROM ... WHERE a.`
