### PR TITLE
Fix case-sensitivity issue with views and column masks

### LINKED ISSUE #24054: Column masks don't work when view declares columns with uppercase names
The view can be as simple as something like this:

```sql
CREATE VIEW test_view AS SELECT 123 AS "COLUMN";
```

When there is a column mask on "column", it should work, because in Trino column names are case-insensitive, but it does not.

(It's difficult to have a full reproducer in a ticket description, because there's no syntax to create column masks in SQL.)

### PR DESCRIPTION
**Pull request by ksobolew**
## Description

The table column reference was registered incorrectly with the original case taken from the view definition. It then failed to match the column schema returned from `SystemAccessControl` and the mask was not applied.

Instead of sprinkling `toLowerCase()` here and there, we will associate the original `Field` with the column mask and use `Field#canResove` to do the matching. The problem with this is that there's no way to do efficient lookups by name in a case-insensitive way, so we have to iterate the list of `Field`-`Expression` pairs to find a match.

Fixes #24054.

## Additional context and related issues

I wonder how many more issues like that will we find...

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
## Section
* Fixed column masks not applying on views declaring non-lowercase column names. ({issue}`24054`)
```

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java [hunk 1]
```diff
@@ -766,7 +766,7 @@ private Type handleResolvedField(Expression node, ResolvedField resolvedField, C
             }
 
             if (field.getOriginTable().isPresent() && field.getOriginColumnName().isPresent()) {
-                tableColumnReferences.put(field.getOriginTable().get(), field.getOriginColumnName().get());
+                tableColumnReferences.put(field.getOriginTable().get(), field.getOriginColumnName().get().toLowerCase(ENGLISH));
```
Comment (ksobolew) [inline core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java:769]: @martint I sprinkled those `toLowerCase` in enough places to fix this particular issue, but I'm not entirely sure if these are the right places. I think the convention is to keep the original case in the AST and only convert it as needed in the analyzer, even though it would probably be easier to fix all issues like this by storing converted names in AST. WDYT?

Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java:769]: Identifiers need to be resolved according to standard sql rules. It differs for quoted vs non-quoted identifiers.

Currently, there are some inconsistencies  in how they are being handled in various places, but we have a long standing issue to fix them. See https://github.com/trinodb/trino/issues/17

**Review by homar — APPROVED** [review]

File: core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java (hunk 1 above)
Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java:769]: I think we can fix this by associating masks to the corresponding Field in StatementAnalyzer and Analysis, instead of doing it by name. Then, in RelationPlanner, the lookup can be done directly by Field instead of relying on the name having the right case.

Comment (ksobolew) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java]: @martint I pushed a prototype of a solution which (I think) implements your suggestion. There's no way to do efficient lookups of `Field`s, though, so in some places we need to do a linear scan of the list of masks in order to find a match.

File: core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java [hunk 2]
```diff
@@ -171,6 +182,7 @@ public TestColumnMask()
                 })
                 .withGetViews((s, prefix) -> ImmutableMap.of(
                         new SchemaTableName("default", "nation_view"), view,
+                        new SchemaTableName("default", "nation_view_uppercase"), viewWithDifferentCase,
```
Comment (kokosing) [inline core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:185]: uppercase and differentcase? I guess you want to pick one.

File: core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java [hunk 3]
```diff
@@ -89,6 +89,17 @@ public TestColumnMask()
                 Optional.of(VIEW_OWNER),
                 false,
                 ImmutableList.of());
+        ConnectorViewDefinition viewWithDifferentCase = new ConnectorViewDefinition(
```
Comment (kokosing) [inline core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:92]: viewWithUpperCasedColumnNames

File: core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java [hunk 4]
```diff
@@ -441,10 +441,11 @@ private RelationPlan addColumnMasks(Table table, RelationPlan plan)
         for (int i = 0; i < plan.getDescriptor().getAllFieldCount(); i++) {
             Field field = plan.getDescriptor().getFieldByIndex(i);
 
-            io.trino.sql.tree.Expression mask = columnMasks.get(field.getName().orElseThrow());
+            Optional<io.trino.sql.tree.Expression> columnMask = Analysis.resolveColumnMask(table.getName(), field.getName().orElseThrow(), columnMasks);
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java:444]: I don't understand this. You pass multiple columns (field expressions) and you get a single mask. I think you should pass only a single column here.

File: core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java [hunk 5]
```diff
@@ -2377,23 +2377,33 @@ private void checkStorageTableNotRedirected(QualifiedObjectName source)
...
+                    fieldBuilder.add(field);
+                    columnSchemaBuilder.add(ColumnSchema.builder()
+                            .setName(fieldName)
+                            .setType(field.getType())
+                            .setHidden(field.isHidden())
+                            .build());
+                });
             }
+            List<Field> fields = fieldBuilder.build();
             List<ColumnSchema> columnSchemas = columnSchemaBuilder.build();
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java:2394]: is this still used?

File: core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java [hunk 6]
```diff
@@ -5222,9 +5232,9 @@ private void analyzeCheckConstraint(Table table, QualifiedObjectName name, Scope
             analysis.addCheckConstraints(table, expression);
         }
 
-        private void analyzeColumnMask(String currentIdentity, Table table, QualifiedObjectName tableName, ColumnSchema columnSchema, Scope scope, ViewExpression mask)
+        private void analyzeColumnMask(String currentIdentity, Table table, QualifiedObjectName tableName, Field columnSchema, Scope scope, ViewExpression mask)
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java:5235]: rename `columnSchema` to field, or restore previous type..

**Review by kokosing — APPROVED** [review]
% comments

File: core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java (hunk 5 above)
Comment (ksobolew) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java:2394]: Yes, `columnSchemas` is what we pass to access control.

Comment (ksobolew) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java:2394]: But note that the SPI effectively forces everything to be lower-case for access control.

File: core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java (hunk 4 above)
Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java:444]: This shouldn't be doing any resolution. It has the `Field`, so all it needs to do is look up the corresponding expression for that field, which should be stored in the analysis object.

So, in a nutshell:
* The analyzer resolves the schema associated with the underlying table (modeled by RelationType)
* The analyzer resolves the masks by column name and analyzes them (type checks, etc). It associates them with the corresponding Field from RelationType.
* The planner injects the necessary projections for each Field by looking them up in the data structure produces by the analyzer (Analysis)

Comment (ksobolew) [reply core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java]: Thanks! I can see there are already `Map`s where `Field` is the key - I wasn't sure I can use it this way, but now the `columnMasks` collection simply changes from `Map<String, Expression>` to `Map<Field, Expression>` and it simplifies things a bit.

File: core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java [hunk 7]
```diff
@@ -1189,7 +1190,7 @@ public List<TableInfo> getReferencedTables()
                             .distinct()
                             .map(fieldName -> new ColumnInfo(
                                     fieldName,
-                                    Optional.ofNullable(columnMasks.getOrDefault(table, ImmutableMap.of()).get(fieldName))
+                                    resolveColumnMask(table.getNode().getName(), fieldName, columnMasks.getOrDefault(table, ImmutableMap.of()))
```
[the remark this answers is not in the document]
Comment (ksobolew) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java:1193]: `columnMasks` already is adjusted. What I would have to adjust is `Analysis#tableColumnReferences`, which currently stores column names as `String` (and uses this to deduplicate references, I think?).

File: core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java [hunk 8]
```diff
@@ -1210,6 +1211,22 @@ public List<TableInfo> getReferencedTables()
                 .collect(toImmutableList());
     }
 
+    private static Optional<Expression> resolveColumnMask(QualifiedName tableName, String fieldName, Map<Field, Expression> expressions)
+    {
+        return expressions.entrySet().stream()
+                .filter(fieldExpression -> fieldExpression.getKey().canResolve(concatIdentifier(tableName, fieldName)))
+                .findFirst()
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java:1218]: Is it ok to have multiple matches here? Shouldn't we expect `Optional` semantic here?

Comment (ksobolew) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java:1218]: This is a good question. I think it's impossible to have multiple matches here. Like @martint says, ideally this would be a `Map` lookup, this should be a 1:0..1 relationship here.

Comment (kokosing) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java:1218]: So let's use `.collect(toOptional())`

Comment (ksobolew) [reply core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java]: Done

**Review by kokosing — APPROVED** [review]

**Comment by kokosing** [comment]
@martint it looks like all the comments are addressed. I would like to move forward with this as this is a fixing a bug, please let me know if you have any more comments, otherwise I would like to merge it.

**Comment by kokosing** [comment]
This PR is fixing the bug, so I think it is important to get this in. If there are any follow up comments about the execution flow or structures I think @ksobolew will be happy to address them in another PR. So any post merge code review is welcome.

**Comment by ksobolew** [comment]
Thank you @kokosing!
