### PR TITLE
Fix events collector

### LINKED ISSUE #5922: Flaky test TestEventListener.testPlanningFailure
https://github.com/prestosql/presto/runs/1386057381

```
2020-11-11T16:45:57.6822217Z [ERROR] Tests run: 2082, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2,162.941 s <<< FAILURE! - in TestSuite
2020-11-11T16:45:57.6823688Z [ERROR] testPlanningFailure(io.prestosql.execution.TestEventListener)  Time elapsed: 0.019 s  <<< FAILURE!
2020-11-11T16:45:57.6825688Z java.lang.IllegalArgumentException: expected one element but was: <io.prestosql.spi.eventlistener.QueryCompletedEvent@7142368e, io.prestosql.spi.eventlistener.QueryCompletedEvent@4b216d17>
2020-11-11T16:45:57.6827721Z 	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:315)
2020-11-11T16:45:57.6829025Z 	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
2020-11-11T16:45:57.6830576Z 	at io.prestosql.execution.TestEventListener.assertFailedQuery(TestEventListener.java:243)
2020-11-11T16:45:57.6832346Z 	at io.prestosql.execution.TestEventListener.assertFailedQuery(TestEventListener.java:235)
2020-11-11T16:45:57.6834519Z 	at io.prestosql.execution.TestEventListener.testPlanningFailure(TestEventListener.java:164)
2020-11-11T16:45:57.6839232Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-11-11T16:45:57.6846082Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-11-11T16:45:57.6854238Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-11-11T16:45:57.6860892Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-11-11T16:45:57.6869367Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-11-11T16:45:57.6876055Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-11-11T16:45:57.6881417Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-11-11T16:45:57.6886531Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-11-11T16:45:57.6892121Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-11-11T16:45:57.6897339Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-11-11T16:45:57.6904472Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-11-11T16:45:57.6912367Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-11-11T16:45:57.6917184Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by dain**
## Description

This is a new attempt at fixing #5922.  The new fix rewrites EventsCollector to collect events on a per query basis, which eliminates the concurrency issues of separating events from different queries.  This requires exposing the `QueryId` to results from `QueryRunner` executions including in exceptions.

## Related issues, pull requests, and links

* Fixes #5922

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java [hunk 1]
```diff
@@ -861,8 +859,8 @@ private MaterializedResultWithPlan executeInternal(Session session, @Language("S
             verify(builder.get() != null, "Output operator was not created");
             return new MaterializedResultWithPlan(session.getQueryId(), builder.get().build(), plan);
         }
-        catch (IOException e) {
-            throw new UncheckedIOException(e);
+        catch (Exception e) {
+            throw new QueryFailedException(session.getQueryId(), e.getMessage(), e);
```
Comment (losipiuk) [inline core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java:863]: this causes bunch of test failures.

File: testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java [hunk 2]
```diff
@@ -14,171 +14,174 @@
...
-                Predicate<QueryCompletedEvent> queryCompletedFilter,
-                Predicate<SplitCompletedEvent> splitCompletedFilter)
+        private synchronized void addQueryCreated(QueryCreatedEvent event)
         {
-            this.queryCreatedFilter = requireNonNull(queryCreatedFilter, "queryCreatedFilter is null");
-            this.queryCompletedFilter = requireNonNull(queryCompletedFilter, "queryCompletedFilter is null");
-            this.splitCompletedFilter = requireNonNull(splitCompletedFilter, "splitCompletedFilter is null");
+            if (queryCreatedEvent != null) {
+                RuntimeException exception = new RuntimeException("QueryCreateEvent already set");
+                exception.fillInStackTrace();
```
Comment (losipiuk) [inline testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java:99]: What would that change? It is called in constuctor already.

```java
    public static void main(String[] args)
    {
        RuntimeException e1 = new RuntimeException("e1");
        RuntimeException e2 = new RuntimeException("e2");
        e2.fillInStackTrace();

        e1.printStackTrace();
        e2.printStackTrace();
    }
```
produces same stacktrace for both exceptions.
```
java.lang.RuntimeException: e1
	at io.trino.execution.EventsCollector.main(EventsCollector.java:190)
java.lang.RuntimeException: e2
	at io.trino.execution.EventsCollector.main(EventsCollector.java:192)
```

File: testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java [hunk 3]
```diff
@@ -14,171 +14,174 @@
...
+            checkQueryCompleted();
         }
 
-        Predicate<QueryCreatedEvent> getQueryCreatedFilter()
+        private synchronized void addQueryCompleted(QueryCompletedEvent event)
         {
-            return queryCreatedFilter;
+            if (queryCompletedEvent != null) {
+                RuntimeException exception = new RuntimeException("QueryCompletedEvent already set");
+                exception.fillInStackTrace();
```
Comment (losipiuk) [inline testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java:111]: not needed?

**Review by losipiuk — APPROVED** [review]
LGTM

File: core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java (hunk 1 above)
Comment (dain) [reply core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java:863]: I figured that might be a problem.  I'll dig in more.

File: testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java [hunk 4]
```diff
@@ -14,171 +14,174 @@
...
+                failures.add(exception);
+                return;
+            }
+            queryCompletedEvent = event;
+            checkQueryCompleted();
         }
 
-        Predicate<QueryCompletedEvent> getQueryCompletedFilter()
+        private synchronized void checkQueryCompleted()
```
[the remark this answers is not in the document]
Comment (dain) [reply testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java:119]: It only marks the query as completed if the both start and end events have been received, so it is checking if the query is completed and only then marks it complete

[the remark this answers is not in the document]
Comment (dain) [reply testing/trino-tests/src/test/java/io/trino/execution/EventsCollector.java]: I just inline this since the logic is very simple

**Comment by dain** [comment]
I simplified this PR by not adding the new method to query runner since the logic is only needed with a `DistrbutedQueryRunner`.  This simplifies the exception change, because it is only needed in `DistrbutedQueryRunner` and it already wrapped exceptions in a RuntimeException.

**Review by electrum — APPROVED** [review]

**Review by losipiuk — APPROVED** [review]
