### PR TITLE
Fix: use parent project id in BigQuery session

### LINKED ISSUE #15867: BigQuery client using wrong project id when creating session
Hi all,

Updating from `403` to `405` when using BigQuery connector we are faced with the following error:

```
Query 20230124_184824_00005_h8n4u failed: io.grpc.StatusRuntimeException: PERMISSION_DENIED: request failed: the user does not have 'bigquery.readsessions.create' permission for 'projects/foobar'
```

This means that the project set in the BigQuery connector properties is being used as request project instead of the parent project.

If I'm not mistaken, this issue is due to https://github.com/trinodb/trino/pull/14961

### PR DESCRIPTION
**Pull request by regadas**
## Description

This issue appears when upgrading from `403` to `405`. 

BigQuery client session should use parent project id when creating a session. 

## Additional context and related issues

Fixes #15867

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by regadas** [comment]
Hello all! Just to let you know that I've sent the signed CLA.

**Comment by ebyhr** [comment]
@regadas Thanks for submitting CLA! The registration process will take a few days.

**Comment by martint** [comment]
@cla-bot check

**Comment by ebyhr** [comment]
/test-with-secrets sha=ae812f54d3ca68398d6733210bfe044bdc2a2c93

**Comment by ebyhr** [comment]
You can configure the code style with https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#code-style
```
Error:  src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:[21,1] (imports) ImportOrder: Wrong order for 'com.google.cloud.bigquery.BigQueryException' import.
```

File: plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java [hunk 1]
```diff
@@ -188,9 +216,14 @@ public TableInfo getCachedTable(Duration viewExpiration, TableInfo remoteTableId
         return materializationCache.getCachedTable(this, query, viewExpiration, remoteTableId);
     }
 
+    public String getParentProjectId()
```
Comment (ebyhr) [inline plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:219]: It worth adding comments to `getParentProjectId` & `getProjectId` methods for explaining the differences.

File: plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java [hunk 2]
```diff
@@ -188,9 +216,14 @@ public TableInfo getCachedTable(Duration viewExpiration, TableInfo remoteTableId
...
+    {
+        return this.parentProjectId;
```
Comment (ebyhr) [inline plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:221]: Remove redundant `this.`. Also, is it possible to use `bigQuery.getOptions().getProjectId()` instead?

File: plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java [hunk 3]
```diff
@@ -188,9 +216,14 @@ public TableInfo getCachedTable(Duration viewExpiration, TableInfo remoteTableId
...
+    }
+
     public String getProjectId()
     {
-        String projectId = configProjectId.orElseGet(() -> bigQuery.getOptions().getProjectId());
+        String projectId = configProjectId.orElseGet(this::getParentProjectId);
```
Comment (ebyhr) [inline plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:226]: Is this change required to fix the issue you faced? When does `bigQuery.getOptions().getProjectId()` return a different value from  `setProjectId(parentProjectId)` at L109?

**Review by ebyhr — COMMENTED** [review]
Please squash commits into one and follow this commit message guideline:
https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages

File: plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java (hunk 1 above)
Comment (regadas) [reply plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:219]: Hi @ebyhr thanks for taking a look. Yeah sounds good, I'll some comments there.

File: plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java (hunk 2 above)
Comment (regadas) [reply plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:221]: Yup, it's possible to use that instead and not assign a new `parentProjectId` variable.

File: plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java (hunk 3 above)
Comment (regadas) [reply plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:226]: It's not required to fix the issue, but I think it would bring meaning to what `bigQuery.getOptions().getProjectId()` inside that `orElseGet` really is and avoids dup.

**Comment by regadas** [comment]
@ebyhr can you take another look? Thanks for your time!

File: plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java [hunk 4]
```diff
@@ -82,20 +86,43 @@
...
+        // 1. Get from configuration
+        return configParentProjectId
+                // 2. Get from the provided credentials, but only ServiceAccountCredentials contains the project id.
+                // All other credentials types (User, AppEngine, GCE, CloudShell, etc.) take it from the environment
+                .orElseGet(() -> credentials
+                        .filter(ServiceAccountCredentials.class::isInstance)
+                        .map(ServiceAccountCredentials.class::cast)
+                        .map(ServiceAccountCredentials::getProjectId)
+                        // 3. No configuration was provided, so get the default from the environment
+                        .orElseGet(BigQueryOptions::getDefaultProjectId));
```
Comment (ebyhr) [inline plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:125]: It's a little hard to understand the actual change for a bug fix because this commit moves some methods. Could you move back the method or separate a commit?

Comment (regadas) [reply plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:125]: Yeah I'll split them; Can this one still make it to 408?

Comment (regadas) [reply plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:125]: [a6c1c23](https://github.com/trinodb/trino/pull/15868/commits/a6c1c231041a82863552729fd56d23c988303fb7) Relocating the BigQuery client logic under `BigQuery` wrapper makes a bit more sense to me, but if you prefer, we can scrap that and possibly move it to a separate PR.

Comment (ebyhr) [reply plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java:125]: It would be if you can separate a PR.

Comment (regadas) [reply plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java]: Fair enough. Done @ebyhr lmk if you need anything else.

**Comment by ebyhr** [comment]
/test-with-secrets sha=1ee572002ae8522c121f05e770cc1d499e2df058
