### PR TITLE
Fix Exasol flaky tests. Avoid exposing not required ports

### LINKED ISSUE #22698: Flaky Exasol connector CI
https://github.com/trinodb/trino/actions/runs/9965297128/job/27535676350?pr=22696

### PR DESCRIPTION
**Pull request by YotillaAntoni**
## Description

Fixes #22698.

The CI pipeline runs several tests that boot up an Exasol container, using `testcontainers`. An Exasol container by default exposes 4 ports for different services. Docker tries to allocate and map ephemeral ports. 

Due to an issue in docker, when it fails to allocate a port in can mess up with the process that was using this port (see https://github.com/moby/moby/pull/48132)

The issue only happens when more than one port is exported, so the fix is rather simple: we only export in the container the strictly needed port for JDBC: 8563

## Release notes

(X) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

File: plugin/trino-exasol/src/test/java/io/trino/plugin/exasol/TestingExasolServer.java [hunk 1]
```diff
@@ -47,7 +47,9 @@ public class TestingExasolServer
 
     public TestingExasolServer()
     {
-        container = new ExasolContainer<>("8.27.0").withRequiredServices(ExasolService.JDBC);
+        container = new ExasolContainer<>("8.32.0")
```
Comment (ebyhr) [inline plugin/trino-exasol/src/test/java/io/trino/plugin/exasol/TestingExasolServer.java:50]: Is this bump required to fix the flaky issue?

**Review by ebyhr — COMMENTED** [review]
Please run stress tests on CI likes #21480.

File: plugin/trino-exasol/src/test/java/io/trino/plugin/exasol/TestingExasolServer.java (hunk 1 above)
Comment (YotillaAntoni) [reply plugin/trino-exasol/src/test/java/io/trino/plugin/exasol/TestingExasolServer.java:50]: Is not strictly required

**Comment by YotillaAntoni** [comment]
Created PR for stress tests as requested: https://github.com/trinodb/trino/pull/24714
Test run succeeded https://github.com/trinodb/trino/actions/runs/12790671238

File: plugin/trino-exasol/src/test/java/io/trino/plugin/exasol/TestingExasolServer.java (hunk 1 above)
Comment (mosabua) [reply plugin/trino-exasol/src/test/java/io/trino/plugin/exasol/TestingExasolServer.java:50]: Lets do it anyway .. but in a separate commit.

**Review by ebyhr — APPROVED** [review]
