### PR TITLE
Include actual parameter types in ambiguous function call error

### LINKED ISSUE #28702: `Could not choose a best candidate operator` error should provide call site info to help user
When `Could not choose a best candidate operator. Explicit type casts must be added.` error is raised, Trino prints signatures of potential overloads for given operator or function.
It should also print the actual types at the call site to help the user choose which overload is best for them.

This situation is already tested here:
https://github.com/trinodb/trino/blob/6c0129d1a0b52a73f7772c80f6691f400e45cfd8/core/trino-main/src/test/java/io/trino/metadata/TestGlobalFunctionCatalog.java#L179

In the test, the actual exception lacks information about actual types:

```
io.trino.spi.TrinoException: Could not choose a best candidate operator. Explicit type casts must be added.
Candidates are:
	 * (decimal(19,0),double):boolean
	 * (double,decimal(19,0)):boolean

	at io.trino.metadata.FunctionBinder.matchFunction(FunctionBinder.java:176)
	at io.trino.metadata.FunctionBinder.matchFunctionWithCoercion(FunctionBinder.java:148)
	at io.trino.metadata.FunctionBinder.tryBindFunction(FunctionBinder.java:96)
	at io.trino.metadata.FunctionBinder.bindFunction(FunctionBinder.java:69)
	at io.trino.metadata.BuiltinFunctionResolver.lambda$resolveBuiltinFunction$0(BuiltinFunctionResolver.java:79)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4859)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3556)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2307)
```

### PR DESCRIPTION
**Pull request by Bingtagui404**
Fixes #28702.

## Description

When `Could not choose a best candidate operator. Explicit type casts must be added.` error is raised, the error message now includes the actual parameter types at the call site.

### Before

```
Could not choose a best candidate operator. Explicit type casts must be added.
Candidates are:
	 * (decimal(19,0),double):boolean
	 * (double,decimal(19,0)):boolean
```

### After

```
Could not choose a best candidate operator. Explicit type casts must be added.
Actual types: (bigint, bigint)
Candidates are:
	 * (decimal(19,0),double):boolean
	 * (double,decimal(19,0)):boolean
```

This helps users understand which explicit cast to add by showing the types they actually passed.

## Changes

- **`FunctionBinder.java`**: Added `Actual types: (...)` line to the error message in `matchFunction()`, using `Joiner.on(", ").join(parameters)` which is consistent with how `functionNotFound()` already formats parameter types.
- **`TestGlobalFunctionCatalog.java`**: Updated two `failsWithMessage` assertions to verify the new `Actual types` information is present.

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/metadata/FunctionBinder.java [hunk 1]
```diff
@@ -167,6 +167,9 @@ private Optional<CatalogFunctionBinding> matchFunction(Collection<CatalogFunctio
 
         StringBuilder errorMessageBuilder = new StringBuilder();
         errorMessageBuilder.append("Could not choose a best candidate operator. Explicit type casts must be added.\n");
+        errorMessageBuilder.append("Actual types: (");
+        errorMessageBuilder.append(Joiner.on(", ").join(parameters));
```
Comment (electrum) [inline core/trino-main/src/main/java/io/trino/metadata/FunctionBinder.java]:
```suggestion
        Joiner.on(", ").appendTo(errorMessageBuilder, parameters);
```

File: core/trino-main/src/test/java/io/trino/metadata/TestGlobalFunctionCatalog.java [hunk 2]
```diff
@@ -176,7 +176,7 @@ public void testAmbiguousCallWithCoercion()
                         functionSignature("decimal(p,s)", "double"),
                         functionSignature("double", "decimal(p,s)"))
                 .forParameters(BIGINT, BIGINT)
-                .failsWithMessage("Could not choose a best candidate operator. Explicit type casts must be added.");
+                .failsWithMessage("Could not choose a best candidate operator. Explicit type casts must be added.", "Actual types: (bigint, bigint)");
```
Comment (electrum) [inline core/trino-main/src/test/java/io/trino/metadata/TestGlobalFunctionCatalog.java]: I checked and we currently don't have any tests that assert the full error message. Can you change `failsWithMessage()` to take a single `String` and have it call `hasMessage()` rather than `hasMessageContainingAll()`?

Then you can use a text block here to verify the exact message.

```suggestion
                .failsWithMessage(
                        """
                        Could not choose a best candidate operator. Explicit type casts must be added.
                        Actual types: (bigint, bigint)
                        Candidates are:
                        \t * (decimal(19,0),double):boolean
                        \t * (double,decimal(19,0)):boolean
                        """);
```

**Comment by Bingtagui404** [comment]
@cla-bot I have sent CLA , thank u~

**Comment by Bingtagui404** [comment]
CI failures in `test (plugin/trino-cassandra)` and `test (plugin/trino-postgresql)` appear to be pre-existing flaky tests unrelated to this change — the `TestPostgreSqlRollbacks.testRollbackCreateTableAsSelect` failure matches #28729 which was filed today. The `test (core/trino-main)` job that covers our changes passed.

**Comment by wendigo** [comment]
Please squash all commits together into a single one.

**Comment by Bingtagui404** [comment]
Done, squashed into a single commit and rebased onto latest master.

**Comment by wendigo** [comment]
@cla-bot check

**Comment by wendigo** [comment]
(rebasing after recent changes)
