### PR TITLE
Fix failure when querying optimizer_rule_stats system table

### LINKED ISSUE #8700: Unable to query optimizer_rule_stats table
Attempting to query the `system.runtime.optimizer_rule_stats` table results in the following error:

```
trino:runtime> select * from optimizer_rule_stats;
Query 20210728_202457_00005_9rmqb failed: Rule stats system table can return results only on coordinator
java.lang.IllegalStateException: Rule stats system table can return results only on coordinator
	at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
	at io.trino.connector.system.RuleStatsSystemTable.pageSource(RuleStatsSystemTable.java:86)
	at io.trino.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:105)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:306)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_359____20210728_202230_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

trino:runtime>
```

I have tried querying this table in multiple clusters I have access to and tried with `node-scheduler.include-coordinator` set to both `true` and `false` but no luck.

I've tested with 356 and 359 and have hit the same issue on both versions.

### PR DESCRIPTION
**Pull request by martint**
RuleStatsRecorder was being constructed directly inside PlanOptimizers
instead of being injected and made available also to RuleStatsSystemTable.

Fixes https://github.com/trinodb/trino/issues/8700

### CODE REVIEW

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/TestSystemConnector.java [hunk 1]
```diff
@@ -37,6 +37,14 @@ public void selectRuntimeNodes()
                 .hasAnyRows();
     }
 
+    @Test
+    public void testRuleStats()
+    {
+        assertThat(query("SELECT rule_name, invocations, matches, failures FROM system.runtime.rule_stats"))
```
Comment (phd3) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/TestSystemConnector.java:43]: optimizer_rule_stats
```
tests               | 2021-09-14 07:27:55 INFO: SUCCESS     /    io.trino.tests.product.TestSystemConnector.selectRuntimeTasks (Groups: system, jdbc) took 0.4 seconds
tests               | 2021-09-14 07:27:55 INFO: [387 of 617] io.trino.tests.product.TestSystemConnector.testRuleStats (Groups: )
presto-master       | 2021-09-14T07:27:55.751+0545	INFO	dispatcher-query-439	io.trino.event.QueryMonitor	TIMELINE: Query 20210914_014255_03181_jbp5w :: Transaction:[74b9fed1-a01d-4cdf-af1f-e944d642c300] :: elapsed 0ms :: planning 0ms :: waiting 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2021-09-14T07:27:55.750+05:45 :: end 2021-09-14T07:27:55.750+05:45
tests               | 2021-09-14 07:27:55 INFO: not retrying; @Flaky annotation not present
tests               | 2021-09-14 07:27:55 INFO: FAILURE     /    io.trino.tests.product.TestSystemConnector.testRuleStats (Groups: ) took 0.0 seconds
tests               | 2021-09-14 07:27:55 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20210914_014255_03181_jbp5w): line 1:55: Table 'system.runtime.rule_stats' does not exist
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
tests               | 	at io.trino.tests.product.TestSystemConnector.testRuleStats(TestSystemConnector.java:43)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tests               | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
tests               | Caused by: java.sql.SQLException: Query failed (#20210914_014255_03181_jbp5w): line 1:55: Table 'system.runtime.rule_stats' does not exist
tests               | 	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1912)
tests               | 	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:243)
tests               | 	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:53)
tests               | 	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
tests               | 	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	... 16 more
tests               | 	Suppressed: java.lang.Exception: Query: SELECT rule_name, invocations, matches, failures FROM system.runtime.rule_stats
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		... 17 more
tests               | Caused by: io.trino.spi.TrinoException: line 1:55: Table 'system.runtime.rule_stats' does not exist
tests               | 	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
tests               | 	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1342)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:360)
tests               | 	at io.trino.sql.tree.Table.accept(Table.java:53)
tests               | 	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3185)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1955)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:360)
tests               | 	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
tests               | 	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:387)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1169)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:360)
tests               | 	at io.trino.sql.tree.Query.accept(Query.java:107)
tests               | 	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
tests               | 	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:340)
tests               | 	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
tests               | 	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
tests               | 	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
tests               | 	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
tests               | 	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
tests               | 	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
tests               | 	at io.trino.$gen.Trino_1f53dbc____20210914_005530_2.call(Unknown Source)
tests               | 	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
tests               | 	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
tests               | 	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
tests               | 
```

File: core/trino-main/src/main/java/io/trino/connector/system/RuleStatsSystemTable.java [hunk 2]
```diff
@@ -50,10 +48,10 @@
 {
     private static final SchemaTableName TABLE_NAME = new SchemaTableName("runtime", "optimizer_rule_stats");
     private final ConnectorTableMetadata ruleStatsTable;
-    private final Optional<RuleStatsRecorder> ruleStatsRecorder;
+    private final RuleStatsRecorder ruleStatsRecorder;
 
     @Inject
-    public RuleStatsSystemTable(Optional<RuleStatsRecorder> ruleStatsRecorder, Metadata metadata)
```
Comment (phd3) [inline core/trino-main/src/main/java/io/trino/connector/system/RuleStatsSystemTable.java:56]: Q: was this coming up empty even after singleton binding because another instance already existed?

Comment (martint) [reply core/trino-main/src/main/java/io/trino/connector/system/RuleStatsSystemTable.java:56]: No, I didn't try that, but I see it works. So let me add that and revert this part of the change.

**Comment by martint** [comment]
@phd, updated

**Comment by phd** [comment]
> @phd, updated

@phd3

**Review by phd3 — APPROVED** [review]
