### PR TITLE
Fix failure when executing `date_add` function with larger value

### LINKED ISSUE #27899: Integer overflow in `date_add('millisecond', ..., ...)`
# Problem

If you add more than `Integer.MAX_VALUE` milliseconds to a timestamp using `date_add()` Trino throws an exception with "Integer Overflow"

# How to reproduce

`select date_add('millisecond', 2147483648, current_timestamp);`

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #27899

## Release notes

```markdown
## General
* Fix failure when executing `date_add` function with larger value. ({issue}`27899`)
```

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java [hunk 1]
```diff
@@ -311,8 +311,13 @@ public static long truncateDate(@SqlType("varchar(x)") Slice unit, @SqlType(Stan
     @SqlType(StandardTypes.DATE)
     public static long addFieldValueDate(@SqlType("varchar(x)") Slice unit, @SqlType(StandardTypes.BIGINT) long value, @SqlType(StandardTypes.DATE) long date)
     {
-        long millis = getDateField(UTC_CHRONOLOGY, unit).add(DAYS.toMillis(date), toIntExact(value));
-        return MILLISECONDS.toDays(millis);
+        try {
+            long millis = getDateField(UTC_CHRONOLOGY, unit).add(DAYS.toMillis(date), toIntExact(value));
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java]: We could drop `toIntExact` here, couldn't we?

File: core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/TestTimestamp.java [hunk 2]
```diff
@@ -2863,6 +2863,50 @@ public void testDateAdd()
         assertThat(assertions.expression("date_add('year', 4, TIMESTAMP '2001-09-10 13:31:00.11111111111')")).matches("TIMESTAMP '2005-09-10 13:31:00.11111111111'");
         assertThat(assertions.expression("date_add('year', 4, TIMESTAMP '2001-09-10 13:31:00.111111111111')")).matches("TIMESTAMP '2005-09-10 13:31:00.111111111111'");
 
+        // Test large value addition
+        long value = 30L * 24 * 60 * 60 * 1000;
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/TestTimestamp.java]:
```suggestion
        // Test addition of a large value (exceeding max integer)
        long value = 30L * 24 * 60 * 60 * 1000;
        checkState(value > Integer.MAX_VALUE);
```

**Review by chenjian2664 — APPROVED** [review]
