### PR TITLE
Fix flaky TestPrometheusIntegrationStatus.testPushDown 

### LINKED ISSUE #7224: Flaky TestPrometheusIntegrationStatus
```
2021-03-08T15:20:03.9011321Z [ERROR] testPushDown(io.trino.plugin.prometheus.TestPrometheusIntegrationStatus)  Time elapsed: 1.082 s  <<< FAILURE!
2021-03-08T15:20:03.9019429Z java.lang.AssertionError: expected [1] but found [2]
2021-03-08T15:20:03.9025167Z 	at org.testng.Assert.fail(Assert.java:94)
2021-03-08T15:20:03.9031490Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2021-03-08T15:20:03.9038117Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
2021-03-08T15:20:03.9044465Z 	at org.testng.Assert.assertEquals(Assert.java:116)
2021-03-08T15:20:03.9050460Z 	at org.testng.Assert.assertEquals(Assert.java:389)
2021-03-08T15:20:03.9058062Z 	at org.testng.Assert.assertEquals(Assert.java:399)
2021-03-08T15:20:03.9073867Z 	at io.trino.plugin.prometheus.TestPrometheusIntegrationStatus.testPushDown(TestPrometheusIntegrationStatus.java:105)
2021-03-08T15:20:03.9087700Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-03-08T15:20:03.9101487Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-03-08T15:20:03.9114944Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-03-08T15:20:03.9122900Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-03-08T15:20:03.9132952Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-03-08T15:20:03.9141695Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-03-08T15:20:03.9150916Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-03-08T15:20:03.9160411Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-03-08T15:20:03.9170980Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-03-08T15:20:03.9181383Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-03-08T15:20:03.9211857Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-03-08T15:20:03.9227356Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-03-08T15:20:03.9235616Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #7224

### CODE REVIEW

**Comment by ebyhr** [comment]
CI
* #10752

File: plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationStatus.java [hunk 1]
```diff
@@ -100,8 +102,8 @@ public void testConfirmMetricAvailableAndCheckUp()
     @Test
     public void testPushDown()
     {
-        // default interval on the `up` metric that Prometheus records on itself is 15 seconds, so this should only yield one row
+        // default interval on the `up` metric that Prometheus records on itself is about 15 seconds, so this should only yield one or two row
         MaterializedResult results = computeActual("SELECT * FROM prometheus.default.up WHERE timestamp > (NOW() - INTERVAL '15' SECOND)");
```
Comment (hashhar) [inline plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationStatus.java:106]: Can we instead create a timestamp literal in Java side and then send that as the predicate.
In the MaterializedResult then we can assert that all rows have a timestamp > the predicate (instead of counting number of rows which is inherently flaky).

Comment (hashhar) [reply plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationStatus.java:106]: Also if we want to test pushdown happenned we should assert on the plan. Since even without pushdown the engine will filter results and we'll get filtered rows.

It's pre-existing issue though.

Comment (ebyhr) [reply plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationStatus.java:106]: Let me punt to #10784

**Review by hashhar — APPROVED** [review]

File: plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationStatus.java (hunk 1 above)
Comment (hashhar) [reply plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationStatus.java:106]: Do we have some stress test results somewhere? LGTM.

Comment (ebyhr) [reply plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationStatus.java:106]: Tested locally because the failure ratio was very low (1 / 500 attempts) in my laptop. Verified 2000 passes with this fix.
