### PR TITLE
Make Iceberg to Spark compatibility tests more resilient to retries

### LINKED ISSUE #21304: TestIcebergSparkCompatibility.testRegisterTableWithShowCreateTable flaky
```
2024-03-28 15:16:37 INFO: FAILURE     /    io.trino.tests.product.iceberg.TestIcebergSparkCompatibility.testRegisterTableWithShowCreateTable [AVRO] (Groups: profile_specific_tests, iceberg) took 3.1 seconds
tests               | 2024-03-28 15:16:37 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20240328_093137_00698_eqax2): More than one latest metadata file found at location: hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5/metadata, latest metadata files are [hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5/metadata/00002-d126c010-497c-4820-a1b7-503fe8e77b05.metadata.json, hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5/metadata/00002-dc5c8fa5-67a8-42d4-8675-87c57c83c726.metadata.json]
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:54)
tests               | 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:54)
tests               | 	at io.trino.tests.product.iceberg.TestIcebergSparkCompatibility.testRegisterTableWithShowCreateTable(TestIcebergSparkCompatibility.java:2592)
tests               | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:1583)
tests               | Caused by: java.sql.SQLException: Query failed (#20240328_093137_00698_eqax2): More than one latest metadata file found at location: hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5/metadata, latest metadata files are [hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5/metadata/00002-d126c010-497c-4820-a1b7-503fe8e77b05.metadata.json, hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5/metadata/00002-dc5c8fa5-67a8-42d4-8675-87c57c83c726.metadata.json]
tests               | 	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
tests               | 	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:294)
tests               | 	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:254)
tests               | 	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
tests               | 	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
tests               | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1949)
tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:292)
tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
tests               | 	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
tests               | 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:298)
tests               | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
tests               | 	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:179)
tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
tests               | 	... 3 more
tests               | 	Suppressed: java.lang.Exception: Query: CALL iceberg.system.register_table ('default', 'test_register_table_with_show_create_table_avro_4pej3h6lg5', 'hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5')
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 		at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:54)
tests               | 		at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
tests               | 		at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
tests               | 		at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
tests               | 		at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
tests               | 		at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
tests               | 		at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
tests               | 		at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:54)
tests               | 		at io.trino.tests.product.iceberg.TestIcebergSparkCompatibility.testRegisterTableWithShowCreateTable(TestIcebergSparkCompatibility.java:2592)
tests               | 		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
tests               | 		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
tests               | 		at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 		at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 		at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 		at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 		at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 		at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 		... 3 more
tests               | Caused by: io.trino.spi.TrinoException: More than one latest metadata file found at location: hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5/metadata, latest metadata files are [hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5/metadata/00002-d126c010-497c-4820-a1b7-503fe8e77b05.metadata.json, hdfs://hadoop-master:9000/user/hive/warehouse/test_register_table_with_show_create_table_avro_4pej3h6lg5/metadata/00002-dc5c8fa5-67a8-42d4-8675-87c57c83c726.metadata.json]
tests               | 	at io.trino.plugin.iceberg.IcebergUtil.getLatestMetadataLocation(IcebergUtil.java:895)
tests               | 	at io.trino.plugin.iceberg.procedure.RegisterTableProcedure.lambda$getMetadataLocation$1(RegisterTableProcedure.java:174)
tests               | 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
tests               | 	at io.trino.plugin.iceberg.procedure.RegisterTableProcedure.getMetadataLocation(RegisterTableProcedure.java:174)
tests               | 	at io.trino.plugin.iceberg.procedure.RegisterTableProcedure.doRegisterTable(RegisterTableProcedure.java:139)
tests               | 	at io.trino.plugin.iceberg.procedure.RegisterTableProcedure.registerTable(RegisterTableProcedure.java:108)
tests               | 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
tests               | 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:758)
tests               | 	at io.trino.execution.CallTask.execute(CallTask.java:210)
tests               | 	at io.trino.execution.CallTask.execute(CallTask.java:70)
tests               | 	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:146)
tests               | 	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
tests               | 	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
tests               | 	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
tests               | 	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
tests               | 	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
tests               | 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
tests               | 	at io.trino.$gen.Trino_76c956e____20240328_092351_2.run(Unknown Source)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:1583)
tests               | 
```

cc: @findinpath

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

Fixes #21304

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java [hunk 1]
```diff
@@ -2523,8 +2524,10 @@ public void testRegisterTableWithTableLocation(StorageFormat storageFormat)
         String sparkTableName = sparkTableName(baseTableName);
 
         onSpark().executeQuery(format("CREATE TABLE %s (a INT, b STRING, c BOOLEAN) USING ICEBERG TBLPROPERTIES ('write.format.default' = '%s')", sparkTableName, storageFormat));
+        // Run both inserts on Spark; When an insert on Trino fails and is retried, it creates a second metadata file with same sequence number in the filename,
+        // and register_table would detect this ambiguity and fail.
```
Comment (hashhar) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2528]: isn't this a bug then? Customers would hit this too I guess.

Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2528]: I think it's specific test? `onTrino()` retries if the exception matches the following condition:
https://github.com/trinodb/trino/blob/79529a769671996fe13ecab022433f603b7703dd/testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/HadoopTestUtils.java#L42-L50

Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2528]: I'm not sure why changing to `onSpark()` resolves the flaky issue. The method also contains the same retry logic.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java [hunk 2]
```diff
@@ -2523,8 +2524,10 @@ public void testRegisterTableWithTableLocation(StorageFormat storageFormat)
...
         onSpark().executeQuery(format("INSERT INTO %s values(1, 'INDIA', true)", sparkTableName));
-        onTrino().executeQuery(format("INSERT INTO %s values(2, 'USA', false)", trinoTableName));
+        onSpark().executeQuery(format("INSERT INTO %s values(2, 'USA', false)", trinoTableName));
```
Comment (ebyhr) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2530]: trinoTableName should be sparkTableName. 

Also, just removing this line might be acceptable. Assuming the test purpose is registering a table created by Spark.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java [hunk 3]
```diff
@@ -2555,10 +2558,11 @@ public void testRegisterTableWithComments(StorageFormat storageFormat)
         onTrino().executeQuery(format("COMMENT ON COLUMN %s.c is 'c-comment'", trinoTableName));
 
         String tableLocation = getTableLocation(trinoTableName);
+        String metadataLocation = getLatestMetadataLocation(trinoTableName);
         // Drop table from hive metastore and use the same table name to register again with the metadata
         dropTableFromMetastore(baseTableName);
 
-        onTrino().executeQuery(format("CALL iceberg.system.register_table ('%s', '%s', '%s')", TEST_SCHEMA_NAME, baseTableName, tableLocation));
+        onTrino().executeQuery(format("CALL iceberg.system.register_table ('%s', '%s', '%s', '%s')", TEST_SCHEMA_NAME, baseTableName, tableLocation, metadataLocation));
```
Comment (findinpath) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2565]: pls leave the test as it was initially.

we should maybe use $metadata_log_entries to get the latest metadata file to be used in `register_table` to avoid ambiguities https://github.com/trinodb/trino/pull/20410

**Comment by findinpath** [comment]
The failure below seems related to your changes: https://github.com/trinodb/trino/actions/runs/8520349910/job/23336628885?pr=21310

```
2024-04-02T09:29:48.1315619Z tests               | 2024-04-02 15:14:48 SEVERE: Failure cause:
2024-04-02T09:29:48.1318417Z tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20240402_092948_00559_2drgq): line 1:18: Table 'hive.default."iceberg.default.test_register_table_with_comments_parquet_vwe36pl231$metadata_log_entries"' does not exist
2024-04-02T09:29:48.1321163Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
2024-04-02T09:29:48.1322674Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2024-04-02T09:29:48.1324276Z tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.lambda$executeQuery$0(QueryExecutors.java:54)
2024-04-02T09:29:48.1325739Z tests               | 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
2024-04-02T09:29:48.1326884Z tests               | 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
2024-04-02T09:29:48.1328219Z tests               | 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
2024-04-02T09:29:48.1330073Z tests               | 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
2024-04-02T09:29:48.1331374Z tests               | 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
2024-04-02T09:29:48.1332978Z tests               | 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
2024-04-02T09:29:48.1334485Z tests               | 	at io.trino.tests.product.utils.QueryExecutors$1.executeQuery(QueryExecutors.java:54)
2024-04-02T09:29:48.1336308Z tests               | 	at io.trino.tests.product.iceberg.util.IcebergTestUtils.getLatestMetadataLocation(IcebergTestUtils.java:31)
2024-04-02T09:29:48.1338689Z tests               | 	at io.trino.tests.product.iceberg.TestIcebergSparkCompatibility.testRegisterTableWithComments(TestIcebergSparkCompatibility.java:2561)
2024-04-02T09:29:48.1402952Z tests               | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2024-04-02T09:29:48.1404500Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-04-02T09:29:48.1408753Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2024-04-02T09:29:48.1410267Z tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2024-04-02T09:29:48.1411458Z tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2024-04-02T09:29:48.1412705Z tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2024-04-02T09:29:48.1414115Z tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2024-04-02T09:29:48.1415543Z tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2024-04-02T09:29:48.1417037Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-04-02T09:29:48.1418686Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-04-02T09:29:48.1420614Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:1570)
2024-04-02T09:29:48.1423162Z tests               | Caused by: java.sql.SQLException: Query failed (#20240402_092948_00559_2drgq): line 1:18: Table 'hive.default."iceberg.default.test_register_table_with_comments_parquet_vwe36pl231$metadata_log_entries"' does not exist
2024-04-02T09:29:48.1425765Z tests               | 	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
2024-04-02T09:29:48.1427225Z tests               | 	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:318)
2024-04-02T09:29:48.1429139Z tests               | 	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:61)
2024-04-02T09:29:48.1430442Z tests               | 	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
2024-04-02T09:29:48.1431699Z tests               | 	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
2024-04-02T09:29:48.1433471Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
2024-04-02T09:29:48.1435100Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
2024-04-02T09:29:48.1436096Z tests               | 	... 22 more
2024-04-02T09:29:48.1437885Z tests               | 	Suppressed: java.lang.Exception: Query: SELECT file FROM "iceberg.default.test_register_table_with_comments_parquet_vwe36pl231$metadata_log_entries" ORDER BY latest_sequence_number DESC LIMIT 1
2024-04-02T09:29:48.1440252Z tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
2024-04-02T09:29:48.1441401Z tests               | 		... 23 more
```

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java (hunk 1 above)
Comment (nineinchnick) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2528]: I'm hoping it either won't fail or won't create metadata files with the same version number in the name. I don't know why Trino does this.

If users hit this, they can do the same workaround - call `register_table()` with specifying the metadata file.

**Comment by nineinchnick** [comment]
@findinpath fixed

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java [hunk 4]
```diff
@@ -2523,8 +2524,10 @@ public void testRegisterTableWithTableLocation(StorageFormat storageFormat)
         String sparkTableName = sparkTableName(baseTableName);
 
         onSpark().executeQuery(format("CREATE TABLE %s (a INT, b STRING, c BOOLEAN) USING ICEBERG TBLPROPERTIES ('write.format.default' = '%s')", sparkTableName, storageFormat));
+        // Run both inserts on Spark; When an insert on Trino fails and is retried, it creates a second metadata file with same sequence number in the filename,
+        // and register_table would detect this ambiguity and fail.
         onSpark().executeQuery(format("INSERT INTO %s values(1, 'INDIA', true)", sparkTableName));
-        onTrino().executeQuery(format("INSERT INTO %s values(2, 'USA', false)", trinoTableName));
+        onSpark().executeQuery(format("INSERT INTO %s values(2, 'USA', false)", sparkTableName));
```
Comment (findinpath) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2530]: Is this still needed now?

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java [hunk 5]
```diff
@@ -2637,13 +2643,14 @@ public void testRegisterTableWithDroppedTable(StorageFormat storageFormat)
...
         String tableLocation = getTableLocation(trinoTableName);
+        String metadataLocation = getLatestMetadataLocation(TRINO_CATALOG, TEST_SCHEMA_NAME, baseTableName);
         String baseTableNameNew = baseTableName + "_new";
 
         // Drop table to verify register_table call fails when no metadata can be found (table doesn't exist)
         onTrino().executeQuery(format("DROP TABLE %s", trinoTableName));
 
-        assertQueryFailure(() -> onTrino().executeQuery(format("CALL iceberg.system.register_table ('%s', '%s', '%s')", TEST_SCHEMA_NAME, baseTableNameNew, tableLocation)))
-                .hasMessageMatching(".*No versioned metadata file exists at location.*");
+        assertQueryFailure(() -> onTrino().executeQuery(format("CALL iceberg.system.register_table ('%s', '%s', '%s', '%s')", TEST_SCHEMA_NAME, baseTableNameNew, tableLocation, metadataLocation)))
```
Comment (findinpath) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2652]: This change is not necessary in the context of this PR.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java (hunk 4 above)
Comment (nineinchnick) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2530]: We test register_table without specifying the metadata file here so we want to avoid retries in Trino

**Review by findinpath — COMMENTED** [review]
Almost there. A few nits still needed.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java (hunk 4 above)
Comment (findinpath) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2530]: > We test register_table without specifying the metadata file here

It seems to me that we do use the metadata file: 

```
onTrino().executeQuery(format("CALL iceberg.system.register_table ('%s', '%s', '%s', '%s')", TEST_SCHEMA_NAME, baseTableName, tableLocation, metadataLocation));
```

Comment (nineinchnick) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2530]: Are we ok with loosing test coverage then?

Comment (nineinchnick) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java]: I reverted changes here.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java [hunk 6]
```diff
@@ -2528,10 +2529,11 @@ public void testRegisterTableWithTableLocation(StorageFormat storageFormat)
 
         List<Row> expected = List.of(row(1, "INDIA", true), row(2, "USA", false));
         String tableLocation = getTableLocation(trinoTableName);
+        String metadataLocation = getLatestMetadataLocation(TRINO_CATALOG, TEST_SCHEMA_NAME, baseTableName);
         // Drop table from hive metastore and use the same table name to register again with the metadata
         dropTableFromMetastore(baseTableName);
 
-        onTrino().executeQuery(format("CALL iceberg.system.register_table ('%s', '%s', '%s')", TEST_SCHEMA_NAME, baseTableName, tableLocation));
+        onTrino().executeQuery(format("CALL iceberg.system.register_table ('%s', '%s', '%s', '%s')", TEST_SCHEMA_NAME, baseTableName, tableLocation, metadataLocation));
```
Comment (ebyhr) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java:2536]: The test name is `testRegisterTableWithTableLocation` and we have `testRegisterTableWithMetadataFile`. Specifying metadata file name in this test looks weird to me.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/util/IcebergTestUtils.java [hunk 7]
```diff
@@ -26,6 +26,11 @@ public static String getTableLocation(String tableName)
         return (String) onTrino().executeQuery("SELECT DISTINCT regexp_replace(\"$path\", '/[^/]*/[^/]*$', '') FROM " + tableName).getOnlyValue();
     }
 
+    public static String getLatestMetadataLocation(String catalog, String schema, String tableName)
```
Comment (ebyhr) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/util/IcebergTestUtils.java:29]: This method returns metadata file name, right? I would rename to `getLatestMetadataFileName` or something.

Comment (nineinchnick) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/util/IcebergTestUtils.java]: Done!

**Review by findinpath — APPROVED** [review]
