### PR TITLE
Fix case sensitivity issue of MongoDB view

### LINKED ISSUE #7491: mongodb select * on view returns error CommandNotSupportedOnView
Any Idea why a select * on a mongodb view results in this error:
```
SQL-Fehler [65536]: Query failed (#20210403_015848_00023_3siug): com.mongodb.MongoCommandException: 
Command failed with error 166 (CommandNotSupportedOnView): 'Namespace enioSites.enrichedSites is a view,
 not a collection' on server host.docker.internal:27117.
 The full response is 
```
```json
{
  "operationTime": {
    "$timestamp": {
      "t": 1617453002,
      "i": 1
    }
  },
  "ok": 0,
  "errmsg": "Namespace enioSites.enrichedSites is a view, not a collection",
  "code": 166,
  "codeName": "CommandNotSupportedOnView",
  "$clusterTime": {
    "clusterTime": {
      "$timestamp": {
        "t": 1617453002,
        "i": 1
      }
    },
    "signature": {
      "hash": {
        "$binary": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=",
        "$type": "00"
      },
      "keyId": {
        "$numberLong": "0"
      }
    }
  }
}
```

Thanks
Ognian

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #7491

### CODE REVIEW

File: plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java [hunk 1]
```diff
@@ -432,7 +433,7 @@ private Document getTableMetadata(SchemaTableName schemaTableName)
 
         if (doc == null) {
             if (!collectionExists(db, tableName)) {
-                throw new TableNotFoundException(schemaTableName);
+                throw new TableNotFoundException(new SchemaTableName(schemaName, tableName));
```
Comment (findepi) [inline plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java:436]: This will lowercase `schemaName, tableName`. Let's pass actual names (case-preserving) with some `String message` message

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java [hunk 2]
```diff
@@ -325,6 +325,34 @@ public void testCaseInsensitive()
         assertUpdate("DROP TABLE testcase.testinsensitive");
     }
 
+    @Test
+    public void testCaseInsensitiveView()
```
Comment (findepi) [inline plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java:329]: testNonLowercaseViewName

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java [hunk 3]
```diff
@@ -325,6 +325,34 @@ public void testCaseInsensitive()
...
+    {
+        // Case insensitive schema name
+        MongoCollection<Document> collection = client.getDatabase("testInsensitive").getCollection("test_collection");
```
Comment (findepi) [inline plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java:332]: testInsensitive -> eg NonLowercaseSchema

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java [hunk 4]
```diff
@@ -325,6 +325,34 @@ public void testCaseInsensitive()
...
+        collection.insertOne(new Document(ImmutableMap.of("Name", "abc", "Value", 1)));
+
+        client.getDatabase("testInsensitive").createView("test_view", "test_collection", ImmutableList.of());
+        assertQuery("SELECT value FROM testinsensitive.test_view WHERE name = 'abc'", "SELECT 1");
+
+        // Case insensitive view name
+        collection = client.getDatabase("test_database").getCollection("test_collection");
+        collection.insertOne(new Document(ImmutableMap.of("Name", "abc", "Value", 1)));
+
+        client.getDatabase("test_database").createView("testInsensitive", "test_collection", ImmutableList.of());
```
Comment (findepi) [inline plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java:342]: testInsensitive -> eg NonLowercaseView

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java [hunk 5]
```diff
@@ -325,6 +325,34 @@ public void testCaseInsensitive()
...
+    public void testNonLowercaseViewName()
+    {
+        // Case insensitive schema name
+        MongoCollection<Document> collection = client.getDatabase("NonLowercaseSchema").getCollection("test_collection");
+        collection.insertOne(new Document(ImmutableMap.of("Name", "abc", "Value", 1)));
+
+        client.getDatabase("NonLowercaseSchema").createView("lowercase_view", "test_collection", ImmutableList.of());
+        assertQuery("SELECT value FROM nonlowercaseschema.lowercase_view WHERE name = 'abc'", "SELECT 1");
+
+        // Case insensitive view name
```
Comment (hashhar) [inline plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java:338]: nit: This comment is misleading. The view name is already lowercase.

**Review by hashhar — APPROVED** [review]
LGTM % nits.

The commit message could be `Fix handling/querying of non-lowercase MongoDB views`.

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java (hunk 5 above)
Comment (ebyhr) [reply plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java:338]: I think it's not lowercase or am I missing something? 

L342 `... createView("NonLowercaseView" ...`

Comment (hashhar) [reply plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java:338]: Sorry, I was looking at the collection name. Thanks. 😄
