### PR TITLE
Fix an issue in InlineProjections that may cause query failure when multiple column masks exist on a table

### LINKED ISSUE #10370: Query fails while masking table columns with different schema order
etc/access_control-rules.json
```
{
  "tables": [
    {
      "catalog": "hive",
      "schema": "temp",
      "table": "test_mask_(good|bad)",
      "columns": [
        {
          "name": "payload",
          "mask": "payload||''"
        },
        {
          "name": "col1",
          "mask": "if(json_extract_scalar(payload,'$.attr') IN ('a'), '***', col1)"
        },
        {
          "name": "col2",
          "mask": "if(json_extract_scalar(payload,'$.attr') IN ('a') or json_extract_scalar(payload,'$.attr') IN ('b'), '***', col2)"
        }
      ],
      "privileges": [
        "SELECT"
      ]
    }
  ]
}
```

**GOOD:**
```
CREATE TABLE temp.test_mask_good(col1 varchar, col2 varchar, payload varchar);

EXPLAIN SELECT col1, col2 from temp.test_mask_good;

Fragment 0 [SINGLE]
    Output layout: [col1, col2]
    Output partitioning: SINGLE []
    Stage Execution Strategy: UNGROUPED_EXECUTION
    Output[col1, col2]
    │   Layout: [col1:varchar, col2:varchar]
    │   Estimates: {rows: 0 (0B), cpu: 0, memory: 0B, network: 0B}
    └─ RemoteSource[1]
           Layout: [col2:varchar, col1:varchar]

Fragment 1 [SOURCE]
    Output layout: [col2, col1]
    Output partitioning: SINGLE []
    Stage Execution Strategy: UNGROUPED_EXECUTION
    ScanProject[table = hive:temp:test_mask_good, grouped = false]
        Layout: [col2:varchar, col1:varchar]
        Estimates: {rows: 0 (0B), cpu: 0, memory: 0B, network: 0B}/{rows: 0 (0B), cpu: 0, memory: 0B, network: 0B}
        col2 := (CASE WHEN ((json_extract_scalar("payload", "$literal$"(from_base64('DgAAAFZBUklBQkxFX1dJRFRIAQAAAAYAAAAABgAAACQuYXR0cg=='))) = VARCHAR 'a') OR (json_extract_scalar("payload", "$literal$"(from_base64('DgAAAFZBUklBQkxFX1dJRFRIAQAAAAYAAAAABgAAACQuYXR0cg=='))) = VARCHAR 'b')) THEN VARCHAR '***' ELSE "col2" END)
        col1 := (CASE WHEN (json_extract_scalar("payload", "$literal$"(from_base64('DgAAAFZBUklBQkxFX1dJRFRIAQAAAAYAAAAABgAAACQuYXR0cg=='))) = VARCHAR 'a') THEN VARCHAR '***' ELSE "col1" END)
        payload := payload:string:REGULAR
        col2 := col2:string:REGULAR
        col1 := col1:string:REGULAR

```

**BAD: (INTERNAL_ERROR)**
```
CREATE TABLE temp.test_mask_bad(col1 varchar, payload varchar, col2 varchar);

EXPLAIN SELECT col1, col2 from temp.test_mask_bad;

java.lang.IllegalStateException: Symbol payload already has assignment "@concat@52QIVVB44009Q180UA4I07RG96DG090K6U5ML5K1KLK2QAVH0OL2DK23J1VO46IUK6LC5U81PLGJ831QOD68L252G81AGB3B419NEG27AMO6PAIC72IPLVJ0BE5PSSIPD8J0M5SHJSDH8125O20UD016EA9RDGOF08O21UEJ3G33KMU5KGGTDVBSJL15LDT05G4BLMN2VBSLTKI478T2D9R7Q1ORAFA54GTH64G07K970F7GOKO4G4EGECECU3KSMU3T73NJ33134LHICKVL213N69TN108MM9U5LHHJ08P9GUHQLEA9O==="("payload", CAST('' AS varchar)), while adding "payload"
	at com.google.common.base.Preconditions.checkState(Preconditions.java:845)
	at io.trino.sql.planner.plan.Assignments$Builder.put(Assignments.java:270)
	at io.trino.sql.planner.plan.Assignments$Builder.putIdentity(Assignments.java:297)
	at io.trino.sql.planner.iterative.rule.InlineProjections.inlineProjections(InlineProjections.java:124)
	at io.trino.sql.planner.iterative.rule.InlineProjections.apply(InlineProjections.java:83)
	at io.trino.sql.planner.iterative.rule.InlineProjections.apply(InlineProjections.java:58)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:184)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:159)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:131)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:217)
	at io.trino.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:126)
	at io.trino.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:109)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:232)
	at io.trino.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:176)
	at io.trino.sql.analyzer.QueryExplainer.getDistributedPlan(QueryExplainer.java:187)
	at io.trino.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:104)
	at io.trino.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:147)
	at io.trino.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:125)
	at io.trino.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:73)
	at io.trino.sql.tree.Explain.accept(Explain.java:61)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:70)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:53)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:88)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:250)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:177)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:768)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_366____20211221_071947_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by weiatwork**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?
Bug fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
Query engine

> How would you describe this change to a non-technical end user or system administrator?
Fixes an issue in InlineProjections that may cause query failure when multiple column masks exist on a table

## Related issues, pull requests, and links
I incorporated unit test cases from #10437. The change in #10437 can be seen as an improvement to avoid unnecessary Project node stacking, but the root cause is how we handle multiple Project nodes when performing symbol inlining.

Fixes #10370

## Documentation

(X) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(X) Release notes entries required with the following suggested text:

```markdown
# Security
* Fix some query failures when multiple column masks exist on a table. ({issue}`10370`)
```

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java [hunk 1]
```diff
@@ -122,6 +122,10 @@ static Optional<ProjectNode> inlineProjections(PlannerContext plannerContext, Pr
         for (Map.Entry<Symbol, Expression> assignment : child.getAssignments().entrySet()) {
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java:122]: Please follow https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages and improve the commit message

File: core/trino-main/src/main/java/io/trino/sql/planner/plan/Assignments.java [hunk 2]
```diff
@@ -60,6 +60,11 @@ public static Assignments identity(Iterable<Symbol> symbols)
         return builder().putIdentities(symbols).build();
     }
 
+    public static boolean isIdentity(Symbol symbol, Expression expression)
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/sql/planner/plan/Assignments.java:63]: Please move this method to `InlineProjections`, also I would rename the method to `isSymbolReference`

**Review by kokosing — APPROVED** [review]
% comments

File: core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java (hunk 1 above)
Comment (weiatwork) [reply core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java:122]: Thanks for the tips. Improved commit message.

File: core/trino-main/src/main/java/io/trino/sql/planner/plan/Assignments.java (hunk 2 above)
Comment (weiatwork) [reply core/trino-main/src/main/java/io/trino/sql/planner/plan/Assignments.java]: Moved and renamed.

**Comment by kokosing** [comment]
Merged thanks.

**Comment by kasiafi** [comment]
This issue was originally caused by the way column masks are planned. While planning column masks, we add projections which change the semantics of the masked symbols:
```
masked_column <-- mask_expression(masked_column)
```
This seems brittle, because different plan transformations we have in Trino span across sequences of plan nodes, and they assume that a symbol consistently has the same semantics. I would not be surprised if we had silent correctness issues resulting from that.

Another issue with planning column masks this way is the notion of "sequential masking". The masks which are applied later "see" the other columns already masked (but maybe it is the way it should be?). Consider this example:

```
@Test
    public void testSequentialMasking()
    {
        accessControl.reset();

        accessControl.columnMask(
                new QualifiedObjectName(CATALOG, "tiny", "region"),
                "regionkey",
                USER,
                new ViewExpression(USER, Optional.empty(), Optional.empty(), "-1"));

        accessControl.columnMask(
                new QualifiedObjectName(CATALOG, "tiny", "region"),
                "name",
                USER,
                new ViewExpression(USER, Optional.empty(), Optional.empty(), "if(regionkey > 2, cast('***' as varchar(25)), name)"));

        assertThat(assertions.query("SELECT regionkey, name FROM region"))
                .matches("VALUES " +
                        "(BIGINT '-1', CAST('AFRICA' as varchar(25)))," +
                        "(BIGINT '-1', CAST('AMERICA' as varchar(25))), " +
                        "(BIGINT '-1', CAST('ASIA' as varchar(25))), " +
                        "(BIGINT '-1', CAST('EUROPE' as varchar(25))), " +
                        "(BIGINT '-1', CAST('MIDDLE EAST' as varchar(25)))");
    }
```
In this example, the mask on `regionkey` column is applied first. As a result, the other mask on `name` column is never effective, because it assumes the original values of `regionkey` column, not the masked values.

The solution to both issues would be to plan masks so that the resulting symbol is a new symbol.

@martint @kokosing @weiatwork

**Comment by weiatwork** [comment]
Thanks @kasiafi for pointing that out. For your second note on "sequential masking", I agree there is a mask dependency issue, which I'm not sure what is the correct/compliant behavior. What's worse is if the sequence of masking is performed in an non-deterministic way, the query result will be inconsistent as well.

**Comment by kokosing** [comment]
Each mask is like a view. If you have multiple masks then you have recursive view that reads from view that reads from a table.

So each mask is applied independently. If you have a table with columns a, b, and two masks functions that `M1: a = hash1(a) and M2: b = hash2(a)`, then it results in `a = hash1(original a)` and `b=hash2(hash1(original a)`.

Surely the order is important and engine applies them in the order that was returned by the plugin. Not sure how much test coverage we have here.

File: core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java [hunk 3]
```diff
@@ -726,4 +726,119 @@ public void testColumnMaskWithHiddenColumns()
...
+        accessControl.columnMask(
+                new QualifiedObjectName(CATALOG, "tiny", "orders"),
+                "comment",
+                USER,
+                new ViewExpression(USER, Optional.empty(), Optional.empty(), "if(regexp_extract(clerk,'([1-9]+)') IN ('951'), '***', comment)"));
+
+        assertThat(assertions.query(query))
+                .matches("VALUES (CAST('***' as varchar(79)), 'O', CAST('***#000000951' as varchar(15)))");
+
+        // Mask "comment" and "orderstatus" using "clerk" ("clerk" appears between "orderstatus" and "comment" in table definition)
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:820]: The order of columns shouldn't determine any mask/filter related behavior.

I don't understand this comment, but it looks like explaining why the expected behavior is what it is.
If the expected behavior was identified as dependent on the column order in the table definition, this comment should be a TODO + link to a github issue.

see also https://github.com/trinodb/trino/pull/14420#issuecomment-1265121690

Comment (kasiafi) [reply core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:820]: The comments on the order of column definitions do not seem related. The tests don't show any dependency between the column order and the effective semantics of the masks. @weiatwork, am I correct? What's the purpose of those comments?

Comment (findepi) [reply core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:820]: cc @kokosing

Comment (weiatwork) [reply core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:820]: @kasiafi That's right. That test didn't demonstrate any "column mask dependent" masking scenario, only trying to avoid the previously not so well understood behavior.

Since now I'm more confident that this behavior is problematic, I made adjustment to the test case and intentionally demo that there shouldn't be dependencies after the fix: https://github.com/trinodb/trino/pull/14420/files#diff-637b4407daa07892834452da6da9e755fd1dfb72813298df590c7fe019796249R849

Comment (kasiafi) [reply core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:820]: @weiatwork please see my comment https://github.com/trinodb/trino/pull/14420#issuecomment-1268086237.
If the behavior of the masks does _not_ depend on the order of column definitions, then it would be worthy to remove the related part of the comments, e.g. `("clerk" appears between "orderstatus" and "comment" in table definition)`, as they might mislead someone into thinking that there is a dependency between mask semantics and column def order.

Comment (weiatwork) [reply core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:820]: Currently there is dependency. Now I realize there shouldn't be any dependency among masks
