### PR TITLE
Fixed #3605: Elastic searching for field with null and value not working correctly

### LINKED ISSUE #3605: Elastic searching for field with null and value not working correctly
this query:
`select id from tmp_table
where value is null or value = 37`

will generate this query 
`{
  "size" : 1000,
  "query" : {
    "bool" : {
      "filter" : [
        {
          "bool" : {
            "must" : [
              {
                "bool" : {
                  "should" : [
                    {
                      "bool" : {
                        "filter" : [
                          {
                            "term" : {
                              "value" : {
                                "value" : 37,
                                "boost" : 1.0
                              }
                            }
                          }
                        ],
                        "adjust_pure_negative" : true,
                        "boost" : 1.0
                      }
                    }
                  ],
                  "adjust_pure_negative" : true,
                  "boost" : 1.0
                }
              }
            ],
            "adjust_pure_negative" : true,
            "boost" : 1.0
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "_source" : {
    "includes" : [
      "id"
    ],
    "excludes" : [ ]
  },
  "sort" : [
    {
      "_doc" : {
        "order" : "asc"
      }
    }
  ]
}`

but this excludes de null values, it only gives records with value 37..

the translation from elastic for that query is 
`{
  "query" : {
    "bool" : {
      "should" : [
        {
          "bool" : {
            "must_not" : [
              {
                "exists" : {
                  "field" : "value",
                  "boost" : 1.0
                }
              }
            ],
            "adjust_pure_negative" : true,
            "boost" : 1.0
          }
        },
        {
          "term" : {
            "value" : {
              "value" : 37,
              "boost" : 1.0
            }
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "_source" : {
    "includes" : [
      "id"
    ],
    "excludes" : [ ]
  },
  "sort" : [
    {
      "_doc" : {
        "order" : "asc"
      }
    }
  ]
}`

### PR DESCRIPTION
**Pull request by sumannewton**
Fixes https://github.com/trinodb/trino/issues/3605

Issue:
Below query pushes only value=32 to elasticsearch. But not `value not exists`.
`select * from table where value is null or value = 32`

Fix:
Push both the queries within the `should` clause. One with `term` query and other with `not_exists` query.

Testcases:

- Test `is null` push down query.
- Test `is not null` push down query.
- Test `is null OR value` push down query.
- Test `is not null OR value` push down query.

### CODE REVIEW

File: plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java [hunk 1]
```diff
@@ -232,6 +232,64 @@ public void testShowColumns()
         assertEquals(expected, actual);
     }
 
+    @Test
+    public void testNullPredicate()
```
Comment (findepi) [inline plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java:236]: the error-proneness is generic (it's not the first time we forget about `domain.isNullAllowed()`) and so we should have a generic test that covers all the the connectors.

do you happen to know why

https://github.com/trinodb/trino/blob/36cada014c8cd1a227920a5508cb68174175f779/testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java#L1226-L1227

and

https://github.com/trinodb/trino/blob/36cada014c8cd1a227920a5508cb68174175f779/testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java#L1234-L1238

did not let us uncover the bug earlier?

Comment (Praveen2112) [reply plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java:236]: I guess this tests runs only if the connector has support for creating tables. And elasticsearch doesn't support it as of now so it got missed.

Comment (Praveen2112) [reply plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java:236]: I think we can have an extra extension point to inject the data via non SQL methods and base connector tests could have an impl for it

Comment (sumannewton) [reply plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java:236]: Exactly. These tests got missed because elasticsearch tests has disabled the support for create table.

Comment (findepi) [reply plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java:236]: Thanks, i missed that.

File: plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java [hunk 2]
```diff
@@ -232,6 +232,64 @@ public void testShowColumns()
...
+            .put("custkey", 1301)
+            .build());
+
+        // not null filter
+        assertQueryReturnsEmptyResult("SELECT * FROM null_predicate2 WHERE null_keyword IS NOT NULL");
+        assertQueryReturnsEmptyResult("SELECT * FROM null_predicate2 WHERE null_keyword = '10' OR null_keyword IS NOT NULL");
+
+        // filtered column is selected
+        assertQuery("SELECT custkey, null_keyword FROM null_predicate2 WHERE null_keyword IS NULL", "VALUES (1301, NULL)");
+        assertQuery("SELECT custkey, null_keyword FROM null_predicate2 WHERE null_keyword = '32' OR null_keyword IS NULL", "VALUES (1301, NULL)");
```
Comment (aalbu) [inline plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java:287]: We should also have a document in the index that has a non-null value for field `null_keyword` (say '32'), as well, and show that a filter like `null_keyword = '32' OR null_keyword IS NULL` selects both the null and non-null values (that was the original issue reported).

Comment (sumannewton) [reply plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java:287]: Added.

**Comment by sumannewton** [comment]
@bitsondatadev @findepi @aalbu Requesting review. Thanks.

**Comment by sumannewton** [comment]
@cla-bot check

**Review by aalbu — APPROVED** [review]

File: plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java [hunk 3]
```diff
@@ -130,6 +130,10 @@ private static QueryBuilder buildTermQuery(BoolQueryBuilder queryBuilder, String
             }
```
Comment (wendigo) [inline plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java:130]: Please change commit message according to https://chris.beams.io/posts/git-commit/

File: plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java [hunk 4]
```diff
@@ -288,6 +288,14 @@ public void testNullPredicate()
```
Comment (wendigo) [inline plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java:288]: Please change commit message: "Added a test for null or value clause in Elasticsearch connector"

File: testing/trino-server-dev/etc/catalog/blackhole.properties [hunk 5]
```diff
@@ -1,8 +0,0 @@
-#
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/blackhole.properties]: Revert

File: testing/trino-server-dev/etc/catalog/example.properties [hunk 6]
```diff
@@ -1,9 +0,0 @@
-#
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/example.properties]: Revert

File: testing/trino-server-dev/etc/catalog/druid.properties [hunk 7]
```diff
@@ -1,7 +0,0 @@
-connector.name=druid
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/druid.properties]: Revert

File: testing/trino-server-dev/etc/catalog/hive.properties [hunk 8]
```diff
@@ -1,26 +0,0 @@
-#
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/hive.properties]: Revert

File: testing/trino-server-dev/etc/catalog/iceberg.properties [hunk 9]
```diff
@@ -1,12 +0,0 @@
-#
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/iceberg.properties]: Revert

File: testing/trino-server-dev/etc/catalog/jmx.properties [hunk 10]
```diff
@@ -1,8 +0,0 @@
-#
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/jmx.properties]: Revert

File: testing/trino-server-dev/etc/catalog/localfile.properties [hunk 11]
```diff
@@ -1,10 +0,0 @@
-#
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/localfile.properties]: Revert

File: testing/trino-server-dev/etc/catalog/memory.properties [hunk 12]
```diff
@@ -1 +0,0 @@
-connector.name=memory
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/memory.properties]: Revert

File: testing/trino-server-dev/etc/catalog/memsql.properties [hunk 13]
```diff
@@ -1,4 +0,0 @@
-connector.name=memsql
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/memsql.properties]: Revert

File: testing/trino-server-dev/etc/catalog/mysql.properties [hunk 14]
```diff
@@ -1,4 +0,0 @@
-connector.name=mysql
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/mysql.properties]: Revert

File: testing/trino-server-dev/etc/catalog/postgresql.properties [hunk 15]
```diff
@@ -1,4 +0,0 @@
-connector.name=postgresql
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/postgresql.properties]: Revert

File: testing/trino-server-dev/etc/catalog/prometheus.properties [hunk 16]
```diff
@@ -1,5 +0,0 @@
-connector.name=prometheus
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/prometheus.properties]: Revert

File: testing/trino-server-dev/etc/catalog/raptor.properties [hunk 17]
```diff
@@ -1,13 +0,0 @@
-#
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/raptor.properties]: Revert

File: testing/trino-server-dev/etc/catalog/sqlserver.properties [hunk 18]
```diff
@@ -1,4 +0,0 @@
-connector.name=sqlserver
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/sqlserver.properties]: Revert

File: testing/trino-server-dev/etc/catalog/thrift.properties [hunk 19]
```diff
@@ -1,9 +0,0 @@
-#
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/thrift.properties]: Revert

File: testing/trino-server-dev/etc/catalog/tpcds.properties [hunk 20]
```diff
@@ -1,2 +0,0 @@
-connector.name=tpcds
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/tpcds.properties]: Revert

File: testing/trino-server-dev/etc/catalog/tpch.properties [hunk 21]
```diff
@@ -1,9 +0,0 @@
-#
```
Comment (wendigo) [inline testing/trino-server-dev/etc/catalog/tpch.properties]: Revert

File: testing/trino-server-dev/etc/catalog/blackhole.properties (hunk 5 above)
Comment (sumannewton) [reply testing/trino-server-dev/etc/catalog/blackhole.properties]: @wendigo All these files have been reverted already with a revert commit.

File: testing/trino-server-dev/etc/catalog/example.properties (hunk 6 above)
Comment (sumannewton) [reply testing/trino-server-dev/etc/catalog/example.properties]: All these changes have been reverted already.

File: plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java (hunk 3 above)
Comment (sumannewton) [reply plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java:130]: Done

File: plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java (hunk 4 above)
Comment (sumannewton) [reply plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java:288]: Done.

**Comment by sumannewton** [comment]
@wendigo @bitsondatadev @findepi Addressed review comments. Requesting your review again.
Thanks.

**Comment by wendigo** [comment]
Please squash revert commit into the previous one and also the one fixing checkstyle errors with the commit that introduced those.

**Review by martint — APPROVED** [review]

**Comment by martint** [comment]
Thanks!
