### PR TITLE
Fix double slash issue in Iceberg metadata location

### LINKED ISSUE #14299: Iceberg metadata location gets changed with newer Trino versions
Hello all!

We are experiencing an issue when trying to upgrade Trino from version 386 to 397. We are using Iceberg tables with default `write.metadata.path` configurations, pointed at our S3 data warehouse bucket. Our S3 path's for our tables look like `s3://dw_bucket/prd_{table}_iceberg/`, and metadata is saved in the default `metadata` directory in that prefix. When trying newer versions (397 and 395 have been tried and present this issue, 391 is the newest version we have tried which doesn't), we have generic internal errors on every type of query pointing at some of our tables, because the metadata_location of the Iceberg table gets changed to `s3://dw_bucket/prd_{table}_iceberg//metadata/{metadata_file}.json` randomly. We have worked around this issue by manually rewriting the metadata_location property correctly using Spark, but we do not know what causes it, and can't guarantee it won't spuriously happen again.

For reference, we are building Trino from the official Docker image, and using Nomad to create containers and scale our production clusters.

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #14299

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Iceberg
* Fix failure when reading a table with leading double slash in the metadata location. ({issue}`14299`)
```

### CODE REVIEW

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 1]
```diff
@@ -623,4 +623,11 @@ private static void validateOrcBloomFilterColumns(ConnectorTableMetadata tableMe
             throw new TrinoException(INVALID_TABLE_PROPERTY, format("Orc bloom filter columns %s not present in schema", Sets.difference(ImmutableSet.copyOf(orcBloomFilterColumns), allColumns)));
         }
     }
+
+    public static String removeRedundantSlash(String location)
+    {
+        // Version 393 and 394 stored metadata location with double slash. e.g. s3://bucket/db/table//metadata/00001.metadata.json
```
Comment (alexjo2144) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:629]: Can you link the PRs that added this issue in 393 and which one fixed it in 395?

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java]: Updated the code comment.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 2]
```diff
@@ -623,4 +623,14 @@ private static void validateOrcBloomFilterColumns(ConnectorTableMetadata tableMe
...
     }
+
+    public static String removeRedundantSlash(String location)
+    {
+        // Version 393 and 394 stored metadata location with double slash https://github.com/trinodb/trino/pull/13530
+        // e.g. s3://bucket/db/table//metadata/00001.metadata.json
+        // It caused failure when accessing S3 objects https://github.com/trinodb/trino/issues/14299
+        // Version 395 fixed the above issue by removing trailing slash https://github.com/trinodb/trino/pull/13984,
+        // but the change was insufficient for existing table cases created by 393 and 394. This method covers existing table cases.
+        return location.replace("//metadata/", "/metadata/");
```
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:634]: is it possible that the metadata path really contains two slashes?
for example, what if table was created with `location = 's3://bucket/my_table/////'`?

also, is it possible that `//metadata/` substring occurs somewhere else within the location?
for example, what if my bucket is called `metadata`?
or, i have a table created with `location = 's3://bucket/i/love/slashes/and//////metadata/my_schema/my_table'`?

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java [hunk 3]
```diff
@@ -107,4 +108,32 @@ public void testS3LocationWithTrailingSlash()
...
+        // Regression test for https://github.com/trinodb/trino/issues/14299
+        String schemaName = getSession().getSchema().orElseThrow();
+        String tableName = "test_meatdata_location_with_double_slash_" + randomTableSuffix();
+
+        assertUpdate("CREATE TABLE " + tableName + " AS SELECT 1 col", 1);
+
+        // Update metadata location to contain double slash
+        String tableId = onMetastore("SELECT tbl_id FROM TBLS t INNER JOIN DBS db ON t.db_id = db.db_id WHERE db.name = '" + schemaName + "' and t.tbl_name = '" + tableName + "'");
+        String metadataLocation = onMetastore("SELECT param_value FROM TABLE_PARAMS WHERE param_key = 'metadata_location' AND tbl_id = " + tableId);
+        String newMetadataLocation = metadataLocation.replace("/metadata/", "//metadata/");
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java:124]: add

```
// Simulate corrupted metadata location as Trino 393-394 was doing
```

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 4]
```diff
@@ -623,4 +623,14 @@ private static void validateOrcBloomFilterColumns(ConnectorTableMetadata tableMe
             throw new TrinoException(INVALID_TABLE_PROPERTY, format("Orc bloom filter columns %s not present in schema", Sets.difference(ImmutableSet.copyOf(orcBloomFilterColumns), allColumns)));
         }
     }
+
+    public static String removeRedundantSlash(String location)
```
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:627]: "Remove redundant slash" sounds a bit  like "remove trailing slash" -- some operation that you do when manipulating paths.
Let's have the name express the fact this is a workaround for bad writers, not something you'd normally have to do.

`fixBrokenMetadataLocation`

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 5]
```diff
@@ -623,4 +623,14 @@ private static void validateOrcBloomFilterColumns(ConnectorTableMetadata tableMe
...
+    {
+        // Version 393 and 394 stored metadata location with double slash https://github.com/trinodb/trino/pull/13530
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java]: Changed a link URL.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 6]
```diff
@@ -624,4 +624,29 @@ private static void validateOrcBloomFilterColumns(ConnectorTableMetadata tableMe
...
+        // It caused failure when accessing S3 objects https://github.com/trinodb/trino/issues/14299
+        // Version 395 fixed the above issue by removing trailing slash https://github.com/trinodb/trino/pull/13984,
+        // but the change was insufficient for existing table cases created by 393 and 394. This method covers existing table cases.
+        String fileName = fileName(location);
+        String correctSuffix = "/metadata/" + fileName;
+        String brokenSuffix = "//metadata/" + fileName;
+        if (!location.endsWith(brokenSuffix)) {
+            return location;
+        }
+        String correctLocation = location.replace(brokenSuffix, correctSuffix);
```
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:641]: it's inconceivable that `location` contains multiple occurrences of `brokenSuffix`, but why would we burden the reader with having to think about that?

Use `substring` (or `replaceFirst(Patter.quote(...) + "$", Matcher.quotereplacement(...))`)

**Review by findepi — APPROVED** [review]

**Comment by ebyhr** [comment]
CI hit #14568

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 7]
```diff
@@ -624,4 +625,25 @@ private static void validateOrcBloomFilterColumns(ConnectorTableMetadata tableMe
...
+    public static String fixBrokenMetadataLocation(String location)
+    {
+        // Version 393-394 stored metadata location with double slash https://github.com/trinodb/trino/commit/e95fdcc7d1ec110b10977d17458e06fc4e6f217d#diff-9bbb7c0b6168f0e6b4732136f9a97f820aa082b04efb5609b6138afc118831d7R46
+        // e.g. s3://bucket/db/table//metadata/00001.metadata.json
+        // It caused failure when accessing S3 objects https://github.com/trinodb/trino/issues/14299
+        // Version 395 fixed the above issue by removing trailing slash https://github.com/trinodb/trino/pull/13984,
+        // but the change was insufficient for existing table cases created by 393 and 394. This method covers existing table cases.
+        String fileName = fileName(location);
+        String correctSuffix = "/metadata/" + fileName;
+        String brokenSuffix = "//metadata/" + fileName;
```
Comment (alexjo2144) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:638]: Could this have happened with files in the `//data/` directory?

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:638]: I temporary reverted #13984 and confirmed a data directory is fine. We may need additional handling if other query engines generates such directories though. Let's keep as-is since we haven't received issues about a data directory for now.
