### PR TITLE
Preserve table catalog/schema in ALTER TABLE qualified_name RENAME TO unqualified_name

### LINKED ISSUE #11281: ALTER TABLE RENAME implicitly changes table schemata
```
$ bin/trino-cli --catalog hive --schema default
trino:default> CREATE SCHEMA s;
CREATE SCHEMA

trino:default> CREATE TABLE s.t(a bigint);
CREATE TABLE

trino:default> ALTER TABLE s.t RENAME TO u;
RENAME TABLE

trino:default> SELECT * FROM s.u;
Query 20220302_124504_00048_5zguy failed: line 1:15: Table 'hive.s.u' does not exist
io.trino.spi.TrinoException: line 1:15: Table 'hive.s.u' does not exist

trino:default> SELECT * FROM default.u;
 a
---
(0 rows)
```

### Expected

`ALTER TABLE [catalog.]schema.table RENAME TO unqalified_name` changes table name only, but doesn't change schema.

Relates to https://github.com/trinodb/trino/issues/11202

### PR DESCRIPTION
**Pull request by findinpath**
## Description

When performing `ALTER TABLE xxx RENAME TO yyy` deduce the qualified object name of `yyy` from the session and use the source as a fallback

> Is this change a fix, improvement, new feature, refactoring, or other?

This is a bugfix.

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Fix.

> How would you describe this change to a non-technical end user or system administrator?

See #11281 

## Related issues, pull requests, and links

Fixes #11281

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(x) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by findepi** [comment]
The CI is red.

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java [hunk 1]
```diff
@@ -270,4 +273,37 @@ public void testCreateSchema()
         // verify DROP SCHEMA for non-existing schema
         assertQueryFails("DROP SCHEMA " + schemaName, format("line 1:1: Schema '.*\\.%s' does not exist", schemaName));
     }
+
+    @Test
+    @Override
+    public void testRenameTableUnqualifiedName()
+    {
+        // override needed to provide valid location for schema (it needs to be s3:// based). By default schema is assigned hdfs:// location
```
Comment (findepi) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java:281]: Can we have a method in BCT to fill in required table properties (default: none), so that we don't need to override such nice and verbose test method?

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java [hunk 2]
```diff
@@ -270,4 +273,37 @@ public void testCreateSchema()
...
+        // TODO: better fix would be to configure hadoop container we use in test to use `s3://` filesystem by default
+        skipTestUnless(hasBehavior(SUPPORTS_CREATE_SCHEMA) && hasBehavior(SUPPORTS_CREATE_TABLE));
```
Comment (findepi) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java:283]: add empty line after `// TODO: better fix would`, since the code line and comment are unrelated

Comment (findepi) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java:283]: BTW `skipTestUnless` is not needed in a specific test class (here), because it knows what it does and doesn't support

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java [hunk 3]
```diff
@@ -1674,6 +1674,36 @@ public void testRenameTableAcrossSchema()
         assertFalse(getQueryRunner().tableExists(getSession(), renamedTable));
     }
 
+    @Test
+    public void testRenameTableUnqualifiedName()
```
Comment (findepi) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:1678]: in prep commit move `testRenameTableAcrossSchema` directly below `testRenameTable`
and then add this new test after the two

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java [hunk 4]
```diff
@@ -1674,6 +1674,36 @@ public void testRenameTableAcrossSchema()
...
+        skipTestUnless(hasBehavior(SUPPORTS_CREATE_SCHEMA) && hasBehavior(SUPPORTS_CREATE_TABLE));
+
+        String sourceSchemaName = "test_source_schema_" + randomTableSuffix();
+        assertUpdate("CREATE SCHEMA " + sourceSchemaName);
+
+        String tableName = "test_rename_unqualified_name_" + randomTableSuffix();
+        assertUpdate("CREATE TABLE " + sourceSchemaName + "." + tableName + " AS SELECT 123 x", 1);
+
+        String renamedTable = "test_rename_unqualified_name_new_" + randomTableSuffix();
+        if (!hasBehavior(SUPPORTS_RENAME_TABLE)) {
```
Comment (findepi) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:1689]: i'd move this to `skipTestUnless` part

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java (hunk 3 above)
Comment (findepi) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:1678]: rename to `testRenameTableToUnqualifiedPreservesSchema`

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java [hunk 5]
```diff
@@ -1674,6 +1674,36 @@ public void testRenameTableAcrossSchema()
...
+            assertUpdate("DROP SCHEMA " + sourceSchemaName);
+            return;
+        }
+
+        assertUpdate("ALTER TABLE " + sourceSchemaName + "." + tableName + " RENAME TO " + renamedTable);
+        assertQuery("SELECT x FROM " + sourceSchemaName + "." + renamedTable, "VALUES 123");
+
+        assertUpdate("DROP TABLE " + sourceSchemaName + "." + renamedTable);
+
+        assertFalse(getQueryRunner().tableExists(getSession(), tableName));
```
Comment (findepi) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:1701]: this should be asserted after `assertUpdate("ALTER TABLE " +`. , not after `assertUpdate("DROP TABLE " renamed`

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java [hunk 6]
```diff
@@ -1674,6 +1674,36 @@ public void testRenameTableAcrossSchema()
...
+        assertFalse(getQueryRunner().tableExists(getSession(), renamedTable));
```
Comment (findepi) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:1702]: no need to assert that

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java (hunk 1 above)
Comment (findinpath) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java:281]: Thank you for seeing this cleaner way to customize the tests for delta lake.

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java (hunk 2 above)
Comment (findinpath) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java:283]: Not applying anymore because the duplicated test method has been removed from the class.

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java (hunk 4 above)
Comment (findinpath) [reply testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:1689]: You are right. There is already a specific test for renaming tables so there's no need to do the check here again.

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java [hunk 7]
```diff
@@ -2001,6 +2001,26 @@ public void testRenameTableAcrossSchema()
...
+
+        String sourceSchemaName = "test_source_schema_" + randomTableSuffix();
+        assertUpdate(createSchemaSql(sourceSchemaName));
+
+        String tableName = "test_rename_unqualified_name_" + randomTableSuffix();
+        assertUpdate("CREATE TABLE " + sourceSchemaName + "." + tableName + " AS SELECT 123 x", 1);
+
+        String renamedTable = "test_rename_unqualified_name_new_" + randomTableSuffix();
+        assertUpdate("ALTER TABLE " + sourceSchemaName + "." + tableName + " RENAME TO " + renamedTable);
+        assertFalse(getQueryRunner().tableExists(getSession(), tableName));
```
Comment (findepi) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:2017]: actually, `assertFalse(getQueryRunner().tableExists(getSession(), tableName));` would succeed even before rename. You don't pass `sourceSchemaName` here (and you cannot).

For simplicity, let's skip the assertion.

Comment (findepi) [reply testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java]: (applied)

**Review by findepi — APPROVED** [review]
