### PR TITLE
Fix incorrect error message in Trino UI

### LINKED ISSUE #16249: Trino Web UI displays incorrect query state for failed queries
It looks like there is a bug in the Trino Web UI wherein it displays incorrect query state for failed queries.
Example: If the query fails with an Internal Error, Trino home page displays it as "EXTERNAL ERROR - {ErrorCode Name}. Query details page shows the correct status with "INTERNAL ERROR".

This issue exists in the latest Trino 407 version. I was able to replicate the issue in 402 as well.

Issue Screenshots:
CurrentState_ExternalError_TrinoMainPage
CurrentState_InternalError_TrinoQueryPage

### PR DESCRIPTION
**Pull request by ayushbilala**
## Description
Trino Web UI displays "EXTERNAL ERROR - ErrorCode Name" even if the query fails with an INTERNAL ERROR due to a missing break keyword in the switch case. 

Fixes #16249

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

File: core/trino-main/src/main/resources/webapp/src/utils.js [hunk 1]
```diff
@@ -130,10 +130,13 @@ export function getHumanReadableState(query: any, forOverviewPage: boolean): str
...
                 }
+                break;
             case "INTERNAL_ERROR":
                 errorMsg = "INTERNAL ERROR";
+                break;
             case "INSUFFICIENT_RESOURCES":
                 errorMsg = "INSUFFICIENT RESOURCES";
+                break;
             case "EXTERNAL":
                 errorMsg = "EXTERNAL ERROR";
```
Comment (ebyhr) [inline core/trino-main/src/main/resources/webapp/src/utils.js:141]: How about adding `break;` to here as well? Otherwise, we may miss when adding another condition after `EXTERNAL` in the future.

Comment (ayushbilala) [reply core/trino-main/src/main/resources/webapp/src/utils.js:141]: Added.

**Comment by ebyhr** [comment]
CI hit #16286

**Review by ebyhr — APPROVED** [review]
