### PR TITLE
Reduce memory pressure due to highly nested fields in Iceberg

### LINKED ISSUE #25077: Excessive memory usage in Iceberg connector since version 468
I just recently did an upgrade from Trino 466 to 470 and operation like 'show columns from' or 'show create table' for Iceberg table started to fail miserably.
The table itself has just several top level fields and one of the fields is a deeply nested data structure with around 7k projected fields.

After digging deeper, I discovered an excessive memory usage in Iceberg module:

Image

It appears there is an array with 7k record where each record is 2.5MB on average.

I can't share a data structure details due to the sensitivity of the content, however, I hope there is something obvious.
This is a critical bug for us as it makes Trino cluster fully unusable.

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

The `IcebergUtil.getProjectedColumns` method generated a list of #projected-columns + #nested-fields. Each entry contains the base ColumnIdentity with children & childFieldIdToIndex.

If the table contains a column with 10000 fields, the method creates a large object (1 column + 10000 fields) * (2 children * 10000 fields). 

A test I added to TestIcebergV2 resulted in Major GC without this PR's change.

Fixes #25077

## Release notes

```markdown
## Iceberg
* Reduce memory pressure when the table contains highly nested fields. ({issue}`25077`)
```

### CODE REVIEW

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 1]
```diff
@@ -262,10 +263,16 @@ public static BaseTable getIcebergTableWithMetadata(
...
+    public static List<IcebergColumnHandle> getProjectedColumns(Table table, TypeManager typeManager)
     {
-        Map<Integer, NestedField> indexById = TypeUtil.indexById(schema.asStruct());
-        return getProjectedColumns(schema, typeManager, indexById, indexById.keySet() /* project all columns */);
+        // Project only root columns and partition's source columns
+        // Extracting all nested fields may cause Major GC in case of highly nested fields
+        // https://github.com/trinodb/trino/issues/25077
+        Set<Integer> projectedIds = ImmutableSet.<Integer>builder()
+                .addAll(table.schema().columns().stream().map(NestedField::fieldId).collect(Collectors.toSet()))
+                .addAll(table.spec().fields().stream().map(PartitionField::sourceId).collect(Collectors.toSet()))
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java]: toImmutableSet ?

**Review by raunaqmorarka — APPROVED** [review]

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java (hunk 1 above)
Comment (chenjian2664) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java]: nit: .iterator()

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
Comment (chenjian2664) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:281]: if the index is large, maybe we could just filter above and this line using `fieldIds` in-advance
On the other hand, feels a bit unnecessary after we apply this change, it is not the root cause

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergUtil.java [hunk 2]
```diff
@@ -76,17 +76,6 @@ public void testGetProjectedColumns()
...
-        assertThat(getProjectedColumns(schema, TESTING_TYPE_MANAGER))
-                .extracting(IcebergColumnHandle::getId, IcebergColumnHandle::getName, column -> column.getBaseColumn().getId(), IcebergColumnHandle::getPath)
-                .containsExactly(
-                        tuple(1, "id", 1, ImmutableList.of()),
-                        tuple(2, "nested", 2, ImmutableList.of()),
-                        tuple(3, "value", 2, ImmutableList.of(3)),
-                        tuple(4, "list", 2, ImmutableList.of(4)),
-                        tuple(5, "element", 2, ImmutableList.of(4, 5)),
-                        tuple(6, "nested", 2, ImmutableList.of(6)),
-                        tuple(7, "value", 2, ImmutableList.of(6, 7)));
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergUtil.java:88]: Why removed?

Comment (chenjian2664) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergUtil.java:88]: I guess because the method signature was updated, we could do:
```
        assertThat(getProjectedColumns(schema, TESTING_TYPE_MANAGER, ImmutableSet.of(1,2,3,4,5,6,7))) ; 
```


But remove is good to me, since the later we identify every id of the column

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java [hunk 3]
```diff
@@ -1426,6 +1427,42 @@ public void testHighlyNestedFieldPartitioningWithTimestampTransform()
                 ImmutableSet.of("grandparent.parent.ts_hour=2021-01-01-01/", "grandparent.parent.ts_hour=2022-02-02-02/", "grandparent.parent.ts_hour=2023-03-03-03/"));
     }
 
+    @Test // regression test for https://github.com/trinodb/trino/issues/25077
+    void testHighlyNestedFields()
+    {
+        String table = "test_highly_nested_fields" + randomNameSuffix();
```
Comment (findinpath) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:1433]: Without the production code changes i could repro locally as well Major GC

```
2025-12-11T05:18:34.591-0600	WARN	Notification Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 0ms, stopped 1401ms: 16.19GB -> 14.97GB (only recovered 7.5% of heap memory)
2025-12-11T05:18:34.591-0600	WARN	Notification Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 0ms, stopped 1401ms: 16.19GB -> 14.97GB (only recovered 7.5% of heap memory)
2025-12-11T05:18:34.591-0600	WARN	Notification Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 0ms, stopped 1401ms: 16.19GB -> 14.97GB (only recovered 7.5% of heap memory)
2025-12-11T05:18:36.509-0600	WARN	Notification Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 547ms, stopped 1373ms: 16.14GB -> 15.93GB (only recovered 1.3% of heap memory)
2025-12-11T05:18:36.509-0600	WARN	Notification Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 547ms, stopped 1373ms: 16.14GB -> 15.93GB (only recovered 1.3% of heap memory)
2025-12-11T05:18:36.509-0600	WARN	Notification Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 547ms, stopped 1373ms: 16.14GB -> 15.93GB (only recovered 1.3% of heap memory)
2025-12-11T05:18:37.968-0600	WARN	Notification Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 85ms, stopped 1375ms: 16.14GB -> 16.09GB (only recovered 0.3% of heap memory)
2025-12-11T05:18:37.968-0600	WARN	Notification Thread	io.airlift.stats.JmxGcMonitor	Major GC: application 85ms, stopped 1375ms: 16.14GB -> 16.09GB (only recovered 0.3% of heap memory)
```

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Comment (findinpath) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:689]:
```suggestion
        List<IcebergColumnHandle> partitionColumns = getProjectedColumns(
                icebergTable.schema(),
                typeManager,
                icebergTable.spec().fields().stream().map(PartitionField::sourceId).collect(Collectors.toSet()));
```

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 4]
```diff
@@ -262,10 +263,16 @@ public static BaseTable getIcebergTableWithMetadata(
...
-    public static List<IcebergColumnHandle> getProjectedColumns(Schema schema, TypeManager typeManager)
+    public static List<IcebergColumnHandle> getProjectedColumns(Table table, TypeManager typeManager)
     {
-        Map<Integer, NestedField> indexById = TypeUtil.indexById(schema.asStruct());
-        return getProjectedColumns(schema, typeManager, indexById, indexById.keySet() /* project all columns */);
+        // Project only root columns and partition's source columns
+        // Extracting all nested fields may cause Major GC in case of highly nested fields
+        // https://github.com/trinodb/trino/issues/25077
+        Set<Integer> projectedIds = ImmutableSet.<Integer>builder()
+                .addAll(table.schema().columns().stream().map(NestedField::fieldId).collect(Collectors.toSet()))
```
Comment (findinpath) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java]: I see that `io.trino.plugin.iceberg.IcebergPageSink` also relies actually on partition column handles only.
I think this is a good opportunity to adjust the code to be more sparingly with the column handles we're creating.

There is a good chance that we rename this method to `getPartitionColumns(Table table, TypeManager typeManager)` and not return anymore the top level columns

Comment (chenjian2664) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java]: just a thought, maybe we could consider add a new method `getPartitionColumns` instead of rename, there are other system might depends on it :)

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java]: @findepi Thanks! I renamed the method and downstream variables. 

@chenjian2664 Disagreed. Trino Iceberg connector is not a library. We shouldn't introduce such a process.

**Comment by ebyhr** [comment]
/test-with-secrets sha=0cc1822af7f711fe8c2d763a4e2f355ac6429c1c
