### PR TITLE
Prepare broken column statistics table using Hive metastore database directly

### LINKED ISSUE #13889: Flaky `TestHiveAnalyzeCorruptStatistics.testAnalyzeCorruptColumnStatisticsOnEmptyTable`
```
2022-08-26T19:22:50.292-0500	ERROR	pool-3-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST FAILURE] io.trino.plugin.hive.TestHiveAnalyzeCorruptStatistics.testAnalyzeCorruptColumnStatisticsOnEmptyTable; (took: 2 minutes and 14 seconds)
java.lang.AssertionError: 
Expecting code to raise a throwable.
	at io.trino.plugin.hive.TestHiveAnalyzeCorruptStatistics.testAnalyzeCorruptColumnStatisticsOnEmptyTable(TestHiveAnalyzeCorruptStatistics.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #13889

## Documentation

(x) No documentation is needed.

## Release notes

(x) No release notes entries required.

### CODE REVIEW

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java [hunk 1]
```diff
@@ -119,5 +120,14 @@ private void prepareBrokenColumnStatisticsTable(String tableName)
             executor.shutdownNow();
             executor.awaitTermination(10, SECONDS);
         }
+
+        // Verify whether column statistics in metastore is broken or not
+        try {
```
Comment (findinpath) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java:125]: optional: move this logic to `testAnalyzeCorruptColumnStatisticsOnEmptyTable()`

**Review by findinpath — APPROVED** [review]

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java:125]: Disagreed as the method name is `prepareBrokenColumnStatisticsTable`. A broken table should exist after called the method.

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java [hunk 2]
```diff
@@ -119,5 +120,14 @@ private void prepareBrokenColumnStatisticsTable(String tableName)
...
+            query("ANALYZE " + tableName);
+            throw new SkipException("Concurrent ANALYZE statements didn't break column statistics");
```
Comment (findepi) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java:127]: `prepareBrokenColumnStatisticsTable` may stop functioning and we will never find out.
Perhaps retry the method instead?

Also, why ANALYZE is expected to fail? eventually it should work. As a user, if a have some bad stats, I'd expect ANALYZE to fix them.

Comment (ebyhr) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java:127]: > Perhaps retry the method instead?

The test already has `invocationCount = 3`. I would like to leave to the option than retrying. 

> Also, why ANALYZE is expected to fail? eventually it should work. As a user, if a have some bad stats, I'd expect ANALYZE to fix them.

I think we agreed to fix only read path in case of broken statistics. Sorry if I misunderstood the conclusion. That's why there's `assertThatThrownBy(() -> query("ANALYZE " + tableName))` at L72. As far as I tried, there's no option in Thrift Hive metastore client for updating or dropping column statistics when it has duplicated entires.

Comment (findepi) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java:127]: > I think we agreed to fix only read path in case of broken statistics

that's fine

but we may want to fix the ANALYZE too, so i wouldn't want to use ANALYZE in the test as a way to check that stats are broken

> The test already has `invocationCount = 3`.

this means that it's attempted 3 times and all 3 times need to pass
it doesn't handle yet the case where setup didn't succeed in producing erroneous situation 

why not retry `prepareBrokenColumnStatisticsTable` until stats are broken

also, can we inject broken stats into HMS database directly?
that could free us from any concurrency in the test

Comment (ebyhr) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java:127]: Yes, we can break MySQL database directly. I will change to the approach.
The reason I avoided it was future HMS may not have duplicated stats issue and direct database modification may hide such changes.

Comment (findepi) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java]: I agree that the previous approach is generally good. However, if it's not reliable, we may need to change the approach. I prefer to change the approach rather than to disable the test.

**Review by findepi — APPROVED** [review]
