### PR TITLE
Resolve SchemaReferences in ConfluentContentSchemaReader

### LINKED ISSUE #6907: Kafka connector: read on schema-registry table with schema references failing
When I tried to do a select on a topic/subject that has references to other schemas, getting this error,

```
[trino@presto-trino-coordinator-564cc6587c-fs5qp /]$ trino --catalog=kafka --schema=default --debug
trino:default> select timestampmsecs from dummy;
Query 20210216_061605_00007_e5knx, FAILED, 2 nodes
http://localhost:8080/ui/query.html?20210216_061605_00007_e5knx
Splits: 17 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 12% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak Memory: 0B
0.37 [0 rows, 0B] [0 rows/s, 0B/s]
Query 20210216_061605_00007_e5knx failed: "Identifier" is not a defined name. The type of the "identifier" field must be a defined name or a {"type": ...} expression.
org.apache.avro.SchemaParseException: "Identifier" is not a defined name. The type of the "identifier" field must be a defined name or a {"type": ...} expression.
	at org.apache.avro.Schema.parse(Schema.java:1635)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1394)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1382)
	at io.trino.decoder.avro.AvroRowDecoderFactory.create(AvroRowDecoderFactory.java:58)
	at io.trino.decoder.DispatchingRowDecoderFactory.create(DispatchingRowDecoderFactory.java:38)
	at io.trino.plugin.kafka.KafkaRecordSetProvider.getRecordSet(KafkaRecordSetProvider.java:68)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorRecordSetProvider.getRecordSet(ClassLoaderSafeConnectorRecordSetProvider.java:49)
	at io.trino.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
	at io.trino.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:68)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:298)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_352____20210216_034829_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Here `Identifier` is a different schema/subject in the schema-registry.

### PR DESCRIPTION
**Pull request by Praveen2112**
Fixes #6907

### CODE REVIEW

File: testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java [hunk 1]
```diff
@@ -73,30 +75,6 @@
     private static final String STRUCTURAL_AVRO_TOPIC_NAME = "read_structural_datatype_avro";
     private static final String STRUCTURAL_SCHEMA_PATH = "/docker/presto-product-tests/conf/presto/etc/catalog/kafka/structural_datatype_avro_schema.avsc";
 
-    private static void createAvroTable(String schemaPath, String tableName, String topicName, ImmutableMap<String, Object> record, MessageSerializer messageSerializer)
```
Comment (kokosing) [inline testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java:76]: Please extract method move to separate commit, otherwise it is hard to see what actually has changed.

File: testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java [hunk 2]
```diff
@@ -205,20 +183,51 @@ public String toString()
...
+            String schema = Files.readString(new File(schemaPath).toPath());
+            createAvroTable(new TestingAvroSchema(schema, ImmutableList.of(), ImmutableList.of()), tableName, topicName, record, messageSerializer);
+        }
+        catch (IOException e) {
+            throw new UncheckedIOException(e);
+        }
+    }
+
+    private static void createAvroTable(TestingAvroSchema schema, String tableName, String topicName, Map<String, Object> record, MessageSerializer messageSerializer)
+            throws IOException
```
Comment (kokosing) [inline testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java:239]: maybe just add `throws Exception` and allow tests to throw `Exception`. No boilerplate with try-catch and rethrow as runtime

File: testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java [hunk 3]
```diff
@@ -183,6 +187,43 @@ public String toString()
         }
     }
 
+    @Test(groups = {KAFKA, PROFILE_SPECIFIC_TESTS})
+    public void testAvroWithSchemaReferences()
+            throws IOException, RestClientException
```
Comment (kokosing) [inline testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java:192]: just `throws Exception`

File: plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java [hunk 4]
```diff
@@ -47,7 +51,11 @@ public AvroConfluentContentSchemaReader(SchemaRegistryClient schemaRegistryClien
         }
         checkState(dataSchemaLocation.isEmpty(), "Unexpected parameter: dataSchemaLocation");
         try {
-            return Optional.of(schemaRegistryClient.getLatestSchemaMetadata(subject.get()).getSchema());
+            SchemaMetadata schemaMetadata = schemaRegistryClient.getLatestSchemaMetadata(subject.get());
+            ParsedSchema schema = schemaRegistryClient.getSchemaById(schemaMetadata.getId());
```
Comment (kokosing) [inline plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java:55]: How does it resolve schema reference?

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroConfluentContentSchemaReader.java [hunk 5]
```diff
@@ -51,6 +56,32 @@ public void testAvroConfluentSchemaReader()
...
+        AvroConfluentContentSchemaReader avroConfluentSchemaReader = new AvroConfluentContentSchemaReader(mockSchemaRegistryClient);
+        assertThat(avroConfluentSchemaReader.readSchema(Optional.empty(), Optional.of(SUBJECT_NAME)).map(schema -> new Parser().parse(schema))).isPresent();
+    }
+
+    private static String getAvroSchemaWithReference()
+    {
+        return "{\n" +
+                "    \"type\":\"record\",\n" +
+                "    \"name\":\"Schema2\",\n" +
+                "    \"fields\":[\n" +
```
Comment (kokosing) [inline plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroConfluentContentSchemaReader.java:78]: How does it work? You referenced a schema and then you specified fields, does it mean that actual fields will be an union of these two? Or is it only about that type `test` is now defined and you can reuse it?

Where is type `test` defined?

**Review by kokosing — COMMENTED** [review]
Thanks!

File: testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java (hunk 2 above)
Comment (skrzypo987) [reply testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java:239]: I prefer the way with UncheckedIO, but this is irrelevant really here.

File: testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java [hunk 6]
```diff
@@ -205,20 +183,51 @@ public String toString()
...
+                1);
+        KafkaTableManager kafkaTableManager = (KafkaTableManager) testContext().getDependency(TableManager.class, "kafka");
+        kafkaTableManager.createImmutable(tableDefinition, tableHandle(tableName).inSchema(KAFKA_SCHEMA));
+    }
+
     @FunctionalInterface
     private interface MessageSerializer
     {
-        byte[] serialize(String topic, Schema schema, Map<String, Object> values)
+        byte[] serialize(String topic, TestingAvroSchema testingAvroSchema, Map<String, Object> values)
```
Comment (skrzypo987) [inline testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java:260]: You can accept `ParsedSchema` interface instead of `TestingAvroSchema` implementation

File: testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java [hunk 7]
```diff
@@ -257,57 +267,64 @@ public String toString()
...
-            private final Schema avroSchema;
+            this.avroSchemaString = requireNonNull(avroSchemaString, "avroSchemaString is null");
+            this.schemaReferences = ImmutableList.copyOf(requireNonNull(schemaReferences, "schemaReferences is null"));
 
-            public TestingAvroSchema(Schema avroSchema)
-            {
-                this.avroSchema = requireNonNull(avroSchema, "avroSchema is null");
-            }
+            Parser parser = new Parser();
+            resolvedReferences.forEach(parser::parse);
```
Comment (skrzypo987) [inline testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java:331]: requireNonNull(resolvedReferences)

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroConfluentContentSchemaReader.java [hunk 8]
```diff
@@ -51,6 +56,32 @@ public void testAvroConfluentSchemaReader()
                 .hasMessage("Could not resolve schema for the 'another-schema' subject");
     }
 
+    @Test
+    public void getAvroSchemaWithReferences()
```
Comment (skrzypo987) [inline plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroConfluentContentSchemaReader.java:60]: test method names should start with `test` unfortunately

File: plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java (hunk 4 above)
Comment (Praveen2112) [reply plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java:55]: Schemas are resolved internally by the `SchemaProvider` implementation. In case of `AvroSchema#getRawSchema` - It gives a fully resolved Schema (which is based on `SchemaReferences` that is passed)

File: plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroConfluentContentSchemaReader.java (hunk 5 above)
Comment (Praveen2112) [reply plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroConfluentContentSchemaReader.java:78]: In some cases it can be union. But here it would be nested. `test` type is referred from the `SchemaRegistry`.

**Review by skrzypo987 — COMMENTED** [review]
Seems ok, ping me after resolving @kooksing issues

**Comment by Praveen2112** [comment]
@kokosing , @skrzypo987 AC

File: testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java [hunk 9]
```diff
@@ -28,6 +28,7 @@
 import io.trino.tempto.fulfillment.table.kafka.ListKafkaDataSource;
```
Comment (kokosing) [inline testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java:28]: Update commit message to:
```
Allow TestingAvroSchema to resolve SchemaReferences
```

It is not a cleanup to me, but a functional change.

**Review by kokosing — APPROVED** [review]

File: testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java [hunk 10]
```diff
@@ -73,32 +72,9 @@
...
-            kafkaTableManager.createImmutable(tableDefinition, tableHandle(tableName).inSchema(KAFKA_SCHEMA));
-        }
-        catch (IOException e) {
-            throw new UncheckedIOException(e);
-        }
-    }
-
     @Test(groups = {KAFKA, PROFILE_SPECIFIC_TESTS}, dataProvider = "catalogs")
     public void testSelectPrimitiveDataType(KafkaCatalog kafkaCatalog, MessageSerializer messageSerializer)
+            throws Exception
```
Comment (lukasz-walkiewicz) [inline testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java:83]: What has changed? Is it the correct commit?

File: testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/catalog/kafka/schema_with_references.avsc [hunk 11]
```diff
@@ -0,0 +1,13 @@
+{
+  "type" : "record",
```
Comment (lukasz-walkiewicz) [inline testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/catalog/kafka/schema_with_references.avsc:2]: Is this the correct formatting for this type of file?

File: plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java [hunk 12]
```diff
@@ -47,7 +51,11 @@ public AvroConfluentContentSchemaReader(SchemaRegistryClient schemaRegistryClien
...
+            checkArgument(schema instanceof AvroSchema, "schema should be an instance of AvroSchema");
+            return Optional.of(schema.rawSchema())
```
Comment (lukasz-walkiewicz) [inline plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java:57]: Can `AvroSchema#rawSchema()` returns null? Haven't found anything indicating that it can't.

**Review by lukasz-walkiewicz — APPROVED** [review]

File: plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java (hunk 12 above)
Comment (Praveen2112) [reply plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java:57]: Ideally it should not return null. Will add `ofNullable` for defensive check

File: testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java (hunk 10 above)
Comment (Praveen2112) [reply testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java:83]: Previously we would throw `UncheckedIOException` so the test method wasn't aware of it.

File: testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/catalog/kafka/schema_with_references.avsc (hunk 11 above)
Comment (Praveen2112) [reply testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/catalog/kafka/schema_with_references.avsc:2]: Checked with other avro specification file in trino. I guess it looks the same

**Review by skrzypo987 — APPROVED** [review]
