### PR TITLE
Fix error location markers for SQL routines

### LINKED ISSUE #21357: Error location markers for SQL routines (functions) are off, may break CLI
Location markers for functions are relative to function definition, not the query scope.

For inline functions this can be reproduced with:

```java
assertFails("""
        WITH FUNCTION correct_function()
        RETURNS integer
        BEGIN
            RETURN 42;
        END,
        FUNCTION return_type_mismatch()
        RETURNS integer
        BEGIN
            RETURN 'not an integer'; -- error comes from here, this is line 9
        END
        VALUES 1
        """)
        .hasErrorCode(TYPE_MISMATCH)
        // TODO Line 4 is inside the correct function, should be line 9
        .hasMessage("line 4:11: Value of RETURN must evaluate to integer (actual: varchar(14))");
```

Invalid error location markers cause Trino CLI to print exceptions (the first stacktrace printed is legit, but the second comes from the CLI itself)

```
$ bin/trino-cli --file my-script.sql
Query 20240402_122642_00001_3g6a8 failed: line 4:121: Value of RETURN must evaluate to integer (actual: bigint)
io.trino.spi.TrinoException: line 4:121: Value of RETURN must evaluate to integer (actual: bigint)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:46)
	at io.trino.sql.routine.SqlRoutineAnalyzer$StatementVisitor.analyzeExpression(SqlRoutineAnalyzer.java:517)
	at io.trino.sql.routine.SqlRoutineAnalyzer$StatementVisitor.visitReturnStatement(SqlRoutineAnalyzer.java:480)
	at io.trino.sql.routine.SqlRoutineAnalyzer$StatementVisitor.visitReturnStatement(SqlRoutineAnalyzer.java:337)
	at io.trino.sql.tree.ReturnStatement.accept(ReturnStatement.java:43)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.routine.SqlRoutineAnalyzer$StatementVisitor.analyzeNodes(SqlRoutineAnalyzer.java:556)
	at io.trino.sql.routine.SqlRoutineAnalyzer$StatementVisitor.visitCompoundStatement(SqlRoutineAnalyzer.java:383)
	at io.trino.sql.routine.SqlRoutineAnalyzer$StatementVisitor.visitCompoundStatement(SqlRoutineAnalyzer.java:337)
	at io.trino.sql.tree.CompoundStatement.accept(CompoundStatement.java:53)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.routine.SqlRoutineAnalyzer.analyze(SqlRoutineAnalyzer.java:156)
	at io.trino.metadata.LanguageFunctionManager$QueryFunctions$LanguageFunctionImplementation.analyzeAndPlan(LanguageFunctionManager.java:422)
	at io.trino.metadata.LanguageFunctionManager$QueryFunctions.addInlineFunction(LanguageFunctionManager.java:261)
	at io.trino.metadata.LanguageFunctionManager.addInlineFunction(LanguageFunctionManager.java:195)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1555)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:522)
	at io.trino.sql.tree.Query.accept(Query.java:118)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:541)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:501)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:490)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:97)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:326)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:224)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:925)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_435_u68_g44799518cfd_1_g24a5e5e____20240402_121033_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.StringIndexOutOfBoundsException: Range [0, 120) out of bounds for length 98
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865)
	at java.base/java.lang.String.substring(String.java:2834)
	at io.trino.cli.Query.renderErrorLocation(Query.java:400)
	at io.trino.cli.Query.renderFailure(Query.java:390)
	at io.trino.cli.Query.renderQueryOutput(Query.java:209)
	at io.trino.cli.Query.renderOutput(Query.java:150)
	at io.trino.cli.Console.process(Console.java:364)
	at io.trino.cli.Console.executeCommand(Console.java:318)
	at io.trino.cli.Console.run(Console.java:182)
	at io.trino.cli.Console.call(Console.java:109)
	at io.trino.cli.Console.call(Console.java:79)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.trino.cli.Trino.main(Trino.java:47)
```

### PR DESCRIPTION
**Pull request by electrum**
Fixes #21357

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix error location markers for SQL routines. ({issue}`21357`)
```

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java [hunk 1]
```diff
@@ -223,40 +223,40 @@ private static void validateArguments(FunctionSpecification function)
...
     }
 
-    private static Optional<String> getLanguage(FunctionSpecification function)
+    private static Optional<Identifier> getLanguage(FunctionSpecification function)
     {
         List<LanguageCharacteristic> language = function.getRoutineCharacteristics().stream()
                 .filter(LanguageCharacteristic.class::isInstance)
                 .map(LanguageCharacteristic.class::cast)
-                .collect(toImmutableList());
+                .toList();
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java:231]: why not `.collect(toImmutableList());` (as it used to be)?

(same below)

if this change is desired, but is a refactor, let's put it in a refactor commit, not in a "Fix ..." commit

File: core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java [hunk 2]
```diff
@@ -223,40 +223,40 @@ private static void validateArguments(FunctionSpecification function)
...
     {
-        Optional<String> language = getLanguage(function);
-        if (language.isPresent() && !language.get().equalsIgnoreCase("sql")) {
-            throw semanticException(NOT_SUPPORTED, function, "Unsupported language: %s", language.get());
-        }
+        getLanguage(function).ifPresent(language -> {
+            if (!language.getValue().equalsIgnoreCase("sql")) {
+                throw semanticException(NOT_SUPPORTED, language, "Unsupported function language: %s", language.getCanonicalValue());
+            }
+        });
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java:248]: Is this refactor or part of the fix? ("Fix position reporting for routine characteristics")

File: core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java [hunk 3]
```diff
@@ -223,40 +223,40 @@ private static void validateArguments(FunctionSpecification function)
...
     {
         List<LanguageCharacteristic> language = function.getRoutineCharacteristics().stream()
                 .filter(LanguageCharacteristic.class::isInstance)
                 .map(LanguageCharacteristic.class::cast)
-                .collect(toImmutableList());
+                .toList();
 
         if (language.size() > 1) {
-            throw semanticException(SYNTAX_ERROR, function, "Multiple language clauses specified");
+            throw semanticException(SYNTAX_ERROR, language.getLast(), "Multiple language clauses specified");
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java:234]: error location at the second one would be even better

**Review by findepi — COMMENTED** [review]
"Fix position reporting for routine characteristics"

File: core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java [hunk 4]
```diff
@@ -92,21 +92,20 @@ public ListenableFuture<Void> execute(CreateFunction statement, QueryStateMachin
...
 
-        String formatted = formatSql(function);
-        verifyFormattedFunction(formatted, function);
-
-        languageFunctionManager.verifyForCreate(session, formatted, functionManager, accessControl);
+        languageFunctionManager.verifyForCreate(session, function, functionManager, accessControl);
 
         String signatureToken = languageFunctionManager.getSignatureToken(function.getParameters());
 
+        String sql = formattedFunction(function);
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java:99]: Formatter may change in the future. Why format before storing?
Add a code comment.

File: core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java [hunk 5]
```diff
@@ -122,8 +121,9 @@ public ListenableFuture<Void> execute(CreateFunction statement, QueryStateMachin
         return immediateVoidFuture();
     }
 
-    private void verifyFormattedFunction(String sql, FunctionSpecification function)
+    private String formattedFunction(FunctionSpecification function)
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java:124]: This also verifies. `verifiedFormattedfunction`?

File: core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionManager.java [hunk 6]
```diff
@@ -428,6 +440,24 @@ private synchronized void analyzeAndPlan(AccessControl accessControl)
...
             }
 
+            private SqlRoutineAnalysis analyze(FunctionContext context)
+            {
+                try {
+                    return analyzer.analyze(context.session(), context.accessControl(), functionSpecification);
+                }
+                catch (TrinoException e) {
+                    if (identityLoader.isEmpty() || (e instanceof LanguageFunctionAnalysisException)) {
+                        throw e;
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionManager.java:450]: What is the `identityLoader.isEmpty()` condition for?
Unless this is obvious to the reader, add a code comment

File: testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java [hunk 7]
```diff
@@ -6728,15 +6732,15 @@ FUNCTION a(x integer) RETURNS integer RETURN b(x),
...
+                .failure().hasMessage("line 2:48: Function 'b' not registered");
 
         // inline function cannot be recursive
         // note: mutual recursion is not supported either, but it is not tested due to the forward declaration limitation above
         assertThat(query("""
                 WITH FUNCTION a(x integer) RETURNS integer RETURN a(x)
                 SELECT a(10)
                 """))
-                .failure().hasMessage("line 3:8: Recursive language functions are not supported: a(integer):integer");
+                .failure().hasMessage("Recursive language functions are not supported: a(integer):integer");
```
Comment (findepi) [inline testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java:6743]: This one could have location marker, because it's an inline funciton.

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java [hunk 8]
```diff
@@ -6566,9 +6566,13 @@ public void testCreateFunction()
...
         assertUpdate("CREATE FUNCTION " + recursive2 + "(x integer) RETURNS integer RETURN " + recursive1 + "(x)");
         assertUpdate("CREATE OR REPLACE FUNCTION " + recursive1 + "(x integer) RETURNS integer RETURN " + recursive2 + "(x)");
-        assertQueryFails("SELECT " + recursive1 + "(42)", "line 3:8: Recursive language functions are not supported: " + recursive1 + "\\(integer\\):integer");
+        assertQueryFails("SELECT " + recursive1 + "(42)", "Recursive language functions are not supported: " + recursive1 + "\\(integer\\):integer");
+        assertQueryFails("SELECT " + recursive2 + "(42)", "Recursive language functions are not supported: " + recursive2 + "\\(integer\\):integer");
         assertUpdate("DROP FUNCTION " + recursive1 + "(integer)");
         assertUpdate("DROP FUNCTION " + recursive2 + "(integer)");
+
+        // verify error location reporting
+        assertQueryFails("CREATE FUNCTION bad() RETURNS varchar RETURN 8", "line 1:46: Value of RETURN must evaluate to varchar \\(actual: integer\\)");
```
Comment (findepi) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:6575]: Doesn't need to be in BCT, provided that it doesn't exercise the connector

**Review by findepi — COMMENTED** [review]
"Fix error location markers for SQL routines"

**Comment by findepi** [comment]
thanks for fixing this

File: core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java (hunk 4 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java:99]: This is an AST node. The formatting is for serialization.

File: testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java (hunk 7 above)
Comment (electrum) [reply testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java:6743]: It could, but I'm not sure how to do that. We don't have access to the original AST at this point.

**Review by findepi — APPROVED** [review]
% previous comments

File: core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java (hunk 2 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java:248]: This is changed because `getLanguage()` now returns `Optional<Identifier>` so that the position can be reported

File: core/trino-main/src/test/java/io/trino/sql/query/TestInlineFunctions.java [hunk 9]
```diff
@@ -60,34 +60,31 @@ public void teardown()
...
                     RETURN x * 2
-                SELECT my_func(nationkey) 
-                FROM nation 
+                SELECT my_func(nationkey)
+                FROM nation
                 WHERE nationkey = 1
                 """))
                 .matches("VALUES BIGINT '2'");
 
-        assertThat(assertions.query(
```
[the remark this answers is not in the document]
Comment (findepi) [reply core/trino-main/src/test/java/io/trino/sql/query/TestInlineFunctions.java:74]: > You need to turn on the "Align when multiline" in the "Text blocks" section in IntelliJ to get reasonable formatting for all scenarios:

if this is expected to be enabled, should it be part of https://github.com/airlift/codestyle?

File: core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java (hunk 3 above)
Comment (findepi) [reply core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java:234]: it also doesn't cost more to call `.get(1)`

Comment (electrum) [reply core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java:234]: Good point, fixed

File: core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java (hunk 5 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java:124]: The verification is an internal check for the function implementation. It's not verifying something on the caller's behalf, so signaling it to the caller (or reader of the calling code) doesn't seem useful.

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java (hunk 8 above)
Comment (electrum) [reply testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:6575]: Good point, this will fail before we actually try to create it

File: core/trino-main/src/test/java/io/trino/sql/query/TestInlineFunctions.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (electrum) [reply core/trino-main/src/test/java/io/trino/sql/query/TestInlineFunctions.java:74]: Thanks, this issue has bugged me for a while

File: core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionManager.java (hunk 6 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionManager.java]: I extracted this to a method with a comment.

File: core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java (hunk 4 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java]: I realize now that the `formatted` part of the name is not useful. I named it that originally because it calls `formatSql`. The fact that it's "formatting" in the "make the SQL look pretty" sense is not important. I renamed it to `functionToSql` as that reflects the purpose.
