### PR TITLE
Throwing a TrinoException instead of ArithmeticException on sum aggregation of decimals

### LINKED ISSUE #20227: Internal error on overflow in sum aggregate of decimal
If a sum aggregate of decimals overflows an internal error is thrown. This should instead be a user error and trigger `NUMERIC_VALUE_OUT_OF_RANGE` instead, similar to:
```
select sum(n) from (values 1, 9223372036854775807) s(n);
```

To reproduce:
```
select sum(n) from (values decimal '1', decimal '99999999999999999999999999999999999999') s(n);
```

The exception thrown is:
```
java.lang.ArithmeticException: Decimal overflow
	at io.trino.operator.aggregation.DecimalSumAggregation.outputDecimal(DecimalSumAggregation.java:123)
	at io.trino.$gen.sumAccumulator_20231227_105506_1994.evaluateFinal(Unknown Source)
	at io.trino.operator.aggregation.Aggregator.evaluate(Aggregator.java:93)
	at io.trino.operator.AggregationOperator.getOutput(AggregationOperator.java:161)
        ...
```

### PR DESCRIPTION
**Pull request by macohen**
## Description
Throwing a TrinoException instead of ArithmeticException on sum aggregation of decimals

## Additional context and related issues
Closes #20227 

## Release notes

( x ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java [hunk 1]
```diff
@@ -120,16 +122,20 @@ public static void outputDecimal(@AggregationState LongDecimalWithOverflowState
...
 
             long[] decimal = state.getDecimalArray();
             int offset = state.getDecimalArrayOffset();
 
             long rawHigh = decimal[offset];
             long rawLow = decimal[offset + 1];
-
-            Decimals.throwIfOverflows(rawHigh, rawLow);
+            try {
+                Decimals.throwIfOverflows(rawHigh, rawLow);
```
Comment (electrum) [inline core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java:134]: Let's inline this method and throw the proper exception directly. Then mark the method as `@Deprecated(forRemoval = true)` since the only caller is in the same class.

**Comment by electrum** [comment]
Please change the commit title:

> Fix error code for overflow on sum aggregation of decimals

File: core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java (hunk 1 above)
Comment (macohen) [reply core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java:134]: oh. nice. will do. thanks.

Comment (macohen) [reply core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java:134]: @electrum, do you still want me to update this given that it is being called in two places?

**Comment by macohen** [comment]
My CLA was accepted. Can the checks be rerun? And can this be merged, @electrum? Please forgive my excitement about getting this in. :)

**Comment by wendigo** [comment]
@cla-bot recheck

File: core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java (hunk 1 above)
Comment (electrum) [reply core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java:134]: Yes, please inline the existing usages and mark the method as deprecated. I think that will make the code clearer.

File: core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java [hunk 2]
```diff
@@ -291,10 +291,13 @@ public static Int128 valueOf(BigInteger value)
         catch (Exception e) {
             throw new ArithmeticException("Decimal overflow");
         }
-        throwIfOverflows(result.getHigh(), result.getLow());
+        if (overflows(result.getHigh(), result.getLow())) {
+            throw new ArithmeticException("Decimal overflow");
```
Comment (macohen) [inline core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java:295]: should this also throw a TrinoException now? What about the exception caught on 291?

Comment (wendigo) [reply core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java]: yes, please throw here as well

**Comment by mosabua** [comment]
👋 @macohen could you ensure all comments are addressed and rebase ?

**Comment by macohen** [comment]
> 👋 @macohen could you ensure all comments are addressed and rebase ?

I'll try to get to this in the next week. I came across a problem where a test fails when throwing the TrinoException on 295. I'll get more info in another comment today or tomorrow.

**Comment by macohen** [comment]
I'm having trouble running just the trino-oracle tests so I'm not able to figure out what's going on there. Is it possible it's flaky? More likely, I'm doing something wrong so I could use some help, please. From the project root, I ran:  

```
./mvnw  -am -pl ./plugin/trino-oracle -U clean compile test
```

which failed on trino-grammar due to checkstyle violations. I

**Review by wendigo — APPROVED** [review]
