### PR TITLE
Fix failure when hidden partition column name conflicted in Iceberg

### LINKED ISSUE #22351: Iceberg table partition creation fails due to column name conflict with  Trino's generated partitioning column name
Sample DDL:
``` sql
create table lakehouse."default".mattest (
	starttime timestamp,
	starttime_day varchar
) with (partitioning = array['day(starttime)']);
```
Relevant stacktrace

```log
Query failed (#20240610_193515_00091_n2dt5): Unable to parse partitioning value: Cannot create partition from name that exists in schema: starttime_day
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:601)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:504)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:511)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:963)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4134)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:190)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5148)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:114)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Query failed (#20240610_193515_00091_n2dt5): Unable to parse partitioning value: Cannot create partition from name that exists in schema: starttime_day
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:294)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:254)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Unknown Source)
	at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:179)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.trino.spi.TrinoException: Unable to parse partitioning value: Cannot create partition from name that exists in schema: starttime_day
	at io.trino.plugin.iceberg.PartitionFields.parsePartitionFields(PartitionFields.java:69)
	at io.trino.plugin.iceberg.IcebergMetadata.getNewTableLayout(IcebergMetadata.java:917)
	at io.trino.plugin.iceberg.IcebergMetadata.createTable(IcebergMetadata.java:884)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:457)
	at io.trino.tracing.TracingConnectorMetadata.createTable(TracingConnectorMetadata.java:394)
	at io.trino.metadata.MetadataManager.createTable(MetadataManager.java:818)
	at io.trino.tracing.TracingMetadata.createTable(TracingMetadata.java:409)
	at io.trino.execution.CreateTableTask.internalExecute(CreateTableTask.java:297)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:126)
	at io.trino.execution.CreateTableTask.execute(CreateTableTask.java:92)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:146)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:570)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:545)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1137)
	at io.trino.$gen.Trino_443____20240604_192937_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: Cannot create partition from name that exists in schema: starttime_day
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
	at org.apache.iceberg.PartitionSpec$Builder.checkAndAddPartitionName(PartitionSpec.java:380)
	at org.apache.iceberg.PartitionSpec$Builder.checkAndAddPartitionName(PartitionSpec.java:358)
	at org.apache.iceberg.PartitionSpec$Builder.day(PartitionSpec.java:461)
	at org.apache.iceberg.PartitionSpec$Builder.day(PartitionSpec.java:471)
	at io.trino.plugin.iceberg.PartitionFields.lambda$parsePartitionField$3(PartitionFields.java:78)
	at io.trino.plugin.iceberg.PartitionFields.tryMatch(PartitionFields.java:110)
	at io.trino.plugin.iceberg.PartitionFields.parsePartitionField(PartitionFields.java:78)
	at io.trino.plugin.iceberg.PartitionFields.parsePartitionFields(PartitionFields.java:64)
	... 20 more

```

I think having a way to alias/name the partitioning column can help resolve this. An example on [spark side](https://iceberg.apache.org/docs/nightly/spark-ddl/#alter-table-add-partition-field)

Slack thread, https://trinodb.slack.com/archives/C0305TQ05KL/p1717577005413109.

Tagging @findinpath

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Iceberg connector caused query failure when the hidden partition column name conflicts with other columns.

The approach is different from Spark. They throw an exception when conflicts happen:
```sql
CREATE TABLE test (ts timestamp, ts_day int) USING iceberg PARTITIONED BY (day(ts));
Failed in [create table test (ts timestamp, ts_day int) using iceberg partitioned by (day(ts))]
java.lang.IllegalArgumentException: Cannot create partition from name that exists in schema: ts_day
```

Fixes #22351

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Iceberg
* Fix failure when hidden partition name conflicted. ({issue}`22351`)
```

### CODE REVIEW

**Comment by findepi** [comment]
I am not against supporting explicit aliases, but i also think that auto-generated names shouldn't conflict with user-provided names without extra effort from the user, so I am not convinced this PR is needed.

IMO  the logic in `parsePartitionField` should automatically deconflict the names. 

Once we have this, the only remaning source of name collisions is when user wants to add a new column that overlaps a partitioning field. If we wanted to solve this problem too, the right resolution for this would be allow user to rename existing partitioning field.

**Review by wendigo — APPROVED** [review]

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionFields.java [hunk 1]
```diff
@@ -70,16 +70,59 @@ public static PartitionSpec parsePartitionFields(Schema schema, List<String> fie
...
-                tryMatch(field, BUCKET_PATTERN, match -> builder.bucket(fromIdentifierToColumn(match.group(1)), parseInt(match.group(2)))) ||
-                tryMatch(field, TRUNCATE_PATTERN, match -> builder.truncate(fromIdentifierToColumn(match.group(1)), parseInt(match.group(2)))) ||
-                tryMatch(field, VOID_PATTERN, match -> builder.alwaysNull(fromIdentifierToColumn(match.group(1))));
+        for (int i = 1; i < schema.columns().size() + fields.size(); i++) {
+            try {
+                parsePartitionField(builder, field, i == 1 ? "" : "_" + i);
+                return;
+            }
+            catch (IllegalArgumentException e) {
+                if (e.getMessage().contains("Cannot create partition from name that exists in schema")
```
Comment (findinpath) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionFields.java:81]: Did you by chance open a ticket on iceberg to have a more structured way of identifying such a problem?
