### PR TITLE
Fix failure when setting NULL in UPDATE statement in JDBC-based connectors

### LINKED ISSUE #24204: Unable to update Postgresql column to null in Trino
Getting the error message "Value is missing" when an SQL update attempts to set a NULLABLE column to NULL. 

```
trino:public> update test set updated_by=null  where id='f75afcdb-6545-4675-b341-4fdf17a9d14b';

Query 20241120_170254_00032_x2wwq, FAILED, 1 node
Splits: 1 total, 0 done (0.00%)
0.04 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20241120_170254_00032_x2wwq failed: Value is missing
```

The same command works when directly use the psql.

```
db=# update test set updated_by=null where id='f75afcdb-6545-4675-b341-4fdf17a9d14b';
UPDATE 1
```

Trino version: 462
Postgresql server 16.4

### PR DESCRIPTION
**Pull request by chenjian2664**
## Description

Close #24204 

## Release notes

```markdown
## ClickHouse, Ignite, MariaDB, MySQL, Oracle, Phoenix, PostgreSQL, Redshift, SingleStore, Snowflake, SQL Server, Vertica
* Fix failure when updating values with `NULL`. ({issue}`24204`)
```

### CODE REVIEW

File: plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java [hunk 1]
```diff
@@ -1868,6 +1868,10 @@ public void testConstantUpdateWithVarcharEqualityPredicates()
             }
             assertUpdate("UPDATE " + table.getName() + " SET col1 = 20 WHERE col2 = 'A'", 1);
             assertQuery("SELECT * FROM " + table.getName(), "VALUES (1, 'a'), (20, 'A')");
+
+            // test update set to null
+            assertUpdate("UPDATE " + table.getName() + " SET col1 = null WHERE col2 = 'A'", 1);
```
Comment (ebyhr) [inline plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java:1873]: A predicate isn't necessary for https://github.com/trinodb/trino/issues/24204 and we should test with all connectors. Please add a new test to `BaseConnectorTest` instead.

File: plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java [hunk 2]
```diff
@@ -951,6 +951,38 @@ public void testUpdate()
     @Override
     public void testUpdateMultipleCondition() {}
 
+    /**
+     * This test fails intermittently because Kudu doesn't have strong enough
+     * semantics to support writing from multiple threads.
+     */
+    @Test
+    @Disabled
```
Comment (chenjian2664) [inline plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java:959]: Disable the test, same as the current `update` related tests in the kudu

**Comment by ebyhr** [comment]
/test-with-secrets sha=bdfaed330c96e2b7c16a7609c8ab88ad361c1b61

File: plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java (hunk 2 above)
Comment (ebyhr) [inline plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java:959]: The following test body is redundant if we disable the test.

Comment (chenjian2664) [reply plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java:959]: Do you want me to remove

Comment (ebyhr) [reply plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java:959]: Ideally, we should run this test by isolating other operations with `executeExclusively`.

**Comment by chenjian2664** [comment]
@ebyhr the test addressed, would you mind to have a look

**Comment by chenjian2664** [comment]
@ebyhr Gentle reminder, the pr is ready to review

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java [hunk 3]
```diff
@@ -5013,6 +5013,43 @@ public void testUpdateMultipleCondition()
         }
     }
 
+    @Test
+    public void testUpdateWithNullValues()
```
Comment (ebyhr) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:5017]: Please check the existing `testUpdateNotNullColumn` test. Some assertion look redundant.

**Review by hashhar — APPROVED** [review]

File: testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java [hunk 4]
```diff
@@ -4999,6 +4999,43 @@ public void testUpdateMultipleCondition()
...
+        }
+
+        if (!hasBehavior(SUPPORTS_NOT_NULL_CONSTRAINT)) {
+            return;
+        }
+
+        try (TestTable table = createTestTableForWrites("test_update_nulls", "(nullable_col1 INTEGER, nullable_col2 INTEGER, not_null_col INTEGER NOT NULL, pk INT)", "pk")) {
+            String tableName = table.getName();
+            assertUpdate("INSERT INTO " + tableName + " VALUES (1, 1, 1, 1), (2, 2, 2, 2)", 2);
+            assertUpdate("UPDATE " + tableName + " SET nullable_col1 = 10 WHERE not_null_col = 1", 1);
```
Comment (ebyhr) [inline testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:5024]: Why do we need this assertion here? This UPDATE doesn't set NULL even though the test name is `testUpdateWithNullValues`.

Comment (chenjian2664) [reply testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:5024]: To make the comparsion, here is to make sure the normal update works,(make sure the fix not change the original branch's logic).

Comment (ebyhr) [reply testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:5024]: We have `testUpdate` for normal update. I still don't understand the motivation.

Comment (chenjian2664) [reply testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java:5024]: updated, since the `testUpdate` is covered the normal case.
