### PR TITLE
Fix bug Delta column operations erases its properties on uppercase names

### LINKED ISSUE #18013: Column properties are ignored when the column name contains uppercase characters
On Databricks/Spark

```
CREATE TABLE findinpathtable(
eventId BIGINT COMMENT 'event identifier comment',
data STRING
)
USING DELTA
LOCATION 's3://like/my/comment' ;
```

On Trino

```
describe findinpathtable;
```

Due to the fact that the column `eventId` is saved under this name in the metadata string, its comment doesn't get shown in the `DESCRIBE`  statement.

Same issue for the statement:
```
select *, comment from mycatalog.information_schema.columns
where table_catalog = 'mycatalog' and table_schema = 'myschema' and table_name = 'findinpathtable';
```

Other operations may be affected as well.
Check for the usages of the method `io.trino.plugin.deltalake.transactionlog.DeltaLakeSchemaSupport#getColumnProperties`

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #18013
Fix the following issue
* Show column comments, NOT NULL constraints correctly when column name contains uppercase characters. Previously, it returned incorrect information.
* Fix issue when ADD COLUMN statement erases existing column properties when the column name contained uppercase characters.
* Fix issue when COMMENT ON COLUMN statement erases existing column properties when the column name contained uppercase characters.
* Store the exact column names in column statistics

The commit isn't separated because the code is tightly related to each other. 

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

```markdown
# Delta Lake
* Show column comments, `NOT NULL` constraint correctly when the column name contains uppercase characters. ({issue}`issuenumber`)
* Fix `ADD COLUMN` statement not to delete column properties when the column name contains uppercase characters. ({issue}`issuenumber`)
* Fix `COMMENT ON COLUMN` statement not to delete column properties when the column name contains uppercase characters. ({issue}`issuenumber`)
```

### CODE REVIEW

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java [hunk 1]
```diff
@@ -692,6 +697,35 @@ private void testColumnMappingModeAddComplexColumn(String mode, Consumer<String>
         }
     }
 
+    @Test(groups = {DELTA_LAKE_DATABRICKS, DELTA_LAKE_OSS, DELTA_LAKE_EXCLUDE_73, DELTA_LAKE_EXCLUDE_91, PROFILE_SPECIFIC_TESTS}, dataProvider = "columnMappingDataProvider")
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java:700]: I don't like mixing up two purposes in a test. Added two tests instead.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 2]
```diff
@@ -3350,12 +3349,12 @@ private static Domain allValues(Type type, boolean includeNull)
         return Domain.notNull(type);
     }
 
-    private static DeltaLakeColumnHandle toColumnHandle(ColumnMetadata column, OptionalInt fieldId, String physicalName, Type physicalType, Collection<String> partitionColumns)
+    private static DeltaLakeColumnHandle toColumnHandle(String name, Type type, OptionalInt fieldId, String physicalName, Type physicalType, Collection<String> partitionColumns)
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:3352]: It may affect access control of `table_changes` function. Updated.

**Comment by ebyhr** [comment]
@findepi Updated commit and PR title & description.

**Review by findepi — COMMENTED** [review]
(not full review)

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 3]
```diff
@@ -680,7 +681,7 @@ public Iterator<TableColumnsMetadata> streamTableColumns(ConnectorSession sessio
                         Map<String, Boolean> columnsNullability = getColumnsNullability(metadata);
                         Map<String, String> columnGenerations = getGeneratedColumnExpressions(metadata);
                         List<ColumnMetadata> columnMetadata = getColumns(metadata).stream()
-                                .map(column -> getColumnMetadata(column, columnComments.get(column.getColumnName()), columnsNullability.getOrDefault(column.getBaseColumnName(), true), columnGenerations.get(column.getBaseColumnName())))
+                                .map(column -> getColumnMetadata(column, columnComments.get(column.getBaseColumnName()), columnsNullability.getOrDefault(column.getBaseColumnName(), true), columnGenerations.get(column.getBaseColumnName())))
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:684]: > columnComments has non-lowercased (original) keys.

Right. 

> column.getBaseColumnName() is (now) lowercased, so a mismatch.

getBaseColumnName **_was_** lowercased previously. It returns the original column names after this change.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 4]
```diff
@@ -1260,26 +1262,12 @@ public void setColumnComment(ConnectorSession session, ConnectorTableHandle tabl
...
-
         try {
             long commitVersion = deltaLakeTableHandle.getReadVersion() + 1;
 
-            List<String> partitionColumns = getPartitionedBy(tableMetadata.getProperties());
-
-            ImmutableList.Builder<String> columnNames = ImmutableList.builderWithExpectedSize(tableMetadata.getColumns().size());
-            ImmutableMap.Builder<String, Object> columnTypes = ImmutableMap.builderWithExpectedSize(tableMetadata.getColumns().size());
-            for (ColumnMetadata columnMetadata : tableMetadata.getColumns()) {
-                if (columnMetadata.isHidden()) {
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1273]: The previous logic used `getTableMetadata` and `getPartitionedBy` that lowercased column names internally.

**Comment by findepi** [comment]
Thanks for working on this. Even though the work is limited to Delta, it shows how lower-casing of String is a hard problem (#17).

I think it would help review & ensure we're doing the right thing if we can somehow express which `String` values or map keys are lower-cased and which are original. Perhaps practically all should be original except when interfacing with SPI, so we should eradicate most of `toLowerCase` calls (still many present in current state of this PR). If we cannot eradicate them, maybe we use some annotation or separate types classes as a demarkation between lower-cased and original, but at this point removing most of lower-casing looks more appealing to me.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java [hunk 5]
```diff
@@ -103,7 +103,7 @@ public List<String> getPartitionedBy()
     {
         return getInputColumns().stream()
                 .filter(column -> column.getColumnType() == PARTITION_KEY)
-                .map(DeltaLakeColumnHandle::getColumnName)
+                .map(DeltaLakeColumnHandle::getBaseColumnName)
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java:106]: To return the original column names. The subsequent `DeltaLakeParquetSchemas#createParquetSchemaMapping` expects the original names.

[the remark this answers is not in the document]
Comment (findepi) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java:106]: why `DeltaLakeColumnHandle::getColumnName` would lower-case?

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 6]
```diff
@@ -2994,7 +2993,7 @@ private void updateTableStatistics(
     private static String toPhysicalColumnName(String columnName, Optional<Map<String, String>> physicalColumnNameMapping)
     {
         if (physicalColumnNameMapping.isPresent()) {
-            String physicalColumnName = physicalColumnNameMapping.get().get(columnName);
+            String physicalColumnName = physicalColumnNameMapping.get().get(columnName.toLowerCase(ENGLISH));
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:2999]: The `columnName` variable is lowercase when it comes from `ComputedStatistics`. Added the code comment.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnHandle.java [hunk 7]
```diff
@@ -159,7 +160,7 @@ public boolean equals(Object obj)
     public String getColumnName()
     {
         checkState(isBaseColumn(), "Unexpected dereference: %s", this);
-        return baseColumnName;
+        return baseColumnName.toLowerCase(ENGLISH);
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnHandle.java]: I was trying to preserve the previous behavior for some usages, e.g. access control in TableChangesFunction. 
Moved this `toLowerCase` to TableChangesFunction.

**Comment by ebyhr** [comment]
Addressed comments. Removed `toLowerCase` calls from this PR as much as possible.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 8]
```diff
@@ -1606,15 +1587,23 @@ private void appendTableEntries(
...
+        Map<String, String> toOriginalColumnNames = originalColumnNames.stream()
+                .collect(toImmutableMap(name -> name.toLowerCase(ENGLISH), identity()));
         for (DataFileInfo info : dataFileInfos) {
             // using Hashmap because partition values can be null
             Map<String, String> partitionValues = new HashMap<>();
             for (int i = 0; i < partitionColumnNames.size(); i++) {
                 partitionValues.put(partitionColumnNames.get(i), info.getPartitionValues().get(i));
             }
+
+            Optional<Map<String, Object>> minStats = toOriginalColumnNames(info.getStatistics().getMinValues(), toOriginalColumnNames);
```
Comment (findepi) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1602]: `toOriginalColumnNames` has this comment: "Lowercase column names because statistics generated by Trino has lowercase names"
yet, we're operating on `DataFileInfo` that Delta connector created (not engine)

are they lowercase because `ColumnChunkMetaData.getPath` ends up being lowercase in 
https://github.com/trinodb/trino/blob/e26bf49d57cc596014b051485c7e0898d20798d5/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java#L218?

please update the code comment in `toOriginalColumnNames`

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 9]
```diff
@@ -1624,12 +1613,21 @@ private static void appendAddFileEntries(TransactionLogWriter transactionLogWrit
...
                             info.getCreationTime(),
                             dataChange,
-                            Optional.of(serializeStatsAsJson(info.getStatistics())),
+                            Optional.of(serializeStatsAsJson(statisticsWithExactNames)),
                             Optional.empty(),
                             ImmutableMap.of()));
         }
     }
 
+    private static Optional<Map<String, Object>> toOriginalColumnNames(Optional<Map<String, Object>> statistics, Map<String, String> exactColumnNames)
```
Comment (findepi) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1622]: exactColumnNames -> lowerCaseToExactColumnNames (or toOriginalColumnNames)
`Map<String, String>` -> `Map</* lowercase*/ String, String>` (or switch to `CanonicalColumnName` as map keys)

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 10]
```diff
@@ -2764,7 +2764,8 @@ public void validateScan(ConnectorSession session, ConnectorTableHandle handle)
                 }
                 Set<String> referencedColumns =
                         deltaLakeTableHandle.getConstraintColumns().stream()
-                                .map(DeltaLakeColumnHandle::getBaseColumnName)
+                                // Lowercase column names because the above partitionColumns variable uses canonical names
+                                .map(column -> column.getBaseColumnName().toLowerCase(ENGLISH))
```
Comment (findepi) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:2768]: "above partitionColumns variable uses canonical names" 

i forgot that "canonical" stands for "lowercase".
it's very unfortunate.
let's rename `io.trino.plugin.deltalake.transactionlog.MetadataEntry#getCanonicalPartitionColumns` to `getLowercasePartitionColumns`

here, we should remove toLowerCase and switch to `getOriginalPartitionColumns`

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (findepi) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:3040]: it's not obvious that keys in `physicalColumnNameMapping` are lowercase.

can we map columnName to original/exact column name and then map to physical name as separate step?

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java [hunk 11]
```diff
@@ -187,7 +188,8 @@ public DataFileInfo getDataFileInfo()
     {
         TrinoInputFile inputFile = fileSystem.newInputFile(rootTableLocation.appendPath(relativeFilePath));
         Map<String, Type> dataColumnTypes = columnHandles.stream()
-                .collect(toImmutableMap(DeltaLakeColumnHandle::getBasePhysicalColumnName, DeltaLakeColumnHandle::getBasePhysicalType));
+                // Lowercase because the subsequent logic expects lowercase
```
Comment (findepi) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java:191]: `Map<String, Type>` -> `Map</* lowercase */ String, Type>`

same in `readStatistics` & `mergeStats` params

.. or switch to `CanonicalColumnName` as map keys

**Comment by findepi** [comment]
i looked thru where we still lowercase and added some comments

general comments

- we have `CanonicalColumnName` to convey case-insensitive matches. The class should probably be renamed because these days we wouldn't call "lowercase" and "canonical" the same thing.
- `DeltaLakeColumnMetadata.getName` is confusing as it returns lowercase name, implicitly.
   - the class should be refactored not to have `ColumnMetadata`  as a field; instead it should have `toColumnMetadata` method.
   - the `getName` should return actual name (jusjt like `DeltaLakeColumnHandle.getColumnName`), and then we don't need separate `getOriginalName`.


cc @alexjo2144 @findinpath

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java (hunk 8 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1602]: Updated the code comment. Parquet file contains the original names, but it's lowercased when reading the metadata at
https://github.com/trinodb/trino/blob/023f8b4cb5fc83615aae8cb30da31ffd61004603/lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java#L139-L141

**Comment by ebyhr** [comment]
CI hit #17512

**Review by findepi — APPROVED** [review]

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java [hunk 12]
```diff
@@ -120,7 +120,7 @@ public List<String> getOriginalPartitionColumns()
      * For use in read-path. Returns lowercase partition column names.
      */
     @JsonIgnore
-    public List<String> getCanonicalPartitionColumns()
+    public List<String> getLowercasePartitionColumns()
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java:123]: IDE marks it as unused

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogUtil.java [hunk 13]
```diff
@@ -42,8 +41,7 @@ public static Map<String, Optional<String>> canonicalizePartitionValues(Map<Stri
     {
         return partitionValues.entrySet().stream()
                 .collect(toImmutableMap(
-                        // canonicalize partition keys to lowercase so they match column names used in DeltaLakeColumnHandle
-                        entry -> canonicalizeColumnName(entry.getKey()),
+                        Map.Entry::getKey,
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogUtil.java:44]: Is this method still needed?
Same question for the field `AddFileEntry#canonicalPartitionValues` .

We don't have any canonicalization anymore here.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java [hunk 14]
```diff
@@ -88,6 +91,40 @@ public void testUpdateTableWithCdf()
...
+                    .add(row("testValue2", 2, "insert", 1L))
+                    .add(row("testValue3", 3, "insert", 1L))
+                    .add(row("testValue3", 3, "update_preimage", 2L))
+                    .add(row("testValue3", 5, "update_postimage", 2L))
+                    .build();
+            assertThat(onDelta().executeQuery("SELECT col1, updated_column, _change_type, _commit_version " +
+                    "FROM table_changes('default." + tableName + "', 0)"))
+                    .containsOnly(expectedRows);
+            assertThat(onTrino().executeQuery("SELECT col1, updated_column, _change_type, _commit_version " +
+                            "FROM TABLE(delta.system.table_changes('default', '" + tableName + "'))"))
```
Comment (findinpath) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java:120]: nit: the formatting of the statement onTrino seems slightly different than the formatting for onDelta

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java [hunk 15]
```diff
@@ -692,6 +697,35 @@ private void testColumnMappingModeAddComplexColumn(String mode, Consumer<String>
...
+        onDelta().executeQuery("" +
+                "CREATE TABLE default." + tableName +
+                " (UPPER_CASE INT)" +
+                " USING delta" +
+                " LOCATION 's3://" + bucketName + "/databricks-compatibility-test-" + tableName + "'" +
+                " TBLPROPERTIES (" +
+                " 'delta.columnMapping.mode' = '" + mode + "'" +
+                ")");
+        try {
+            onDelta().executeQuery("INSERT INTO default." + tableName + " VALUES (1)");
```
Comment (findinpath) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java:715]:
```suggestion
onDelta().executeQuery("INSERT INTO default." + tableName + " VALUES 1");
```

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java (hunk 11 above)
Comment (findinpath) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java:191]: Can we switch back to the original names here instead of doing it remotely in `io.trino.plugin.deltalake.DeltaLakeMetadata#appendAddFileEntries` ?

**Review by findinpath — APPROVED** [review]

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java (hunk 12 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java:123]: This method is used by non-test methods as well. 

Screenshot 2023-08-07 at 15 27 01

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogUtil.java (hunk 13 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogUtil.java:44]: It's still needed because the value is still canonicalized in this method.

**Comment by mosabua** [comment]
Can you confirm that this does NOT need release notes entries and the suggested text in the description is redundant @ebyhr ?

**Comment by ebyhr** [comment]
@mosabua This PR fixes user-facing issues. I updated the PR description.

**Comment by mosabua** [comment]
ok .. thanks .. @colebow can you run with this now that you are back ;-)
