### PR TITLE
Retry Spark query when minReplication error happened

### LINKED ISSUE #13601: TestIcebergSparkCompatibility test methods became flaky recently
Some tests in `TestIcebergSparkCompatibility`  are failing with 
`could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and no node(s) are excluded in this operation`

There are retries for that in Hive product tests. Maybe similar mechanism can be added here?

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #13601

## Documentation

(x) No documentation is needed.

## Release notes

(x) No release notes entries required.

### CODE REVIEW

**Comment by ebyhr** [comment]
`could only be written to 0 of the 1 minReplication nodes` happened with `Unsupported table change: Self-suppression not permitted`, not `Writing job aborted` error.

**Comment by ebyhr** [comment]
```
io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: Can not rename the managed table('`default`.`test_trino_reading_migrated_nested_data_8wla2ykl5pms_BACKUP_`'). The associated location('hdfs://hadoop-master:9000/user/hive/warehouse/test_trino_reading_migrated_nested_data_8wla2ykl5pms') already exists.
```
https://github.com/trinodb/trino/runs/7915590576

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/SparkTestUtils.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+    public static final RetryPolicy<QueryResult> MIN_REPLICATION_ERROR_RETRY_POLICY = new RetryPolicy<QueryResult>()
+            .handleIf(SparkTestUtils::isMinReplicationError)
+            .withBackoff(1, 10, ChronoUnit.SECONDS)
+            .withMaxRetries(30)
+            .onRetry(event -> log.warn(event.getLastFailure(), "Query failed on attempt %d, will retry.", event.getAttemptCount()));
+
+    private static boolean isMinReplicationError(Throwable throwable)
+    {
+        return Throwables.getStackTraceAsString(throwable).contains("could only be written to 0 of the 1 minReplication");
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/SparkTestUtils.java:35]: That may depend on Hadoop client version bundled.
That's probably whyb io.trino.tests.product.hive.HiveProductTest#ERROR_COMMITTING_WRITE_TO_HIVE_MATCH is an OR.

What about reusing that pattern, perhaps moving it out of the Hive-specific class (into some Hadoop-related class)?

**Review by findepi — APPROVED** [review]
