### PR TITLE
Store physical partition name in Delta CREATE TABLE AS SELECT

### LINKED ISSUE #18661: Cannot read partition & id or name column mapping mode tables created by `CREATE TABLE AS SELECT`
Transaction log created by `CREATE TABLE AS SELECT` is incorrect when it's partitioned with id or name column mapping mode. 
```sql
CREATE TABLE test  WITH (column_mapping_mode = 'name',partitioned_by = ARRAY['b']) AS 
SELECT 1 AS a, 2 AS b;
```

```
SELECT * FROM test;
io.trino.spi.TrinoException: DELTA_LAKE_BAD_DATA
	at io.trino.plugin.deltalake.DeltaLakePageSource.getNextPage(DeltaLakePageSource.java:189)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:299)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:555)
	at io.trino.$gen.Trino_testversion____20230813_223059_75.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #18661

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Delta Lake
* Fix writing incorrect transaction log in case of partitioned tables with `id` or `name` column mapping mode. ({issue}`18661`)
```

### CODE REVIEW

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 1]
```diff
@@ -1401,7 +1405,7 @@ public void dropColumn(ConnectorSession session, ConnectorTableHandle tableHandl
 
         long commitVersion = table.getReadVersion() + 1;
         List<String> partitionColumns = metadataEntry.getOriginalPartitionColumns();
-        if (partitionColumns.contains(dropColumnName)) {
+        if (deltaLakeColumn.getColumnType() == PARTITION_KEY) {
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1408]: `TestDeltaLakeColumnMappingMode.testDropLastNonPartitionColumnWithColumnMappingMode` starts failing without this change.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 2]
```diff
@@ -1135,6 +1135,10 @@ public Optional<ConnectorOutputMetadata> finishCreateTable(
         ColumnMappingMode columnMappingMode = handle.getColumnMappingMode();
         String schemaString = handle.getSchemaString();
         List<String> columnNames = handle.getInputColumns().stream().map(DeltaLakeColumnHandle::getBaseColumnName).collect(toImmutableList());
+        List<String> physicalPartitionNames = handle.getInputColumns().stream()
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1138]: This seems to be something we didn't consider in #12638
I don't see at the moment any further related open issues.

**Review by findinpath — APPROVED** [review]

**Review by pajaks — APPROVED** [review]

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 3]
```diff
@@ -1151,7 +1155,7 @@ public Optional<ConnectorOutputMetadata> finishCreateTable(
                     session,
                     handle.getComment(),
                     handle.getProtocolEntry());
-            appendAddFileEntries(transactionLogWriter, dataFileInfos, handle.getPartitionedBy(), columnNames, true);
+            appendAddFileEntries(transactionLogWriter, dataFileInfos, physicalPartitionNames, columnNames, true);
```
Comment (alexjo2144) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1158]: What about a couple lines up in the `appendTableEntries` call, should we use physicalPartitionNames there too?

Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1158]: Do you mean `handle.getPartitionedBy()` for `partitionColumns` in `metaData`? The current implementation is same as OSS Delta Lake. They store non-physical partition column names in the field.

**Review by findepi — APPROVED** [review]

**Review by alexjo2144 — APPROVED** [review]
