### PR TITLE
Fix test for invalid rate in FormatUtils.formatDataRate()

### LINKED ISSUE #13093: io.trino.cli.FormatUtils.formatDataRate incorrectly tests long rate with Double functions
Test code:

```java
assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(1), Duration.valueOf("0s"), false), "0B");
```

Assertion fails:

```
TestFormatUtils.formatDataRate:287 expected [0B] but found [9223P]
```

The issue is that `formatDataRate` calculates its `rate` local variable as a `long`:

```java
long rate = Math.round(dataSize.toBytes() / duration.getValue(SECONDS));
```

but then this test can never succeed, since both functions will return false for any `long`

```java
        if (Double.isNaN(rate) || Double.isInfinite(rate)) {
            rate = 0;
        }
```

The test should instead be:

```java
        if (rate == Long.MAX_VALUE) {
            rate = 0;
        }
```

### PR DESCRIPTION
**Pull request by metadaddy**
## Description

`FormatUtils.formatDataRate()` contains the following code:

```java
long rate = Math.round(dataSize.toBytes() / duration.getValue(SECONDS));
if (Double.isNaN(rate) || Double.isInfinite(rate)) {
    rate = 0;
}
```

The test can never evaluate as `true`, since both functions will return false for any `long`.

The correct test is:

```java
if (rate == Long.MAX_VALUE) {
    rate = 0;
}
```

It's not necessary to test for `Long.MIN_VALUE`, since neither `dataSize` nor `duration` can be negative.

## Unit Test

I added a new class, `TestFormatUtils` to test both this fix and the rest of `FormatUtils`. The tests for this change are:

```java
assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(1), Duration.valueOf("0s"), false), "0B");
assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(1), Duration.valueOf("0s"), true), "0B/s");
```

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

## Related Issue

Fixes #13093

### CODE REVIEW

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java [hunk 1]
```diff
@@ -0,0 +1,353 @@
...
+        assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(864000), Duration.valueOf("10d"), true), "1B/s");
+        assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(8640000), Duration.valueOf("10d"), false), "10B");
+        assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(8640000), Duration.valueOf("10d"), true), "10B/s");
+
+        assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(1), Duration.valueOf("0s"), false), "0B");
+        assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(1), Duration.valueOf("0s"), true), "0B/s");
+    }
+
+    @Test
+    public void testPluralize()
```
Comment (findepi) [inline client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:282]: that's awesome you're adding this test class.
note that it covers lot more than just the fix itself

what about introducing the test class as a prep commit
and then only doing the change (that should be reflected with only a small, related test change)

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java [hunk 2]
```diff
@@ -0,0 +1,353 @@
...
+    {
+        assertEquals(FormatUtils.formatProgressBar(10, 0), "<=>       ");
+        assertEquals(FormatUtils.formatProgressBar(10, 1), " <=>      ");
+        assertEquals(FormatUtils.formatProgressBar(10, 7), "       <=>");
+        assertEquals(FormatUtils.formatProgressBar(10, 8), "      <=> ");
+        assertEquals(FormatUtils.formatProgressBar(10, 13), " <=>      ");
+        assertEquals(FormatUtils.formatProgressBar(10, 14), "<=>       ");
+    }
+
+    @Test(expectedExceptions = IllegalArgumentException.class, expectedExceptionsMessageRegExp = "invalid count: -1")
```
Comment (findepi) [inline client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:325]: avoid `@Test(expectedExceptions`

use `assertThatThrownBy` instead

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java [hunk 3]
```diff
@@ -0,0 +1,353 @@
...
+    public void testInvalidIndeterminateProgressBar()
+    {
+        assertEquals(FormatUtils.formatProgressBar(10, -1), "<=>       ");
```
Comment (findepi) [inline client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:328]: looks like `assertEquals` is unreachable code, since `formatProgressBar` throws, right?

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java [hunk 4]
```diff
@@ -0,0 +1,353 @@
...
+import org.testng.annotations.Test;
+
+import static org.testng.Assert.assertEquals;
+
+public class TestFormatUtils
+{
+    @Test
+    public void testFormatCount()
+    {
+        assertEquals(FormatUtils.formatCount(1L), "1");
```
Comment (findepi) [inline client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:27]: nit: you can import FormatUtils method statically

i know this will make it less clear that we're invking FormatUtils methods
but it will improve readability overall

File: client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java [hunk 5]
```diff
@@ -115,7 +115,7 @@ else if (longForm) {
     public static String formatDataRate(DataSize dataSize, Duration duration, boolean longForm)
     {
         long rate = Math.round(dataSize.toBytes() / duration.getValue(SECONDS));
-        if (Double.isNaN(rate) || Double.isInfinite(rate)) {
+        if (rate == Long.MAX_VALUE) {
```
[the remark this answers is not in the document]
Comment (pettyjamesm) [reply client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java:118]: `Math.round` returns `Long.MAX_VALUE` for positive infinity and `Long.MIN_VALUE` for negative infinity. `Double.NaN` returns `0`. The check looks correct to me since `dataSize.toBytes()` can only return positive values, making negative infinity impossible.

**Review by pettyjamesm — APPROVED** [review]

File: client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java [hunk 6]
```diff
@@ -115,7 +115,7 @@ else if (longForm) {
     public static String formatDataRate(DataSize dataSize, Duration duration, boolean longForm)
     {
         long rate = Math.round(dataSize.toBytes() / duration.getValue(SECONDS));
-        if (Double.isNaN(rate) || Double.isInfinite(rate)) {
```
[the remark this answers is not in the document]
Comment (metadaddy) [reply client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java:118]: Nice!

File: client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (metadaddy) [reply client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java:118]: The check against `Long.MAX_VALUE` preserves the intended semantics (and mirrors those of `formatCountRate()`) - if the rate calculation results in 'infinity', then set it to zero.

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java (hunk 1 above)
Comment (metadaddy) [reply client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:282]: @findepi Two PRs, or one PR containing two commits?

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java (hunk 2 above)
Comment (metadaddy) [reply client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:325]: Done:

```java
    @Test
    public void testInvalidIndeterminateProgressBar()
    {
        assertThatThrownBy(() -> formatProgressBar(10, -1))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("invalid count: -1");
    }
```

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java (hunk 4 above)
Comment (metadaddy) [reply client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:27]: done

**Comment by metadaddy** [comment]
Thanks for the reviews! I've made the suggested changes; @findepi - just let me know whether you're looking for two PRs, or one PR with two commits and I'll do another push.

**Comment by metadaddy** [comment]
@findepi I refactored to two commits and force-pushed them. Let me know if you need two PRs.

File: client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (findepi) [reply client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java:118]: Are we printing "oh, so big a rate that I can't handle it" and "nothing is happening" the same way?

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java (hunk 1 above)
Comment (findepi) [reply client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:284]: I'd do 1 PR containing two commits.

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java [hunk 7]
```diff
@@ -275,6 +275,9 @@ public void testFormatDataRate()
         assertEquals(formatDataRate(DataSize.ofBytes(864000), Duration.valueOf("10d"), true), "1B/s");
         assertEquals(formatDataRate(DataSize.ofBytes(8640000), Duration.valueOf("10d"), false), "10B");
         assertEquals(formatDataRate(DataSize.ofBytes(8640000), Duration.valueOf("10d"), true), "10B/s");
+
+        assertEquals(formatDataRate(DataSize.ofBytes(1), Duration.valueOf("0s"), false), "0B");
```
Comment (findepi) [inline client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:279]: If we eg transferred 1 MB within "zero time" (which isn't impossible given clock granularity), why would we want to print 0?

Comment (metadaddy) [reply client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:279]: I don't know; I'm simply honoring the intent of the original code written by @electrum

File: client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (metadaddy) [reply client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java:118]: Yes - this is how `formatCountRate` works. I'm merely fixing the check here so it works as intended.

File: client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java (hunk 1 above)
Comment (metadaddy) [reply client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java:284]: Done

**Comment by mosabua** [comment]
@findepi @metadaddy @pettyjamesm can you continue to collaborate on this PR please?

**Comment by mosabua** [comment]
Does this PR need anything besides a merge @findepi and @pettyjamesm ?

**Comment by pettyjamesm** [comment]
> Does this PR need anything besides a merge @findepi and @pettyjamesm ?

Nothing on my end, @findepi  had some feedback and conversations going after I had approved it- so I defer to him on merge readiness, although if he’s not available I can pick it up and re-review.

**Comment by mosabua** [comment]
Could you rebase @metadaddy .. maybe we can find someone to look and get this merged after.

**Comment by metadaddy** [comment]
Hi @mosabua - I rebased, as requested 👍🏻

File: client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (dain) [reply client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java:137]: I'm pretty sure the only way to get infinity (and thus max long) is if the duration is effectively zero.  In that case I think printing a zero rate is fine.  It will quickly update to a real value.

**Review by dain — APPROVED** [review]
