### PR TITLE
Fix issues due to mask aliasing

### LINKED ISSUE #15659: Security issue with access control: column masking gets lost when querying only nested field
We found a security issue with access control. Here's the repro

Create a table with a struct column and load some data:
```
use memory.default;
create table nestedtable (buyer row(customerId varchar), purchaseId varchar);
INSERT into nestedtable SELECT ROW('a') as buyer, 'p1';
INSERT into nestedtable SELECT ROW('b') as buyer, 'p2';
INSERT into nestedtable SELECT ROW('c') as buyer, 'p3';
```
Apply a file-based access control policy as such:
```
{
    "tables": [
        {
            "catalog": "memory",
            "schema": "default",
            "table": "nestedtable",
            "privileges": ["SELECT"],
            "columns" : [
                {
                    "name": "purchaseId",
                    "allow": true
                },
                {
                    "name": "buyer",
                    "mask": "if (purchaseId <> 'p3', buyer)"
                }
            ]
        }
    ]
}
```
Now run some queries
```
-- Correct
trino:default> select * from nestedtable;
     buyer      | purchaseid
----------------+------------
 {customerid=b} | p2
 NULL           | p3
 {customerid=a} | p1

-- Correct
trino:default> select buyer from nestedtable;
     buyer
----------------
 {customerid=a}
 {customerid=b}
 NULL
(3 rows)

-- Correct
trino:default> select buyer.customerid, buyer from nestedtable;
 customerid |     buyer
------------+----------------
 NULL       | NULL
 a          | {customerid=a}
 b          | {customerid=b}

-- Wrong
trino:default> select buyer.customerid from nestedtable;
 customerid
------------
 c <<< No content from column "buyer" should be exposed for this row
 b
 a
```
Based on the plan below, we can tell that when only nested subfield is queried, certain "unneeded" projected column gets pruned, in this case "buyer" (and its masking).
```
trino:default> explain select buyer.customerid from nestedtable;
                                                          Query Plan
-------------------------------------------------------------------------------------------------------------------------------
 Trino version: dev
 Fragment 0 [SOURCE]
     Output layout: [expr_0]
     Output partitioning: SINGLE []
     Output[columnNames = [customerid]]
     │   Layout: [expr_0:varchar]
     │   Estimates: {rows: 3 (165B), cpu: 0, memory: 0B, network: 0B}
     │   customerid := expr_0
     └─ ScanProject[table = memory:0]
            Layout: [expr_0:varchar]
            Estimates: {rows: 3 (165B), cpu: 165, memory: 0B, network: 0B}/{rows: 3 (165B), cpu: 165, memory: 0B, network: 0B}
            expr_0 := "buyer"[1]
            buyer := 0
```
The pruning is done at `PruneProjectColumns`. We believe this is wrong. Some mechanism should be added to tell whether a ProjectNode is for masking, and we should always retain that ProjectNode to be on the safe side.

### PR DESCRIPTION
**Pull request by martint**
Fix aliasing of fields in mask expressions

This causes two problems:
* Masks can inadvertently refer to columns that appear earlier
      in the list of columns as the projection is planned. This
      causes the mask expression to see the masked value of other columns
      instead of the underlying value
* A possible bug in other optimizers causes mask expressions to be
      lost when the result of a such an expression is of type ROW
      and there's a dereference of a field downstream

Fixes #15659

Relates to #14420

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Section
* TBD
```

### CODE REVIEW

File: lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java [hunk 1]
```diff
@@ -968,7 +968,13 @@ public List<ViewExpression> getColumnMasks(SystemSecurityContext context, Catalo
                 .findFirst()
                 .stream()
                 .flatMap(Optional::stream)
-                .collect(toImmutableList());
+                .findFirst();
```
Comment (ksobolew) [inline lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java:971]: There's already a `findFirst` here. This was deliberate - the SPI could return multiple masks, but File Based access control was still returning the first mask that matched, even if there were more.

```suggestion
                .findFirst()
                .flatMap(Function.identity());
```

Comment (ksobolew) [reply lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java:971]: (Same applies to the connector-level one, of course)

File: core/trino-main/src/main/java/io/trino/security/AccessControlManager.java [hunk 2]
```diff
@@ -1248,26 +1249,30 @@ public List<ViewExpression> getRowFilters(SecurityContext context, QualifiedObje
...
+                    .ifPresent(masks::add);
         }
 
-        return masks.build();
+        List<ViewExpression> allMasks = masks.build();
+        if (allMasks.size() > 1) {
+            throw new TrinoException(INVALID_COLUMN_MASK, format("Column must have a single mask: %s", columnName));
+        }
+
+        return allMasks.stream().findFirst();
```
Comment (kokosing) [inline core/trino-main/src/main/java/io/trino/security/AccessControlManager.java:1275]: `getOnlyElement`?

File: core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java [hunk 3]
```diff
@@ -196,25 +196,6 @@ public void testConditionalMask()
                 .matches("VALUES (NULL), CAST('-781' AS BIGINT)");
     }
 
-    @Test
-    public void testMultipleMasksOnSameColumn()
```
Comment (kokosing) [inline core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:200]: I would keep the test and validate that in case of multiple masks it fails as expected

File: core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java [hunk 4]
```diff
@@ -614,22 +595,6 @@ public void testJoin()
                 USER,
                 new ViewExpression(USER, Optional.of(LOCAL_CATALOG), Optional.of("tiny"), "orderkey + 1"));
         assertThat(assertions.query("SELECT count(*) FROM orders JOIN orders USING (orderkey)")).matches("VALUES BIGINT '15000'");
-
-        // multiple masks
```
Comment (kokosing) [inline core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:618]: same

File: lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java [hunk 5]
```diff
@@ -459,6 +460,16 @@ private static void assertViewExpressionEquals(List<ViewExpression> result, View
         assertEquals(actual.getExpression(), expected.getExpression(), "Expression");
     }
 
+    private static void assertViewExpressionEquals(Optional<ViewExpression> result, ViewExpression expected)
+    {
+        assertTrue(result.isPresent());
+        ViewExpression actual = result.get();
```
Comment (kokosing) [inline lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java:466]: can we share the code with the method above?

**Review by kokosing — COMMENTED** [review]
LGTM % comments

File: core/trino-main/src/main/java/io/trino/security/AccessControlManager.java [hunk 6]
```diff
@@ -1248,26 +1249,30 @@ public List<ViewExpression> getRowFilters(SecurityContext context, QualifiedObje
...
-            connectorAccessControl.getColumnMasks(toConnectorSecurityContext(tableName.getCatalogName(), context), tableName.asSchemaTableName(), columnName, type)
-                    .forEach(masks::add);
+            connectorAccessControl.getColumnMask(toConnectorSecurityContext(tableName.getCatalogName(), context), tableName.asSchemaTableName(), columnName, type)
+                    .ifPresent(masks::add);
         }
 
         for (SystemAccessControl systemAccessControl : getSystemAccessControls()) {
-            systemAccessControl.getColumnMasks(context.toSystemSecurityContext(), tableName.asCatalogSchemaTableName(), columnName, type)
-                    .forEach(masks::add);
+            systemAccessControl.getColumnMask(context.toSystemSecurityContext(), tableName.asCatalogSchemaTableName(), columnName, type)
```
Comment (weiatwork) [inline core/trino-main/src/main/java/io/trino/security/AccessControlManager.java:1266]: If we will stick with having only one mask altogether no matter where it comes from, then the connector mask should be dropped here if any and give place to the system mask. This behavior is guaranteed in the doc: https://trino.io/docs/current/security/built-in-system-access-control.html
`A system access control enforces authorization at a global level, before any connector level authorization`
We may also want to update the doc to mention what will happen if masks for the same column are defined in both system and connector AC.

File: core/trino-main/src/main/java/io/trino/security/AccessControlManager.java (hunk 2 above)
Comment (martint) [reply core/trino-main/src/main/java/io/trino/security/AccessControlManager.java:1275]: It could have 0 or 1 elements, so findFirst produces an optional.

File: core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java (hunk 3 above)
Comment (martint) [reply core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java:200]: It's not possible, since TestingAccessControl allows a single mask per column.

File: core/trino-main/src/main/java/io/trino/security/AccessControlManager.java (hunk 6 above)
Comment (martint) [reply core/trino-main/src/main/java/io/trino/security/AccessControlManager.java:1266]: That's an interesting point. In the current implementation, the masks stack on top of each other, with system level ones having precedence. As we've been discussing, stacking masks is problematic, so that leaves us with two options:

1. System-level column mask takes precedence and connector-level mask is ignored if one is also provided.
2. Fail the query if a system-level and a connector-level mask exist.

I'm not sure yet which option is best. The desire for `A system access control enforces authorization at a global level, before any connector level authorization` doesn't quite apply here, since the masks don't behave like regular permission checks.

The issue with option 1 is that it may lead to inadvertent security holes if someone installs a system level plugin after the fact that provides a weaker mask that the connector-level access control did.

@dain, do you have any thoughts?

Comment (kokosing) [reply core/trino-main/src/main/java/io/trino/security/AccessControlManager.java:1266]: > weaker mask 

I don't think mask can be anyhow ordered. 

If we go with option 2 then it is possible to relax it in the future to option 1. 

The fact we had a list of masks was because it was addressing a corner case which should be very rare. Integrating with multiple authorization systems at once is complex. If you consider that each of them can provide masking for the same columns is a madness :)

Let's disallow this and wait to see if such use case is even real.

**Review by kokosing — APPROVED** [review]

File: lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java [hunk 7]
```diff
@@ -654,21 +656,30 @@ public List<ViewExpression> getRowFilters(ConnectorSecurityContext context, Sche
...
-        return tableRules.stream()
+        List<ViewExpression> masks = tableRules.stream()
                 .filter(rule -> rule.matches(identity.getUser(), identity.getEnabledSystemRoles(), identity.getGroups(), tableName))
                 .map(rule -> rule.getColumnMask(identity.getUser(), catalogName, tableName.getSchemaName(), columnName))
-                // we return the first one we find
-                .findFirst()
-                .stream()
                 .flatMap(Optional::stream)
-                .collect(toImmutableList());
+                .toList();
```
[the remark this answers is not in the document]
Comment (ksobolew) [reply lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java]: Sorry if I wasn't clear earlier. Yes, that's the expected behavior. I worked in that area previously and changed that behavior (unintentionally), and users started complaining almost immediately :)

[the remark this answers is not in the document]
Comment (martint) [reply lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java]: Great, thanks. I restored that behavior.
