### PR TITLE
Increase the max number of http connections in Azure native FS

### LINKED ISSUE #22548: Performance regression in native FS on Azure
I'm executing:
* [query 09](https://github.com/trinodb/trino/blob/b983eeeac122391bfbe295af80b4558daf415495/testing/trino-benchmark-queries/src/main/resources/sql/trino/tpcds/q09.sql#L4) from the TPCDS benchmark
* on the sf1000 schema in an Iceberg catalog, with data stored in Azure,
* using HMS,
* using a 16 node cluster and Trino 449, running on Azure.

Using the legacy FS, after some initial warm up, the query executes in about 11s. After switching to native FS, the query takes over 60s.

Comparing the query plans, the only noticeable difference is in the `Physical input time` value, which is much higher when using native FS.

I tried running a similar query on AWS, using Glue, and there was no significant difference in query run time (after warm up).

I'll keep investigating and will post more details later.

### PR DESCRIPTION
**Pull request by nineinchnick**
## Description

By default, OkHttp only allows 5 concurrent HTTP connections per host, and 64 total concurrent connections. Increase these values to avoid a performance degradation compared to the legacy FS, when executing queries with a large number of splits, on nodes with large number of split runner threads.

Fixes #22548 

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# General
* Fix a performance regression in native FS for Azure, compared to legacy FS. ({issue}`issuenumber`)
```

### CODE REVIEW

File: lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java [hunk 1]
```diff
@@ -96,6 +97,9 @@ public static HttpClient createAzureHttpClient(OkHttpClient okHttpClient, HttpCl
         Integer poolSize = clientOptions.getMaximumConnectionPoolSize();
         // By default, OkHttp uses a maximum idle connection count of 5.
         int maximumConnectionPoolSize = (poolSize != null && poolSize > 0) ? poolSize : 5;
+        Dispatcher dispatcher = new Dispatcher();
+        dispatcher.setMaxRequests(Runtime.getRuntime().availableProcessors() * 4);
+        dispatcher.setMaxRequestsPerHost(Runtime.getRuntime().availableProcessors() * 2);
```
Comment (nineinchnick) [inline lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java:102]: This is the same as the default for the number of worker threads: https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java#L62

I didn't want to get it from that config to avoid adding a dependency on `trino-main`. I set the max requests as twice as much, but I don't have any specific reason for it. I'm open for suggestions how to choose a better value.

**Comment by nineinchnick** [comment]
I tested this manually on a 16 node cluster executing q09 from TPCDS. The wall time went down from 60s to 9s, matching legacy FS.

File: lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java (hunk 1 above)
Comment (anusudarsan) [reply lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java:102]: is this worth exposing it as a configuration property? 

Also nit: extract Runtime.getRuntime().availableProcessors() to a variable, and also inline `dispatcher` below

Comment (nineinchnick) [reply lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java:102]: I can't inline it, as the setters don't return anything.

If we'll make it configurable, it should only be a fallback in case we get the default wrong. Maybe we should ask differently - in which cases the number of worker threads should be customized?

**Review by electrum — APPROVED** [review]

**Comment by findinpath** [comment]
> By default, OkHttp only allows 5 concurrent HTTP connections per host, and 64 total concurrent connections. 

@nineinchnick does this finding apply for AWS S3 or GCS clients?
