### PR TITLE
Fix failure for IN expression in join criteria

### LINKED ISSUE #4380: Left Join condition association does not support subqueries
sql->whit tmp_auth as (select node_id, node_type from xxx.xxx.organization where status = '1' and node_type <> '0')
select t1.id, t2.name from xxx.xxx.test1 t1 left jon xxx.xxx.test2 t2 on t1.id = t2.o_id and **t1.s_id in (select node_id from tmp_auth where node_id = 1)** limit 10;

error message -> Column 't1.s_id' cannot be resolved

### PR DESCRIPTION
**Pull request by martint**
The planner was making a decision of whether to plan the subquery on the
left or right depending on whether all the columns in the expression
could be satisfied by either side. However, it was not excluding
columns in the subquery.

Fixes https://github.com/prestosql/presto/issues/4380

### CODE REVIEW

**Review by losipiuk — APPROVED** [review]

File: presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java [hunk 1]
```diff
@@ -181,5 +191,15 @@ protected Void visitIdentifier(Identifier node, ImmutableSet.Builder<QualifiedNa
             builder.add(QualifiedName.of(node.getValue()));
             return null;
         }
+
+        @Override
+        protected Void visitSubqueryExpression(SubqueryExpression node, ImmutableSet.Builder<QualifiedName> context)
```
Comment (sopel39) [inline presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java:196]: what if there is a reference to outer column within subquery?

File: presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java [hunk 2]
```diff
@@ -124,7 +125,14 @@ private SymbolsExtractor() {}
...
         ImmutableSet.Builder<QualifiedName> builder = ImmutableSet.builder();
-        new QualifiedNameBuilderVisitor(columnReferences).process(expression, builder);
+        new QualifiedNameBuilderVisitor(columnReferences, true).process(expression, builder);
+        return builder.build();
+    }
+
+    public static Set<QualifiedName> extractNamesNoSubqueries(Expression expression, Set<NodeRef<Expression>> columnReferences)
+    {
+        ImmutableSet.Builder<QualifiedName> builder = ImmutableSet.builder();
+        new QualifiedNameBuilderVisitor(columnReferences, false).process(expression, builder);
```
Comment (kokosing) [inline presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java:135]: consider using `io.prestosql.sql.util.AstUtils#preOrder` instead of `DefaultExpressionTraversalVisitor`

File: presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java (hunk 1 above)
Comment (martint) [reply presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java:196]: That’s taken care of during analysis. See the comment where this is used in join planning.

There’s a broader cleanup that needs to be done at some point. Unfortunately, we currently resolve columns in join planning to determine where they originate. This should be done entirely during analysis.

Comment (sopel39) [reply presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java:196]: Could we have a test case for such subquery (referencing outer scope)?

Comment (martint) [reply presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java:196]: We already have a bunch of them. See the tests further down below the one I added. E.g.,

```
        assertThatThrownBy(() -> assertions.query(
                "SELECT * FROM (VALUES 1, 2, NULL) t(x) FULL JOIN (VALUES 1, 3, NULL) u(x) ON u.x IN (VALUES t.x)"))
                .hasMessage("line 1:93: Reference to column 't.x' from outer scope not allowed in this context");
```

File: presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java (hunk 2 above)
Comment (martint) [reply presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java:135]: That's more complicated, as there's no way to stop the recursion with `preOrder`. In any case, I just extended what's already there. That would be a separate cleanup task.

**Review by sopel39 — APPROVED** [review]
