### PR TITLE
Fix Iceberg value for varbinary

### LINKED ISSUE #22071: Iceberg: varbinary type and bucket partition trnsformation
Problem reproduction:

**Step 1:** `CREATE TABLE t(col_1 VARBINARY) WITH (partitioning=array['bucket(col_1, 16)'])`
**Step 2:** `INSERT INTO t(col_1) VALUES (x'01')`
**Result:** `throw (io.trino.plugin.iceberg.IcebergPageSink#applyTransform) ClassCastException (message: class [B cannot be cast to class java.nio.ByteBuffer)`

<details>
<summary><b>Stack trace</b></summary>

```java
Caused by: java.lang.ClassCastException: class [B cannot be cast to class java.nio.ByteBuffer ([B and java.nio.ByteBuffer are in module java.base of loader 'bootstrap')
	at org.apache.iceberg.transforms.Bucket$BucketByteBuffer.apply(Bucket.java:230)
	at io.trino.plugin.iceberg.IcebergPageSink.applyTransform(IcebergPageSink.java:471)
	at io.trino.plugin.iceberg.IcebergPageSink.getPartitionData(IcebergPageSink.java:463)
	at io.trino.plugin.iceberg.IcebergPageSink.getWriterIndexes(IcebergPageSink.java:347)
	at io.trino.plugin.iceberg.IcebergPageSink.writePage(IcebergPageSink.java:273)
	at io.trino.plugin.iceberg.IcebergPageSink.doAppend(IcebergPageSink.java:267)
	at io.trino.plugin.iceberg.IcebergPageSink.appendPage(IcebergPageSink.java:220)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:68)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:276)
	at io.trino.operator.Driver.processInternal(Driver.java:408)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
	at io.trino.operator.Driver.tryWithLock(Driver.java:709)
	at io.trino.operator.Driver.process(Driver.java:298)
	at io.trino.operator.Driver.processForDuration(Driver.java:269)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:77)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
	at io.trino.$gen.Trino_testversion____20240522_133059_1.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
	at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:168)
	at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

</details>

### PR DESCRIPTION
**Pull request by IlyaEp**
## Additional context and related issues

Fix #22071 

The exception appeared since a Iceberg value of `VARBINARY` was interpreted as a byte array (`io.trino.plugin.iceberg.IcebergPageSink#getIcebergValue`), but the Iceberg function (`org.apache.iceberg.transforms.Bucket.BucketByteBuffer`) of `bucket` requires a `ByteBuffer`.

To fix this, Iceberg value of `VARBINARY` was changed to byte buffer.

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
(x) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text

### CODE REVIEW

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java [hunk 1]
```diff
@@ -8035,6 +8040,27 @@ protected Session withoutSmallFileThreshold(Session session)
                 .build();
     }
 
+    @Test
+    protected void testBucketTransformationsWithVarbinary()
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:8044]: Can this be added to existing `testBucketTransform` method which covers bucketing for other types?

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java [hunk 2]
```diff
@@ -8035,6 +8040,27 @@ protected Session withoutSmallFileThreshold(Session session)
...
+                insertValuesJoiner.add(String.format("(%s, %s)", i, String.format("x'%s'", Integer.toString(i).length() % 2 == 0 ? i : "0" + i)));
+                if (i > 9) {
+                    result.row(i, Bytes.fromBytes((byte) (i + 6)));
+                }
+                else {
+                    result.row(i, Bytes.fromBytes((byte) i));
+                }
+            }
+
+            Assertions.assertDoesNotThrow(() -> getQueryRunner().execute(format("INSERT INTO %s(c, pc) VALUES %s", table.getName(), insertValuesJoiner)));
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:8059]: we don't use `assertDoesNotThrow` in this project.
use `assertUpdate`

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java [hunk 3]
```diff
@@ -8035,6 +8040,27 @@ protected Session withoutSmallFileThreshold(Session session)
...
+            query("SELECT * FROM " + table.getName()).assertThat().result().containsAll(result.build());
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:8060]: `assertThat(query(...))`

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java [hunk 4]
```diff
@@ -210,6 +226,42 @@ public void testV2TableWithEqualityDelete()
         assertQuery("SELECT nationkey, comment FROM " + tableName, "SELECT nationkey, comment FROM nation WHERE regionkey != 1");
     }
 
+    @Test
+    public void testV2TableWithEqualityDeleteVarbinary()
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:230]: do we need 5 more tests in this class?
or would having the one in BaseIcebergConnectorTest.java  be enough?

Comment (IlyaEp) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:230]: There is a path: `io.trino.plugin.iceberg.delete.EqualityDeleteFilter#readEqualityDeletes` &#8594; `io.trino.plugin.iceberg.delete.TrinoRow` &#8594; `io.trino.plugin.iceberg.IcebergPageSink#getIcebergValue`

These tests check this path

Comment (findepi) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:230]: understood, but `IcebergPageSink#getIcebergValue` could actually be unit tested.
varbinary transform should be also tested (good)

i proposed not to add these other tests

Comment (IlyaEp) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java]: Ok, I removed them

**Comment by findepi** [comment]
LGTM, thanks!
can you please squash commits?

**Comment by IlyaEp** [comment]
I squashed commits

**Review by findepi — APPROVED** [review]

**Review by wendigo — APPROVED** [review]
