### PR TITLE
Test timeout consistency for TestQueues

### LINKED ISSUE #27611: Flaky test `TestQueues.testQueryTextBasedSelection`: timeot
https://github.com/trinodb/trino/actions/runs/20105681115/job/57688885967?pr=27609

```
Error:  Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 77.35 s <<< FAILURE! -- in io.trino.execution.TestQueues
Error:  io.trino.execution.TestQueues.testQueryTextBasedSelection -- Time elapsed: 10.05 s <<< ERROR!
java.util.concurrent.TimeoutException: testQueryTextBasedSelection() timed out after 10 seconds
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: org.junit.jupiter.api.util.PreemptiveTimeoutUtils$ExecutionTimeoutException: Execution timed out in thread junit-timeout-thread-8
	at java.base/java.lang.Thread.sleepNanos0(Native Method)
	at java.base/java.lang.Thread.sleepNanos(Thread.java:509)
	at java.base/java.lang.Thread.sleep(Thread.java:577)
	at java.base/java.util.concurrent.TimeUnit.sleep(TimeUnit.java:446)
	at io.trino.execution.SqlTaskManager.close(SqlTaskManager.java:332)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at io.airlift.bootstrap.LifeCycleManager.stopInstance(LifeCycleManager.java:240)
	at io.airlift.bootstrap.LifeCycleManager.stop(LifeCycleManager.java:209)
	at io.airlift.bootstrap.LifeCycleManager.stop(LifeCycleManager.java:174)
	at io.trino.server.testing.TestingTrinoServer.lambda$close$1(TestingTrinoServer.java:468)
	at com.google.common.io.Closer.close(Closer.java:203)
	at io.trino.server.testing.TestingTrinoServer.close(TestingTrinoServer.java:471)
	at com.google.common.io.Closer.close(Closer.java:203)
	at io.trino.testing.DistributedQueryRunner.close(DistributedQueryRunner.java:684)
	at io.trino.execution.TestQueues.testQueryTextBasedSelection(TestQueues.java:314)
```

### PR DESCRIPTION
**Pull request by gertjanal**
## Description
This test takes 1.4 seconds on my machine, but takes longer when run in the github checks. Reverted timeout to 240s, for consistency with other test methods. Fixes #27611

## Additional context and related issues
Initial discussion: https://github.com/trinodb/trino/pull/27129#discussion_r2594137872

## Release notes

( X ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

File: testing/trino-tests/src/test/java/io/trino/execution/TestQueues.java [hunk 1]
```diff
@@ -301,7 +301,7 @@ public void testSelectorResourceEstimateBasedSelection()
     }
 
     @Test
-    @Timeout(10)
+    @Timeout(240)
```
Comment (ebyhr) [inline testing/trino-tests/src/test/java/io/trino/execution/TestQueues.java:304]: 4m for a single test looks too long. Why do we need such a long timeout? Can we leave a code comment? 

https://github.com/prestodb/presto/pull/3459 was the PR created this test class. Unfortunately, the PR doesn't give us the context of long timeout.
