### PR TITLE
Fix query failure when unsupported check constraint exists in Delta

### LINKED ISSUE #16865: Delta Lake connector can't read a table having unsupported check constraint expressions
We should deny only write operations for unsupported expressions because check constraints are unused during read.

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #16865

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# Delta Lake
* Fix query failure when unsupported expressions exist in check constraints. ({issue}`16865`)
```

### CODE REVIEW

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 1]
```diff
@@ -486,7 +492,19 @@ public ConnectorTableMetadata getTableMetadata(ConnectorSession session, Connect
                 properties.buildOrThrow(),
                 Optional.ofNullable(tableHandle.getMetadataEntry().getDescription()),
                 constraints.stream()
-                        .map(SparkExpressionParser::toTrinoExpression)
+                        .map(constraint -> {
+                            try {
+                                return toTrinoExpression(constraint);
+                            }
+                            catch (TrinoException e) {
+                                if (e.getErrorCode().equals(DELTA_LAKE_UNSUPPORTED_EXPRESSION.toErrorCode()) && suppressExpressionParserFailure) {
```
Comment (pajaks) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:500]: Is comparing such generic error type as USER_ERROR safe here? 
What if someone else uses this error type for for other error?

Is this logic actually needed? Seems that `toTrinoExpression` can fail only because of failed conversion.

Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:500]: > Is comparing such generic error type as USER_ERROR safe here?
What if someone else uses this error type for for other error?

Even if someone uses `DELTA_LAKE_UNSUPPORTED_EXPRESSION` in different places, that doesn't break this logic. If someone change the exception type inside of  `toTrinoExpression`, we can catch by CI failure. 

> Is this logic actually needed? Seems that toTrinoExpression can fail only because of failed conversion.

What's your suggestion? If we remove this block, SELECT query fails even though check constraints shouldn't affect it.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeErrorCode.java [hunk 2]
```diff
@@ -27,6 +28,7 @@
     DELTA_LAKE_BAD_DATA(2, EXTERNAL),
     DELTA_LAKE_BAD_WRITE(3, EXTERNAL),
     DELTA_LAKE_FILESYSTEM_ERROR(4, EXTERNAL),
+    DELTA_LAKE_UNSUPPORTED_EXPRESSION(5, USER_ERROR),
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeErrorCode.java:31]: I'd argue that this is rather an `EXTERNAL` error.
The Delta table is created by another query engine (atm Trino can't create such tables).

In case Trino will eventually support creating/altering delta tables with  constraints that are not supported, this would qualify for a user error.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 3]
```diff
@@ -486,7 +492,19 @@ public ConnectorTableMetadata getTableMetadata(ConnectorSession session, Connect
...
+                                    LOG.warn("Failed to convert Spark check constraints to Trino expressions: %s", constraint);
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:501]: Why do we log the warning?

Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: Changed to debug log.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeErrorCode.java (hunk 2 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeErrorCode.java]: StandardErrorCode uses USER_ERROR for NOT_SUPPORTED as you may already know. If we think the operation as "users tried to read tables having unsupported expression", it will be USER_ERROR.

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java [hunk 4]
```diff
@@ -159,4 +159,40 @@ public void testMetadataOperationsRetainCheckConstraint()
...
+                "USING DELTA " +
+                "LOCATION 's3://" + bucketName + "/databricks-compatibility-test-" + tableName + "'");
+
+        try {
+            // This constraint should be changed to a new one if the connector supports the expression
+            onDelta().executeQuery("ALTER TABLE default." + tableName + " ADD CONSTRAINT test_constraint CHECK (a = abs(b))");
+            onDelta().executeQuery("INSERT INTO default." + tableName + " VALUES (1, -1)");
+
+            assertQueryFailure(() -> onTrino().executeQuery("INSERT INTO delta.default." + tableName + " VALUES (1, -1)"))
+                    .hasMessageContaining("Unsupported Spark expression");
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java:178]: It's included in the error message. I intentionally avoid asserting the expression here because it's unrelated to the test purpose and we may change the expression in the future.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java (hunk 1 above)
Comment (pajaks) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:500]: > DELTA_LAKE_UNSUPPORTED_EXPRESSION in different places, that doesn't break this logic.

I was rather referring to someone creating other exception type and using USER_ERROR there. With newest changes any DELTA_LAKE_* error will be suppressed.

My suggestion was to not check exception error type at all and treat all `TrinoException` as parsing error, because `toTrinoExpression` only parses constraint. Even when somone add another exception there and will use `ErrorType.EXTERNAL` errorCode, exception will be supressed.

**Review by findinpath — APPROVED** [review]

**Review by krvikash — APPROVED** [review]

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 5]
```diff
@@ -486,7 +492,19 @@ public ConnectorTableMetadata getTableMetadata(ConnectorSession session, Connect
...
                 constraints.stream()
-                        .map(SparkExpressionParser::toTrinoExpression)
+                        .map(constraint -> {
+                            try {
+                                return toTrinoExpression(constraint);
+                            }
+                            catch (TrinoException e) {
+                                if (e.getErrorCode().equals(DELTA_LAKE_UNSUPPORTED_EXPRESSION.toErrorCode()) && suppressExpressionParserFailure) {
+                                    LOG.debug("Failed to convert Spark check constraints to Trino expressions: %s", constraint);
+                                    return null;
```
Comment (findepi) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:502]: You can return `CAST(fail('Failed to convert Delta check constraints to Trino expression') AS boolean` as the constraint expression.
It wouldn't affect reads, and would fail same way for writes.
It would keep the code simpler.

Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: Thanks for your suggestion. Changed to use `fail` function.

**Review by findepi — APPROVED** [review]
