### PR TITLE
Remove empty `UPDATE`

### LINKED ISSUE #12422: `UPDATE` does not support `WHERE false`
```
trino:default> create table t1(a_varchar varchar);
CREATE TABLE
trino:default> update t1 set a_varchar = 'Trino' where false;
Query 20220516_111829_00001_7ng9n failed: Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode

trino:default> insert into t1 select * from t1 where false;
INSERT: 0 rows

Query 20220516_111855_00002_7ng9n, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
1.83 [0 rows, 0B] [0 rows/s, 0B/s]

trino:default> delete from t1 where false;
DELETE: 0 rows

Query 20220516_112029_00003_7ng9n, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.26 [0 rows, 0B] [0 rows/s, 0B/s]
```

`UPDATE` does not support `WHERE FALSE` while `SELECT` and `DELETE` do.

Stacktrace:

```
trino:default> update t1 set a_varchar = 'Trino' where false;
Query 20220818_085157_00009_st42k failed: Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode
java.lang.IllegalArgumentException: Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.findTableScanHandleForDeleteOrUpdate(BeginTableWrite.java:353)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:247)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:268)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.getWriterTarget(BeginTableWrite.java:268)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:217)
	at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:109)
	at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:72)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:72)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:37)
	at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:21)
	at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:31)
	at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:94)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:247)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:222)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:462)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:443)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:384)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_393_5_g41d9749____20220818_085025_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: Current plan:
                Output[columnNames = [rows]]
                │   Layout: [rows:bigint]
                │   Estimates: 
                └─ TableCommit[]
                   │   Layout: [rows:bigint]
                   │   Estimates: 
                   └─ LocalExchange[partitioning = SINGLE]
                      │   Layout: [partialrows:bigint, fragment:varbinary]
                      │   Estimates: 
                      └─ RemoteExchange[type = GATHER]
                         │   Layout: [partialrows:bigint, fragment:varbinary]
                         │   Estimates: 
                         └─ Update[[]][]
                            │   Layout: [partialrows:bigint, fragment:varbinary]
                            │   Estimates: 
                            │   a_varchar := expr_0
                            └─ LocalExchange[partitioning = ROUND_ROBIN]
                               │   Layout: [field:row(_pos bigint), expr_0:varchar]
                               │   Estimates: 
                               └─ Values[]
                                      Layout: [field:row(_pos bigint), expr_0:varchar]
                                      Estimates: 

		at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:100)
		... 12 more
```

Found in Trino 381

Tested with Trino 393

Input from @findepi 

> This is because the TableScan was fully replaced with Values.

### PR DESCRIPTION
**Pull request by findinpath**
## Description

Replace the `UPDATE` plan node with an empty `VALUES` node when the predicate is optimized to `false`.

> Is this change a fix, improvement, new feature, refactoring, or other?

Fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Core query engine

> How would you describe this change to a non-technical end user or system administrator?

Support queries like the following:

```
UPDATE table_name SET col1 = 'some_value' WHERE false;
```

## Related issues, pull requests, and links

Fixes #12422

This PR takes inspiration from the commit 02be06c0 which was dealing with empty `DELETE` plan nodes.

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# Core
* Replace the `UPDATE` plan node with an empty `VALUES` node when the predicate is optimized to `false`.
```

### CODE REVIEW

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveEmptyUpdate.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+import io.trino.sql.planner.assertions.PlanMatchPattern;
+import io.trino.sql.planner.iterative.rule.test.BaseRuleTest;
+import org.testng.annotations.Test;
+
+import static io.trino.testing.TestingHandles.TEST_CATALOG_HANDLE;
+
+public class TestRemoveEmptyUpdate
+        extends BaseRuleTest
+{
+    @Test
```
Comment (findinpath) [inline core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveEmptyUpdate.java:32]: I'm inexperienced in the query planning area of Trino so I'd very much benefit of some hints regarding to improve/extend the tests for this fix.

File: core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java [hunk 2]
```diff
@@ -864,8 +865,9 @@ public PlanOptimizers(
                         statsCalculator,
                         costCalculator,
                         ImmutableSet.<Rule<?>>builder()
-                                // Run RemoveEmptyDeleteRuleSet and RemoveEmptyTableExecute after table scan is removed by PickTableLayout/AddExchanges
+                                // Run RemoveEmptyDeleteRuleSet, RemoveEmptyUpdate and RemoveEmptyTableExecute after table scan is removed by PickTableLayout/AddExchanges
                                 .addAll(RemoveEmptyDeleteRuleSet.rules())
+                                .add(new RemoveEmptyUpdate())
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java:870]: for Delete we have a rule set (since we match empty delete with and without an exchange).
wonder whether this is some left over (or otherwise: why don't we need same for Update?)

**Review by findepi — APPROVED** [review]

**Review by losipiuk — APPROVED** [review]

**Comment by findepi** [comment]
> ```gfm
> # Core
> * Replace the `UPDATE` plan node with an empty `VALUES` node when the predicate is optimized to `false`.
> ```

RN are meant to be understood by users. I will reformulate this

File: core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java (hunk 2 above)
Comment (findepi) [reply core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java:870]: followed up with https://github.com/trinodb/trino/pull/13794
