### PR TITLE
Write checkpoint if needed on CREATE OR REPLACE without schema change

### LINKED ISSUE #28310: CREATE OR REPLACE in Delta Lake not writing checkpoints as expected
This is a regression of #21609

Introduced in https://github.com/trinodb/trino/pull/27886

Specifically, here: https://github.com/trinodb/trino/pull/27886/changes#diff-79f367e47040dda32ac81ecec46b27cfd7cc822858bc8c31fe435a15a47446dcL1378-R1385

Pre-#27886, the behaviour was to always call `writeCheckpointIfNeeded`, which would write a checkpoint based on the checkpoint writing interval.

There was a bug in there: if the schema changed, we should write a checkpoint regardless of interval. The goal of #27886 was to fix this bug, but instead it changed the logic to write a checkpoint _only_ if the schema changed.

As a result, we're now not writing checkpoints on tables that get updated solely with CREATE AND REPLACE, which was originally fixed in #21609

This was not caught in CI because the unit tests introduced in #21609 unfortunately also did a schema change (!), which meant they were still passing after #27886.

### PR DESCRIPTION
**Pull request by Pluies**
## Description

Fixes regression in Delta Lake where we stopped writing checkpoints on CREATE OR REPLACE without a schema change. See #28310 for full explanation.

This PR has two commits:
- First commit improves the original test from #21609 to test without a schema change. These tests will fail, showing the issue written up in #28310.
- Second commit then fixes the underlying issue

I'm relying on tests included in #27886 to ensure the other use case of "Delta needs to write a checkpoint on schema change" works properly, e.g. [here](https://github.com/trinodb/trino/pull/27886/changes#diff-f8407debd31f7e168ce7c1259a228f6a5538c536d53f5e2c343df2f4e6fcf595R344).

I've taken the liberty of renaming `isNewCheckpointFileRequired` to specify exactly what it does, and including the schema-change check as part of `writeCheckpointIfNeeded`, which makes the logic easier to follow.

## Additional context and related issues

Fixes #28310

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 1]
```diff
@@ -3181,23 +3181,29 @@ private void writeCheckpointIfNeeded(
             VendedCredentialsHandle credentialsHandle,
             long readVersion,
             Optional<Long> checkpointInterval,
-            long newVersion)
+            long newVersion,
+            boolean isSchemaChanged)
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: It feels we're trying to unify here by adding `isSchemaChanged` the logic related to writing checkpoints.

However, note that besides doing `CREATE OR REPLACE` statements, the schema can change also through `ALTER TABLE` statements.


I just noticed that the we're not respecting the `checkpoint_interval` when working with such a scenario

```
trino> create schema delta.tiny with (location='s3://test-bucket/tiny');
CREATE SCHEMA
trino> create table delta.tiny.t1 (a integer) with (checkpoint_interval = 2) ;
CREATE TABLE
trino> alter table delta.tiny.t1 add column b integer;
ADD COLUMN
trino> alter table delta.tiny.t1 add column c integer;
ADD COLUMN
trino> alter table delta.tiny.t1 add column d integer;
ADD COLUMN
```
In the above example, there's no checkpoint created, although we've executed 4 statements (> checkpoint interval set to 2).

I doubt that this functionality is intended :( .
cc @ebyhr

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 2]
```diff
@@ -3214,7 +3220,7 @@ private void writeCheckpoint(ConnectorSession session, SchemaTableName table, St
         checkpointWriterManager.writeCheckpoint(session, snapshot, credentialsHandle);
     }
 
-    private static boolean isNewCheckpointFileRequired(List<DeltaLakeColumnHandle> existingColumns, List<DeltaLakeColumnHandle> newColumns)
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:3219]: Yes, we have missed here the check used to verify whether the checkpoint interval has been exceeded :( 

I see the reasoning why you opted for unifying into `writeCheckpointIfNeeded` method.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java (hunk 1 above)
Comment (Pluies) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: Good point @findinpath – another bug! Likely there's no call to `writeCheckpointIfNeeded` at all in ALTER TABLE 👀 

I'm all for simplifying/putting this all into a single call 👍

Comment (findinpath) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: Note that when calling `writeCheckpointIfNeeded` from alter table methods, we'll need to respect (probably) the `checkpoint_interval` rule and not the schema changed shortcircuit.

**Comment by ebyhr** [comment]
Added a release blocker label since the regression comes from https://github.com/trinodb/trino/pull/27886 (v480).

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java (hunk 1 above)
Comment (Pluies) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: Makes sense. I'm thinking of adding checkpoints to ALTER TABLE in a separate PR, as it's technically a new feature, whereas this is a regression, to keep scope small on this PR and unblock the release of 480 – what do you think?

Comment (findinpath) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: Yes, let's proceed with the bugfix.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 3]
```diff
@@ -1380,9 +1380,8 @@ public void createTable(ConnectorSession session, ConnectorTableMetadata tableMe
                 if (replaceExistingTable) {
                     List<DeltaLakeColumnHandle> existingColumns = getColumns(tableHandle.getMetadataEntry(), tableHandle.getProtocolEntry());
                     List<DeltaLakeColumnHandle> newColumns = getColumns(metadataEntry, protocolEntry);
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1384]: Write checkpoint if needed on CREATE OR REPLACE without schema change -> Write checkpoint on CREATE OR REPLACE if checkpoint interval is exceeded

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java (hunk 1 above)
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: Now a reader may think that if schema is changed there needs to happen always a new checkpoint write.
Can we use a more meaningful variable name here?

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 4]
```diff
@@ -3181,23 +3181,29 @@ private void writeCheckpointIfNeeded(
...
+                }
 
-            // TODO: There is a race possibility here(https://github.com/trinodb/trino/issues/12004),
-            // which may result in us not writing checkpoints at exactly the planned frequency.
-            // The snapshot obtained above may already be on a version higher than `newVersion` because some other transaction could have just been committed.
-            // This does not pose correctness issue but may be confusing if someone looks into transaction log.
-            // To fix that we should allow for getting snapshot for given version.
-
-            writeCheckpoint(session, table, tableLocation, credentialsHandle, newVersion);
+                // TODO: There is a race possibility here(https://github.com/trinodb/trino/issues/12004),
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: Let's do the writing in only one branch of the code.
You have now a call in 3192 and one in 3205 (and a large comment about concurrency which applies only to the call in 3205).

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java [hunk 5]
```diff
@@ -1463,27 +1463,27 @@ public void testCreateOrReplaceCheckpointing()
         assertThat(listCheckpointFiles(transactionLogDirectory)).isEmpty();
         assertQuery("SELECT * FROM " + tableName, "VALUES (1,'ala'),  (2,'kota'), (3, 'psa')");
 
-        // replace table
+        // replace table with same schema, expect a checkpoint
```
Comment (chenjian2664) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java]:
```suggestion
        // replace table with same schema, expect a checkpoint because the checkpoint interval threshold has been reached
```

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java [hunk 6]
```diff
@@ -1446,7 +1446,7 @@ public void testCheckpointWriteStatsAsStructWithPartiallyUnsupportedColumnStats(
     }
 
     @Test
-    public void testCreateOrReplaceCheckpointing()
+    public void testCreateOrReplaceSameSchemaWritesCheckpoint()
```
Comment (chenjian2664) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java]:
```suggestion
testCreateOrReplaceWithSameSchemaWritesCheckpoint
```

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java (hunk 3 above)
Comment (chenjian2664) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java:1384]: Indeed, we missed original writing the checkpoint logic in https://github.com/trinodb/trino/pull/27886

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java (hunk 1 above)
Comment (chenjian2664) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: The `isSchemaChanged` isn't accurate here, i,e the situation when adding a new column doesn't treated a checkpoint required situation, thus i think previous the method `isNewCheckpointFileRequired` would be better

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 7]
```diff
@@ -3214,7 +3220,7 @@ private void writeCheckpoint(ConnectorSession session, SchemaTableName table, St
         checkpointWriterManager.writeCheckpoint(session, snapshot, credentialsHandle);
     }
 
-    private static boolean isNewCheckpointFileRequired(List<DeltaLakeColumnHandle> existingColumns, List<DeltaLakeColumnHandle> newColumns)
+    private static boolean isSchemaChangedForCheckpoint(List<DeltaLakeColumnHandle> existingColumns, List<DeltaLakeColumnHandle> newColumns)
```
Comment (chenjian2664) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: I think the name is good and we should keep the original name

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 8]
```diff
@@ -3181,23 +3181,29 @@ private void writeCheckpointIfNeeded(
...
+            boolean isSchemaChanged)
     {
         try {
             // We are writing checkpoint synchronously. It should not be long lasting operation for tables where transaction log is not humongous.
             // Tables with really huge transaction logs would behave poorly in read flow already.
-            long lastCheckpointVersion = getLastCheckpointVersion(session, table, tableLocation, readVersion, credentialsHandle);
-            if (newVersion - lastCheckpointVersion < checkpointInterval.orElse(defaultCheckpointInterval)) {
-                return;
+            if (isSchemaChanged) {
+                // Always write a checkpoint on schema change
```
Comment (chenjian2664) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: This is not true, see the logic in `isNewCheckpointFileRequired`, we don't write a checkpoint in every schema change.

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java (hunk 5 above)
Comment (findepi) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java]: Add this as a new test case.
There's definitely a value testing replace table with a schema change, so we should continue doing so.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java (hunk 1 above)
Comment (Pluies) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: You're correct that the name here isn't accurate 👍 However, I don't like `isNewCheckpointFileRequired` either because it's misleading in the other direction, implying that if it's false then a new checkpoint file is _not_ required... Which is not true! As it could still be required by the checkpoint interval.

I'm rewriting this in a new commit by:
- Passing (as `Optional`) the list of old & new columns into `writeCheckpointIfNeeded`, which stays the final arbiter of whether a new checkpoint is needed or not
- Renaming the helper method to a very explicit `columnChangeRequiresCheckpoint`

Will push this soon, running tests locally first 🤞

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java (hunk 5 above)
Comment (Pluies) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java]: I agree! Both parts need to be tested 👍 

This is already tested in https://github.com/trinodb/trino/pull/27886/changes#diff-f8407debd31f7e168ce7c1259a228f6a5538c536d53f5e2c343df2f4e6fcf595R344 ; but I guess there's no harm to test it there as well? Adding as `testCreateOrReplaceWithDifferentSchemaWritesCheckpoint`

**Comment by Pluies** [comment]
@findepi @findinpath @chenjian2664 hey folks, sorry about the delay, I've incorporated your feedback in two new commits:
- https://github.com/trinodb/trino/pull/28312/commits/eb7ee03673a8a0a7a9e81c0d070ee17103fec2a9
- https://github.com/trinodb/trino/pull/28312/changes/bdb5aed3db545f2fadcc7f2a1a5dd080015d30d4

Hopefully this covers everything, ptal 🙏

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java [hunk 9]
```diff
@@ -3184,21 +3184,26 @@ private void writeCheckpointIfNeeded(
...
+            Optional<List<DeltaLakeColumnHandle>> existingColumns,
+            Optional<List<DeltaLakeColumnHandle>> newColumns)
     {
         try {
             // We are writing checkpoint synchronously. It should not be long lasting operation for tables where transaction log is not humongous.
             // Tables with really huge transaction logs would behave poorly in read flow already.
-            if (isSchemaChanged) {
-                // Always write a checkpoint on schema change
-                writeCheckpoint(session, table, tableLocation, credentialsHandle, newVersion);
+            boolean checkpointNeeded = false;
```
Comment (chenjian2664) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: how about add a helper method similar to:
```

    private boolean isCheckpointNeeded(
            ConnectorSession session,
            SchemaTableName table,
            String tableLocation,
            VendedCredentialsHandle credentialsHandle,
            long readVersion,
            Optional<Long> checkpointInterval,
            long newVersion,
            Optional<List<DeltaLakeColumnHandle>> existingColumns,
            Optional<List<DeltaLakeColumnHandle>> newColumns)
    {
        // If columns have changed: we need to write a new checkpoint
        if (columnChangeRequiresCheckpoint(existingColumns, newColumns)) {
            return true;
        }

        // If we've reached the checkpoint writing interval: we need to write a checkpoint
        long lastCheckpointVersion = getLastCheckpointVersion(session, table, tableLocation, readVersion, credentialsHandle);
        return newVersion - lastCheckpointVersion >= checkpointInterval.orElse(defaultCheckpointInterval);
    }
```

Comment (Pluies) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: I like the idea here; on it!

Comment (Pluies) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java]: Extracted (including relevant comment) in https://github.com/trinodb/trino/pull/28312/changes/51d448704bf1e74a75617da064ef54ea7293a5a8 👍

**Comment by chenjian2664** [comment]
@Pluies Please squash the commits
