### PR TITLE
Ensure first table matched rule in access control

### LINKED ISSUE #12203: The masking logic has been broken since 376
Regression due to https://github.com/trinodb/trino/pull/11654

Access control should pick the first matched table rule and not the first with a masking column.

Setting the following access control:
```
{
  "tables": [
    {
      "catalog": "some-catalog",
      "schema": "my_schema",
      "table": "my_table",
      "privileges": ["SELECT", "GRANT_SELECT", "OWNERSHIP", "INSERT", "DELETE", "UPDATE"],
      "group": "group1"
    },
    {
      "catalog": "some-catalog",
      "schema": "my_schema",
      "table": "my_table",
      "columns" : [
         {
           "name": "col_a",
           "mask": "'mask_a'"
         },
         {
           "name": "col_b",
           "mask": "'mask_b'"
         }
      ],
      "privileges": ["SELECT", "GRANT_SELECT"],
      "group": "group2"
    }
  ]
}

```
any user that belongs to `group1` (and in particular to both groups: `group1` and `group2`) is allowed to access `my_table` without masking.

With https://github.com/trinodb/trino/pull/11654 a user that belongs to both groups will be masked by the second matched rule of `group2` and will not be able to INSERT data ( `io.trino.spi.TrinoException: Insert into table with column masks is not supported`)

cc @kokosing @ksobolew

### PR DESCRIPTION
**Pull request by guyco33**
although it doesn't have masked columns or table filters

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

Fix regression for PR https://github.com/trinodb/trino/pull/11654

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

> How would you describe this change to a non-technical end user or system administrator?

## Related issues, pull requests, and links

Fixes #12203

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by Praveen2112 — COMMENTED** [review]
I think we need it to be fixed for  `FileBasedAccessControl` ? Can we have similar tests for them ?

**Comment by Praveen2112** [comment]
@ksobolew Can you please take a look at this fix ?

**Review by ksobolew — COMMENTED** [review]
Sorry, my bad. Streams of Optionals are tricky, and I was not really sure what the expected semantics are (initially I wanted to return all matching rules). The fix looks good, but as @Praveen2112 says, this should also be applied to connector-level `FileBasedAccessControl`.

File: lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java [hunk 1]
```diff
@@ -687,6 +687,50 @@ public void testTableRulesForCheckCanRenameColumn()
...
+                new ViewExpression(userGroup2.getIdentity().getUser(), Optional.of("some-catalog"), Optional.of("my_schema"), "'mask_a'"));
+
+        SystemSecurityContext userGroup1Group3 = new SystemSecurityContext(Identity.forUser("user_1_3")
+                .withGroups(ImmutableSet.of("group1", "group3")).build(), Optional.empty());
+        SystemSecurityContext userGroup3 = new SystemSecurityContext(Identity.forUser("user_3")
+                .withGroups(ImmutableSet.of("group3")).build(), Optional.empty());
+
+        assertEquals(
+                accessControl.getRowFilters(
+                        userGroup1Group3,
```
Comment (martint) [inline lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java:723]: This is interesting edge case. The user belongs to group1 and group3, but the table only has a filter for group3. I'm not quite sure what the correct semantics should be here. 

For instance, the first entry may be about allowing users in group1 (e.g., employees in some department) to access a table, but the second entry might be about limiting what users in group3 can see (e.g., employees in some specific geography). In that case, it should use all filters that are present. 

Let me think more about it.

Comment (guyco33) [reply lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java:723]: I think that in all cases we should pick the first matching rule. This way we can control the way we want to limit access.
For example, in cases that we want to implement a more restrictive approach, we will place the table rules with filters and masks before the rules without them.

Comment (ksobolew) [reply lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java:723]: I personally would lean towards returning all matching rules. But I'm not very familiar with file-based AC and its use cases so I'm not sure what's actually expected.

> I think that in all cases we should pick the first matching rule. This way we can control the way we want to limit access.

But doesn't it mean that if there is a second matching rule, it will never actually be returned and is entirely redundant?

**Review by ksobolew — APPROVED** [review]
Approving because it restores the behavior to the state from before #11654, though actual semantics are a matter of discussion.

File: lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java (hunk 1 above)
Comment (guyco33) [reply lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java:723]: Safe logic for returning all matching rules must take into account the rules without filters and maskings.
Rules order is important, so possible solution might be retrieving all matched filters / maskings rules until a rule without filter / masks is matched. 
Anyway it's a subject for different PR

**Review by Praveen2112 — APPROVED** [review]

**Comment by Praveen2112** [comment]
Merged !! Thanks for fixing this.
