### PR TITLE
Handle mixed array fields in ES

### LINKED ISSUE #7012: Elasticsearch fields with a single value should be handled alongside with fields that have multiple values (Array)
**Introduction**
From [Trino docs](https://trino.io/docs/current/connector/elasticsearch.html#array-types): 

> Fields in Elasticsearch can contain [zero or more values](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html) , but there is no dedicated array type.

In order for Trino to handle a field that contains an array, that field [**has** to be inserted](https://trino.io/docs/current/connector/elasticsearch.html#array-types) under a Trino-specific structure in the `_meta` section of the index mapping.

**Problem Statement**
In cases where the same field both contains single and multiple values (such as `"score": "97"` and `"score": ["97", "90"]`, then Trino throws out the following error since we have (and we must) specify that this field is an array under the `"_meta"` section of the index mapping.
`io.trino.spi.TrinoException: Expected list of elements for field 'score' of type ARRAY: 97 [String]`

If we don't add this field under the `"_meta"` section of the index mapping, then we receive the following error:
`Expected a string or numeric value for field 'score' of type VARCHAR: [97, 90] [ArrayList]`

**Additional Info**
@martint from the slack `#troubleshooting` channel

>:
martin  1 day ago
oh, actually… this is a bug, I think. Elasticsearch doesn’t have a proper concept of array types. That’s why we had to add the mechanism for explicit mappings. In the case where a document contains a single element, it should be interpreted as a single-element array.
The case that would be hard support is when the elements have mixed types across documents, but that’s no different than documents having mixed scalar types.

### PR DESCRIPTION
**Pull request by martint**
Allow interpreting scalar values as single-element arrays if a field
was tagged as an array field in the index mapping

Fixes https://github.com/trinodb/trino/issues/7012

### CODE REVIEW

File: plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchSmokeTest.java [hunk 1]
```diff
@@ -283,6 +283,44 @@ public void testArrayFields()
                 "VALUES ('hello', 20, 30, 60, NULL)");
     }
 
+    @Test
+    public void testMixedArray()
+            throws IOException
+    {
+        String indexName = "test_arrays";
```
Comment (phd3) [inline plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchSmokeTest.java:290]: nit: use different name than `testArrayFields`

```
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test_arrays/XxPYXOdjSF6S85ZXKIeEOA] already exists","index_uuid":"XxPYXOdjSF6S85ZXKIeEOA","index":"test_arrays"}],"type":"resource_already_exists_exception","reason":"index [test_arrays/XxPYXOdjSF6S85ZXKIeEOA] already exists","index_uuid":"XxPYXOdjSF6S85ZXKIeEOA","index":"test_arrays"},"status":400}
2021-03-11T01:55:51.4867093Z 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:355)
2021-03-11T01:55:51.4868699Z 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:344)
2021-03-11T01:55:51.4870532Z 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
2021-03-11T01:55:51.4874075Z 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
2021-03-11T01:55:51.4879707Z 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
2021-03-11T01:55:51.4884231Z 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
2021-03-11T01:55:51.4925823Z 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
2021-03-11T01:55:51.4929055Z 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
2021-03-11T01:55:51.4931973Z 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
2021-03-11T01:55:51.4934818Z 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
2021-03-11T01:55:51.4937484Z 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
2021-03-11T01:55:51.4940556Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
2021-03-11T01:55:51.4943591Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
2021-03-11T01:55:51.4948969Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
2021-03-11T01:55:51.4951738Z 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
2021-03-11T01:55:51.4997222Z 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
2021-03-11T01:55:51.4999488Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

File: plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchSmokeTest.java [hunk 2]
```diff
@@ -283,6 +283,44 @@ public void testArrayFields()
...
+                "      }" +
+                "}";
+
+        createIndex(indexName, mapping);
+
+        index(indexName, ImmutableMap.<String, Object>builder()
+                .put("a", "hello")
+                .build());
+
+        index(indexName, ImmutableMap.<String, Object>builder()
```
Comment (phd3) [inline plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchSmokeTest.java:315]: optional: we could add an assertion in the test that missing value is still interpreted as `null` array and not something funny like `array[null]`.

File: plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchSmokeTest.java [hunk 3]
```diff
@@ -283,6 +283,44 @@ public void testArrayFields()
...
+        String mapping = "" +
+                "{" +
+                "      \"_meta\": {" +
+                "        \"presto\": {" +
+                "          \"a\": {" +
+                "                \"isArray\": true" +
+                "          }" +
+                "        }" +
+                "      }," +
+                "      \"properties\":{" +
```
Comment (phd3) [inline plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchSmokeTest.java:302]: nit: space after `:`

**Review by phd3 — APPROVED** [review]
LGTM.

**Review by bitsondatadev — APPROVED** [review]
Solution + test looks good!
