### PR TITLE
Don't show unsupported AUTHORIZATION ROLE in Hive schema

### LINKED ISSUE #8817: Show create schema for hive connector displays unsupported AUTHORIZATION ROLE property
Query:
```
trino> create schema hive.my_test with (location = 's3://starburst-benchmark-data/my_test');
CREATE SCHEMA
trino> show create schema hive.my_test;
                     Create Schema
-------------------------------------------------------
 CREATE SCHEMA hive.my_test
 AUTHORIZATION ROLE public
 WITH (
    location = 's3://starburst-benchmark-data/my_test'
 )
(1 row)

Query 20210806_110755_00966_uhfzg, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.46 [0 rows, 0B] [0 rows/s, 0B/s]

trino> drop schema hive.my_test;
DROP SCHEMA
trino> CREATE SCHEMA hive.my_test
    ->  AUTHORIZATION ROLE public
    ->  WITH (
    ->     location = 's3://starburst-benchmark-data/my_test'
    ->  );
Query 20210806_110809_00968_uhfzg failed: This connector does not support roles
```

Expected behaviour: sql statement as produced by `show create schema` should work and allow to create schema.

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Don't show unsupported `AUTHORIZATION ROLE` property in `SHOW CREATE SCHEMA` result when the access control doesn't support roles in Hive connector.
Fixes #8817

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Hive
* Don't show unsupported `AUTHORIZATION ROLE` property in `SHOW CREATE SCHEMA` result when the access control doesn't support roles. ({issue}`8817`)
```

### CODE REVIEW

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/AccessControlMetadata.java [hunk 1]
```diff
@@ -34,6 +34,11 @@ default boolean isUsingSystemSecurity()
         return false;
     }
 
+    default boolean supportsRole()
+    {
+        return false;
```
Comment (findepi) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/AccessControlMetadata.java:39]: "supportsRoles" (plural)?

also, this should be used in default implementations of all other role-related methods.

File: plugin/trino-hive/src/test/resources/io/trino/plugin/hive/security.json [hunk 2]
```diff
@@ -10,7 +10,7 @@
   ],
   "schemas": [
     {
-      "owner": false
+      "owner": true
```
Comment (findepi) [inline plugin/trino-hive/src/test/resources/io/trino/plugin/hive/security.json:13]: Why this change?

Comment (ebyhr) [reply plugin/trino-hive/src/test/resources/io/trino/plugin/hive/security.json:13]: Otherwise, a new test in `TestHiveFileBasedSecurity` fails due to permission error. Existing tests don't depend on this condition as far as I confirmed.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/AccessControlMetadata.java [hunk 3]
```diff
@@ -34,6 +35,11 @@ default boolean isUsingSystemSecurity()
         return false;
     }
 
+    default boolean supportsRoles()
```
Comment (kokosing) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/AccessControlMetadata.java:38]: I don't like it. Maybe we should have `AccessControlMetadata` to be bound as `Optional`?

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java [hunk 4]
```diff
@@ -2549,6 +2549,10 @@ public Optional<TrinoPrincipal> getSchemaOwner(ConnectorSession session, Catalog
     {
         checkState(!isHiveSystemSchema(schemaName.getSchemaName()), "Schema is not accessible: %s", schemaName);
 
+        if (!accessControlMetadata.supportsRoles()) {
```
Comment (kokosing) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java:2552]: I think it exposes some issue in the engine. If engine controls ownership elsewhere it should not even ask connector for the owner.

**Review by kokosing — COMMENTED** [review]
skimmed

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java (hunk 4 above)
Comment (kokosing) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java:2552]: I think I get it now, it is about using `allow-all` so you now don't return the owner of the schema in such case.

I am not sure if it is the way to go. Support of roles and ownership could be seen independent from each other. I mean returning role as owner would seem odd, but returning an user sounds ok.

Should we move this method implementation to `AccessControlMetadata`?

What about owner for table and view?

Comment (ebyhr) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java]: Moved to `AccessControlMetadata`. `SHOW CREATE` table and view don't show the owner if my understanding is correct.

Comment (kokosing) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java]: I know, but it is more about the logical ownership. The thing that schema owner is used today should define the actual design decision.

**Comment by ebyhr** [comment]
Just rebased on upstream.

**Comment by dain** [comment]
Have we considered going the opposite direction and instead adding support for setting the owner directly during create schema?

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/AccessControlMetadata.java [hunk 5]
```diff
@@ -120,6 +120,14 @@ default void grantSchemaPrivileges(ConnectorSession session, String schemaName,
         throw new TrinoException(NOT_SUPPORTED, "This connector does not support grants on schemas");
     }
 
+    /**
+     * Get the owner on the specified schema
+     */
+    default Optional<HivePrincipal> getSchemaOwner(ConnectorSession session, String schemaName)
+    {
+        return Optional.empty();
```
Comment (findepi) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/AccessControlMetadata.java:128]: Should this throw in the default implementation?
Looks like all other methods do throw by default.

**Review by kokosing — APPROVED** [review]

**Comment by hashhar** [comment]
Ci seems to fail. PTAL https://github.com/trinodb/trino/actions/runs/3410817080/jobs/5674773042#step:4:348

```
Error:  io.trino.plugin.iceberg.catalog.glue.TestSharedGlueMetastore.testShowSchemas  Time elapsed: 0.919 s  <<< FAILURE!
java.lang.AssertionError: 
expected [CREATE SCHEMA hive.test_shared_schema_14x52kn5jo
AUTHORIZATION ROLE public
WITH (
   location = '/tmp/TrinoTest16557917362932507789/iceberg_data'
)] but found [CREATE SCHEMA hive.test_shared_schema_14x52kn5jo
WITH (
   location = '/tmp/TrinoTest16557917362932507789/iceberg_data'
)]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at io.trino.plugin.iceberg.BaseSharedMetastoreTest.testShowSchemas(BaseSharedMetastoreTest.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

and

```
Error:  io.trino.plugin.deltalake.TestDeltaLakeSharedGlueMetastoreWithTableRedirections.testShowSchemas  Time elapsed: 2.98 s  <<< FAILURE!
java.lang.AssertionError: 
expected [CREATE SCHEMA hive_with_redirections.test_shared_schema_1oiyqgnkkd
AUTHORIZATION ROLE public
WITH (
   location = '/tmp/TrinoTest1321593021550281499/delta_lake_data'
)] but found [CREATE SCHEMA hive_with_redirections.test_shared_schema_1oiyqgnkkd
WITH (
   location = '/tmp/TrinoTest1321593021550281499/delta_lake_data'
)]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at io.trino.plugin.deltalake.BaseDeltaLakeSharedMetastoreWithTableRedirectionsTest.testShowSchemas(BaseDeltaLakeSharedMetastoreWithTableRedirectionsTest.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ebyhr** [comment]
@hashhar Thanks for catching that. Sent #14940
