### PR TITLE
Fix wrong field path in Elasticsearch ROW type

### LINKED ISSUE #12250: Trino is not supporting Date type in ElasticDB nested fields
I'm trying to query on date fields(ISO formated) with ElasticDB.
Able to query on direct fields like..

```
trino> select createdtime from elasticsearch.default.alerts limit 3;
       createdtime       
-------------------------
 NULL                    
 2021-12-21 07:04:20.000 
 2022-04-18 12:29:32.000 
(3 rows)
```
but not on nested fields.
```
trino> select statushistory.acknowledgedBy from elasticsearch.default.alerts limit 3;

Query 20220420_110046_00003_ez866, FAILED, 1 node
Splits: 4 total, 0 done (0.00%)
1.07 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220420_110046_00003_ez866 failed: Text '2022-04-18T11:36:44+0100' could not be parsed, unparsed text found at index 19
```
**FYI**: Both fields defined as timestamp(3)

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #12250

## Documentation

(x) No documentation is needed.

## Release notes

( ) No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# Elasticsearch
* Fix failure when reading not ISO 8601 formatted timestamp values in `row` type. ({issue}`12250`)
```

### CODE REVIEW

File: plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java [hunk 1]
```diff
@@ -364,7 +364,7 @@ else if (type instanceof ObjectType) {
             ImmutableList.Builder<RowDecoder.NameAndDescriptor> decoderFields = ImmutableList.builder();
             for (IndexMetadata.Field rowField : objectType.getFields()) {
                 String name = rowField.getName();
-                TypeAndDecoder child = toTrino(appendPath(path, name), rowField);
```
Comment (Praveen2112) [inline plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java:367]: Does it fail only for timestamp or even for other types ? Do we have tests for other data types ?

Comment (ebyhr) [reply plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java:367]: Other types look fine as far as I confirmed. Basic test cases exist in `testDataTypesNested`. 
https://github.com/trinodb/trino/blob/c4711c10e66d21ecce78a5fa261da8783ed0d1cb/plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java#L1549

**Review by Praveen2112 — APPROVED** [review]
