### PR TITLE
Deny writing unsupported dates in ClickHouse

### LINKED ISSUE #10055: ClickHouse DATE type stores incorrect result when the value is out of range
This might be expected behavior as ClickHouse, but I suppose we should deny such values during CTAS & INSERT in Trino side.

```bash
trino> CREATE TABLE clickhouse.tpch.test_date (c1 DATE);
CREATE TABLE
trino> INSERT INTO clickhouse.tpch.test_date VALUES (DATE '9999-12-31');
INSERT: 1 row

trino> SELECT * FROM clickhouse.tpch.test_date;
     c1
------------
 1970-01-01
```

https://clickhouse.com/docs/en/sql-reference/data-types/date/

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #10055

### CODE REVIEW

File: plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java [hunk 1]
```diff
@@ -546,6 +550,30 @@ else if (prop.size() == 1) {
...
+            verifySupportedDate(value);
+            statement.setObject(index, LocalDate.ofEpochDay(value));
+        };
+    }
+
+    private static void verifySupportedDate(long value)
+    {
+        // Deny unsupported dates eagerly to prevent unexpected results. ClickHouse stores '1970-01-01' when the date is out of supported range.
+        if (value < MIN_SUPPORTED_DATE_EPOCH || value > MAX_SUPPORTED_DATE_EPOCH) {
+            throw new TrinoException(INVALID_ARGUMENTS, format("Epoch must be between %s and %s: %s", MIN_SUPPORTED_DATE_EPOCH, MAX_SUPPORTED_DATE_EPOCH, value));
```
Comment (electrum) [inline plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java:573]: An epoch is an "instant in time", so I think it makes more sense to say "Date must be between ..."

File: plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java [hunk 2]
```diff
@@ -416,6 +415,19 @@ public void testDate(ZoneId sessionZone)
                 .execute(getQueryRunner(), session, clickhouseCreateAndInsert("tpch.test_date"));
     }
 
+    @Test
+    public void testUnsupportedDate()
+    {
+        try (TestTable table = new TestTable(getQueryRunner()::execute, "test_unsupported_date", "(dt date)")) {
+            assertQueryFails(
+                    format("INSERT INTO %s VALUES (DATE '1969-12-31')", table.getName()),
+                    "Epoch must be between 0 and 49710: -1");
```
Comment (electrum) [inline plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java:424]: It would be better to format these as dates, since that is what the user interacts with. How Clickhouse stores dates internally shouldn't matter to the Trino user.

> Date must be between 1970-01-01 and 2106-02-07: 1969-12-31

**Review by electrum — APPROVED** [review]
Minor comments about the error message, otherwise looks good
