### PR TITLE
Iceberg DML operation timeout avoids corrupting the table

### LINKED ISSUE #14104: Missing iceberg manifest list file after HMS read times out
Hey folks, we are running Trino 385 on self-managed EKS cluster on AWS and have been seeing missing manifest list file issue frequently in the event of HMS read timeout, similar to this issue https://github.com/trinodb/trino/issues/12581

`"message":"java.sql.SQLException: Query failed (#20220830_200538_00217_v3bfb): Failed to get status for file: s3://our_bucket/our_table/metadata/snap-5248356702593051690-1-4bab0c8e-543c-41bd-99a7-62dcb1864795.avro`

We have enabled object versioning and CloudTrail and can confirm the manifest list file exists and is deleted by Trino. From our Trino log, it looks like that the iceberg library removes the manifest list file in the event of commit failure despite the fact the snapshot has been successfully committed. Here's our query log: 

1. Execute a INSERT SELECT FROM statement (QueryId: 20220830_195613_00200)
2. Iceberg performs a base table scans with snapshot ID 7266396334490458249
```
2022-08-30T19:56:15.027Z INFO Query-20220830_195613_00200_v3bfb-2519 
org.apache.iceberg.BaseTableScan Scanning table "our_schema"."our_table" snapshot 7266396334490458249 created at 2022-08-30 16:37:05.638 with filter true
```
3. Trino successfully committed a snapshot 5248356702593051690
```
2022-08-30T19:56:17.780Z INFO 20220830_195613_00200_v3bfb.0.0.0-32-257 
org.apache.iceberg.SnapshotProducer Committed snapshot 5248356702593051690 (MergeAppend)
```
4. Despite that the snapshot is successfully committed, Trino reports commit task failure org.apache.iceberg.exceptions.CommitFailedException (This stack trace is taken from Splunk so the execution order might not be accurate )
```
org.apache.iceberg.exceptions.CommitFailedException: Failed to commit to table our_schema.our_table
at io.trino.plugin.iceberg.catalog.AbstractIcebergTableOperations.commit(AbstractIcebergTableOperations.java:150)
at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$5(BaseTransaction.java:386)
at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214)
at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198)
at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190)
at org.apache.iceberg.BaseTransaction.commitSimpleTransaction(BaseTransaction.java:378)
at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:268)
at io.trino.plugin.iceberg.IcebergMetadata.finishInsert(IcebergMetadata.java:752)
at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:504)
at io.trino.metadata.MetadataManager.finishInsert(MetadataManager.java:892)
at io.trino.sql.planner.LocalExecutionPlanner.lambda$createTableFinisher$3(LocalExecutionPlanner.java:3962)
at io.trino.operator.TableFinishOperator.getOutput(TableFinishOperator.java:319)
at io.trino.operator.Driver.processInternal(Driver.java:410)
at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
at io.trino.operator.Driver.tryWithLock(Driver.java:698)
at io.trino.operator.Driver.process(Driver.java:305)
at io.trino.operator.Driver.processForDuration(Driver.java:276)
at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
 at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
at io.trino.$gen.Trino_385_sfdc_2_4d4b287____20220830_184755_2.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.trino.spi.TrinoException: bdmpresto-hive-002.presto-hive-metastore.uip.aws-esvc1-useast2.aws.sfdc.is:80: java.net.SocketTimeoutException: Read timed out
at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.alterTable(ThriftHiveMetastore.java:1161)
at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.alterTable(BridgingHiveMetastore.java:340)
at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.replaceTable(BridgingHiveMetastore.java:219)
at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.replaceTable(CachingHiveMetastore.java:523)
at io.trino.plugin.iceberg.catalog.hms.HiveMetastoreTableOperations.commitToExistingTable(HiveMetastoreTableOperations.java:93)
... 25 more
... more
```
5. As the result of CommitFailedException , Iceberg retries the commit 4 times and all of the retry attempts failed. The retry attempts were exhausted and eventually the query failed. 
```
2022-08-30T19:58:18.386Z WARN 20220830_195613_00200_v3bfb.0.0.0-32-257 org.apache.iceberg.util.Tasks Retrying task after failure: Failed to commit to table our_schema.our_table
2022-08-30T20:00:18.894Z WARN 20220830_195613_00200_v3bfb.0.0.0-32-257 org.apache.iceberg.util.Tasks Retrying task after failure: Failed to commit to table  our_schema.our_table
2022-08-30T20:02:19.543Z WARN 20220830_195613_00200_v3bfb.0.0.0-32-257 org.apache.iceberg.util.Tasks Retrying task after failure: Failed to commit to table  our_schema.our_table
2022-08-30T20:04:20.385Z WARN 20220830_195613_00200_v3bfb.0.0.0-32-257 org.apache.iceberg.util.Tasks Retrying task after failure: Failed to commit to table  our_schema.our_table

2022-08-30T20:05:32.872Z ERROR SplitRunner-151-257 io.trino.execution.executor.TaskExecutor Error processing Split 20220830_195613_00200_v3bfb.0.0.0-32 (start = 4349124.505863, wall = 557971 ms, cpu = 7 ms, wait = 7 ms, calls = 27)
2022-08-30T20:05:32.876Z ERROR remote-task-callback-1373 io.trino.execution.scheduler.PipelinedStageExecution Pipelined stage execution for stage 20220830_195613_00200_v3bfb.0 failed
2022-08-30T20:05:32.878Z ERROR stage-scheduler io.trino.execution.StageStateMachine Stage 20220830_195613_00200_v3bfb.0 failed
```
6. After this query failure, we start to see missing manifest list error. For example,  query 20220830_200538_00217_v3bfb-2732. When performing base table scan, the metadata file is now pointing at the new snapshot created from Step 3. Yet the manifest list file is missing, resulting in query failure: 

```
2022-08-30T20:05:39.366Z INFO Query-20220830_200538_00217_v3bfb-2732 
org.apache.iceberg.BaseTableScan Scanning table "sdb_trace_non_prod_hourly"."statement_text" snapshot 5248356702593051690 created at 2022-08-30 19:56:17.773 with filter true

"message":"java.sql.SQLException: Query failed (#20220830_200538_00217_v3bfb): Failed to get status for file: s3://our_bucket/our_table/metadata/snap-5248356702593051690-1-4bab0c8e-543c-41bd-99a7-62dcb1864795.avro
```

It looks like Iceberg successfully committed a snapshot change. However, because of the CommitFailedException,
The manifest list file that was created along with the snapshot was deleted. We dived deeper into the iceberg library and suspected that this is where iceberg removes manifest list in the event of commit failure: [commitSimpleTransaction](https://github.com/apache/iceberg/blob/cc7e6d9fa259707a5c690b3534ea6b5c7da3fc05/core/src/main/java/org/apache/iceberg/BaseTransaction.java#L402) calls 
[cleanUpOnCommitFailure](https://github.com/apache/iceberg/blob/cc7e6d9fa259707a5c690b3534ea6b5c7da3fc05/core/src/main/java/org/apache/iceberg/BaseTransaction.java#L443) in the event of commit failure. Then 
[cleanAll](https://github.com/apache/iceberg/blob/cc7e6d9fa259707a5c690b3534ea6b5c7da3fc05/core/src/main/java/org/apache/iceberg/SnapshotProducer.java#L435) is called to remove manifest list file in the new snapshot update. 

Can someone in the community help us understand:
1. Why would a commitTaskFailure exception be thrown when the snapshot has been successfully committed?
2. When a commitFailedException is thrown, is the commit state known or unknown? If the state is known, removing the manifest list after a successful snapshot creation and commitFailedException will corrupt the table. Should we avoid removing manifest file when the metadata file is updated?

Thanks in advance!

### PR DESCRIPTION
**Pull request by findinpath**
## Description

In case of dealing with an `CommitFailedException` while
commiting an Iceberg transaction, the Iceberg framework
will attempt to retry for `COMMIT_NUM_RETRIES` times the
operation and if the operation still fails, it will clean up
the metadata file corresponding to the transaction.
In case of a metastore client timeout operation the
Iceberg library can therefore delete metadata files
which eventually get referenced from the configuration
of the table persisted on the metastore for the table
which leaves the table in a corrupt state.

Throw `CommitStateUnknownException` to ensure that the
table is not left in a corrupt state after the erroneous
completion of the DML operation.

Fixes #14104
probably fixes https://github.com/trinodb/trino/issues/12581 too

## Non-technical explanation

Avoid deleting metadata files in case of a DML operation timeout because these filesmay eventually get referenced from the Hive metastore configuration of the Iceberg table.

## Release notes

( ) This is not user-visible and no release notes are required.
( ) Release notes are required, please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Iceberg
* Iceberg DML operation timeout avoids corrupting the table
```

### CODE REVIEW

**Review by homar — APPROVED** [review]

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java [hunk 1]
```diff
@@ -76,7 +77,7 @@ protected void commitToExistingTable(TableMetadata base, TableMetadata metadata)
             metastore.replaceTable(database, tableName, table, privileges);
         }
         catch (RuntimeException e) {
-            throw new CommitFailedException(e, "Failed to commit transaction to FileHiveMetastore");
+            throw new CommitStateUnknownException(e);
```
Comment (osscm) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java:80]: thanks for fixing this!

wondering, can there be still a situation while handling `RuntimeException` that we need to `CommitFailedException` to make sure its retried and cleaned up the Iceberg Library?
Or was it introduced to handle any specific case?

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+        try {
+            baseDir = Files.createTempDirectory(null).toFile();
+        }
+        catch (IOException e) {
+            throw new UncheckedIOException(e);
+        }
+
+        HdfsConfig hdfsConfig = new HdfsConfig();
+        HdfsConfiguration hdfsConfiguration = new DynamicHdfsConfiguration(new HdfsConfigurationInitializer(hdfsConfig), ImmutableSet.of());
+        HdfsEnvironment hdfsEnvironment = new HdfsEnvironment(hdfsConfiguration, hdfsConfig, new NoHdfsAuthentication());
```
Comment (electrum) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java:78]: Use `HiveTestUtils.HDFS_ENVIRONMENT` if possible

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java (hunk 1 above)
Comment (electrum) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java:80]: We'd need to handle transient and non-transient errors differently, which we don't do today and is hard to do since it depends on the underlying implementation. In general, permanent (non-transient) errors are not expected to happen frequently, so I don't think we need to worry about it.

If this causes a problem for someone, we can look at the specific situation and figure out how to handle it.

**Review by electrum — COMMENTED** [review]
Do you plan to squash the first commit?

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+            @Override
+            public synchronized void replaceTable(String databaseName, String tableName, Table newTable, PrincipalPrivileges principalPrivileges)
+            {
+                replaceTableAttempts++;
+                if (replaceTableAttempts == (COMMIT_NUM_RETRIES_DEFAULT + 1)) {
+                    // Ensure that on the last retry operation the `replaceTable` does indeed succeed
+                    // and the table points to a new metadata file
+                    super.replaceTable(databaseName, tableName, newTable, principalPrivileges);
+                }
+                if (true) {
```
Comment (electrum) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java:91]: Not needed

**Comment by findinpath** [comment]
> Do you plan to squash the first commit?

The added value of the first commit is only for maintenance reasons. Squashing the commits would leave a naive reader of the code without any clear context related to the problem being addressed in the commit.
I'm fine either way. I wanted to have a test at hand that showcases the issue and not blindly add a fix.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java (hunk 1 above)
Comment (findinpath) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java:89]: There are a few tests:

- `TestIcebergOrcConnectorTest.testInsertRowConcurrently` 
- `TestIcebergConnectorSmokeTest.testDeleteRowsConcurrently`

which failed due to concurrent modifications exceptions.


I added a special handling in the `FileMetastoreTableOperations`

```
            if (e instanceof TrinoException trinoException &&
                    trinoException.getErrorCode() == HIVE_METASTORE_ERROR.toErrorCode() &&
                    Objects.equals(trinoException.getMessage(), "Cannot update Iceberg table: supplied previous location does not match current location")) {
                // CommitFailedException is handled as a special case in the Iceberg library. This commit will automatically retry
                throw new CommitFailedException(e, "Failed to replace table due to concurrent updates: %s.%s", database, tableName);
            }
```

@electrum  is this what you were hinting at in  https://github.com/trinodb/trino/issues/14104#issuecomment-1244755074

> We can handle it by checking for the ` supplied previous location does not match current location` exception message.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java [hunk 4]
```diff
@@ -90,8 +91,7 @@ protected void commitToExistingTable(TableMetadata base, TableMetadata metadata)
                 metastore.replaceTable(database, tableName, table, privileges);
             }
             catch (RuntimeException e) {
-                // CommitFailedException is handled as a special case in the Iceberg library. This commit will automatically retry
-                throw new CommitFailedException(e, "Failed to commit to table %s.%s", database, tableName);
+                throw new CommitStateUnknownException(e);
```
Comment (marton-bod) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java:94]: Just to double-check: we don't need the same logic here as in `FileMetastoreTableOperations`, i.e. to throw a `CommitFailedException` in case the commit swap unambiguously failed?

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java [hunk 5]
```diff
@@ -76,7 +80,13 @@ protected void commitToExistingTable(TableMetadata base, TableMetadata metadata)
             metastore.replaceTable(database, tableName, table, privileges);
         }
         catch (RuntimeException e) {
-            throw new CommitFailedException(e, "Failed to commit transaction to FileHiveMetastore");
+            if (e instanceof TrinoException trinoException &&
+                    trinoException.getErrorCode() == HIVE_METASTORE_ERROR.toErrorCode() &&
+                    Objects.equals(trinoException.getMessage(), "Cannot update Iceberg table: supplied previous location does not match current location")) {
+                // CommitFailedException is handled as a special case in the Iceberg library. This commit will automatically retry
+                throw new CommitFailedException(e, "Failed to replace table due to concurrent updates: %s.%s", database, tableName);
```
Comment (marton-bod) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java:87]: nit: since this string constant is present in a couple of places in the codebase, is it worth pulling it out?

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java [hunk 6]
```diff
@@ -76,7 +80,13 @@ protected void commitToExistingTable(TableMetadata base, TableMetadata metadata)
             metastore.replaceTable(database, tableName, table, privileges);
         }
         catch (RuntimeException e) {
-            throw new CommitFailedException(e, "Failed to commit transaction to FileHiveMetastore");
+            if (e instanceof TrinoException trinoException &&
+                    trinoException.getErrorCode() == HIVE_METASTORE_ERROR.toErrorCode() &&
+                    Objects.equals(trinoException.getMessage(), "Cannot update Iceberg table: supplied previous location does not match current location")) {
+                // CommitFailedException is handled as a special case in the Iceberg library. This commit will automatically retry
```
Comment (marton-bod) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java:86]: nit: the essence of this comment for me is that this is the only scenario in which it's safe to delete the metadata files from the FS and retry (in all other scenarios it's not possible to tell with certainty whether the commit swap succeeded, so it's up to the user to ascertain)

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java (hunk 4 above)
Comment (findinpath) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java:94]: I think https://github.com/trinodb/trino/pull/14118/files/2e46887b6ea7f08a725c2e3169abc553f35ceaa8#r970003583 answers your question.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java (hunk 6 above)
Comment (findinpath) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java:86]: @marton-bod 

> the essence of this comment for me is that this is the only scenario in which it's safe to delete the metadata files from the FS and retry

The metadata files are removed only after exhausting the retries.

Note that [cleanUpOnCommitFailure ](https://github.com/apache/iceberg/blob/cc7e6d9fa259707a5c690b3534ea6b5c7da3fc05/core/src/main/java/org/apache/iceberg/BaseTransaction.java#L402) is thrown only after exhausting the retries.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java [hunk 7]
```diff
@@ -0,0 +1,142 @@
...
+                .setCatalog(ICEBERG_CATALOG)
+                .setSchema(SCHEMA_NAME)
+                .build();
+
+        try {
+            baseDir = Files.createTempDirectory(null).toFile();
+        }
+        catch (IOException e) {
+            throw new UncheckedIOException(e);
+        }
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java:68]: remove `try`, `catch`.
`createQueryRunner()` can throw any `Exception`

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java [hunk 8]
```diff
@@ -0,0 +1,142 @@
...
+                .setDatabaseName(SCHEMA_NAME)
+                .setOwnerName(Optional.of("public"))
+                .setOwnerType(Optional.of(PrincipalType.ROLE))
+                .build();
+        metastore.createDatabase(database);
+
+        return queryRunner;
+    }
+
+    @BeforeMethod
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java]: the test class should be single-threaded.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java [hunk 9]
```diff
@@ -82,12 +78,7 @@ protected LocalQueryRunner createQueryRunner()
             @Override
             public synchronized void replaceTable(String databaseName, String tableName, Table newTable, PrincipalPrivileges principalPrivileges)
             {
-                replaceTableAttempts++;
-                if (replaceTableAttempts == (COMMIT_NUM_RETRIES_DEFAULT + 1)) {
-                    // Ensure that on the last retry operation the `replaceTable` does indeed succeed
-                    // and the table points to a new metadata file
-                    super.replaceTable(databaseName, tableName, newTable, principalPrivileges);
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java]: Why does the second commit change the test scaffolding?

Did you mean to amend the first commit instead?

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java [hunk 10]
```diff
@@ -76,7 +80,13 @@ protected void commitToExistingTable(TableMetadata base, TableMetadata metadata)
             metastore.replaceTable(database, tableName, table, privileges);
         }
         catch (RuntimeException e) {
-            throw new CommitFailedException(e, "Failed to commit transaction to FileHiveMetastore");
+            if (e instanceof TrinoException trinoException &&
+                    trinoException.getErrorCode() == HIVE_METASTORE_ERROR.toErrorCode() &&
+                    Objects.equals(trinoException.getMessage(), "Cannot update Iceberg table: supplied previous location does not match current location")) {
```
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java:85]: Basing the logic on exact message doesn't feel robust.
Maybe we need to have a dedicated error code for this.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java (hunk 9 above)
Comment (findinpath) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java]: This is the 2nd time this question appears in this PR https://github.com/trinodb/trino/pull/14118#issuecomment-1245864736

I'm squashing therefore the commits.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java (hunk 10 above)
Comment (findinpath) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java:85]: Thanks for the hint.
`Hive.HIVE_CONCURRENT_MODIFICATION_DETECTED` (already exists) seems appropriate for the purpose at hand.

**Review by alexjo2144 — APPROVED** [review]
Thanks Marius!

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java (hunk 4 above)
Comment (findepi) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java:94]: Document why throwing CommitStateUnknownException is important here

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java (hunk 7 above)
Comment (findepi) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java:69]: bump

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java [hunk 11]
```diff
@@ -0,0 +1,122 @@
...
+    }
+
+    @Test
+    public void testInsertFailureDoesNotCorruptTheTableMetadata()
+    {
+        String tableName = "test_insert_failure";
+
+        getQueryRunner().execute(format("CREATE TABLE %s (a_varchar) AS VALUES ('Trino')", tableName));
+        assertThatThrownBy(() -> getQueryRunner().execute("INSERT INTO " + tableName + " VALUES 'rocks'"))
+                .isInstanceOf(CommitStateUnknownException.class);
```
Comment (findepi) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreTableOperationsInsertFailure.java:110]: ... verify this is caused by the test exception thrown above

**Review by findepi — APPROVED** [review]

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
@findinpath under what circumstances should the `GlueIcebergTableOperations` throw `CommitStateUnknownException`?

**Comment by findinpath** [comment]
> under what circumstances should the GlueIcebergTableOperations throw CommitStateUnknownException?

`com.amazonaws.services.glue.AWSGlue#updateTable`

From the javadoc

```
     * @throws ConcurrentModificationException
     *         Two processes are trying to modify a resource simultaneously.
```

**Comment by findepi** [comment]
That indicates that `ConcurrentModificationException` handling is (probably) right.

Under what circumstances should we throw `CommitStateUnknownException` in `GlueIcebergTableOperations`?

**Comment by findinpath** [comment]
Good, I see where you are probably hinting. I've been too focused on the HMS part and missed the fact that Glue is also affected by the same issue.

Here is the list of exceptions thrown by `updateTable` operation:

```
EntityNotFoundException – A specified entity does not exist
InvalidInputException – The input provided was not valid.
InternalServiceException – An internal service error occurred.
OperationTimeoutException – The operation timed out.
ConcurrentModificationException – Two processes are trying to modify a resource simultaneously.
ResourceNumberLimitExceededException – A resource numerical limit was exceeded.
GlueEncryptionException – An encryption operation failed.
```

Except `ConcurrentModificationException`, `ResourceNumberLimitExceededException` (should be happening before hitting the internal metastore service so no risk of corruption here)  , `InvalidInputException` (not very sure here if there may happen that the processing of the input is not half-way through before throwing the exception) and `EntityNotFoundException` (quite unlikely to be thrown in our specific case) I'd opt to throw `CommitStateUnknownException`. 

So `ResourceNumberLimitExceededException` & `ConcurrentModificationException` ask for a retry -> let's throw a `CommitFailedException`. I'll make a follow-up PR on this topic.
