### PR TITLE
Retry when failed to communicate with Oracle after restart

### LINKED ISSUE #4568: Flaky test init TestOraclePoolIntegrationSmokeTest
```
2020-07-24T15:47:18.1678486Z [ERROR] Tests run: 256, Failures: 2, Errors: 0, Skipped: 203, Time elapsed: 486.597 s <<< FAILURE! - in TestSuite
2020-07-24T15:47:18.1685135Z [ERROR] init(io.prestosql.plugin.oracle.TestOraclePoolIntegrationSmokeTest)  Time elapsed: 255.865 s  <<< FAILURE!
2020-07-24T15:47:18.1691519Z java.lang.RuntimeException: java.sql.SQLRecoverableException: IO Error: Connection reset by peer, Authentication lapse 0 ms.
2020-07-24T15:47:18.1696116Z 	at io.prestosql.plugin.oracle.TestingOracleServer.<init>(TestingOracleServer.java:75)
2020-07-24T15:47:18.1702161Z 	at io.prestosql.plugin.oracle.BaseOracleIntegrationSmokeTest.createQueryRunner(BaseOracleIntegrationSmokeTest.java:41)
2020-07-24T15:47:18.1707186Z 	at io.prestosql.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:80)
2020-07-24T15:47:18.1712382Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-24T15:47:18.1717673Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-24T15:47:18.1726507Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-24T15:47:18.1731457Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-07-24T15:47:18.1737032Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-07-24T15:47:18.1741666Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2020-07-24T15:47:18.1746241Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2020-07-24T15:47:18.1751062Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2020-07-24T15:47:18.1756226Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2020-07-24T15:47:18.1760462Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2020-07-24T15:47:18.1767100Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-07-24T15:47:18.1773300Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-07-24T15:47:18.1776512Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-24T15:47:18.1782769Z Caused by: java.sql.SQLRecoverableException: IO Error: Connection reset by peer, Authentication lapse 0 ms.
2020-07-24T15:47:18.1786751Z 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:874)
2020-07-24T15:47:18.1791522Z 	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
2020-07-24T15:47:18.1796885Z 	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
2020-07-24T15:47:18.1801027Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
2020-07-24T15:47:18.1805352Z 	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
2020-07-24T15:47:18.1809592Z 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
2020-07-24T15:47:18.1813840Z 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
2020-07-24T15:47:18.1819013Z 	at io.prestosql.plugin.oracle.TestingOracleServer.<init>(TestingOracleServer.java:67)
2020-07-24T15:47:18.1820414Z 	... 15 more
2020-07-24T15:47:18.1825327Z Caused by: java.io.IOException: Connection reset by peer, Authentication lapse 0 ms.
2020-07-24T15:47:18.1829643Z 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:870)
2020-07-24T15:47:18.1830870Z 	... 22 more
2020-07-24T15:47:18.1834453Z Caused by: java.io.IOException: Connection reset by peer
2020-07-24T15:47:18.1838446Z 	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
2020-07-24T15:47:18.1842564Z 	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
2020-07-24T15:47:18.1846741Z 	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
2020-07-24T15:47:18.1850231Z 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
2020-07-24T15:47:18.1853368Z 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
2020-07-24T15:47:18.1858174Z 	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:355)
2020-07-24T15:47:18.1862214Z 	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:174)
2020-07-24T15:47:18.1866401Z 	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:555)
2020-07-24T15:47:18.1870358Z 	at oracle.net.ns.NIOPacket.readNIOPacket(NIOPacket.java:403)
2020-07-24T15:47:18.1874631Z 	at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:127)
2020-07-24T15:47:18.1880071Z 	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:340)
2020-07-24T15:47:18.1883988Z 	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1596)
2020-07-24T15:47:18.1887741Z 	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:588)
2020-07-24T15:47:18.1889114Z 	... 22 more
```

https://github.com/prestosql/presto/runs/907209390

### LINKED ISSUE #8917: TestOraclePoolConnectorSmokeTest is flaky
```
2021-08-18T12:20:39.6429500Z [ERROR] init(io.trino.plugin.oracle.TestOraclePoolConnectorSmokeTest)  Time elapsed: 226.1 s  <<< FAILURE!
2021-08-18T12:20:39.6431569Z java.lang.IllegalStateException: Container is started, but cannot be accessed by (JDBC URL: jdbc:oracle:thin:@localhost:49162:xe), please check container logs
2021-08-18T12:20:39.6434057Z 	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:165)
2021-08-18T12:20:39.6436597Z 	at io.trino.plugin.oracle.TestingOracleServer.<init>(TestingOracleServer.java:72)
2021-08-18T12:20:39.6439196Z 	at io.trino.plugin.oracle.TestOraclePoolConnectorSmokeTest.createQueryRunner(TestOraclePoolConnectorSmokeTest.java:35)
2021-08-18T12:20:39.6441910Z 	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:91)
2021-08-18T12:20:39.6444825Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-08-18T12:20:39.6450656Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-08-18T12:20:39.6453835Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-08-18T12:20:39.6456501Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-08-18T12:20:39.6461623Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-08-18T12:20:39.6463621Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-08-18T12:20:39.6466035Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-08-18T12:20:39.6469879Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2021-08-18T12:20:39.6476310Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2021-08-18T12:20:39.6480468Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-08-18T12:20:39.6486814Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-08-18T12:20:39.6492509Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-08-18T12:20:39.6495718Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #8917 Fixes #4568 

Stress test #9117

I tried some system options and new image `gvenzl/oracle-xe`, but didn't work well. Then, I propose just adding retry logic.

### CODE REVIEW

**Comment by hashhar** [comment]
In the last run on the stress test PR one run failed with:

```
Error:  io.trino.plugin.oracle.TestOraclePoolConnectorSmokeTest.init  Time elapsed: 39.698 s  <<< FAILURE!
java.lang.RuntimeException: 
java.sql.SQLException: ORA-01543: tablespace 'TRINO_TEST' already exists
```

Is the stress-test PR up to date with changes in this PR?

**Comment by ebyhr** [comment]
@hashhar Currently, stress-test PR is little newer than this change. Looks like there are two issues, initialization and the already-exists error.

File: plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java [hunk 1]
```diff
@@ -62,14 +68,8 @@ public TestingOracleServer()
             throw new RuntimeException(e);
         }
 
-        try {
-            execInContainer("/bin/bash", "/etc/init.d/oracle-xe", "restart");
-        }
-        catch (InterruptedException | IOException e) {
-            throw new RuntimeException(e);
-        }
+        Failsafe.with(RETRY_POLICY).run(this::restart);
```
Comment (findepi) [inline plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java:71]: I would rather tear the container down and create a container afresh.
https://github.com/trinodb/trino/blob/9b1b8296055d9bdc59dd05cc294e278c707932e9/plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java#L76-L77

**Comment by ebyhr** [comment]
#4568 seems the same issue. PR title mentions the specific test, but I think it comes from flaky Oracle server initialization.

File: plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java [hunk 2]
```diff
@@ -45,10 +59,27 @@ public TestingOracleServer()
...
+        Failsafe.with(CONTAINER_RETRY_POLICY).run(this::createContainer);
+    }
+
+    private void createContainer()
+            throws Exception
+    {
         withCopyFileToContainer(MountableFile.forClasspathResource("init.sql"), "/docker-entrypoint-initdb.d/init.sql");
 
-        start();
+        Closeable cleanup = startOrReuse(this);
```
Comment (findepi) [inline plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java:70]: Was your intention to both: add retries and make this a reusable container?
I'd suggest keeping these separate (two commits, or two PRs)

File: plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java [hunk 3]
```diff
@@ -45,10 +59,27 @@ public TestingOracleServer()
     {
         super("wnameless/oracle-xe-11g-r2");
 
+        Failsafe.with(CONTAINER_RETRY_POLICY).run(this::createContainer);
```
Comment (findepi) [inline plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java:62]: `this` is a container and has a state (created, running, healthy, etc.)
it container gets started, but further setup fails, IMO we should start with a new container

as a preparatory refactor, we should replace `extends OracleContainer` with a field in this class (composition instead of inheritance)

Comment (findepi) [reply plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java:62]: if we need `waitUntilContainerStarted` we can create a "shim" subclass ("TestingOracleContainer") that will expose this operation publicly.

File: plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java (hunk 2 above)
Comment (ebyhr) [reply plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java]: It's not my intention. Let me use `start()` method instead.

File: plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java [hunk 4]
```diff
@@ -13,43 +13,78 @@
...
 public class TestingOracleServer
-        extends OracleContainer
         implements Closeable
 {
+    private static final Logger log = Logger.get(TestingOracleServer.class);
+
+    private static final RetryPolicy<Object> CONTAINER_RETRY_POLICY = new RetryPolicy<>()
+            .withBackoff(1, 5, ChronoUnit.SECONDS)
+            .withMaxAttempts(5)
+            .handleIf(throwable -> throwable instanceof RetryableException)
```
Comment (findepi) [inline plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java:46]: Do we need `RetryableException`? we could retry on any RTE, thus additionally covering `container.start()` too.

File: plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java [hunk 5]
```diff
@@ -13,43 +13,78 @@
...
+        container.withCopyFileToContainer(MountableFile.forClasspathResource("init.sql"), "/docker-entrypoint-initdb.d/init.sql");
 
-        withCopyFileToContainer(MountableFile.forClasspathResource("init.sql"), "/docker-entrypoint-initdb.d/init.sql");
+        container.start();
+        try {
+            setUpDatabase(container);
+        }
+        catch (Exception e) {
+            container.stop();
+            closeAllSuppress(e);
```
Comment (findepi) [inline plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java:77]: `closeAllSuppress(e)` is no-op

did you mean `closeAllSuppresse(e, container::stop)` ?

**Review by findepi — COMMENTED** [review]
lgtm

File: plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java (hunk 4 above)
Comment (ebyhr) [reply plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java]: Sorry, I was misunderstanding failsafe behavior. Updated.

**Review by hashhar — APPROVED** [review]
