### PR TITLE
Restore skip archive handler in Iceberg Glue catalog

### LINKED ISSUE #16561: Fix broken handling for `iceberg.glue.skip-archive` config property
```
Error:  io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueCatalogSkipArchive.testNotRemoveExistingArchive  Time elapsed: 3.173 s  <<< FAILURE!
java.lang.AssertionError: 

Expected size: 2 but was: 3 in:
[{Table: {Name: test_remove_archive84pd6n6xiz,DatabaseName: test_iceberg_skip_archive_nyjh64rhi7,CreateTime: Wed Mar 15 01:25:31 CST 2023,UpdateTime: Wed Mar 15 01:25:34 CST 2023,Retention: 0,TableType: EXTERNAL_TABLE,Parameters: {previous_metadata_location=/tmp/test_iceberg7598293935899680638/test_iceberg_skip_archive_nyjh64rhi7.db/test_remove_archive84pd6n6xiz-a90dcd23adeb4259838d2cddd0af9897/metadata/00000-0559c067-b253-4aaf-b39e-35f3a90a8313.metadata.json, metadata_location=/tmp/test_iceberg7598293935899680638/test_iceberg_skip_archive_nyjh64rhi7.db/test_remove_archive84pd6n6xiz-a90dcd23adeb4259838d2cddd0af9897/metadata/00001-a6dc2072-074e-4f29-a430-f5e70547233e.metadata.json, table_type=ICEBERG},CreatedBy: arn:aws:iam::894365193301:user/Trino-CI,IsRegisteredWithLakeFormation: false,CatalogId: 894365193301,VersionId: 2},VersionId: 2},
    {Table: {Name: test_remove_archive84pd6n6xiz,DatabaseName: test_iceberg_skip_archive_nyjh64rhi7,CreateTime: Wed Mar 15 01:25:31 CST 2023,UpdateTime: Wed Mar 15 01:25:32 CST 2023,Retention: 0,TableType: EXTERNAL_TABLE,Parameters: {metadata_location=/tmp/test_iceberg7598293935899680638/test_iceberg_skip_archive_nyjh64rhi7.db/test_remove_archive84pd6n6xiz-a90dcd23adeb4259838d2cddd0af9897/metadata/00000-0559c067-b253-4aaf-b39e-35f3a90a8313.metadata.json, table_type=ICEBERG},CreatedBy: arn:aws:iam::894365193301:user/Trino-CI,IsRegisteredWithLakeFormation: false,CatalogId: 894365193301,VersionId: 1},VersionId: 1},
    {Table: {Name: test_remove_archive84pd6n6xiz,DatabaseName: test_iceberg_skip_archive_nyjh64rhi7,Owner: user,CreateTime: Wed Mar 15 01:25:31 CST 2023,UpdateTime: Wed Mar 15 01:25:31 CST 2023,Retention: 0,TableType: EXTERNAL_TABLE,Parameters: {metadata_location=/tmp/test_iceberg7598293935899680638/test_iceberg_skip_archive_nyjh64rhi7.db/test_remove_archive84pd6n6xiz-a90dcd23adeb4259838d2cddd0af9897/metadata/00000-0559c067-b253-4aaf-b39e-35f3a90a8313.metadata.json, table_type=ICEBERG},CreatedBy: arn:aws:iam::894365193301:user/Trino-CI,IsRegisteredWithLakeFormation: false,CatalogId: 894365193301,VersionId: 0},VersionId: 0}]
	at io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueCatalogSkipArchive.testNotRemoveExistingArchive(TestIcebergGlueCatalogSkipArchive.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Error:  io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueCatalogSkipArchive.testSkipArchive  Time elapsed: 2.485 s  <<< FAILURE!
java.lang.AssertionError: 

Expected size: 1 but was: 2 in:
[{Table: {Name: test_skip_archive49ccernstg,DatabaseName: test_iceberg_skip_archive_nyjh64rhi7,CreateTime: Wed Mar 15 01:25:35 CST 2023,UpdateTime: Wed Mar 15 01:25:36 CST 2023,Retention: 0,TableType: EXTERNAL_TABLE,Parameters: {previous_metadata_location=/tmp/test_iceberg7598293935899680638/test_iceberg_skip_archive_nyjh64rhi7.db/test_skip_archive49ccernstg-125f0e7c6506413e8ec5effabb409e0c/metadata/00000-81b6dabb-7072-4d09-87cb-ea9b71c03fb0.metadata.json, metadata_location=/tmp/test_iceberg7598293935899680638/test_iceberg_skip_archive_nyjh64rhi7.db/test_skip_archive49ccernstg-125f0e7c6506413e8ec5effabb409e0c/metadata/00001-23249017-cd92-4353-8277-2112db57c7af.metadata.json, table_type=ICEBERG},CreatedBy: arn:aws:iam::894365193301:user/Trino-CI,IsRegisteredWithLakeFormation: false,CatalogId: 894365193301,VersionId: 1},VersionId: 1},
    {Table: {Name: test_skip_archive49ccernstg,DatabaseName: test_iceberg_skip_archive_nyjh64rhi7,Owner: user,CreateTime: Wed Mar 15 01:25:35 CST 2023,UpdateTime: Wed Mar 15 01:25:35 CST 2023,Retention: 0,TableType: EXTERNAL_TABLE,Parameters: {metadata_location=/tmp/test_iceberg7598293935899680638/test_iceberg_skip_archive_nyjh64rhi7.db/test_skip_archive49ccernstg-125f0e7c6506413e8ec5effabb409e0c/metadata/00000-81b6dabb-7072-4d09-87cb-ea9b71c03fb0.metadata.json, table_type=ICEBERG},CreatedBy: arn:aws:iam::894365193301:user/Trino-CI,IsRegisteredWithLakeFormation: false,CatalogId: 894365193301,VersionId: 0},VersionId: 0}]
	at io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueCatalogSkipArchive.testSkipArchive(TestIcebergGlueCatalogSkipArchive.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

https://github.com/trinodb/trino/actions/runs/4423139411/jobs/7756034818

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #16561

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/IcebergGlueCatalogModule.java [hunk 1]
```diff
@@ -46,7 +47,8 @@
     protected void setup(Binder binder)
     {
         configBinder(binder).bindConfig(GlueHiveMetastoreConfig.class);
-        configBinder(binder).bindConfig(IcebergGlueCatalogConfig.class);
+        IcebergGlueCatalogConfig config = buildConfigObject(IcebergGlueCatalogConfig.class);
```
Comment (electrum) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/IcebergGlueCatalogModule.java:50]: `buildConfigObject()` is intended for conditional configuration of the injector. In this case, we don't need it at binding time, so it's cleaner to use a provider method, just like any other object that we need manually construct based on injected things:
```java
@Provides
@Singleton
@ForGlueHiveMetastore
public static RequestHandler2 createRequestHandler(IcebergGlueCatalogConfig config)
{
    return new SkipArchiveRequestHandler(config.isSkipArchive());
}
```
While using `buildConfigObject()` works fine, it feels like a "trick" or "cheat" that doesn't generalize to other situations. If we needed anything else from the injector to construct the instance, it wouldn't work.

**Review by electrum — APPROVED** [review]
