### PR TITLE
Fix the explain (TYPE IO) Exception when table is hive partition tabl…

### LINKED ISSUE #10398: Explain (TYPE IO)  will throw Exception when table is hive partition table which is empty
common_20211203001_raw,common_20210902002_raw are hive partition table,but common_20211203001_raw is empty.
image
image
this logical is also  different
image

### PR DESCRIPTION
**Pull request by albericgenius**
## Description
Fix the explain (TYPE IO) Exception when table is hive partition table which is empty

> Is this change a fix, improvement, new feature, refactoring, or other?
Yes, [a bug fix](https://github.com/trinodb/trino/issues/10398)
> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
This a change for HIVE connector
> How would you describe this change to a non-technical end user or system administrator?
Fix the explain (TYPE IO) Exception when table is hive partition table which is empty
## Related issues, pull requests, and links
https://github.com/trinodb/trino/issues/10398

## Documentation

(+) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

(+) No release notes entries required.
( ) Release notes entries required with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`10398`)
```

### CODE REVIEW

**Comment by findinpath** [comment]
Please do follow the guideline for the Git commits

https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages

Make the git commit message header much smaller, wrap the message to 70-80 chars, and concentrate on make it more descriptive for the other fellows working on your changes.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java [hunk 1]
```diff
@@ -2926,9 +2926,12 @@ public ConnectorTableHandle makeCompatiblePartitioning(ConnectorSession session,
     @VisibleForTesting
     static TupleDomain<ColumnHandle> createPredicate(List<ColumnHandle> partitionColumns, List<HivePartition> partitions)
     {
-        if (partitions.isEmpty()) {
+        if (partitionColumns.isEmpty() && partitions.isEmpty()) {
```
Comment (findinpath) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java:2929]:
```suggestion
        if (partitions.isEmpty()){
            return partitionColumns.isEmpty() ? TupleDomain.none() : TupleDomain.all();
        }
```

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java [hunk 2]
```diff
@@ -2926,9 +2926,12 @@ public ConnectorTableHandle makeCompatiblePartitioning(ConnectorSession session,
...
             return TupleDomain.none();
         }
+        else if (!partitionColumns.isEmpty() && partitions.isEmpty()) {
```
Comment (findinpath) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java:2932]: add a test to showcase the problem you are fixing.

**Comment by albericgenius** [comment]
> 

+ Thanks for sharing, it is really helpful
+ Updated the commit message header to smaller.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java (hunk 2 above)
Comment (albericgenius) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java:2936]: + add 3 test cases

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java (hunk 1 above)
Comment (findinpath) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java:2933]: @albericgenius  `partitions.isEmpty()` check is common in both `if` statements.
Please consider applying the suggested change.

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadata.java [hunk 3]
```diff
@@ -73,6 +74,25 @@ public void testCreatePredicate()
                 false));
     }
 
+    @Test
+    public void testCreatePredicateWithEmptyPartition()
+    {
+        ImmutableList.Builder<HivePartition> partitions = ImmutableList.builder();
+        Domain domain = createPredicate(ImmutableList.of(TEST_COLUMN_HANDLE), partitions.build())
```
Comment (findinpath) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadata.java:81]: Use `ImmutableList.of()` instead of defining extra field `partitions` for keeping the code smaller.

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java [hunk 4]
```diff
@@ -1131,6 +1131,28 @@ public void testIoExplain()
         assertUpdate("DROP TABLE test_io_explain");
     }
 
+    @Test
+    public void testIoExplainWithEmptyPartition()
+    {
+        // Test IO explain with small number of discrete components.
+        computeActual("CREATE TABLE test_io_explain WITH (partitioned_by = ARRAY['orderkey', 'processing']) AS SELECT custkey, orderkey, orderstatus = 'P' processing FROM orders WHERE 1 != 1");
```
Comment (findinpath) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java:1138]: nit `WHERE 1 != 1` -> `WHERE false`

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadata.java [hunk 5]
```diff
@@ -73,6 +74,25 @@ public void testCreatePredicate()
...
+                .getDomains().orElseThrow().get(TEST_COLUMN_HANDLE);
+        assertEquals(domain, Domain.all(VARCHAR));
+    }
+
+    @Test
+    public void testCreatePredicateWithEmptyPartitionAndEmptyColumn()
+    {
+        ImmutableList.Builder<HivePartition> partitions = ImmutableList.builder();
+        ImmutableList.Builder<ColumnHandle> columnHandle = ImmutableList.builder();
+        Domain domain = createPredicate(columnHandle.build(), partitions.build())
```
Comment (findinpath) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadata.java:91]: Replace with:
`createPredicate(ImmutableList.of(), ImmutableList.of()).getDomains().orElseThrow().get(TEST_COLUMN_HANDLE)`

**Review by findinpath — APPROVED** [review]

**Comment by findinpath** [comment]
Please add in the description:

> Fixes #10398

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java (hunk 1 above)
Comment (albericgenius) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java]: Thanks, I can see the improvement from your comments.

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadata.java (hunk 3 above)
Comment (albericgenius) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadata.java]: fixed

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java (hunk 4 above)
Comment (albericgenius) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java]: fixed

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadata.java (hunk 5 above)
Comment (albericgenius) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadata.java]: fixed

**Comment by findinpath** [comment]
Please be more brief with implementation details in the commit message.
Think of explaining what you are doing and not every implementation detail how you did it.

**Comment by albericgenius** [comment]
> Please add in the description:
> 
> > Fixes #10398

Thanks for notes, I added :)

**Comment by albericgenius** [comment]
@findepi and @findinpath 
This is my first approved commit, I am not sure the process.
do I need the second approval here, or you can help me to merge into master branch?
Thanks
Alberic

**Comment by findinpath** [comment]
@albericgenius generally it may take a while (a few hours/ a few days) until a maintainer merges the commit.
In any case feel free to take a stab on another open issue in the meanwhile.

Good job!


@bitsondatadev  we should probably document the PR process on https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md to avoid confusion.

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java [hunk 6]
```diff
@@ -1131,6 +1131,28 @@ public void testIoExplain()
         assertUpdate("DROP TABLE test_io_explain");
     }
 
+    @Test
+    public void testIoExplainWithEmptyPartition()
+    {
+        // Test IO explain with small number of discrete components.
+        computeActual("CREATE TABLE test_io_explain WITH (partitioned_by = ARRAY['orderkey', 'processing']) AS SELECT custkey, orderkey, orderstatus = 'P' processing FROM orders WHERE false");
```
[the remark this answers is not in the document]
Comment (albericgenius) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java]: fixed.

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java [hunk 7]
```diff
@@ -1131,6 +1131,28 @@ public void testIoExplain()
         assertUpdate("DROP TABLE test_io_explain");
     }
 
+    @Test
+    public void testIoExplainWithEmptyPartition()
+    {
+        // Test IO explain with small number of discrete components.
```
[the remark this answers is not in the document]
Comment (albericgenius) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java]: updated the comment.

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java [hunk 8]
```diff
@@ -1131,6 +1131,28 @@ public void testIoExplain()
         assertUpdate("DROP TABLE test_io_explain");
     }
 
+    @Test
+    public void testIoExplainWithEmptyPartition()
```
[the remark this answers is not in the document]
Comment (albericgenius) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java]: update the method name, it is more clear

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java [hunk 9]
```diff
@@ -2925,7 +2925,7 @@ public ConnectorTableHandle makeCompatiblePartitioning(ConnectorSession session,
     static TupleDomain<ColumnHandle> createPredicate(List<ColumnHandle> partitionColumns, List<HivePartition> partitions)
     {
         if (partitions.isEmpty()) {
-            return TupleDomain.none();
+            return partitionColumns.isEmpty() ? TupleDomain.none() : TupleDomain.all();
```
[the remark this answers is not in the document]
Comment (albericgenius) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java:2928]: + originally we return TupleDomain.none() when partitions.isEmpty()
+ but in the case of no data of the PartitionedTable, we will throw IllegalArgumentException in `IoPlanPrinter.parseConstraints`. because the constraint is none.
+ for no data of the PartitionedTable case, the partitions is empty, and partitionColumns is not empty

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java [hunk 10]
```diff
@@ -1131,6 +1131,28 @@ public void testIoExplain()
...
+                new IoPlan(
+                        ImmutableSet.of(
+                                new TableColumnInfo(
+                                        new CatalogSchemaTableName(catalog, "tpch", "test_io_explain"),
+                                        ImmutableSet.of(),
+                                        estimate)),
+                        Optional.empty(),
+                        estimate));
+
+        assertUpdate("DROP TABLE test_io_explain");
```
Comment (findepi) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java:1153]: test_io_explain -> test_io_explain_with_empty_partitioned_table

using same table name as in the other test will make tests fail when run concurrently

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (findepi) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java:2928]: thanks for the explanation

> * but in the case of no data of the PartitionedTable, we will throw IllegalArgumentException in `IoPlanPrinter.parseConstraints`. because the constraint is none.

does it mean we should fix that method instead?

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java [hunk 11]
```diff
@@ -1131,6 +1131,28 @@ public void testIoExplain()
         assertUpdate("DROP TABLE test_io_explain");
     }
 
+    @Test
+    public void testIoExplainWithEmptyPartitionedTable()
+    {
+        // Test IO explain a partitioned table with no data.
+        computeActual("CREATE TABLE test_io_explain WITH (partitioned_by = ARRAY['orderkey']) AS SELECT custkey, orderkey FROM orders WITH NO DATA");
```
Comment (findepi) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java:1138]:
```suggestion
        assertUpdate("CREATE TABLE test_io_explain WITH (partitioned_by = ARRAY['orderkey']) AS SELECT custkey, orderkey FROM orders WITH NO DATA", 0);
```

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (findepi) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java]: added a suggestion for this (https://github.com/trinodb/trino/pull/12349/files#r876895580)

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (findepi) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java]: thanks

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java (hunk 11 above)
Comment (albericgenius) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java]: got it, Thanks

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java (hunk 10 above)
Comment (albericgenius) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java:1153]: https://github.com/trinodb/trino/pull/12349#discussion_r876894886
+ IoPlanPrinter.parseConstraints will check the constraint is none or not. The logic is correct.
+ I think if a partitioned table do not have any data, we should return TupleDomain.all() as constraint. there is only one case that partitions is empty and partitionColumns is not because of no data. 
+ Only partitionColumns and partitions are empty, we should return TupleDomain.none().
+ What is your thought?

Comment (albericgenius) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java]: + This implement will not take effect  "no rows match the filter". because there is no data(partitions is empty and partitionColumns is not empty), even we return TupleDomain.all(), there is no data match the filter, the result is same.
+ I agree with you, this is better to fix inside IoPlanPrinter.parseConstraints, but i still do not know how to get partitions informations in plan process. i will continue to think about it tomorrow. if you have free time, please help to give me some suggestion. 

Thanks for your time
Alberic

Comment (findepi) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java]: > even we return TupleDomain.all(), there is no data match the filter, the result is same.

`io.trino.spi.connector.ConnectorMetadata#getTableProperties`'s `io.trino.spi.connector.ConnectorTableProperties#predicate` is used to inform the planner and allow deriving filters for other tables.

for example, a query
```sql
SELECT * FROM some_table JOIN empty_partitioned_table ON ...
```

should be reduced to `SELECT .. WHERE false` because the planner realizes `empty_partitioned_table` has no rows (`TupleDomain.none()`).

**Review by findepi — CHANGES_REQUESTED** [review]
Per https://github.com/trinodb/trino/pull/12349/files#r876894886

**Review by findinpath — APPROVED** [review]

File: core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java [hunk 12]
```diff
@@ -717,7 +716,9 @@ private EstimatedStatsAndCost getEstimatedStatsAndCost(TableScanNode node)
 
         private Set<ColumnConstraint> parseConstraints(TableHandle tableHandle, TupleDomain<ColumnHandle> constraint)
         {
-            checkArgument(!constraint.isNone());
+            if (constraint.isNone()) {
+                return ImmutableSet.of();
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java:720]: That's exactly what we would return if predicate is `all`, so it's probably not the right return value for the `none` case.

Comment (findepi) [reply core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java:720]: `IoPlan.TableColumnInfo` cannot currently represent a table with NONE constraint.

In general, such table should be eliminated from the query plan, this happens e.g. here
https://github.com/trinodb/trino/blob/14b901dc533eb28a6898650642b133422a1c2c5a/core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java#L255-L258

We could fix the optimizer so that it happens as well in the `SELECT * FROM empty_partitioned_table` case and we probably should. However, this wouldn't eliminate the need to fix `EXPLAIN (TYPE IO)` from failing in such case, since it's generally a possible situation. That's why we deal with it also on page source level instead of failing there
https://github.com/trinodb/trino/blob/ad8663794f0e6a63cfee6b420f86a522fafc1f63/core/trino-main/src/main/java/io/trino/split/PageSourceManager.java#L63

So, back to our problem. We need to make `IoPlan.TableColumnInfo` be able to represent table scan without data, with none constraint.
I would suggest replacing `Set<ColumnConstraint> columnConstraints` field with
```
class Constraint {
  boolean isNone;
  Set<ColumnConstraint> columnConstraints;
}
```

cc @martint @sopel39 @kokosing @losipiuk @JamesRTaylor

**Comment by albericgenius** [comment]
> > @albericgenius albericgenius force-pushed the mainline branch from 9a4b2d1 to [26ef697](https://github.com/trinodb/trino/commit/26ef697107add3b991a11775fe66764dfbce5837) 17 hours ago
> 
> the diff is https://github.com/trinodb/trino/compare/9a4b2d177ee4d2ebd0c992c8385bc00fbab7c5ac..26ef697107add3b991a11775fe66764dfbce5837
> 
> @albericgenius please don't rebase, unless necessary. it makes reviewing harder. Github should be able to show a diff that of changes that matter, but it's apparently not implemented yet.

**Comment by albericgenius** [comment]
@findepi Thanks for your help and time.
I try to follow your idea to add a Rule: RemoveEmptyTableScan. if the table is empty and partition is empty, i will replace the scan table node with a value node. Then the IoPlanPrinter issue is resolved.

I am not sure my implement way is math your idea or not? now it affect some JDBC test cases because of this new Rule. 

- If it is matched, i will fix the JDBC test cases. 
- Otherwise please help for any comment. I will response as soon as possible.

**Comment by findepi** [comment]
@albericgenius 
in https://github.com/trinodb/trino/pull/12349#discussion_r879426360 i indicated we need to fix the IO plan printer

> So, back to our problem. We need to make IoPlan.TableColumnInfo be able to represent table scan without data, with none constraint.
I would suggest replacing Set<ColumnConstraint> columnConstraints field with ...

However, i also see that we could choose NOT to fix the plan printer, and consider a plan with redundant TableScan left as "bogus" or "invalid". It's surely undesirable. 

@martint thoughts?

**Comment by martint** [comment]
> However, i also see that we could choose NOT to fix the plan printer, and consider a plan with redundant TableScan left as "bogus" or "invalid". It's surely undesirable.

A TableScan that produces no data is a perfectly valid plan, so that should be fixed in the plan printer. It might be undesirable from a performance perspective, but that's just an optimization.

File: core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java [hunk 13]
```diff
@@ -248,28 +248,85 @@ public boolean equals(Object obj)
...
                         .add("estimate", estimate)
                         .toString();
             }
         }
     }
 
+    public static class Constraint
+    {
+        private final boolean isNone;
+
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java:276]:
```suggestion
```

File: core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java [hunk 14]
```diff
@@ -248,28 +248,85 @@ public boolean equals(Object obj)
...
+        private final Set<ColumnConstraint> columnConstraints;
+
+        @JsonCreator
+        public Constraint(
+                @JsonProperty("none") boolean isNone,
+                @JsonProperty("columnConstraints") Set<ColumnConstraint> columnConstraints)
+        {
+            this.isNone = isNone;
+            this.columnConstraints = columnConstraints;
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java:285]: make a defensive copy to ensure that Constraint is immutable

```suggestion
            this.columnConstraints = ImmutableSet.copyIf(requireNonNull(columnConstraints, "columnConstraints is null"));
```

File: core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java [hunk 15]
```diff
@@ -697,13 +754,14 @@ private void addInputTableConstraints(TupleDomain<ColumnHandle> filterDomain, Ta
             TableMetadata tableMetadata = plannerContext.getMetadata().getTableMetadata(session, table);
             TupleDomain<ColumnHandle> predicateDomain = plannerContext.getMetadata().getTableProperties(session, table).getPredicate();
             EstimatedStatsAndCost estimatedStatsAndCost = getEstimatedStatsAndCost(tableScan);
+            boolean withoutData = estimatedStatsAndCost.getOutputRowCount() == 0d ? true : false;
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java:757]: The logic here should not depend on stats.
Stats are estimates, can be inaccurate and off.

File: core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java [hunk 16]
```diff
@@ -722,18 +780,20 @@ private EstimatedStatsAndCost getEstimatedStatsAndCost(TableScanNode node)
             return estimatedStatsAndCost;
         }
 
-        private Set<ColumnConstraint> parseConstraints(TableHandle tableHandle, TupleDomain<ColumnHandle> constraint)
+        private Constraint parseConstraint(TableHandle tableHandle, TupleDomain<ColumnHandle> constraint, boolean withoutData)
         {
-            checkArgument(!constraint.isNone());
+            checkArgument(!constraint.isNone() || withoutData);
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java:785]: i think we need to replace this check with an if
```java
if (constraint.isNone()) {
  return new Constraint(true, ImmutableSet.of());
}
```

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java [hunk 17]
```diff
@@ -1043,13 +1044,15 @@ public void testIoExplain()
...
+        boolean withoutData = estimate.getOutputRowCount() == 0d ? true : false;
         MaterializedResult result = computeActual("EXPLAIN (TYPE IO, FORMAT JSON) INSERT INTO test_io_explain SELECT custkey, orderkey, processing FROM test_io_explain WHERE custkey <= 10");
         assertEquals(
                 getIoPlanCodec().fromJson((String) getOnlyElement(result.getOnlyColumnAsSet())),
                 new IoPlan(
                         ImmutableSet.of(
                                 new TableColumnInfo(
                                         new CatalogSchemaTableName(catalog, "tpch", "test_io_explain"),
+                                        new IoPlanPrinter.Constraint(withoutData,
                                         ImmutableSet.of(
```
Comment (findepi) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java:1056]: the indentation here is off and will change as soon as someone invokes reformatting

```suggestion
                                        new IoPlanPrinter.Constraint(withoutData, ImmutableSet.of(
```

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java [hunk 18]
```diff
@@ -1043,13 +1044,15 @@ public void testIoExplain()
         computeActual("CREATE TABLE test_io_explain WITH (partitioned_by = ARRAY['orderkey', 'processing']) AS SELECT custkey, orderkey, orderstatus = 'P' processing FROM orders WHERE orderkey < 3");
 
         EstimatedStatsAndCost estimate = new EstimatedStatsAndCost(2.0, 40.0, 40.0, 0.0, 0.0);
+        boolean withoutData = estimate.getOutputRowCount() == 0d ? true : false;
```
Comment (findepi) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java:1047]: We now the expected result (constraint here shouldn't be none)
we don't need a variable and conditional initialization for that

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java [hunk 19]
```diff
@@ -1091,64 +1094,70 @@ public void testIoExplain()
         computeActual("CREATE TABLE test_io_explain WITH (partitioned_by = ARRAY['orderkey']) AS SELECT custkey, orderkey FROM orders WHERE orderkey < 200");
 
         estimate = new EstimatedStatsAndCost(55.0, 990.0, 990.0, 0.0, 0.0);
+        withoutData = estimate.getOutputRowCount() == 0d ? true : false;
```
Comment (findepi) [inline plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java:1097]: as above -- replace with constant and inline

**Review by findepi — CHANGES_REQUESTED** [review]

**Comment by findepi** [comment]
I applied some cosmetic changes (to the code & commit message) myself. Will merge once the build passes.

Thank you for your contribution!

**Review by findepi — APPROVED** [review]

**Comment by albericgenius** [comment]
> I applied some cosmetic changes (to the code & commit message) myself. Will merge once the build passes.
> 
> Thank you for your contribution!

Thanks for your time and your coaching.
