### PR TITLE
JDBC Client: fix a bug where TrinoResultSet cannot be properly closed

### LINKED ISSUE #7374: In Trino-JDBC calling TrinoResultSet.cancel can't really close completablaFuture thread
When using Trino-JDBC, the implementation of `ResultSet.close` in Trino `ResultSet` will call the cancel method in AsyncIterator Class to cancel the current thread. Since the thread of AsyncIterator is a CompletableFuture implementation, it will not throw an Interupption Exception，even if the thread is in the wait state.
If `TrinoResultSet.AsyncIterator.rowQueue` is full and the user closes TrinoJDBC connection/statement/resultSet at the same time, the current thread will be in the wait state and will never be cancelled, and the rawQueue memory held by the current thread will not be released. 
When there are a large number of ResultSet requests that have not been fetched, and ResultSet.close is called, thread and memory leaks will result.

```java
private static class AsyncIterator<T>
            extends AbstractIterator<T>
    {
        private static final int MAX_QUEUED_ROWS = 50_000;
        private static final ExecutorService executorService = newCachedThreadPool(daemonThreadsNamed("Trino JDBC worker-%d"));

        private final StatementClient client;
        private final BlockingQueue<T> rowQueue = new ArrayBlockingQueue<>(MAX_QUEUED_ROWS);
        // Semaphore to indicate that some data is ready.
        // Each permit represents a row of data (or that the underlying iterator is exhausted).
        private final Semaphore semaphore = new Semaphore(0);
        private final CompletableFuture<Void> future;

        public AsyncIterator(Iterator<T> dataIterator, StatementClient client)
        {
            requireNonNull(dataIterator, "dataIterator is null");
            this.client = client;
            this.future = CompletableFuture.runAsync(() -> {
                try {
                    while (dataIterator.hasNext()) {
                        rowQueue.put(dataIterator.next());
                        semaphore.release();
                    }
                }
                catch (InterruptedException e) {
                    interrupt(e);
                }
                finally {
                    semaphore.release();
                }
            }, executorService);
        }

        public void cancel()
        {
            future.cancel(true);
        }

        public void interrupt(InterruptedException e)
        {
            client.close();
            Thread.currentThread().interrupt();
            throw new RuntimeException(new SQLException("ResultSet thread was interrupted", e));
        }
```

I replace the implementation of CompletableFuture with FutureTask, can actually cancel the thread and avoid the leakage of memory and thread.

```java
        public AsyncIterator(Iterator<T> dataIterator, StatementClient client)
        {
            requireNonNull(dataIterator, "dataIterator is null");
            this.client = client;
//            this.future = CompletableFuture.runAsync(() -> {
              this.future = executorService.submit(new Runnable() {
                 @Override
                 public void run()
                 {
                     try {
                         while (dataIterator.hasNext()) {
                             rowQueue.put(dataIterator.next());
                             semaphore.release();
                         }
                     } catch (InterruptedException e) {
                         interrupt(e);
                     } finally {
                         semaphore.release();
                     }
                 }
             });
        }

```

### PR DESCRIPTION
**Pull request by xiacongling**
ResultSet cannot be properly closed since the inner Thread cannot be interrupted and stop data row iteration. That will lead to thread and memory leaks on the client side. This patch uses FutureTask, which is created by ThreadPoolExecutor, instead of CompletableFuture to make sure InterruptedException can be raised as expected. And for the case that interruption is not properly handled by the underlying StatementClient, a status check is added to the loop condition so that loop can terminate and thread can be released.

## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

a fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

JDBC client

> How would you describe this change to a non-technical end user or system administrator?

fix a bug where `TrinoResultSet` cannot be properly closed which will lead to thread and memory leaks on the client side.

## Related issues, pull requests, and links

* Fixes #7374 
* Fixes https://github.com/trinodb/trino/issues/14176
* Related to https://github.com/trinodb/trino/pull/7404

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(x) Release notes entries required with the following suggested text:

```markdown
# JDBC Client
* Fix a bug where TrinoResultSet cannot be properly closed. ({issue}`7374`)
```

### CODE REVIEW

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 1]
```diff
@@ -156,13 +158,13 @@ private static <T> Iterator<T> flatten(Iterator<Iterable<T>> iterator, long maxR
...
         // Each permit represents a row of data (or that the underlying iterator is exhausted).
         private final Semaphore semaphore = new Semaphore(0);
-        private final CompletableFuture<Void> future;
+        private final Future<?> future;
 
         public AsyncIterator(Iterator<T> dataIterator, StatementClient client)
         {
             requireNonNull(dataIterator, "dataIterator is null");
             this.client = client;
-            this.future = CompletableFuture.runAsync(() -> {
```
Comment (lhofhansl) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:165]: Looks good.
Now I wonder why we have used a CompletableFuture in the first place.

File: client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java [hunk 2]
```diff
@@ -0,0 +1,223 @@
...
+            }
+
+            @Override
+            public Iterable<List<Object>> next()
+            {
+                return ImmutableList.of((ImmutableList.of(new Object())));
+            }
+        });
+
+        MILLISECONDS.sleep(100);
```
Comment (lhofhansl) [inline client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java:58]: Tests with waits in them make me cringe.
A slow machine/VM can make it fail.

Comment (martint) [reply client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java:58]: Indeed. The test should get the code to the expected synchronization points by means of CountdownLatch/Semaphore/CyclicBarrier/etc.

Comment (xiacongling) [reply client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java]: Updated. A CountDownLatch is used to notify the main thread instead of the indeterminate Thread.sleep().

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 3]
```diff
@@ -156,13 +158,13 @@ private static <T> Iterator<T> flatten(Iterator<Iterable<T>> iterator, long maxR
...
+            this.future = executorService.submit(() -> {
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:167]: > This patch uses FutureTask, which
is created by ThreadPoolExecutor, instead of CompletableFuture to
make sure InterruptedException can be raised as expected.

I think relying on interrupts is inherently unreliable.
Should we also have explicit atomic/violatile boolean closed flag to ensure iteration is stopped even if some piece of code (our or lib) mishandles interruption?

Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:167]: Thanks for the reply, @findepi . 

Using `Thread.interrupt` is a good choice, I think, because it can stop the work immediately when thread is waiting or sleeping. When thread is running, the InterruptedException will not be raised (I was wrong in the pr description), so we need to check the thread's `interrupted` status (it can act as the flag as you've mentioned) to make sure we can exit the iteration. I did not do the check here, so I will add it to make things right.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 4]
```diff
@@ -144,27 +145,38 @@ private static <T> Iterator<T> flatten(Iterator<Iterable<T>> iterator, long maxR
...
         private final StatementClient client;
-        private final BlockingQueue<T> rowQueue = new ArrayBlockingQueue<>(MAX_QUEUED_ROWS);
+        private final BlockingQueue<T> rowQueue;
         // Semaphore to indicate that some data is ready.
         // Each permit represents a row of data (or that the underlying iterator is exhausted).
         private final Semaphore semaphore = new Semaphore(0);
-        private final CompletableFuture<Void> future;
+        private final Future<?> future;
+        private volatile boolean cancelled;
+        private volatile boolean finished;
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:163]: What's the difference between finished and cancelled? why do we need two fields?

Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:163]: - `cancelled` is used for process control. When `cancel()` is invoked, `cancelled` is set to `true` so that the iteration can be terminated
- and `finished` is a state used only for test to check whether the underlying work is done or terminated. 
 
The issue we want to solve here is that threads may leak even though we cancel or close the ResultSet. We should make sure that threads can finally complete the task in the `run` and should not get blocked in the middle.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 3 above)
Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:177]: Flag added, but still needs some improvement.

There are 2 test cases:
- One for queue is full and the thread will be blocked on `rowQueue.put`. Interruptions are useful to terminate the waiting. In this case, flag check is not working.
- One to simulate underlying implemetation mishandles interruptions. In this case, flag check can terminate the iteration.

It cannot solve the problem when situations are combined. For example, an interruption occurred (when cancel being invoked) during `dataIterator.hasNext()` or `dataIterator.next()` but has been mis-handled, and then the thread blocked on `rowQueue.put` for a full queue.

Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:175]: Hi, @findepi. Things becomes complicated.

When we distruct the underlying implementation of interruption handling, there are cases we are not able to abort the running. For example, If the inner implemetation swalloweds the InterruptedException and still wait for more result data, the thread will not be released unless more result data generated. The flag check has nothing to do with the problem. 
Further more, after result data being generated, thread may be blocked at `rowQueue.put()` for a full queue. In this case, the thread will never be released. Addition code change, like using continuous `rowQueue.offer()`, is needed to avoid the long wait. 
Another problem is that when thread been terminated by a failure flag check, we cannot distinguish whether it is aborted or correctly finished. Some code should be added to make the distinction.

Here the issues is that threads may leak due to not be interrupted. The key problem is that `Thread.interrupt()` is never invoked during a `Future` cancellation. It is not a problem for interruption mishandle (at least for now) since the actual inner iteration implementation does do the right thing (maybe we can add some guard test cases to garantee). I think we can do a quick fix for this issue and to discuss about a new and better implemenation of TrinoResultSet in another thread.

For the reason above, I decide to revert the changes of add flag check and make the code change easy to understand.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 5]
```diff
@@ -144,27 +145,36 @@ private static <T> Iterator<T> flatten(Iterator<Iterable<T>> iterator, long maxR
...
-        private final CompletableFuture<Void> future;
+        private final Future<?> future;
+        private volatile boolean finished;
 
         public AsyncIterator(Iterator<T> dataIterator, StatementClient client)
+        {
+            this(dataIterator, client, Optional.empty());
+        }
+
+        AsyncIterator(Iterator<T> dataIterator, StatementClient client, Optional<BlockingQueue<T>> queue)
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:169]: Add `@VisibleForTesting` here.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 6]
```diff
@@ -144,27 +145,36 @@ private static <T> Iterator<T> flatten(Iterator<Iterable<T>> iterator, long maxR
...
         {
             requireNonNull(dataIterator, "dataIterator is null");
             this.client = client;
-            this.future = CompletableFuture.runAsync(() -> {
+            this.rowQueue = queue.orElseGet(() -> new ArrayBlockingQueue<>(MAX_QUEUED_ROWS));
+            this.finished = false;
+            this.future = executorService.submit(() -> {
                 try {
-                    while (dataIterator.hasNext()) {
+                    while (!Thread.currentThread().isInterrupted() && dataIterator.hasNext()) {
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:177]: `Thread.currentThread().isInterrupted()` is unreliable (interruption may be swallowed)
also, this clears interruption flag.

why not `while (!finished ..` ?

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 3 above)
Comment (findepi) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:175]: > Further more, after result data being generated, thread may be blocked at `rowQueue.put()` for a full queue. In this case, the thread will never be released. Addition code change, like using continuous `rowQueue.offer()`, is needed to avoid the long wait.

Why not drain (clear) the `rowQueue` upon cancellation?

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 5 above)
Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:171]: done

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 3 above)
Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:178]: updated.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 7]
```diff
@@ -144,27 +145,39 @@ private static <T> Iterator<T> flatten(Iterator<Iterable<T>> iterator, long maxR
...
         private final StatementClient client;
-        private final BlockingQueue<T> rowQueue = new ArrayBlockingQueue<>(MAX_QUEUED_ROWS);
+        private final BlockingQueue<T> rowQueue;
         // Semaphore to indicate that some data is ready.
         // Each permit represents a row of data (or that the underlying iterator is exhausted).
         private final Semaphore semaphore = new Semaphore(0);
-        private final CompletableFuture<Void> future;
+        private final Future<?> future;
+        private volatile boolean cancelled;
+        private volatile boolean finished;
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:163]: is the `finished` field for testing only?
why not check whether future.isDone() instead, and not have this field?

Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:163]: Yes, the problem is that threads may leak in current implementation even though future is cancelled (`future.isDone() == true`), so I add this test to make sure thread goes to the end of its work.

File: client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java [hunk 8]
```diff
@@ -0,0 +1,262 @@
...
+                        @Override
+                        public Map<String, String> getAddedPreparedStatements()
+                        {
+                            return null;
+                        }
+
+                        @Override
+                        public Set<String> getDeallocatedPreparedStatements()
+                        {
+                            return null;
```
Comment (findepi) [inline client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java:232]: throw `UnsupportedOperationException` on any method that's not implemented

File: client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java [hunk 9]
```diff
@@ -0,0 +1,262 @@
...
+import java.util.Set;
+import java.util.concurrent.ArrayBlockingQueue;
+import java.util.concurrent.BlockingQueue;
+import java.util.concurrent.CountDownLatch;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.atomic.AtomicReference;
+
+import static org.testng.Assert.assertTrue;
+
+public class TestTrinoResultSet
```
Comment (findepi) [inline client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java:38]: We already have TestJdbcResultSet to test the ResultSet implementation

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 10]
```diff
@@ -239,15 +273,9 @@ protected Iterable<List<Object>> computeNext()
                 QueryStatusInfo results = client.currentStatusInfo();
                 progressCallback.accept(QueryStats.create(results.getId(), results.getStats()));
                 warningsManager.addWarnings(results.getWarnings());
-                Iterable<List<Object>> data = client.currentData().getData();
-
-                try {
-                    client.advance();
-                }
-                catch (RuntimeException e) {
-                    throw e;
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:248]: That's a good change, but unrelated to the other changes.
Can you move it to separate commit (same or separate PR)?

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 11]
```diff
@@ -174,22 +187,43 @@ public AsyncIterator(Iterator<T> dataIterator, StatementClient client)
...
-            client.close();
+            cleanup();
             Thread.currentThread().interrupt();
             throw new RuntimeException(new SQLException("ResultSet thread was interrupted", e));
         }
 
+        private void cleanup()
+        {
+            client.close();
+            rowQueue.clear();
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:212]: Add a comment why it matters

**Comment by findepi** [comment]
@electrum please take a look

File: client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java (hunk 8 above)
Comment (xiacongling) [reply client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java]: done

File: client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java (hunk 9 above)
Comment (xiacongling) [reply client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java:38]: Yes, I notice that. But TestJdbcResultSet is a integration test with test trino server set up. The test cases here are all unit tests. Is it better to keep them separate?

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 10 above)
Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java]: OK, reverted.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 11 above)
Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:215]: comment added.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 12]
```diff
@@ -174,22 +187,46 @@ public AsyncIterator(Iterator<T> dataIterator, StatementClient client)
...
+                    finished = true;
                 }
-            }, executorService);
+            });
         }
 
         public void cancel()
         {
             future.cancel(true);
+            cancelled = true;
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:198]: `cancelled = true;` should be done before sending interrupt (`future.cancel(true)`), so that we have the guarantee that the woken up thread sees the right value of the cancellation flag

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 13]
```diff
@@ -174,22 +187,46 @@ public AsyncIterator(Iterator<T> dataIterator, StatementClient client)
...
-            client.close();
+            cleanup();
             Thread.currentThread().interrupt();
             throw new RuntimeException(new SQLException("ResultSet thread was interrupted", e));
         }
 
+        private void cleanup()
+        {
+            // When thread interruption is mis-handled by underlying implementation of `client`, the thread which
+            // is working for `future` may be blocked by `rowQueue.put` (`rowQueue` is full) and will never finish
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:212]: I think being blocked could also happen without mis-handling of the interrupts, right?

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 14]
```diff
@@ -174,22 +187,46 @@ public AsyncIterator(Iterator<T> dataIterator, StatementClient client)
...
+            // its work. It is necessary to close `client` and drain `rowQueue` to avoid such leaks.
+            client.close();
+            rowQueue.clear();
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:215]: Does the order of these actions (client.close, draining) matter?

File: client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java (hunk 9 above)
Comment (findepi) [reply client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java:38]: Add a javadoc explaining what it is and also `@see` tag -- in both these tests.
 
like

```java
/**
 * A unit test for {@link TrinoResultSet}.
 * 
 * @see TestJdbcResultSet an integration test.
 */
```

File: client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java [hunk 15]
```diff
@@ -0,0 +1,268 @@
...
+                    @Override
+                    public Iterable<List<Object>> next()
+                    {
+                        thread.compareAndSet(null, Thread.currentThread());
+                        try {
+                            TimeUnit.MILLISECONDS.sleep(1000);
+                        }
+                        catch (InterruptedException e) {
+                            interruptedButSwallowedLatch.countDown();
+                            Thread.currentThread().interrupt();
```
Comment (findepi) [inline client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java:64]: if we're pretending to swallow interrupts (as indicated by interruptedButSwallowedLatch), we shouldn't re-interrupt the current thread, should we?

note: not doing `Thread.currentThread().interrupt()` requires a comment that it's intentional

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java [hunk 16]
```diff
@@ -174,22 +187,46 @@ public AsyncIterator(Iterator<T> dataIterator, StatementClient client)
...
+        }
+
+        @VisibleForTesting
+        Future<?> getFuture()
+        {
+            return future;
+        }
+
+        @VisibleForTesting
+        boolean isFinished()
```
Comment (findepi) [inline client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:225]: isFinished() -> isBackgroundThreadFinished

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 12 above)
Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:198]: It doesn't matter. Interruptions are more effiencient than loop check if interruptions are well handled. Because iteration may waiting for the result data to be produced.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 13 above)
Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:212]: Block happens, but will be interrupted if it is properly handled.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 14 above)
Comment (xiacongling) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:215]: It doesn't matter for most cases. I am just worried that `client` may fill `rowQueue` after it has been drained.

File: client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java (hunk 15 above)
Comment (xiacongling) [reply client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java]: removed

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 12 above)
Comment (findepi) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:198]: > . Interruptions are more effiencient than loop check if interruptions are well handled.

Yes

We want to have two mechanisms for the case where interruptions are not well handled.
In such cases, setting a flag first is important.

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 14 above)
Comment (findepi) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:215]: So it may matter. Let's document the reasoning as a code comment

File: client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java (hunk 12 above)
Comment (findepi) [reply client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoResultSet.java:197]: Applied myself

**Review by findepi — APPROVED** [review]

**Comment by Twilightuse** [comment]
> ResultSet cannot be properly closed since the inner Thread cannot be interrupted and stop data row iteration. That will lead to thread and memory leaks on the client side. This patch uses FutureTask, which is created by ThreadPoolExecutor, instead of CompletableFuture to make sure InterruptedException can be raised as expected. And for the case that interruption is not properly handled by the underlying StatementClient, a status check is added to the loop condition so that loop can terminate and thread can be released.
> 
> ## Description
> > Is this change a fix, improvement, new feature, refactoring, or other?
> 
> a fix
> 
> > Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
> 
> JDBC client
> 
> > How would you describe this change to a non-technical end user or system administrator?
> 
> fix a bug where `TrinoResultSet` cannot be properly closed which will lead to thread and memory leaks on the client side.
> 
> ## Related issues, pull requests, and links
> * Fixes [In Trino-JDBC calling TrinoResultSet.cancel can't really close completablaFuture thread #7374](https://github.com/trinodb/trino/issues/7374)
> * Fixes [An increasing number of WAITING state threads in JDBC driver #14176](https://github.com/trinodb/trino/issues/14176)
> * Related to [FutureTask replaces CompletableFuture to solve the thread can't be cancelled #7404](https://github.com/trinodb/trino/pull/7404)
> 
> ## Documentation
> (x) No documentation is needed. ( ) Sufficient documentation is included in this PR. ( ) Documentation PR is available with #prnumber. ( ) Documentation issue #issuenumber is filed, and can be handled later.
> 
> ## Release notes
> ( ) No release notes entries required. (x) Release notes entries required with the following suggested text:
> 
> ```
> # JDBC Client
> * Fix a bug where TrinoResultSet cannot be properly closed. ({issue}`7374`)
> ```

trino-jdbc 406 a lot of connection in timed_wating, there is the thread stack
"OkHttp ConnectionPool" https://github.com/trinodb/trino/pull/3363 daemon prio=5 os_prio=0 tid=0x00007f403810d800 nid=0x1195 in Object.wait() [0x00007f362a373000]
java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:460)
at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnectionPool.lambda$new$0(RealConnectionPool.java:62)

locked <0x0000000722d630e0> (a io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnectionPool)
at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnectionPool$$Lambda$2010/1587346617.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Locked ownable synchronizers:

<0x000000072287d118> (a java.util.concurrent.ThreadPoolExecutor$Worker)
"OkHttp ConnectionPool" https://github.com/trinodb/trino/pull/3358 daemon prio=5 os_prio=0 tid=0x00007f3eb0095000 nid=0x118d in Object.wait() [0x00007f362ab7b000]
java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:460)
at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnectionPool.lambda$new$0(RealConnectionPool.java:62)
locked <0x0000000722ae7c90> (a io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnectionPool)
at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnectionPool$$Lambda$2010/1587346617.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Locked ownable synchronizers:

<0x000000072261f628> (a java.util.concurrent.ThreadPoolExecutor$Worker)
a
