### PR TITLE
Fix ClassCastException in DomainTranslator

### LINKED ISSUE #14954: Using BETWEEN with varchar cast to date fails
```sql
with  t as (select '2022-01-01' as start_date,'2022-02-01' as end_date )
select  * from t 
where Date('2022-01-01') between date(start_date) and date(end_date)
```

Running above SQL fails with following stack trace.

```
Query 20221108_160922_00000_w2jf2 failed: class io.trino.sql.tree.GenericLiteral cannot be cast to class io.trino.sql.tree.Cast (io.trino.sql.tree.GenericLiteral and io.trino.sql.tree.Cast are in unnamed module of loader 'app')
java.lang.ClassCastException: class io.trino.sql.tree.GenericLiteral cannot be cast to class io.trino.sql.tree.Cast (io.trino.sql.tree.GenericLiteral and io.trino.sql.tree.Cast are in unnamed module of loader 'app')
	at io.trino.sql.planner.DomainTranslator$Visitor.createVarcharCastToDateComparisonExtractionResult(DomainTranslator.java:612)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitComparisonExpression(DomainTranslator.java:514)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitComparisonExpression(DomainTranslator.java:332)
	at io.trino.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:71)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.DomainTranslator$Visitor.lambda$visitLogicalExpression$0(DomainTranslator.java:387)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitLogicalExpression(DomainTranslator.java:388)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitLogicalExpression(DomainTranslator.java:332)
	at io.trino.sql.tree.LogicalExpression.accept(LogicalExpression.java:80)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitBetweenPredicate(DomainTranslator.java:1037)
	at io.trino.sql.planner.DomainTranslator$Visitor.visitBetweenPredicate(DomainTranslator.java:332)
	at io.trino.sql.tree.BetweenPredicate.accept(BetweenPredicate.java:71)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.DomainTranslator.getExtractionResult(DomainTranslator.java:329)
	at io.trino.sql.planner.optimizations.PropertyDerivations$Visitor.visitFilter(PropertyDerivations.java:720)
	at io.trino.sql.planner.optimizations.PropertyDerivations$Visitor.visitFilter(PropertyDerivations.java:170)
	at io.trino.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.trino.sql.planner.optimizations.PropertyDerivations.deriveProperties(PropertyDerivations.java:144)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.deriveProperties(AddExchanges.java:1341)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.deriveProperties(AddExchanges.java:1335)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.withDerivedProperties(AddExchanges.java:1330)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.rebaseAndDeriveProperties(AddExchanges.java:1306)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitFilter(AddExchanges.java:587)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitFilter(AddExchanges.java:147)
	at io.trino.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1301)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:193)
	at io.trino.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:147)
	at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:83)
	at io.trino.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:143)
	at io.trino.sql.planner.optimizations.StatsRecordingPlanOptimizer.optimize(StatsRecordingPlanOptimizer.java:54)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:247)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:222)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:217)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:475)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:456)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:397)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:249)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_402____20221108_160916_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Changing BETWEEN to > and < works. i.e. following SQL works

```sql
with  t as (select '2022-01-01' as start_date,'2022-02-01' as end_date )
select  * from t
where Date('2022-01-01') > date(start_date) and Date('2022-01-01') <= date(end_date);
```

### PR DESCRIPTION
**Pull request by martint**
When theres's an expression such as:

    CAST('2022-01-01') AS date) BETWEEN CAST(start_date AS date) AND CAST(end_date AS date)

There's a call to visitComparisonExpression with the term:

    DATE '2022-01-01' >= CAST(start_date AS date)

Inside that method, the expression is normalized to have the symbol on the left and the constant on the right. However, the createVarcharCastToDateComparisonExtractionResult pulls the elements from the unnormalized ComparisonExpression node and expects the left subexpression to be cast, which results in a failure due to ClassCastException

Fixes #14954 

## Release notes

(x) Release notes are required, with the following suggested text:

```markdown
# General
* Fix failure for queries involving BETWEEN predicates over `varchar` columns that contain temporal data. ({issue}`14954`)
```

### CODE REVIEW

**Review by findinpath — APPROVED** [review]

**Comment by findepi** [comment]
> When theres's an expression such as:
> 
> ```
> CAST('2022-01-01') AS date) BETWEEN CAST(start_date AS date) AND CAST(end_date AS date)
> ```
> 
> There's a call to visitComparisonExpression with the term:
> 
> ```
> DATE '2022-01-01' >= CAST(start_date AS varchar)
> ```

Did you mean `varchar` or `date` in the CAST on the rhs of the comparison?

File: core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java [hunk 1]
```diff
@@ -1083,6 +1083,23 @@ public void testPredicateWithVarcharCastToDate()
                 and(
                         greaterThanOrEqual(cast(C_VARCHAR, DATE), new GenericLiteral("DATE", "2001-01-31")),
                         lessThanOrEqual(cast(C_VARCHAR, DATE), new GenericLiteral("DATE", "2005-09-10"))));
+
+        assertPredicateTranslates(
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java:1087]: Add a comment what's special about this case.

**Review by findepi — APPROVED** [review]

File: core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java [hunk 2]
```diff
@@ -512,10 +512,12 @@ protected ExtractionResult visitComparisonExpression(ComparisonExpression node,
...
                 if (castSourceType instanceof VarcharType && castTargetType == DATE && !castExpression.isSafe()) {
                     Optional<ExtractionResult> result = createVarcharCastToDateComparisonExtractionResult(
-                            node,
+                            castExpression,
+                            normalized.getComparisonOperator(),
                             (VarcharType) castSourceType,
                             normalized.getValue(),
-                            complement);
+                            complement,
+                            node);
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java:520]: Why not `normalized` here?

File: core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java [hunk 3]
```diff
@@ -1083,6 +1083,23 @@ public void testPredicateWithVarcharCastToDate()
...
+                between(new GenericLiteral("DATE", "2001-01-31"), cast(C_VARCHAR, DATE), cast(C_VARCHAR_1, DATE)),
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java:1088]: the bug is reproducible with a simpler case

```java
        assertPredicateTranslates(
                greaterThan(new GenericLiteral("DATE", "2001-01-31"), cast(C_VARCHAR, DATE)),
                tupleDomain(
                        C_VARCHAR,
                        Domain.create(ValueSet.ofRanges(
                                Range.lessThan(VARCHAR, utf8Slice("2002")),
                                Range.greaterThan(VARCHAR, utf8Slice("9"))),
                                false)),
                greaterThan(new GenericLiteral("DATE", "2001-01-31"), cast(C_VARCHAR, DATE)));
```

- please add a simpler case
- please keep the BETWEEN case, as the BETWEEN explains why this cases needs to be handled correctly (and not eg rejected)
- please put some comment on both, for consistently with the rest of the method
  - can be as short as "regression test for ..."

File: core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java (hunk 2 above)
Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java:520]: You mean instead of passing the fields separately? Yes, that's a good idea.

Comment (findepi) [reply core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java:518]: No, i meant passing `normalized` instead of `node` for "original node" (of course, name to be changed).
This way, if we have "remaining expression", this is a normalized one, instead of original.

Nit anyway.

Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java:518]: Got it. Let me think about it. I'll post a follow-up.
