### PR TITLE
Fix planning failure due to incomplete pushdown

### LINKED ISSUE #2320: Join fails on IllegalArgumentException in simple cases of mixed types equality
Error occurs in version 326 and 324 and doesn't occur in 318 (It wasn't tested in version 319+) 
It happens on EXPLAIN execution.

```
create table t1(id integer);
create table t2(id bigint);
```

```
-- fail 
SELECT t1.id
FROM t1
JOIN t2 ON t1.id = t2.id
WHERE t1.id=10
```

```
-- succeed
SELECT t1.id
FROM t1
JOIN t2 ON t1.id = t2.id
```

```
-- fail 
SELECT t1.id
FROM t1
JOIN t2 ON cast(t1.id as bigint) = t2.id
WHERE t1.id=10
```

```
-- succeed
SELECT t1.id
FROM t1
JOIN t2 ON t1.id = cast(t2.id as integer)
WHERE t1.id=10
```

```
-- fail
SELECT t1.id
FROM t1
right JOIN t2 ON t1.id = t2.id
where t1.id=10
```

```
-- succeed
SELECT t1.id
FROM t1
left JOIN t2 ON t1.id = t2.id
WHERE t1.id=10
```

```
-- succeed
SELECT t1.id
FROM t1
full JOIN t2 ON t1.id = t2.id
WHERE t1.id=10
```

Error stack trace is :
```
java.lang.IllegalArgumentException: Equi criteria are empty, so INNER join should not have PARTITIONED distribution type
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:440)
	at io.prestosql.sql.planner.plan.JoinNode.<init>(JoinNode.java:128)
	at io.prestosql.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:554)
	at io.prestosql.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:130)
	at io.prestosql.sql.planner.plan.JoinNode.accept(JoinNode.java:314)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.optimizations.PredicatePushDown$Rewriter.visitExchange(PredicatePushDown.java:190)
	at io.prestosql.sql.planner.optimizations.PredicatePushDown$Rewriter.visitExchange(PredicatePushDown.java:130)
	at io.prestosql.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at io.prestosql.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:167)
	at io.prestosql.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:130)
	at io.prestosql.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at io.prestosql.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at io.prestosql.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at io.prestosql.sql.planner.optimizations.PredicatePushDown.optimize(PredicatePushDown.java:124)
	at io.prestosql.sql.planner.optimizations.StatsRecordingPlanOptimizer.optimize(StatsRecordingPlanOptimizer.java:52)
	at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:180)
	at io.prestosql.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:182)
	at io.prestosql.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:121)
	at io.prestosql.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:137)
	at io.prestosql.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:115)
	at io.prestosql.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:65)
	at io.prestosql.sql.tree.Explain.accept(Explain.java:80)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:62)
	at io.prestosql.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:57)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:80)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:219)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:178)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:95)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:715)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:119)
	at io.prestosql.$gen.Presto_326_g5e62b0e____20191211_141807.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by martint**
Given these tables:

```
CREATE TABLE t1(id integer);
CREATE TABLE t2(id bigint);
```
The following query fails with "Equi criteria are empty, so INNER join should not have PARTITIONED distribution type"

```
SELECT t1.id
FROM t1
JOIN t2 ON t1.id = t2.id
WHERE t1.id = 10
```

This occurs because PredicatePushdown cannot derive an equivalence during the first pass that helps
it infer that the join condition is always true. By the time the join distribution strategy is picked,
the join is still an equi-join, so the planner chooses PARTITIONED. Later on, during another pass of
PredicatePushdown, the condition is determined to be always true, and that implicitly converts the
Join to a cross join.

This change enhances PredicatePushdown to consider the predicate above the join to simplify the
effective predicate of the left/right branches of the join before engaging in the usual inference
logic. This is equivalent to inlining equalities defined by the predicate into the left/right
predicates and allows the equivalence inferencer to "infer more" and push predicates across the
branches of the join.

Fixes https://github.com/prestosql/presto/issues/2320

### CODE REVIEW

File: presto-testing/src/main/java/io/prestosql/testing/AbstractTestJoinQueries.java [hunk 1]
```diff
@@ -2256,6 +2256,25 @@ public void testRightJoinWithEmptyProbeSide()
                 "WITH small_part AS (SELECT * FROM part WHERE name = 'a') SELECT lineitem.orderkey FROM small_part RIGHT JOIN lineitem ON  small_part.partkey = lineitem.partkey");
     }
 
+    @Test
+    public void testEquijoinOnDifferentTypesWithFilter()
+    {
+        // Non-sensical query that exercises a join on integer vs bigint with a filter on the integer column that can be pushed down
```
Comment (findepi) [inline presto-testing/src/main/java/io/prestosql/testing/AbstractTestJoinQueries.java]: remove "Non-sensical". Most test queries do not make much sense

**Comment by sopel39** [comment]
This seem to solve problem only partially.

> Later on, during another pass of PredicatePushdown, the condition is determined to be always true, and that implicitly converts the Join to a cross join.

I think this implicit conversion should not produce invalid join node, but rather change join type to replicated.

File: presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java [hunk 2]
```diff
@@ -885,14 +885,20 @@ private static InnerJoinPushDownResult processInnerJoin(
             ImmutableSet<Symbol> leftScope = ImmutableSet.copyOf(leftSymbols);
             ImmutableSet<Symbol> rightScope = ImmutableSet.copyOf(rightSymbols);
 
+            // Attempt to simplify the effective left/right predicates with the predicate we're pushing down
+            // This, effectively, inlines any constants derived from such predicate
+            EqualityInference predicateInference = EqualityInference.newInstance(metadata, inheritedPredicate);
```
Comment (sopel39) [inline presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java]: Could we build more nested plan, where there are still not enough predicate pushdowns iterations?
See: https://github.com/prestodb/presto/issues/11569 (inference for outer joins might is limited and predicates might be derived only after n-th run depending how nested joins are)

**Comment by kasiafi** [comment]
> I think this implicit conversion should not produce invalid join node, but rather change join type to replicated.

I think `PredicatePushDown` should be able to adjust the distribution type in the case when it produces a cross join.
However, this mustn't happen after `AddExchanges`, and `PredicatePushDown` is run once after `AddExchanges`.

**Comment by sopel39** [comment]
> However, this mustn't happen after AddExchanges, and PredicatePushDown is run once after AddExchanges.

Right, so maybe PP shouldn't touch predicate at all if they require join type change (it's not PP responsibility)

**Comment by kasiafi** [comment]
> Right, so maybe PP shouldn't touch predicate at all if they require join type change (it's not PP responsibility)
I think we may want to keep this optimisation. Maybe PP could be aware if it is before or after AddExchanges?
Apart from that, we need some enhancement of PP to reduce the number of iterations. I checked the provided example query. It is a simple query, and still it needs exactly as many passes of PP to pushdown fully, as there are currently in PlanOptimizers.

**Comment by sopel39** [comment]
> I think we may want to keep this optimisation. Maybe PP could be aware if it is before or after AddExchanges?

If we do that before add exchanges, then it shouldn't matter as there is no PP execution between add exhanges and reorder joins/choose join distribution type

> Apart from that, we need some enhancement of PP to reduce the number of iterations.

this requires moving PP to iterative optimizer, but that requires more generic traits (for inherited predicate)

**Comment by martint** [comment]
> I think this implicit conversion should not produce invalid join node, but rather change join type to replicated.

This points to a more fundamental problem with how the IR and optimization work today (it's I'm my long-term list of things to address as we continue to evolve the IR). A partitioned join *needs* an equijoin criteria. A cross join doesn't have one. Changing it to replicated would break other assumptions and decisions AddExchanges made, so it can't be done in isolation.

**Comment by kasiafi** [comment]
> If we do that before add exchanges, then it shouldn't matter as there is no PP execution between add exhanges and reorder joins/choose join distribution type

So my suggestion is that we allow PredicatePushDown to produce cross joins, and set their DistributionType to REPLICATED or just leave it empty so that DetermineJoinDistributionType() will determine it.
The last point where we can do this is somewhere around the line 517.

There is one more occurrence of PredicatePushDown after AddExchanges. There we have to make sure that we don't produce a cross join from a PARTITIONED join.

File: presto-testing/src/main/java/io/prestosql/testing/AbstractTestJoinQueries.java (hunk 1 above)
Comment (martint) [reply presto-testing/src/main/java/io/prestosql/testing/AbstractTestJoinQueries.java]: It’s particularly non-sensical because it joins nation with lineitem on keys that are unrelated. But fair enough, I’ll remove it.

File: presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestReorderWindows.java [hunk 3]
```diff
@@ -248,7 +248,7 @@ public void testNotReorderAcrossNonPartitionFilter()
                                         .specification(windowA)
                                         .addFunction(functionCall("avg", commonFrame, ImmutableList.of(QUANTITY_ALIAS))),
                                 project(
-                                        filter(RECEIPTDATE_ALIAS + " IS NOT NULL",
+                                        filter("NOT (" + RECEIPTDATE_ALIAS + " IS NULL)",
```
Comment (findepi) [inline presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestReorderWindows.java]: btw why `IS NOT NULL` isn't the canonical form?

Comment (martint) [reply presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestReorderWindows.java]: Because we want the IR to be as small as possible. We already need to support NOT as a fundamental boolean operation. Note that the plan testing framework “cheats” and uses SQL expressions as a way to describe IR, so the fact that it’s the canonical IR form doesn’t mean it’s the canonical form in the SQL language.

File: presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/UnwrapCastInComparison.java [hunk 4]
```diff
@@ -112,6 +112,15 @@ private static ExpressionRewriter createRewrite(Metadata metadata, TypeAnalyzer
         };
     }
 
+    public static Expression unwrapCasts(Session session, Metadata metadata, TypeAnalyzer typeAnalyzer, TypeProvider types, Expression expression)
```
Comment (sopel39) [inline presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/UnwrapCastInComparison.java]: use `unwrapCasts` in `createRewrite`

File: presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java [hunk 5]
```diff
@@ -258,6 +260,8 @@ public PlanNode visitProject(ProjectNode node, RewriteContext<Expression> contex
 
             List<Expression> inlinedDeterministicConjuncts = inlineConjuncts.get(true).stream()
                     .map(entry -> inlineSymbols(node.getAssignments().getMap(), entry))
+                    .map(conjunct -> canonicalizeExpression(conjunct, typeAnalyzer.getTypes(session, types, conjunct), metadata))
```
Comment (sopel39) [inline presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java]: add comment why this is needed?
BTW: why canonicalization is needed here?

**Review by sopel39 — APPROVED** [review]

File: presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java (hunk 5 above)
Comment (martint) [reply presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java]: It's because UnwrapCasts only works with expressions of the form `CAST(x AS T) = constant`. `canonicalizeExpression` converts `constant = CAST(x AS T)`
