### PR TITLE
Change Hive CSV escape character to backslash when set to double quote

### LINKED ISSUE #18918: Behavior difference between OpenCSV native implementation and hive serde
When I create a table with csv data, where quote character and escape character are same, it throws an error with the native csv implementation (`Quote and escape characters cannot be the same`) whereas with hive it provides the expected output..

```
eg
data.csv

"""""col1","col2"

 CREATE TABLE t1 (
    a varchar,
    b varchar   
 )
 WITH (
    csv_escape = '"',
    csv_quote = '"',
    external_location = 's3://<>',
    format = 'CSV'
 )

Output with hive serde 
trino:default> select * from t1;
   a    |  b
--------+------
 ""col1 | col2

Output with native implementation
Query 20230905_051701_00009_dhywj failed: Quote and escape character cannot be the same

If i disable the checkArgument, then it shows 
trino:default> select * from t1;
  a   |  b
------+------
 col1 | col2
(1 row)
```

q1. What was the thought behind adding the checkArgument? Is it a limitation with native implementation?
q2. Any hack to achieve the same behavior as hive serde?

### PR DESCRIPTION
**Pull request by dain**
## Description

Hive has a bug that changes the escape character to backslash when it is explicitly set to a double quote during deserialization.  The native CSV reader is a bug for bug compatible reimplementation of the Hive OpenCSV reader, so this behavior must be replicated.

Fixes #18918 

## Release notes

(X) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix incompatibility with Hive OpenCSV deserialization.  When escape character is explicitly set to double quote, a backslash must be used instead. ({issue}`18918`)
```

### CODE REVIEW

File: lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/csv/CsvDeserializerFactory.java [hunk 1]
```diff
@@ -44,6 +46,15 @@ public LineDeserializer create(List<Column> columns, Map<String, String> serdePr
         char separatorChar = getCharProperty(serdeProperties, SEPARATOR_KEY, DEFAULT_SEPARATOR);
         char quoteChar = getCharProperty(serdeProperties, QUOTE_KEY, DEFAULT_QUOTE);
         char escapeChar = getCharProperty(serdeProperties, ESCAPE_KEY, DESERIALIZER_DEFAULT_ESCAPE);
+        // Hive has a bug where when the escape character is explicitly set to double quote (char 34),
+        // it changes the escape character to backslash (char 92) when deserializing.
+        if (escapeChar == SERIALIZER_DEFAULT_ESCAPE) {
+            // Add an explicit checks for separator or quote being backslash, so a more helpful error message can be provided
+            // as this Hive behavior is not obvious
+            checkArgument(separatorChar != DESERIALIZER_DEFAULT_ESCAPE, "Separator character cannot be '\\' when escape character is '\"");
```
Comment (electrum) [inline lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/csv/CsvDeserializerFactory.java:54]: Missing closing ‘ in both error messages for the second item

**Review by electrum — APPROVED** [review]
