### PR TITLE
Increase startup attempts from 1 to 3 in MongoDB container

### LINKED ISSUE #7005: Testing MongoServer is unable to start (flaky)
```
Error:  Tests run: 468, Failures: 2, Errors: 0, Skipped: 453, Time elapsed: 88.709 s <<< FAILURE! - in TestSuite
Error:  init(io.trino.plugin.mongodb.TestMongo4DistributedQueriesLatest)  Time elapsed: 22.563 s  <<< FAILURE!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at io.trino.plugin.mongodb.MongoServer.<init>(MongoServer.java:38)
	at io.trino.plugin.mongodb.TestMongo4DistributedQueriesLatest.createQueryRunner(TestMongo4DistributedQueriesLatest.java:29)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	... 17 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:497)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 18 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '(?i).*waiting for connections.*'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:49)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:892)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
	... 20 more

```
https://github.com/trinodb/trino/pull/6999/checks?check_run_id=1960893959

### LINKED ISSUE #8457: MongoServer is flaky
```
2021-06-29T10:05:09.6150786Z [ERROR] init(io.trino.plugin.mongodb.TestMongo3LatestConnectorSmokeTest)  Time elapsed: 17.784 s  <<< FAILURE!
2021-06-29T10:05:09.6159298Z org.testcontainers.containers.ContainerLaunchException: Container startup failed
2021-06-29T10:05:09.6169119Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
2021-06-29T10:05:09.6177498Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
2021-06-29T10:05:09.6184357Z 	at io.trino.plugin.mongodb.MongoServer.<init>(MongoServer.java:38)
2021-06-29T10:05:09.6195752Z 	at io.trino.plugin.mongodb.TestMongo3LatestConnectorSmokeTest.createQueryRunner(TestMongo3LatestConnectorSmokeTest.java:28)
2021-06-29T10:05:09.6205801Z 	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:91)
2021-06-29T10:05:09.6214060Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-06-29T10:05:09.6223513Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-06-29T10:05:09.6233801Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-06-29T10:05:09.6240872Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-06-29T10:05:09.6249380Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-06-29T10:05:09.6257207Z 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
2021-06-29T10:05:09.6264343Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
2021-06-29T10:05:09.6271306Z 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
2021-06-29T10:05:09.6276656Z 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
2021-06-29T10:05:09.6281235Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
2021-06-29T10:05:09.6285650Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-06-29T10:05:09.6290226Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-06-29T10:05:09.6293379Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-06-29T10:05:09.6297251Z Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
2021-06-29T10:05:09.6301983Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
2021-06-29T10:05:09.6307001Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
2021-06-29T10:05:09.6310290Z 	... 17 more
2021-06-29T10:05:09.6314684Z Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
2021-06-29T10:05:09.6320618Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:497)
2021-06-29T10:05:09.6326347Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
2021-06-29T10:05:09.6331863Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
2021-06-29T10:05:09.6335215Z 	... 18 more
2021-06-29T10:05:09.6339207Z Caused by: java.lang.ArrayIndexOutOfBoundsException: size=101 offset=0 byteCount=228
2021-06-29T10:05:09.6343893Z 	at org.testcontainers.shaded.okio.Util.checkOffsetAndCount(Util.java:30)
2021-06-29T10:05:09.6348866Z 	at org.testcontainers.shaded.okio.AsyncTimeout$1.write(AsyncTimeout.java:162)
2021-06-29T10:05:09.6354672Z 	at org.testcontainers.shaded.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
2021-06-29T10:05:09.6360826Z 	at org.testcontainers.shaded.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:54)
2021-06-29T10:05:09.6368954Z 	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.writeRequest(Http1ExchangeCodec.java:196)
2021-06-29T10:05:09.6437108Z 	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec.writeRequestHeaders(Http1ExchangeCodec.java:141)
2021-06-29T10:05:09.6441776Z 	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange.writeRequestHeaders(Exchange.java:72)
2021-06-29T10:05:09.6449398Z 	at org.testcontainers.shaded.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:43)
2021-06-29T10:05:09.6453469Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-06-29T10:05:09.6457377Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2021-06-29T10:05:09.6461610Z 	at org.testcontainers.shaded.com.github.dockerjava.okhttp.HijackingInterceptor.intercept(HijackingInterceptor.java:20)
2021-06-29T10:05:09.6465861Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-06-29T10:05:09.6469946Z 	at org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
2021-06-29T10:05:09.6474011Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-06-29T10:05:09.6478115Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2021-06-29T10:05:09.6481913Z 	at org.testcontainers.shaded.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
2021-06-29T10:05:09.6485678Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-06-29T10:05:09.6489575Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2021-06-29T10:05:09.6493556Z 	at org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2021-06-29T10:05:09.6497458Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-06-29T10:05:09.6501854Z 	at org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
2021-06-29T10:05:09.6506287Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2021-06-29T10:05:09.6510199Z 	at org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2021-06-29T10:05:09.6513920Z 	at org.testcontainers.shaded.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
2021-06-29T10:05:09.6516634Z 	at org.testcontainers.shaded.okhttp3.RealCall.execute(RealCall.java:81)
2021-06-29T10:05:09.6521610Z 	at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkDockerHttpClient$OkResponse.<init>(OkDockerHttpClient.java:256)
2021-06-29T10:05:09.6525629Z 	at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkDockerHttpClient.execute(OkDockerHttpClient.java:230)
2021-06-29T10:05:09.6530108Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
2021-06-29T10:05:09.6534744Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124)
2021-06-29T10:05:09.6539180Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.ExecCreateCmdExec.execute(ExecCreateCmdExec.java:30)
2021-06-29T10:05:09.6543561Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.ExecCreateCmdExec.execute(ExecCreateCmdExec.java:13)
2021-06-29T10:05:09.6548099Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
2021-06-29T10:05:09.6552464Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
2021-06-29T10:05:09.6556635Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.ExecCreateCmdImpl.exec(ExecCreateCmdImpl.java:172)
2021-06-29T10:05:09.6561127Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.ExecCreateCmdImpl.exec(ExecCreateCmdImpl.java:12)
2021-06-29T10:05:09.6571419Z 	at org.testcontainers.containers.ExecInContainerPattern.execInContainer(ExecInContainerPattern.java:71)
2021-06-29T10:05:09.6574520Z 	at org.testcontainers.containers.ContainerState.execInContainer(ContainerState.java:235)
2021-06-29T10:05:09.6581359Z 	at org.testcontainers.containers.ContainerState.execInContainer(ContainerState.java:226)
2021-06-29T10:05:09.6584119Z 	at org.testcontainers.containers.MongoDBContainer.initReplicaSet(MongoDBContainer.java:126)
2021-06-29T10:05:09.6587059Z 	at org.testcontainers.containers.MongoDBContainer.containerIsStarted(MongoDBContainer.java:80)
2021-06-29T10:05:09.6590145Z 	at org.testcontainers.containers.GenericContainer.containerIsStarted(GenericContainer.java:659)
2021-06-29T10:05:09.6592906Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:476)
2021-06-29T10:05:09.6594319Z 	... 20 more
2021-06-29T10:05:09.6594562Z 
2021-06-29T10:05:10.0559511Z [INFO] 
2021-06-29T10:05:10.0562330Z [INFO] Results:
2021-06-29T10:05:10.0563905Z [INFO] 
2021-06-29T10:05:10.0565437Z [ERROR] Failures: 
2021-06-29T10:05:10.0571856Z [ERROR]   TestMongo3LatestConnectorSmokeTest>AbstractTestQueryFramework.init:91->createQueryRunner:28 » ContainerLaunch
2021-06-29T10:05:10.0575585Z [INFO] 
2021-06-29T10:05:10.0578609Z [ERROR] Tests run: 187, Failures: 1, Errors: 0, Skipped: 50
```

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #8457 Fixes #7005

Stress test: https://github.com/trinodb/trino/runs/3700255475

### CODE REVIEW

File: plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoServer.java [hunk 1]
```diff
@@ -33,6 +33,7 @@ public MongoServer()
     public MongoServer(String mongoVersion)
     {
         this.dockerContainer = new MongoDBContainer("mongo:" + mongoVersion)
+                .withStartupAttempts(3)
```
Comment (findepi) [inline plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoServer.java:36]: nice

**Review by findepi — APPROVED** [review]
