### PR TITLE
Iceberg: use native implementation to obtain snapshot schema

### LINKED ISSUE #13613: Fail to execute Iceberg time travel query
After update Trino version to 392, queries failed for time travel queries. 

```
trino> SELECT * FROM iceberg.meta.jobs for version as of 658617487758551825 limit 1;
Query 20220811_091143_00000_5rmtv failed: Internal error
```

Stacktrace: 
```
java.lang.NullPointerException: undefined
	at org.apache.iceberg.SchemaParser.toJson(SchemaParser.java:172)
	at org.apache.iceberg.SchemaParser.toJson(SchemaParser.java:162)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableHandle(IcebergMetadata.java:341)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableHandle(IcebergMetadata.java:228)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:1006)
	at io.trino.metadata.MetadataManager.lambda$getTableHandle$4(MetadataManager.java:268)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:262)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1458)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.getTableHandle(StatementAnalyzer.java:4610)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1783)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:447)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:464)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3732)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2420)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:447)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:464)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:472)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1389)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:447)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:464)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:427)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:193)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:808)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:139)
	at io.trino.$gen.Trino_392_mi_SNAPSHOT____20220811_090358_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by xiacongling**
## Description

> Is this change a fix, improvement, new feature, refactoring, or other?

a fix

> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)

Iceberg Connector

> How would you describe this change to a non-technical end user or system administrator?

Uss native implementation to obtain snapshot schema when executing Iceberg time travel queries. Time travel queries on a table created with Iceberg<0.12 will fail without this fix.

## Related issues, pull requests, and links

related to #12743 #12786
fixes #13613

## Documentation

(x) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

() No release notes entries required.
(x) Release notes entries required with the following suggested text

```markdown
# Iceberg
* Fix failure when executing time travel queries on a table created with Iceberg<0.12. ({issue}`13613`)
```

### CODE REVIEW

**Review by findepi — APPROVED** [review]
@xiacongling would you be able to add a regression product test for this case?

see `TestIcebergSparkCompatibility` for existing tests

**Comment by xiacongling** [comment]
@findepi sure

**Comment by xiacongling** [comment]
Spend some time with the testing framework and finally get it work. A case is added in SuiteCompatibility for the reason that Iceberg metafile is changing over times, we must make sure tables created by an early version of Trino can be queried correctly. 

Early versions (<= 364) of Trino use iceberg v0.11 which did not support time traveling. The snapshot did not have a field named `schema-id` in its metadata JSON file. After updated to Trino 392, it will fail to query such tables with the following exception message:
```
io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20220812_044558_00002_36g47): Cannot invoke "org.apache.iceberg.Schema.asStruct()" because "schema" is null
```

**Comment by xiacongling** [comment]
@findepi Could you review this PR?

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+public class TestIcebergFormatVersionCompatibility
+        extends ProductTest
+{
+    private static final String TRINO_CATALOG = "iceberg";
+    private static final String TEST_SCHEMA_NAME = "default";
+
+    @Test(groups = {ICEBERG_FORMAT_VERSION_COMPATIBILITY, PROFILE_SPECIFIC_TESTS})
+    public void testTrinoTimeTravelReadTableCreatedByEarlyVersionTrino()
+    {
+        String baseTableName = "test_trino_reading_primitive_types_" + randomTableSuffix();
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java:42]: update table name to match test name

Comment (xiacongling) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java]: updated

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+        String tableName = trinoTableName(baseTableName);
+
+        onCompatibilityTestServer().executeQuery(format("CREATE TABLE %s (c VARCHAR)", tableName));
+        onCompatibilityTestServer().executeQuery(format("INSERT INTO %s VALUES ('a'), ('b'), ('c');", tableName));
```
[the remark this answers is not in the document]
Comment (xiacongling) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java]: updated

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+
+        long latestSnapshotId = (long) onCompatibilityTestServer()
+                .executeQuery(format("SELECT snapshot_id FROM %s ORDER BY committed_at DESC FETCH FIRST 1 ROW WITH TIES", trinoTableName("\"" + baseTableName + "$snapshots\"")))
+                .row(0).get(0);
```
[the remark this answers is not in the document]
Comment (xiacongling) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java]: updated. thanks for pointing it out.

File: testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteCompatibility.java [hunk 4]
```diff
@@ -60,10 +60,16 @@ public List<SuiteTestRun> getTestRuns(EnvironmentConfig config)
                         .withGroups("configured_features", "hive_view_compatibility")
                         .build())
                 .collect(toImmutableList());
+        ImmutableList<SuiteTestRun> trinoIcebergCompatibilityTestRuns = testedPrestoDockerImages().stream()
```
[the remark this answers is not in the document]
Comment (xiacongling) [reply testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteCompatibility.java]: Sorry for my mistake to use the unexpected method. You are right that different versions should be tested and using  `testedTrinoDockerImages` is a better choice. Thanks for your advice.

**Comment by findinpath** [comment]
@xiacongling please squash the commits and follow the 
 guideline for the commit messages: 

https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md#format-git-commit-messages

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java [hunk 5]
```diff
@@ -326,7 +327,7 @@ public IcebergTableHandle getTableHandle(
             long snapshotId = endVersion.map(connectorTableVersion -> getSnapshotIdFromVersion(table, connectorTableVersion))
                     .orElseGet(() -> resolveSnapshotId(table, name.getSnapshotId().get(), isAllowLegacySnapshotSyntax(session)));
             tableSnapshotId = Optional.of(snapshotId);
-            tableSchema = table.schemas().get(table.snapshot(snapshotId).schemaId());
+            tableSchema = schemaFor(table, snapshotId);
```
Comment (alexjo2144) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:330]: For reference, here's what that method does:


```
  public static Schema schemaFor(Table table, long snapshotId) {
    Snapshot snapshot = table.snapshot(snapshotId);
    Preconditions.checkArgument(snapshot != null, "Cannot find snapshot with ID %s", snapshotId);
    Integer schemaId = snapshot.schemaId();

    // schemaId could be null, if snapshot was created before Iceberg added schema id to snapshot
    if (schemaId != null) {
      Schema schema = table.schemas().get(schemaId);
      Preconditions.checkState(schema != null,
          "Cannot find schema with schema id %s", schemaId);
      return schema;
    }

    // TODO: recover the schema by reading previous metadata files
    return table.schema();
  }
```

**Comment by xiacongling** [comment]
@findinpath done

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+        List<QueryAssert.Row> expected = onCompatibilityTestServer().executeQuery(format("SELECT * FROM %s", tableName)).rows().stream()
+                .map(row -> row(row.toArray()))
+                .collect(toImmutableList());
+        assertEquals(expected.size(), 3);
+        assertThat(onTrino().executeQuery(format("SELECT * FROM %s FOR VERSION AS OF %d", tableName, latestSnapshotId))).containsOnly(expected);
+
+        onCompatibilityTestServer().executeQuery(format("DROP TABLE %s", tableName));
+    }
+
+    private static String trinoTableName(String tableName)
```
Comment (homar) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java:63]: I saw similar method here `io.trino.tests.product.iceberg.TestIcebergSparkCompatibility#trinoTableName` maybe it makes sense to extract it to some utils ? Or make that one public and use here ?

**Review by homar — APPROVED** [review]

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java (hunk 6 above)
Comment (xiacongling) [reply testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java:63]: Yes, it's duplicated. Invoking method from the another test class is not a good idea, I think, because they are seperated part of testing and seems unrelated. Creating a method here is just for convenience and it's implemention is so simple. It seems no utility method exists to generate qualified table names. If using duplicated method here is not a good practice, I can directly use `String.format` just like other testing code.

**Comment by ebyhr** [comment]
I confirmed @xiacongling already submit CLA last week. 
cc: @martint

**Comment by martint** [comment]
@cla-bot check

**Comment by ebyhr** [comment]
Merged, thanks!
