### PR TITLE
Disable average aggreagtion pushdown on decimal type in ClickHouse

### LINKED ISSUE #10650: Incorrect average decimal pushdown in new ClickHouse versions
Below assertion in `TestClickHouseConnectorTest.testNumericAggregationPushdown()` fails in new ClickHouse versions (e.g. `21.3.19.1`).
```java
assertThat(query("SELECT avg(short_decimal), avg(long_decimal), avg(a_bigint), avg(t_double) FROM " + testTable.getName())).isFullyPushedDown();
```

```
Expecting:
  <(111.660, 111728394.9938271600, 1.117283945E8, 111.6605)>
to contain exactly in any order:
  <[(111.661, 111728394.9938271605, 1.117283945E8, 111.6605)]>
elements not found:
  <(111.661, 111728394.9938271605, 1.117283945E8, 111.6605)>
and elements not expected:
  <(111.660, 111728394.9938271600, 1.117283945E8, 111.6605)>
```

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #10650

I couldn't find the way to get the same result between new ClickHouse versions and Trino.

### CODE REVIEW

File: plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java [hunk 1]
```diff
@@ -432,7 +432,6 @@ public void testNumericAggregationPushdown()
             assertThat(query("SELECT min(short_decimal), min(long_decimal), min(a_bigint), min(t_double) FROM " + testTable.getName())).isFullyPushedDown();
             assertThat(query("SELECT max(short_decimal), max(long_decimal), max(a_bigint), max(t_double) FROM " + testTable.getName())).isFullyPushedDown();
             assertThat(query("SELECT sum(short_decimal), sum(long_decimal), sum(a_bigint), sum(t_double) FROM " + testTable.getName())).isFullyPushedDown();
-            assertThat(query("SELECT avg(short_decimal), avg(long_decimal), avg(a_bigint), avg(t_double) FROM " + testTable.getName())).isFullyPushedDown();
```
Comment (hashhar) [inline plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java:435]: Instead of deleting change assertion to `isNotFullyPushedDown`?

**Review by wendigo — APPROVED** [review]

**Review by hashhar — APPROVED** [review]
LGTM.

I'll investigate/ask upstream if there are functions to emulate Trino behaviour with newer versions. e.g. I see there is a `roundBankers` but I haven't tried.

**Comment by ebyhr** [comment]
Already tried `roundBankers`, but it didn't work well.

File: docs/src/main/sphinx/connector/clickhouse.rst [hunk 2]
```diff
@@ -12,7 +12,7 @@ Requirements
 
 To connect to a ClickHouse server, you need:
 
-* ClickHouse (version 20.8 or higher) or Altinity (version 20.3 or higher).
+* ClickHouse (version 21.3 or higher) or Altinity (version 20.3 or higher).
```
Comment (mosabua) [inline docs/src/main/sphinx/connector/clickhouse.rst:15]: why did the Altinity version not change? Oversight?

Comment (ebyhr) [reply docs/src/main/sphinx/connector/clickhouse.rst:15]: https://github.com/trinodb/trino/blob/master/plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java#L38
