### PR TITLE
Fix failure when reading non-primitive Parquet fields in Iceberg

### LINKED ISSUE #22347: Iceberg query failure because of predicate pushdown with iceberg column id
**Context**

> we have some Iceberg tables where we manually generate the parquet data files and Iceberg metadata ourselves. 

When `id` for the type is missing from the parquet file, this can cause a query failure on the call:

https://github.com/trinodb/trino/blob/7190f200962dc77d0ccb11a8e34beb71865e43b0/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java#L937

**Relevant stack trace**
```
Query 20240609_161836_02951_zpmtj failed: Error opening Iceberg split /path/data/file.parquet (offset=0, length=1660): Cannot invoke "org.apache.parquet.schema.Type$ID.intValue()" because the return value of "org.apache.parquet.schema.PrimitiveType.getId()" is null
io.trino.spi.TrinoException: Error opening Iceberg split /mnt/shavast01_datalake/iceberg/temp/_managedtmp/6p7pl0cwmpdw/iceberg_caches/iceberg-temp-ghjkloyvmfircvttdsyufowgjqtmgzwh/data/file.parquet (offset=0, length=1660): Cannot invoke "org.apache.parquet.schema.Type$ID.intValue()" because the return value of "org.apache.parquet.schema.PrimitiveType.getId()" is null
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createParquetPageSource(IcebergPageSourceProvider.java:1132)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createDataPageSource(IcebergPageSourceProvider.java:633)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:373)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:265)
        at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:48)
        at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
        at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:264)
        at io.trino.operator.Driver.processInternal(Driver.java:403)
        at io.trino.operator.Driver.lambda$process$8(Driver.java:306)
        at io.trino.operator.Driver.tryWithLock(Driver.java:709)
        at io.trino.operator.Driver.process(Driver.java:298)
        at io.trino.operator.Driver.processForDuration(Driver.java:269)
        at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:890)
        at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:77)
        at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
        at io.trino.$gen.Trino_448____20240607_201000_2.run(Unknown Source)
        at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
        at io.trino.execution.executor.scheduler.FairScheduler.runTask(FairScheduler.java:168)
        at io.trino.execution.executor.scheduler.FairScheduler.lambda$submit$0(FairScheduler.java:155)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.parquet.schema.Type$ID.intValue()" because the return value of "org.apache.parquet.schema.PrimitiveType.getId()" is null
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.lambda$getParquetTupleDomain$35(IcebergPageSourceProvider.java:1504)
        at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$7(CollectCollectors.java:195)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:702)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.getParquetTupleDomain(IcebergPageSourceProvider.java:1504)
        at io.trino.plugin.iceberg.IcebergPageSourceProvider.createParquetPageSource(IcebergPageSourceProvider.java:1017)
        ... 25 more
```

**Slack discussion**

https://trinodb.slack.com/archives/CJ6UC075E/p1717777005901119

**Technical notes**

The issue reported here is likely related to https://github.com/trinodb/trino/pull/19066

Avoid doing the predicate pushdown when any of the descriptors from the parquet schema is missing the **id** value.

For the corresponding PR - add an integration test to ensure we'll not be dealing with further regressions (either through hive migrate procedure or potentially https://iceberg.apache.org/docs/latest/spark-procedures/#add_files)

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

We were getting the value from `descriptorsByPath` only when it's a primitive type before https://github.com/trinodb/trino/pull/19066.

Fixes #22347 

## Release notes

```markdown
# Iceberg
* Fix failure when reading Parquet files that don't have `field-id` on structured types. ({issue}`22347`)
```

### CODE REVIEW

**Review by findepi — APPROVED** [review]

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java [hunk 1]
```diff
@@ -1421,6 +1421,7 @@ static TupleDomain<ColumnDescriptor> getParquetTupleDomain(Map<List<String>, Col
         }
 
         Map<Integer, ColumnDescriptor> descriptorsById = descriptorsByPath.values().stream()
+                .filter(descriptor -> descriptor.getPrimitiveType().getId() != null)
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java:1424]: Will this skip predicate pushdown when field ids are not present in parquet footer schema ?

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java [hunk 2]
```diff
@@ -229,6 +231,29 @@ public void testV2TableWithEqualityDeleteWhenColumnIsNested()
         assertQuery("SELECT array_column[1], map_column[1], row_column.x FROM " + tableName, "SELECT 1, 2, 1 FROM nation WHERE regionkey != 1");
     }
 
+    @Test
+    public void testParquetGeneratedByPyArrow()
+    {
+        String tableName = "test_parquet_by_pyarrow" + randomNameSuffix();
+        assertUpdate("CREATE TABLE " + tableName + "(names ARRAY(varchar))");
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:238]: Is the problem specific to complex types ?
I got the impression that it could happen for any primitive type when field ids are not in parquet footer schema

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java [hunk 3]
```diff
@@ -229,6 +231,29 @@ public void testV2TableWithEqualityDeleteWhenColumnIsNested()
         assertQuery("SELECT array_column[1], map_column[1], row_column.x FROM " + tableName, "SELECT 1, 2, 1 FROM nation WHERE regionkey != 1");
     }
 
+    @Test
+    public void testParquetGeneratedByPyArrow()
+    {
+        String tableName = "test_parquet_by_pyarrow" + randomNameSuffix();
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:237]: Do we need pyarrow file specifically ?
My guess is that we could write file through hive connector and migrate table to iceberg to get similar situation

Comment (ebyhr) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:237]: I couldn't reproduce the issue with Hive connector. We already have such a test `TestIcebergMigrateProcedure#testMigrateTableWithComplexType`, but it didn't catch the regression.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java (hunk 2 above)
Comment (ebyhr) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:238]: It's specific to compelx types. I initially tested with primitive types, but it doesn't cause a query failure.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java (hunk 1 above)
Comment (Heltman) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java:1424]: I guess yes, because we can't push predicate to parquet when we don't know field ids

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java:1424]: I think so. We have the following logic:
https://github.com/trinodb/trino/blob/623bcc2fb328665467d12ae02cb8700d6ae0a389/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java#L1428-L1434

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java (hunk 3 above)
Comment (raunaqmorarka) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:237]: I looked closer at it, we're able to generate ids from `nameMapping` for the migrated tables, that's why there is no issue there.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java (hunk 1 above)
Comment (raunaqmorarka) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java:1424]: I saw that we're able to generate ids from `nameMapping` for migrated tables from hive where the parquet files originally had no field ids. I'm wondering what's different in the pyarrow case which causes `ParquetSchemaUtil.applyNameMapping` to not provide ids. Is it just because of the contents of `schema.name-mapping.default` and not because of anything special about the parquet file from pyarrow ?

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java:1424]: Right. So, we can reproduce the issue with Hive connector if we directly add the file to Iceberg table without `migrate` procedure.

Comment (raunaqmorarka) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java:1424]: ya, i think it'll be better to keep the test based on hive connector produced files. We'll be able to avoid the pyarrow specific test resources and someone looking into this scenario in future will not need to know anything outside Trino.

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java:1424]: Updated the test to create a Parquet file with Hive connector on the fly.

**Review by raunaqmorarka — APPROVED** [review]

**Review by Heltman — APPROVED** [review]

**Review by wendigo — APPROVED** [review]
