### PR TITLE
Fix writing incorrect results when partition order is different in Delta Lake

### LINKED ISSUE #13505: Delta Lake broken when partition column order does not match table column order
```sql
DROP TABLE IF EXISTS test_delta; 

CREATE TABLE test_delta (
   id integer,
   first varchar,
   second varchar
)
WITH (
   type = 'DELTA',
   partitioned_by = ARRAY['second', 'first'] -- NOTE: different than table column order
);

INSERT INTO test_delta (first, id, second)
VALUES ('A', 1, 'B');

-- also broken when inserting with default column order
INSERT INTO test_delta 
VALUES (2, 'X', 'Y');

select * from test_delta;
```

Here is the output.  Notice first and second are swapped:

id | first | second
-- | -- | --
1 | B | A
2 | Y | X

Some example test queries
```sql
-- test cases
SELECT if (first <> 'A', fail('delta partitioning is broken')) FROM test_delta WHERE id = 1;
SELECT if (first <> 'X', fail('delta partitioning is broken')) FROM test_delta WHERE id = 2;
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

```sql
CREATE TABLE test_delta (
   id integer,
   first varchar,
   second varchar
)
WITH (
   partitioned_by = ARRAY['second', 'first']
);
```

This PR fixes  wrong `partitionValues` field and changes directory structure (`first=x/second=y` → `second=y/first=x`). The new directory structure is same as Spark. 

Fixes #13505

## Documentation

(x) No documentation is needed.

## Release notes

(x) Release notes entries required with the following suggested text:

```markdown
# Delta Lake
* Fix writing incorrect results when the partition column order is different from the table definition. ({issue}`13505`)
```

### CODE REVIEW

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java [hunk 1]
```diff
@@ -262,6 +262,29 @@ public void testQueryNullPartitionWithNotPushdownablePredicate()
         assertQuery("SELECT a FROM " + tableName + " WHERE c % 5 = 1", "VALUES (1)");
     }
 
+    @Test
+    public void testPartitionColumnOrderIsDifferentFromTableDefinition()
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java:266]: Can you pls add a compatibility test with Spark (databricks/delta oss)?

Comment (ebyhr) [reply plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java:270]: Added compatibility tests.

**Comment by findepi** [comment]
is the CI failure related?

**Comment by ebyhr** [comment]
@findepi No, it's "Table being modified concurrently" error in existing tests.

**Review by findepi — APPROVED** [review]
