### PR TITLE
Handle repeated expressions in QueryPlanner.coerce()

### LINKED ISSUE #8027: 'Multiple entries with same key' error on duplicated grouping on literal value
The following queries fail with 'Multiple entries with same key' error on Trino 356.

```
trino> select null group by 1, 1;
Query 20210521_142930_00005_r3wn2 failed: line 1:26: Multiple entries with same key: @15593b5d: null=expr and @15593b5d: null=expr

trino> select '123' group by 1, 1;
Query 20210521_142933_00006_r3wn2 failed: Multiple entries with same key: @55e072a3: '123'=expr and @55e072a3: '123'=expr
```

Full stacktrace:
```
	
java.lang.IllegalArgumentException: Multiple entries with same key: @15593b5d: null=expr and @15593b5d: null=expr
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:210)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:204)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:146)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:109)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:389)
	at io.trino.sql.planner.QueryPlanner.coerce(QueryPlanner.java:1340)
	at io.trino.sql.planner.QueryPlanner.aggregate(QueryPlanner.java:657)
	at io.trino.sql.planner.QueryPlanner.plan(QueryPlanner.java:377)
	at io.trino.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:931)
	at io.trino.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:129)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:587)
	at io.trino.sql.planner.QueryPlanner.plan(QueryPlanner.java:185)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:924)
	at io.trino.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:129)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:692)
	at io.trino.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:266)
	at io.trino.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:237)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:202)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:197)
	at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:192)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:482)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:462)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:405)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_356____20210521_141328_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

As far as I investigated, this error started to happen from this commit: https://github.com/trinodb/trino/commit/edb4b8b12a01d4b5ecad3395b87bc92daa829902, but I'm not yet sure what actually causes this issue.

### PR DESCRIPTION
**Pull request by martint**
This can happen as a result of resolving repeated GROUP BY ordinals.

Fixes https://github.com/trinodb/trino/issues/8027

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java [hunk 1]
```diff
@@ -1310,24 +1310,26 @@ public static PlanAndMappings coerce(PlanBuilder subPlan, List<Expression> expre
...
 
-        ImmutableMap.Builder<NodeRef<Expression>, Symbol> mappings = ImmutableMap.builder();
+        Map<NodeRef<Expression>, Symbol> mappings = new HashMap<>();
         for (Expression expression : expressions) {
             Type coercion = analysis.getCoercion(expression);
 
-            if (coercion != null) {
-                Type type = analysis.getType(expression);
-                Symbol symbol = symbolAllocator.newSymbol(expression, coercion);
+            if (!mappings.containsKey(NodeRef.of(expression))) {
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java:1317]: Why would `expressions` contain duplicates (in identity sense)?

is it because `SELECT exp ... GROUP BY 1, 1`  gets "converted" into `... GROUP BY exp, exp`?

add explanation to the code.

File: core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java [hunk 2]
```diff
@@ -1337,7 +1339,7 @@ public static PlanAndMappings coerce(PlanBuilder subPlan, List<Expression> expre
                         subPlan.getRoot(),
                         assignments.build()));
 
-        return new PlanAndMappings(subPlan, mappings.build());
+        return new PlanAndMappings(subPlan, mappings);
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java:1342]: `ImmutableMap.copyOf`

(`PlanAndMappings` constructor should _also_ do that, but currently it doesn't)

**Review by findepi — APPROVED** [review]

File: core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java (hunk 1 above)
Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java:1317]: Yes. It's because the `1` are treated as "references" to an expression. From the point of view of this method, there's no requirement that the expressions be unique in the provided list, so it needs to protect against duplicates singe it's using a structure that doesn't allow them.

File: core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java (hunk 2 above)
Comment (martint) [reply core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java:1342]: That's actually unnecessary here. This method doesn't hold on to the map, so it doesn't care what `PlanAndMappings` does with it. `PlanAndMappings` should be updated to do it, though.

Comment (findepi) [reply core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java:1343]: > That's actually unnecessary here. This method doesn't hold on to the map

yes, but we don't want downstream code to become dependent on the map being mutable

(not important, nvrm)
