### PR TITLE
Fix partition predicate pushdown containing null in Glue

### LINKED ISSUE #13083: Predicate pushdown with NULL on Glue return incorrect result
# sql1
```
select 
            account_channel,
            count(*)
              FROM hive.lb_bi_finance.dws_ipo_profit_and_loss_analysis_d
              WHERE 
                  pt IN ('20220704','20210704')
                  ---and account_channel !='lb'
                AND (account_channel = 'pspl_sg' OR account_channel IS NULL)
              GROUP BY 
                  account_channel
```

### Trino

image

### Presto

image

# Sql2:count null
```
select count(0)
              FROM hive.lb_bi_finance.dws_ipo_profit_and_loss_analysis_d
              WHERE 
                  pt IN ('20220704','20210704')
                  and account_channel is null
```
### Trino

image

### Presto

image

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fix partition predicate pushdown containing null in Glue
Fixes #13083

## Documentation

(x) No documentation is needed.

## Release notes

(x) Release notes entries required with the following suggested text:

```markdown
# Hive, Iceberg, Delta Lake
* Fix incorrect results when using the Glue metastore and queries contain `IS NULL` with additional filters. ({issue}`13124`). ({issue}`13083`)
```

### CODE REVIEW

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java [hunk 1]
```diff
@@ -196,6 +196,10 @@ else if (singleValues.size() > 1) {
             disjuncts.add(inClause);
         }
 
+        if (domain.isNullAllowed()) {
+            disjuncts.add(format("(%s = '%s')", columnName, NULL_STRING));
```
Comment (findinpath) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java:200]: This issues an invalid expression when working with partition columns which don't have string type.

```
((part_key_1 = 1000) OR (part_key_1 = '__HIVE_DEFAULT_PARTITION__'))
```

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java [hunk 2]
```diff
@@ -837,6 +837,49 @@ public void testGetPartitionsFilterIsNullWithValue()
...
+                .build();
+
+        doGetPartitionsFilterTest(
+                CREATE_TABLE_COLUMNS_PARTITIONED_TWO_KEYS,
+                ImmutableList.of(PARTITION_KEY, PARTITION_KEY2),
+                ImmutableList.of(
+                        PartitionValues.make("2020-01-01", "100"),
+                        PartitionValues.make("2020-02-01", "200"),
+                        PartitionValues.make("2020-03-01", "300"),
+                        PartitionValues.make(null, "300")),
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java:878]: It should be `300` (same value used at L868).

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java:200]: Such types are already excluded by: https://github.com/trinodb/trino/blob/0cdabe186d190cdcfbf156138d261d3905001d09/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java#L79-L82

File: plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (findinpath) [reply plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java:878]: You are right. Thank you for the explanation.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java (hunk 1 above)
Comment (findinpath) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java:200]: The following test

```
 @Test
    public void testGetPartitionsFilterSmallIntFilterEqualsOrIsNullWithValue()
            throws Exception
    {
        TupleDomain<String> equalsOrIsNullFilter = new PartitionFilterBuilder()
                .addSmallintValues(PARTITION_KEY, 1000L)
                .addDomain(PARTITION_KEY, Domain.onlyNull(SmallintType.SMALLINT))
                .build();


        doGetPartitionsFilterTest(
                CREATE_TABLE_COLUMNS_PARTITIONED_SMALLINT,
                ImmutableList.of(PARTITION_KEY),
                ImmutableList.of(
                        PartitionValues.make("1"),
                        PartitionValues.make("100"),
                        PartitionValues.make("1000"),
                        PartitionValues.make("10000"),
                        PartitionValues.make((String)null)),
                ImmutableList.of(equalsOrIsNullFilter),
                ImmutableList.of(ImmutableList.of()));
    }
```

fails with the following stacktrace

```
io.trino.spi.TrinoException: Failed to fetch partitions from Glue Data Catalog

	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.getPartitions(GlueHiveMetastore.java:785)
	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.getPartitionNamesByFilter(GlueHiveMetastore.java:757)
	at io.trino.plugin.hive.metastore.glue.TestHiveGlueMetastore.doGetPartitionsFilterTest(TestHiveGlueMetastore.java:1313)
	at io.trino.plugin.hive.metastore.glue.TestHiveGlueMetastore.testGetPartitionsFilterSmallIntFilterEqualsOrIsNullWithValue(TestHiveGlueMetastore.java:894)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.util.concurrent.ExecutionException: io.trino.spi.TrinoException: com.amazonaws.daylight.core.exceptions.InvalidPartitionValueException: For input string: "__HIVE_D" is not an integer. (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: 6a7c487f-7b61-48d9-941e-15df77cedcbe; Proxy: null)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.getPartitions(GlueHiveMetastore.java:778)
	... 27 more
```

Note that the `GlueHiveMetastore` has the setting `hive.metastore.glue.assume-canonical-partition-keys` set to `true` in the test class `TestGlueHiveMetastore`.

Comment (ebyhr) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java:200]: Good catch. The existing logic with single condition also hits the issue. According to https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-partitions.html#aws-glue-api-catalog-partitions-GetPartitions, we could simply use `IS (NOT) NULL` instead of `__HIVE_DEFAULT_PARTITION__`. Investigating.

Comment (findinpath) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java:200]: I tried it out already and it doesn't seem to work :( 
I'm not sure in which constellation is the filter `columnName IS NULL` is actually effective.

Comment (ebyhr) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java:200]: At glance, `columnName IS NULL` looks effective in case of numeric types. It didn't work for varchar type though.

Comment (findinpath) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java:200]: I tried it as well to verify again and didn't receive the expected output.

Let's rather return `Optional.empty()` when dealing with a situation where `NULL` is allowed (at least for everything non `varchar`) in `buildGlueExpressionForSingleDomain` (and add additional test case assertion to verify that the predicate  corresponding to the column having allowing NULL values in its filter is discarded - proof of concept: `io.trino.plugin.hive.metastore.glue.TestHiveGlueMetastore#testGetPartitionsWithFilterUsingReservedKeywordsAsColumnName`)

Comment (ebyhr) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java:200]: > Let's rather return Optional.empty() when dealing with a situation where NULL is allowed (at least for everything non varchar) in buildGlueExpressionForSingleDomain

This will lead to incorrect result in my understanding. Let's continue in #13124.

Comment (findinpath) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java:200]: Actually no. It will just retrieve more partitions from Glue, but they will be further filtered locally. Similarly to the approach done for columns named wirh the reserved keywords, we can retrieve for now at least more partitions for the null check use case. If we find in the meantime a better solution we can improve then  hive glue support.

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
```
42 successful, 1 failing, and 1 in progress checks
ci / test (plugin/trino-delta-lake) (pull_request) Failing after 18m — test (plugin/trino-delta-lake)
ci / pt (default, suite-2, ) (pull_request) In progress — This check has started...
```
