### PR TITLE
Fix JDBC Driver.getPropertyInfo() and validate allowed properties

### LINKED ISSUE #10624: JDBC driver does not return list of properties

### PR DESCRIPTION
**Pull request by electrum**
Fixes #10624

### CODE REVIEW

File: client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java [hunk 1]
```diff
@@ -378,6 +380,50 @@ public void testNullUrl()
...
+                .extracting(TestTrinoDriver::driverPropertyInfoToString)
+                .contains("{name=user, required=true}")
+                .contains("{name=password, required=false}")
+                .contains("{name=accessToken, required=false}")
+                .contains("{name=SSL, required=false, choices=[true, false]}");
+
+        assertThat(infos).extracting(x -> x.name)
+                .doesNotContain("SSLVerification", "SSLTrustStorePath");
+
+        properties.setProperty("user", "test");
```
Comment (kokosing) [inline client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java:403]: please extract this case as separate test method

**Review by kokosing — APPROVED** [review]

**Comment by mosabua** [comment]
Can we get this merged before the 372 release maybe @martint and @electrum ?

**Comment by mosabua** [comment]
Awesome. I will let the DBVisualizer team know..
