### PR TITLE
Fix failure when equality delete updated nested fields in Iceberg

### LINKED ISSUE #18625: Read iceberg v2 table which has equality deletes with nested fields failed
Iceberg v2 table with equality deletes should support nested fields as delete column, but when read, it will throw error like below:
```log
2023-08-09T15:16:47.338-0600	ERROR	stage-scheduler	io.trino.execution.StageStateMachine	Stage 20230809_211647_00008_s6wq4.0 failed
io.trino.spi.TrinoException: Multiple entries with same key: 3=f1 and 3=root.f1
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:142)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:299)
	at io.trino.operator.Driver.processInternal(Driver.java:395)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
```

For example:
```sql
-- create schema below
CREATE TABLE iceberg.default.test (id BIGINT, root ROW(nested BIGINT, nested_other BIGINT);
-- delete by `nested` to generate equality deletes
...
-- query table throw exception
SELECT * FROM iceberg.default.test;
```

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #18625

## Release notes

```markdown
## Iceberg
* Fix failure when reading tables which equality deletes updated nested fields. ({issue}`18625`)
```

### CODE REVIEW

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java [hunk 1]
```diff
@@ -349,23 +349,21 @@ public ConnectorPageSource createPageSource(
...
-                .map(readerColumns -> readerColumns.get().stream().map(IcebergColumnHandle.class::cast).collect(toList()))
-                .orElse(requiredColumns);
-
         Supplier<Optional<RowPredicate>> deletePredicate = memoize(() -> getDeleteManager(partitionSpec, partitionData)
                 .getDeletePredicate(
                         path,
                         dataSequenceNumber,
                         deletes,
-                        readColumns,
+                        deleteFilterRequiredColumns.stream().collect(toImmutableList()),
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java:357]: Why not just pass in the Set ? It will avoid the `indexOf` lookups in List

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java [hunk 2]
```diff
@@ -120,7 +134,7 @@ public Page getNextPage()
 
             Optional<RowPredicate> deleteFilterPredicate = deletePredicate.get();
             if (deleteFilterPredicate.isPresent()) {
-                dataPage = deleteFilterPredicate.get().filterPage(dataPage);
+                dataPage = deleteFilterPredicate.get().filterPage(dataPage, deleteFilterIndexes);
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java:137]: I don't think you need to change interface, you can pass in `deleteFilterIndexes.length == 0 ? dataPage : dataPage.getColumns(deleteFilterIndexes)` to existing method

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java:137]: The `dataPage` contains non-filter columns. Calling `getColumns` early results in out-of-index failure.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/RowPredicate.java [hunk 3]
```diff
@@ -29,13 +29,13 @@ default RowPredicate and(RowPredicate other)
...
 
-    default Page filterPage(Page page)
+    default Page filterPage(Page page, int[] columns)
     {
         int positionCount = page.getPositionCount();
         int[] retained = new int[positionCount];
         int retainedCount = 0;
         for (int position = 0; position < positionCount; position++) {
-            if (test(page, position)) {
+            if (test(columns.length == 0 ? page : page.getColumns(columns), position)) {
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/RowPredicate.java:38]: Should `getColumns` be called per position ? I suspect it should be per page

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java (hunk 2 above)
Comment (raunaqmorarka) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java:137]: I'm not sure I follow, if calling `getColumns` works inside `filterPage` then it should work here too as the input page or deleteFilterIndexes are not changing

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java:137]: `getColumns` is used only for `test()` call in `filterPage`. Your suggestion affects all `page` in `filterPage`.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/RowPredicate.java [hunk 4]
```diff
@@ -29,13 +29,14 @@ default RowPredicate and(RowPredicate other)
...
 
-    default Page filterPage(Page page)
+    default Page filterPage(Page page, int[] columns)
     {
         int positionCount = page.getPositionCount();
         int[] retained = new int[positionCount];
         int retainedCount = 0;
         for (int position = 0; position < positionCount; position++) {
-            if (test(page, position)) {
+            Page selectedPage = columns.length == 0 ? page : page.getColumns(columns);
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/RowPredicate.java:38]: Why not do this outside the for loop ?

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/RowPredicate.java [hunk 5]
```diff
@@ -29,13 +29,14 @@ default RowPredicate and(RowPredicate other)
...
+            if (test(selectedPage, position)) {
```
Comment (raunaqmorarka) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/RowPredicate.java:39]: If we extract a subset of columns as input to `test`, then does it break assumptions about block index in the implementations ? E.g. in `io.trino.plugin.iceberg.delete.PositionDeleteFilter#createPredicate` we have `page.getBlock(filePosChannel)` and that can select different column if we pass in a subset of blocks of the page.

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/RowPredicate.java:39]: I'm not sure if I fully understand your concern. `List<IcebergColumnHandle> columns` argument in `PositionDeleteFilter#createPredicate` is also adjusted in this PR. https://github.com/trinodb/trino/pull/24512/files#diff-705548e3717786bbc076aba181f1eca081ec69200050c18100bfa959e05095dfR357

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 6]
```diff
@@ -432,10 +432,17 @@ private static IcebergColumnHandle createColumnHandle(NestedField baseColumn, Ne
...
-                .collect(toImmutableList());
-        return new Schema(StructType.of(icebergColumns).asStructType().fields());
+        Schema schema = new Schema();
+        List<NestedField> icebergColumns = new ArrayList<>();
+        for (IcebergColumnHandle column : columns) {
+            NestedField field = NestedField.optional(column.getId(), column.getName(), toIcebergType(column.getType(), column.getColumnIdentity()));
+            // Schema disallows duplicate fields
+            if (schema.findField(field.fieldId()) == null) {
+                icebergColumns.add(field);
+                schema = new Schema(StructType.of(icebergColumns).asStructType().fields());
```
Comment (findinpath) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:442]: Do we absolutely need to re-create the `schema` for each column?

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java [hunk 7]
```diff
@@ -62,15 +65,26 @@ public IcebergPageSource(
...
+        requireNonNull(rowPositionColumnIndex, "rowPositionColumnIndex is null");
         this.expectedColumnIndexes = new int[expectedColumns.size()];
-        for (int i = 0; i < expectedColumns.size(); i++) {
-            IcebergColumnHandle expectedColumn = expectedColumns.get(i);
-            checkArgument(expectedColumn.equals(requiredColumns.get(i)), "Expected columns must be a prefix of required columns");
-            expectedColumnIndexes[i] = i;
-
-            if (expectedColumn.isMergeRowIdColumn()) {
+        this.deleteFilterIndexes = new int[deleteFilterColumns.size()];
+        for (int i = 0; i < requiredColumns.size(); i++) {
```
Comment (pajaks) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java:72]: Is `expectedColumns` always subset of `requiredColumns` with index of elements preservation?

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java [hunk 8]
```diff
@@ -62,15 +65,26 @@ public IcebergPageSource(
...
+            IcebergColumnHandle column = requiredColumns.get(i);
+            if (i < expectedColumns.size()) {
+                expectedColumnIndexes[i] = i;
+            }
+            if (column.isMergeRowIdColumn()) {
                 this.rowIdColumnIndex = i;
             }
+            if (deleteFilterColumns.contains(column)) {
+                if (column.isRowPositionColumn()) {
+                    this.deleteFilterIndexes[deleteFilterColumns.indexOf(column)] = rowPositionColumnIndex.orElseThrow();
```
Comment (pajaks) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java:82]: Is is possible to have two columns with` isRowPositionColumn==true` ?

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java [hunk 9]
```diff
@@ -432,10 +432,17 @@ private static IcebergColumnHandle createColumnHandle(NestedField baseColumn, Ne
...
-        List<NestedField> icebergColumns = columns.stream()
-                .map(column -> NestedField.optional(column.getId(), column.getName(), toIcebergType(column.getType(), column.getColumnIdentity())))
-                .collect(toImmutableList());
-        return new Schema(StructType.of(icebergColumns).asStructType().fields());
+        Schema schema = new Schema();
+        List<NestedField> icebergColumns = new ArrayList<>();
+        for (IcebergColumnHandle column : columns) {
+            NestedField field = NestedField.optional(column.getId(), column.getName(), toIcebergType(column.getType(), column.getColumnIdentity()));
+            // Schema disallows duplicate fields
+            if (schema.findField(field.fieldId()) == null) {
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:440]: Yes, `TestIcebergV2.testMultipleEqualityDeletesWithNestedFields`. The `columns` parameter contains two field-id `3` before this change: 

Screenshot 2025-01-29 at 13 05 26

**Comment by ebyhr** [comment]
I'm investigating if replacing `Schema` with `StructType` may simplify the solution.

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (pajaks) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java:440]: During debugging `testMultipleEqualityDeletesWithNestedFields`, `columns` size is always 1 after changes.
As I understand `getDeletePredicate` now takes `deleteFilterRequiredColumns.stream().collect(toImmutableList())` instead of `readColumns` so it's already filtered?

**Review by pajaks — APPROVED** [review]

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java [hunk 10]
```diff
@@ -602,8 +602,8 @@ public void testMultipleEqualityDeletesWithNestedFields()
                     equalityFieldIds);
         }
 
-        // TODO: support read equality deletes with nested fields(https://github.com/trinodb/trino/issues/18625)
-        assertThat(query("SELECT * FROM " + tableName)).failure().hasMessageContaining("Multiple entries with same key");
+        assertThat(query("SELECT * FROM " + tableName))
```
Comment (findinpath) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java:605]: I don't know whether it is relevant

https://github.com/trinodb/trino/blob/4971ef1a6b07014354d28b22530f1101f482a4fd/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java#L297-L299

I've added the following assertion to see what happens when the column relevant in the equality filter is not present in the `SELECT` statement. Works as expected.
If you add this assertion, pls consider adding a corresponding comment  - worth having there to be protected against regressions 

```
        // verify that the equality delete is effective also when not specifying the corresponding column in the projection list
        assertThat(query("SELECT id FROM " + tableName))
                .matches("VALUES (BIGINT '1')");
```

**Review by findinpath — APPROVED** [review]
Well done!!!
