### PR TITLE
Fixed constant expression being passed to Connector through applyProjection

### LINKED ISSUE #19988: applyProjection should not pass constants to the connector
found by @SemionPar 

> As to how engine behaves, for a query `SELECT acctbal, 'test' FROM customer`, there are 2 calls to `applyProjection()`. First with just `acctbal` in projections, second with both `acctbal` and `Slice[hash=-613973703,length=4]::varchar(4)`

this is a bug -- engine should not bother the connector about constants, as the connector won't be able to do anything reasonable with them. they should be filtered out before `applyProjection` is called

### PR DESCRIPTION
**Pull request by athultr1997**
Constant expression should not be passed to the Connector since the connector cannot do anything meaningful with it. Added fix to filter out constant expressions before being pushed to the connector.

## Description
Fixes #19988. Constant expressions are being passed on to the connector via `Metadata.applyProjection` method during planning in the rule `PushProjectionIntoTableScan`. But, the connector cannot do anything meaningful with it. Therefore, this PR filters out constant expressions before applying the projections to the connector. Also, have changed the `TestPushProjectionIntoTableScan.testPushProjection` test for verification.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java [hunk 1]
```diff
@@ -115,6 +116,8 @@ public Result apply(ProjectNode project, Captures captures, Context context)
                                 typeAnalyzer,
                                 context.getSymbolAllocator().getTypes(),
                                 plannerContext).entrySet().stream())
+                // Filter out constant expressions. Constant expressions should not be pushed to the connector.
+                .filter(expression -> !(expression.getValue() instanceof Constant))
```
Comment (findepi) [inline core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java:120]: `expression` -> `entry` ?

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java [hunk 2]
```diff
@@ -199,12 +199,6 @@ public void testPushProjection()
                                             .collect(toImmutableMap(Map.Entry::getKey, e -> e.getValue()::equals)),
                                     Optional.of(PlanNodeStatsEstimate.builder()
                                             .setOutputRowCount(42)
-                                            .addSymbolStatistics(new Symbol(newNames.get(constant)), SymbolStatsEstimate.builder()
-                                                    .setDistinctValuesCount(1)
-                                                    .setNullsFraction(0)
-                                                    .setLowValue(5)
-                                                    .setHighValue(5)
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java:206]: why removed?

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java [hunk 3]
```diff
@@ -185,10 +188,7 @@ public void testPushProjection()
                                                 .build()))));
                     })
                     .matches(project(
-                            newNames.entrySet().stream()
-                                    .collect(toImmutableMap(
-                                            e -> e.getKey().getName(),
-                                            e -> expression(symbolReference(e.getValue())))),
+                            createAssignments(newNames, constants),
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java:191]: Can this be inlined back?

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java [hunk 4]
```diff
@@ -341,4 +335,23 @@ private static ColumnHandle column(String name, Type type)
     {
         return new TpchColumnHandle(name, type);
     }
+
+    private static Map<String, ExpressionMatcher> createAssignments(ImmutableMap<Symbol, String> newNames, ImmutableMap<Symbol, Expression> constants)
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java:339]: nit: while we love immutable collections and use them everywhere, in the interest of code readability we don't declare fields, variables or parameters as "Immutable...". Just `Map` will be enough

**Review by findepi — COMMENTED** [review]
thank you for your PR!

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java (hunk 2 above)
Comment (athultr1997) [reply core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java:206]: Symbol statistics for a constant did not make any sense.

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java (hunk 3 above)
Comment (athultr1997) [reply core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java]: Done

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java (hunk 4 above)
Comment (athultr1997) [reply core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java]: This function has been removed now as per the earlier comment to make the code inline.

File: core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java (hunk 1 above)
Comment (athultr1997) [reply core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java]: Done

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java [hunk 5]
```diff
@@ -185,10 +188,18 @@ public void testPushProjection()
                                                 .build()))));
                     })
                     .matches(project(
-                            newNames.entrySet().stream()
+                            Stream.concat(newNames.entrySet().stream(), constants.entrySet().stream())
                                     .collect(toImmutableMap(
                                             e -> e.getKey().getName(),
-                                            e -> expression(symbolReference(e.getValue())))),
+                                            e -> {
+                                                if (e.getValue() instanceof String) {
```
Comment (electrum) [inline core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java:195]: This can use pattern matching to avoid the explicit cast
```java
if (e.getValue() instanceof String value) {
    return expression(symbolReference(value.getValue()));
}

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java [hunk 6]
```diff
@@ -185,10 +188,18 @@ public void testPushProjection()
...
+                                                    return expression(symbolReference((String) e.getValue()));
+                                                }
+                                                else if (e.getValue() instanceof Expression) {
```
Comment (electrum) [inline core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java:198]: The "else" here is redundant since the "if" above always returns. So this can be
```java
if (e.getValue() instanceof Expression value) {
    return expression(value.getValue());
}

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java (hunk 5 above)
Comment (athultr1997) [reply core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java]: Done

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java (hunk 6 above)
Comment (athultr1997) [reply core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java]: done

File: core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java (hunk 2 above)
Comment (findepi) [reply core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java:206]: does it mean we no longer have statistics for the symbol that happens to be a constant projection?

Comment (athultr1997) [reply core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java:206]: Yes. Since constant projections will be filtered out before reaching the connector, statistics for constant symbols won't make any sense. WDYT ?

Comment (findepi) [reply core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java:206]: This is not stats provided to the connector.
This is stats provided to the engine (the optimizer).
After the change, the optimizer no longer knows that the symbol representing a constant is actually representing a constant.

Please restore this assertion.
The code responsible for producing this value needs to be updated. This is here
https://github.com/trinodb/trino/blob/768ff6f63a2f94e017c9c27f0c8b0c191b05425e/core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java#L180-L196

**Comment by mosabua** [comment]
👋 @athultr1997 .. thank you for keeping this PR up to date and rebased and addressing all comments.

@electrum and @findepi are there any further changes necessary or can you approve and merge?
