### PR TITLE
Fix DESCRIBE OUTPUT with versioned tables

### LINKED ISSUE #29077: Regression: Fail to DESCRIBE OUTPUT of iceberg versioned table
### Trino version

480

### Please describe the bug

Since https://github.com/trinodb/trino/pull/28681 DESCRIBE cursor fails for views selecting from specific iceberg snapshot.

```
CREATE OR REPLACE VIEW tbl_v AS
SELECT * FROM tbl_1 FOR VERSION AS OF 755360854029738355;

PREPARE statament1 FROM SELECT * FROM tbl_v;
DESCRIBE OUTPUT statament1;

io.trino.spi.TrinoException: line 3:3: DESCRIBE is not supported if a versioned table uses parameters
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:58)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.extractTableVersion(StatementAnalyzer.java:6078)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.getTableHandle(StatementAnalyzer.java:6056)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2333)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:534)
	at io.trino.sql.tree.Table.accept(Table.java:70)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:553)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:5107)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3180)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:534)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:553)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:561)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1607)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:534)
	at io.trino.sql.tree.Query.accept(Query.java:130)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:553)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:513)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:502)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:98)
	at io.trino.sql.rewrite.DescribeOutputRewrite$Visitor.visitDescribeOutput(DescribeOutputRewrite.java:132)
	at io.trino.sql.rewrite.DescribeOutputRewrite$Visitor.visitDescribeOutput(DescribeOutputRewrite.java:85)
	at io.trino.sql.tree.DescribeOutput.accept(DescribeOutput.java:42)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.DescribeOutputRewrite.rewrite(DescribeOutputRewrite.java:82)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:54)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:93)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:87)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:288)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:222)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:892)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:163)
	at io.trino.$gen.Trino_480____20260412_112717_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:128)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```

It's a major issue for apps using a view layer that selects from previous "ready" snapshots until the new "version" is ready to use

cc @ebyhr @findepi

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

- Fixes #29077

## Release notes

```markdown
## General
* Fix failure when executing `DESCRIBE OUTPUT` with versioned tables. ({issue}`29077`)
```

### CODE REVIEW

**Review by chenjian2664 — APPROVED** [review]

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java [hunk 1]
```diff
@@ -7945,7 +7945,32 @@ public void testPreparedStatementWithParameterizedVersionedTable()
...
+    }
+
+    @Test
+    public void testDescribeOutputWithVersionedTable()
+    {
+        try (TestTable table = newTrinoTable("test", "(x int)", List.of("1"))) {
+            Session firstSession = Session.builder(getSession())
+                    .addPreparedStatement("my_query", "SELECT * FROM %s FOR VERSION AS OF %s".formatted(table.getName(), getCurrentSnapshotId(table.getName())))
+                    .build();
+            assertThat(query(firstSession, "DESCRIBE OUTPUT my_query"))
```
Comment (Praveen2112) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:7958]: But do we expose the table version in case of DESCRIBE OUTPUT ?

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java [hunk 2]
```diff
@@ -7945,7 +7945,32 @@ public void testPreparedStatementWithParameterizedVersionedTable()
...
         assertQueryFails(session, "EXECUTE my_query USING " + (snapshotId - 1), "Iceberg snapshot ID does not exists: .*");
-        assertQueryFails(session, "DESCRIBE OUTPUT my_query", ".* DESCRIBE is not supported if a versioned table uses parameters");
+    }
+
+    @Test
+    public void testDescribeOutputWithVersionedTable()
+    {
+        try (TestTable table = newTrinoTable("test", "(x int)", List.of("1"))) {
+            Session firstSession = Session.builder(getSession())
+                    .addPreparedStatement("my_query", "SELECT * FROM %s FOR VERSION AS OF %s".formatted(table.getName(), getCurrentSnapshotId(table.getName())))
```
Comment (Praveen2112) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:7956]: But if the version is passed as a parameter, we should fail right ?

Comment (ebyhr) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:7956]: Right, let me update this PR.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java [hunk 3]
```diff
@@ -7945,7 +7945,32 @@ public void testPreparedStatementWithParameterizedVersionedTable()
                 .matches("TABLE region");
 
         assertQueryFails(session, "EXECUTE my_query USING " + (snapshotId - 1), "Iceberg snapshot ID does not exists: .*");
-        assertQueryFails(session, "DESCRIBE OUTPUT my_query", ".* DESCRIBE is not supported if a versioned table uses parameters");
```
Comment (Praveen2112) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:7948]: Is this test case migrated to a different class ?

Comment (ebyhr) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:7948]: I restored this case.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java:7958]: DESCRIBE OUTPUT result doesn't contain the table version, but the value can affect the output.

**Review by Praveen2112 — APPROVED** [review]
