### PR TITLE
Fix rounding in cast from TIME to TIMESTAMP

### LINKED ISSUE #5736: Invalid result of TIME to TIMESTAMP cast for high precisions
The value renders correctly (appears to be correct):

```
presto> SELECT CAST(TIME '12:34:56.55555555' AS TIMESTAMP(7));
            _col0
-----------------------------
 2020-10-29 12:34:56.5555556
(1 row)
```

but actual runtime value is not correct:

```
presto> SELECT CAST(TIME '12:34:56.55555555' AS TIMESTAMP(7)) = TIMESTAMP '2020-10-29 12:34:56.5555556';
 _col0
-------
 false
(1 row)
```

### PR DESCRIPTION
**Pull request by martint**
Fixes #5736

Relates to #5738

### CODE REVIEW

**Comment by findepi** [comment]
> Fixes #5736, #5738

To fix https://github.com/prestosql/presto/issues/5738 we should apply checks to other types too:

- length checks for char, varchar
- space padding checks for char
- ...

File: presto-main/src/main/java/io/prestosql/operator/scalar/time/TimeToTimestampCast.java [hunk 1]
```diff
@@ -56,23 +57,36 @@ public static LongTimestamp castToLong(
...
         }
 
-        long microFraction = rescale(picoFraction, TimeType.MAX_PRECISION, 6);
-        return multiplyExact(epochSecond, MICROSECONDS_PER_SECOND) + microFraction;
+        return picoFraction;
+    }
+
+    private static long computeEpochMicros(long epochSeconds, long picoFraction)
+    {
+        long microFraction = rescale(picoFraction, 12, 6);
```
Comment (findepi) [inline presto-main/src/main/java/io/prestosql/operator/scalar/time/TimeToTimestampCast.java:89]: Does `rescale` round or truncate?
i checked it truncates, but i'd write this simply as
```
// picoFraction is already rounded to whole micros
long microFraction = picoFraction / PICOSECONDS_PER_MICROSECOND;
```

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java [hunk 2]
```diff
@@ -43,7 +45,26 @@ public static SqlTimestamp fromMillis(int precision, long millis)
 
     public static SqlTimestamp newInstance(int precision, long epochMicros, int picosOfMicro)
     {
-        return newInstanceWithRounding(precision, epochMicros, picosOfMicro);
+        if (precision <= 6) {
+            if (picosOfMicro != 0) {
+                throw new IllegalArgumentException("Expected picosOfMicro to be 0 for precision <= 6: " + picosOfMicro);
```
Comment (findepi) [inline presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:50]: Mentioning epochMicros and precision as part of the exc msg may help tracing down the problem, should the exception occur anywhere outside of our tests.

introducing `private void checkArgument(...)` may help increase readability.

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java [hunk 3]
```diff
@@ -43,7 +45,26 @@ public static SqlTimestamp fromMillis(int precision, long millis)
...
+            }
+
+            if (rescale(rescale(epochMicros, 6, precision), precision, 6) != epochMicros) {
```
Comment (findepi) [inline presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:53]: since you already know precision <= 6, you can more tersely:

```
if (round(epochMicros, 6 - precision) != epochMicros)
```

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java [hunk 4]
```diff
@@ -43,7 +45,26 @@ public static SqlTimestamp fromMillis(int precision, long millis)
...
+                throw new IllegalArgumentException(format("Expected 0s for digits beyond precision %s: epochMicros = %s", precision, epochMicros));
+            }
+        }
+        else {
+            if (rescale(rescale(picosOfMicro, 12, precision), precision, 12) != picosOfMicro) {
```
Comment (findepi) [inline presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:58]: `round` as above

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java [hunk 5]
```diff
@@ -43,7 +45,26 @@ public static SqlTimestamp fromMillis(int precision, long millis)
 
     public static SqlTimestamp newInstance(int precision, long epochMicros, int picosOfMicro)
     {
-        return newInstanceWithRounding(precision, epochMicros, picosOfMicro);
+        if (precision <= 6) {
```
Comment (findepi) [inline presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:48]: should the `fromMillis` above do rounding or checks?

or maybe we (re)move it, since it is used in tests only

File: presto-spi/src/main/java/io/prestosql/spi/type/Timestamps.java [hunk 6]
```diff
@@ -79,10 +79,6 @@ public static long round(long value, int magnitude)
      */
     static long rescale(long value, int fromPrecision, int toPrecision)
     {
-        if (value < 0) {
-            throw new IllegalArgumentException("value must be >= 0");
```
Comment (findepi) [inline presto-spi/src/main/java/io/prestosql/spi/type/Timestamps.java:83]: `rescale` method works great when the rounding is known to be not necessary. 
For cases when rounding may be necessary, `round`, `floorDiv` seem to offer well defined semantics.

In this commit you're using the rounding-or-truncation of this method, but i'd change it to expect that value is pre-rounded. (actual check may be too expensive for runtime, idk).

This is more relevant when we allow negative numbers here.

**Review by findepi — APPROVED** [review]
Couple comments, otherwise LGTM.

Per https://github.com/prestosql/presto/pull/5742#issuecomment-718992077, i think we should not close https://github.com/prestosql/presto/issues/5738 when merging this.

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java (hunk 5 above)
Comment (martint) [reply presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:48]: It's supposed to be a convenience method to instantiate a SqlTimestamp of a given precision, including any necessary rounding. The issue with (re)moving it is that it would require making `newInstanceWithRounding` public, and that's not something I want to be visible.

File: presto-spi/src/main/java/io/prestosql/spi/type/Timestamps.java (hunk 6 above)
Comment (martint) [reply presto-spi/src/main/java/io/prestosql/spi/type/Timestamps.java:83]: > rescale method works great when the rounding is known to be not necessary.

Correct, and that's the exact purpose of this method. The only reason we had this check is to protect against trying to rescale epoch values which can be negative. But it doesn't matter. I'll get rid of the call to rescale as you suggested above and revert this change.

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java (hunk 5 above)
Comment (findepi) [reply presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:48]: > The issue with (re)moving it is that it would require making newInstanceWithRounding public, and that's not something I want to be visible.

`fromMillis` currently doesn't call `newInstanceWithRounding`, it calls `newInstance`

(perhaps incorectly so?)

Comment (martint) [reply presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:48]: Oh yeah, I fixed that in my branch and forgot to push :)

File: presto-spi/src/test/java/io/prestosql/spi/type/TestTimestamps.java [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+
+import static io.prestosql.spi.type.Timestamps.roundDiv;
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class TestTimestamps
+{
+    @Test
+    public void testRoundDiv()
+    {
+        // round towards negative
```
Comment (findepi) [inline presto-spi/src/test/java/io/prestosql/spi/type/TestTimestamps.java:26]: towards negative -> towards zero?
or "round down"

File: presto-spi/src/test/java/io/prestosql/spi/type/TestTimestamps.java [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+        assertThat(roundDiv(44444, 100000)).isEqualTo(0);
+
+        assertThat(roundDiv(-55556, 1)).isEqualTo(-55556);
+        assertThat(roundDiv(-55556, 10)).isEqualTo(-5556);
+        assertThat(roundDiv(-55556, 100)).isEqualTo(-556);
+        assertThat(roundDiv(-55556, 1000)).isEqualTo(-56);
+        assertThat(roundDiv(-55556, 10000)).isEqualTo(-6);
+        assertThat(roundDiv(-55556, 100000)).isEqualTo(-1);
+
+        // round towards positive
```
Comment (findepi) [inline presto-spi/src/test/java/io/prestosql/spi/type/TestTimestamps.java:41]: "round up"

File: presto-spi/src/test/java/io/prestosql/spi/type/TestTimestamps.java [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+
+import org.testng.annotations.Test;
+
+import static io.prestosql.spi.type.Timestamps.roundDiv;
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class TestTimestamps
+{
+    @Test
+    public void testRoundDiv()
```
Comment (findepi) [inline presto-spi/src/test/java/io/prestosql/spi/type/TestTimestamps.java:24]: perhaps add a test with 0 divisor (failure)
it would be great if negative divisor was rejected too

File: presto-main/src/main/java/io/prestosql/testing/DateTimeTestingUtils.java [hunk 10]
```diff
@@ -63,7 +64,7 @@ public static SqlTimestampWithTimeZone sqlTimestampWithTimeZoneOf(int precision,
         ZonedDateTime base = ZonedDateTime.of(year, month, day, hour, minute, second, 0, timeZoneKey.getZoneId());
 
         long epochMillis = base.toEpochSecond() * MILLISECONDS_PER_SECOND + nanoOfSecond / NANOSECONDS_PER_MILLISECOND;
-        int picosOfMilli = (int) scaleNanosToPicos(nanoOfSecond);
+        int picosOfMilli = (int) (scaleNanosToPicos(nanoOfSecond) % PICOSECONDS_PER_MILLISECOND);
```
Comment (findepi) [inline presto-main/src/main/java/io/prestosql/testing/DateTimeTestingUtils.java:67]: I dont understand the % here. If the value can `>= PICOSECONDS_PER_MILLISECOND`,  it seems we're discarding some information without compensating it (with eg `epochMillis++` or whatever is appropriate)

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java [hunk 11]
```diff
@@ -38,12 +39,24 @@
...
+            checkArgument(picosOfMicro == 0, "Expected picosOfMicro to be 0 for precision %s: %s", precision, picosOfMicro);
+            checkArgument(round(epochMicros, 6 - precision) == epochMicros, "Expected 0s for digits beyond precision %s: epochMicros = %s", precision, epochMicros);
+        }
+        else {
+            checkArgument(round(picosOfMicro, 12 - precision) == picosOfMicro, "Expected 0s for digits beyond precision %s: picosOfMicro = %s", precision, picosOfMicro);
+        }
+
+        if (picosOfMicro < 0 || picosOfMicro > PICOSECONDS_PER_MICROSECOND) {
+            throw new IllegalArgumentException("picosOfMicro is out of range: " + picosOfMicro);
+        }
```
Comment (findepi) [inline presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:57]: This could use `checkArgument` too

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestampWithTimeZone.java [hunk 12]
```diff
@@ -47,7 +48,19 @@ public static SqlTimestampWithTimeZone fromInstant(int precision, Instant instan
...
+            checkArgument(picosOfMilli == 0, "Expected picosOfMilli to be 0 for precision %s: %s", precision, picosOfMilli);
+            checkArgument(round(epochMillis, 3 - precision) == epochMillis, "Expected 0s for digits beyond precision %s: epochMicros = %s", precision, epochMillis);
+        }
+        else {
+            checkArgument(round(picosOfMilli, 12 - precision) == picosOfMilli, "Expected 0s for digits beyond precision %s: picosOfMilli = %s", precision, picosOfMilli);
+        }
+
+        if (picosOfMilli < 0 || picosOfMilli > PICOSECONDS_PER_MILLISECOND) {
+            throw new IllegalArgumentException("picosOfMilli is out of range: " + picosOfMilli);
+        }
```
Comment (findepi) [inline presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestampWithTimeZone.java:61]: This could use `checkArgument` too

File: presto-spi/src/test/java/io/prestosql/spi/type/TestSqlTimestamp.java [hunk 13]
```diff
@@ -40,78 +40,6 @@ public void testBaseline()
...
-    {
-        // round down
-        // represents a timestamp of 1970-01-01 00:00:00.111111111111
-        assertThat(newInstance(0, 111111, 111111).toString()).isEqualTo("1970-01-01 00:00:00");
-        assertThat(newInstance(1, 111111, 111111).toString()).isEqualTo("1970-01-01 00:00:00.1");
-        assertThat(newInstance(2, 111111, 111111).toString()).isEqualTo("1970-01-01 00:00:00.11");
-        assertThat(newInstance(3, 111111, 111111).toString()).isEqualTo("1970-01-01 00:00:00.111");
-        assertThat(newInstance(4, 111111, 111111).toString()).isEqualTo("1970-01-01 00:00:00.1111");
-        assertThat(newInstance(5, 111111, 111111).toString()).isEqualTo("1970-01-01 00:00:00.11111");
-        assertThat(newInstance(6, 111111, 111111).toString()).isEqualTo("1970-01-01 00:00:00.111111");
```
Comment (findepi) [inline presto-spi/src/test/java/io/prestosql/spi/type/TestSqlTimestamp.java:54]: This deletion is part `Make construction of SqlTimestamp and SqlTimestampWithTimeZone stricter` commit.
Would it mnake sense toi keep the test, replacing `newInstance` with `newInstanceWithRounding` here?

File: presto-main/src/main/java/io/prestosql/testing/DateTimeTestingUtils.java (hunk 10 above)
Comment (martint) [reply presto-main/src/main/java/io/prestosql/testing/DateTimeTestingUtils.java:67]: The new code is actually correct. It works because of the line above. `epochMillis` is computed by taking into account `nanoOfSecond / NANOSECONDS_PER_MILLISECOND`. The remainder is stored in `picosOfMilli`.

It would actually be clearer to do it the other way around. I'll update it.

```java
long epochMillis = base.toEpochSecond() * MILLISECONDS_PER_SECOND + nanoOfSecond / NANOSECONDS_PER_MILLISECOND;
int picosOfMilli = (nanoOfSecond % NANOSECONDS_PER_MILLISECOND) * PICOSECONDS_PER_NANOSECOND;
```

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java (hunk 11 above)
Comment (findepi) [reply presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:57]: Same reasoning either applies or doesn't apply to other checks above, right?

File: presto-spi/src/test/java/io/prestosql/spi/type/TestSqlTimestamp.java (hunk 13 above)
Comment (findepi) [reply presto-spi/src/test/java/io/prestosql/spi/type/TestSqlTimestamp.java:54]: you can make `newInstanceWithRounding` package private, visiblefortesting

anyway, up to you

File: presto-main/src/main/java/io/prestosql/testing/DateTimeTestingUtils.java (hunk 10 above)
Comment (findepi) [reply presto-main/src/main/java/io/prestosql/testing/DateTimeTestingUtils.java]: yeah, that's so clear that even i can understand. thanks

File: presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java (hunk 11 above)
Comment (martint) [reply presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:57]: Yes, you're right. For some reason, I was thinking that they were in a conditional that was only evaluated sometimes, but that's obviously not the case. I'll revert the changes

Comment (martint) [reply presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java:57]: Yes, you're right. For some reason, I was thinking that they were in a conditional that was only evaluated sometimes, but that's obviously not the case. I'll revert the changes
