### PR TITLE
Suppress NoSuchFileException in LocalFileIterator

### LINKED ISSUE #20520: Flaky TestIcebergConnectorSmokeTest.testCreateSchema
```sh
Error:    TestIcebergConnectorSmokeTest>BaseConnectorSmokeTest.testCreateSchema:375->AbstractTestQueryFramework.query:328->AbstractTestQueryFramework.query:333 » QueryFailed Error listing schemas for catalog iceberg: /tmp/TrinoTest6237267186906259759/iceberg_data/tpch/test_insert_nvkpm1973w-6c4e049ef0a444009e5e33fa88e4cc83/metadata/snap-4179595911964093228-1-30594bc6-b09b-4fbd-9666-12d340604c33.avro
```
https://github.com/trinodb/trino/actions/runs/7722012293/job/21049575309

We can reproduce the failure by:
```java
    @RepeatedTest(100)
    void test()
    {
        testCreateSchema();
        testInsert();
    }
```

https://github.com/trinodb/trino/blob/f61cb5a53298f36c23c3dd60c65f74d0d608afd3/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java#L321-L329

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Files.walk method may throw an exception during the iteration. https://bugs.openjdk.org/browse/JDK-8039910
Fixes #20520

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

File: lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileIterator.java [hunk 1]
```diff
@@ -46,16 +48,29 @@ public LocalFileIterator(Location location, Path rootPath, Path path)
...
+                    }
+                    return FileVisitResult.CONTINUE;
+                }
+
+                @Override
+                public FileVisitResult visitFileFailed(Path file, IOException e)
+                        throws IOException
+                {
+                    if (e instanceof NoSuchFileException) {
+                        return FileVisitResult.CONTINUE;
```
Comment (findepi) [inline lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileIterator.java:68]: worth documenting why?

**Review by findepi — APPROVED** [review]

**Comment by dain** [comment]
Please get @electrum  to review this before merging.  The exact behavior of exceptions from the file system implementations is required to be consistent, and I'd like david to make sure this is following the expected behavior.

**Review by electrum — CHANGES_REQUESTED** [review]
The Javadoc for `listFiles()` says

> If the location does not exist, an empty iterator is returned.

> For hierarchical file systems, if the path is not a directory, an exception is raised.

The expectation is that it only throws in the above case, or if there is a network error or similar. We should never see `NoSuchFileException` in `FileHiveMetastore` for `listFiles()`. If we do, that's a bug in the file system implementation.

**Comment by electrum** [comment]
So I believe that the first commit is correct and the second commit is not needed.

**Comment by ebyhr** [comment]
@electrum Both commits are required to fix the concurrent issue. `LocalFileIterator#next` calls `Files.size(path)`. It throws NoSuchFileException if the file is deleted concurrently.

**Comment by electrum** [comment]
Thanks for explaining. We should change `LocalFileIterator` to ignore those exceptions by not returning the file entry. Listing files is not atomic, so this is an expected race condition that we need to handle.

**Comment by findinpath** [comment]
> We should change LocalFileIterator to ignore those exceptions by not returning the file entry.

@ebyhr did you consider making use of a simplified version of `java.nio.file.Files#walkFileTree(java.nio.file.Path, java.util.Set<java.nio.file.FileVisitOption>, int, java.nio.file.FileVisitor<? super java.nio.file.Path>)` (what `Files.walkFileTree` uses in the background) and create the `FileEntry` instances on the fly in the `LocalFileIterator`?

File: lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileIterator.java [hunk 2]
```diff
@@ -13,49 +13,73 @@
...
+                @Override
+                public FileVisitResult visitFile(Path file, BasicFileAttributes attributes)
+                        throws IOException
+                {
+                    if (Files.isRegularFile(file)) {
+                        if (!file.startsWith(rootPath)) {
+                            throw new IOException("entry is not inside of filesystem root");
+                        }
+
+                        files.add(new FileEntry(
```
Comment (findinpath) [inline lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileIterator.java:62]: The current approach may have the downside that between the time when the `FileEntry` gets created and when it gets visited it may be modified/deleted.
As long as this is used for testing I find this approach good enough.

Otherwise, pls consider investigating the strategy exposed in https://github.com/trinodb/trino/pull/20526#issuecomment-1946119026

Comment (ebyhr) [reply lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileIterator.java:62]: I can't understand https://github.com/trinodb/trino/pull/20526#issuecomment-1946119026. Can you elaborate on that?

Comment (findinpath) [reply lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileIterator.java:62]: I'm implying to use a (potentially) simplified version of the algorithm https://github.com/openjdk/jdk/blob/18cea823a173e1b8b48d276daeca67b2a5cf3584/src/java.base/share/classes/java/nio/file/Files.java#L2798-L2848 based on `FileTreeWalker` which basically acts like an iterator.

Comment (findinpath) [reply lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileIterator.java:62]: Thnank you for the hint @ebyhr .

Given that `FileTreeWalker` is a package-private tests and that `LocalFileIterator` is used only for test purposes - I consider that the downside of collecting early the files to list acceptable.

**Review by findinpath — APPROVED** [review]

**Review by electrum — APPROVED** [review]
