### PR TITLE
retry to connect to hive metastore with new delegation token.

### LINKED ISSUE #10534: Suggestions : Hive Metastore Delegation-Token Authentication Failure
### Situation
I figured out that the delegation-token of the hive metastore server (HMS) is created and the cached token is implemented to continuously access until the time of the `hive.metastore.thrift.delegation-token.cache-ttl` option among the hive connecter options.
​
As a result, when the hive metastore server (HMS) is restarted, it was confirmed that an authentication error occurred because trino continuously accesses the cached token.

When an error occurs, the following error occurs.

### Error Message
error code : https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java#L2051
```
io.trino.spi.TrinoException: Failed connecting to Hive metastore: [a-server:9083, b-server:9083, c-server:9083]
	at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.getTable(ThriftHiveMetastore.java:357)
	at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.getTable(BridgingHiveMetastore.java:96)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:322)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:259)
	at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getTable(CachingHiveMetastore.java:311)
	at io.trino.plugin.hive.HiveMetastoreClosure.getTable(HiveMetastoreClosure.java:76)
	at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getTable(SemiTransactionalHiveMetastore.java:206)
	at io.trino.plugin.hive.HiveMetadata.getView(HiveMetadata.java:2040)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getView(ClassLoaderSafeConnectorMetadata.java:535)
	at io.trino.metadata.MetadataManager.getView(MetadataManager.java:1132)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1229)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:343)
	at io.trino.sql.tree.Table.accept(Table.java:53)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:360)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2770)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1589)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:343)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:360)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:370)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1075)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:343)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:360)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:323)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:263)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:186)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:768)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:129)
	at io.trino.$gen.Trino_353____20210517_084257_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

### Suggestions
Since cached tokens may expire, such as restarting Hive Metastore, I think it would be better to retry by renewing the token in case of access failure with the cached token.

So I suggest modifying the logic as below.

```java
    private ThriftMetastoreClient createMetastoreClient(HiveIdentity identity)
            throws TException
    {
        if (!impersonationEnabled) {
            return createMetastoreClient();
        }

        String username = identity.getUsername().orElseThrow(() -> new IllegalStateException("End-user name should exist when metastore impersonation is enabled"));
        if (authenticationEnabled) {
            try {
                return createMetastoreClientWithAuthentication(username, false);
            }
            catch (TException e) {
                log.debug("It may be a delegation token permission failure, so try again with a new delegation token, exception message : %s", e.getMessage());
                return createMetastoreClientWithAuthentication(username, true);
            }
        }

        ThriftMetastoreClient client = createMetastoreClient();
        setMetastoreUserOrClose(client, username);
        return client;
    }

    private ThriftMetastoreClient createMetastoreClientWithAuthentication(String username, boolean refresh)
            throws TException
    {
        if (refresh) {
            delegationTokenCache.refresh(username);
        }
        String delegationToken;
        try {
            delegationToken = delegationTokenCache.getUnchecked(username);
        }
        catch (UncheckedExecutionException e) {
            throwIfInstanceOf(e.getCause(), TrinoException.class);
            throw e;
        }
        return clientProvider.createMetastoreClient(Optional.of(delegationToken));
    }
```

### PR DESCRIPTION
**Pull request by Sunwoo-Shin**
Fixes #10534

### CODE REVIEW

**Comment by Sunwoo-Shin** [comment]
> Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please submit the signed CLA to cla@trino.io. For more information, see https://github.com/trinodb/cla.

CLA had sent to cla@trino.io
( Sent Email: sunwoo.shin@navercorp.com )

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java [hunk 1]
```diff
@@ -2040,22 +2040,37 @@ private ThriftMetastoreClient createMetastoreClient(HiveIdentity identity)
...
         ThriftMetastoreClient client = createMetastoreClient();
         setMetastoreUserOrClose(client, username);
         return client;
     }
 
+    private ThriftMetastoreClient createMetastoreClientWithAuthentication(String username, boolean refresh)
+        throws TException
+    {
+        if (refresh) {
+            delegationTokenCache.refresh(username);
```
Comment (findepi) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java:2061]: refresh might be async (under what conditions?). it should be simpler to `invalidate`, but this would be vulnerable to https://github.com/trinodb/trino/issues/10512 / https://github.com/google/guava/issues/1881.

cc @kokosing

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java [hunk 2]
```diff
@@ -2040,22 +2040,37 @@ private ThriftMetastoreClient createMetastoreClient(HiveIdentity identity)
...
             }
-            return clientProvider.createMetastoreClient(Optional.of(delegationToken));
         }
 
         ThriftMetastoreClient client = createMetastoreClient();
         setMetastoreUserOrClose(client, username);
         return client;
     }
 
+    private ThriftMetastoreClient createMetastoreClientWithAuthentication(String username, boolean refresh)
```
Comment (findepi) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java:2057]: Extract:

```java
 private String getDelegationToken(String username)
    {
        String delegationToken;
        try {
            delegationToken = delegationTokenCache.getUnchecked(username);
        }
        catch (UncheckedExecutionException e) {
            throwIfInstanceOf(e.getCause(), TrinoException.class);
            throw e;
        }
        return delegationToken;
    }
```

and inline this back:
```java
        if (authenticationEnabled) {
            try {
                return clientProvider.createMetastoreClient(Optional.of(getDelegationToken(username)));
            }
            catch (TException e) {
                log.debug(e, "It may be a delegation token permission failure, so try again with a new delegation token");
                delegationTokenCache.refresh(username);
                return clientProvider.createMetastoreClient(Optional.of(getDelegationToken(username)));
            }
        }
```

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java (hunk 1 above)
Comment (kokosing) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java:2061]: I think we should not use `refresh`. It makes it hard to reason about the current state. Notice that we don't know if below `getUnchecked` would return new or old value.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java (hunk 2 above)
Comment (Sunwoo-Shin) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java]: modified in that way. please check again.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java (hunk 1 above)
Comment (Sunwoo-Shin) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java]: With the link below, it was confirmed that `refresh` function works as async. Therefore, it has been modified from `refresh` function to `put` function.

* https://github.com/google/guava/blob/master/guava/src/com/google/common/cache/LocalCache.java#L2364

**Comment by ebyhr** [comment]
@cla-bot check

**Comment by mosabua** [comment]
:wave: @Sunwoo-Shin - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that. As a first step you would need to rebase.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by Sunwoo-Shin** [comment]
@mosabua 
Thanks for noticing. I was missing this PR.
now rebase is complete.
It was confirmed that the logic was changed from the `ThriftHiveMetastore` class to the `TokenFetchingMetastoreClientFactory` class, and I modified it accordingly.

cc. @findepi

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java [hunk 3]
```diff
@@ -70,15 +73,25 @@ public ThriftMetastoreClient createMetastoreClientFor(Optional<ConnectorIdentity
         String username = identity.map(ConnectorIdentity::getUser)
                 .orElseThrow(() -> new IllegalStateException("End-user name should exist when metastore impersonation is enabled"));
 
-        String delegationToken;
         try {
-            delegationToken = delegationTokenCache.getUnchecked(username);
+            return clientProvider.createMetastoreClient(Optional.of(getDelegationToken(username)));
+        }
+        catch (TException e) {
+            log.debug(e, "It may be a delegation token permission failure, so try again with a new delegation token");
```
Comment (losipiuk) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java:80]: I do not think we need this log here. Trino will not be run with `debug` log level enabled anyway and the log message does not provide any actionable information..

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java [hunk 4]
```diff
@@ -70,15 +73,25 @@ public ThriftMetastoreClient createMetastoreClientFor(Optional<ConnectorIdentity
         String username = identity.map(ConnectorIdentity::getUser)
                 .orElseThrow(() -> new IllegalStateException("End-user name should exist when metastore impersonation is enabled"));
 
-        String delegationToken;
         try {
-            delegationToken = delegationTokenCache.getUnchecked(username);
+            return clientProvider.createMetastoreClient(Optional.of(getDelegationToken(username)));
+        }
+        catch (TException e) {
```
Comment (losipiuk) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java:79]: can we be look deeper into exception to determine if regenerating delegatin token can really be helpful?

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java [hunk 5]
```diff
@@ -70,15 +73,25 @@ public ThriftMetastoreClient createMetastoreClientFor(Optional<ConnectorIdentity
...
+            log.debug(e, "It may be a delegation token permission failure, so try again with a new delegation token");
+            delegationTokenCache.put(username, loadDelegationToken(username));
+            return clientProvider.createMetastoreClient(Optional.of(getDelegationToken(username)));
```
Comment (losipiuk) [inline plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java:82]: you can store the delegation token obtained from `loadDelegationToken(username))` on variable; put it in the cache and then use it here without going through cache

Comment (Sunwoo-Shin) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java]: Thank for giving feedbacks :)
changed it to be reused as a local variable.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java (hunk 3 above)
Comment (Sunwoo-Shin) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java]: Thank for giving feedbacks :)
I also agree with what you said. this log has been removed.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java (hunk 4 above)
Comment (Sunwoo-Shin) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java:76]: An exception is occurring as below.
#### Trino Error (402 version)
스크린샷 2022-11-08 오후 12 29 12

#### Hive Metastore Error (3.1.2 version)
스크린샷 2022-11-08 오후 12 32 48

Comment (losipiuk) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java:76]: Maybe sth like that
```java
    @Override
    public ThriftMetastoreClient createMetastoreClientFor(Optional<ConnectorIdentity> identity)
            throws TException
    {
        if (!impersonationEnabled) {
            return createMetastoreClient();
        }

        String username = identity.map(ConnectorIdentity::getUser)
                .orElseThrow(() -> new IllegalStateException("End-user name should exist when metastore impersonation is enabled"));

        try {
            return clientProvider.createMetastoreClient(Optional.of(getDelegationToken(username)));
        }
        catch (TException e) {
            if (isDelegationTokenExpiration(e)) {
                // try once again with new token
                String delegationToken = loadDelegationToken(username);
                delegationTokenCache.put(username, delegationToken);
                return clientProvider.createMetastoreClient(Optional.of(delegationToken));
            }
            throw e;
        }
    }

    private boolean isDelegationTokenExpiration(Throwable exception)
    {
        if (exception instanceof SecretManager.InvalidToken) {
            return true;
        }
        if (exception.getCause() == null || exception.getCause() == exception) {
            return false;
        }
        return (isDelegationTokenExpiration(exception.getCause()));
    }

```

**Review by losipiuk — COMMENTED** [review]
Please squash commits and make commit message:

```
Regenerate Hive delegation token when expired
```

**Comment by Sunwoo-Shin** [comment]
@losipiuk 
> Please squash commits and make commit message:
Regenerate Hive delegation token when expired

squash commit and modified it with the written message.

File: plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java (hunk 4 above)
Comment (Sunwoo-Shin) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java:76]: Unfortunately, the message passed to the thrift response cannot be identified as `SecretManager.InvalidToken` because it is transmitted only with the following string information.

* [TSaslTransport](https://github.com/apache/thrift/blob/e8353cb46e9f5e71f9b76f55d6bf59530b7f98ef/lib/java/src/main/java/org/apache/thrift/transport/TSaslTransport.java#L164-L167)
스크린샷 2022-11-09 오전 1 50 43

Comment (losipiuk) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java:76]: Oh - I misread your previous message. The "cause" does not make it through the "TTransportException".  :/

Comment (losipiuk) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java:76]: Ok - let's go with that. Just please add a comment in `catch` clause why are you reloading the token.

Comment (Sunwoo-Shin) [reply plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java:80]: > Just please add a comment in catch clause why are you reloading the token.

Added a comment to that.

> Also please add a code which ensures that we are not refreshing the token "too often", I think ensuring at most 1 refresh per minute will be fine. We do not want to start hammering metastore which returns errors, because it is overloaded with twice as many requests.

I also positively agree with that.
Since tokens are generated for each user and each expires, the refresh period check is implemented to be checked for each user.

**Review by phd3 — APPROVED** [review]
lgtm

**Comment by losipiuk** [comment]
THanks.
I squashed the commits. Made record definition private, and added null check. WIll merge when CI passes.

**Comment by Chaho12** [comment]
CI failed :'(

**Comment by ebyhr** [comment]
Both failures are unrelated to this change as far as I confirmed.

**Comment by losipiuk** [comment]
> THanks.
> I squashed the commits. Made record definition private, and added null check. WIll merge when CI passes.

And I totally forgot 🤦 . Sorry

**Comment by colebow** [comment]
@Sunwoo-Shin @losipiuk does this need a release note?

**Comment by losipiuk** [comment]
> @Sunwoo-Shin @losipiuk does this need a release note?

@colebow maybe sth like:
```
Refresh the Hive metastore delegation token to prevent query failures if the metastore was restarted mid-query.
```
