### PR TITLE
Disallow creating Delta tables partitioned by array, map or row type

### LINKED ISSUE #18352: Disallow creating Delta tables partitioned by array, map and row types
Both OSS Delta and Databricks don't support creating such tables.
Currently, the connector can create and insert into the tables, but SELECT query fails. 

https://github.com/delta-io/delta/blob/dc061f7b5b47ffb4cf980b445d85100690bedf05/spark/src/main/scala/org/apache/spark/sql/delta/util/PartitionUtils.scala#L595-L609

### PR DESCRIPTION
**Pull request by ebyhr**
## Description

Fixes #18352

## Release notes

(x) This is not user-visible or docs only and no release notes are required.

### CODE REVIEW

File: testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java [hunk 1]
```diff
@@ -248,4 +249,36 @@ public void testReplaceTableWithSchemaChangeOnCheckpoint()
             dropDeltaTableWithRetry(tableName);
         }
     }
+
```
Comment (findepi) [inline testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java:252]: add a test outside of product tests (delta connector test?)

**Review by findepi — APPROVED** [review]

**Comment by ebyhr** [comment]
I will send another PR for `DROP COLUMN` statement.
