### PR TITLE
Fix MAP and ARRAY flat write

### LINKED ISSUE #18863: Queries Failed on trino 425 : `map keys cannot be null` (GENERIC_INTERNAL_ERROR)
While changing trino version from 423 to 425, some of queries failed with `map keys cannot be null` exception.

Our query format looks like below. It happens when distinct `map<varchar, varchar>` table join query.
```sql
WITH WITH_1 (  
  SELECT
    DISTINCT 
    a, 
    b, 
    map_value -- map<varchar, varchar>
  FROM
    TABLE_1
)
SELECT
  WITH_1.a, WITH_1.b, TABLE_2.c
FROM
  TABLE_2
  JOIN WITH_1
  ON TABLE_2.a = WITH_1.a
  AND TABLE_2.b = WITH_1.b
```

```
java.lang.IllegalArgumentException: map keys cannot be null
	at io.trino.spi.block.MapHashTables.getHashPosition(MapHashTables.java:260)
	at io.trino.spi.block.MapHashTables.buildHashTableInternal(MapHashTables.java:139)
	at io.trino.spi.block.MapHashTables.buildHashTable(MapHashTables.java:130)
	at io.trino.spi.block.MapBlockBuilder.buildEntry(MapBlockBuilder.java:203)
	at io.trino.spi.type.MapType.readFlatToBlock(MapType.java:547)
	at io.trino.spi.type.ArrayType.readFlatElements(ArrayType.java:404)
	at io.trino.spi.type.ArrayType.lambda$readFlatToBlock$2(ArrayType.java:392)
	at io.trino.spi.block.ArrayBlockBuilder.buildEntry(ArrayBlockBuilder.java:158)
	at io.trino.spi.type.ArrayType.readFlatToBlock(ArrayType.java:391)
	at io.trino.spi.type.MapType.readFlatEntries(MapType.java:593)
	at io.trino.spi.type.MapType.lambda$readFlatToBlock$2(MapType.java:548)
	at io.trino.spi.block.MapBlockBuilder.buildEntry(MapBlockBuilder.java:194)
	at io.trino.spi.type.MapType.readFlatToBlock(MapType.java:547)
	at io.trino.spi.type.ArrayType.readFlatElements(ArrayType.java:404)
	at io.trino.spi.type.ArrayType.readFlat(ArrayType.java:376)
	at io.trino.operator.FlatHashStrategy.valueNotDistinctFrom(FlatHashStrategy.java:254)
	at io.trino.operator.FlatHash.valueNotDistinctFrom(FlatHash.java:448)
	at io.trino.operator.FlatHash.matchInVector(FlatHash.java:241)
	at io.trino.operator.FlatHash.getIndex(FlatHash.java:221)
	at io.trino.operator.FlatHash.putIfAbsent(FlatHash.java:197)
	at io.trino.operator.FlatGroupByHash.putIfAbsent(FlatGroupByHash.java:173)
	at io.trino.operator.FlatGroupByHash$AddNonDictionaryPageWork.process(FlatGroupByHash.java:315)
	at io.trino.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:444)
	at io.trino.operator.Driver.processInternal(Driver.java:400)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
	at io.trino.operator.Driver.tryWithLock(Driver.java:694)
	at io.trino.operator.Driver.process(Driver.java:290)
	at io.trino.operator.Driver.processForDuration(Driver.java:261)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
	at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
	at io.trino.$gen.Trino_425____20230829_225615_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by dain**
## Description

The MAP and ARRAY types were incorrectly adjusting the pointer for the variable width data by the fixed width size of the type.  Since the variable width and fixed with data are kept in different sections of the flat record, the adjustment is not needed and causes failures.

Fixes #18863

## Release notes

(X) Release notes are required, with the following suggested text:

```markdown
# Section
* Fix index out of bounds exceptions in flat memory data structures using MAP and ARRAY types. ({issue}`18863`)
```

### CODE REVIEW

File: core/trino-spi/src/main/java/io/trino/spi/type/RowType.java [hunk 1]
```diff
@@ -134,6 +136,15 @@ private RowType(TypeSignature typeSignature, List<Field> originalFields)
 
         this.comparable = fields.stream().allMatch(field -> field.getType().isComparable());
         this.orderable = fields.stream().allMatch(field -> field.getType().isOrderable());
+
+        // flat fixed size is one null byte for each field plus the sum field fixed sizes
+        int fixedSize = fieldTypes.size();
+        for (Type fieldType : fieldTypes) {
+            fixedSize += fieldType.getFlatFixedSize() + 4;
```
Comment (martint) [inline core/trino-spi/src/main/java/io/trino/spi/type/RowType.java:143]: Where does the `4` come from? "one null byte" should be 1, no?

File: core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java [hunk 2]
```diff
@@ -320,21 +320,22 @@ public int relocateFlatVariableWidthOffsets(byte[] fixedSizeSlice, int fixedSize
 
     private int relocateVariableWidthData(int positionCount, int elementFixedSize, byte[] slice, int offset)
     {
-        int writeVariableWidthOffset = positionCount * (1 + elementFixedSize);
+        int writeFixedOffset = offset;
+        int writeVariableWidthOffset = offset + positionCount * (1 + elementFixedSize);
```
Comment (martint) [inline core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java:346]: Is the `1` for the null flag? Add a comment to clarify.

File: core/trino-spi/src/main/java/io/trino/spi/type/MapType.java [hunk 3]
```diff
@@ -387,33 +387,34 @@ public int relocateFlatVariableWidthOffsets(byte[] fixedSizeSlice, int fixedSize
 
     private int relocateVariableWidthData(int positionCount, int keyFixedSize, int valueFixedSize, byte[] slice, int offset)
     {
-        int writeVariableWidthOffset = positionCount / 2 * (2 + keyFixedSize + valueFixedSize);
+        int writeFixedOffset = offset;
+        int writeVariableWidthOffset = offset + (positionCount / 2 * (2 + keyFixedSize + valueFixedSize));
```
Comment (martint) [inline core/trino-spi/src/main/java/io/trino/spi/type/MapType.java:414]: I know it's pre-existing, but it's not clear where this formula comes from.

Also, why does it divide before multiplying? If positionCount is odd, it will round down before the multiplication happens. Is that intended?

File: core/trino-spi/src/main/java/io/trino/spi/type/RowType.java (hunk 1 above)
Comment (electrum) [reply core/trino-spi/src/main/java/io/trino/spi/type/RowType.java:143]: Same question, though the calculation is copied from below

File: core/trino-spi/src/main/java/io/trino/spi/type/MapType.java [hunk 4]
```diff
@@ -334,6 +334,29 @@ public void writeObject(BlockBuilder blockBuilder, Object value)
         });
     }
 
+    // FLAT MEMORY LAYOUT
+    //
+    // All data of the map is stored in the variable width section. Within the variable width section,
+    // fixed data for all keys and value is stored first, followed by variable length data for all keys
```
Comment (electrum) [inline core/trino-spi/src/main/java/io/trino/spi/type/MapType.java:340]: "all keys and values are stored first"

File: core/trino-spi/src/main/java/io/trino/spi/type/RowType.java [hunk 5]
```diff
@@ -134,6 +136,15 @@ private RowType(TypeSignature typeSignature, List<Field> originalFields)
 
         this.comparable = fields.stream().allMatch(field -> field.getType().isComparable());
         this.orderable = fields.stream().allMatch(field -> field.getType().isOrderable());
+
+        // flat fixed size is one null byte for each field plus the sum field fixed sizes
```
Comment (electrum) [inline core/trino-spi/src/main/java/io/trino/spi/type/RowType.java:140]: Did you mean

> flat fixed size is one null byte for each field plus the sum of the field fixed sizes

**Review by electrum — APPROVED** [review]
