### PR TITLE
Fix handing of grouped ordered aggregations with filtering

### LINKED ISSUE #13449: Get Null Pointer Exception in some queries doing array_agg
Hi team,
Some of the queries with array_agg are failing with null pointer exception, stack trace given below.

Whats more weird is that if we run the query with more resources (num of workers and worker memory), it runs fine.

Version -: Reproducible in `v391` 

Stack Trace -:
```
java.lang.NullPointerException: Cannot load from short array because "this.array[io.trino.array.BigArrays.segment(long)]" is null
	at io.trino.array.ShortBigArray.get(ShortBigArray.java:74)
	at io.trino.operator.aggregation.AbstractGroupCollectionAggregationState.isEmpty(AbstractGroupCollectionAggregationState.java:173)
	at io.trino.operator.aggregation.arrayagg.ArrayAggregationFunction.output(ArrayAggregationFunction.java:61)
	at io.trino.$gen.array_aggGroupedAccumulator_20220801_055623_81.evaluateFinal(Unknown Source)
	at io.trino.operator.aggregation.OrderedAccumulatorFactory$OrderingGroupedAccumulator.evaluateFinal(OrderedAccumulatorFactory.java:232)
	at io.trino.operator.aggregation.GroupedAggregator.evaluate(GroupedAggregator.java:96)
	at io.trino.operator.aggregation.builder.InMemoryHashAggregationBuilder.lambda$buildResult$2(InMemoryHashAggregationBuilder.java:289)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:391)
	at io.trino.operator.HashAggregationOperator.getOutput(HashAggregationOperator.java:509)
	at io.trino.operator.Driver.processInternal(Driver.java:410)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:313)
	at io.trino.operator.Driver.tryWithLock(Driver.java:698)
	at io.trino.operator.Driver.process(Driver.java:305)
	at io.trino.operator.Driver.processForDuration(Driver.java:276)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:740)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_391_2_g5fb3da2____20220801_052834_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Diff Stat from our internal build -:
``` 
.gitlab-ci.yml  | 151 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ci-build.sh    |  32 +++++++++++++++++++++++++
 ci-release.sh  |  26 ++++++++++++++++++++
 pom.xml        |   1 +
```

Please let me know if I can contribute somehow.

### PR DESCRIPTION
**Pull request by dain**
When a grouped ordered aggregation input is completely filtered, the underlying aggregation must still be informed of the empty groups.

## Related issues, pull requests, and links

* Fixes #13449

## Documentation

(X) No documentation is needed.
( ) Sufficient documentation is included in this PR.
( ) Documentation PR is available with #prnumber.
( ) Documentation issue #issuenumber is filed, and can be handled later.

## Release notes

( ) No release notes entries required.
(X) Release notes entries required with the following suggested text:

```markdown
# General
* Fix some failure of queries with grouped aggregations that are ordered and filtered. ({issue}`issuenumber`)
```

### CODE REVIEW

File: core/trino-main/src/test/java/io/trino/sql/query/TestOrderedAggregation.java [hunk 1]
```diff
@@ -167,4 +167,31 @@ public void testRepeatedSortItems()
...
     }
+
+    @Test
+    public void testCompletelyFilteredGroup()
+    {
+        // This query filters out all values to a most groups, which results in an accumulator with no pages to sort.
+        // This can cause a failure if the ordering code does not inform the accumulator of the max row group.
+        assertThat(assertions.query("" +
+                "select count(id) > 15000, sum(cardinality(v))" +
+                "from (" +
```
Comment (findepi) [inline core/trino-main/src/test/java/io/trino/sql/query/TestOrderedAggregation.java:178]: add a space

```suggestion
                "select count(id) > 15000, sum(cardinality(v)) " +
                "from (" +
```

so that `from` is separated from `sum(cardinality(v))`


also, can you please uppercase the sql keywords?

File: core/trino-main/src/main/java/io/trino/operator/aggregation/OrderedAccumulatorFactory.java [hunk 2]
```diff
@@ -211,7 +211,16 @@ public void addInput(GroupByIdBlock groupIdsBlock, Page page, Optional<Block> ma
             if (mask.isPresent()) {
                 page = filter(page, mask.orElseThrow());
             }
-            pagesIndex.addPage(page);
+            if (page.getPositionCount() == 0) {
```
Comment (sopel39) [inline core/trino-main/src/main/java/io/trino/operator/aggregation/OrderedAccumulatorFactory.java:214]: the same seems to be required for `DistinctAccumulator`

**Review by sopel39 — APPROVED** [review]

File: core/trino-main/src/main/java/io/trino/operator/aggregation/OrderedAccumulatorFactory.java (hunk 2 above)
Comment (dain) [reply core/trino-main/src/main/java/io/trino/operator/aggregation/OrderedAccumulatorFactory.java:214]: Good catch.  I looked at DistinctAccumulator also, and missed the place where it skips input

Comment (dain) [reply core/trino-main/src/main/java/io/trino/operator/aggregation/OrderedAccumulatorFactory.java:214]: The existing distinct code is correct, but I added a test to verify that we don't introduce this bug in that code (also, I verified the test catches the bug if we change the code).  I also added a comment to the distinct code to remind people about the issue
